PACS System: kcenon::pacs::services::mpps_scu Class Reference
kcenon::pacs::services::mpps_scu Class Reference
#include <mpps_scu.h>
Public Member Functions
mpps_scu (std::shared_ptr< di::ILogger > logger=nullptr)
Construct MPPS SCU with default configuration.
mpps_scu (const mpps_scu_config &config, std::shared_ptr< di::ILogger > logger=nullptr)
Construct MPPS SCU with custom configuration.
~mpps_scu ()=default
mpps_scu (const mpps_scu &)=delete
mpps_scu & operator= (const mpps_scu &)=delete
mpps_scu (mpps_scu &&)=delete
mpps_scu & operator= (mpps_scu &&)=delete
network::Result< mpps_result > create (network::association &assoc, const mpps_create_data &data)
Create a new MPPS instance (N-CREATE)
network::Result< mpps_result > set (network::association &assoc, const mpps_set_data &data)
Update an existing MPPS instance (N-SET)
network::Result< mpps_result > complete (network::association &assoc, std::string_view mpps_uid, const std::vector< performed_series_info > &performed_series)
Complete an MPPS instance (convenience method)
network::Result< mpps_result > discontinue (network::association &assoc, std::string_view mpps_uid, std::string_view reason="")
Discontinue an MPPS instance (convenience method)
size_t creates_performed () const noexcept
Get the number of N-CREATE operations performed.
size_t sets_performed () const noexcept
Get the number of N-SET operations performed.
void reset_statistics () noexcept
Reset statistics counters to zero.
Private Member Functions
core::dicom_dataset build_create_dataset (const mpps_create_data &data) const
Build DICOM dataset for N-CREATE request.
core::dicom_dataset build_set_dataset (const mpps_set_data &data) const
Build DICOM dataset for N-SET request.
std::string generate_mpps_uid () const
Generate a unique MPPS SOP Instance UID.
std::string get_current_date () const
Get current date in DICOM DA format (YYYYMMDD)
std::string get_current_time () const
Get current time in DICOM TM format (HHMMSS)
uint16_t next_message_id () noexcept
Get the next message ID for DIMSE operations.
Private Attributes
std::shared_ptr< di::ILogger > logger_
Logger instance.
mpps_scu_config config_
Configuration.
std::atomic< uint16_t > message_id_counter_ {1}
Message ID counter.
std::atomic< size_t > creates_performed_ {0}
Statistics: N-CREATE operations performed.
std::atomic< size_t > sets_performed_ {0}
Statistics: N-SET operations performed.
Detailed Description
Examples
mpps_scu/main.cpp.
Definition at line 254 of file mpps_scu.h.
Constructor & Destructor Documentation
mpps_scu() [1/4]
kcenon::pacs::services::mpps_scu::mpps_scu (std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct MPPS SCU with default configuration.
Parameters
logger Logger instance for service logging (nullptr uses null_logger)
Definition at line 86 of file mpps_scu.cpp.
    : logger_(logger ? std::move(logger) : di::null_logger()) {}
mpps_scu() [2/4]
kcenon::pacs::services::mpps_scu::mpps_scu (const mpps_scu_config & config, std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct MPPS SCU with custom configuration.
Parameters
config Configuration options
logger Logger instance for service logging (nullptr uses null_logger)
Definition at line 89 of file mpps_scu.cpp.
    : logger_(logger ? std::move(logger) : di::null_logger()),
      config_(config) {}
~mpps_scu()
kcenon::pacs::services::mpps_scu::~mpps_scu () default
mpps_scu() [3/4]
kcenon::pacs::services::mpps_scu::mpps_scu (const mpps_scu &) delete
mpps_scu() [4/4]
kcenon::pacs::services::mpps_scu::mpps_scu (mpps_scu &&) delete
Member Function Documentation
build_create_dataset()
core::dicom_dataset kcenon::pacs::services::mpps_scu::build_create_dataset (const mpps_create_data & data) const nodiscard private
Build DICOM dataset for N-CREATE request.
Definition at line 350 of file mpps_scu.cpp.
{
    using namespace core;
    using namespace encoding;
    dicom_dataset ds;
    // Performed Procedure Step Status - always IN PROGRESS for N-CREATE
    ds.set_string(mpps_tags::performed_procedure_step_status, vr_type::CS, "IN PROGRESS");
    // Performed Procedure Step Timing
    std::string start_date = data.procedure_step_start_date.empty()
        ? get_current_date() : data.procedure_step_start_date;
    std::string start_time = data.procedure_step_start_time.empty()
        ? get_current_time() : data.procedure_step_start_time;
    ds.set_string(mpps_tags::performed_procedure_step_start_date, vr_type::DA, start_date);
    ds.set_string(mpps_tags::performed_procedure_step_start_time, vr_type::TM, start_time);
    // Modality and Station
    if (!data.modality.empty()) {
        ds.set_string(tags::modality, vr_type::CS, data.modality);
    }
    if (!data.station_ae_title.empty()) {
        ds.set_string(mpps_tags::performed_station_ae_title, vr_type::AE, data.station_ae_title);
    }
    if (!data.station_name.empty()) {
        ds.set_string(mpps_tags::performed_station_name, vr_type::SH, data.station_name);
    }
    // Procedure Step ID
    if (!data.scheduled_procedure_step_id.empty()) {
        ds.set_string(mpps_tags::performed_procedure_step_id, vr_type::SH,
                      data.scheduled_procedure_step_id);
    }
    // Procedure Description
    if (!data.procedure_description.empty()) {
        ds.set_string(mpps_tags::performed_procedure_step_description, vr_type::LO,
                      data.procedure_description);
    }
    // Patient Information (required)
    std::string patient_name = data.patient_name.empty() ? "ANONYMOUS" : data.patient_name;
    ds.set_string(tags::patient_name, vr_type::PN, patient_name);
    if (!data.patient_id.empty()) {
        ds.set_string(tags::patient_id, vr_type::LO, data.patient_id);
    }
    if (!data.patient_birth_date.empty()) {
        ds.set_string(tags::patient_birth_date, vr_type::DA, data.patient_birth_date);
    }
    if (!data.patient_sex.empty()) {
        ds.set_string(tags::patient_sex, vr_type::CS, data.patient_sex);
    }
    // Study reference
    if (!data.study_instance_uid.empty()) {
        ds.set_string(tags::study_instance_uid, vr_type::UI, data.study_instance_uid);
    }
    if (!data.accession_number.empty()) {
        ds.set_string(tags::accession_number, vr_type::SH, data.accession_number);
    }
    // Performing Information
    if (!data.performing_physician.empty()) {
        ds.set_string(mpps_tags::performing_physicians_name, vr_type::PN,
                      data.performing_physician);
    }
    if (!data.operator_name.empty()) {
        ds.set_string(mpps_tags::operators_name, vr_type::PN, data.operator_name);
    }
    return ds;
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::services::mpps_create_data::accession_number, get_current_date(), get_current_time(), kcenon::pacs::core::tags::modality, kcenon::pacs::services::mpps_create_data::modality, kcenon::pacs::services::mpps_create_data::operator_name, kcenon::pacs::services::mpps_tags::operators_name, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::services::mpps_create_data::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::services::mpps_create_data::patient_id, kcenon::pacs::core::tags::patient_name, kcenon::pacs::services::mpps_create_data::patient_name, kcenon::pacs::core::tags::patient_sex, kcenon::pacs::services::mpps_create_data::patient_sex, kcenon::pacs::services::mpps_tags::performed_procedure_step_description, kcenon::pacs::services::mpps_tags::performed_procedure_step_id, kcenon::pacs::services::mpps_tags::performed_procedure_step_start_date, kcenon::pacs::services::mpps_tags::performed_procedure_step_start_time, kcenon::pacs::services::mpps_tags::performed_procedure_step_status, kcenon::pacs::services::mpps_tags::performed_station_ae_title, kcenon::pacs::services::mpps_tags::performed_station_name, kcenon::pacs::services::mpps_create_data::performing_physician, kcenon::pacs::services::mpps_tags::performing_physicians_name, kcenon::pacs::services::mpps_create_data::procedure_description, kcenon::pacs::services::mpps_create_data::procedure_step_start_date, kcenon::pacs::services::mpps_create_data::procedure_step_start_time, kcenon::pacs::services::mpps_create_data::scheduled_procedure_step_id, kcenon::pacs::services::mpps_create_data::station_ae_title, kcenon::pacs::services::mpps_create_data::station_name, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::services::mpps_create_data::study_instance_uid.
Referenced by create().
build_set_dataset()
core::dicom_dataset kcenon::pacs::services::mpps_scu::build_set_dataset (const mpps_set_data & data) const nodiscard private
Build DICOM dataset for N-SET request.
Definition at line 425 of file mpps_scu.cpp.
{
    using namespace core;
    using namespace encoding;
    dicom_dataset ds;
    // Update status
    ds.set_string(mpps_tags::performed_procedure_step_status, vr_type::CS,
                  std::string(to_string(data.status)));
    // End date/time
    std::string end_date = data.procedure_step_end_date.empty()
        ? get_current_date() : data.procedure_step_end_date;
    std::string end_time = data.procedure_step_end_time.empty()
        ? get_current_time() : data.procedure_step_end_time;
    ds.set_string(mpps_tags::performed_procedure_step_end_date, vr_type::DA, end_date);
    ds.set_string(mpps_tags::performed_procedure_step_end_time, vr_type::TM, end_time);
    // Add performed series sequence for COMPLETED status
    if (data.status == mpps_status::completed && !data.performed_series.empty()) {
        auto& seq = ds.get_or_create_sequence(mpps_tags::performed_series_sequence);
        for (const auto& s : data.performed_series) {
            dicom_dataset series_item;
            if (!s.series_uid.empty()) {
                series_item.set_string(tags::series_instance_uid, vr_type::UI, s.series_uid);
            }
            if (!s.series_description.empty()) {
                series_item.set_string(mpps_tags::series_description, vr_type::LO,
                                       s.series_description);
            }
            if (!s.modality.empty()) {
                series_item.set_string(tags::modality, vr_type::CS, s.modality);
            }
            if (!s.performing_physician.empty()) {
                series_item.set_string(mpps_tags::performing_physicians_name, vr_type::PN,
                                       s.performing_physician);
            }
            if (!s.operator_name.empty()) {
                series_item.set_string(mpps_tags::operators_name, vr_type::PN, s.operator_name);
            }
            seq.push_back(std::move(series_item));
        }
    }
    return ds;
}
References kcenon::pacs::services::completed, get_current_date(), get_current_time(), kcenon::pacs::core::tags::modality, kcenon::pacs::services::mpps_tags::operators_name, kcenon::pacs::services::mpps_tags::performed_procedure_step_end_date, kcenon::pacs::services::mpps_tags::performed_procedure_step_end_time, kcenon::pacs::services::mpps_tags::performed_procedure_step_status, kcenon::pacs::services::mpps_set_data::performed_series, kcenon::pacs::services::mpps_tags::performed_series_sequence, kcenon::pacs::services::mpps_tags::performing_physicians_name, kcenon::pacs::services::mpps_set_data::procedure_step_end_date, kcenon::pacs::services::mpps_set_data::procedure_step_end_time, kcenon::pacs::services::mpps_tags::series_description, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::services::mpps_set_data::status, and kcenon::pacs::services::to_string().
Referenced by set().
complete()
network::Result< mpps_result > kcenon::pacs::services::mpps_scu::complete (network::association & assoc, std::string_view mpps_uid, const std::vector< performed_series_info > & performed_series) nodiscard
Complete an MPPS instance (convenience method)
Updates the MPPS to COMPLETED status with performed series information. Automatically fills in current date/time for end timestamps.
Parameters
assoc The established association to use
mpps_uid The MPPS SOP Instance UID
performed_series Information about performed series
Returns
Result containing mpps_result on success, or error message
Examples
mpps_scu/main.cpp.
Definition at line 299 of file mpps_scu.cpp.
{
    mpps_set_data data;
    data.mpps_sop_instance_uid = std::string(mpps_uid);
    data.status = mpps_status::completed;
    data.procedure_step_end_date = get_current_date();
    data.procedure_step_end_time = get_current_time();
    data.performed_series = performed_series;
    return set(assoc, data);
}
References kcenon::pacs::services::completed, get_current_date(), get_current_time(), kcenon::pacs::services::mpps_set_data::mpps_sop_instance_uid, kcenon::pacs::services::mpps_set_data::performed_series, kcenon::pacs::services::mpps_set_data::procedure_step_end_date, kcenon::pacs::services::mpps_set_data::procedure_step_end_time, set(), and kcenon::pacs::services::mpps_set_data::status.
create()
network::Result< mpps_result > kcenon::pacs::services::mpps_scu::create (network::association & assoc, const mpps_create_data & data) nodiscard
Create a new MPPS instance (N-CREATE)
Starts a new Modality Performed Procedure Step with IN PROGRESS status. If mpps_sop_instance_uid is empty, a unique UID will be auto-generated.
Parameters
assoc The established association to use
data The MPPS creation data
Returns
Result containing mpps_result on success, or error message
Examples
mpps_scu/main.cpp.
Definition at line 98 of file mpps_scu.cpp.
{
    using namespace network::dimse;
    auto start_time = std::chrono::steady_clock::now();
    // Verify association is established
    if (!assoc.is_established()) {
        return kcenon::pacs::pacs_error<mpps_result>(
            kcenon::pacs::error_codes::association_not_established,
            "Association not established");
    }
    // Get accepted presentation context for MPPS
    auto context_id = assoc.accepted_context_id(mpps_sop_class_uid);
    if (!context_id) {
        return kcenon::pacs::pacs_error<mpps_result>(
            kcenon::pacs::error_codes::mpps_context_not_accepted,
            "No accepted presentation context for MPPS SOP Class");
    }
    // Generate or use provided MPPS UID
    std::string mpps_uid = data.mpps_sop_instance_uid;
    if (mpps_uid.empty() && config_.auto_generate_uid) {
        mpps_uid = generate_mpps_uid();
    }
    if (mpps_uid.empty()) {
        return kcenon::pacs::pacs_error<mpps_result>(
            kcenon::pacs::error_codes::mpps_missing_uid,
            "MPPS SOP Instance UID is required");
    }
    // Build the MPPS creation dataset
    auto dataset = build_create_dataset(data);
    // Create the N-CREATE request
    auto request = make_n_create_rq(next_message_id(), mpps_uid, std::move(dataset));
    logger_->debug("Sending N-CREATE request for MPPS: " + mpps_uid);
    // Send the request
    auto send_result = assoc.send_dimse(*context_id, request);
    if (send_result.is_err()) {
        logger_->error("Failed to send N-CREATE: " + send_result.error().message);
        return send_result.error();
    }
    // Receive the response
    auto recv_result = assoc.receive_dimse(config_.timeout);
    if (recv_result.is_err()) {
        logger_->error("Failed to receive N-CREATE response: " + recv_result.error().message);
        return recv_result.error();
    }
    const auto& [recv_context_id, response] = recv_result.value();
    // Verify it's an N-CREATE response
    if (response.command() != command_field::n_create_rsp) {
        return kcenon::pacs::pacs_error<mpps_result>(
            kcenon::pacs::error_codes::mpps_unexpected_command,
            "Expected N-CREATE-RSP but received " +
            std::string(to_string(response.command())));
    }
    auto end_time = std::chrono::steady_clock::now();
    auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
        end_time - start_time);
    // Build result
    mpps_result result;
    result.mpps_sop_instance_uid = mpps_uid;
    result.status = static_cast<uint16_t>(response.status());
    result.elapsed = elapsed;
    // Extract error comment if present
    if (response.command_set().contains(tag_error_comment)) {
        result.error_comment = response.command_set().get_string(tag_error_comment);
    }
    // Update statistics
    creates_performed_.fetch_add(1, std::memory_order_relaxed);
    if (result.is_success()) {
        logger_->info("N-CREATE successful for MPPS: " + mpps_uid);
    } else {
        logger_->warn("N-CREATE returned status 0x" +
                      std::to_string(result.status) + " for MPPS: " + mpps_uid);
    }
    return result;
}
References kcenon::pacs::network::association::accepted_context_id(), kcenon::pacs::error_codes::association_not_established, kcenon::pacs::services::mpps_scu_config::auto_generate_uid, build_create_dataset(), config_, creates_performed_, kcenon::pacs::services::mpps_result::elapsed, kcenon::pacs::services::mpps_result::error_comment, generate_mpps_uid(), kcenon::pacs::network::association::is_established(), kcenon::pacs::services::mpps_result::is_success(), logger_, kcenon::pacs::error_codes::mpps_context_not_accepted, kcenon::pacs::error_codes::mpps_missing_uid, kcenon::pacs::services::mpps_sop_class_uid, kcenon::pacs::services::mpps_create_data::mpps_sop_instance_uid, kcenon::pacs::services::mpps_result::mpps_sop_instance_uid, kcenon::pacs::error_codes::mpps_unexpected_command, next_message_id(), kcenon::pacs::pacs_error(), kcenon::pacs::network::association::receive_dimse(), kcenon::pacs::network::association::send_dimse(), kcenon::pacs::services::mpps_result::status, kcenon::pacs::services::mpps_scu_config::timeout, and kcenon::pacs::services::to_string().
Referenced by operator=().
creates_performed()
size_t kcenon::pacs::services::mpps_scu::creates_performed () const nodiscard noexcept
Get the number of N-CREATE operations performed.
Returns
Count of create operations
Definition at line 333 of file mpps_scu.cpp.
{
    return creates_performed_.load(std::memory_order_relaxed);
}
References creates_performed_.
discontinue()
network::Result< mpps_result > kcenon::pacs::services::mpps_scu::discontinue (network::association & assoc, std::string_view mpps_uid, std::string_view reason = "") nodiscard
Discontinue an MPPS instance (convenience method)
Updates the MPPS to DISCONTINUED status. Automatically fills in current date/time for end timestamps.
Parameters
assoc The established association to use
mpps_uid The MPPS SOP Instance UID
reason Optional discontinuation reason
Returns
Result containing mpps_result on success, or error message
Examples
mpps_scu/main.cpp.
Definition at line 314 of file mpps_scu.cpp.
{
    mpps_set_data data;
    data.mpps_sop_instance_uid = std::string(mpps_uid);
    data.status = mpps_status::discontinued;
    data.procedure_step_end_date = get_current_date();
    data.procedure_step_end_time = get_current_time();
    data.discontinuation_reason = std::string(reason);
    return set(assoc, data);
}
References kcenon::pacs::services::mpps_set_data::discontinuation_reason, kcenon::pacs::services::discontinued, get_current_date(), get_current_time(), kcenon::pacs::services::mpps_set_data::mpps_sop_instance_uid, kcenon::pacs::services::mpps_set_data::procedure_step_end_date, kcenon::pacs::services::mpps_set_data::procedure_step_end_time, set(), and kcenon::pacs::services::mpps_set_data::status.
generate_mpps_uid()
std::string kcenon::pacs::services::mpps_scu::generate_mpps_uid () const nodiscard private
Generate a unique MPPS SOP Instance UID.
Definition at line 479 of file mpps_scu.cpp.
{
    static std::mt19937_64 gen{std::random_device{}()};
    static std::uniform_int_distribution<uint64_t> dist;
    auto now = std::chrono::system_clock::now();
    auto timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(
        now.time_since_epoch()).count();
    return std::string(uid_root) + "." + std::to_string(timestamp) +
           "." + std::to_string(dist(gen) % 100000);
}
Referenced by create().
get_current_date()
std::string kcenon::pacs::services::mpps_scu::get_current_date () const nodiscard private
Get current date in DICOM DA format (YYYYMMDD)
Definition at line 491 of file mpps_scu.cpp.
{
    auto now = std::time(nullptr);
    std::tm tm{};
#if defined(_WIN32)
    localtime_s(&tm, &now);
#else
    localtime_r(&now, &tm);
#endif
    std::ostringstream oss;
    oss << std::put_time(&tm, "%Y%m%d");
    return oss.str();
}
Referenced by build_create_dataset(), build_set_dataset(), complete(), and discontinue().
get_current_time()
std::string kcenon::pacs::services::mpps_scu::get_current_time () const nodiscard private
Get current time in DICOM TM format (HHMMSS)
Definition at line 504 of file mpps_scu.cpp.
{
    auto now = std::time(nullptr);
    std::tm tm{};
#if defined(_WIN32)
    localtime_s(&tm, &now);
#else
    localtime_r(&now, &tm);
#endif
    std::ostringstream oss;
    oss << std::put_time(&tm, "%H%M%S");
    return oss.str();
}
Referenced by build_create_dataset(), build_set_dataset(), complete(), and discontinue().
next_message_id()
uint16_t kcenon::pacs::services::mpps_scu::next_message_id () nodiscard private noexcept
Get the next message ID for DIMSE operations.
Definition at line 517 of file mpps_scu.cpp.
{
    uint16_t id = message_id_counter_.fetch_add(1, std::memory_order_relaxed);
    // Wrap around at 0xFFFF, skip 0 (reserved)
    if (id == 0) {
        id = message_id_counter_.fetch_add(1, std::memory_order_relaxed);
    }
    return id;
}
References message_id_counter_.
Referenced by create(), and set().
operator=() [1/2]
mpps_scu & kcenon::pacs::services::mpps_scu::operator= (const mpps_scu &) delete
operator=() [2/2]
mpps_scu & kcenon::pacs::services::mpps_scu::operator= (mpps_scu &&) delete
References create(), and set().
reset_statistics()
void kcenon::pacs::services::mpps_scu::reset_statistics () noexcept
Reset statistics counters to zero.
Definition at line 341 of file mpps_scu.cpp.
{
    creates_performed_.store(0, std::memory_order_relaxed);
    sets_performed_.store(0, std::memory_order_relaxed);
}
References creates_performed_, and sets_performed_.
set()
network::Result< mpps_result > kcenon::pacs::services::mpps_scu::set (network::association & assoc, const mpps_set_data & data) nodiscard
Update an existing MPPS instance (N-SET)
Updates an MPPS instance to COMPLETED or DISCONTINUED status.
Parameters
assoc The established association to use
data The MPPS update data
Returns
Result containing mpps_result on success, or error message
Definition at line 197 of file mpps_scu.cpp.
{
    using namespace network::dimse;
    auto start_time = std::chrono::steady_clock::now();
    // Verify association is established
    if (!assoc.is_established()) {
        return kcenon::pacs::pacs_error<mpps_result>(
            kcenon::pacs::error_codes::association_not_established,
            "Association not established");
    }
    // Validate MPPS UID is provided
    if (data.mpps_sop_instance_uid.empty()) {
        return kcenon::pacs::pacs_error<mpps_result>(
            kcenon::pacs::error_codes::mpps_missing_uid,
            "MPPS SOP Instance UID is required for N-SET");
    }
    // Validate status is not IN PROGRESS (can only set to COMPLETED or DISCONTINUED)
    if (data.status == mpps_status::in_progress) {
        return kcenon::pacs::pacs_error<mpps_result>(
            kcenon::pacs::error_codes::mpps_invalid_status_transition,
            "Cannot set MPPS status back to IN PROGRESS");
    }
    // Get accepted presentation context for MPPS
    auto context_id = assoc.accepted_context_id(mpps_sop_class_uid);
    if (!context_id) {
        return kcenon::pacs::pacs_error<mpps_result>(
            kcenon::pacs::error_codes::mpps_context_not_accepted,
            "No accepted presentation context for MPPS SOP Class");
    }
    // Build the modification dataset
    auto dataset = build_set_dataset(data);
    // Create the N-SET request
    auto request = make_n_set_rq(
        next_message_id(),
        data.mpps_sop_instance_uid,
        std::move(dataset));
    logger_->debug("Sending N-SET request for MPPS: " + data.mpps_sop_instance_uid);
    // Send the request
    auto send_result = assoc.send_dimse(*context_id, request);
    if (send_result.is_err()) {
        logger_->error("Failed to send N-SET: " + send_result.error().message);
        return send_result.error();
    }
    // Receive the response
    auto recv_result = assoc.receive_dimse(config_.timeout);
    if (recv_result.is_err()) {
        logger_->error("Failed to receive N-SET response: " + recv_result.error().message);
        return recv_result.error();
    }
    const auto& [recv_context_id, response] = recv_result.value();
    // Verify it's an N-SET response
    if (response.command() != command_field::n_set_rsp) {
        return kcenon::pacs::pacs_error<mpps_result>(
            kcenon::pacs::error_codes::mpps_unexpected_command,
            "Expected N-SET-RSP but received " +
            std::string(to_string(response.command())));
    }
    auto end_time = std::chrono::steady_clock::now();
    auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
        end_time - start_time);
    // Build result
    mpps_result result;
    result.mpps_sop_instance_uid = data.mpps_sop_instance_uid;
    result.status = static_cast<uint16_t>(response.status());
    result.elapsed = elapsed;
    // Extract error comment if present
    if (response.command_set().contains(tag_error_comment)) {
        result.error_comment = response.command_set().get_string(tag_error_comment);
    }
    // Update statistics
    sets_performed_.fetch_add(1, std::memory_order_relaxed);
    if (result.is_success()) {
        logger_->info("N-SET successful for MPPS: " + data.mpps_sop_instance_uid +
                      " (status: " + std::string(to_string(data.status)) + ")");
    } else {
        logger_->warn("N-SET returned status 0x" +
                      std::to_string(result.status) + " for MPPS: " +
                      data.mpps_sop_instance_uid);
    }
    return result;
}
References kcenon::pacs::network::association::accepted_context_id(), kcenon::pacs::error_codes::association_not_established, build_set_dataset(), config_, kcenon::pacs::services::mpps_result::elapsed, kcenon::pacs::services::mpps_result::error_comment, kcenon::pacs::services::in_progress, kcenon::pacs::network::association::is_established(), kcenon::pacs::services::mpps_result::is_success(), logger_, kcenon::pacs::error_codes::mpps_context_not_accepted, kcenon::pacs::error_codes::mpps_invalid_status_transition, kcenon::pacs::error_codes::mpps_missing_uid, kcenon::pacs::services::mpps_sop_class_uid, kcenon::pacs::services::mpps_result::mpps_sop_instance_uid, kcenon::pacs::services::mpps_set_data::mpps_sop_instance_uid, kcenon::pacs::error_codes::mpps_unexpected_command, next_message_id(), kcenon::pacs::pacs_error(), kcenon::pacs::network::association::receive_dimse(), kcenon::pacs::network::association::send_dimse(), sets_performed_, kcenon::pacs::services::mpps_result::status, kcenon::pacs::services::mpps_set_data::status, kcenon::pacs::services::mpps_scu_config::timeout, and kcenon::pacs::services::to_string().
Referenced by complete(), discontinue(), and operator=().
sets_performed()
size_t kcenon::pacs::services::mpps_scu::sets_performed () const nodiscard noexcept
Get the number of N-SET operations performed.
Returns
Count of set operations
Definition at line 337 of file mpps_scu.cpp.
{
    return sets_performed_.load(std::memory_order_relaxed);
}
References sets_performed_.
Member Data Documentation
config_
mpps_scu_config kcenon::pacs::services::mpps_scu::config_ private
Configuration.
Definition at line 417 of file mpps_scu.h.
Referenced by create(), and set().
creates_performed_
std::atomic<size_t> kcenon::pacs::services::mpps_scu::creates_performed_ {0} private
Statistics: N-CREATE operations performed.
Definition at line 423 of file mpps_scu.h.
{0};
Referenced by create(), creates_performed(), and reset_statistics().
logger_
std::shared_ptr<di::ILogger> kcenon::pacs::services::mpps_scu::logger_ private
Logger instance.
Definition at line 414 of file mpps_scu.h.
Referenced by create(), and set().
message_id_counter_
std::atomic<uint16_t> kcenon::pacs::services::mpps_scu::message_id_counter_ {1} private
Message ID counter.
Definition at line 420 of file mpps_scu.h.
{1};
Referenced by next_message_id().
sets_performed_
std::atomic<size_t> kcenon::pacs::services::mpps_scu::sets_performed_ {0} private
Statistics: N-SET operations performed.
Definition at line 426 of file mpps_scu.h.
{0};
Referenced by reset_statistics(), set(), and sets_performed().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/mpps_scu.h
src/services/mpps_scu.cpp