PACS System: kcenon::pacs::dcm_modify::uid_mapper Class Reference
kcenon::pacs::dcm_modify::uid_mapper Class Reference
UID mapping for consistent anonymization across related instances.
#include <anonymizer.h>
Public Member Functions
std::string map (const std::string &original_uid)
Get or create a replacement UID for the original UID.
void clear ()
Clear all mappings.
Private Member Functions
std::string generate_uid ()
Private Attributes
std::map< std::string, std::string > mapping_
Static Private Attributes
static constexpr const char * uid_root_ = "1.2.826.0.1.3680043.8.1055.2"
Detailed Description
UID mapping for consistent anonymization across related instances.
Definition at line 31 of file anonymizer.h.
Member Function Documentation
clear()
void kcenon::pacs::dcm_modify::uid_mapper::clear () inline
Clear all mappings.
Definition at line 52 of file anonymizer.h.
                 {
        mapping_.clear();
    }
References mapping_.
generate_uid()
std::string kcenon::pacs::dcm_modify::uid_mapper::generate_uid () inline private
Definition at line 57 of file anonymizer.h.
{
        static std::atomic<uint64_t> counter{0};
        auto now = std::chrono::system_clock::now();
        auto timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(
            now.time_since_epoch()).count();
        return std::string(uid_root_) + "." + std::to_string(timestamp) + "." +
               std::to_string(++counter);
    }
References uid_root_.
Referenced by map().
map()
std::string kcenon::pacs::dcm_modify::uid_mapper::map (const std::string & original_uid) inline
Get or create a replacement UID for the original UID.
Parameters
original_uid The original UID to map
Returns
The replacement UID (consistent for same original)
Definition at line 38 of file anonymizer.h.
{
        auto it = mapping_.find(original_uid);
        if (it != mapping_.end()) {
            return it->second;
        }
        auto new_uid = generate_uid();
        mapping_[original_uid] = new_uid;
        return new_uid;
    }
References generate_uid(), and mapping_.
Referenced by kcenon::pacs::dcm_modify::anonymizer::anonymize_uids().
Member Data Documentation
mapping_
std::map<std::string, std::string> kcenon::pacs::dcm_modify::uid_mapper::mapping_ private
Definition at line 67 of file anonymizer.h.
Referenced by clear(), and map().
uid_root_
const char* kcenon::pacs::dcm_modify::uid_mapper::uid_root_ = "1.2.826.0.1.3680043.8.1055.2" static constexpr private
Definition at line 68 of file anonymizer.h.
Referenced by generate_uid().
The documentation for this class was generated from the following file:
examples/dcm_modify/anonymizer.h