PACS System: kcenon::pacs::services::validation::ophthalmic_iod_validator Class Reference
kcenon::pacs::services::validation::ophthalmic_iod_validator Class Reference
#include <ophthalmic_iod_validator.h>
Public Member Functions
ophthalmic_iod_validator ()=default
Construct validator with default options.
ophthalmic_iod_validator (const ophthalmic_validation_options &options)
Construct validator with custom options.
validation_result validate (const core::dicom_dataset &dataset) const
Validate a DICOM dataset against Ophthalmic IOD.
bool quick_check (const core::dicom_dataset &dataset) const
Quick check if dataset has minimum required ophthalmic attributes.
const ophthalmic_validation_options & options () const noexcept
Get the validation options.
void set_options (const ophthalmic_validation_options &options)
Set validation options.
Private Member Functions
void validate_patient_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_study_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_series_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_ophthalmic_image_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_image_pixel_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_multiframe_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_acquisition_context_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_sop_common_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_type1_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_type2_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_modality (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_laterality (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_pixel_data_consistency (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
Private Attributes
ophthalmic_validation_options options_
Detailed Description
Definition at line 138 of file ophthalmic_iod_validator.h.
Constructor & Destructor Documentation
ophthalmic_iod_validator() [1/2]
kcenon::pacs::services::validation::ophthalmic_iod_validator::ophthalmic_iod_validator () default
Construct validator with default options.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
ophthalmic_iod_validator() [2/2]
kcenon::pacs::services::validation::ophthalmic_iod_validator::ophthalmic_iod_validator (const ophthalmic_validation_options & options) explicit
Construct validator with custom options.
Parameters
options Validation options
Definition at line 26 of file ophthalmic_iod_validator.cpp.
    : options_(options) {}
Member Function Documentation
check_laterality()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::check_laterality (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 397 of file ophthalmic_iod_validator.cpp.
{
    if (!dataset.contains(ophthalmic_iod_tags::image_laterality)) {
        return;  // Already reported as Type 1 missing
    }
    auto laterality =
        dataset.get_string(ophthalmic_iod_tags::image_laterality);
    if (laterality != "R" && laterality != "L" && laterality != "B") {
        findings.push_back(
            {validation_severity::error,
             ophthalmic_iod_tags::image_laterality,
             "ImageLaterality must be 'R' (Right), 'L' (Left), or "
             "'B' (Both), found: " + laterality,
             "OPHTH-ERR-004"});
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), and kcenon::pacs::services::validation::ophthalmic_iod_tags::image_laterality.
Referenced by validate_ophthalmic_image_module().
check_modality()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::check_modality (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 379 of file ophthalmic_iod_validator.cpp.
{
    if (!dataset.contains(tags::modality)) {
        return;  // Already reported as Type 1 missing
    }
    auto modality = dataset.get_string(tags::modality);
    if (modality != "OP" && modality != "OPT") {
        findings.push_back(
            {validation_severity::error, tags::modality,
             "Modality must be 'OP' or 'OPT' for ophthalmic images, "
             "found: " + modality,
             "OPHTH-ERR-003"});
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), and kcenon::pacs::core::tags::modality.
Referenced by validate_general_series_module().
check_pixel_data_consistency()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::check_pixel_data_consistency (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 417 of file ophthalmic_iod_validator.cpp.
{
    // Check BitsStored <= BitsAllocated
    auto bits_allocated =
        dataset.get_numeric<uint16_t>(tags::bits_allocated);
    auto bits_stored = dataset.get_numeric<uint16_t>(tags::bits_stored);
    auto high_bit = dataset.get_numeric<uint16_t>(tags::high_bit);
    if (bits_allocated && bits_stored) {
        if (*bits_stored > *bits_allocated) {
            findings.push_back(
                {validation_severity::error, tags::bits_stored,
                 "BitsStored (" + std::to_string(*bits_stored) +
                     ") exceeds BitsAllocated (" +
                     std::to_string(*bits_allocated) + ")",
                 "OPHTH-ERR-005"});
        }
    }
    // Check HighBit == BitsStored - 1
    if (bits_stored && high_bit) {
        if (*high_bit != *bits_stored - 1) {
            findings.push_back(
                {validation_severity::warning, tags::high_bit,
                 "HighBit (" + std::to_string(*high_bit) +
                     ") should typically be BitsStored - 1 (" +
                     std::to_string(*bits_stored - 1) + ")",
                 "OPHTH-WARN-002"});
        }
    }
    // Validate PhotometricInterpretation for ophthalmic
    if (dataset.contains(tags::photometric_interpretation)) {
        auto photometric =
            dataset.get_string(tags::photometric_interpretation);
        if (!sop_classes::is_valid_ophthalmic_photometric(photometric)) {
            findings.push_back(
                {validation_severity::error,
                 tags::photometric_interpretation,
                 "Ophthalmic images must use MONOCHROME1, MONOCHROME2, "
                 "RGB, YBR_FULL_422, or PALETTE COLOR, found: " + photometric,
                 "OPHTH-ERR-006"});
        }
    }
    // Ophthalmic SamplesPerPixel must be 1 (grayscale) or 3 (color)
    auto samples = dataset.get_numeric<uint16_t>(tags::samples_per_pixel);
    if (samples && *samples != 1 && *samples != 3) {
        findings.push_back(
            {validation_severity::error, tags::samples_per_pixel,
             "Ophthalmic images require SamplesPerPixel of 1 or 3, "
             "found: " + std::to_string(*samples),
             "OPHTH-ERR-007"});
    }
    // Ophthalmic images use unsigned pixel representation
    auto pixel_rep =
        dataset.get_numeric<uint16_t>(tags::pixel_representation);
    if (pixel_rep && *pixel_rep != 0) {
        findings.push_back(
            {validation_severity::warning, tags::pixel_representation,
             "Ophthalmic images typically use unsigned pixel representation "
             "(PixelRepresentation = 0)",
             "OPHTH-WARN-003"});
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_numeric(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::services::sop_classes::is_valid_ophthalmic_photometric(), kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::samples_per_pixel, and kcenon::pacs::services::validation::warning.
Referenced by validate_image_pixel_module().
check_type1_attribute()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::check_type1_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 342 of file ophthalmic_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back(
            {validation_severity::error, tag,
             std::string("Type 1 attribute missing: ") + std::string(name) +
                 " (" + tag.to_string() + ")",
             "OPHTH-TYPE1-MISSING"});
    } else {
        // Type 1 must have a value (cannot be empty)
        auto value = dataset.get_string(tag);
        if (value.empty()) {
            findings.push_back(
                {validation_severity::error, tag,
                 std::string("Type 1 attribute has empty value: ") +
                     std::string(name) + " (" + tag.to_string() + ")",
                 "OPHTH-TYPE1-EMPTY"});
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), name, and kcenon::pacs::core::dicom_tag::to_string().
Referenced by validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_ophthalmic_image_module(), and validate_sop_common_module().
check_type2_attribute()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::check_type2_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 365 of file ophthalmic_iod_validator.cpp.
{
    // Type 2 must be present but can be empty
    if (!dataset.contains(tag)) {
        findings.push_back(
            {validation_severity::warning, tag,
             std::string("Type 2 attribute missing: ") + std::string(name) +
                 " (" + tag.to_string() + ")",
             "OPHTH-TYPE2-MISSING"});
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), name, kcenon::pacs::core::dicom_tag::to_string(), and kcenon::pacs::services::validation::warning.
Referenced by validate_general_series_module(), validate_general_study_module(), and validate_patient_module().
options()
const ophthalmic_validation_options & kcenon::pacs::services::validation::ophthalmic_iod_validator::options () const nodiscard noexcept
Get the validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 107 of file ophthalmic_iod_validator.cpp.
{
    return options_;
}
References options_.
Referenced by set_options().
quick_check()
bool kcenon::pacs::services::validation::ophthalmic_iod_validator::quick_check (const core::dicom_dataset & dataset) const nodiscard
Quick check if dataset has minimum required ophthalmic attributes.
Parameters
dataset The dataset to check
Returns
true if all Type 1 attributes are present
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 73 of file ophthalmic_iod_validator.cpp.
{
    // General Study Module Type 1
    if (!dataset.contains(tags::study_instance_uid)) return false;
    // General Series Module Type 1
    if (!dataset.contains(tags::modality)) return false;
    if (!dataset.contains(tags::series_instance_uid)) return false;
    // Check modality is OP or OPT
    auto modality = dataset.get_string(tags::modality);
    if (modality != "OP" && modality != "OPT") return false;
    // Ophthalmic Image Module Type 1
    if (!dataset.contains(tags::image_type)) return false;
    if (!dataset.contains(ophthalmic_iod_tags::image_laterality)) return false;
    // Image Pixel Module Type 1
    if (!dataset.contains(tags::samples_per_pixel)) return false;
    if (!dataset.contains(tags::photometric_interpretation)) return false;
    if (!dataset.contains(tags::rows)) return false;
    if (!dataset.contains(tags::columns)) return false;
    if (!dataset.contains(tags::bits_allocated)) return false;
    if (!dataset.contains(tags::bits_stored)) return false;
    if (!dataset.contains(tags::high_bit)) return false;
    if (!dataset.contains(tags::pixel_representation)) return false;
    // SOP Common Module Type 1
    if (!dataset.contains(tags::sop_class_uid)) return false;
    if (!dataset.contains(tags::sop_instance_uid)) return false;
    return true;
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::tags::columns, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::services::validation::ophthalmic_iod_tags::image_laterality, kcenon::pacs::core::tags::image_type, kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, and kcenon::pacs::core::tags::study_instance_uid.
Referenced by kcenon::pacs::services::validation::is_valid_ophthalmic_dataset().
set_options()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::set_options (const ophthalmic_validation_options & options)
Set validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 111 of file ophthalmic_iod_validator.cpp.
{
    options_ = options;
}
References options(), and options_.
validate()
validation_result kcenon::pacs::services::validation::ophthalmic_iod_validator::validate (const core::dicom_dataset & dataset) const nodiscard
Validate a DICOM dataset against Ophthalmic IOD.
Parameters
dataset The dataset to validate
Returns
Validation result with all findings
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 30 of file ophthalmic_iod_validator.cpp.
{
    validation_result result;
    result.is_valid = true;
    // Validate mandatory modules (PS3.3 Tables A.39-1 / A.40-1)
    if (options_.check_type1 || options_.check_type2) {
        validate_patient_module(dataset, result.findings);
        validate_general_study_module(dataset, result.findings);
        validate_general_series_module(dataset, result.findings);
        validate_sop_common_module(dataset, result.findings);
    }
    if (options_.validate_ophthalmic_params) {
        validate_ophthalmic_image_module(dataset, result.findings);
    }
    if (options_.validate_pixel_data) {
        validate_image_pixel_module(dataset, result.findings);
    }
    // Multi-frame Module is conditional — applies to OCT images
    if (options_.check_conditional) {
        validate_multiframe_module(dataset, result.findings);
        validate_acquisition_context_module(dataset, result.findings);
    }
    // Determine overall validity
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
        if (options_.strict_mode &&
            finding.severity == validation_severity::warning) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References kcenon::pacs::services::validation::ophthalmic_validation_options::check_conditional, kcenon::pacs::services::validation::ophthalmic_validation_options::check_type1, kcenon::pacs::services::validation::ophthalmic_validation_options::check_type2, kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::services::validation::validation_result::is_valid, options_, kcenon::pacs::services::validation::ophthalmic_validation_options::strict_mode, validate_acquisition_context_module(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_multiframe_module(), validate_ophthalmic_image_module(), kcenon::pacs::services::validation::ophthalmic_validation_options::validate_ophthalmic_params, validate_patient_module(), kcenon::pacs::services::validation::ophthalmic_validation_options::validate_pixel_data, validate_sop_common_module(), and kcenon::pacs::services::validation::warning.
Referenced by kcenon::pacs::services::validation::validate_ophthalmic_iod().
validate_acquisition_context_module()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_acquisition_context_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 298 of file ophthalmic_iod_validator.cpp.
{
    // Acquisition Context Module is mandatory
    if (!dataset.contains(ophthalmic_iod_tags::acquisition_context_sequence)) {
        findings.push_back(
            {validation_severity::info,
             ophthalmic_iod_tags::acquisition_context_sequence,
             "AcquisitionContextSequence (0040,0555) not present - "
             "acquisition context unavailable",
             "OPHTH-INFO-004"});
    }
}
References kcenon::pacs::services::validation::ophthalmic_iod_tags::acquisition_context_sequence, kcenon::pacs::core::dicom_dataset::contains(), and kcenon::pacs::services::validation::info.
Referenced by validate().
validate_general_series_module()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_general_series_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 161 of file ophthalmic_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::modality, "Modality", findings);
        check_type1_attribute(dataset, tags::series_instance_uid,
                              "SeriesInstanceUID", findings);
        // Modality must be "OP" or "OPT"
        check_modality(dataset, findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::series_number, "SeriesNumber",
                              findings);
    }
}
References check_modality(), kcenon::pacs::services::validation::ophthalmic_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::ophthalmic_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::tags::modality, options_, kcenon::pacs::core::tags::series_instance_uid, and kcenon::pacs::core::tags::series_number.
Referenced by validate().
validate_general_study_module()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_general_study_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 137 of file ophthalmic_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::study_instance_uid,
                              "StudyInstanceUID", findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::study_date, "StudyDate",
                              findings);
        check_type2_attribute(dataset, tags::study_time, "StudyTime",
                              findings);
        check_type2_attribute(dataset, tags::referring_physician_name,
                              "ReferringPhysicianName", findings);
        check_type2_attribute(dataset, tags::study_id, "StudyID", findings);
        check_type2_attribute(dataset, tags::accession_number,
                              "AccessionNumber", findings);
    }
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::services::validation::ophthalmic_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::ophthalmic_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::core::tags::study_time.
Referenced by validate().
validate_image_pixel_module()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_image_pixel_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 246 of file ophthalmic_iod_validator.cpp.
{
    // Type 1 attributes
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::samples_per_pixel,
                              "SamplesPerPixel", findings);
        check_type1_attribute(dataset, tags::photometric_interpretation,
                              "PhotometricInterpretation", findings);
        check_type1_attribute(dataset, tags::rows, "Rows", findings);
        check_type1_attribute(dataset, tags::columns, "Columns", findings);
        check_type1_attribute(dataset, tags::bits_allocated, "BitsAllocated",
                              findings);
        check_type1_attribute(dataset, tags::bits_stored, "BitsStored",
                              findings);
        check_type1_attribute(dataset, tags::high_bit, "HighBit", findings);
        check_type1_attribute(dataset, tags::pixel_representation,
                              "PixelRepresentation", findings);
    }
    // Validate pixel data consistency
    if (options_.validate_pixel_data) {
        check_pixel_data_consistency(dataset, findings);
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, check_pixel_data_consistency(), kcenon::pacs::services::validation::ophthalmic_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::tags::columns, kcenon::pacs::core::tags::high_bit, options_, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, and kcenon::pacs::services::validation::ophthalmic_validation_options::validate_pixel_data.
Referenced by validate().
validate_multiframe_module()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_multiframe_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 273 of file ophthalmic_iod_validator.cpp.
{
    // Multi-frame Module is conditional — required for OCT images
    if (!dataset.contains(tags::sop_class_uid)) return;
    auto sop_class = dataset.get_string(tags::sop_class_uid);
    bool is_oct =
        (sop_class == sop_classes::ophthalmic_tomography_storage_uid ||
         sop_class == sop_classes::ophthalmic_oct_bscan_analysis_storage_uid);
    if (is_oct) {
        // NumberOfFrames is Type 1 for OCT multi-frame
        if (!dataset.contains(ophthalmic_iod_tags::number_of_frames)) {
            findings.push_back(
                {validation_severity::error,
                 ophthalmic_iod_tags::number_of_frames,
                 "NumberOfFrames (0028,0008) required for OCT multi-frame "
                 "images",
                 "OPHTH-ERR-001"});
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::ophthalmic_iod_tags::number_of_frames, kcenon::pacs::services::sop_classes::ophthalmic_oct_bscan_analysis_storage_uid, kcenon::pacs::services::sop_classes::ophthalmic_tomography_storage_uid, and kcenon::pacs::core::tags::sop_class_uid.
Referenced by validate().
validate_ophthalmic_image_module()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_ophthalmic_image_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 182 of file ophthalmic_iod_validator.cpp.
{
    // ImageType is Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::image_type, "ImageType",
                              findings);
    }
    // Image Laterality is Type 1 — must be R, L, or B
    if (options_.validate_laterality) {
        check_type1_attribute(dataset, ophthalmic_iod_tags::image_laterality,
                              "ImageLaterality", findings);
        check_laterality(dataset, findings);
    }
    // Informational checks for ophthalmic-specific attributes
    if (options_.check_conditional) {
        // Anatomic Region Sequence — Type 1 for ophthalmic
        if (!dataset.contains(
                ophthalmic_iod_tags::anatomic_region_sequence)) {
            findings.push_back(
                {validation_severity::warning,
                 ophthalmic_iod_tags::anatomic_region_sequence,
                 "AnatomicRegionSequence (0008,2218) missing - anatomic "
                 "region unspecified",
                 "OPHTH-WARN-001"});
        }
        // Acquisition Device Type Code Sequence — Type 2
        if (!dataset.contains(
                ophthalmic_iod_tags::acquisition_device_type_code_sequence)) {
            findings.push_back(
                {validation_severity::info,
                 ophthalmic_iod_tags::acquisition_device_type_code_sequence,
                 "AcquisitionDeviceTypeCodeSequence (0022,0015) not present "
                 "- device type unavailable",
                 "OPHTH-INFO-001"});
        }
        // Horizontal Field of View — Type 2C
        if (!dataset.contains(
                ophthalmic_iod_tags::horizontal_field_of_view)) {
            findings.push_back(
                {validation_severity::info,
                 ophthalmic_iod_tags::horizontal_field_of_view,
                 "HorizontalFieldOfView (0022,000C) not present - field of "
                 "view unavailable",
                 "OPHTH-INFO-002"});
        }
        // Pupil Dilated — Type 2C
        if (!dataset.contains(ophthalmic_iod_tags::pupil_dilated)) {
            findings.push_back(
                {validation_severity::info,
                 ophthalmic_iod_tags::pupil_dilated,
                 "PupilDilated (0022,000D) not present - pupil dilation "
                 "status unknown",
                 "OPHTH-INFO-003"});
        }
    }
}
References kcenon::pacs::services::validation::ophthalmic_iod_tags::acquisition_device_type_code_sequence, kcenon::pacs::services::validation::ophthalmic_iod_tags::anatomic_region_sequence, kcenon::pacs::services::validation::ophthalmic_validation_options::check_conditional, check_laterality(), kcenon::pacs::services::validation::ophthalmic_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::ophthalmic_iod_tags::horizontal_field_of_view, kcenon::pacs::services::validation::ophthalmic_iod_tags::image_laterality, kcenon::pacs::core::tags::image_type, kcenon::pacs::services::validation::info, options_, kcenon::pacs::services::validation::ophthalmic_iod_tags::pupil_dilated, kcenon::pacs::services::validation::ophthalmic_validation_options::validate_laterality, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_patient_module()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_patient_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 120 of file ophthalmic_iod_validator.cpp.
{
    // Patient Module - All attributes are Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::patient_name, "PatientName",
                              findings);
        check_type2_attribute(dataset, tags::patient_id, "PatientID",
                              findings);
        check_type2_attribute(dataset, tags::patient_birth_date,
                              "PatientBirthDate", findings);
        check_type2_attribute(dataset, tags::patient_sex, "PatientSex",
                              findings);
    }
}
References kcenon::pacs::services::validation::ophthalmic_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, and kcenon::pacs::core::tags::patient_sex.
Referenced by validate().
validate_sop_common_module()
void kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_sop_common_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 313 of file ophthalmic_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::sop_class_uid, "SOPClassUID",
                              findings);
        check_type1_attribute(dataset, tags::sop_instance_uid,
                              "SOPInstanceUID", findings);
    }
    // Validate SOP Class UID is an ophthalmic storage class
    if (dataset.contains(tags::sop_class_uid)) {
        auto sop_class = dataset.get_string(tags::sop_class_uid);
        if (!sop_classes::is_ophthalmic_storage_sop_class(sop_class)) {
            findings.push_back(
                {validation_severity::error, tags::sop_class_uid,
                 "SOPClassUID is not a recognized Ophthalmic Storage SOP "
                 "Class: " + sop_class,
                 "OPHTH-ERR-002"});
        }
    }
}
References kcenon::pacs::services::validation::ophthalmic_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_ophthalmic_storage_sop_class(), options_, kcenon::pacs::core::tags::sop_class_uid, and kcenon::pacs::core::tags::sop_instance_uid.
Referenced by validate().
Member Data Documentation
options_
ophthalmic_validation_options kcenon::pacs::services::validation::ophthalmic_iod_validator::options_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 237 of file ophthalmic_iod_validator.h.
Referenced by options(), set_options(), validate(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_ophthalmic_image_module(), validate_patient_module(), and validate_sop_common_module().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h
src/services/validation/ophthalmic_iod_validator.cpp