PACS System: kcenon::pacs::ai::assessment_creator Class Reference
kcenon::pacs::ai::assessment_creator Class Reference
#include <aira_assessment.h>
Public Member Functions
assessment_creator ()=default
assessment_creation_result create_assessment (const ai_assessment &assessment) const
Create an assessment SR document for an AI result.
Static Public Member Functions
static std::string assessment_type_to_code (assessment_type type)
Convert assessment_type to DICOM coded value.
static std::string assessment_type_to_meaning (assessment_type type)
Convert assessment_type to human-readable meaning.
static std::string status_to_completion_flag (assessment_status status)
Convert assessment_status to DICOM completion flag value.
Private Member Functions
void build_patient_module (core::dicom_dataset &sr, const ai_assessment &assessment) const
void build_sr_content (core::dicom_dataset &sr, const ai_assessment &assessment) const
void build_referenced_sop_sequence (core::dicom_dataset &sr, const ai_assessment &assessment) const
std::string generate_uid () const
Detailed Description
Definition at line 210 of file aira_assessment.h.
Constructor & Destructor Documentation
assessment_creator()
kcenon::pacs::ai::assessment_creator::assessment_creator () default
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/ai/aira_assessment.h.
Member Function Documentation
assessment_type_to_code()
std::string kcenon::pacs::ai::assessment_creator::assessment_type_to_code (assessment_type type) static nodiscard
Convert assessment_type to DICOM coded value.
Parameters
type Assessment type
Returns
Coded string representation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/ai/aira_assessment.h.
Definition at line 330 of file aira_assessment.cpp.
{
    switch (type) {
    case assessment_type::accept: return "AIRA-ACCEPT";
    case assessment_type::modify: return "AIRA-MODIFY";
    case assessment_type::reject: return "AIRA-REJECT";
    }
    return "AIRA-ACCEPT";
}
References kcenon::pacs::ai::accept, kcenon::pacs::ai::modify, and kcenon::pacs::ai::reject.
Referenced by build_sr_content().
assessment_type_to_meaning()
std::string kcenon::pacs::ai::assessment_creator::assessment_type_to_meaning (assessment_type type) static nodiscard
Convert assessment_type to human-readable meaning.
Parameters
type Assessment type
Returns
Display string
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/ai/aira_assessment.h.
Definition at line 339 of file aira_assessment.cpp.
{
    switch (type) {
    case assessment_type::accept: return "AI Result Accepted";
    case assessment_type::modify: return "AI Result Modified";
    case assessment_type::reject: return "AI Result Rejected";
    }
    return "AI Result Accepted";
}
References kcenon::pacs::ai::accept, kcenon::pacs::ai::modify, and kcenon::pacs::ai::reject.
Referenced by build_sr_content().
build_patient_module()
void kcenon::pacs::ai::assessment_creator::build_patient_module (core::dicom_dataset & sr, const ai_assessment & assessment) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/ai/aira_assessment.h.
Definition at line 162 of file aira_assessment.cpp.
{
    sr.set_string(tags::patient_name, vr_type::PN, "");
    sr.set_string(tags::patient_id, vr_type::LO, "");
    sr.set_string(tags::patient_birth_date, vr_type::DA, "");
    sr.set_string(tags::patient_sex, vr_type::CS, "");
}
References kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, and kcenon::pacs::core::tags::patient_sex.
Referenced by create_assessment().
build_referenced_sop_sequence()
void kcenon::pacs::ai::assessment_creator::build_referenced_sop_sequence (core::dicom_dataset & sr, const ai_assessment & assessment) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/ai/aira_assessment.h.
Definition at line 282 of file aira_assessment.cpp.
{
    std::vector<dicom_dataset> ref_items;
    // Reference to the assessed AI result
    dicom_dataset ref_item;
    ref_item.set_string(aira_tags::referenced_sop_class_uid, vr_type::UI,
                        assessment.ai_result.sop_class_uid);
    ref_item.set_string(aira_tags::referenced_sop_instance_uid, vr_type::UI,
                        assessment.ai_result.sop_instance_uid);
    ref_items.push_back(std::move(ref_item));
    // Reference to modified result (if applicable)
    if (assessment.type == assessment_type::modify &&
        assessment.modification &&
        assessment.modification->modified_result_uid) {
        dicom_dataset mod_ref;
        mod_ref.set_string(aira_tags::referenced_sop_class_uid, vr_type::UI,
                           assessment.modification->modified_result_class_uid
                               .value_or(assessment.ai_result.sop_class_uid));
        mod_ref.set_string(aira_tags::referenced_sop_instance_uid, vr_type::UI,
                           assessment.modification->modified_result_uid.value());
        ref_items.push_back(std::move(mod_ref));
    }
    insert_sequence(sr, aira_tags::referenced_sop_sequence,
                    std::move(ref_items));
}
References kcenon::pacs::ai::ai_assessment::ai_result, kcenon::pacs::ai::ai_assessment::modification, kcenon::pacs::ai::modify, kcenon::pacs::ai::aira_tags::referenced_sop_class_uid, kcenon::pacs::ai::aira_tags::referenced_sop_instance_uid, kcenon::pacs::ai::aira_tags::referenced_sop_sequence, kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::ai::assessed_result_reference::sop_class_uid, kcenon::pacs::ai::assessed_result_reference::sop_instance_uid, and kcenon::pacs::ai::ai_assessment::type.
Referenced by create_assessment().
build_sr_content()
void kcenon::pacs::ai::assessment_creator::build_sr_content (core::dicom_dataset & sr, const ai_assessment & assessment) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/ai/aira_assessment.h.
Definition at line 172 of file aira_assessment.cpp.
{
    // Root content: CONTAINER
    sr.set_string(aira_tags::value_type, vr_type::CS, "CONTAINER");
    // Concept Name: AI Result Assessment (custom code)
    auto concept_name = make_code_item(
        "AIRA-001", "99PACS", "AI Result Assessment");
    insert_sequence(sr, aira_tags::concept_name_code_sequence, {concept_name});
    // Content Template Sequence (IHE AIRA assessment template)
    dicom_dataset template_item;
    template_item.set_string(aira_tags::template_identifier, vr_type::CS,
                             "AIRA");
    template_item.set_string(aira_tags::mapping_resource, vr_type::CS, "99PACS");
    insert_sequence(sr, aira_tags::content_template_sequence, {template_item});
    // Content Sequence items
    std::vector<dicom_dataset> content_items;
    // Item 1: Assessment Type (CODE)
    {
        dicom_dataset item;
        item.set_string(aira_tags::relationship_type, vr_type::CS, "CONTAINS");
        item.set_string(aira_tags::value_type, vr_type::CS, "CODE");
        auto name = make_code_item("AIRA-010", "99PACS", "Assessment Decision");
        insert_sequence(item, aira_tags::concept_name_code_sequence, {name});
        auto value = make_code_item(
            assessment_type_to_code(assessment.type),
            "99PACS",
            assessment_type_to_meaning(assessment.type));
        // Concept Code Sequence (0040,A168) for CODE value type
        constexpr dicom_tag concept_code_sequence{0x0040, 0xA168};
        insert_sequence(item, concept_code_sequence, {value});
        content_items.push_back(std::move(item));
    }
    // Item 2: Assessor (PNAME)
    {
        dicom_dataset item;
        item.set_string(aira_tags::relationship_type, vr_type::CS, "HAS OBS CONTEXT");
        item.set_string(aira_tags::value_type, vr_type::CS, "PNAME");
        auto name = make_code_item("AIRA-020", "99PACS", "Assessor");
        insert_sequence(item, aira_tags::concept_name_code_sequence, {name});
        constexpr dicom_tag person_name{0x0040, 0xA123};
        item.set_string(person_name, vr_type::PN, assessment.assessor_name);
        content_items.push_back(std::move(item));
    }
    // Item 3: Comment (TEXT, optional)
    if (assessment.comment && !assessment.comment->empty()) {
        dicom_dataset item;
        item.set_string(aira_tags::relationship_type, vr_type::CS, "CONTAINS");
        item.set_string(aira_tags::value_type, vr_type::CS, "TEXT");
        auto name = make_code_item("AIRA-030", "99PACS", "Assessment Comment");
        insert_sequence(item, aira_tags::concept_name_code_sequence, {name});
        item.set_string(aira_tags::text_value, vr_type::UT,
                        assessment.comment.value());
        content_items.push_back(std::move(item));
    }
    // Item 4: Modification description (TEXT, only for modify type)
    if (assessment.type == assessment_type::modify && assessment.modification) {
        dicom_dataset item;
        item.set_string(aira_tags::relationship_type, vr_type::CS, "CONTAINS");
        item.set_string(aira_tags::value_type, vr_type::CS, "TEXT");
        auto name = make_code_item("AIRA-040", "99PACS",
                                   "Modification Description");
        insert_sequence(item, aira_tags::concept_name_code_sequence, {name});
        item.set_string(aira_tags::text_value, vr_type::UT,
                        assessment.modification->description);
        content_items.push_back(std::move(item));
    }
    // Item 5: Rejection reason (CODE, only for reject type)
    if (assessment.type == assessment_type::reject && assessment.rejection) {
        dicom_dataset item;
        item.set_string(aira_tags::relationship_type, vr_type::CS, "CONTAINS");
        item.set_string(aira_tags::value_type, vr_type::CS, "CODE");
        auto name = make_code_item("AIRA-050", "99PACS", "Rejection Reason");
        insert_sequence(item, aira_tags::concept_name_code_sequence, {name});
        auto value = make_code_item(
            assessment.rejection->reason_code,
            assessment.rejection->reason_scheme,
            assessment.rejection->reason_description);
        constexpr dicom_tag concept_code_sequence{0x0040, 0xA168};
        insert_sequence(item, concept_code_sequence, {value});
        content_items.push_back(std::move(item));
    }
    insert_sequence(sr, aira_tags::content_sequence, std::move(content_items));
}
References assessment_type_to_code(), assessment_type_to_meaning(), kcenon::pacs::ai::ai_assessment::assessor_name, kcenon::pacs::ai::ai_assessment::comment, kcenon::pacs::ai::aira_tags::concept_name_code_sequence, kcenon::pacs::ai::aira_tags::content_sequence, kcenon::pacs::ai::aira_tags::content_template_sequence, kcenon::pacs::ai::aira_tags::mapping_resource, kcenon::pacs::ai::ai_assessment::modification, kcenon::pacs::ai::modify, name, kcenon::pacs::ai::reject, kcenon::pacs::ai::ai_assessment::rejection, kcenon::pacs::ai::aira_tags::relationship_type, kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::ai::aira_tags::template_identifier, kcenon::pacs::ai::aira_tags::text_value, kcenon::pacs::ai::ai_assessment::type, and kcenon::pacs::ai::aira_tags::value_type.
Referenced by create_assessment().
create_assessment()
assessment_creation_result kcenon::pacs::ai::assessment_creator::create_assessment (const ai_assessment & assessment) const nodiscard
Create an assessment SR document for an AI result.
Parameters
assessment The assessment data
Returns
Creation result with the SR dataset
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/ai/aira_assessment.h.
Definition at line 98 of file aira_assessment.cpp.
{
    assessment_creation_result result;
    // Validate required fields
    if (assessment.ai_result.sop_instance_uid.empty()) {
        result.error_message = "AI result SOP Instance UID is required";
        return result;
    }
    if (assessment.assessor_name.empty()) {
        result.error_message = "Assessor name is required";
        return result;
    }
    core::dicom_dataset sr;
    // --- SOP Common Module ---
    sr.set_string(tags::sop_class_uid, vr_type::UI,
                  "1.2.840.10008.5.1.4.1.1.88.22");  // Enhanced SR
    result.assessment_uid = generate_uid();
    sr.set_string(tags::sop_instance_uid, vr_type::UI, result.assessment_uid);
    // --- Patient Module (Type 2 - empty if not provided) ---
    build_patient_module(sr, assessment);
    // --- General Study Module ---
    sr.set_string(tags::study_instance_uid, vr_type::UI,
                  assessment.ai_result.study_instance_uid);
    sr.set_string(tags::study_date, vr_type::DA, current_date());
    sr.set_string(tags::study_time, vr_type::TM, current_time());
    sr.set_string(tags::referring_physician_name, vr_type::PN, "");
    sr.set_string(tags::study_id, vr_type::SH, "");
    sr.set_string(tags::accession_number, vr_type::SH, "");
    // --- General Series Module ---
    sr.set_string(tags::modality, vr_type::CS, "SR");
    sr.set_string(tags::series_instance_uid, vr_type::UI, generate_uid());
    sr.set_string(tags::series_number, vr_type::IS, "1");
    // --- General Equipment Module ---
    sr.set_string(dicom_tag{0x0008, 0x0070}, vr_type::LO, "");  // Manufacturer
    // --- SR Document General Module ---
    sr.set_string(tags::instance_number, vr_type::IS, "1");
    sr.set_string(tags::content_date, vr_type::DA, current_date());
    sr.set_string(tags::content_time, vr_type::TM, current_time());
    sr.set_string(aira_tags::completion_flag, vr_type::CS,
                  status_to_completion_flag(assessment.status));
    sr.set_string(aira_tags::verification_flag, vr_type::CS, "UNVERIFIED");
    // --- SR Document Content Module ---
    build_sr_content(sr, assessment);
    // --- Referenced SOP Sequence ---
    build_referenced_sop_sequence(sr, assessment);
    result.success = true;
    result.sr_dataset = std::move(sr);
    return result;
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::ai::ai_assessment::ai_result, kcenon::pacs::ai::assessment_creation_result::assessment_uid, kcenon::pacs::ai::ai_assessment::assessor_name, build_patient_module(), build_referenced_sop_sequence(), build_sr_content(), kcenon::pacs::ai::aira_tags::completion_flag, kcenon::pacs::core::tags::content_date, kcenon::pacs::core::tags::content_time, kcenon::pacs::ai::assessment_creation_result::error_message, generate_uid(), kcenon::pacs::core::tags::instance_number, kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::series_number, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::ai::assessed_result_reference::sop_instance_uid, kcenon::pacs::core::tags::sop_instance_uid, kcenon::pacs::ai::assessment_creation_result::sr_dataset, kcenon::pacs::ai::ai_assessment::status, status_to_completion_flag(), kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_id, kcenon::pacs::ai::assessed_result_reference::study_instance_uid, kcenon::pacs::core::tags::study_instance_uid, kcenon::pacs::core::tags::study_time, kcenon::pacs::ai::assessment_creation_result::success, and kcenon::pacs::ai::aira_tags::verification_flag.
generate_uid()
std::string kcenon::pacs::ai::assessment_creator::generate_uid () const nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/ai/aira_assessment.h.
Definition at line 313 of file aira_assessment.cpp.
{
    static constexpr const char* uid_root = "1.2.826.0.1.3680043.2.1545.1";
    static std::mt19937_64 gen{std::random_device{}()};
    static std::uniform_int_distribution<uint64_t> dist;
    auto now = std::chrono::system_clock::now();
    auto timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(
        now.time_since_epoch()).count();
    return std::string(uid_root) + "." + std::to_string(timestamp) +
           "." + std::to_string(dist(gen) % 100000);
}
Referenced by create_assessment().
status_to_completion_flag()
std::string kcenon::pacs::ai::assessment_creator::status_to_completion_flag (assessment_status status) static nodiscard
Convert assessment_status to DICOM completion flag value.
Parameters
status Assessment status
Returns
Completion flag string (COMPLETE or PARTIAL)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/ai/aira_assessment.h.
Definition at line 348 of file aira_assessment.cpp.
{
    switch (status) {
    case assessment_status::draft:   return "PARTIAL";
    case assessment_status::final_:  return "COMPLETE";
    case assessment_status::amended: return "COMPLETE";
    }
    return "PARTIAL";
}
References kcenon::pacs::ai::amended, kcenon::pacs::ai::draft, and kcenon::pacs::ai::final_.
Referenced by create_assessment().
The documentation for this class was generated from the following files:
include/kcenon/pacs/ai/aira_assessment.h
src/ai/aira_assessment.cpp