PACS System: kcenon::pacs::services::retrieve_scu Class Reference
kcenon::pacs::services::retrieve_scu Class Reference
#include <retrieve_scu.h>
Public Member Functions
retrieve_scu (std::shared_ptr< di::ILogger > logger=nullptr)
Construct a Retrieve SCU with default configuration.
retrieve_scu (const retrieve_scu_config &config, std::shared_ptr< di::ILogger > logger=nullptr)
Construct a Retrieve SCU with custom configuration.
~retrieve_scu ()=default
retrieve_scu (const retrieve_scu &)=delete
retrieve_scu & operator= (const retrieve_scu &)=delete
retrieve_scu (retrieve_scu &&)=delete
retrieve_scu & operator= (retrieve_scu &&)=delete
network::Result< retrieve_result > move (network::association &assoc, const core::dicom_dataset &query_keys, std::string_view destination_ae, retrieve_progress_callback progress=nullptr)
Perform a C-MOVE operation with raw dataset.
network::Result< retrieve_result > get (network::association &assoc, const core::dicom_dataset &query_keys, retrieve_progress_callback progress=nullptr)
Perform a C-GET operation with raw dataset.
network::Result< retrieve_result > retrieve_study (network::association &assoc, std::string_view study_uid, retrieve_progress_callback progress=nullptr)
Retrieve a study by Study Instance UID.
network::Result< retrieve_result > retrieve_series (network::association &assoc, std::string_view series_uid, retrieve_progress_callback progress=nullptr)
Retrieve a series by Series Instance UID.
network::Result< retrieve_result > retrieve_instance (network::association &assoc, std::string_view sop_instance_uid, retrieve_progress_callback progress=nullptr)
Retrieve a single instance by SOP Instance UID.
network::Result< std::monostate > cancel (network::association &assoc, uint16_t message_id)
Send a C-CANCEL request to stop an ongoing retrieve.
void set_config (const retrieve_scu_config &config)
Update the SCU configuration.
void set_move_destination (std::string_view ae_title)
Set the move destination AE title.
const retrieve_scu_config & config () const noexcept
Get the current configuration.
size_t retrieves_performed () const noexcept
Get the number of retrieves performed since construction.
size_t instances_retrieved () const noexcept
Get the total number of instances retrieved since construction.
size_t bytes_retrieved () const noexcept
Get the total bytes retrieved since construction (C-GET only)
void reset_statistics () noexcept
Reset statistics counters to zero.
Private Member Functions
network::Result< retrieve_result > perform_move (network::association &assoc, const core::dicom_dataset &query_keys, std::string_view destination_ae, retrieve_progress_callback progress)
Internal C-MOVE implementation.
network::Result< retrieve_result > perform_get (network::association &assoc, const core::dicom_dataset &query_keys, retrieve_progress_callback progress)
Internal C-GET implementation.
uint16_t next_message_id () noexcept
Get the next message ID for DIMSE operations.
std::string_view get_move_sop_class_uid () const noexcept
Get MOVE SOP Class UID based on current configuration.
std::string_view get_get_sop_class_uid () const noexcept
Get GET SOP Class UID based on current configuration.
core::dicom_dataset build_study_query (std::string_view study_uid) const
Build query dataset for study retrieval.
core::dicom_dataset build_series_query (std::string_view series_uid) const
Build query dataset for series retrieval.
core::dicom_dataset build_instance_query (std::string_view sop_instance_uid) const
Build query dataset for instance retrieval.
Private Attributes
std::shared_ptr< di::ILogger > logger_
Logger instance for service logging.
retrieve_scu_config config_
Configuration.
std::atomic< uint16_t > message_id_counter_ {1}
Message ID counter.
std::atomic< size_t > retrieves_performed_ {0}
Statistics: number of retrieves performed.
std::atomic< size_t > instances_retrieved_ {0}
Statistics: total number of instances retrieved.
std::atomic< size_t > bytes_retrieved_ {0}
Statistics: total bytes retrieved.
Detailed Description
Definition at line 352 of file retrieve_scu.h.
Constructor & Destructor Documentation
retrieve_scu() [1/4]
kcenon::pacs::services::retrieve_scu::retrieve_scu (std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct a Retrieve SCU with default configuration.
Parameters
logger Logger instance for service logging (nullptr uses null_logger)
Definition at line 25 of file retrieve_scu.cpp.
    : logger_(logger ? std::move(logger) : di::null_logger()) {}
retrieve_scu() [2/4]
kcenon::pacs::services::retrieve_scu::retrieve_scu (const retrieve_scu_config & config, std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct a Retrieve SCU with custom configuration.
Parameters
config Configuration options
logger Logger instance for service logging (nullptr uses null_logger)
Definition at line 28 of file retrieve_scu.cpp.
    : logger_(logger ? std::move(logger) : di::null_logger()), config_(config) {}
~retrieve_scu()
kcenon::pacs::services::retrieve_scu::~retrieve_scu () default
retrieve_scu() [3/4]
kcenon::pacs::services::retrieve_scu::retrieve_scu (const retrieve_scu &) delete
retrieve_scu() [4/4]
kcenon::pacs::services::retrieve_scu::retrieve_scu (retrieve_scu &&) delete
Member Function Documentation
build_instance_query()
core::dicom_dataset kcenon::pacs::services::retrieve_scu::build_instance_query (std::string_view sop_instance_uid) const nodiscard private
Build query dataset for instance retrieval.
Definition at line 526 of file retrieve_scu.cpp.
{
    using namespace core;
    using namespace encoding;
    dicom_dataset ds;
    ds.set_string(tags::query_retrieve_level, vr_type::CS, "IMAGE");
    ds.set_string(tags::sop_instance_uid, vr_type::UI, std::string(sop_instance_uid));
    return ds;
}
References kcenon::pacs::core::tags::query_retrieve_level, and kcenon::pacs::core::tags::sop_instance_uid.
Referenced by retrieve_instance().
build_series_query()
core::dicom_dataset kcenon::pacs::services::retrieve_scu::build_series_query (std::string_view series_uid) const nodiscard private
Build query dataset for series retrieval.
Definition at line 513 of file retrieve_scu.cpp.
{
    using namespace core;
    using namespace encoding;
    dicom_dataset ds;
    ds.set_string(tags::query_retrieve_level, vr_type::CS, "SERIES");
    ds.set_string(tags::series_instance_uid, vr_type::UI, std::string(series_uid));
    return ds;
}
References kcenon::pacs::core::tags::query_retrieve_level, and kcenon::pacs::core::tags::series_instance_uid.
Referenced by retrieve_series().
build_study_query()
core::dicom_dataset kcenon::pacs::services::retrieve_scu::build_study_query (std::string_view study_uid) const nodiscard private
Build query dataset for study retrieval.
Definition at line 500 of file retrieve_scu.cpp.
{
    using namespace core;
    using namespace encoding;
    dicom_dataset ds;
    ds.set_string(tags::query_retrieve_level, vr_type::CS, "STUDY");
    ds.set_string(tags::study_instance_uid, vr_type::UI, std::string(study_uid));
    return ds;
}
References kcenon::pacs::core::tags::query_retrieve_level, and kcenon::pacs::core::tags::study_instance_uid.
Referenced by retrieve_study().
bytes_retrieved()
size_t kcenon::pacs::services::retrieve_scu::bytes_retrieved () const nodiscard noexcept
Get the total bytes retrieved since construction (C-GET only)
Returns
Total bytes of dataset data received
Definition at line 455 of file retrieve_scu.cpp.
{
    return bytes_retrieved_.load(std::memory_order_relaxed);
}
References bytes_retrieved_.
cancel()
network::Result< std::monostate > kcenon::pacs::services::retrieve_scu::cancel (network::association & assoc, uint16_t message_id) nodiscard
Send a C-CANCEL request to stop an ongoing retrieve.
Parameters
assoc The association on which the retrieve is running
message_id The message ID of the retrieve to cancel
Returns
Success or error
Definition at line 405 of file retrieve_scu.cpp.
{
    using namespace network::dimse;
    auto sop_class_uid = (config_.mode == retrieve_mode::c_move)
        ? get_move_sop_class_uid()
        : get_get_sop_class_uid();
    auto context_id = assoc.accepted_context_id(sop_class_uid);
    if (!context_id) {
        return kcenon::pacs::pacs_error<std::monostate>(
            kcenon::pacs::error_codes::no_acceptable_context,
            "No accepted presentation context for cancel");
    }
    // Build C-CANCEL-RQ message
    dimse_message cancel_rq{command_field::c_cancel_rq, message_id};
    return assoc.send_dimse(*context_id, cancel_rq);
}
References kcenon::pacs::network::association::accepted_context_id(), kcenon::pacs::services::c_move, config_, get_get_sop_class_uid(), get_move_sop_class_uid(), kcenon::pacs::services::retrieve_scu_config::mode, kcenon::pacs::error_codes::no_acceptable_context, kcenon::pacs::pacs_error(), and kcenon::pacs::network::association::send_dimse().
config()
const retrieve_scu_config & kcenon::pacs::services::retrieve_scu::config () const nodiscard noexcept
Get the current configuration.
Returns
Reference to the current configuration
Definition at line 439 of file retrieve_scu.cpp.
{
    return config_;
}
References config_.
Referenced by set_config().
get()
network::Result< retrieve_result > kcenon::pacs::services::retrieve_scu::get (network::association & assoc, const core::dicom_dataset & query_keys, retrieve_progress_callback progress = nullptr) nodiscard
Perform a C-GET operation with raw dataset.
Sends a C-GET request with the provided query keys to retrieve matching images. The images are received directly on the same association via C-STORE sub-operations.
Parameters
assoc The established association to use
query_keys The DICOM dataset containing query keys
progress Optional callback for progress updates
Returns
Result containing retrieve_result on success, or error message
Definition at line 186 of file retrieve_scu.cpp.
{
    return perform_get(assoc, query_keys, progress);
}
References perform_get().
Referenced by retrieve_instance(), retrieve_series(), and retrieve_study().
get_get_sop_class_uid()
std::string_view kcenon::pacs::services::retrieve_scu::get_get_sop_class_uid () const nodiscard private noexcept
Get GET SOP Class UID based on current configuration.
Definition at line 489 of file retrieve_scu.cpp.
{
    switch (config_.model) {
        case query_model::patient_root:
            return patient_root_get_sop_class_uid;
        case query_model::study_root:
            return study_root_get_sop_class_uid;
        default:
            return study_root_get_sop_class_uid;
    }
}
References config_, kcenon::pacs::services::retrieve_scu_config::model, kcenon::pacs::services::patient_root, kcenon::pacs::services::patient_root_get_sop_class_uid, kcenon::pacs::services::study_root, and kcenon::pacs::services::study_root_get_sop_class_uid.
Referenced by cancel(), and perform_get().
get_move_sop_class_uid()
std::string_view kcenon::pacs::services::retrieve_scu::get_move_sop_class_uid () const nodiscard private noexcept
Get MOVE SOP Class UID based on current configuration.
Definition at line 478 of file retrieve_scu.cpp.
{
    switch (config_.model) {
        case query_model::patient_root:
            return patient_root_move_sop_class_uid;
        case query_model::study_root:
            return study_root_move_sop_class_uid;
        default:
            return study_root_move_sop_class_uid;
    }
}
References config_, kcenon::pacs::services::retrieve_scu_config::model, kcenon::pacs::services::patient_root, kcenon::pacs::services::patient_root_move_sop_class_uid, kcenon::pacs::services::study_root, and kcenon::pacs::services::study_root_move_sop_class_uid.
Referenced by cancel(), and perform_move().
instances_retrieved()
size_t kcenon::pacs::services::retrieve_scu::instances_retrieved () const nodiscard noexcept
Get the total number of instances retrieved since construction.
Returns
Total count of successful sub-operations
Definition at line 451 of file retrieve_scu.cpp.
{
    return instances_retrieved_.load(std::memory_order_relaxed);
}
References instances_retrieved_.
move()
network::Result< retrieve_result > kcenon::pacs::services::retrieve_scu::move (network::association & assoc, const core::dicom_dataset & query_keys, std::string_view destination_ae, retrieve_progress_callback progress = nullptr) nodiscard
Perform a C-MOVE operation with raw dataset.
Sends a C-MOVE request with the provided query keys to retrieve matching images. The SCP will send the images to the specified destination AE title.
Parameters
assoc The established association to use
query_keys The DICOM dataset containing query keys
destination_ae The destination AE title to send images to
progress Optional callback for progress updates
Returns
Result containing retrieve_result on success, or error message
Definition at line 36 of file retrieve_scu.cpp.
{
    return perform_move(assoc, query_keys, destination_ae, progress);
}
References perform_move().
Referenced by retrieve_instance(), retrieve_series(), and retrieve_study().
next_message_id()
uint16_t kcenon::pacs::services::retrieve_scu::next_message_id () nodiscard private noexcept
Get the next message ID for DIMSE operations.
Definition at line 469 of file retrieve_scu.cpp.
{
    uint16_t id = message_id_counter_.fetch_add(1, std::memory_order_relaxed);
    // Wrap around at 0xFFFF, skip 0 (reserved)
    if (id == 0) {
        id = message_id_counter_.fetch_add(1, std::memory_order_relaxed);
    }
    return id;
}
References message_id_counter_.
Referenced by perform_get(), and perform_move().
operator=() [1/2]
retrieve_scu & kcenon::pacs::services::retrieve_scu::operator= (const retrieve_scu &) delete
operator=() [2/2]
retrieve_scu & kcenon::pacs::services::retrieve_scu::operator= (retrieve_scu &&) delete
perform_get()
network::Result< retrieve_result > kcenon::pacs::services::retrieve_scu::perform_get (network::association & assoc, const core::dicom_dataset & query_keys, retrieve_progress_callback progress) nodiscard private
Internal C-GET implementation.
Definition at line 194 of file retrieve_scu.cpp.
{
    using namespace network::dimse;
    auto start_time = std::chrono::steady_clock::now();
    auto message_id = next_message_id();
    // Verify association is established
    if (!assoc.is_established()) {
        return kcenon::pacs::pacs_error<retrieve_result>(
            kcenon::pacs::error_codes::association_not_established,
            "Association not established");
    }
    // Get SOP Class UID
    auto sop_class_uid = get_get_sop_class_uid();
    // Get accepted presentation context for this SOP class
    auto context_id = assoc.accepted_context_id(sop_class_uid);
    if (!context_id) {
        return kcenon::pacs::pacs_error<retrieve_result>(
            kcenon::pacs::error_codes::no_acceptable_context,
            "No accepted presentation context for SOP Class: " +
            std::string(sop_class_uid));
    }
    // Build C-GET-RQ message
    dimse_message request{command_field::c_get_rq, message_id};
    request.set_affected_sop_class_uid(sop_class_uid);
    request.set_priority(config_.priority);
    request.set_dataset(query_keys);
    logger_->debug_fmt("Sending C-GET request (message_id={}, sop_class={})",
                       message_id, sop_class_uid);
    // Send the request
    auto send_result = assoc.send_dimse(*context_id, request);
    if (send_result.is_err()) {
        return send_result.error();
    }
    // Initialize progress tracking
    retrieve_progress prog;
    prog.start_time = start_time;
    // Receive responses (C-GET-RSP and C-STORE-RQ interleaved)
    retrieve_result result;
    bool retrieve_complete = false;
    while (!retrieve_complete) {
        auto recv_result = assoc.receive_dimse(config_.timeout);
        if (recv_result.is_err()) {
            return recv_result.error();
        }
        auto& [recv_context_id, msg] = recv_result.value();
        auto cmd = msg.command();
        if (cmd == command_field::c_get_rsp) {
            auto status = msg.status();
            // Extract sub-operation counts
            if (auto remaining = msg.remaining_subops()) {
                prog.remaining = *remaining;
            }
            if (auto completed = msg.completed_subops()) {
                prog.completed = *completed;
                result.completed = *completed;
            }
            if (auto failed = msg.failed_subops()) {
                prog.failed = *failed;
                result.failed = *failed;
            }
            if (auto warning = msg.warning_subops()) {
                prog.warning = *warning;
                result.warning = *warning;
            }
            // Call progress callback
            if (progress) {
                progress(prog);
            }
            // Check completion status
            if (status == status_success) {
                retrieve_complete = true;
                result.final_status = static_cast<uint16_t>(status);
            } else if (status == status_cancel) {
                retrieve_complete = true;
                result.final_status = static_cast<uint16_t>(status);
            } else if ((status & 0xF000) == 0xA000 ||
                       (status & 0xF000) == 0xC000) {
                // Error status
                retrieve_complete = true;
                result.final_status = static_cast<uint16_t>(status);
            }
        } else if (cmd == command_field::c_store_rq) {
            // Incoming C-STORE sub-operation - store the received instance
            if (msg.has_dataset()) {
                auto dataset_result = msg.dataset();
                if (dataset_result.is_ok()) {
                    result.received_instances.push_back(dataset_result.value().get());
                    // Update bytes transferred (approximate)
                    bytes_retrieved_.fetch_add(1024, std::memory_order_relaxed);
                }
            }
            // Send C-STORE response
            auto sop_class = msg.affected_sop_class_uid();
            auto sop_instance = msg.affected_sop_instance_uid();
            auto store_rsp = make_c_store_rsp(
                msg.message_id(),
                sop_class,
                sop_instance,
                status_success
            );
            auto send_rsp_result = assoc.send_dimse(recv_context_id, store_rsp);
            if (send_rsp_result.is_err()) {
                logger_->warn_fmt("Failed to send C-STORE response: {}",
                                  send_rsp_result.error().message);
            }
        }
    }
    auto end_time = std::chrono::steady_clock::now();
    result.elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
        end_time - start_time);
    // Update statistics
    retrieves_performed_.fetch_add(1, std::memory_order_relaxed);
    instances_retrieved_.fetch_add(result.completed, std::memory_order_relaxed);
    logger_->debug_fmt("C-GET completed: {} completed, {} failed, {} received in {} ms",
                       result.completed, result.failed,
                       result.received_instances.size(), result.elapsed.count());
    return result;
}
References kcenon::pacs::network::association::accepted_context_id(), kcenon::pacs::error_codes::association_not_established, bytes_retrieved_, kcenon::pacs::services::completed, kcenon::pacs::services::retrieve_progress::completed, kcenon::pacs::services::retrieve_result::completed, config_, kcenon::pacs::services::retrieve_result::elapsed, kcenon::pacs::services::retrieve_progress::failed, kcenon::pacs::services::retrieve_result::failed, kcenon::pacs::services::retrieve_result::final_status, get_get_sop_class_uid(), instances_retrieved_, kcenon::pacs::network::association::is_established(), logger_, next_message_id(), kcenon::pacs::error_codes::no_acceptable_context, kcenon::pacs::pacs_error(), kcenon::pacs::services::retrieve_scu_config::priority, kcenon::pacs::network::association::receive_dimse(), kcenon::pacs::services::retrieve_result::received_instances, kcenon::pacs::services::retrieve_progress::remaining, retrieves_performed_, kcenon::pacs::network::association::send_dimse(), kcenon::pacs::services::retrieve_progress::start_time, kcenon::pacs::services::retrieve_scu_config::timeout, kcenon::pacs::services::warning, kcenon::pacs::services::retrieve_progress::warning, and kcenon::pacs::services::retrieve_result::warning.
Referenced by get().
perform_move()
network::Result< retrieve_result > kcenon::pacs::services::retrieve_scu::perform_move (network::association & assoc, const core::dicom_dataset & query_keys, std::string_view destination_ae, retrieve_progress_callback progress) nodiscard private
Internal C-MOVE implementation.
Definition at line 45 of file retrieve_scu.cpp.
{
    using namespace network::dimse;
    auto start_time = std::chrono::steady_clock::now();
    auto message_id = next_message_id();
    // Verify association is established
    if (!assoc.is_established()) {
        return kcenon::pacs::pacs_error<retrieve_result>(
            kcenon::pacs::error_codes::association_not_established,
            "Association not established");
    }
    // Validate move destination
    if (destination_ae.empty()) {
        return kcenon::pacs::pacs_error<retrieve_result>(
            kcenon::pacs::error_codes::retrieve_missing_destination,
            "Move destination AE title is required");
    }
    // Get SOP Class UID
    auto sop_class_uid = get_move_sop_class_uid();
    // Get accepted presentation context for this SOP class
    auto context_id = assoc.accepted_context_id(sop_class_uid);
    if (!context_id) {
        return kcenon::pacs::pacs_error<retrieve_result>(
            kcenon::pacs::error_codes::no_acceptable_context,
            "No accepted presentation context for SOP Class: " +
            std::string(sop_class_uid));
    }
    // Build C-MOVE-RQ message
    dimse_message request{command_field::c_move_rq, message_id};
    request.set_affected_sop_class_uid(sop_class_uid);
    request.set_priority(config_.priority);
    // Set Move Destination
    request.command_set().set_string(
        tag_move_destination,
        encoding::vr_type::AE,
        std::string(destination_ae));
    request.set_dataset(query_keys);
    logger_->debug_fmt("Sending C-MOVE request (message_id={}, dest={}, sop_class={})",
                       message_id, destination_ae, sop_class_uid);
    // Send the request
    auto send_result = assoc.send_dimse(*context_id, request);
    if (send_result.is_err()) {
        return send_result.error();
    }
    // Initialize progress tracking
    retrieve_progress prog;
    prog.start_time = start_time;
    // Receive responses
    retrieve_result result;
    bool move_complete = false;
    while (!move_complete) {
        auto recv_result = assoc.receive_dimse(config_.timeout);
        if (recv_result.is_err()) {
            return recv_result.error();
        }
        const auto& [recv_context_id, response] = recv_result.value();
        // Verify it's a C-MOVE response
        if (response.command() != command_field::c_move_rsp) {
            return kcenon::pacs::pacs_error<retrieve_result>(
                kcenon::pacs::error_codes::retrieve_unexpected_command,
                "Expected C-MOVE-RSP but received " +
                std::string(to_string(response.command())));
        }
        auto status = response.status();
        // Extract sub-operation counts
        if (auto remaining = response.remaining_subops()) {
            prog.remaining = *remaining;
        }
        if (auto completed = response.completed_subops()) {
            prog.completed = *completed;
            result.completed = *completed;
        }
        if (auto failed = response.failed_subops()) {
            prog.failed = *failed;
            result.failed = *failed;
        }
        if (auto warning = response.warning_subops()) {
            prog.warning = *warning;
            result.warning = *warning;
        }
        // Call progress callback
        if (progress) {
            progress(prog);
        }
        // Check completion status
        if (status == status_success) {
            move_complete = true;
            result.final_status = static_cast<uint16_t>(status);
        } else if (status == status_cancel) {
            move_complete = true;
            result.final_status = static_cast<uint16_t>(status);
        } else if ((status & 0xF000) == 0xA000 ||
                   (status & 0xF000) == 0xC000) {
            // Error status (Refused or Failed)
            move_complete = true;
            result.final_status = static_cast<uint16_t>(status);
        }
        // status_pending (0xFF00) continues the loop
    }
    auto end_time = std::chrono::steady_clock::now();
    result.elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
        end_time - start_time);
    // Update statistics
    retrieves_performed_.fetch_add(1, std::memory_order_relaxed);
    instances_retrieved_.fetch_add(result.completed, std::memory_order_relaxed);
    logger_->debug_fmt("C-MOVE completed: {} completed, {} failed in {} ms",
                       result.completed, result.failed, result.elapsed.count());
    return result;
}
References kcenon::pacs::network::association::accepted_context_id(), kcenon::pacs::encoding::AE, kcenon::pacs::error_codes::association_not_established, kcenon::pacs::services::completed, kcenon::pacs::services::retrieve_progress::completed, kcenon::pacs::services::retrieve_result::completed, config_, kcenon::pacs::services::retrieve_result::elapsed, kcenon::pacs::services::retrieve_progress::failed, kcenon::pacs::services::retrieve_result::failed, kcenon::pacs::services::retrieve_result::final_status, get_move_sop_class_uid(), instances_retrieved_, kcenon::pacs::network::association::is_established(), logger_, next_message_id(), kcenon::pacs::error_codes::no_acceptable_context, kcenon::pacs::pacs_error(), kcenon::pacs::services::retrieve_scu_config::priority, kcenon::pacs::network::association::receive_dimse(), kcenon::pacs::services::retrieve_progress::remaining, kcenon::pacs::error_codes::retrieve_missing_destination, kcenon::pacs::error_codes::retrieve_unexpected_command, retrieves_performed_, kcenon::pacs::network::association::send_dimse(), kcenon::pacs::services::retrieve_progress::start_time, kcenon::pacs::services::retrieve_scu_config::timeout, kcenon::pacs::services::to_string(), kcenon::pacs::services::warning, kcenon::pacs::services::retrieve_progress::warning, and kcenon::pacs::services::retrieve_result::warning.
Referenced by move().
reset_statistics()
void kcenon::pacs::services::retrieve_scu::reset_statistics () noexcept
Reset statistics counters to zero.
Definition at line 459 of file retrieve_scu.cpp.
{
    retrieves_performed_.store(0, std::memory_order_relaxed);
    instances_retrieved_.store(0, std::memory_order_relaxed);
    bytes_retrieved_.store(0, std::memory_order_relaxed);
}
References bytes_retrieved_, instances_retrieved_, and retrieves_performed_.
retrieve_instance()
network::Result< retrieve_result > kcenon::pacs::services::retrieve_scu::retrieve_instance (network::association & assoc, std::string_view sop_instance_uid, retrieve_progress_callback progress = nullptr) nodiscard
Retrieve a single instance by SOP Instance UID.
Uses C-MOVE or C-GET based on current configuration.
Parameters
assoc The established association to use
sop_instance_uid The SOP Instance UID to retrieve
progress Optional callback for progress updates
Returns
Result containing retrieve_result on success
Definition at line 382 of file retrieve_scu.cpp.
{
    auto query_ds = build_instance_query(sop_instance_uid);
    if (config_.mode == retrieve_mode::c_move) {
        if (config_.move_destination.empty()) {
            return kcenon::pacs::pacs_error<retrieve_result>(
                kcenon::pacs::error_codes::retrieve_missing_destination,
                "Move destination is required for C-MOVE mode");
        }
        return move(assoc, query_ds, config_.move_destination, progress);
    } else {
        return get(assoc, query_ds, progress);
    }
}
References build_instance_query(), kcenon::pacs::services::c_move, config_, get(), kcenon::pacs::services::retrieve_scu_config::mode, move(), kcenon::pacs::services::retrieve_scu_config::move_destination, kcenon::pacs::pacs_error(), and kcenon::pacs::error_codes::retrieve_missing_destination.
retrieve_series()
network::Result< retrieve_result > kcenon::pacs::services::retrieve_scu::retrieve_series (network::association & assoc, std::string_view series_uid, retrieve_progress_callback progress = nullptr) nodiscard
Retrieve a series by Series Instance UID.
Uses C-MOVE or C-GET based on current configuration.
Parameters
assoc The established association to use
series_uid The Series Instance UID to retrieve
progress Optional callback for progress updates
Returns
Result containing retrieve_result on success
Definition at line 363 of file retrieve_scu.cpp.
{
    auto query_ds = build_series_query(series_uid);
    if (config_.mode == retrieve_mode::c_move) {
        if (config_.move_destination.empty()) {
            return kcenon::pacs::pacs_error<retrieve_result>(
                kcenon::pacs::error_codes::retrieve_missing_destination,
                "Move destination is required for C-MOVE mode");
        }
        return move(assoc, query_ds, config_.move_destination, progress);
    } else {
        return get(assoc, query_ds, progress);
    }
}
References build_series_query(), kcenon::pacs::services::c_move, config_, get(), kcenon::pacs::services::retrieve_scu_config::mode, move(), kcenon::pacs::services::retrieve_scu_config::move_destination, kcenon::pacs::pacs_error(), and kcenon::pacs::error_codes::retrieve_missing_destination.
Referenced by kcenon::pacs::client::job_manager::impl::execute_retrieve_job().
retrieve_study()
network::Result< retrieve_result > kcenon::pacs::services::retrieve_scu::retrieve_study (network::association & assoc, std::string_view study_uid, retrieve_progress_callback progress = nullptr) nodiscard
Retrieve a study by Study Instance UID.
Uses C-MOVE or C-GET based on current configuration.
Parameters
assoc The established association to use
study_uid The Study Instance UID to retrieve
progress Optional callback for progress updates
Returns
Result containing retrieve_result on success
Definition at line 344 of file retrieve_scu.cpp.
{
    auto query_ds = build_study_query(study_uid);
    if (config_.mode == retrieve_mode::c_move) {
        if (config_.move_destination.empty()) {
            return kcenon::pacs::pacs_error<retrieve_result>(
                kcenon::pacs::error_codes::retrieve_missing_destination,
                "Move destination is required for C-MOVE mode");
        }
        return move(assoc, query_ds, config_.move_destination, progress);
    } else {
        return get(assoc, query_ds, progress);
    }
}
References build_study_query(), kcenon::pacs::services::c_move, config_, get(), kcenon::pacs::services::retrieve_scu_config::mode, move(), kcenon::pacs::services::retrieve_scu_config::move_destination, kcenon::pacs::pacs_error(), and kcenon::pacs::error_codes::retrieve_missing_destination.
Referenced by kcenon::pacs::client::job_manager::impl::execute_retrieve_job(), and kcenon::pacs::workflow::auto_prefetch_service::prefetch_study().
retrieves_performed()
size_t kcenon::pacs::services::retrieve_scu::retrieves_performed () const nodiscard noexcept
Get the number of retrieves performed since construction.
Returns
Count of C-MOVE/C-GET requests sent
Definition at line 447 of file retrieve_scu.cpp.
{
    return retrieves_performed_.load(std::memory_order_relaxed);
}
References retrieves_performed_.
set_config()
void kcenon::pacs::services::retrieve_scu::set_config (const retrieve_scu_config & config)
Update the SCU configuration.
Parameters
config New configuration options
Definition at line 431 of file retrieve_scu.cpp.
{
    config_ = config;
}
References config(), and config_.
set_move_destination()
void kcenon::pacs::services::retrieve_scu::set_move_destination (std::string_view ae_title)
Set the move destination AE title.
Parameters
ae_title The destination AE title for C-MOVE operations
Definition at line 435 of file retrieve_scu.cpp.
{
    config_.move_destination = std::string(ae_title);
}
References config_, and kcenon::pacs::services::retrieve_scu_config::move_destination.
Member Data Documentation
bytes_retrieved_
std::atomic<size_t> kcenon::pacs::services::retrieve_scu::bytes_retrieved_ {0} private
Statistics: total bytes retrieved.
Definition at line 617 of file retrieve_scu.h.
{0};
Referenced by bytes_retrieved(), perform_get(), and reset_statistics().
config_
retrieve_scu_config kcenon::pacs::services::retrieve_scu::config_ private
Configuration.
Definition at line 605 of file retrieve_scu.h.
Referenced by cancel(), config(), get_get_sop_class_uid(), get_move_sop_class_uid(), perform_get(), perform_move(), retrieve_instance(), retrieve_series(), retrieve_study(), set_config(), and set_move_destination().
instances_retrieved_
std::atomic<size_t> kcenon::pacs::services::retrieve_scu::instances_retrieved_ {0} private
Statistics: total number of instances retrieved.
Definition at line 614 of file retrieve_scu.h.
{0};
Referenced by instances_retrieved(), perform_get(), perform_move(), and reset_statistics().
logger_
std::shared_ptr<di::ILogger> kcenon::pacs::services::retrieve_scu::logger_ private
Logger instance for service logging.
Definition at line 602 of file retrieve_scu.h.
Referenced by perform_get(), and perform_move().
message_id_counter_
std::atomic<uint16_t> kcenon::pacs::services::retrieve_scu::message_id_counter_ {1} private
Message ID counter.
Definition at line 608 of file retrieve_scu.h.
{1};
Referenced by next_message_id().
retrieves_performed_
std::atomic<size_t> kcenon::pacs::services::retrieve_scu::retrieves_performed_ {0} private
Statistics: number of retrieves performed.
Definition at line 611 of file retrieve_scu.h.
{0};
Referenced by perform_get(), perform_move(), reset_statistics(), and retrieves_performed().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/retrieve_scu.h
src/services/retrieve_scu.cpp