PACS System: kcenon::pacs::services::n_get_scp Class Reference
kcenon::pacs::services::n_get_scp Class Reference final
#include <n_get_scp.hpp>
Public Member Functions
n_get_scp (std::shared_ptr< di::ILogger > logger=nullptr)
Construct N-GET SCP with optional logger.
~n_get_scp () override=default
void set_handler (n_get_handler handler)
Set the N-GET handler function.
void add_supported_sop_class (std::string sop_class_uid)
Add a SOP Class UID that this SCP supports.
std::vector< std::string > supported_sop_classes () const override
Get supported SOP Class UIDs.
network::Result< std::monostate > handle_message (network::association &assoc, uint8_t context_id, const network::dimse::dimse_message &request) override
Handle an incoming N-GET-RQ message.
std::string_view service_name () const noexcept override
Get the service name.
size_t gets_processed () const noexcept
Get total number of N-GET requests processed.
void reset_statistics () noexcept
Reset statistics counters.
Public Member Functions inherited from kcenon::pacs::services::scp_service
scp_service (std::shared_ptr< di::ILogger > logger=nullptr)
Construct SCP service with optional logger.
virtual ~scp_service ()=default
scp_service (const scp_service &)=delete
scp_service & operator= (const scp_service &)=delete
scp_service (scp_service &&)=default
scp_service & operator= (scp_service &&)=default
void set_logger (std::shared_ptr< di::ILogger > logger)
Set the logger instance.
const std::shared_ptr< di::ILogger > & logger () const noexcept
Get the current logger instance.
bool supports_sop_class (std::string_view sop_class_uid) const
Check if this service supports a specific SOP Class.
Private Member Functions
network::Result< std::monostate > send_n_get_response (network::association &assoc, uint8_t context_id, uint16_t message_id, const std::string &sop_class_uid, const std::string &sop_instance_uid, network::dimse::status_code status, core::dicom_dataset *dataset=nullptr)
Send N-GET response.
Private Attributes
n_get_handler handler_
std::vector< std::string > supported_sop_classes_
std::atomic< size_t > gets_processed_ {0}
Additional Inherited Members
Protected Attributes inherited from kcenon::pacs::services::scp_service
std::shared_ptr< di::ILogger > logger_
Logger instance for service logging.
Detailed Description
Definition at line 130 of file n_get_scp.hpp.
Constructor & Destructor Documentation
n_get_scp()
kcenon::pacs::services::n_get_scp::n_get_scp (std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct N-GET SCP with optional logger.
Parameters
logger Logger instance (nullptr uses null_logger)
Definition at line 50 of file n_get_scp.cpp.
    : scp_service(std::move(logger)) {}
~n_get_scp()
kcenon::pacs::services::n_get_scp::~n_get_scp () override default
Member Function Documentation
add_supported_sop_class()
void kcenon::pacs::services::n_get_scp::add_supported_sop_class (std::string sop_class_uid)
Add a SOP Class UID that this SCP supports.
N-GET can be used with multiple SOP Classes (e.g., MPPS, Printer). By default, no SOP Classes are registered. Call this method to add supported SOP Classes.
Parameters
sop_class_uid The SOP Class UID to support
Definition at line 61 of file n_get_scp.cpp.
{
    supported_sop_classes_.push_back(std::move(sop_class_uid));
}
References supported_sop_classes_.
gets_processed()
size_t kcenon::pacs::services::n_get_scp::gets_processed () const noexcept
Get total number of N-GET requests processed.
Definition at line 156 of file n_get_scp.cpp.
{
    return gets_processed_.load();
}
References gets_processed_.
handle_message()
network::Result< std::monostate > kcenon::pacs::services::n_get_scp::handle_message (network::association & assoc, uint8_t context_id, const network::dimse::dimse_message & request) override virtual
Handle an incoming N-GET-RQ message.
Parameters
assoc The association on which the message was received
context_id The presentation context ID
request The incoming N-GET-RQ message
Returns
Success or error
Implements kcenon::pacs::services::scp_service.
Definition at line 73 of file n_get_scp.cpp.
{
    using namespace network::dimse;
    // Verify command type is N-GET-RQ
    if (request.command() != command_field::n_get_rq) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::n_get_unexpected_command,
            "Unexpected command for N-GET SCP: " +
            std::string(to_string(request.command())));
    }
    // Verify we have a handler configured
    if (!handler_) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::n_get_handler_not_set,
            "No N-GET handler configured");
    }
    // Extract Requested SOP Class UID
    auto sop_class_uid = request.requested_sop_class_uid();
    if (sop_class_uid.empty()) {
        return send_n_get_response(
            assoc, context_id, request.message_id(),
            "", "", status_error_missing_attribute);
    }
    // Verify the SOP Class is supported
    if (!supports_sop_class(sop_class_uid)) {
        return send_n_get_response(
            assoc, context_id, request.message_id(),
            sop_class_uid, "", status_refused_sop_class_not_supported);
    }
    // Extract Requested SOP Instance UID
    auto sop_instance_uid = request.requested_sop_instance_uid();
    if (sop_instance_uid.empty()) {
        return send_n_get_response(
            assoc, context_id, request.message_id(),
            sop_class_uid, "", status_error_missing_attribute);
    }
    // Extract Attribute Identifier List (empty = all attributes)
    auto attribute_tags = request.attribute_identifier_list();
    logger_->debug("N-GET request for instance: " + sop_instance_uid +
                   " (attributes requested: " +
                   (attribute_tags.empty() ? "all" :
                    std::to_string(attribute_tags.size())) + ")");
    // Call the handler to retrieve attributes
    auto result = handler_(sop_class_uid, sop_instance_uid, attribute_tags);
    if (result.is_err()) {
        logger_->warn("N-GET handler failed for instance: " + sop_instance_uid +
                       " - " + result.error().message);
        return send_n_get_response(
            assoc, context_id, request.message_id(),
            sop_class_uid, sop_instance_uid,
            status_error_invalid_object_instance);
    }
    // Update statistics
    ++gets_processed_;
    // Send success response with dataset
    auto dataset = std::move(result.value());
    return send_n_get_response(
        assoc, context_id, request.message_id(),
        sop_class_uid, sop_instance_uid,
        status_success, &dataset);
}
References kcenon::pacs::network::dimse::dimse_message::attribute_identifier_list(), kcenon::pacs::network::dimse::dimse_message::command(), gets_processed_, handler_, kcenon::pacs::services::scp_service::logger_, kcenon::pacs::network::dimse::dimse_message::message_id(), kcenon::pacs::error_codes::n_get_handler_not_set, kcenon::pacs::error_codes::n_get_unexpected_command, kcenon::pacs::pacs_void_error(), kcenon::pacs::network::dimse::dimse_message::requested_sop_class_uid(), kcenon::pacs::network::dimse::dimse_message::requested_sop_instance_uid(), send_n_get_response(), and kcenon::pacs::services::scp_service::supports_sop_class().
reset_statistics()
void kcenon::pacs::services::n_get_scp::reset_statistics () noexcept
Reset statistics counters.
Definition at line 160 of file n_get_scp.cpp.
{
    gets_processed_ = 0;
}
References gets_processed_.
send_n_get_response()
network::Result< std::monostate > kcenon::pacs::services::n_get_scp::send_n_get_response (network::association & assoc, uint8_t context_id, uint16_t message_id, const std::string & sop_class_uid, const std::string & sop_instance_uid, network::dimse::status_code status, core::dicom_dataset * dataset = nullptr) private
Send N-GET response.
Definition at line 168 of file n_get_scp.cpp.
{
    using namespace network::dimse;
    // Create N-GET response using factory function
    auto response = make_n_get_rsp(
        message_id, sop_class_uid, sop_instance_uid, status);
    // Attach dataset if provided (successful responses include attributes)
    if (dataset != nullptr) {
        response.set_dataset(std::move(*dataset));
    }
    // Send the response
    return assoc.send_dimse(context_id, response);
}
References kcenon::pacs::network::association::send_dimse().
Referenced by handle_message().
service_name()
std::string_view kcenon::pacs::services::n_get_scp::service_name () const override virtual noexcept
Get the service name.
Returns
"N-GET SCP"
Implements kcenon::pacs::services::scp_service.
Definition at line 148 of file n_get_scp.cpp.
{
    return "N-GET SCP";
}
set_handler()
void kcenon::pacs::services::n_get_scp::set_handler (n_get_handler handler)
Set the N-GET handler function.
The handler is called for each N-GET request to retrieve attributes from a managed SOP Instance.
Parameters
handler The N-GET handler function
Definition at line 57 of file n_get_scp.cpp.
{
    handler_ = std::move(handler);
}
References handler_.
supported_sop_classes()
std::vector< std::string > kcenon::pacs::services::n_get_scp::supported_sop_classes () const override virtual
Get supported SOP Class UIDs.
Returns
Vector of registered SOP Class UIDs
Implements kcenon::pacs::services::scp_service.
Definition at line 69 of file n_get_scp.cpp.
{
    return supported_sop_classes_;
}
References supported_sop_classes_.
Member Data Documentation
gets_processed_
std::atomic<size_t> kcenon::pacs::services::n_get_scp::gets_processed_ {0} private
Definition at line 239 of file n_get_scp.hpp.
{0};
Referenced by gets_processed(), handle_message(), and reset_statistics().
handler_
n_get_handler kcenon::pacs::services::n_get_scp::handler_ private
Definition at line 236 of file n_get_scp.hpp.
Referenced by handle_message(), and set_handler().
supported_sop_classes_
std::vector<std::string> kcenon::pacs::services::n_get_scp::supported_sop_classes_ private
Definition at line 237 of file n_get_scp.hpp.
Referenced by add_supported_sop_class(), and supported_sop_classes().
The documentation for this class was generated from the following files:
include/pacs/services/n_get_scp.hpp
src/services/n_get_scp.cpp