PACS System: kcenon::pacs::dcm_modify::anonymizer Class Reference
kcenon::pacs::dcm_modify::anonymizer Class Reference
DICOM Anonymizer - removes or replaces PHI from datasets.
#include <anonymizer.h>
Public Member Functions
anonymizer ()=default
Construct an anonymizer with default options.
anonymizer (anonymize_options opts)
Construct an anonymizer with custom options.
void anonymize (core::dicom_dataset &dataset)
Anonymize a DICOM dataset in place.
uid_mapper & get_uid_mapper ()
Get the UID mapper for consistent UID replacement.
const anonymize_options & options () const
Get the current options.
void set_options (anonymize_options opts)
Set new options.
Private Member Functions
void anonymize_patient_info (core::dicom_dataset &dataset)
void anonymize_uids (core::dicom_dataset &dataset)
void remove_private_tags (core::dicom_dataset &dataset)
void remove_additional_phi (core::dicom_dataset &dataset)
Private Attributes
anonymize_options options_
uid_mapper uid_mapper_
std::atomic< uint64_t > patient_counter_ {0}
Detailed Description
DICOM Anonymizer - removes or replaces PHI from datasets.
Implements basic DICOM anonymization as specified in DICOM PS3.15. This includes removal/replacement of:
Patient identifying information
UIDs (to prevent correlation)
Dates (optional shifting)
Free-text fields that may contain PHI
Definition at line 113 of file anonymizer.h.
Constructor & Destructor Documentation
anonymizer() [1/2]
kcenon::pacs::dcm_modify::anonymizer::anonymizer () default
Construct an anonymizer with default options.
anonymizer() [2/2]
kcenon::pacs::dcm_modify::anonymizer::anonymizer (anonymize_options opts) inline explicit
Construct an anonymizer with custom options.
Parameters
opts Anonymization options
Definition at line 124 of file anonymizer.h.
: options_(std::move(opts)) {}
Member Function Documentation
anonymize()
void kcenon::pacs::dcm_modify::anonymizer::anonymize (core::dicom_dataset & dataset) inline
Anonymize a DICOM dataset in place.
Parameters
dataset The dataset to anonymize
Definition at line 130 of file anonymizer.h.
{
        using namespace kcenon::pacs::core;
        using namespace kcenon::pacs::encoding;
        // Patient identifying information
        anonymize_patient_info(dataset);
        // UIDs
        if (options_.replace_uids) {
            anonymize_uids(dataset);
        }
        // Dates
        if (options_.remove_birth_date) {
            dataset.remove(tags::patient_birth_date);
        }
        // Referring physician
        if (options_.remove_referring_physician) {
            dataset.remove(tags::referring_physician_name);
        }
        // Institution
        if (options_.remove_institution) {
            dataset.remove(dicom_tag{0x0008, 0x0080});  // InstitutionName
            dataset.remove(dicom_tag{0x0008, 0x0081});  // InstitutionAddress
        }
        // Descriptions (may contain PHI in free text)
        if (options_.remove_descriptions) {
            dataset.remove(tags::study_description);
            dataset.remove(dicom_tag{0x0008, 0x103E});  // SeriesDescription
        }
        // Address and other contact info
        if (options_.remove_address) {
            dataset.remove(dicom_tag{0x0010, 0x1040});  // PatientAddress
            dataset.remove(dicom_tag{0x0010, 0x2154});  // PatientTelephoneNumbers
        }
        // Remove private tags unless explicitly kept
        if (!options_.keep_private_tags) {
            remove_private_tags(dataset);
        }
        // Additional PHI tags
        remove_additional_phi(dataset);
    }
References anonymize_patient_info(), anonymize_uids(), kcenon::pacs::dcm_modify::anonymize_options::keep_private_tags, options_, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::core::dicom_dataset::remove(), remove_additional_phi(), kcenon::pacs::dcm_modify::anonymize_options::remove_address, kcenon::pacs::dcm_modify::anonymize_options::remove_birth_date, kcenon::pacs::dcm_modify::anonymize_options::remove_descriptions, kcenon::pacs::dcm_modify::anonymize_options::remove_institution, remove_private_tags(), kcenon::pacs::dcm_modify::anonymize_options::remove_referring_physician, kcenon::pacs::dcm_modify::anonymize_options::replace_uids, and kcenon::pacs::core::tags::study_description.
anonymize_patient_info()
void kcenon::pacs::dcm_modify::anonymizer::anonymize_patient_info (core::dicom_dataset & dataset) inline private
Definition at line 198 of file anonymizer.h.
{
        using namespace kcenon::pacs::core;
        using namespace kcenon::pacs::encoding;
        // Patient Name
        if (!options_.patient_name_replacement.empty()) {
            dataset.set_string(tags::patient_name, vr_type::PN,
                               options_.patient_name_replacement);
        } else {
            dataset.remove(tags::patient_name);
        }
        // Patient ID
        std::string patient_id = options_.patient_id_prefix +
                                 std::to_string(++patient_counter_);
        dataset.set_string(tags::patient_id, vr_type::LO, patient_id);
        // Patient's Birth Name, Mother's Maiden Name
        dataset.remove(dicom_tag{0x0010, 0x1005});  // PatientBirthName
        dataset.remove(dicom_tag{0x0010, 0x1060});  // PatientMotherBirthName
        // Other patient IDs
        dataset.remove(dicom_tag{0x0010, 0x1000});  // OtherPatientIDs
        dataset.remove(dicom_tag{0x0010, 0x1001});  // OtherPatientNames
    }
References options_, patient_counter_, kcenon::pacs::core::tags::patient_id, kcenon::pacs::dcm_modify::anonymize_options::patient_id_prefix, kcenon::pacs::core::tags::patient_name, kcenon::pacs::dcm_modify::anonymize_options::patient_name_replacement, kcenon::pacs::core::dicom_dataset::remove(), and kcenon::pacs::core::dicom_dataset::set_string().
Referenced by anonymize().
anonymize_uids()
void kcenon::pacs::dcm_modify::anonymizer::anonymize_uids (core::dicom_dataset & dataset) inline private
Definition at line 224 of file anonymizer.h.
{
        using namespace kcenon::pacs::core;
        using namespace kcenon::pacs::encoding;
        // Study Instance UID
        auto study_uid = dataset.get_string(tags::study_instance_uid);
        if (!study_uid.empty()) {
            dataset.set_string(tags::study_instance_uid, vr_type::UI,
                               uid_mapper_.map(study_uid));
        }
        // Series Instance UID
        auto series_uid = dataset.get_string(tags::series_instance_uid);
        if (!series_uid.empty()) {
            dataset.set_string(tags::series_instance_uid, vr_type::UI,
                               uid_mapper_.map(series_uid));
        }
        // SOP Instance UID
        auto sop_uid = dataset.get_string(tags::sop_instance_uid);
        if (!sop_uid.empty()) {
            dataset.set_string(tags::sop_instance_uid, vr_type::UI,
                               uid_mapper_.map(sop_uid));
        }
        // Frame of Reference UID
        auto frame_uid = dataset.get_string(dicom_tag{0x0020, 0x0052});
        if (!frame_uid.empty()) {
            dataset.set_string(dicom_tag{0x0020, 0x0052}, vr_type::UI,
                               uid_mapper_.map(frame_uid));
        }
    }
References kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::dcm_modify::uid_mapper::map(), kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::core::tags::sop_instance_uid, kcenon::pacs::core::tags::study_instance_uid, and uid_mapper_.
Referenced by anonymize().
get_uid_mapper()
uid_mapper & kcenon::pacs::dcm_modify::anonymizer::get_uid_mapper () inline
Get the UID mapper for consistent UID replacement.
Returns
Reference to the UID mapper
Definition at line 183 of file anonymizer.h.
{ return uid_mapper_; }
References uid_mapper_.
options()
const anonymize_options & kcenon::pacs::dcm_modify::anonymizer::options () const inline
Get the current options.
Returns
Reference to the options
Definition at line 189 of file anonymizer.h.
{ return options_; }
References options_.
remove_additional_phi()
void kcenon::pacs::dcm_modify::anonymizer::remove_additional_phi (core::dicom_dataset & dataset) inline private
Definition at line 271 of file anonymizer.h.
{
        // Accession Number (may be linked to hospital records)
        dataset.remove(core::dicom_tag{0x0008, 0x0050});
        // Patient comments
        dataset.remove(core::dicom_tag{0x0010, 0x4000});
        // Study comments
        dataset.remove(core::dicom_tag{0x0032, 0x4000});
        // Requested Procedure Description
        dataset.remove(core::dicom_tag{0x0032, 0x1060});
        // Performed Procedure Step Description
        dataset.remove(core::dicom_tag{0x0040, 0x0254});
        // Device Serial Number
        dataset.remove(core::dicom_tag{0x0018, 0x1000});
    }
References kcenon::pacs::core::dicom_dataset::remove().
Referenced by anonymize().
remove_private_tags()
void kcenon::pacs::dcm_modify::anonymizer::remove_private_tags (core::dicom_dataset & dataset) inline private
Definition at line 257 of file anonymizer.h.
{
        std::vector<core::dicom_tag> private_tags;
        for (const auto& [tag, element] : dataset) {
            if (tag.is_private()) {
                private_tags.push_back(tag);
            }
        }
        for (const auto& tag : private_tags) {
            dataset.remove(tag);
        }
    }
References kcenon::pacs::core::dicom_dataset::remove().
Referenced by anonymize().
set_options()
void kcenon::pacs::dcm_modify::anonymizer::set_options (anonymize_options opts) inline
Set new options.
Parameters
opts New options
Definition at line 195 of file anonymizer.h.
{ options_ = std::move(opts); }
References options_.
Member Data Documentation
options_
anonymize_options kcenon::pacs::dcm_modify::anonymizer::options_ private
Definition at line 291 of file anonymizer.h.
Referenced by anonymize(), anonymize_patient_info(), options(), and set_options().
patient_counter_
std::atomic<uint64_t> kcenon::pacs::dcm_modify::anonymizer::patient_counter_ {0} private
Definition at line 293 of file anonymizer.h.
{0};
Referenced by anonymize_patient_info().
uid_mapper_
uid_mapper kcenon::pacs::dcm_modify::anonymizer::uid_mapper_ private
Definition at line 292 of file anonymizer.h.
Referenced by anonymize_uids(), and get_uid_mapper().
The documentation for this class was generated from the following file:
examples/dcm_modify/anonymizer.h