PACS System: kcenon::pacs::integration::logger_adapter Class Reference
kcenon::pacs::integration::logger_adapter Class Reference
Adapter for DICOM audit logging using logger_system.
#include <logger_adapter.h>
Classes
class impl
Static Public Member Functions
static void initialize (const logger_config &config)
Initialize the logger with configuration.
static void shutdown ()
Shutdown the logger.
static auto is_initialized () noexcept -> bool
Check if the logger is initialized.
template<typename... Args>
static void trace (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args)
Log a trace-level message.
template<typename... Args>
static void debug (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args)
Log a debug-level message.
template<typename... Args>
static void info (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args)
Log an info-level message.
template<typename... Args>
static void warn (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args)
Log a warning-level message.
template<typename... Args>
static void error (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args)
Log an error-level message.
template<typename... Args>
static void fatal (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args)
Log a fatal-level message.
static void log (log_level level, const std::string &message)
Log a message at the specified level.
static auto is_level_enabled (log_level level) noexcept -> bool
Check if a log level is enabled.
static void flush ()
Flush all pending log messages.
static void log_association_established (const std::string &calling_ae, const std::string &called_ae, const std::string &remote_ip)
Log DICOM association establishment.
static void log_association_released (const std::string &calling_ae, const std::string &called_ae)
Log DICOM association release.
static void log_c_store_received (const std::string &calling_ae, const std::string &patient_id, const std::string &study_uid, const std::string &sop_instance_uid, storage_status status)
Log C-STORE operation.
static void log_c_find_executed (const std::string &calling_ae, query_level level, std::size_t matches_returned)
Log C-FIND operation.
static void log_c_move_executed (const std::string &calling_ae, const std::string &destination_ae, const std::string &study_uid, std::size_t instances_moved, move_status status)
Log C-MOVE operation.
static void log_security_event (security_event_type type, const std::string &description, const std::string &user_id="")
Log a security-related event.
static void set_min_level (log_level level)
Set the minimum log level.
static auto get_min_level () noexcept -> log_level
Get the current minimum log level.
static auto get_config () -> const logger_config &
Get the current configuration.
Static Private Member Functions
static void write_audit_log (const std::string &event_type, const std::string &outcome, const std::map< std::string, std::string > &fields)
static auto storage_status_to_string (storage_status status) -> std::string
static auto move_status_to_string (move_status status) -> std::string
static auto query_level_to_string (query_level level) -> std::string
static auto security_event_to_string (security_event_type type) -> std::string
static auto log_level_to_string (log_level level) -> std::string
Static Private Attributes
static std::unique_ptr< impl > pimpl_ = nullptr
Detailed Description
Adapter for DICOM audit logging using logger_system.
This class provides a unified interface for logging in the PACS system, including:
Standard application logging (trace through fatal)
DICOM-specific audit logging for HIPAA/regulatory compliance
Security event logging for access control and intrusion detection
The adapter uses logger_system's high-performance async logging (4.34M msg/s) internally while providing a PACS-specific API.
Thread Safety: All methods are thread-safe.
Definition at line 184 of file logger_adapter.h.
Member Function Documentation
debug()
template<typename... Args> static void kcenon::pacs::integration::logger_adapter::debug (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args) inline static
Log a debug-level message.
Template Parameters
Args Format argument types
Parameters
fmt Format string (std::format syntax)
args Format arguments
Definition at line 237 of file logger_adapter.h.
{
        log(log_level::debug, kcenon::pacs::compat::format(fmt, std::forward<Args>(args)...));
    }
References kcenon::pacs::integration::debug, and log().
Referenced by kcenon::pacs::workflow::task_scheduler::create_archive_callback(), kcenon::pacs::workflow::task_scheduler::create_cleanup_callback(), kcenon::pacs::workflow::task_scheduler::create_verification_callback(), http_client::del(), kcenon::pacs::workflow::task_scheduler::execute_task(), http_client::get(), kcenon::pacs::workflow::task_scheduler::load_tasks(), kcenon::pacs::workflow::auto_prefetch_service::on_worklist_query(), http_client::post(), kcenon::pacs::workflow::auto_prefetch_service::prefetch_study(), kcenon::pacs::workflow::auto_prefetch_service::process_request(), kcenon::pacs::workflow::auto_prefetch_service::query_prior_studies(), kcenon::pacs::workflow::auto_prefetch_service::run_loop(), kcenon::pacs::workflow::task_scheduler::run_loop(), and kcenon::pacs::workflow::task_scheduler::save_tasks().
error()
template<typename... Args> static void kcenon::pacs::integration::logger_adapter::error (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args) inline static
Log an error-level message.
Template Parameters
Args Format argument types
Parameters
fmt Format string (std::format syntax)
args Format arguments
Definition at line 270 of file logger_adapter.h.
{
        log(log_level::error, kcenon::pacs::compat::format(fmt, std::forward<Args>(args)...));
    }
References kcenon::pacs::integration::error, and log().
Referenced by kcenon::pacs::workflow::task_scheduler::create_archive_callback(), kcenon::pacs::workflow::task_scheduler::create_cleanup_callback(), kcenon::pacs::workflow::task_scheduler::create_verification_callback(), kcenon::pacs::workflow::task_scheduler::execute_task(), kcenon::pacs::workflow::task_scheduler::load_tasks(), kcenon::pacs::workflow::auto_prefetch_service::prefetch_study(), kcenon::pacs::workflow::auto_prefetch_service::query_prior_studies(), ai_service_connector::impl::request_inference(), and kcenon::pacs::workflow::task_scheduler::save_tasks().
fatal()
template<typename... Args> static void kcenon::pacs::integration::logger_adapter::fatal (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args) inline static
Log a fatal-level message.
Template Parameters
Args Format argument types
Parameters
fmt Format string (std::format syntax)
args Format arguments
Definition at line 281 of file logger_adapter.h.
{
        log(log_level::fatal, kcenon::pacs::compat::format(fmt, std::forward<Args>(args)...));
    }
References kcenon::pacs::integration::fatal, and log().
flush()
void kcenon::pacs::integration::logger_adapter::flush () static
Flush all pending log messages.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 342 of file logger_adapter.cpp.
{}
get_config()
auto kcenon::pacs::integration::logger_adapter::get_config () -> const logger_config& static nodiscard
Get the current configuration.
Returns
Current logger configuration
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 346 of file logger_adapter.cpp.
{
    static const logger_config default_config;
    return default_config;
}
get_min_level()
auto kcenon::pacs::integration::logger_adapter::get_min_level () -> log_level static nodiscard noexcept
Get the current minimum log level.
Returns
Current minimum log level
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 344 of file logger_adapter.cpp.
{ return log_level::off; }
References kcenon::pacs::integration::off.
info()
template<typename... Args> static void kcenon::pacs::integration::logger_adapter::info (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args) inline static
Log an info-level message.
Template Parameters
Args Format argument types
Parameters
fmt Format string (std::format syntax)
args Format arguments
Definition at line 248 of file logger_adapter.h.
{
        log(log_level::info, kcenon::pacs::compat::format(fmt, std::forward<Args>(args)...));
    }
References kcenon::pacs::integration::info, and log().
Referenced by ai_service_connector::impl::cancel(), kcenon::pacs::workflow::task_scheduler::cancel_task(), kcenon::pacs::workflow::task_scheduler::create_archive_callback(), kcenon::pacs::workflow::task_scheduler::create_cleanup_callback(), kcenon::pacs::workflow::task_scheduler::create_verification_callback(), kcenon::pacs::workflow::auto_prefetch_service::execute_cycle(), kcenon::pacs::workflow::task_scheduler::execute_cycle(), kcenon::pacs::workflow::task_scheduler::execute_task(), ai_service_connector::impl::initialize(), kcenon::pacs::workflow::task_scheduler::load_tasks(), kcenon::pacs::workflow::task_scheduler::pause_task(), kcenon::pacs::workflow::auto_prefetch_service::prefetch_study(), ai_service_connector::impl::request_inference(), kcenon::pacs::workflow::task_scheduler::resume_task(), kcenon::pacs::workflow::task_scheduler::schedule(), ai_service_connector::impl::shutdown(), kcenon::pacs::workflow::auto_prefetch_service::start(), kcenon::pacs::workflow::task_scheduler::start(), kcenon::pacs::workflow::auto_prefetch_service::stop(), kcenon::pacs::workflow::task_scheduler::stop(), kcenon::pacs::workflow::task_scheduler::trigger_task(), ai_service_connector::impl::update_credentials(), and kcenon::pacs::workflow::task_scheduler::update_schedule().
initialize()
void kcenon::pacs::integration::logger_adapter::initialize (const logger_config & config) static
Initialize the logger with configuration.
Must be called before any logging operations. Sets up console and file writers, configures log levels, and initializes the audit logger if enabled.
Parameters
config Configuration options
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 337 of file logger_adapter.cpp.
{}
is_initialized()
auto kcenon::pacs::integration::logger_adapter::is_initialized () -> bool static nodiscard noexcept
Check if the logger is initialized.
Returns
true if initialized, false otherwise
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 339 of file logger_adapter.cpp.
{ return false; }
is_level_enabled()
auto kcenon::pacs::integration::logger_adapter::is_level_enabled (log_level level) -> bool static nodiscard noexcept
Check if a log level is enabled.
Parameters
level The level to check
Returns
true if messages at this level will be logged
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 341 of file logger_adapter.cpp.
{ return false; }
Referenced by kcenon::pacs::di::LoggerService::is_enabled().
log()
void kcenon::pacs::integration::logger_adapter::log (log_level level, const std::string & message) static
Log a message at the specified level.
Parameters
level Log severity level
message The message to log
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 340 of file logger_adapter.cpp.
{}
Referenced by kcenon::pacs::di::LoggerService::debug(), debug(), kcenon::pacs::di::LoggerService::error(), error(), kcenon::pacs::di::LoggerService::fatal(), fatal(), kcenon::pacs::di::LoggerService::info(), info(), kcenon::pacs::di::LoggerService::trace(), trace(), kcenon::pacs::di::LoggerService::warn(), and warn().
log_association_established()
void kcenon::pacs::integration::logger_adapter::log_association_established (const std::string & calling_ae, const std::string & called_ae, const std::string & remote_ip) static
Log DICOM association establishment.
Records when a remote system connects and establishes a DICOM association.
Parameters
calling_ae AE title of the remote system
called_ae AE title of this system
remote_ip IP address of the remote system
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 362 of file logger_adapter.cpp.
{
    info("Association established: {} -> {} from {}",
         calling_ae, called_ae, remote_ip);
    write_audit_log("ASSOCIATION_ESTABLISHED", "success",
                    {{"calling_ae", calling_ae},
                     {"called_ae", called_ae},
                     {"remote_ip", remote_ip}});
}
References kcenon::pacs::integration::info, and write_audit_log().
log_association_released()
void kcenon::pacs::integration::logger_adapter::log_association_released (const std::string & calling_ae, const std::string & called_ae) static
Log DICOM association release.
Records when a DICOM association is gracefully released.
Parameters
calling_ae AE title of the remote system
called_ae AE title of this system
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 374 of file logger_adapter.cpp.
{
    debug("Association released: {} -> {}", calling_ae, called_ae);
    write_audit_log("ASSOCIATION_RELEASED", "success",
                    {{"calling_ae", calling_ae}, {"called_ae", called_ae}});
}
References kcenon::pacs::integration::debug, and write_audit_log().
log_c_find_executed()
void kcenon::pacs::integration::logger_adapter::log_c_find_executed (const std::string & calling_ae, query_level level, std::size_t matches_returned) static
Log C-FIND operation.
Records when a query is executed against the PACS database.
Parameters
calling_ae AE title of the querying system
level Query retrieve level (patient, study, series, image)
matches_returned Number of matching records returned
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 406 of file logger_adapter.cpp.
{
    auto level_str = query_level_to_string(level);
    debug("C-FIND executed: level={} matches={} from {}",
          level_str, matches_returned, calling_ae);
    write_audit_log("C-FIND", "success",
                    {{"calling_ae", calling_ae},
                     {"query_level", level_str},
                     {"matches_returned", std::to_string(matches_returned)}});
}
References kcenon::pacs::integration::debug, query_level_to_string(), and write_audit_log().
log_c_move_executed()
void kcenon::pacs::integration::logger_adapter::log_c_move_executed (const std::string & calling_ae, const std::string & destination_ae, const std::string & study_uid, std::size_t instances_moved, move_status status) static
Log C-MOVE operation.
Records when images are transferred to another system.
Parameters
calling_ae AE title requesting the move
destination_ae AE title of the destination
study_uid Study Instance UID being moved
instances_moved Number of instances successfully moved
status Status of the move operation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 420 of file logger_adapter.cpp.
{
    auto outcome = (status == move_status::success ||
                    status == move_status::partial_success)
                       ? "success"
                       : "failure";
    auto status_str = move_status_to_string(status);
    if (status == move_status::success) {
        info("C-MOVE completed: study={} instances={} to {} from {}",
             study_uid, instances_moved, destination_ae, calling_ae);
    } else {
        warn("C-MOVE failed: study={} status={} to {} from {}",
             study_uid, status_str, destination_ae, calling_ae);
    }
    write_audit_log("C-MOVE", outcome,
                    {{"calling_ae", calling_ae},
                     {"destination_ae", destination_ae},
                     {"study_uid", study_uid},
                     {"instances_moved", std::to_string(instances_moved)},
                     {"status", status_str}});
}
References kcenon::pacs::integration::info, move_status_to_string(), kcenon::pacs::integration::partial_success, kcenon::pacs::integration::success, kcenon::pacs::integration::warn, and write_audit_log().
log_c_store_received()
void kcenon::pacs::integration::logger_adapter::log_c_store_received (const std::string & calling_ae, const std::string & patient_id, const std::string & study_uid, const std::string & sop_instance_uid, storage_status status) static
Log C-STORE operation.
Records when a DICOM object is received via C-STORE. This is critical for HIPAA audit trail requirements.
Parameters
calling_ae AE title of the sender
patient_id Patient ID from the received object
study_uid Study Instance UID
sop_instance_uid SOP Instance UID of the stored object
status Status of the storage operation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 382 of file logger_adapter.cpp.
{
    auto outcome = (status == storage_status::success) ? "success" : "failure";
    auto status_str = storage_status_to_string(status);
    if (status == storage_status::success) {
        info("C-STORE received: patient={} study={} instance={} from {}",
             patient_id, study_uid, sop_instance_uid, calling_ae);
    } else {
        warn("C-STORE failed: patient={} status={} from {}",
             patient_id, status_str, calling_ae);
    }
    write_audit_log("C-STORE", outcome,
                    {{"calling_ae", calling_ae},
                     {"patient_id", patient_id},
                     {"study_uid", study_uid},
                     {"sop_instance_uid", sop_instance_uid},
                     {"status", status_str}});
}
References kcenon::pacs::integration::info, storage_status_to_string(), kcenon::pacs::integration::success, kcenon::pacs::integration::warn, and write_audit_log().
log_level_to_string()
auto kcenon::pacs::integration::logger_adapter::log_level_to_string (log_level level) -> std::string static nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 563 of file logger_adapter.cpp.
{
    switch (level) {
        case log_level::trace:
            return "TRACE";
        case log_level::debug:
            return "DEBUG";
        case log_level::info:
            return "INFO";
        case log_level::warn:
            return "WARN";
        case log_level::error:
            return "ERROR";
        case log_level::fatal:
            return "FATAL";
        case log_level::off:
        default:
            return "OFF";
    }
}
References kcenon::pacs::integration::debug, kcenon::pacs::integration::error, kcenon::pacs::integration::fatal, kcenon::pacs::integration::info, kcenon::pacs::integration::off, kcenon::pacs::integration::trace, and kcenon::pacs::integration::warn.
log_security_event()
void kcenon::pacs::integration::logger_adapter::log_security_event (security_event_type type, const std::string & description, const std::string & user_id = "") static
Log a security-related event.
Records security events for audit and intrusion detection.
Parameters
type Type of security event
description Human-readable description
user_id Optional user or system identifier
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 447 of file logger_adapter.cpp.
{
    auto type_str = security_event_to_string(type);
    // Security events are always logged at warn level or higher
    switch (type) {
        case security_event_type::authentication_success:
            info("Security event: {} - {}", type_str, description);
            break;
        case security_event_type::authentication_failure:
        case security_event_type::access_denied:
        case security_event_type::association_rejected:
        case security_event_type::invalid_request:
            warn("Security event: {} - {}", type_str, description);
            break;
        case security_event_type::configuration_change:
        case security_event_type::data_export:
            info("Security event: {} - {}", type_str, description);
            break;
    }
    std::map<std::string, std::string> fields = {
        {"security_event", type_str}, {"description", description}};
    if (!user_id.empty()) {
        fields["user_id"] = user_id;
    }
    write_audit_log("SECURITY", security_event_to_string(type), fields);
}
References kcenon::pacs::integration::access_denied, kcenon::pacs::integration::association_rejected, kcenon::pacs::integration::authentication_failure, kcenon::pacs::integration::authentication_success, kcenon::pacs::integration::configuration_change, kcenon::pacs::integration::data_export, kcenon::pacs::integration::info, kcenon::pacs::integration::invalid_request, security_event_to_string(), kcenon::pacs::integration::warn, and write_audit_log().
move_status_to_string()
auto kcenon::pacs::integration::logger_adapter::move_status_to_string (move_status status) -> std::string static nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 505 of file logger_adapter.cpp.
{
    switch (status) {
        case move_status::success:
            return "Success";
        case move_status::partial_success:
            return "PartialSuccess";
        case move_status::refused_out_of_resources:
            return "RefusedOutOfResources";
        case move_status::refused_move_destination_unknown:
            return "RefusedMoveDestinationUnknown";
        case move_status::identifier_does_not_match:
            return "IdentifierDoesNotMatch";
        case move_status::unable_to_process:
            return "UnableToProcess";
        case move_status::cancelled:
            return "Cancelled";
        case move_status::unknown_error:
        default:
            return "UnknownError";
    }
}
References kcenon::pacs::integration::cancelled, kcenon::pacs::integration::identifier_does_not_match, kcenon::pacs::integration::partial_success, kcenon::pacs::integration::refused_move_destination_unknown, kcenon::pacs::integration::refused_out_of_resources, kcenon::pacs::integration::success, kcenon::pacs::integration::unable_to_process, and kcenon::pacs::integration::unknown_error.
Referenced by log_c_move_executed().
query_level_to_string()
auto kcenon::pacs::integration::logger_adapter::query_level_to_string (query_level level) -> std::string static nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 527 of file logger_adapter.cpp.
{
    switch (level) {
        case query_level::patient:
            return "PATIENT";
        case query_level::study:
            return "STUDY";
        case query_level::series:
            return "SERIES";
        case query_level::image:
            return "IMAGE";
        default:
            return "UNKNOWN";
    }
}
References kcenon::pacs::integration::image, kcenon::pacs::integration::patient, kcenon::pacs::integration::series, and kcenon::pacs::integration::study.
Referenced by log_c_find_executed().
security_event_to_string()
auto kcenon::pacs::integration::logger_adapter::security_event_to_string (security_event_type type) -> std::string static nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 542 of file logger_adapter.cpp.
{
    switch (type) {
        case security_event_type::authentication_success:
            return "authentication_success";
        case security_event_type::authentication_failure:
            return "authentication_failure";
        case security_event_type::access_denied:
            return "access_denied";
        case security_event_type::configuration_change:
            return "configuration_change";
        case security_event_type::data_export:
            return "data_export";
        case security_event_type::association_rejected:
            return "association_rejected";
        case security_event_type::invalid_request:
            return "invalid_request";
        default:
            return "unknown";
    }
}
References kcenon::pacs::integration::access_denied, kcenon::pacs::integration::association_rejected, kcenon::pacs::integration::authentication_failure, kcenon::pacs::integration::authentication_success, kcenon::pacs::integration::configuration_change, kcenon::pacs::integration::data_export, and kcenon::pacs::integration::invalid_request.
Referenced by log_security_event().
set_min_level()
void kcenon::pacs::integration::logger_adapter::set_min_level (log_level level) static
Set the minimum log level.
Parameters
level New minimum log level
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 343 of file logger_adapter.cpp.
{}
shutdown()
void kcenon::pacs::integration::logger_adapter::shutdown () static
Shutdown the logger.
Flushes all pending messages and releases resources. Should be called before application exit.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 338 of file logger_adapter.cpp.
{}
storage_status_to_string()
auto kcenon::pacs::integration::logger_adapter::storage_status_to_string (storage_status status) -> std::string static nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 483 of file logger_adapter.cpp.
{
    switch (status) {
        case storage_status::success:
            return "Success";
        case storage_status::out_of_resources:
            return "OutOfResources";
        case storage_status::dataset_error:
            return "DataSetError";
        case storage_status::cannot_understand:
            return "CannotUnderstand";
        case storage_status::processing_failure:
            return "ProcessingFailure";
        case storage_status::duplicate_rejected:
            return "DuplicateRejected";
        case storage_status::duplicate_stored:
            return "DuplicateStored";
        case storage_status::unknown_error:
        default:
            return "UnknownError";
    }
}
References kcenon::pacs::integration::cannot_understand, kcenon::pacs::integration::dataset_error, kcenon::pacs::integration::duplicate_rejected, kcenon::pacs::integration::duplicate_stored, kcenon::pacs::integration::out_of_resources, kcenon::pacs::integration::processing_failure, kcenon::pacs::integration::success, and kcenon::pacs::integration::unknown_error.
Referenced by log_c_store_received().
trace()
template<typename... Args> static void kcenon::pacs::integration::logger_adapter::trace (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args) inline static
Log a trace-level message.
Template Parameters
Args Format argument types
Parameters
fmt Format string (std::format syntax)
args Format arguments
Definition at line 226 of file logger_adapter.h.
{
        log(log_level::trace, kcenon::pacs::compat::format(fmt, std::forward<Args>(args)...));
    }
References log(), and kcenon::pacs::integration::trace.
warn()
template<typename... Args> static void kcenon::pacs::integration::logger_adapter::warn (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args) inline static
Log a warning-level message.
Template Parameters
Args Format argument types
Parameters
fmt Format string (std::format syntax)
args Format arguments
Definition at line 259 of file logger_adapter.h.
{
        log(log_level::warn, kcenon::pacs::compat::format(fmt, std::forward<Args>(args)...));
    }
References log(), and kcenon::pacs::integration::warn.
Referenced by kcenon::pacs::workflow::task_scheduler::create_archive_callback(), kcenon::pacs::workflow::task_scheduler::create_cleanup_callback(), kcenon::pacs::workflow::task_scheduler::create_verification_callback(), kcenon::pacs::workflow::task_scheduler::deserialize_tasks(), kcenon::pacs::workflow::task_scheduler::execute_task(), and ai_service_connector::impl::initialize().
write_audit_log()
void kcenon::pacs::integration::logger_adapter::write_audit_log (const std::string & event_type, const std::string & outcome, const std::map< std::string, std::string > & fields) static private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 351 of file logger_adapter.cpp.
                                         {}
Referenced by log_association_established(), log_association_released(), log_c_find_executed(), log_c_move_executed(), log_c_store_received(), and log_security_event().
Member Data Documentation
pimpl_
std::unique_ptr< logger_adapter::impl > kcenon::pacs::integration::logger_adapter::pimpl_ = nullptr static private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/logger_adapter.h.
Definition at line 430 of file logger_adapter.h.
The documentation for this class was generated from the following files:
include/kcenon/pacs/integration/logger_adapter.h
src/integration/logger_adapter.cpp