PACS System: kcenon::pacs::services::validation::rt_structure_set_iod_validator Class Reference
kcenon::pacs::services::validation::rt_structure_set_iod_validator Class Reference
Validator for RT Structure Set IODs.
#include <rt_iod_validator.h>
Public Member Functions
rt_structure_set_iod_validator ()=default
rt_structure_set_iod_validator (const rt_validation_options &options)
validation_result validate (const core::dicom_dataset &dataset) const
bool quick_check (const core::dicom_dataset &dataset) const
const rt_validation_options & options () const noexcept
void set_options (const rt_validation_options &options)
Private Member Functions
void validate_patient_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_study_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_rt_series_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_structure_set_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_roi_contour_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_rt_roi_observations_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_sop_common_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_type1_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_type2_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_roi_consistency (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
Private Attributes
rt_validation_options options_
Detailed Description
Validator for RT Structure Set IODs.
Validates DICOM datasets against the RT Structure Set IOD specification. Checks ROI definitions, contours, and referenced frame of reference.
Validated Modules
Mandatory Modules
Patient Module (M)
General Study Module (M)
RT Series Module (M)
General Equipment Module (M)
Structure Set Module (M)
ROI Contour Module (M)
RT ROI Observations Module (M)
Approval Module (U)
SOP Common Module (M)
Definition at line 267 of file rt_iod_validator.h.
Constructor & Destructor Documentation
rt_structure_set_iod_validator() [1/2]
kcenon::pacs::services::validation::rt_structure_set_iod_validator::rt_structure_set_iod_validator () default
rt_structure_set_iod_validator() [2/2]
kcenon::pacs::services::validation::rt_structure_set_iod_validator::rt_structure_set_iod_validator (const rt_validation_options & options) explicit
Definition at line 780 of file rt_iod_validator.cpp.
    : options_(options) {}
Member Function Documentation
check_roi_consistency()
void kcenon::pacs::services::validation::rt_structure_set_iod_validator::check_roi_consistency (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 1034 of file rt_iod_validator.cpp.
{
    // Check that ROI Contour Sequence items reference valid ROIs from Structure Set ROI Sequence
    // This is a simplified check - full implementation would iterate through sequences
    if (dataset.contains(rt_tags::structure_set_roi_sequence) &&
        dataset.contains(rt_tags::roi_contour_sequence)) {
        // Both sequences present - good
    } else if (dataset.contains(rt_tags::structure_set_roi_sequence) &&
               !dataset.contains(rt_tags::roi_contour_sequence)) {
        findings.push_back({
            validation_severity::warning,
            rt_tags::roi_contour_sequence,
            "StructureSetROISequence present but ROIContourSequence missing - ROIs have no contours",
            "RTSTRUCT-WARN-002"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::rt_tags::roi_contour_sequence, kcenon::pacs::services::validation::rt_tags::structure_set_roi_sequence, and kcenon::pacs::services::validation::warning.
Referenced by validate().
check_type1_attribute()
void kcenon::pacs::services::validation::rt_structure_set_iod_validator::check_type1_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Definition at line 989 of file rt_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::error,
            tag,
            std::string("Type 1 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "RTSTRUCT-TYPE1-MISSING"
        });
    } else {
        auto value = dataset.get_string(tag);
        if (value.empty()) {
            findings.push_back({
                validation_severity::error,
                tag,
                std::string("Type 1 attribute has empty value: ") +
                std::string(name) + " (" + tag.to_string() + ")",
                "RTSTRUCT-TYPE1-EMPTY"
            });
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), name, and kcenon::pacs::core::dicom_tag::to_string().
Referenced by validate_general_study_module(), validate_roi_contour_module(), validate_rt_roi_observations_module(), validate_rt_series_module(), validate_sop_common_module(), and validate_structure_set_module().
check_type2_attribute()
void kcenon::pacs::services::validation::rt_structure_set_iod_validator::check_type2_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Definition at line 1017 of file rt_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::warning,
            tag,
            std::string("Type 2 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "RTSTRUCT-TYPE2-MISSING"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), name, kcenon::pacs::core::dicom_tag::to_string(), and kcenon::pacs::services::validation::warning.
Referenced by validate_general_study_module(), validate_patient_module(), and validate_structure_set_module().
options()
const rt_validation_options & kcenon::pacs::services::validation::rt_structure_set_iod_validator::options () const nodiscard noexcept
Definition at line 836 of file rt_iod_validator.cpp.
{
    return options_;
}
References options_.
Referenced by set_options().
quick_check()
bool kcenon::pacs::services::validation::rt_structure_set_iod_validator::quick_check (const core::dicom_dataset & dataset) const nodiscard
Definition at line 820 of file rt_iod_validator.cpp.
{
    if (!dataset.contains(tags::study_instance_uid)) return false;
    if (!dataset.contains(tags::series_instance_uid)) return false;
    if (!dataset.contains(tags::modality)) return false;
    auto modality = dataset.get_string(tags::modality);
    if (modality != "RTSTRUCT") return false;
    if (!dataset.contains(rt_tags::structure_set_label)) return false;
    if (!dataset.contains(rt_tags::structure_set_roi_sequence)) return false;
    if (!dataset.contains(tags::sop_class_uid)) return false;
    if (!dataset.contains(tags::sop_instance_uid)) return false;
    return true;
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, kcenon::pacs::services::validation::rt_tags::structure_set_label, kcenon::pacs::services::validation::rt_tags::structure_set_roi_sequence, and kcenon::pacs::core::tags::study_instance_uid.
Referenced by kcenon::pacs::services::validation::is_valid_rt_structure_set_dataset().
set_options()
void kcenon::pacs::services::validation::rt_structure_set_iod_validator::set_options (const rt_validation_options & options)
Definition at line 840 of file rt_iod_validator.cpp.
{
    options_ = options;
}
References options(), and options_.
validate()
validation_result kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate (const core::dicom_dataset & dataset) const nodiscard
Definition at line 783 of file rt_iod_validator.cpp.
{
    validation_result result;
    result.is_valid = true;
    // Validate mandatory modules
    if (options_.check_type1 || options_.check_type2) {
        validate_patient_module(dataset, result.findings);
        validate_general_study_module(dataset, result.findings);
        validate_rt_series_module(dataset, result.findings);
        validate_structure_set_module(dataset, result.findings);
        validate_sop_common_module(dataset, result.findings);
    }
    // RT Structure Set specific validation
    if (options_.validate_rt_structure_set) {
        validate_roi_contour_module(dataset, result.findings);
        validate_rt_roi_observations_module(dataset, result.findings);
    }
    // Check ROI consistency
    check_roi_consistency(dataset, result.findings);
    // Check for errors
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
        if (options_.strict_mode && finding.severity == validation_severity::warning) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References check_roi_consistency(), kcenon::pacs::services::validation::rt_validation_options::check_type1, kcenon::pacs::services::validation::rt_validation_options::check_type2, kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::services::validation::validation_result::is_valid, options_, kcenon::pacs::services::validation::rt_validation_options::strict_mode, validate_general_study_module(), validate_patient_module(), validate_roi_contour_module(), validate_rt_roi_observations_module(), validate_rt_series_module(), kcenon::pacs::services::validation::rt_validation_options::validate_rt_structure_set, validate_sop_common_module(), validate_structure_set_module(), and kcenon::pacs::services::validation::warning.
Referenced by kcenon::pacs::services::validation::rt_iod_validator::validate(), and kcenon::pacs::services::validation::validate_rt_structure_set_iod().
validate_general_study_module()
void kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_general_study_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 856 of file rt_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::study_instance_uid, "StudyInstanceUID", findings);
    }
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::study_date, "StudyDate", findings);
        check_type2_attribute(dataset, tags::study_time, "StudyTime", findings);
        check_type2_attribute(dataset, tags::study_id, "StudyID", findings);
        check_type2_attribute(dataset, tags::accession_number, "AccessionNumber", findings);
    }
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::rt_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::core::tags::study_time.
Referenced by validate().
validate_patient_module()
void kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_patient_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 844 of file rt_iod_validator.cpp.
{
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::patient_name, "PatientName", findings);
        check_type2_attribute(dataset, tags::patient_id, "PatientID", findings);
        check_type2_attribute(dataset, tags::patient_birth_date, "PatientBirthDate", findings);
        check_type2_attribute(dataset, tags::patient_sex, "PatientSex", findings);
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, and kcenon::pacs::core::tags::patient_sex.
Referenced by validate().
validate_roi_contour_module()
void kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_roi_contour_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 924 of file rt_iod_validator.cpp.
{
    // ROI Contour Sequence is Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, rt_tags::roi_contour_sequence, "ROIContourSequence", findings);
    }
    // ROI Display Color is Type 3 but useful
    if (!dataset.contains(rt_tags::roi_display_color)) {
        findings.push_back({
            validation_severity::info,
            rt_tags::roi_display_color,
            "ROIDisplayColor not present - ROIs will use default colors",
            "RTSTRUCT-INFO-001"
        });
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::info, options_, kcenon::pacs::services::validation::rt_tags::roi_contour_sequence, and kcenon::pacs::services::validation::rt_tags::roi_display_color.
Referenced by validate().
validate_rt_roi_observations_module()
void kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_rt_roi_observations_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 944 of file rt_iod_validator.cpp.
{
    // RT ROI Observations Sequence is Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, rt_tags::rt_roi_observations_sequence,
                              "RTROIObservationsSequence", findings);
    }
    // Check for RT ROI Interpreted Type
    if (dataset.contains(rt_tags::rt_roi_observations_sequence)) {
        if (!dataset.contains(rt_tags::rt_roi_interpreted_type)) {
            findings.push_back({
                validation_severity::info,
                rt_tags::rt_roi_interpreted_type,
                "RTROIInterpretedType not specified - ROI semantic meaning not defined",
                "RTSTRUCT-INFO-002"
            });
        }
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::info, options_, kcenon::pacs::services::validation::rt_tags::rt_roi_interpreted_type, and kcenon::pacs::services::validation::rt_tags::rt_roi_observations_sequence.
Referenced by validate().
validate_rt_series_module()
void kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_rt_series_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 872 of file rt_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::modality, "Modality", findings);
        check_type1_attribute(dataset, tags::series_instance_uid, "SeriesInstanceUID", findings);
        if (dataset.contains(tags::modality)) {
            auto modality = dataset.get_string(tags::modality);
            if (modality != "RTSTRUCT") {
                findings.push_back({
                    validation_severity::error,
                    tags::modality,
                    "Modality must be 'RTSTRUCT' for RT Structure Set, found: " + modality,
                    "RTSTRUCT-ERR-001"
                });
            }
        }
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::modality, options_, and kcenon::pacs::core::tags::series_instance_uid.
Referenced by validate().
validate_sop_common_module()
void kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_sop_common_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 967 of file rt_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::sop_class_uid, "SOPClassUID", findings);
        check_type1_attribute(dataset, tags::sop_instance_uid, "SOPInstanceUID", findings);
    }
    if (dataset.contains(tags::sop_class_uid)) {
        auto sop_class = dataset.get_string(tags::sop_class_uid);
        if (sop_class != sop_classes::rt_structure_set_storage_uid) {
            findings.push_back({
                validation_severity::error,
                tags::sop_class_uid,
                "SOPClassUID is not RT Structure Set Storage: " + sop_class,
                "RTSTRUCT-ERR-002"
            });
        }
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), options_, kcenon::pacs::services::sop_classes::rt_structure_set_storage_uid, kcenon::pacs::core::tags::sop_class_uid, and kcenon::pacs::core::tags::sop_instance_uid.
Referenced by validate().
validate_structure_set_module()
void kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_structure_set_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 894 of file rt_iod_validator.cpp.
{
    // Type 1 attributes
    if (options_.check_type1) {
        check_type1_attribute(dataset, rt_tags::structure_set_label, "StructureSetLabel", findings);
        check_type1_attribute(dataset, rt_tags::structure_set_roi_sequence,
                              "StructureSetROISequence", findings);
    }
    // Type 2 attributes
    if (options_.check_type2) {
        check_type2_attribute(dataset, rt_tags::structure_set_date, "StructureSetDate", findings);
        check_type2_attribute(dataset, rt_tags::structure_set_time, "StructureSetTime", findings);
    }
    // ReferencedFrameOfReferenceSequence is important for spatial registration
    if (options_.validate_references) {
        if (!dataset.contains(rt_tags::referenced_frame_of_reference_sequence)) {
            findings.push_back({
                validation_severity::warning,
                rt_tags::referenced_frame_of_reference_sequence,
                "ReferencedFrameOfReferenceSequence not present - structures have no spatial reference",
                "RTSTRUCT-WARN-001"
            });
        }
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::rt_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::dicom_dataset::contains(), options_, kcenon::pacs::services::validation::rt_tags::referenced_frame_of_reference_sequence, kcenon::pacs::services::validation::rt_tags::structure_set_date, kcenon::pacs::services::validation::rt_tags::structure_set_label, kcenon::pacs::services::validation::rt_tags::structure_set_roi_sequence, kcenon::pacs::services::validation::rt_tags::structure_set_time, kcenon::pacs::services::validation::rt_validation_options::validate_references, and kcenon::pacs::services::validation::warning.
Referenced by validate().
Member Data Documentation
options_
rt_validation_options kcenon::pacs::services::validation::rt_structure_set_iod_validator::options_ private
Definition at line 323 of file rt_iod_validator.h.
Referenced by options(), set_options(), validate(), validate_general_study_module(), validate_patient_module(), validate_roi_contour_module(), validate_rt_roi_observations_module(), validate_rt_series_module(), validate_sop_common_module(), and validate_structure_set_module().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/validation/rt_iod_validator.h
src/services/validation/rt_iod_validator.cpp