PACS System: kcenon::pacs::integration::monitoring_adapter Class Reference
kcenon::pacs::integration::monitoring_adapter Class Reference
Adapter for PACS performance metrics and distributed tracing.
#include <monitoring_adapter.h>
Classes
struct health_status
Health check result containing component status.
class impl
class span
Represents a unit of work in distributed tracing.
Static Public Member Functions
static void initialize (const monitoring_config &config)
Initialize the monitoring adapter with configuration.
static void shutdown ()
Shutdown the monitoring adapter.
static auto is_initialized () noexcept -> bool
Check if the monitoring adapter is initialized.
static void increment_counter (std::string_view name, std::int64_t value=1)
Increment a counter metric.
static void set_gauge (std::string_view name, double value)
Set a gauge metric value.
static void record_histogram (std::string_view name, double value)
Record a histogram sample.
static void record_timing (std::string_view name, std::chrono::nanoseconds duration)
Record a timing measurement.
static void record_c_store (std::chrono::nanoseconds duration, std::size_t bytes, bool success)
Record C-STORE operation metrics.
static void record_c_find (std::chrono::nanoseconds duration, std::size_t matches, query_level level)
Record C-FIND operation metrics.
static void record_association (const std::string &calling_ae, bool established)
Record DICOM association metrics.
static void update_storage_stats (std::size_t total_instances, std::size_t total_bytes)
Update storage statistics.
static auto start_span (std::string_view operation) -> span
Start a new trace span.
static auto get_health () -> health_status
Get current health status.
static void register_health_check (std::string_view component, std::function< bool()> check)
Register a health check for a component.
static void unregister_health_check (std::string_view component)
Unregister a health check.
static auto get_config () -> const monitoring_config &
Get the current configuration.
Static Private Member Functions
static auto query_level_to_string (query_level level) -> std::string
Static Private Attributes
static std::unique_ptr< impl > pimpl_
Detailed Description
Adapter for PACS performance metrics and distributed tracing.
This class provides a unified interface for monitoring in the PACS system, including:
Performance metrics (counters, gauges, histograms, timing)
DICOM-specific metrics (C-STORE, C-FIND, associations, storage)
Distributed tracing for request tracking across services
Health check endpoints for component status
The adapter uses monitoring_system's high-performance profiling internally while providing a PACS-specific API.
Thread Safety: All methods are thread-safe.
Definition at line 128 of file monitoring_adapter.h.
Member Function Documentation
get_config()
auto kcenon::pacs::integration::monitoring_adapter::get_config () -> const monitoring_config& static nodiscard
Get the current configuration.
Returns
Current monitoring configuration
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 489 of file monitoring_adapter.cpp.
{
    return pimpl_->get_config();
}
References kcenon::pacs::integration::monitoring_adapter::impl::get_config(), and pimpl_.
get_health()
auto kcenon::pacs::integration::monitoring_adapter::get_health () -> health_status static nodiscard
Get current health status.
Returns
Health status of all registered components
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 472 of file monitoring_adapter.cpp.
{
    return pimpl_->get_health();
}
References kcenon::pacs::integration::monitoring_adapter::impl::get_health(), and pimpl_.
increment_counter()
void kcenon::pacs::integration::monitoring_adapter::increment_counter (std::string_view name, std::int64_t value = 1) static
Increment a counter metric.
Parameters
name The counter name
value The value to add (default: 1)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 416 of file monitoring_adapter.cpp.
{
    pimpl_->increment_counter(name, value);
}
References kcenon::pacs::integration::monitoring_adapter::impl::increment_counter(), name, and pimpl_.
Referenced by kcenon::pacs::workflow::auto_prefetch_service::execute_cycle(), kcenon::pacs::workflow::task_scheduler::execute_cycle(), kcenon::pacs::workflow::task_scheduler::execute_task(), ai_service_connector::impl::request_inference(), and job_tracker::update_status().
initialize()
void kcenon::pacs::integration::monitoring_adapter::initialize (const monitoring_config & config) static
Initialize the monitoring adapter with configuration.
Must be called before any monitoring operations. Sets up metrics collection, tracing, and health check endpoints if configured.
Parameters
config Configuration options
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 402 of file monitoring_adapter.cpp.
{
    pimpl_->initialize(config);
}
References kcenon::pacs::integration::monitoring_adapter::impl::initialize(), and pimpl_.
is_initialized()
auto kcenon::pacs::integration::monitoring_adapter::is_initialized () -> bool static nodiscard noexcept
Check if the monitoring adapter is initialized.
Returns
true if initialized, false otherwise
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 408 of file monitoring_adapter.cpp.
{
    return pimpl_->is_initialized();
}
References kcenon::pacs::integration::monitoring_adapter::impl::is_initialized(), and pimpl_.
query_level_to_string()
auto kcenon::pacs::integration::monitoring_adapter::query_level_to_string (query_level level) -> std::string static nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 497 of file monitoring_adapter.cpp.
{
    switch (level) {
        case query_level::patient:
            return "PATIENT";
        case query_level::study:
            return "STUDY";
        case query_level::series:
            return "SERIES";
        case query_level::image:
            return "IMAGE";
        default:
            return "UNKNOWN";
    }
}
References kcenon::pacs::integration::image, kcenon::pacs::integration::patient, kcenon::pacs::integration::series, and kcenon::pacs::integration::study.
record_association()
void kcenon::pacs::integration::monitoring_adapter::record_association (const std::string & calling_ae, bool established) static
Record DICOM association metrics.
Records metrics for DICOM association establishment/release.
Metrics recorded:
pacs_associations_total (counter)
pacs_associations_active (gauge)
Parameters
calling_ae AE title of the remote system
established true if association was established, false if released
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 450 of file monitoring_adapter.cpp.
{
    pimpl_->record_association(calling_ae, established);
}
References pimpl_, and kcenon::pacs::integration::monitoring_adapter::impl::record_association().
record_c_find()
void kcenon::pacs::integration::monitoring_adapter::record_c_find (std::chrono::nanoseconds duration, std::size_t matches, query_level level) static
Record C-FIND operation metrics.
Records performance metrics for a DICOM C-FIND query operation.
Metrics recorded:
pacs_c_find_total (counter)
pacs_c_find_duration_seconds (histogram)
pacs_c_find_matches (histogram)
Parameters
duration Time taken for the query
matches Number of matching records returned
level Query retrieve level (patient, study, series, image)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 444 of file monitoring_adapter.cpp.
{
    pimpl_->record_c_find(duration, matches, level);
}
References pimpl_, and kcenon::pacs::integration::monitoring_adapter::impl::record_c_find().
record_c_store()
void kcenon::pacs::integration::monitoring_adapter::record_c_store (std::chrono::nanoseconds duration, std::size_t bytes, bool success) static
Record C-STORE operation metrics.
Records performance metrics for a DICOM C-STORE operation including duration, bytes transferred, and success/failure status.
Metrics recorded:
pacs_c_store_total (counter)
pacs_c_store_duration_seconds (histogram)
pacs_c_store_bytes_total (counter)
Parameters
duration Time taken for the operation
bytes Number of bytes transferred
success Whether the operation succeeded
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 438 of file monitoring_adapter.cpp.
{
    pimpl_->record_c_store(duration, bytes, success);
}
References pimpl_, kcenon::pacs::integration::monitoring_adapter::impl::record_c_store(), and kcenon::pacs::integration::success.
record_histogram()
void kcenon::pacs::integration::monitoring_adapter::record_histogram (std::string_view name, double value) static
Record a histogram sample.
Parameters
name The histogram name
value The sample value
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 425 of file monitoring_adapter.cpp.
{
    pimpl_->record_histogram(name, value);
}
References name, pimpl_, and kcenon::pacs::integration::monitoring_adapter::impl::record_histogram().
Referenced by kcenon::pacs::workflow::auto_prefetch_service::execute_cycle(), and kcenon::pacs::workflow::task_scheduler::execute_task().
record_timing()
void kcenon::pacs::integration::monitoring_adapter::record_timing (std::string_view name, std::chrono::nanoseconds duration) static
Record a timing measurement.
Parameters
name The timing metric name
duration The duration to record
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 429 of file monitoring_adapter.cpp.
{
    pimpl_->record_timing(name, duration);
}
References name, pimpl_, and kcenon::pacs::integration::monitoring_adapter::impl::record_timing().
Referenced by job_tracker::update_status().
register_health_check()
void kcenon::pacs::integration::monitoring_adapter::register_health_check (std::string_view component, std::function< bool()> check) static
Register a health check for a component.
The provided function will be called during health checks. It should return true if the component is healthy.
Parameters
component Name of the component
check Function that returns true if healthy
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 476 of file monitoring_adapter.cpp.
{
    pimpl_->register_health_check(component, std::move(check));
}
References pimpl_, and kcenon::pacs::integration::monitoring_adapter::impl::register_health_check().
set_gauge()
void kcenon::pacs::integration::monitoring_adapter::set_gauge (std::string_view name, double value) static
Set a gauge metric value.
Parameters
name The gauge name
value The current value
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 421 of file monitoring_adapter.cpp.
{
    pimpl_->set_gauge(name, value);
}
References name, pimpl_, and kcenon::pacs::integration::monitoring_adapter::impl::set_gauge().
Referenced by job_tracker::add_job(), ai_service_connector::impl::initialize(), and job_tracker::remove_job().
shutdown()
void kcenon::pacs::integration::monitoring_adapter::shutdown () static
Shutdown the monitoring adapter.
Flushes all pending metrics and releases resources. Should be called before application exit.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 406 of file monitoring_adapter.cpp.
{ pimpl_->shutdown(); }
References pimpl_, and kcenon::pacs::integration::monitoring_adapter::impl::shutdown().
start_span()
auto kcenon::pacs::integration::monitoring_adapter::start_span (std::string_view operation) -> span static nodiscard
Start a new trace span.
Parameters
operation Name of the operation
Returns
A new span for the operation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 464 of file monitoring_adapter.cpp.
{
    return span(operation);
}
unregister_health_check()
void kcenon::pacs::integration::monitoring_adapter::unregister_health_check (std::string_view component) static
Unregister a health check.
Parameters
component Name of the component to unregister
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 481 of file monitoring_adapter.cpp.
{
    pimpl_->unregister_health_check(component);
}
References pimpl_, and kcenon::pacs::integration::monitoring_adapter::impl::unregister_health_check().
update_storage_stats()
void kcenon::pacs::integration::monitoring_adapter::update_storage_stats (std::size_t total_instances, std::size_t total_bytes) static
Update storage statistics.
Updates gauge metrics for storage usage.
Metrics recorded:
pacs_storage_instances (gauge)
pacs_storage_bytes (gauge)
Parameters
total_instances Total number of stored DICOM instances
total_bytes Total storage used in bytes
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 455 of file monitoring_adapter.cpp.
{
    pimpl_->update_storage_stats(total_instances, total_bytes);
}
References pimpl_, and kcenon::pacs::integration::monitoring_adapter::impl::update_storage_stats().
Member Data Documentation
pimpl_
std::unique_ptr< monitoring_adapter::impl > kcenon::pacs::integration::monitoring_adapter::pimpl_ static private
Initial value:
=
    std::make_unique<monitoring_adapter::impl>()
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/monitoring_adapter.h.
Definition at line 404 of file monitoring_adapter.h.
Referenced by get_config(), get_health(), increment_counter(), initialize(), is_initialized(), record_association(), record_c_find(), record_c_store(), record_histogram(), record_timing(), register_health_check(), set_gauge(), shutdown(), unregister_health_check(), and update_storage_stats().
The documentation for this class was generated from the following files:
include/kcenon/pacs/integration/monitoring_adapter.h
src/integration/monitoring_adapter.cpp