PACS System: kcenon::pacs::services::validation::ct_iod_validator Class Reference
kcenon::pacs::services::validation::ct_iod_validator Class Reference
#include <ct_iod_validator.hpp>
Public Member Functions
ct_iod_validator ()=default
Construct validator with default options.
ct_iod_validator (const ct_validation_options &options)
Construct validator with custom options.
validation_result validate (const core::dicom_dataset &dataset) const
Validate a DICOM dataset against CT IOD.
bool quick_check (const core::dicom_dataset &dataset) const
Quick check if dataset has minimum required CT attributes.
const ct_validation_options & options () const noexcept
Get the validation options.
void set_options (const ct_validation_options &options)
Set validation options.
Private Member Functions
void validate_patient_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_study_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_series_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_frame_of_reference_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_equipment_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_ct_image_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_image_pixel_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_sop_common_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_type1_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_type2_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_modality (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_pixel_data_consistency (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
Private Attributes
ct_validation_options options_
Detailed Description
Definition at line 183 of file ct_iod_validator.hpp.
Constructor & Destructor Documentation
ct_iod_validator() [1/2]
kcenon::pacs::services::validation::ct_iod_validator::ct_iod_validator () default
Construct validator with default options.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
ct_iod_validator() [2/2]
kcenon::pacs::services::validation::ct_iod_validator::ct_iod_validator (const ct_validation_options & options) explicit
Construct validator with custom options.
Parameters
options Validation options
Definition at line 50 of file ct_iod_validator.cpp.
    : options_(options) {}
Member Function Documentation
check_modality()
void kcenon::pacs::services::validation::ct_iod_validator::check_modality (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 389 of file ct_iod_validator.cpp.
{
    if (!dataset.contains(tags::modality)) {
        return;  // Already reported as Type 1 missing
    }
    auto modality = dataset.get_string(tags::modality);
    if (modality != "CT") {
        findings.push_back(
            {validation_severity::error, tags::modality,
             "Modality must be 'CT' for CT images, found: " + modality,
             "CT-ERR-002"});
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), and kcenon::pacs::core::tags::modality.
Referenced by validate_general_series_module().
check_pixel_data_consistency()
void kcenon::pacs::services::validation::ct_iod_validator::check_pixel_data_consistency (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 406 of file ct_iod_validator.cpp.
{
    // Check BitsStored <= BitsAllocated
    auto bits_allocated =
        dataset.get_numeric<uint16_t>(tags::bits_allocated);
    auto bits_stored = dataset.get_numeric<uint16_t>(tags::bits_stored);
    auto high_bit = dataset.get_numeric<uint16_t>(tags::high_bit);
    if (bits_allocated && bits_stored) {
        if (*bits_stored > *bits_allocated) {
            findings.push_back(
                {validation_severity::error, tags::bits_stored,
                 "BitsStored (" + std::to_string(*bits_stored) +
                     ") exceeds BitsAllocated (" +
                     std::to_string(*bits_allocated) + ")",
                 "CT-ERR-003"});
        }
    }
    // Check HighBit == BitsStored - 1
    if (bits_stored && high_bit) {
        if (*high_bit != *bits_stored - 1) {
            findings.push_back(
                {validation_severity::warning, tags::high_bit,
                 "HighBit (" + std::to_string(*high_bit) +
                     ") should typically be BitsStored - 1 (" +
                     std::to_string(*bits_stored - 1) + ")",
                 "CT-WARN-003"});
        }
    }
    // CT images must be grayscale (MONOCHROME1 or MONOCHROME2)
    if (dataset.contains(tags::photometric_interpretation)) {
        auto photometric =
            dataset.get_string(tags::photometric_interpretation);
        if (!sop_classes::is_valid_ct_photometric(photometric)) {
            findings.push_back(
                {validation_severity::error,
                 tags::photometric_interpretation,
                 "CT images must use MONOCHROME1 or MONOCHROME2, found: " +
                     photometric,
                 "CT-ERR-004"});
        }
    }
    // CT images must have SamplesPerPixel = 1
    auto samples = dataset.get_numeric<uint16_t>(tags::samples_per_pixel);
    if (samples && *samples != 1) {
        findings.push_back(
            {validation_severity::error, tags::samples_per_pixel,
             "CT images require SamplesPerPixel = 1, found: " +
                 std::to_string(*samples),
             "CT-ERR-005"});
    }
    // CT images typically use signed pixel representation (for HU values)
    auto pixel_rep =
        dataset.get_numeric<uint16_t>(tags::pixel_representation);
    if (pixel_rep && *pixel_rep != 1) {
        findings.push_back(
            {validation_severity::info, tags::pixel_representation,
             "CT images typically use signed pixel representation "
             "(PixelRepresentation = 1) for Hounsfield Unit values",
             "CT-INFO-003"});
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_numeric(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::services::validation::info, kcenon::pacs::services::sop_classes::is_valid_ct_photometric(), kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::samples_per_pixel, and kcenon::pacs::services::validation::warning.
Referenced by validate_image_pixel_module().
check_type1_attribute()
void kcenon::pacs::services::validation::ct_iod_validator::check_type1_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 352 of file ct_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back(
            {validation_severity::error, tag,
             std::string("Type 1 attribute missing: ") + std::string(name) +
                 " (" + tag.to_string() + ")",
             "CT-TYPE1-MISSING"});
    } else {
        // Type 1 must have a value (cannot be empty)
        auto value = dataset.get_string(tag);
        if (value.empty()) {
            findings.push_back(
                {validation_severity::error, tag,
                 std::string("Type 1 attribute has empty value: ") +
                     std::string(name) + " (" + tag.to_string() + ")",
                 "CT-TYPE1-EMPTY"});
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), name, and kcenon::pacs::core::dicom_tag::to_string().
Referenced by validate_ct_image_module(), validate_frame_of_reference_module(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), and validate_sop_common_module().
check_type2_attribute()
void kcenon::pacs::services::validation::ct_iod_validator::check_type2_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 375 of file ct_iod_validator.cpp.
{
    // Type 2 must be present but can be empty
    if (!dataset.contains(tag)) {
        findings.push_back(
            {validation_severity::warning, tag,
             std::string("Type 2 attribute missing: ") + std::string(name) +
                 " (" + tag.to_string() + ")",
             "CT-TYPE2-MISSING"});
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), name, kcenon::pacs::core::dicom_tag::to_string(), and kcenon::pacs::services::validation::warning.
Referenced by validate_ct_image_module(), validate_frame_of_reference_module(), validate_general_equipment_module(), validate_general_series_module(), validate_general_study_module(), and validate_patient_module().
options()
const ct_validation_options & kcenon::pacs::services::validation::ct_iod_validator::options () const noexcept
Get the validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 127 of file ct_iod_validator.cpp.
{
    return options_;
}
References options_.
Referenced by set_options().
quick_check()
bool kcenon::pacs::services::validation::ct_iod_validator::quick_check (const core::dicom_dataset & dataset) const
Quick check if dataset has minimum required CT attributes.
Parameters
dataset The dataset to check
Returns
true if all Type 1 attributes are present
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 92 of file ct_iod_validator.cpp.
{
    // Check only Type 1 required attributes for quick validation
    // General Study Module Type 1
    if (!dataset.contains(tags::study_instance_uid)) return false;
    // General Series Module Type 1
    if (!dataset.contains(tags::modality)) return false;
    if (!dataset.contains(tags::series_instance_uid)) return false;
    // Check modality is CT
    auto modality = dataset.get_string(tags::modality);
    if (modality != "CT") return false;
    // Frame of Reference Module Type 1
    if (!dataset.contains(tags::frame_of_reference_uid)) return false;
    // Image Pixel Module Type 1
    if (!dataset.contains(tags::samples_per_pixel)) return false;
    if (!dataset.contains(tags::photometric_interpretation)) return false;
    if (!dataset.contains(tags::rows)) return false;
    if (!dataset.contains(tags::columns)) return false;
    if (!dataset.contains(tags::bits_allocated)) return false;
    if (!dataset.contains(tags::bits_stored)) return false;
    if (!dataset.contains(tags::high_bit)) return false;
    if (!dataset.contains(tags::pixel_representation)) return false;
    if (!dataset.contains(tags::pixel_data)) return false;
    // SOP Common Module Type 1
    if (!dataset.contains(tags::sop_class_uid)) return false;
    if (!dataset.contains(tags::sop_instance_uid)) return false;
    return true;
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::tags::columns, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::tags::frame_of_reference_uid, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, and kcenon::pacs::core::tags::study_instance_uid.
Referenced by kcenon::pacs::services::validation::is_valid_ct_dataset().
set_options()
void kcenon::pacs::services::validation::ct_iod_validator::set_options (const ct_validation_options & options)
Set validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 131 of file ct_iod_validator.cpp.
{
    options_ = options;
}
References options(), and options_.
validate()
validation_result kcenon::pacs::services::validation::ct_iod_validator::validate (const core::dicom_dataset & dataset) const
Validate a DICOM dataset against CT IOD.
Parameters
dataset The dataset to validate
Returns
Validation result with all findings
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 53 of file ct_iod_validator.cpp.
{
    validation_result result;
    result.is_valid = true;
    // Validate mandatory modules (PS3.3 Table A.3-1)
    if (options_.check_type1 || options_.check_type2) {
        validate_patient_module(dataset, result.findings);
        validate_general_study_module(dataset, result.findings);
        validate_general_series_module(dataset, result.findings);
        validate_frame_of_reference_module(dataset, result.findings);
        validate_general_equipment_module(dataset, result.findings);
        validate_sop_common_module(dataset, result.findings);
    }
    if (options_.validate_ct_params) {
        validate_ct_image_module(dataset, result.findings);
    }
    if (options_.validate_pixel_data) {
        validate_image_pixel_module(dataset, result.findings);
    }
    // Determine overall validity
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
        if (options_.strict_mode &&
            finding.severity == validation_severity::warning) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References kcenon::pacs::services::validation::ct_validation_options::check_type1, kcenon::pacs::services::validation::ct_validation_options::check_type2, kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::services::validation::validation_result::is_valid, options_, kcenon::pacs::services::validation::ct_validation_options::strict_mode, validate_ct_image_module(), kcenon::pacs::services::validation::ct_validation_options::validate_ct_params, validate_frame_of_reference_module(), validate_general_equipment_module(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_patient_module(), kcenon::pacs::services::validation::ct_validation_options::validate_pixel_data, validate_sop_common_module(), and kcenon::pacs::services::validation::warning.
Referenced by kcenon::pacs::services::validation::validate_ct_iod().
validate_ct_image_module()
void kcenon::pacs::services::validation::ct_iod_validator::validate_ct_image_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 230 of file ct_iod_validator.cpp.
{
    // CT Image Module (PS3.3 Section C.8.2.1)
    // ImageType is Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::image_type, "ImageType",
                              findings);
    }
    // Type 2 attributes specific to CT Image Module
    if (options_.check_type2) {
        check_type2_attribute(dataset, ct_tags::kvp, "KVP", findings);
        check_type2_attribute(dataset, tags::rescale_intercept,
                              "RescaleIntercept", findings);
        check_type2_attribute(dataset, tags::rescale_slope, "RescaleSlope",
                              findings);
    }
    // Type 2C/3 - informational checks for common CT attributes
    if (options_.check_conditional) {
        if (!dataset.contains(ct_tags::slice_thickness)) {
            findings.push_back(
                {validation_severity::info, ct_tags::slice_thickness,
                 "SliceThickness (0018,0050) not present - slice geometry "
                 "information unavailable",
                 "CT-INFO-001"});
        }
        if (!dataset.contains(ct_tags::convolution_kernel)) {
            findings.push_back(
                {validation_severity::info, ct_tags::convolution_kernel,
                 "ConvolutionKernel (0018,1210) not present - reconstruction "
                 "algorithm unknown",
                 "CT-INFO-002"});
        }
        // Image Position (Patient) is Type 1C - required if
        // Frame of Reference Module is present
        if (dataset.contains(tags::frame_of_reference_uid) &&
            !dataset.contains(ct_tags::image_position_patient)) {
            findings.push_back(
                {validation_severity::warning,
                 ct_tags::image_position_patient,
                 "ImagePositionPatient (0020,0032) missing - required when "
                 "Frame of Reference is present",
                 "CT-WARN-001"});
        }
        // Image Orientation (Patient) is Type 1C
        if (dataset.contains(tags::frame_of_reference_uid) &&
            !dataset.contains(ct_tags::image_orientation_patient)) {
            findings.push_back(
                {validation_severity::warning,
                 ct_tags::image_orientation_patient,
                 "ImageOrientationPatient (0020,0037) missing - required when "
                 "Frame of Reference is present",
                 "CT-WARN-002"});
        }
    }
}
References kcenon::pacs::services::validation::ct_validation_options::check_conditional, kcenon::pacs::services::validation::ct_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::ct_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::ct_tags::convolution_kernel, kcenon::pacs::core::tags::frame_of_reference_uid, kcenon::pacs::services::validation::ct_tags::image_orientation_patient, kcenon::pacs::services::validation::ct_tags::image_position_patient, kcenon::pacs::core::tags::image_type, kcenon::pacs::services::validation::info, kcenon::pacs::services::validation::ct_tags::kvp, options_, kcenon::pacs::core::tags::rescale_intercept, kcenon::pacs::core::tags::rescale_slope, kcenon::pacs::services::validation::ct_tags::slice_thickness, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_frame_of_reference_module()
void kcenon::pacs::services::validation::ct_iod_validator::validate_frame_of_reference_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 201 of file ct_iod_validator.cpp.
{
    // Frame of Reference UID is Type 1 for CT
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::frame_of_reference_uid,
                              "FrameOfReferenceUID", findings);
    }
    // Position Reference Indicator is Type 2
    if (options_.check_type2) {
        constexpr dicom_tag position_reference_indicator{0x0020, 0x1040};
        check_type2_attribute(dataset, position_reference_indicator,
                              "PositionReferenceIndicator", findings);
    }
}
References kcenon::pacs::services::validation::ct_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::ct_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::tags::frame_of_reference_uid, and options_.
Referenced by validate().
validate_general_equipment_module()
void kcenon::pacs::services::validation::ct_iod_validator::validate_general_equipment_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 219 of file ct_iod_validator.cpp.
{
    // Manufacturer is Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::manufacturer, "Manufacturer",
                              findings);
    }
}
References kcenon::pacs::services::validation::ct_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::tags::manufacturer, and options_.
Referenced by validate().
validate_general_series_module()
void kcenon::pacs::services::validation::ct_iod_validator::validate_general_series_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 180 of file ct_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::modality, "Modality", findings);
        check_type1_attribute(dataset, tags::series_instance_uid,
                              "SeriesInstanceUID", findings);
        // Modality must be "CT"
        check_modality(dataset, findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::series_number, "SeriesNumber",
                              findings);
    }
}
References check_modality(), kcenon::pacs::services::validation::ct_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::ct_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::tags::modality, options_, kcenon::pacs::core::tags::series_instance_uid, and kcenon::pacs::core::tags::series_number.
Referenced by validate().
validate_general_study_module()
void kcenon::pacs::services::validation::ct_iod_validator::validate_general_study_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 156 of file ct_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::study_instance_uid,
                              "StudyInstanceUID", findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::study_date, "StudyDate",
                              findings);
        check_type2_attribute(dataset, tags::study_time, "StudyTime",
                              findings);
        check_type2_attribute(dataset, tags::referring_physician_name,
                              "ReferringPhysicianName", findings);
        check_type2_attribute(dataset, tags::study_id, "StudyID", findings);
        check_type2_attribute(dataset, tags::accession_number,
                              "AccessionNumber", findings);
    }
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::services::validation::ct_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::ct_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::core::tags::study_time.
Referenced by validate().
validate_image_pixel_module()
void kcenon::pacs::services::validation::ct_iod_validator::validate_image_pixel_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 294 of file ct_iod_validator.cpp.
{
    // Type 1 attributes
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::samples_per_pixel,
                              "SamplesPerPixel", findings);
        check_type1_attribute(dataset, tags::photometric_interpretation,
                              "PhotometricInterpretation", findings);
        check_type1_attribute(dataset, tags::rows, "Rows", findings);
        check_type1_attribute(dataset, tags::columns, "Columns", findings);
        check_type1_attribute(dataset, tags::bits_allocated, "BitsAllocated",
                              findings);
        check_type1_attribute(dataset, tags::bits_stored, "BitsStored",
                              findings);
        check_type1_attribute(dataset, tags::high_bit, "HighBit", findings);
        check_type1_attribute(dataset, tags::pixel_representation,
                              "PixelRepresentation", findings);
        check_type1_attribute(dataset, tags::pixel_data, "PixelData",
                              findings);
    }
    // Validate pixel data consistency
    if (options_.validate_pixel_data) {
        check_pixel_data_consistency(dataset, findings);
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, check_pixel_data_consistency(), kcenon::pacs::services::validation::ct_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::tags::columns, kcenon::pacs::core::tags::high_bit, options_, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, and kcenon::pacs::services::validation::ct_validation_options::validate_pixel_data.
Referenced by validate().
validate_patient_module()
void kcenon::pacs::services::validation::ct_iod_validator::validate_patient_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 139 of file ct_iod_validator.cpp.
{
    // Patient Module - All attributes are Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::patient_name, "PatientName",
                              findings);
        check_type2_attribute(dataset, tags::patient_id, "PatientID",
                              findings);
        check_type2_attribute(dataset, tags::patient_birth_date,
                              "PatientBirthDate", findings);
        check_type2_attribute(dataset, tags::patient_sex, "PatientSex",
                              findings);
    }
}
References kcenon::pacs::services::validation::ct_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, and kcenon::pacs::core::tags::patient_sex.
Referenced by validate().
validate_sop_common_module()
void kcenon::pacs::services::validation::ct_iod_validator::validate_sop_common_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 323 of file ct_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::sop_class_uid, "SOPClassUID",
                              findings);
        check_type1_attribute(dataset, tags::sop_instance_uid,
                              "SOPInstanceUID", findings);
    }
    // Validate SOP Class UID is a CT storage class
    if (dataset.contains(tags::sop_class_uid)) {
        auto sop_class = dataset.get_string(tags::sop_class_uid);
        if (!sop_classes::is_ct_storage_sop_class(sop_class)) {
            findings.push_back(
                {validation_severity::error, tags::sop_class_uid,
                 "SOPClassUID is not a recognized CT Storage SOP Class: " +
                     sop_class,
                 "CT-ERR-001"});
        }
    }
}
References kcenon::pacs::services::validation::ct_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_ct_storage_sop_class(), options_, kcenon::pacs::core::tags::sop_class_uid, and kcenon::pacs::core::tags::sop_instance_uid.
Referenced by validate().
Member Data Documentation
options_
ct_validation_options kcenon::pacs::services::validation::ct_iod_validator::options_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/ct_iod_validator.hpp.
Definition at line 277 of file ct_iod_validator.hpp.
Referenced by options(), set_options(), validate(), validate_ct_image_module(), validate_frame_of_reference_module(), validate_general_equipment_module(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_patient_module(), and validate_sop_common_module().
The documentation for this class was generated from the following files:
include/pacs/services/validation/ct_iod_validator.hpp
src/services/validation/ct_iod_validator.cpp