PACS System: kcenon::pacs::services::verification_scp Class Reference
kcenon::pacs::services::verification_scp Class Reference final
#include <verification_scp.hpp>
Public Member Functions
verification_scp (std::shared_ptr< di::ILogger > logger=nullptr)
Construct Verification SCP with optional logger.
~verification_scp () override=default
std::vector< std::string > supported_sop_classes () const override
Get supported SOP Class UIDs.
network::Result< std::monostate > handle_message (network::association &assoc, uint8_t context_id, const network::dimse::dimse_message &request) override
Handle an incoming DIMSE message (C-ECHO-RQ)
std::string_view service_name () const noexcept override
Get the service name.
Public Member Functions inherited from kcenon::pacs::services::scp_service
scp_service (std::shared_ptr< di::ILogger > logger=nullptr)
Construct SCP service with optional logger.
virtual ~scp_service ()=default
scp_service (const scp_service &)=delete
scp_service & operator= (const scp_service &)=delete
scp_service (scp_service &&)=default
scp_service & operator= (scp_service &&)=default
void set_logger (std::shared_ptr< di::ILogger > logger)
Set the logger instance.
const std::shared_ptr< di::ILogger > & logger () const noexcept
Get the current logger instance.
bool supports_sop_class (std::string_view sop_class_uid) const
Check if this service supports a specific SOP Class.
Additional Inherited Members
Protected Attributes inherited from kcenon::pacs::services::scp_service
std::shared_ptr< di::ILogger > logger_
Logger instance for service logging.
Detailed Description
Definition at line 99 of file verification_scp.hpp.
Constructor & Destructor Documentation
verification_scp()
kcenon::pacs::services::verification_scp::verification_scp (std::shared_ptr< di::ILogger > logger = nullptr) inline explicit
Construct Verification SCP with optional logger.
Parameters
logger Logger instance for service logging (nullptr uses null_logger)
Definition at line 110 of file verification_scp.hpp.
        : scp_service(std::move(logger)) {}
~verification_scp()
kcenon::pacs::services::verification_scp::~verification_scp () override default
Member Function Documentation
handle_message()
network::Result< std::monostate > kcenon::pacs::services::verification_scp::handle_message (network::association & assoc, uint8_t context_id, const network::dimse::dimse_message & request) override virtual
Handle an incoming DIMSE message (C-ECHO-RQ)
Processes the C-ECHO request and sends a C-ECHO response with success status.
Parameters
assoc The association on which the message was received
context_id The presentation context ID for the message
request The incoming C-ECHO-RQ message
Returns
Success or error if the message is not a valid C-ECHO-RQ
Note
This method rejects any message that is not a C-ECHO-RQ
Implements kcenon::pacs::services::scp_service.
Definition at line 46 of file verification_scp.cpp.
{
    using namespace network::dimse;
    // Verify the message is a C-ECHO request
    if (request.command() != command_field::c_echo_rq) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::echo_unexpected_command,
            "Expected C-ECHO-RQ but received " +
            std::string(to_string(request.command())));
    }
    // Build C-ECHO response using the factory function
    auto response = make_c_echo_rsp(
        request.message_id(),
        status_success,
        verification_sop_class_uid
    );
    // Send the response
    return assoc.send_dimse(context_id, response);
}
References kcenon::pacs::network::dimse::dimse_message::command(), kcenon::pacs::error_codes::echo_unexpected_command, kcenon::pacs::network::dimse::dimse_message::message_id(), kcenon::pacs::pacs_void_error(), kcenon::pacs::network::association::send_dimse(), and kcenon::pacs::services::verification_sop_class_uid.
service_name()
std::string_view kcenon::pacs::services::verification_scp::service_name () const override virtual noexcept
Get the service name.
Returns
"Verification SCP"
Implements kcenon::pacs::services::scp_service.
Definition at line 72 of file verification_scp.cpp.
{
    return "Verification SCP";
}
supported_sop_classes()
std::vector< std::string > kcenon::pacs::services::verification_scp::supported_sop_classes () const override virtual
Get supported SOP Class UIDs.
Returns
Vector containing only the Verification SOP Class UID
Implements kcenon::pacs::services::scp_service.
Definition at line 42 of file verification_scp.cpp.
{
    return {std::string(verification_sop_class_uid)};
}
References kcenon::pacs::services::verification_sop_class_uid.
The documentation for this class was generated from the following files:
include/pacs/services/verification_scp.hpp
src/services/verification_scp.cpp