PACS System: kcenon::pacs::core::dicom_dictionary Class Reference
kcenon::pacs::core::dicom_dictionary Class Reference
#include <dicom_dictionary.hpp>
Public Member Functions
dicom_dictionary (const dicom_dictionary &)=delete
dicom_dictionary (dicom_dictionary &&)=delete
auto operator= (const dicom_dictionary &) -> dicom_dictionary &=delete
auto operator= (dicom_dictionary &&) -> dicom_dictionary &=delete
auto find (dicom_tag tag) const -> std::optional< tag_info >
Find tag metadata by DICOM tag.
auto find_by_keyword (std::string_view keyword) const -> std::optional< tag_info >
Find tag metadata by keyword.
auto contains (dicom_tag tag) const -> bool
Check if a tag exists in the dictionary.
auto contains_keyword (std::string_view keyword) const -> bool
Check if a keyword exists in the dictionary.
auto validate_vm (dicom_tag tag, uint32_t count) const -> bool
Validate that a value count is valid for a tag's VM.
auto get_vr (dicom_tag tag) const -> uint16_t
Get the VR type for a tag.
auto register_private_tag (const tag_info &info) -> bool
Register a private tag at runtime.
auto size () const -> size_t
Get the total number of tags in the dictionary.
auto standard_tag_count () const -> size_t
Get the number of standard (non-private) tags.
auto private_tag_count () const -> size_t
Get the number of registered private tags.
auto get_tags_in_group (uint16_t group) const -> std::vector< tag_info >
Get all tags in a specific group.
Static Public Member Functions
static auto instance () -> dicom_dictionary &
Get the singleton instance.
Private Member Functions
dicom_dictionary ()
Private constructor - initializes with standard tags.
void initialize_standard_tags ()
Initialize the dictionary with standard PS3.6 tags.
Private Attributes
std::unordered_map< dicom_tag, tag_info > tag_map_
Hash map for O(1) lookup by tag.
std::unordered_map< std::string_view, dicom_tag > keyword_map_
Hash map for O(1) lookup by keyword.
size_t standard_count_ {0}
Count of standard tags (vs private)
std::shared_mutex mutex_
Mutex for thread-safe private tag registration.
Detailed Description
Definition at line 90 of file dicom_dictionary.hpp.
Constructor & Destructor Documentation
dicom_dictionary() [1/3]
kcenon::pacs::core::dicom_dictionary::dicom_dictionary (const dicom_dictionary &) delete
dicom_dictionary() [2/3]
kcenon::pacs::core::dicom_dictionary::dicom_dictionary (dicom_dictionary &&) delete
dicom_dictionary() [3/3]
kcenon::pacs::core::dicom_dictionary::dicom_dictionary () private
Private constructor - initializes with standard tags.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 50 of file dicom_dictionary.cpp.
{
    initialize_standard_tags();
}
References initialize_standard_tags().
Member Function Documentation
contains()
auto kcenon::pacs::core::dicom_dictionary::contains (dicom_tag tag) const -> bool
Check if a tag exists in the dictionary.
Parameters
tag The DICOM tag to check
Returns
true if the tag is in the dictionary
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 94 of file dicom_dictionary.cpp.
{
    std::shared_lock lock(mutex_);
    return tag_map_.contains(tag);
}
contains_keyword()
auto kcenon::pacs::core::dicom_dictionary::contains_keyword (std::string_view keyword) const -> bool
Check if a keyword exists in the dictionary.
Parameters
keyword The keyword to check
Returns
true if the keyword is in the dictionary
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 99 of file dicom_dictionary.cpp.
{
    std::shared_lock lock(mutex_);
    return keyword_map_.contains(keyword);
}
find()
auto kcenon::pacs::core::dicom_dictionary::find (dicom_tag tag) const -> std::optional<tag_info>
Find tag metadata by DICOM tag.
Parameters
tag The DICOM tag to look up
Returns
Optional containing tag_info if found, nullopt otherwise
O(1) average time complexity using hash table lookup. Thread-safe for concurrent reads.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 70 of file dicom_dictionary.cpp.
{
    std::shared_lock lock(mutex_);
    const auto it = tag_map_.find(tag);
    if (it != tag_map_.end()) {
        return it->second;
    }
    return std::nullopt;
}
find_by_keyword()
auto kcenon::pacs::core::dicom_dictionary::find_by_keyword (std::string_view keyword) const -> std::optional<tag_info>
Find tag metadata by keyword.
Parameters
keyword The tag keyword (e.g., "PatientName")
Returns
Optional containing tag_info if found, nullopt otherwise
O(1) average time complexity using hash table lookup. Thread-safe for concurrent reads.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 80 of file dicom_dictionary.cpp.
{
    std::shared_lock lock(mutex_);
    const auto it = keyword_map_.find(keyword);
    if (it != keyword_map_.end()) {
        const auto tag_it = tag_map_.find(it->second);
        if (tag_it != tag_map_.end()) {
            return tag_it->second;
        }
    }
    return std::nullopt;
}
get_tags_in_group()
auto kcenon::pacs::core::dicom_dictionary::get_tags_in_group (uint16_t group) const -> std::vector<tag_info>
Get all tags in a specific group.
Parameters
group The group number to filter by
Returns
Vector of tag_info for all tags in the group
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 155 of file dicom_dictionary.cpp.
{
    std::shared_lock lock(mutex_);
    std::vector<tag_info> result;
    for (const auto& [tag, info] : tag_map_) {
        if (tag.group() == group) {
            result.push_back(info);
        }
    }
    std::sort(result.begin(), result.end(),
              [](const auto& a, const auto& b) {
                  return a.tag < b.tag;
              });
    return result;
}
get_vr()
auto kcenon::pacs::core::dicom_dictionary::get_vr (dicom_tag tag) const -> uint16_t
Get the VR type for a tag.
Parameters
tag The DICOM tag
Returns
The VR type as uint16_t, or 0 if tag not found
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 112 of file dicom_dictionary.cpp.
{
    const auto info = find(tag);
    if (!info) {
        return 0;
    }
    return info->vr;
}
initialize_standard_tags()
void kcenon::pacs::core::dicom_dictionary::initialize_standard_tags () private
Initialize the dictionary with standard PS3.6 tags.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 54 of file dicom_dictionary.cpp.
{
    const auto tags = get_standard_tags();
    tag_map_.reserve(tags.size());
    keyword_map_.reserve(tags.size());
    for (const auto& info : tags) {
        tag_map_.emplace(info.tag, info);
        if (!info.keyword.empty()) {
            keyword_map_.emplace(info.keyword, info.tag);
        }
    }
    standard_count_ = tags.size();
}
References kcenon::pacs::core::get_standard_tags(), keyword_map_, standard_count_, and tag_map_.
Referenced by dicom_dictionary().
instance()
auto kcenon::pacs::core::dicom_dictionary::instance () -> dicom_dictionary& static
Get the singleton instance.
Returns
Reference to the global dicom_dictionary instance
Thread-safe initialization using C++11 static initialization guarantee.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 45 of file dicom_dictionary.cpp.
{
    static dicom_dictionary instance;
    return instance;
}
Referenced by kcenon::pacs::encoding::implicit_vr_codec::decode_element(), and kcenon::pacs::core::dicom_file::decode_implicit_vr_le().
operator=() [1/2]
auto kcenon::pacs::core::dicom_dictionary::operator= (const dicom_dictionary &) -> dicom_dictionary &=delete delete
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
operator=() [2/2]
auto kcenon::pacs::core::dicom_dictionary::operator= (dicom_dictionary &&) -> dicom_dictionary &=delete delete
private_tag_count()
auto kcenon::pacs::core::dicom_dictionary::private_tag_count () const -> size_t
Get the number of registered private tags.
Returns
The count of runtime-registered private tags
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 150 of file dicom_dictionary.cpp.
{
    std::shared_lock lock(mutex_);
    return tag_map_.size() - standard_count_;
}
References mutex_, standard_count_, and tag_map_.
register_private_tag()
auto kcenon::pacs::core::dicom_dictionary::register_private_tag (const tag_info & info) -> bool
Register a private tag at runtime.
Parameters
info The tag_info for the private tag
Returns
true if registration succeeded, false if tag already exists
Only private tags (odd group numbers > 0x0008) can be registered. Thread-safe, serializes write operations.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 120 of file dicom_dictionary.cpp.
{
    // Only allow private tags
    if (!info.tag.is_private()) {
        return false;
    }
    std::unique_lock lock(mutex_);
    // Check if already exists
    if (tag_map_.contains(info.tag)) {
        return false;
    }
    tag_map_.emplace(info.tag, info);
    if (!info.keyword.empty()) {
        keyword_map_.emplace(info.keyword, info.tag);
    }
    return true;
}
size()
auto kcenon::pacs::core::dicom_dictionary::size () const -> size_t
Get the total number of tags in the dictionary.
Returns
The count of registered tags (standard + private)
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 141 of file dicom_dictionary.cpp.
{
    std::shared_lock lock(mutex_);
    return tag_map_.size();
}
References mutex_, and tag_map_.
standard_tag_count()
auto kcenon::pacs::core::dicom_dictionary::standard_tag_count () const -> size_t
Get the number of standard (non-private) tags.
Returns
The count of standard PS3.6 tags
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 146 of file dicom_dictionary.cpp.
{
    return standard_count_;
}
References standard_count_.
validate_vm()
auto kcenon::pacs::core::dicom_dictionary::validate_vm (dicom_tag tag, uint32_t count) const -> bool
Validate that a value count is valid for a tag's VM.
Parameters
tag The DICOM tag to validate against
count The number of values to validate
Returns
true if count satisfies the tag's VM, false if tag not found or invalid
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 104 of file dicom_dictionary.cpp.
{
    const auto info = find(tag);
    if (!info) {
        return false;
    }
    return info->vm.is_valid(count);
}
Member Data Documentation
keyword_map_
std::unordered_map<std::string_view, dicom_tag> kcenon::pacs::core::dicom_dictionary::keyword_map_ private
Hash map for O(1) lookup by keyword.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 207 of file dicom_dictionary.hpp.
Referenced by initialize_standard_tags().
mutex_
std::shared_mutex kcenon::pacs::core::dicom_dictionary::mutex_ mutable private
Mutex for thread-safe private tag registration.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 213 of file dicom_dictionary.hpp.
Referenced by private_tag_count(), and size().
standard_count_
size_t kcenon::pacs::core::dicom_dictionary::standard_count_ {0} private
Count of standard tags (vs private)
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 210 of file dicom_dictionary.hpp.
{0};
Referenced by initialize_standard_tags(), private_tag_count(), and standard_tag_count().
tag_map_
std::unordered_map<dicom_tag, tag_info> kcenon::pacs::core::dicom_dictionary::tag_map_ private
Hash map for O(1) lookup by tag.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/core/dicom_dictionary.hpp.
Definition at line 204 of file dicom_dictionary.hpp.
Referenced by initialize_standard_tags(), private_tag_count(), and size().
The documentation for this class was generated from the following files:
include/pacs/core/dicom_dictionary.hpp
src/core/dicom_dictionary.cpp