PACS System: kcenon::pacs::core::dicom_tag Class Reference
kcenon::pacs::core::dicom_tag Class Reference
#include <dicom_tag.h>
Public Member Functions
constexpr dicom_tag () noexcept
Default constructor - creates tag (0000,0000)
constexpr dicom_tag (uint16_t group, uint16_t element) noexcept
Construct from group and element numbers.
constexpr dicom_tag (uint32_t combined) noexcept
Construct from combined 32-bit value.
constexpr auto group () const noexcept -> uint16_t
Get the group number.
constexpr auto element () const noexcept -> uint16_t
Get the element number.
constexpr auto combined () const noexcept -> uint32_t
Get the combined 32-bit value.
constexpr auto is_private () const noexcept -> bool
Check if this is a private tag.
constexpr auto is_group_length () const noexcept -> bool
Check if this is a group length tag (xxxx,0000)
constexpr auto is_private_creator () const noexcept -> bool
Check if this is a private creator tag.
constexpr auto is_private_data () const noexcept -> bool
Check if this is a private data element.
constexpr auto private_block_number () const noexcept -> std::optional< uint8_t >
Extract the Private Creator block number from this tag.
constexpr auto private_creator_tag () const noexcept -> std::optional< dicom_tag >
Get the Private Creator tag that owns this data element.
constexpr auto private_data_range () const noexcept -> std::optional< std::pair< dicom_tag, dicom_tag > >
Get the data element range owned by this Private Creator tag.
auto to_string () const -> std::string
Convert to string representation.
constexpr auto operator<=> (const dicom_tag &other) const noexcept -> std::strong_ordering=default
Three-way comparison operator.
constexpr auto operator== (const dicom_tag &other) const noexcept -> bool=default
Equality comparison.
Static Public Member Functions
static auto from_string (std::string_view str) -> std::optional< dicom_tag >
Parse tag from string representation.
Private Attributes
uint32_t combined_
Detailed Description
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h, dcm_anonymize/main.cpp, dcm_dir/main.cpp, dcm_dump/main.cpp, dcm_modify/main.cpp, dcm_to_json/main.cpp, dcm_to_xml/main.cpp, find_scu/main.cpp, get_scu/main.cpp, json_to_dcm/main.cpp, module_example/main.cpp, move_scu/main.cpp, and xml_to_dcm/main.cpp.
Definition at line 51 of file dicom_tag.h.
Constructor & Destructor Documentation
dicom_tag() [1/3]
kcenon::pacs::core::dicom_tag::dicom_tag () inline constexpr noexcept
Default constructor - creates tag (0000,0000)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h.
Definition at line 56 of file dicom_tag.h.
: combined_{0} {}
dicom_tag() [2/3]
kcenon::pacs::core::dicom_tag::dicom_tag (uint16_t group, uint16_t element) inline constexpr noexcept
Construct from group and element numbers.
Parameters
group The group number (0x0000 - 0xFFFF)
element The element number (0x0000 - 0xFFFF)
Definition at line 63 of file dicom_tag.h.
        : combined_{static_cast<uint32_t>(group) << 16 | element} {}
References element(), and group().
dicom_tag() [3/3]
kcenon::pacs::core::dicom_tag::dicom_tag (uint32_t combined) inline explicit constexpr noexcept
Construct from combined 32-bit value.
Parameters
combined The combined value (group << 16 | element)
Definition at line 70 of file dicom_tag.h.
        : combined_{combined} {}
References combined().
Member Function Documentation
combined()
auto kcenon::pacs::core::dicom_tag::combined () const -> uint32_t inline nodiscard constexpr noexcept
Get the combined 32-bit value.
Returns
The combined value (group << 16 | element)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h.
Definition at line 106 of file dicom_tag.h.
{
        return combined_;
    }
References combined_.
Referenced by dicom_tag().
element()
auto kcenon::pacs::core::dicom_tag::element () const -> uint16_t inline nodiscard constexpr noexcept
Get the element number.
Returns
The 16-bit element number
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h, dcm_dump/main.cpp, dcm_to_json/main.cpp, dcm_to_xml/main.cpp, and module_example/main.cpp.
Definition at line 98 of file dicom_tag.h.
{
        return static_cast<uint16_t>(combined_ & 0xFFFF);
    }
References combined_.
Referenced by dicom_tag(), is_group_length(), is_private_creator(), is_private_data(), private_block_number(), private_data_range(), and to_string().
from_string()
auto kcenon::pacs::core::dicom_tag::from_string (std::string_view str) -> std::optional<dicom_tag> static nodiscard
Parse tag from string representation.
Supported formats:
"(GGGG,EEEE)" - Standard DICOM format with parentheses
"GGGGEEEE" - Compact hexadecimal format
Parameters
str String representation of the tag
Returns
Optional containing the parsed tag, or nullopt if parsing failed
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h.
Definition at line 58 of file dicom_tag.cpp.
{
    // Remove leading/trailing whitespace
    while (!str.empty() && (str.front() == ' ' || str.front() == '\t')) {
        str.remove_prefix(1);
    }
    while (!str.empty() && (str.back() == ' ' || str.back() == '\t')) {
        str.remove_suffix(1);
    }
    if (str.empty()) {
        return std::nullopt;
    }
    // Format 1: "(GGGG,EEEE)"
    if (str.size() == 11 && str.front() == '(' && str.back() == ')' &&
        str[5] == ',') {
        const auto group = parse_hex4(str.data() + 1);
        const auto element = parse_hex4(str.data() + 6);
        if (group && element) {
            return dicom_tag{*group, *element};
        }
        return std::nullopt;
    }
    // Format 2: "GGGGEEEE" (8 hex digits)
    if (str.size() == 8) {
        const auto group = parse_hex4(str.data());
        const auto element = parse_hex4(str.data() + 4);
        if (group && element) {
            return dicom_tag{*group, *element};
        }
        return std::nullopt;
    }
    // Format 3: "GGGG,EEEE" (without parentheses)
    if (str.size() == 9 && str[4] == ',') {
        const auto group = parse_hex4(str.data());
        const auto element = parse_hex4(str.data() + 5);
        if (group && element) {
            return dicom_tag{*group, *element};
        }
        return std::nullopt;
    }
    return std::nullopt;
}
group()
auto kcenon::pacs::core::dicom_tag::group () const -> uint16_t inline nodiscard constexpr noexcept
Get the group number.
Returns
The 16-bit group number
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h, dcm_dump/main.cpp, dcm_to_json/main.cpp, dcm_to_xml/main.cpp, and module_example/main.cpp.
Definition at line 90 of file dicom_tag.h.
{
        return static_cast<uint16_t>(combined_ >> 16);
    }
References combined_.
Referenced by dicom_tag(), is_private(), private_creator_tag(), private_data_range(), and to_string().
is_group_length()
auto kcenon::pacs::core::dicom_tag::is_group_length () const -> bool inline nodiscard constexpr noexcept
Check if this is a group length tag (xxxx,0000)
Returns
true if element number is 0x0000
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h.
Definition at line 128 of file dicom_tag.h.
{
        return element() == 0x0000;
    }
References element().
is_private()
auto kcenon::pacs::core::dicom_tag::is_private () const -> bool inline nodiscard constexpr noexcept
Check if this is a private tag.
Private tags have odd group numbers (except group 0x0001). Groups with odd numbers in the range (0x0009, 0x00FF) and above 0x0007 are reserved for private use.
Returns
true if this is a private tag, false otherwise
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h.
Definition at line 119 of file dicom_tag.h.
{
        const auto grp = group();
        return (grp & 1) != 0 && grp > 0x0008;
    }
References group().
Referenced by is_private_creator(), is_private_data(), and kcenon::pacs::web::metadata_service::read_dicom_tags().
is_private_creator()
auto kcenon::pacs::core::dicom_tag::is_private_creator () const -> bool inline nodiscard constexpr noexcept
Check if this is a private creator tag.
Private creator tags are in the range (gggg,0010)-(gggg,00FF) where gggg is an odd group number.
Returns
true if this is a private creator tag
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h.
Definition at line 140 of file dicom_tag.h.
{
        if (!is_private()) {
            return false;
        }
        const auto elem = element();
        return elem >= 0x0010 && elem <= 0x00FF;
    }
References element(), and is_private().
Referenced by private_data_range().
is_private_data()
auto kcenon::pacs::core::dicom_tag::is_private_data () const -> bool inline nodiscard constexpr noexcept
Check if this is a private data element.
Private data elements have element number > 0x00FF within a private group. This excludes private creator elements (0x0010-0x00FF) and group length (0x0000).
Returns
true if this is a private data element
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h.
Definition at line 156 of file dicom_tag.h.
{
        return is_private() && element() > 0x00FF;
    }
References element(), and is_private().
Referenced by private_block_number().
operator<=>()
auto kcenon::pacs::core::dicom_tag::operator<=> (const dicom_tag & other) const -> std::strong_ordering=default nodiscard constexpr default noexcept
Three-way comparison operator.
Tags are compared by their combined 32-bit value, which means they are sorted first by group, then by element.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h.
operator==()
auto kcenon::pacs::core::dicom_tag::operator== (const dicom_tag & other) const -> bool=default nodiscard constexpr default noexcept
Equality comparison.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h.
private_block_number()
auto kcenon::pacs::core::dicom_tag::private_block_number () const -> std::optional<uint8_t> inline nodiscard constexpr noexcept
Extract the Private Creator block number from this tag.
For a private data element (gggg,xxyy) where xx >= 0x10, returns xx. Per DICOM PS3.5 §7.8.1, the high byte of the element number identifies which Private Creator block owns this data element.
Returns
The block number (0x10-0xFF), or nullopt if not a private data element
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h.
Definition at line 169 of file dicom_tag.h.
{
        if (!is_private_data()) {
            return std::nullopt;
        }
        return static_cast<uint8_t>(element() >> 8);
    }
References element(), and is_private_data().
Referenced by private_creator_tag().
private_creator_tag()
auto kcenon::pacs::core::dicom_tag::private_creator_tag () const -> std::optional<dicom_tag> inline nodiscard constexpr noexcept
Get the Private Creator tag that owns this data element.
For a private data element (gggg,xxyy), returns (gggg,00xx). Per DICOM PS3.5 §7.8.1, the creator tag identifies the owner of this private data block.
Returns
The Private Creator tag, or nullopt if not a private data element
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h.
Definition at line 186 of file dicom_tag.h.
{
        const auto block = private_block_number();
        if (!block) {
            return std::nullopt;
        }
        return dicom_tag{group(), *block};
    }
References group(), and private_block_number().
private_data_range()
auto kcenon::pacs::core::dicom_tag::private_data_range () const -> std::optional<std::pair<dicom_tag, dicom_tag>> inline nodiscard constexpr noexcept
Get the data element range owned by this Private Creator tag.
For a Private Creator tag (gggg,00xx), returns the range (gggg,xx00) to (gggg,xxFF) inclusive.
Returns
Pair of {first, last} tags in the range, or nullopt if not a creator tag
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h.
Definition at line 203 of file dicom_tag.h.
{
        if (!is_private_creator()) {
            return std::nullopt;
        }
        const auto block = static_cast<uint16_t>(element() << 8);
        return std::pair{
            dicom_tag{group(), block},
            dicom_tag{group(), static_cast<uint16_t>(block | 0x00FF)}
        };
    }
References element(), group(), and is_private_creator().
to_string()
auto kcenon::pacs::core::dicom_tag::to_string () const -> std::string nodiscard
Convert to string representation.
Returns
String in format "(GGGG,EEEE)"
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h, dcm_dump/main.cpp, and dcm_modify/main.cpp.
Definition at line 108 of file dicom_tag.cpp.
{
    // Pre-allocate exact size: "(" + 4 hex + "," + 4 hex + ")" = 11 chars
    std::string result;
    result.reserve(11);
    // Use lookup table for hex conversion (faster than std::format)
    static constexpr std::array<char, 16> hex_chars = {
        '0', '1', '2', '3', '4', '5', '6', '7',
        '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'};
    const auto grp = group();
    const auto elem = element();
    result += '(';
    result += hex_chars[(grp >> 12) & 0xF];
    result += hex_chars[(grp >> 8) & 0xF];
    result += hex_chars[(grp >> 4) & 0xF];
    result += hex_chars[grp & 0xF];
    result += ',';
    result += hex_chars[(elem >> 12) & 0xF];
    result += hex_chars[(elem >> 8) & 0xF];
    result += hex_chars[(elem >> 4) & 0xF];
    result += hex_chars[elem & 0xF];
    result += ')';
    return result;
}
References element(), and group().
Referenced by kcenon::pacs::services::validation::ct_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::ct_processing_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::dx_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::label_map_seg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::mg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::mr_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::nm_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::ophthalmic_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::parametric_map_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::pet_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::rt_dose_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::rt_plan_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::seg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::sr_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::us_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::wsi_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::xa_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::ct_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::ct_processing_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::dx_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::label_map_seg_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::mg_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::mr_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::nm_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::ophthalmic_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::parametric_map_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::pet_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::rt_dose_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::rt_plan_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::seg_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::sr_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::us_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::wsi_iod_validator::check_type2_attribute(), and kcenon::pacs::services::validation::xa_iod_validator::check_type2_attribute().
Member Data Documentation
combined_
uint32_t kcenon::pacs::core::dicom_tag::combined_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_tag.h.
Definition at line 237 of file dicom_tag.h.
Referenced by combined(), element(), and group().
The documentation for this class was generated from the following files:
include/kcenon/pacs/core/dicom_tag.h
src/core/dicom_tag.cpp