PACS System: kcenon::pacs::security::certificate_chain Class Reference
kcenon::pacs::security::certificate_chain Class Reference
Represents a certificate chain for validation.
#include <certificate.h>
Public Member Functions
certificate_chain ()=default
Default constructor - creates an empty chain.
void add (certificate cert)
Add a certificate to the chain.
auto end_entity () const -> const certificate *
Get the end-entity (leaf) certificate.
auto certificates () const -> const std::vector< certificate > &
Get all certificates in the chain.
auto empty () const noexcept -> bool
Check if chain is empty.
auto size () const noexcept -> size_t
Get number of certificates in chain.
Static Public Member Functions
static auto load_from_pem (std::string_view path) -> kcenon::common::Result< certificate_chain >
Load certificate chain from PEM file.
Private Attributes
std::vector< certificate > certs_
Detailed Description
Represents a certificate chain for validation.
A certificate chain consists of the end-entity certificate, intermediate certificates, and optionally the root certificate.
Definition at line 339 of file certificate.h.
Constructor & Destructor Documentation
certificate_chain()
kcenon::pacs::security::certificate_chain::certificate_chain () default
Default constructor - creates an empty chain.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/security/certificate.h.
Member Function Documentation
add()
void kcenon::pacs::security::certificate_chain::add (certificate cert)
Add a certificate to the chain.
Parameters
cert Certificate to add
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/security/certificate.h.
Definition at line 615 of file certificate.cpp.
{
    certs_.push_back(std::move(cert));
}
References certs_.
Referenced by load_from_pem().
certificates()
auto kcenon::pacs::security::certificate_chain::certificates () const -> const std::vector<certificate>& nodiscard
Get all certificates in the chain.
Returns
Vector of certificates (end-entity first, root last)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/security/certificate.h.
Definition at line 626 of file certificate.cpp.
{
    return certs_;
}
References certs_.
empty()
auto kcenon::pacs::security::certificate_chain::empty () const -> bool nodiscard noexcept
Check if chain is empty.
Returns
true if no certificates in chain
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/security/certificate.h.
Definition at line 630 of file certificate.cpp.
{
    return certs_.empty();
}
References certs_.
Referenced by load_from_pem().
end_entity()
auto kcenon::pacs::security::certificate_chain::end_entity () const -> const certificate* nodiscard
Get the end-entity (leaf) certificate.
Returns
End-entity certificate or nullptr if chain is empty
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/security/certificate.h.
Definition at line 619 of file certificate.cpp.
{
    if (certs_.empty()) {
        return nullptr;
    }
    return &certs_.front();
}
References certs_.
load_from_pem()
auto kcenon::pacs::security::certificate_chain::load_from_pem (std::string_view path) -> kcenon::common::Result<certificate_chain> static nodiscard
Load certificate chain from PEM file.
PEM file may contain multiple certificates. The first certificate is treated as the end-entity certificate.
Parameters
path Path to PEM file containing certificate chain
Returns
Result containing certificate chain or error
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/security/certificate.h.
Definition at line 638 of file certificate.cpp.
{
    auto content_result = read_file(path);
    if (content_result.is_err()) {
        return kcenon::common::make_error<certificate_chain>(
            content_result.error().code,
            content_result.error().message,
            "certificate_chain");
    }
    const std::string& content = content_result.value();
    certificate_chain chain;
    // Parse multiple certificates from PEM
    bio_ptr bio(BIO_new_mem_buf(content.data(), static_cast<int>(content.size())));
    if (!bio) {
        return kcenon::common::make_error<certificate_chain>(
            2, "Failed to create BIO: " + get_openssl_error(), "certificate_chain");
    }
    while (true) {
        X509* x509 = PEM_read_bio_X509(bio.get(), nullptr, nullptr, nullptr);
        if (!x509) {
            // Check if it's EOF or an error
            unsigned long err = ERR_peek_last_error();
            if (ERR_GET_REASON(err) == PEM_R_NO_START_LINE) {
                ERR_clear_error();
                break; // End of file
            }
            break; // Error or EOF
        }
        certificate cert;
        cert.impl_ = std::make_unique<certificate_impl>(x509);
        chain.add(std::move(cert));
    }
    if (chain.empty()) {
        return kcenon::common::make_error<certificate_chain>(
            3, "No certificates found in PEM file", "certificate_chain");
    }
    return chain;
}
References add(), empty(), and kcenon::pacs::security::certificate::impl_.
size()
auto kcenon::pacs::security::certificate_chain::size () const -> size_t nodiscard noexcept
Get number of certificates in chain.
Returns
Certificate count
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/security/certificate.h.
Definition at line 634 of file certificate.cpp.
{
    return certs_.size();
}
References certs_.
Member Data Documentation
certs_
std::vector<certificate> kcenon::pacs::security::certificate_chain::certs_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/security/certificate.h.
Definition at line 389 of file certificate.h.
Referenced by add(), certificates(), empty(), end_entity(), and size().
The documentation for this class was generated from the following files:
include/kcenon/pacs/security/certificate.h
src/security/certificate.cpp