PACS System: kcenon::pacs::monitoring::dicom_collector_base< Derived > Class Template Reference
kcenon::pacs::monitoring::dicom_collector_base< Derived > Class Template Reference
CRTP base class for DICOM metric collectors.
#include <dicom_collector_base.hpp>
Public Member Functions
dicom_collector_base ()=default
virtual ~dicom_collector_base ()=default
dicom_collector_base (const dicom_collector_base &)=delete
dicom_collector_base & operator= (const dicom_collector_base &)=delete
dicom_collector_base (dicom_collector_base &&)=delete
dicom_collector_base & operator= (dicom_collector_base &&)=delete
bool initialize (const config_map &config)
Initialize the collector with configuration.
std::vector< dicom_metric > collect ()
Collect metrics from the data source.
std::string get_name () const
Get the name of this collector.
std::vector< std::string > get_metric_types () const
Get supported metric types.
bool is_healthy () const
Check if the collector is healthy.
stats_map get_statistics () const
Get collector statistics.
bool is_enabled () const
Check if collector is enabled.
std::size_t get_collection_count () const
Get collection count.
std::size_t get_collection_errors () const
Get error count.
std::string get_ae_title () const
Get the AE title.
void set_ae_title (std::string ae_title)
Set the AE title.
Protected Member Functions
dicom_metric create_base_metric (const std::string &name, double value, const std::string &type, const std::unordered_map< std::string, std::string > &extra_tags={}) const
Create a metric with common tags.
Protected Attributes
bool enabled_ {true}
std::string ae_title_ {"PACS_SCP"}
std::mutex stats_mutex_
std::atomic< std::size_t > collection_count_ {0}
std::atomic< std::size_t > collection_errors_ {0}
std::chrono::steady_clock::time_point init_time_
std::chrono::system_clock::time_point last_collection_time_
Private Member Functions
Derived & derived ()
Get reference to derived class (CRTP helper)
const Derived & derived () const
Detailed Description
template<typename Derived>
class kcenon::pacs::monitoring::dicom_collector_base< Derived >
CRTP base class for DICOM metric collectors.
This template class implements common functionality shared by all DICOM collectors:
Configuration parsing (enabled state, AE title)
Collection with error handling and statistics
Health monitoring
Statistics tracking (collection count, error count)
Usage:
class my_dicom_collector : public dicom_collector_base<my_dicom_collector> {
public:
    static constexpr const char* collector_name = "my_dicom_collector";
    bool do_initialize(const config_map& config) {
        return true;
    }
    std::vector<dicom_metric> do_collect() {
        return metrics;
    }
    bool is_available() const { return true; }
    std::vector<std::string> do_get_metric_types() const {
        return {"metric_1", "metric_2"};
    }
    void do_add_statistics(stats_map& stats) const {}
};
Template Parameters
Derived The derived collector class (CRTP pattern)
Definition at line 129 of file dicom_collector_base.hpp.
Constructor & Destructor Documentation
dicom_collector_base() [1/3]
template<typename Derived > kcenon::pacs::monitoring::dicom_collector_base< Derived >::dicom_collector_base () default
~dicom_collector_base()
template<typename Derived > virtual kcenon::pacs::monitoring::dicom_collector_base< Derived >::~dicom_collector_base () virtual default
dicom_collector_base() [2/3]
template<typename Derived > kcenon::pacs::monitoring::dicom_collector_base< Derived >::dicom_collector_base (const dicom_collector_base< Derived > &) delete
dicom_collector_base() [3/3]
template<typename Derived > kcenon::pacs::monitoring::dicom_collector_base< Derived >::dicom_collector_base (dicom_collector_base< Derived > &&) delete
Member Function Documentation
collect()
template<typename Derived > std::vector< dicom_metric > kcenon::pacs::monitoring::dicom_collector_base< Derived >::collect () inline
Collect metrics from the data source.
Returns
Collection of DICOM metrics
Definition at line 167 of file dicom_collector_base.hpp.
{
        if (!enabled_) {
            return {};
        }
        try {
            auto metrics = derived().do_collect();
            ++collection_count_;
            last_collection_time_ = std::chrono::system_clock::now();
            return metrics;
        } catch (...) {
            ++collection_errors_;
            return {};
        }
    }
References kcenon::pacs::monitoring::dicom_collector_base< Derived >::collection_count_, kcenon::pacs::monitoring::dicom_collector_base< Derived >::collection_errors_, kcenon::pacs::monitoring::dicom_collector_base< Derived >::derived(), kcenon::pacs::monitoring::dicom_collector_base< Derived >::enabled_, and kcenon::pacs::monitoring::dicom_collector_base< Derived >::last_collection_time_.
create_base_metric()
template<typename Derived > dicom_metric kcenon::pacs::monitoring::dicom_collector_base< Derived >::create_base_metric (const std::string & name, double value, const std::string & type, const std::unordered_map< std::string, std::string > & extra_tags = {}) const inline protected
Create a metric with common tags.
Parameters
name Metric name
value Metric value
type Metric type ("gauge", "counter", "histogram")
extra_tags Additional tags to include
Returns
Created metric
Definition at line 279 of file dicom_collector_base.hpp.
                                                                   {}) const {
        std::unordered_map<std::string, std::string> tags = extra_tags;
        tags["collector"] = Derived::collector_name;
        if (!ae_title_.empty()) {
            tags["ae_title"] = ae_title_;
        }
        return dicom_metric(name, value, type, std::move(tags));
    }
derived() [1/2]
template<typename Derived > Derived & kcenon::pacs::monitoring::dicom_collector_base< Derived >::derived () inline private
Get reference to derived class (CRTP helper)
Definition at line 309 of file dicom_collector_base.hpp.
{ return static_cast<Derived&>(*this); }
Referenced by kcenon::pacs::monitoring::dicom_collector_base< Derived >::collect(), kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_metric_types(), kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_statistics(), kcenon::pacs::monitoring::dicom_collector_base< Derived >::initialize(), and kcenon::pacs::monitoring::dicom_collector_base< Derived >::is_healthy().
derived() [2/2]
template<typename Derived > const Derived & kcenon::pacs::monitoring::dicom_collector_base< Derived >::derived () const inline private
Definition at line 310 of file dicom_collector_base.hpp.
{ return static_cast<const Derived&>(*this); }
get_ae_title()
template<typename Derived > std::string kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_ae_title () const inline
Get the AE title.
Returns
Application Entity title
Definition at line 262 of file dicom_collector_base.hpp.
{ return ae_title_; }
References kcenon::pacs::monitoring::dicom_collector_base< Derived >::ae_title_.
get_collection_count()
template<typename Derived > std::size_t kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_collection_count () const inline
Get collection count.
Returns
Number of successful collections
Definition at line 246 of file dicom_collector_base.hpp.
{
        return collection_count_.load();
    }
References kcenon::pacs::monitoring::dicom_collector_base< Derived >::collection_count_.
get_collection_errors()
template<typename Derived > std::size_t kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_collection_errors () const inline
Get error count.
Returns
Number of failed collections
Definition at line 254 of file dicom_collector_base.hpp.
{
        return collection_errors_.load();
    }
References kcenon::pacs::monitoring::dicom_collector_base< Derived >::collection_errors_.
get_metric_types()
template<typename Derived > std::vector< std::string > kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_metric_types () const inline
Get supported metric types.
Returns
Vector of supported metric type names
Definition at line 195 of file dicom_collector_base.hpp.
{
        return derived().do_get_metric_types();
    }
References kcenon::pacs::monitoring::dicom_collector_base< Derived >::derived().
get_name()
template<typename Derived > std::string kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_name () const inline
Get the name of this collector.
Returns
Collector name from Derived::collector_name
Definition at line 187 of file dicom_collector_base.hpp.
{
        return Derived::collector_name;
    }
get_statistics()
template<typename Derived > stats_map kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_statistics () const inline
Get collector statistics.
Returns
Map of statistic name to value
Definition at line 214 of file dicom_collector_base.hpp.
{
        std::lock_guard<std::mutex> lock(stats_mutex_);
        stats_map stats;
        // Common statistics
        stats["enabled"] = enabled_ ? 1.0 : 0.0;
        stats["collection_count"] = static_cast<double>(collection_count_.load());
        stats["collection_errors"] = static_cast<double>(collection_errors_.load());
        // Uptime if initialized
        if (init_time_.time_since_epoch().count() > 0) {
            const auto uptime = std::chrono::duration_cast<std::chrono::seconds>(
                std::chrono::steady_clock::now() - init_time_);
            stats["uptime_seconds"] = static_cast<double>(uptime.count());
        }
        // Let derived class add specific statistics
        derived().do_add_statistics(stats);
        return stats;
    }
References kcenon::pacs::monitoring::dicom_collector_base< Derived >::collection_count_, kcenon::pacs::monitoring::dicom_collector_base< Derived >::collection_errors_, kcenon::pacs::monitoring::dicom_collector_base< Derived >::derived(), kcenon::pacs::monitoring::dicom_collector_base< Derived >::enabled_, kcenon::pacs::monitoring::dicom_collector_base< Derived >::init_time_, and kcenon::pacs::monitoring::dicom_collector_base< Derived >::stats_mutex_.
initialize()
template<typename Derived > bool kcenon::pacs::monitoring::dicom_collector_base< Derived >::initialize (const config_map & config) inline
Initialize the collector with configuration.
Parameters
config Configuration options
"enabled": "true"/"false" (default: true)
"ae_title": Application Entity title for labeling
Returns
true if initialization successful
Definition at line 147 of file dicom_collector_base.hpp.
{
        // Parse common configuration
        if (auto it = config.find("enabled"); it != config.end()) {
            enabled_ = (it->second == "true" || it->second == "1");
        }
        if (auto it = config.find("ae_title"); it != config.end()) {
            ae_title_ = it->second;
        }
        init_time_ = std::chrono::steady_clock::now();
        // Delegate to derived class for specific initialization
        return derived().do_initialize(config);
    }
References kcenon::pacs::monitoring::dicom_collector_base< Derived >::ae_title_, kcenon::pacs::monitoring::dicom_collector_base< Derived >::derived(), kcenon::pacs::monitoring::dicom_collector_base< Derived >::enabled_, and kcenon::pacs::monitoring::dicom_collector_base< Derived >::init_time_.
is_enabled()
template<typename Derived > bool kcenon::pacs::monitoring::dicom_collector_base< Derived >::is_enabled () const inline
Check if collector is enabled.
Returns
true if enabled
Definition at line 240 of file dicom_collector_base.hpp.
{ return enabled_; }
References kcenon::pacs::monitoring::dicom_collector_base< Derived >::enabled_.
is_healthy()
template<typename Derived > bool kcenon::pacs::monitoring::dicom_collector_base< Derived >::is_healthy () const inline
Check if the collector is healthy.
Returns
true if collector is operational
Definition at line 203 of file dicom_collector_base.hpp.
{
        if (!enabled_) {
            return true;  // Disabled collectors are considered healthy
        }
        return derived().is_available();
    }
References kcenon::pacs::monitoring::dicom_collector_base< Derived >::derived(), and kcenon::pacs::monitoring::dicom_collector_base< Derived >::enabled_.
operator=() [1/2]
template<typename Derived > dicom_collector_base & kcenon::pacs::monitoring::dicom_collector_base< Derived >::operator= (const dicom_collector_base< Derived > &) delete
operator=() [2/2]
template<typename Derived > dicom_collector_base & kcenon::pacs::monitoring::dicom_collector_base< Derived >::operator= (dicom_collector_base< Derived > &&) delete
set_ae_title()
template<typename Derived > void kcenon::pacs::monitoring::dicom_collector_base< Derived >::set_ae_title (std::string ae_title) inline
Set the AE title.
Parameters
ae_title Application Entity title
Definition at line 268 of file dicom_collector_base.hpp.
{ ae_title_ = std::move(ae_title); }
References kcenon::pacs::monitoring::dicom_collector_base< Derived >::ae_title_.
Member Data Documentation
ae_title_
template<typename Derived > std::string kcenon::pacs::monitoring::dicom_collector_base< Derived >::ae_title_ {"PACS_SCP"} protected
Definition at line 296 of file dicom_collector_base.hpp.
{"PACS_SCP"};
Referenced by kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_ae_title(), kcenon::pacs::monitoring::dicom_collector_base< Derived >::initialize(), and kcenon::pacs::monitoring::dicom_collector_base< Derived >::set_ae_title().
collection_count_
template<typename Derived > std::atomic<std::size_t> kcenon::pacs::monitoring::dicom_collector_base< Derived >::collection_count_ {0} protected
Definition at line 300 of file dicom_collector_base.hpp.
{0};
Referenced by kcenon::pacs::monitoring::dicom_collector_base< Derived >::collect(), kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_collection_count(), and kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_statistics().
collection_errors_
template<typename Derived > std::atomic<std::size_t> kcenon::pacs::monitoring::dicom_collector_base< Derived >::collection_errors_ {0} protected
Definition at line 301 of file dicom_collector_base.hpp.
{0};
Referenced by kcenon::pacs::monitoring::dicom_collector_base< Derived >::collect(), kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_collection_errors(), and kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_statistics().
enabled_
template<typename Derived > bool kcenon::pacs::monitoring::dicom_collector_base< Derived >::enabled_ {true} protected
Definition at line 295 of file dicom_collector_base.hpp.
{true};
Referenced by kcenon::pacs::monitoring::dicom_collector_base< Derived >::collect(), kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_statistics(), kcenon::pacs::monitoring::dicom_collector_base< Derived >::initialize(), kcenon::pacs::monitoring::dicom_collector_base< Derived >::is_enabled(), and kcenon::pacs::monitoring::dicom_collector_base< Derived >::is_healthy().
init_time_
template<typename Derived > std::chrono::steady_clock::time_point kcenon::pacs::monitoring::dicom_collector_base< Derived >::init_time_ protected
Definition at line 302 of file dicom_collector_base.hpp.
Referenced by kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_statistics(), and kcenon::pacs::monitoring::dicom_collector_base< Derived >::initialize().
last_collection_time_
template<typename Derived > std::chrono::system_clock::time_point kcenon::pacs::monitoring::dicom_collector_base< Derived >::last_collection_time_ protected
Definition at line 303 of file dicom_collector_base.hpp.
Referenced by kcenon::pacs::monitoring::dicom_collector_base< Derived >::collect().
stats_mutex_
template<typename Derived > std::mutex kcenon::pacs::monitoring::dicom_collector_base< Derived >::stats_mutex_ mutable protected
Definition at line 299 of file dicom_collector_base.hpp.
Referenced by kcenon::pacs::monitoring::dicom_collector_base< Derived >::get_statistics().
The documentation for this class was generated from the following file:
include/pacs/monitoring/collectors/dicom_collector_base.hpp