PACS System: kcenon::pacs::security::certificate Class Reference
kcenon::pacs::security::certificate Class Reference
#include <certificate.hpp>
Public Member Functions
certificate ()
Default constructor - creates an empty certificate.
certificate (const certificate &other)
Copy constructor.
certificate (certificate &&other) noexcept
Move constructor.
auto operator= (const certificate &other) -> certificate &
Copy assignment.
auto operator= (certificate &&other) noexcept -> certificate &
Move assignment.
~certificate ()
Destructor.
auto subject_name () const -> std::string
Get the subject distinguished name.
auto subject_common_name () const -> std::string
Get the common name from the subject.
auto subject_organization () const -> std::string
Get the organization from the subject.
auto issuer_name () const -> std::string
Get the issuer distinguished name.
auto serial_number () const -> std::string
Get the certificate serial number.
auto thumbprint () const -> std::string
Get the certificate thumbprint (SHA-256)
auto not_before () const -> std::chrono::system_clock::time_point
Get the not-before date.
auto not_after () const -> std::chrono::system_clock::time_point
Get the not-after date.
auto is_valid () const -> bool
Check if the certificate is currently valid.
auto is_expired () const -> bool
Check if the certificate has expired.
auto to_pem () const -> std::string
Export certificate as PEM string.
auto to_der () const -> std::vector< std::uint8_t >
Export certificate as DER bytes.
auto is_loaded () const noexcept -> bool
Check if certificate is loaded.
auto impl () const noexcept -> const certificate_impl *
Get internal implementation (for internal use only)
auto impl () noexcept -> certificate_impl *
Static Public Member Functions
static auto load_from_pem (std::string_view path) -> kcenon::common::Result< certificate >
Load certificate from PEM file.
static auto load_from_pem_string (std::string_view pem_data) -> kcenon::common::Result< certificate >
Load certificate from PEM string.
static auto load_from_der (std::span< const std::uint8_t > der_data) -> kcenon::common::Result< certificate >
Load certificate from DER-encoded bytes.
Private Attributes
std::unique_ptr< certificate_impl > impl_
Friends
class certificate_chain
Detailed Description
Definition at line 81 of file certificate.hpp.
Constructor & Destructor Documentation
certificate() [1/3]
kcenon::pacs::security::certificate::certificate ()
Default constructor - creates an empty certificate.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 239 of file certificate.cpp.
: impl_(std::make_unique<certificate_impl>()) {}
certificate() [2/3]
kcenon::pacs::security::certificate::certificate (const certificate & other)
Copy constructor.
Definition at line 241 of file certificate.cpp.
    : impl_(std::make_unique<certificate_impl>(*other.impl_)) {}
certificate() [3/3]
kcenon::pacs::security::certificate::certificate (certificate && other) default noexcept
Move constructor.
~certificate()
kcenon::pacs::security::certificate::~certificate () default
Destructor.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Member Function Documentation
impl() [1/2]
auto kcenon::pacs::security::certificate::impl () const -> const certificate_impl* noexcept
Get internal implementation (for internal use only)
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 533 of file certificate.cpp.
{
    return impl_.get();
}
References impl_.
Referenced by kcenon::pacs::security::get_x509_from_certificate().
impl() [2/2]
auto kcenon::pacs::security::certificate::impl () -> certificate_impl* noexcept
Definition at line 537 of file certificate.cpp.
{
    return impl_.get();
}
References impl_.
is_expired()
auto kcenon::pacs::security::certificate::is_expired () const -> bool
Check if the certificate has expired.
Returns
true if certificate has expired
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 489 of file certificate.cpp.
{
    if (!impl_->is_loaded()) {
        return true;
    }
    auto now = std::chrono::system_clock::now();
    return now > not_after();
}
References impl_, and not_after().
is_loaded()
auto kcenon::pacs::security::certificate::is_loaded () const -> bool noexcept
Check if certificate is loaded.
Returns
true if certificate data is loaded
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 529 of file certificate.cpp.
{
    return impl_ && impl_->is_loaded();
}
References impl_.
is_valid()
auto kcenon::pacs::security::certificate::is_valid () const -> bool
Check if the certificate is currently valid.
Returns
true if current time is within validity period
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 480 of file certificate.cpp.
{
    if (!impl_->is_loaded()) {
        return false;
    }
    auto now = std::chrono::system_clock::now();
    return now >= not_before() && now <= not_after();
}
References impl_, not_after(), and not_before().
issuer_name()
auto kcenon::pacs::security::certificate::issuer_name () const -> std::string
Get the issuer distinguished name.
Returns
Issuer name
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 393 of file certificate.cpp.
{
    if (!impl_->is_loaded()) {
        return "";
    }
    X509_NAME* name = X509_get_issuer_name(impl_->x509());
    if (!name) {
        return "";
    }
    bio_ptr bio(BIO_new(BIO_s_mem()));
    X509_NAME_print_ex(bio.get(), name, 0, XN_FLAG_RFC2253);
    char* data = nullptr;
    long len = BIO_get_mem_data(bio.get(), &data);
    return std::string(data, static_cast<size_t>(len));
}
References impl_, and name.
load_from_der()
auto kcenon::pacs::security::certificate::load_from_der (std::span< const std::uint8_t > der_data) -> kcenon::common::Result<certificate> static
Load certificate from DER-encoded bytes.
Parameters
der_data DER-encoded certificate bytes
Returns
Result containing certificate or error
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 289 of file certificate.cpp.
{
    const unsigned char* data = der_data.data();
    X509* x509 = d2i_X509(nullptr, &data, static_cast<long>(der_data.size()));
    if (!x509) {
        return kcenon::common::make_error<certificate>(
            4, "Failed to parse DER certificate: " + get_openssl_error(), "certificate");
    }
    certificate cert;
    cert.impl_ = std::make_unique<certificate_impl>(x509);
    return cert;
}
References impl_.
Referenced by kcenon::pacs::security::digital_signature::get_signature_info(), kcenon::pacs::security::digital_signature::verify(), and kcenon::pacs::security::digital_signature::verify_with_trust().
load_from_pem()
auto kcenon::pacs::security::certificate::load_from_pem (std::string_view path) -> kcenon::common::Result<certificate> static
Load certificate from PEM file.
Parameters
path Path to PEM-encoded certificate file
Returns
Result containing certificate or error
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 257 of file certificate.cpp.
{
    auto content_result = read_file(path);
    if (content_result.is_err()) {
        return kcenon::common::make_error<certificate>(
            content_result.error().code,
            content_result.error().message,
            "certificate");
    }
    return load_from_pem_string(content_result.value());
}
load_from_pem_string()
auto kcenon::pacs::security::certificate::load_from_pem_string (std::string_view pem_data) -> kcenon::common::Result<certificate> static
Load certificate from PEM string.
Parameters
pem_data PEM-encoded certificate data
Returns
Result containing certificate or error
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 270 of file certificate.cpp.
{
    bio_ptr bio(BIO_new_mem_buf(pem_data.data(), static_cast<int>(pem_data.size())));
    if (!bio) {
        return kcenon::common::make_error<certificate>(
            2, "Failed to create BIO: " + get_openssl_error(), "certificate");
    }
    X509* x509 = PEM_read_bio_X509(bio.get(), nullptr, nullptr, nullptr);
    if (!x509) {
        return kcenon::common::make_error<certificate>(
            3, "Failed to parse PEM certificate: " + get_openssl_error(), "certificate");
    }
    certificate cert;
    cert.impl_ = std::make_unique<certificate_impl>(x509);
    return cert;
}
References impl_.
not_after()
auto kcenon::pacs::security::certificate::not_after () const -> std::chrono::system_clock::time_point
Get the not-after date.
Returns
End of validity period
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 471 of file certificate.cpp.
{
    if (!impl_->is_loaded()) {
        return std::chrono::system_clock::time_point{};
    }
    const ASN1_TIME* time = X509_get0_notAfter(impl_->x509());
    return asn1_time_to_time_point(time);
}
References impl_.
Referenced by is_expired(), and is_valid().
not_before()
auto kcenon::pacs::security::certificate::not_before () const -> std::chrono::system_clock::time_point
Get the not-before date.
Returns
Start of validity period
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 462 of file certificate.cpp.
{
    if (!impl_->is_loaded()) {
        return std::chrono::system_clock::time_point{};
    }
    const ASN1_TIME* time = X509_get0_notBefore(impl_->x509());
    return asn1_time_to_time_point(time);
}
References impl_.
Referenced by is_valid().
operator=() [1/2]
auto kcenon::pacs::security::certificate::operator= (certificate && other) -> certificate & default noexcept
Move assignment.
operator=() [2/2]
auto kcenon::pacs::security::certificate::operator= (const certificate & other) -> certificate&
Copy assignment.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 246 of file certificate.cpp.
{
    if (this != &other) {
        impl_ = std::make_unique<certificate_impl>(*other.impl_);
    }
    return *this;
}
References kcenon::pacs::security::other.
serial_number()
auto kcenon::pacs::security::certificate::serial_number () const -> std::string
Get the certificate serial number.
Returns
Serial number as hex string
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 411 of file certificate.cpp.
{
    if (!impl_->is_loaded()) {
        return "";
    }
    const ASN1_INTEGER* serial = X509_get_serialNumber(impl_->x509());
    if (!serial) {
        return "";
    }
    BIGNUM* bn = ASN1_INTEGER_to_BN(serial, nullptr);
    if (!bn) {
        return "";
    }
    char* hex = BN_bn2hex(bn);
    BN_free(bn);
    if (!hex) {
        return "";
    }
    std::string result(hex);
    OPENSSL_free(hex);
    return result;
}
References impl_.
subject_common_name()
auto kcenon::pacs::security::certificate::subject_common_name () const -> std::string
Get the common name from the subject.
Returns
Common name (CN) or empty string if not present
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 321 of file certificate.cpp.
{
    if (!impl_->is_loaded()) {
        return "";
    }
    X509_NAME* name = X509_get_subject_name(impl_->x509());
    if (!name) {
        return "";
    }
    int idx = X509_NAME_get_index_by_NID(name, NID_commonName, -1);
    if (idx < 0) {
        return "";
    }
    X509_NAME_ENTRY* entry = X509_NAME_get_entry(name, idx);
    if (!entry) {
        return "";
    }
    ASN1_STRING* data = X509_NAME_ENTRY_get_data(entry);
    if (!data) {
        return "";
    }
    unsigned char* utf8 = nullptr;
    int len = ASN1_STRING_to_UTF8(&utf8, data);
    if (len < 0) {
        return "";
    }
    std::string result(reinterpret_cast<char*>(utf8), static_cast<size_t>(len));
    OPENSSL_free(utf8);
    return result;
}
References impl_, and name.
subject_name()
auto kcenon::pacs::security::certificate::subject_name () const -> std::string
Get the subject distinguished name.
Returns
Subject name (e.g., "CN=John Doe,O=Hospital,C=US")
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 303 of file certificate.cpp.
{
    if (!impl_->is_loaded()) {
        return "";
    }
    X509_NAME* name = X509_get_subject_name(impl_->x509());
    if (!name) {
        return "";
    }
    bio_ptr bio(BIO_new(BIO_s_mem()));
    X509_NAME_print_ex(bio.get(), name, 0, XN_FLAG_RFC2253);
    char* data = nullptr;
    long len = BIO_get_mem_data(bio.get(), &data);
    return std::string(data, static_cast<size_t>(len));
}
References impl_, and name.
subject_organization()
auto kcenon::pacs::security::certificate::subject_organization () const -> std::string
Get the organization from the subject.
Returns
Organization (O) or empty string if not present
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 357 of file certificate.cpp.
{
    if (!impl_->is_loaded()) {
        return "";
    }
    X509_NAME* name = X509_get_subject_name(impl_->x509());
    if (!name) {
        return "";
    }
    int idx = X509_NAME_get_index_by_NID(name, NID_organizationName, -1);
    if (idx < 0) {
        return "";
    }
    X509_NAME_ENTRY* entry = X509_NAME_get_entry(name, idx);
    if (!entry) {
        return "";
    }
    ASN1_STRING* data = X509_NAME_ENTRY_get_data(entry);
    if (!data) {
        return "";
    }
    unsigned char* utf8 = nullptr;
    int len = ASN1_STRING_to_UTF8(&utf8, data);
    if (len < 0) {
        return "";
    }
    std::string result(reinterpret_cast<char*>(utf8), static_cast<size_t>(len));
    OPENSSL_free(utf8);
    return result;
}
References impl_, and name.
thumbprint()
auto kcenon::pacs::security::certificate::thumbprint () const -> std::string
Get the certificate thumbprint (SHA-256)
Returns
Thumbprint as hex string
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 438 of file certificate.cpp.
{
    if (!impl_->is_loaded()) {
        return "";
    }
    unsigned char hash[EVP_MAX_MD_SIZE];
    unsigned int hash_len = 0;
    if (X509_digest(impl_->x509(), EVP_sha256(), hash, &hash_len) != 1) {
        return "";
    }
    std::string result;
    result.reserve(hash_len * 2);
    static const char hex_chars[] = "0123456789ABCDEF";
    for (unsigned int i = 0; i < hash_len; ++i) {
        result += hex_chars[(hash[i] >> 4) & 0x0F];
        result += hex_chars[hash[i] & 0x0F];
    }
    return result;
}
References kcenon::pacs::security::hash, and impl_.
to_der()
auto kcenon::pacs::security::certificate::to_der () const -> std::vector<std::uint8_t>
Export certificate as DER bytes.
Returns
DER-encoded certificate
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 513 of file certificate.cpp.
{
    if (!impl_->is_loaded()) {
        return {};
    }
    unsigned char* data = nullptr;
    int len = i2d_X509(impl_->x509(), &data);
    if (len <= 0) {
        return {};
    }
    std::vector<std::uint8_t> result(data, data + len);
    OPENSSL_free(data);
    return result;
}
References impl_.
to_pem()
auto kcenon::pacs::security::certificate::to_pem () const -> std::string
Export certificate as PEM string.
Returns
PEM-encoded certificate
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 498 of file certificate.cpp.
{
    if (!impl_->is_loaded()) {
        return "";
    }
    bio_ptr bio(BIO_new(BIO_s_mem()));
    if (PEM_write_bio_X509(bio.get(), impl_->x509()) != 1) {
        return "";
    }
    char* data = nullptr;
    long len = BIO_get_mem_data(bio.get(), &data);
    return std::string(data, static_cast<size_t>(len));
}
References impl_.
Friends And Related Symbol Documentation
certificate_chain
friend class certificate_chain friend
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 242 of file certificate.hpp.
Member Data Documentation
impl_
std::unique_ptr<certificate_impl> kcenon::pacs::security::certificate::impl_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/security/certificate.hpp.
Definition at line 243 of file certificate.hpp.
Referenced by impl(), impl(), is_expired(), is_loaded(), is_valid(), issuer_name(), load_from_der(), kcenon::pacs::security::certificate_chain::load_from_pem(), load_from_pem_string(), not_after(), not_before(), serial_number(), subject_common_name(), subject_name(), subject_organization(), thumbprint(), to_der(), and to_pem().
The documentation for this class was generated from the following files:
include/pacs/security/certificate.hpp
src/security/certificate.cpp