PACS System: kcenon::pacs::services::query_scu Class Reference
kcenon::pacs::services::query_scu Class Reference
#include <query_scu.hpp>
Public Member Functions
query_scu (std::shared_ptr< di::ILogger > logger=nullptr)
Construct a Query SCU with default configuration.
query_scu (const query_scu_config &config, std::shared_ptr< di::ILogger > logger=nullptr)
Construct a Query SCU with custom configuration.
~query_scu ()=default
query_scu (const query_scu &)=delete
query_scu & operator= (const query_scu &)=delete
query_scu (query_scu &&)=delete
query_scu & operator= (query_scu &&)=delete
network::Result< query_result > find (network::association &assoc, const core::dicom_dataset &query_keys)
Perform a C-FIND query with raw dataset.
network::Result< size_t > find_streaming (network::association &assoc, const core::dicom_dataset &query_keys, query_streaming_callback callback)
Perform a streaming C-FIND query for large result sets.
network::Result< query_result > find_patients (network::association &assoc, const patient_query_keys &keys)
Query for patients.
network::Result< query_result > find_studies (network::association &assoc, const study_query_keys &keys)
Query for studies.
network::Result< query_result > find_series (network::association &assoc, const series_query_keys &keys)
Query for series within a study.
network::Result< query_result > find_instances (network::association &assoc, const instance_query_keys &keys)
Query for instances within a series.
network::Result< std::monostate > cancel (network::association &assoc, uint16_t message_id)
Send a C-CANCEL request to stop an ongoing query.
void set_config (const query_scu_config &config)
Update the SCU configuration.
const query_scu_config & config () const noexcept
Get the current configuration.
size_t queries_performed () const noexcept
Get the number of queries performed since construction.
size_t total_matches () const noexcept
Get the total number of matches received since construction.
void reset_statistics () noexcept
Reset statistics counters to zero.
Private Member Functions
network::Result< query_result > find_impl (network::association &assoc, const core::dicom_dataset &query_keys, uint16_t message_id)
Internal query implementation.
uint16_t next_message_id () noexcept
Get the next message ID for DIMSE operations.
core::dicom_dataset build_query_dataset (const patient_query_keys &keys) const
Build query dataset from patient keys.
core::dicom_dataset build_query_dataset (const study_query_keys &keys) const
Build query dataset from study keys.
core::dicom_dataset build_query_dataset (const series_query_keys &keys) const
Build query dataset from series keys.
core::dicom_dataset build_query_dataset (const instance_query_keys &keys) const
Build query dataset from instance keys.
std::string_view get_sop_class_uid () const noexcept
Get SOP Class UID based on current configuration.
Private Attributes
std::shared_ptr< di::ILogger > logger_
Logger instance for service logging.
query_scu_config config_
Configuration.
std::atomic< uint16_t > message_id_counter_ {1}
Message ID counter.
std::atomic< size_t > queries_performed_ {0}
Statistics: number of queries performed.
std::atomic< size_t > total_matches_ {0}
Statistics: total number of matches received.
Detailed Description
Definition at line 319 of file query_scu.hpp.
Constructor & Destructor Documentation
query_scu() [1/4]
kcenon::pacs::services::query_scu::query_scu (std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct a Query SCU with default configuration.
Parameters
logger Logger instance for service logging (nullptr uses null_logger)
Definition at line 50 of file query_scu.cpp.
    : logger_(logger ? std::move(logger) : di::null_logger()) {}
query_scu() [2/4]
kcenon::pacs::services::query_scu::query_scu (const query_scu_config & config, std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct a Query SCU with custom configuration.
Parameters
config Configuration options
logger Logger instance for service logging (nullptr uses null_logger)
Definition at line 53 of file query_scu.cpp.
    : logger_(logger ? std::move(logger) : di::null_logger()), config_(config) {}
~query_scu()
kcenon::pacs::services::query_scu::~query_scu () default
query_scu() [3/4]
kcenon::pacs::services::query_scu::query_scu (const query_scu &) delete
query_scu() [4/4]
kcenon::pacs::services::query_scu::query_scu (query_scu &&) delete
Member Function Documentation
build_query_dataset() [1/4]
core::dicom_dataset kcenon::pacs::services::query_scu::build_query_dataset (const instance_query_keys & keys) const private
Build query dataset from instance keys.
Definition at line 510 of file query_scu.cpp.
{
    using namespace core;
    using namespace encoding;
    dicom_dataset ds;
    // Set Query/Retrieve Level
    ds.set_string(tags::query_retrieve_level, vr_type::CS, "IMAGE");
    // Series UID (required for instance query)
    ds.set_string(tags::series_instance_uid, vr_type::UI, keys.series_uid);
    // Instance keys
    ds.set_string(tags::sop_instance_uid, vr_type::UI, keys.sop_instance_uid);
    ds.set_string(tags::sop_class_uid, vr_type::UI, "");
    ds.set_string(tags::instance_number, vr_type::IS, keys.instance_number);
    return ds;
}
References kcenon::pacs::core::tags::instance_number, kcenon::pacs::services::instance_query_keys::instance_number, kcenon::pacs::core::tags::query_retrieve_level, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::services::instance_query_keys::series_uid, kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, and kcenon::pacs::services::instance_query_keys::sop_instance_uid.
build_query_dataset() [2/4]
core::dicom_dataset kcenon::pacs::services::query_scu::build_query_dataset (const patient_query_keys & keys) const private
Build query dataset from patient keys.
Definition at line 428 of file query_scu.cpp.
{
    using namespace core;
    using namespace encoding;
    dicom_dataset ds;
    // Set Query/Retrieve Level
    ds.set_string(tags::query_retrieve_level, vr_type::CS, "PATIENT");
    // Set query keys (empty string = return key, non-empty = match key)
    ds.set_string(tags::patient_name, vr_type::PN, keys.patient_name);
    ds.set_string(tags::patient_id, vr_type::LO, keys.patient_id);
    ds.set_string(tags::patient_birth_date, vr_type::DA, keys.birth_date);
    ds.set_string(tags::patient_sex, vr_type::CS, keys.sex);
    // Add standard return keys
    ds.set_string(tags::number_of_patient_related_studies, vr_type::IS, "");
    ds.set_string(tags::number_of_patient_related_series, vr_type::IS, "");
    ds.set_string(tags::number_of_patient_related_instances, vr_type::IS, "");
    return ds;
}
References kcenon::pacs::services::patient_query_keys::birth_date, kcenon::pacs::core::tags::number_of_patient_related_instances, kcenon::pacs::core::tags::number_of_patient_related_series, kcenon::pacs::core::tags::number_of_patient_related_studies, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::services::patient_query_keys::patient_id, kcenon::pacs::core::tags::patient_name, kcenon::pacs::services::patient_query_keys::patient_name, kcenon::pacs::core::tags::patient_sex, kcenon::pacs::core::tags::query_retrieve_level, kcenon::pacs::core::dicom_dataset::set_string(), and kcenon::pacs::services::patient_query_keys::sex.
Referenced by find_instances(), find_patients(), find_series(), and find_studies().
build_query_dataset() [3/4]
core::dicom_dataset kcenon::pacs::services::query_scu::build_query_dataset (const series_query_keys & keys) const private
Build query dataset from series keys.
Definition at line 484 of file query_scu.cpp.
{
    using namespace core;
    using namespace encoding;
    dicom_dataset ds;
    // Set Query/Retrieve Level
    ds.set_string(tags::query_retrieve_level, vr_type::CS, "SERIES");
    // Study UID (required for series query)
    ds.set_string(tags::study_instance_uid, vr_type::UI, keys.study_uid);
    // Series keys
    ds.set_string(tags::series_instance_uid, vr_type::UI, keys.series_uid);
    ds.set_string(tags::modality, vr_type::CS, keys.modality);
    ds.set_string(tags::series_number, vr_type::IS, keys.series_number);
    ds.set_string(tags::series_description, vr_type::LO, "");
    // Standard return keys
    ds.set_string(tags::number_of_series_related_instances, vr_type::IS, "");
    return ds;
}
References kcenon::pacs::core::tags::modality, kcenon::pacs::services::series_query_keys::modality, kcenon::pacs::core::tags::number_of_series_related_instances, kcenon::pacs::core::tags::query_retrieve_level, kcenon::pacs::core::tags::series_description, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::series_number, kcenon::pacs::services::series_query_keys::series_number, kcenon::pacs::services::series_query_keys::series_uid, kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::services::series_query_keys::study_uid.
build_query_dataset() [4/4]
core::dicom_dataset kcenon::pacs::services::query_scu::build_query_dataset (const study_query_keys & keys) const private
Build query dataset from study keys.
Definition at line 453 of file query_scu.cpp.
{
    using namespace core;
    using namespace encoding;
    dicom_dataset ds;
    // Set Query/Retrieve Level
    ds.set_string(tags::query_retrieve_level, vr_type::CS, "STUDY");
    // Patient info (return keys)
    ds.set_string(tags::patient_name, vr_type::PN, "");
    ds.set_string(tags::patient_id, vr_type::LO, keys.patient_id);
    // Study keys
    ds.set_string(tags::study_instance_uid, vr_type::UI, keys.study_uid);
    ds.set_string(tags::study_date, vr_type::DA, keys.study_date);
    ds.set_string(tags::study_time, vr_type::TM, "");
    ds.set_string(tags::accession_number, vr_type::SH, keys.accession_number);
    ds.set_string(tags::study_id, vr_type::SH, "");
    ds.set_string(tags::study_description, vr_type::LO, keys.study_description);
    ds.set_string(tags::modalities_in_study, vr_type::CS, keys.modality);
    // Standard return keys
    ds.set_string(tags::number_of_study_related_series, vr_type::IS, "");
    ds.set_string(tags::number_of_study_related_instances, vr_type::IS, "");
    return ds;
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::services::study_query_keys::accession_number, kcenon::pacs::core::tags::modalities_in_study, kcenon::pacs::services::study_query_keys::modality, kcenon::pacs::core::tags::number_of_study_related_instances, kcenon::pacs::core::tags::number_of_study_related_series, kcenon::pacs::core::tags::patient_id, kcenon::pacs::services::study_query_keys::patient_id, kcenon::pacs::core::tags::patient_name, kcenon::pacs::core::tags::query_retrieve_level, kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::core::tags::study_date, kcenon::pacs::services::study_query_keys::study_date, kcenon::pacs::core::tags::study_description, kcenon::pacs::services::study_query_keys::study_description, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, kcenon::pacs::core::tags::study_time, and kcenon::pacs::services::study_query_keys::study_uid.
cancel()
network::Result< std::monostate > kcenon::pacs::services::query_scu::cancel (network::association & assoc, uint16_t message_id)
Send a C-CANCEL request to stop an ongoing query.
Parameters
assoc The association on which the query is running
message_id The message ID of the query to cancel
Returns
Success or error
Definition at line 366 of file query_scu.cpp.
{
    using namespace network::dimse;
    auto sop_class_uid = get_sop_class_uid();
    auto context_id = assoc.accepted_context_id(sop_class_uid);
    if (!context_id) {
        return kcenon::pacs::pacs_error<std::monostate>(
            kcenon::pacs::error_codes::no_acceptable_context,
            "No accepted presentation context for cancel");
    }
    // Build C-CANCEL-RQ manually since there's no factory function
    dimse_message cancel_rq{command_field::c_cancel_rq, message_id};
    return assoc.send_dimse(*context_id, cancel_rq);
}
References kcenon::pacs::network::association::accepted_context_id(), get_sop_class_uid(), kcenon::pacs::error_codes::no_acceptable_context, and kcenon::pacs::network::association::send_dimse().
Referenced by find_impl(), and find_streaming().
config()
const query_scu_config & kcenon::pacs::services::query_scu::config () const noexcept
Get the current configuration.
Returns
Reference to the current configuration
Definition at line 394 of file query_scu.cpp.
{
    return config_;
}
References config_.
Referenced by set_config().
find()
network::Result< query_result > kcenon::pacs::services::query_scu::find (network::association & assoc, const core::dicom_dataset & query_keys)
Perform a C-FIND query with raw dataset.
Sends a C-FIND request with the provided query keys and collects all matching datasets from the SCP.
Parameters
assoc The established association to use
query_keys The DICOM dataset containing query keys
Returns
Result containing query_result on success, or error message
Definition at line 61 of file query_scu.cpp.
{
    return find_impl(assoc, query_keys, next_message_id());
}
References find_impl(), and next_message_id().
Referenced by kcenon::pacs::client::job_manager::impl::execute_prefetch_job(), kcenon::pacs::client::job_manager::impl::execute_query_job(), kcenon::pacs::client::job_manager::impl::execute_sync_job(), find_instances(), find_patients(), find_series(), find_studies(), and kcenon::pacs::client::sync_manager::impl::query_remote_studies().
find_impl()
network::Result< query_result > kcenon::pacs::services::query_scu::find_impl (network::association & assoc, const core::dicom_dataset & query_keys, uint16_t message_id) private
Internal query implementation.
Definition at line 68 of file query_scu.cpp.
{
    using namespace network::dimse;
    auto start_time = std::chrono::steady_clock::now();
    // Verify association is established
    if (!assoc.is_established()) {
        return kcenon::pacs::pacs_error<query_result>(
            kcenon::pacs::error_codes::association_not_established,
            "Association not established");
    }
    // Get SOP Class UID
    auto sop_class_uid = get_sop_class_uid();
    // Get accepted presentation context for this SOP class
    auto context_id = assoc.accepted_context_id(sop_class_uid);
    if (!context_id) {
        return kcenon::pacs::pacs_error<query_result>(
            kcenon::pacs::error_codes::no_acceptable_context,
            "No accepted presentation context for SOP Class: " +
            std::string(sop_class_uid));
    }
    // Build C-FIND-RQ message
    auto request = make_c_find_rq(message_id, sop_class_uid);
    request.set_dataset(query_keys);
    logger_->debug_fmt("Sending C-FIND request (message_id={}, sop_class={})",
                       message_id, sop_class_uid);
    // Send the request
    auto send_result = assoc.send_dimse(*context_id, request);
    if (send_result.is_err()) {
        return send_result.error();
    }
    // Receive responses
    query_result result;
    bool query_complete = false;
    while (!query_complete) {
        auto recv_result = assoc.receive_dimse(config_.timeout);
        if (recv_result.is_err()) {
            return recv_result.error();
        }
        const auto& [recv_context_id, response] = recv_result.value();
        // Verify it's a C-FIND response
        if (response.command() != command_field::c_find_rsp) {
            return kcenon::pacs::pacs_error<query_result>(
                kcenon::pacs::error_codes::find_unexpected_command,
                "Expected C-FIND-RSP but received " +
                std::string(to_string(response.command())));
        }
        auto status = response.status();
        if (status == status_pending || status == status_pending_warning) {
            ++result.total_pending;
            if (response.has_dataset()) {
                // Check if we should collect this result
                if (config_.max_results == 0 ||
                    result.matches.size() < config_.max_results) {
                    auto dataset_result = response.dataset();
                    if (dataset_result.is_ok()) {
                        result.matches.push_back(dataset_result.value().get());
                    }
                }
                // Check if we should cancel due to max_results
                if (config_.max_results > 0 &&
                    result.matches.size() >= config_.max_results &&
                    config_.cancel_on_max) {
                    logger_->debug_fmt(
                        "Max results ({}) reached, sending C-CANCEL",
                        config_.max_results);
                    // Send C-CANCEL
                    auto cancel_result = cancel(assoc, message_id);
                    if (cancel_result.is_err()) {
                        logger_->warn_fmt("Failed to send C-CANCEL: {}",
                                          cancel_result.error().message);
                    }
                }
            }
        } else if (status == status_success) {
            query_complete = true;
            result.status = static_cast<uint16_t>(status);
        } else if (status == status_cancel) {
            query_complete = true;
            result.status = static_cast<uint16_t>(status);
        } else {
            // Error status
            query_complete = true;
            result.status = static_cast<uint16_t>(status);
        }
    }
    auto end_time = std::chrono::steady_clock::now();
    result.elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
        end_time - start_time);
    // Update statistics
    queries_performed_.fetch_add(1, std::memory_order_relaxed);
    total_matches_.fetch_add(result.matches.size(), std::memory_order_relaxed);
    logger_->debug_fmt("C-FIND completed: {} matches in {} ms",
                       result.matches.size(), result.elapsed.count());
    return result;
}
References kcenon::pacs::network::association::accepted_context_id(), kcenon::pacs::error_codes::association_not_established, cancel(), kcenon::pacs::services::query_scu_config::cancel_on_max, config_, kcenon::pacs::services::query_result::elapsed, kcenon::pacs::error_codes::find_unexpected_command, get_sop_class_uid(), kcenon::pacs::network::association::is_established(), logger_, kcenon::pacs::services::query_result::matches, kcenon::pacs::services::query_scu_config::max_results, kcenon::pacs::error_codes::no_acceptable_context, queries_performed_, kcenon::pacs::network::association::receive_dimse(), kcenon::pacs::network::association::send_dimse(), kcenon::pacs::services::query_result::status, kcenon::pacs::services::query_scu_config::timeout, total_matches_, and kcenon::pacs::services::query_result::total_pending.
Referenced by find().
find_instances()
network::Result< query_result > kcenon::pacs::services::query_scu::find_instances (network::association & assoc, const instance_query_keys & keys)
Query for instances within a series.
Parameters
assoc The established association to use
keys Instance-level query keys (series_uid required)
Returns
Result containing query_result on success
Definition at line 348 of file query_scu.cpp.
{
    auto saved_level = config_.level;
    config_.level = query_level::image;
    auto query_ds = build_query_dataset(keys);
    auto result = find(assoc, query_ds);
    config_.level = saved_level;
    return result;
}
References build_query_dataset(), config_, find(), kcenon::pacs::services::image, and kcenon::pacs::services::query_scu_config::level.
Referenced by kcenon::pacs::web::endpoints::register_remote_nodes_endpoints_impl().
find_patients()
network::Result< query_result > kcenon::pacs::services::query_scu::find_patients (network::association & assoc, const patient_query_keys & keys)
Query for patients.
Parameters
assoc The established association to use
keys Patient-level query keys
Returns
Result containing query_result on success
Definition at line 306 of file query_scu.cpp.
{
    auto saved_level = config_.level;
    config_.level = query_level::patient;
    auto query_ds = build_query_dataset(keys);
    auto result = find(assoc, query_ds);
    config_.level = saved_level;
    return result;
}
References build_query_dataset(), config_, find(), kcenon::pacs::services::query_scu_config::level, and kcenon::pacs::services::patient.
Referenced by kcenon::pacs::web::endpoints::register_remote_nodes_endpoints_impl().
find_series()
network::Result< query_result > kcenon::pacs::services::query_scu::find_series (network::association & assoc, const series_query_keys & keys)
Query for series within a study.
Parameters
assoc The established association to use
keys Series-level query keys (study_uid required)
Returns
Result containing query_result on success
Definition at line 334 of file query_scu.cpp.
{
    auto saved_level = config_.level;
    config_.level = query_level::series;
    auto query_ds = build_query_dataset(keys);
    auto result = find(assoc, query_ds);
    config_.level = saved_level;
    return result;
}
References build_query_dataset(), config_, find(), kcenon::pacs::services::query_scu_config::level, and kcenon::pacs::services::series.
Referenced by kcenon::pacs::web::endpoints::register_remote_nodes_endpoints_impl().
find_streaming()
network::Result< size_t > kcenon::pacs::services::query_scu::find_streaming (network::association & assoc, const core::dicom_dataset & query_keys, query_streaming_callback callback)
Perform a streaming C-FIND query for large result sets.
Sends a C-FIND request and calls the callback for each pending response. This is more memory-efficient for large result sets.
Parameters
assoc The established association to use
query_keys The DICOM dataset containing query keys
callback Called for each matching dataset; return false to cancel
Returns
Result containing the number of results processed, or error
Definition at line 189 of file query_scu.cpp.
{
    using namespace network::dimse;
    auto message_id = next_message_id();
    auto start_time = std::chrono::steady_clock::now();
    // Verify association is established
    if (!assoc.is_established()) {
        return kcenon::pacs::pacs_error<size_t>(
            kcenon::pacs::error_codes::association_not_established,
            "Association not established");
    }
    // Get SOP Class UID
    auto sop_class_uid = get_sop_class_uid();
    // Get accepted presentation context for this SOP class
    auto context_id = assoc.accepted_context_id(sop_class_uid);
    if (!context_id) {
        return kcenon::pacs::pacs_error<size_t>(
            kcenon::pacs::error_codes::no_acceptable_context,
            "No accepted presentation context for SOP Class: " +
            std::string(sop_class_uid));
    }
    // Build C-FIND-RQ message
    auto request = make_c_find_rq(message_id, sop_class_uid);
    request.set_dataset(query_keys);
    logger_->debug_fmt("Sending streaming C-FIND request (message_id={})",
                       message_id);
    // Send the request
    auto send_result = assoc.send_dimse(*context_id, request);
    if (send_result.is_err()) {
        return send_result.error();
    }
    // Receive responses
    size_t count = 0;
    bool query_complete = false;
    bool should_cancel = false;
    while (!query_complete) {
        auto recv_result = assoc.receive_dimse(config_.timeout);
        if (recv_result.is_err()) {
            return recv_result.error();
        }
        const auto& [recv_context_id, response] = recv_result.value();
        // Verify it's a C-FIND response
        if (response.command() != command_field::c_find_rsp) {
            return kcenon::pacs::pacs_error<size_t>(
                kcenon::pacs::error_codes::find_unexpected_command,
                "Expected C-FIND-RSP but received " +
                std::string(to_string(response.command())));
        }
        auto status = response.status();
        if (status == status_pending || status == status_pending_warning) {
            if (response.has_dataset()) {
                auto dataset_result = response.dataset();
                if (dataset_result.is_ok()) {
                    ++count;
                    // Call the callback
                    if (callback) {
                        if (!callback(dataset_result.value().get())) {
                            should_cancel = true;
                        }
                    }
                    // Check if we need to cancel
                    if (should_cancel ||
                        (config_.max_results > 0 &&
                         count >= config_.max_results &&
                         config_.cancel_on_max)) {
                        logger_->debug("Cancelling streaming query");
                        auto cancel_result = cancel(assoc, message_id);
                        if (cancel_result.is_err()) {
                            logger_->warn_fmt("Failed to send C-CANCEL: {}",
                                              cancel_result.error().message);
                        }
                        should_cancel = false;  // Already sent cancel
                    }
                }
            }
        } else {
            query_complete = true;
        }
    }
    // Update statistics
    queries_performed_.fetch_add(1, std::memory_order_relaxed);
    total_matches_.fetch_add(count, std::memory_order_relaxed);
    auto end_time = std::chrono::steady_clock::now();
    auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
        end_time - start_time);
    logger_->debug_fmt("Streaming C-FIND completed: {} results in {} ms",
                       count, elapsed.count());
    return count;
}
References kcenon::pacs::network::association::accepted_context_id(), kcenon::pacs::error_codes::association_not_established, cancel(), kcenon::pacs::services::query_scu_config::cancel_on_max, config_, kcenon::pacs::error_codes::find_unexpected_command, get_sop_class_uid(), kcenon::pacs::network::association::is_established(), logger_, kcenon::pacs::services::query_scu_config::max_results, next_message_id(), kcenon::pacs::error_codes::no_acceptable_context, queries_performed_, kcenon::pacs::network::association::receive_dimse(), kcenon::pacs::network::association::send_dimse(), kcenon::pacs::services::query_scu_config::timeout, and total_matches_.
find_studies()
network::Result< query_result > kcenon::pacs::services::query_scu::find_studies (network::association & assoc, const study_query_keys & keys)
Query for studies.
Parameters
assoc The established association to use
keys Study-level query keys
Returns
Result containing query_result on success
Definition at line 320 of file query_scu.cpp.
{
    auto saved_level = config_.level;
    config_.level = query_level::study;
    auto query_ds = build_query_dataset(keys);
    auto result = find(assoc, query_ds);
    config_.level = saved_level;
    return result;
}
References build_query_dataset(), config_, find(), kcenon::pacs::services::query_scu_config::level, and kcenon::pacs::services::study.
Referenced by kcenon::pacs::workflow::auto_prefetch_service::query_prior_studies(), and kcenon::pacs::web::endpoints::register_remote_nodes_endpoints_impl().
get_sop_class_uid()
std::string_view kcenon::pacs::services::query_scu::get_sop_class_uid () const private noexcept
Get SOP Class UID based on current configuration.
Definition at line 532 of file query_scu.cpp.
{
    return get_find_sop_class_uid(config_.model);
}
References config_, kcenon::pacs::services::get_find_sop_class_uid(), and kcenon::pacs::services::query_scu_config::model.
Referenced by cancel(), find_impl(), and find_streaming().
next_message_id()
uint16_t kcenon::pacs::services::query_scu::next_message_id () private noexcept
Get the next message ID for DIMSE operations.
Definition at line 419 of file query_scu.cpp.
{
    uint16_t id = message_id_counter_.fetch_add(1, std::memory_order_relaxed);
    // Wrap around at 0xFFFF, skip 0 (reserved)
    if (id == 0) {
        id = message_id_counter_.fetch_add(1, std::memory_order_relaxed);
    }
    return id;
}
References message_id_counter_.
Referenced by find(), and find_streaming().
operator=() [1/2]
query_scu & kcenon::pacs::services::query_scu::operator= (const query_scu &) delete
operator=() [2/2]
query_scu & kcenon::pacs::services::query_scu::operator= (query_scu &&) delete
queries_performed()
size_t kcenon::pacs::services::query_scu::queries_performed () const noexcept
Get the number of queries performed since construction.
Returns
Count of C-FIND requests sent
Definition at line 402 of file query_scu.cpp.
{
    return queries_performed_.load(std::memory_order_relaxed);
}
References queries_performed_.
reset_statistics()
void kcenon::pacs::services::query_scu::reset_statistics () noexcept
Reset statistics counters to zero.
Definition at line 410 of file query_scu.cpp.
{
    queries_performed_.store(0, std::memory_order_relaxed);
    total_matches_.store(0, std::memory_order_relaxed);
}
References queries_performed_, and total_matches_.
set_config()
void kcenon::pacs::services::query_scu::set_config (const query_scu_config & config)
Update the SCU configuration.
Parameters
config New configuration options
Definition at line 390 of file query_scu.cpp.
{
    config_ = config;
}
References config(), and config_.
total_matches()
size_t kcenon::pacs::services::query_scu::total_matches () const noexcept
Get the total number of matches received since construction.
Returns
Total count of matching datasets received
Definition at line 406 of file query_scu.cpp.
{
    return total_matches_.load(std::memory_order_relaxed);
}
References total_matches_.
Member Data Documentation
config_
query_scu_config kcenon::pacs::services::query_scu::config_ private
Configuration.
Definition at line 540 of file query_scu.hpp.
Referenced by config(), find_impl(), find_instances(), find_patients(), find_series(), find_streaming(), find_studies(), get_sop_class_uid(), and set_config().
logger_
std::shared_ptr<di::ILogger> kcenon::pacs::services::query_scu::logger_ private
Logger instance for service logging.
Definition at line 537 of file query_scu.hpp.
Referenced by find_impl(), and find_streaming().
message_id_counter_
std::atomic<uint16_t> kcenon::pacs::services::query_scu::message_id_counter_ {1} private
Message ID counter.
Definition at line 543 of file query_scu.hpp.
{1};
Referenced by next_message_id().
queries_performed_
std::atomic<size_t> kcenon::pacs::services::query_scu::queries_performed_ {0} private
Statistics: number of queries performed.
Definition at line 546 of file query_scu.hpp.
{0};
Referenced by find_impl(), find_streaming(), queries_performed(), and reset_statistics().
total_matches_
std::atomic<size_t> kcenon::pacs::services::query_scu::total_matches_ {0} private
Statistics: total number of matches received.
Definition at line 549 of file query_scu.hpp.
{0};
Referenced by find_impl(), find_streaming(), reset_statistics(), and total_matches().
The documentation for this class was generated from the following files:
include/pacs/services/query_scu.hpp
src/services/query_scu.cpp