PACS System: kcenon::pacs::services::pir::patient_reconciliation_service Class Reference
kcenon::pacs::services::pir::patient_reconciliation_service Class Reference
#include <patient_reconciliation_service.h>
Public Member Functions
patient_reconciliation_service ()=default
bool add_instance (const core::dicom_dataset &dataset)
Add a DICOM instance to the managed store.
reconciliation_result update_demographics (const demographics_update_request &request)
Update patient demographics across all matching instances.
reconciliation_result merge_patients (const patient_merge_request &request)
Merge instances from source patient to target patient.
std::vector< core::dicom_dataset > find_instances (const std::string &patient_id) const
Find all instances for a given patient ID.
size_t instance_count () const noexcept
Get the total number of managed instances.
std::vector< std::string > get_patient_ids () const
Get distinct patient IDs in the store.
const std::vector< reconciliation_audit_record > & audit_trail () const noexcept
Get the audit trail of reconciliation operations.
std::vector< reconciliation_audit_record > audit_trail_for_patient (const std::string &patient_id) const
Get audit records for a specific patient.
Private Member Functions
void apply_demographics (core::dicom_dataset &dataset, const patient_demographics &demographics) const
std::string generate_record_id () const
Private Attributes
std::vector< core::dicom_dataset > instances_
std::vector< reconciliation_audit_record > audit_records_
Detailed Description
Definition at line 194 of file patient_reconciliation_service.h.
Constructor & Destructor Documentation
patient_reconciliation_service()
kcenon::pacs::services::pir::patient_reconciliation_service::patient_reconciliation_service () default
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/pir/patient_reconciliation_service.h.
Member Function Documentation
add_instance()
bool kcenon::pacs::services::pir::patient_reconciliation_service::add_instance (const core::dicom_dataset & dataset)
Add a DICOM instance to the managed store.
Parameters
dataset The DICOM dataset to add
Returns
true if added successfully
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/pir/patient_reconciliation_service.h.
Definition at line 28 of file patient_reconciliation_service.cpp.
{
    auto uid = dataset.get_string(tags::sop_instance_uid);
    if (uid.empty()) {
        return false;
    }
    instances_.push_back(dataset);
    return true;
}
References kcenon::pacs::core::dicom_dataset::get_string(), instances_, kcenon::pacs::core::tags::sop_instance_uid, and uid.
apply_demographics()
void kcenon::pacs::services::pir::patient_reconciliation_service::apply_demographics (core::dicom_dataset & dataset, const patient_demographics & demographics) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/pir/patient_reconciliation_service.h.
Definition at line 212 of file patient_reconciliation_service.cpp.
{
    if (demographics.patient_name) {
        dataset.set_string(tags::patient_name, vr_type::PN,
                           demographics.patient_name.value());
    }
    if (demographics.patient_id) {
        dataset.set_string(tags::patient_id, vr_type::LO,
                           demographics.patient_id.value());
    }
    if (demographics.patient_birth_date) {
        dataset.set_string(tags::patient_birth_date, vr_type::DA,
                           demographics.patient_birth_date.value());
    }
    if (demographics.patient_sex) {
        dataset.set_string(tags::patient_sex, vr_type::CS,
                           demographics.patient_sex.value());
    }
    if (demographics.issuer_of_patient_id) {
        dataset.set_string(tags::issuer_of_patient_id, vr_type::LO,
                           demographics.issuer_of_patient_id.value());
    }
}
References kcenon::pacs::core::tags::issuer_of_patient_id, kcenon::pacs::services::pir::patient_demographics::issuer_of_patient_id, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::services::pir::patient_demographics::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::services::pir::patient_demographics::patient_id, kcenon::pacs::core::tags::patient_name, kcenon::pacs::services::pir::patient_demographics::patient_name, kcenon::pacs::core::tags::patient_sex, kcenon::pacs::services::pir::patient_demographics::patient_sex, and kcenon::pacs::core::dicom_dataset::set_string().
Referenced by merge_patients(), and update_demographics().
audit_trail()
const std::vector< reconciliation_audit_record > & kcenon::pacs::services::pir::patient_reconciliation_service::audit_trail () const nodiscard noexcept
Get the audit trail of reconciliation operations.
Returns
List of audit records
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/pir/patient_reconciliation_service.h.
Definition at line 189 of file patient_reconciliation_service.cpp.
{
    return audit_records_;
}
References audit_records_.
audit_trail_for_patient()
std::vector< reconciliation_audit_record > kcenon::pacs::services::pir::patient_reconciliation_service::audit_trail_for_patient (const std::string & patient_id) const nodiscard
Get audit records for a specific patient.
Parameters
patient_id Patient ID to filter by
Returns
Filtered audit records
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/pir/patient_reconciliation_service.h.
Definition at line 194 of file patient_reconciliation_service.cpp.
{
    std::vector<reconciliation_audit_record> results;
    for (const auto& record : audit_records_) {
        if (record.primary_patient_id == patient_id ||
            (record.secondary_patient_id &&
             record.secondary_patient_id.value() == patient_id)) {
            results.push_back(record);
        }
    }
    return results;
}
References audit_records_.
find_instances()
std::vector< core::dicom_dataset > kcenon::pacs::services::pir::patient_reconciliation_service::find_instances (const std::string & patient_id) const nodiscard
Find all instances for a given patient ID.
Parameters
patient_id Patient ID to search for
Returns
List of matching DICOM datasets
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/pir/patient_reconciliation_service.h.
Definition at line 161 of file patient_reconciliation_service.cpp.
{
    std::vector<core::dicom_dataset> results;
    for (const auto& instance : instances_) {
        if (instance.get_string(tags::patient_id) == patient_id) {
            results.push_back(instance);
        }
    }
    return results;
}
References instances_, and kcenon::pacs::core::tags::patient_id.
generate_record_id()
std::string kcenon::pacs::services::pir::patient_reconciliation_service::generate_record_id () const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/pir/patient_reconciliation_service.h.
Definition at line 238 of file patient_reconciliation_service.cpp.
{
    static std::mt19937_64 gen{std::random_device{}()};
    static std::uniform_int_distribution<uint64_t> dist;
    auto now = std::chrono::system_clock::now();
    auto timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(
        now.time_since_epoch()).count();
    return "PIR-" + std::to_string(timestamp) + "-" +
           std::to_string(dist(gen) % 100000);
}
Referenced by merge_patients(), and update_demographics().
get_patient_ids()
std::vector< std::string > kcenon::pacs::services::pir::patient_reconciliation_service::get_patient_ids () const nodiscard
Get distinct patient IDs in the store.
Returns
List of unique patient IDs
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/pir/patient_reconciliation_service.h.
Definition at line 177 of file patient_reconciliation_service.cpp.
{
    std::set<std::string> ids;
    for (const auto& instance : instances_) {
        auto pid = instance.get_string(tags::patient_id);
        if (!pid.empty()) {
            ids.insert(pid);
        }
    }
    return {ids.begin(), ids.end()};
}
References instances_, and kcenon::pacs::core::tags::patient_id.
instance_count()
size_t kcenon::pacs::services::pir::patient_reconciliation_service::instance_count () const nodiscard noexcept
Get the total number of managed instances.
Returns
Instance count
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/pir/patient_reconciliation_service.h.
Definition at line 173 of file patient_reconciliation_service.cpp.
{
    return instances_.size();
}
References instances_.
merge_patients()
reconciliation_result kcenon::pacs::services::pir::patient_reconciliation_service::merge_patients (const patient_merge_request & request) nodiscard
Merge instances from source patient to target patient.
All instances belonging to the source patient are reassigned to the target patient. The source patient effectively ceases to exist after the merge.
Parameters
request Patient merge request
Returns
Result of the operation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/pir/patient_reconciliation_service.h.
Definition at line 91 of file patient_reconciliation_service.cpp.
{
    reconciliation_result result;
    result.type = reconciliation_type::patient_merge;
    if (request.source_patient_id.empty()) {
        result.error_message = "Source patient ID is required";
        return result;
    }
    if (request.target_patient_id.empty()) {
        result.error_message = "Target patient ID is required";
        return result;
    }
    if (request.source_patient_id == request.target_patient_id) {
        result.error_message = "Source and target patient IDs must be different";
        return result;
    }
    size_t updated = 0;
    std::set<std::string> affected_studies;
    for (auto& instance : instances_) {
        auto pid = instance.get_string(tags::patient_id);
        if (pid == request.source_patient_id) {
            // Reassign to target patient
            instance.set_string(tags::patient_id, vr_type::LO,
                                request.target_patient_id);
            // Apply target demographics if provided
            if (request.target_demographics) {
                apply_demographics(instance, request.target_demographics.value());
            }
            updated++;
            auto study_uid = instance.get_string(tags::study_instance_uid);
            if (!study_uid.empty()) {
                affected_studies.insert(study_uid);
            }
        }
    }
    if (updated == 0) {
        result.error_message = "No instances found for source patient ID: " +
                               request.source_patient_id;
        return result;
    }
    result.success = true;
    result.instances_updated = updated;
    result.studies_affected = affected_studies.size();
    // Create audit record
    reconciliation_audit_record audit;
    audit.record_id = generate_record_id();
    audit.type = reconciliation_type::patient_merge;
    audit.primary_patient_id = request.target_patient_id;
    audit.secondary_patient_id = request.source_patient_id;
    audit.operator_name = request.operator_name.value_or("SYSTEM");
    audit.instances_updated = updated;
    audit.timestamp = std::chrono::system_clock::now();
    audit.success = true;
    audit_records_.push_back(std::move(audit));
    return result;
}
References apply_demographics(), audit_records_, kcenon::pacs::services::pir::reconciliation_result::error_message, generate_record_id(), instances_, kcenon::pacs::services::pir::reconciliation_audit_record::instances_updated, kcenon::pacs::services::pir::reconciliation_result::instances_updated, kcenon::pacs::services::pir::patient_merge_request::operator_name, kcenon::pacs::services::pir::reconciliation_audit_record::operator_name, kcenon::pacs::core::tags::patient_id, kcenon::pacs::services::pir::patient_merge, kcenon::pacs::services::pir::reconciliation_audit_record::primary_patient_id, kcenon::pacs::services::pir::reconciliation_audit_record::record_id, kcenon::pacs::services::pir::reconciliation_audit_record::secondary_patient_id, kcenon::pacs::services::pir::patient_merge_request::source_patient_id, kcenon::pacs::services::pir::reconciliation_result::studies_affected, kcenon::pacs::core::tags::study_instance_uid, kcenon::pacs::services::pir::reconciliation_audit_record::success, kcenon::pacs::services::pir::reconciliation_result::success, kcenon::pacs::services::pir::patient_merge_request::target_demographics, kcenon::pacs::services::pir::patient_merge_request::target_patient_id, kcenon::pacs::services::pir::reconciliation_audit_record::timestamp, kcenon::pacs::services::pir::reconciliation_audit_record::type, and kcenon::pacs::services::pir::reconciliation_result::type.
update_demographics()
reconciliation_result kcenon::pacs::services::pir::patient_reconciliation_service::update_demographics (const demographics_update_request & request) nodiscard
Update patient demographics across all matching instances.
Finds all instances with the specified patient ID and updates the patient-level attributes with the new values.
Parameters
request Demographics update request
Returns
Result of the operation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/pir/patient_reconciliation_service.h.
Definition at line 40 of file patient_reconciliation_service.cpp.
{
    reconciliation_result result;
    result.type = reconciliation_type::demographics_update;
    if (request.target_patient_id.empty()) {
        result.error_message = "Target patient ID is required";
        return result;
    }
    size_t updated = 0;
    std::set<std::string> affected_studies;
    for (auto& instance : instances_) {
        auto pid = instance.get_string(tags::patient_id);
        if (pid == request.target_patient_id) {
            apply_demographics(instance, request.updated_demographics);
            updated++;
            auto study_uid = instance.get_string(tags::study_instance_uid);
            if (!study_uid.empty()) {
                affected_studies.insert(study_uid);
            }
        }
    }
    if (updated == 0) {
        result.error_message = "No instances found for patient ID: " +
                               request.target_patient_id;
        return result;
    }
    result.success = true;
    result.instances_updated = updated;
    result.studies_affected = affected_studies.size();
    // Create audit record
    reconciliation_audit_record audit;
    audit.record_id = generate_record_id();
    audit.type = reconciliation_type::demographics_update;
    audit.primary_patient_id = request.target_patient_id;
    audit.operator_name = request.operator_name.value_or("SYSTEM");
    audit.instances_updated = updated;
    audit.timestamp = std::chrono::system_clock::now();
    audit.success = true;
    audit_records_.push_back(std::move(audit));
    return result;
}
References apply_demographics(), audit_records_, kcenon::pacs::services::pir::demographics_update, kcenon::pacs::services::pir::reconciliation_result::error_message, generate_record_id(), instances_, kcenon::pacs::services::pir::reconciliation_audit_record::instances_updated, kcenon::pacs::services::pir::reconciliation_result::instances_updated, kcenon::pacs::services::pir::demographics_update_request::operator_name, kcenon::pacs::services::pir::reconciliation_audit_record::operator_name, kcenon::pacs::core::tags::patient_id, kcenon::pacs::services::pir::reconciliation_audit_record::primary_patient_id, kcenon::pacs::services::pir::reconciliation_audit_record::record_id, kcenon::pacs::services::pir::reconciliation_result::studies_affected, kcenon::pacs::core::tags::study_instance_uid, kcenon::pacs::services::pir::reconciliation_audit_record::success, kcenon::pacs::services::pir::reconciliation_result::success, kcenon::pacs::services::pir::demographics_update_request::target_patient_id, kcenon::pacs::services::pir::reconciliation_audit_record::timestamp, kcenon::pacs::services::pir::reconciliation_audit_record::type, kcenon::pacs::services::pir::reconciliation_result::type, and kcenon::pacs::services::pir::demographics_update_request::updated_demographics.
Member Data Documentation
audit_records_
std::vector<reconciliation_audit_record> kcenon::pacs::services::pir::patient_reconciliation_service::audit_records_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/pir/patient_reconciliation_service.h.
Definition at line 277 of file patient_reconciliation_service.h.
Referenced by audit_trail(), audit_trail_for_patient(), merge_patients(), and update_demographics().
instances_
std::vector<core::dicom_dataset> kcenon::pacs::services::pir::patient_reconciliation_service::instances_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/pir/patient_reconciliation_service.h.
Definition at line 276 of file patient_reconciliation_service.h.
Referenced by add_instance(), find_instances(), get_patient_ids(), instance_count(), merge_patients(), and update_demographics().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/pir/patient_reconciliation_service.h
src/services/pir/patient_reconciliation_service.cpp