PACS System: kcenon::pacs::storage::migration_runner Class Reference
kcenon::pacs::storage::migration_runner Class Reference
#include <migration_runner.h>
Public Member Functions
migration_runner ()
Default constructor.
~migration_runner ()=default
Default destructor.
migration_runner (const migration_runner &)=delete
auto operator= (const migration_runner &) -> migration_runner &=delete
migration_runner (migration_runner &&)=delete
auto operator= (migration_runner &&) -> migration_runner &=delete
auto run_migrations (sqlite3 *db) -> VoidResult
Run all pending migrations.
auto run_migrations_to (sqlite3 *db, int target_version) -> VoidResult
Run migrations up to a specific version.
auto get_current_version (sqlite3 *db) const -> int
Get the current schema version.
auto get_latest_version () const noexcept -> int
Get the latest available schema version.
auto needs_migration (sqlite3 *db) const -> bool
Check if migration is needed.
auto get_history (sqlite3 *db) const -> std::vector< migration_record >
Get the migration history.
Private Member Functions
auto ensure_schema_version_table (sqlite3 *db) -> VoidResult
Create the schema_version table if it doesn't exist.
auto apply_migration (sqlite3 *db, int version) -> VoidResult
Apply a single migration.
auto record_migration (sqlite3 *db, int version, std::string_view description) -> VoidResult
Record a migration in the schema_version table.
auto execute_sql (sqlite3 *db, std::string_view sql) -> VoidResult
Execute SQL statement and handle errors.
auto migrate_v1 (sqlite3 *db) -> VoidResult
auto migrate_v2 (sqlite3 *db) -> VoidResult
auto migrate_v3 (sqlite3 *db) -> VoidResult
auto migrate_v4 (sqlite3 *db) -> VoidResult
auto migrate_v5 (sqlite3 *db) -> VoidResult
auto migrate_v6 (sqlite3 *db) -> VoidResult
auto migrate_v7 (sqlite3 *db) -> VoidResult
auto migrate_v8 (sqlite3 *db) -> VoidResult
auto migrate_v9 (sqlite3 *db) -> VoidResult
Private Attributes
std::vector< std::pair< int, migration_function > > migrations_
Migration function registry.
Static Private Attributes
static constexpr int LATEST_VERSION = 9
Latest schema version (increment when adding migrations)
Detailed Description
Definition at line 103 of file migration_runner.h.
Constructor & Destructor Documentation
migration_runner() [1/3]
kcenon::pacs::storage::migration_runner::migration_runner ()
Default constructor.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 36 of file migration_runner.cpp.
{
    // Register all migrations (SQLite version)
    migrations_.push_back({1, [this](sqlite3* db) { return migrate_v1(db); }});
    migrations_.push_back({2, [this](sqlite3* db) { return migrate_v2(db); }});
    migrations_.push_back({3, [this](sqlite3* db) { return migrate_v3(db); }});
    migrations_.push_back({4, [this](sqlite3* db) { return migrate_v4(db); }});
    migrations_.push_back({5, [this](sqlite3* db) { return migrate_v5(db); }});
    migrations_.push_back({6, [this](sqlite3* db) { return migrate_v6(db); }});
    migrations_.push_back({7, [this](sqlite3* db) { return migrate_v7(db); }});
    migrations_.push_back({8, [this](sqlite3* db) { return migrate_v8(db); }});
    migrations_.push_back({9, [this](sqlite3* db) { return migrate_v9(db); }});
#ifdef PACS_WITH_DATABASE_SYSTEM
    // Register all migrations (pacs_database_adapter version)
    adapter_migrations_.push_back(
        {1, [this](pacs_database_adapter& db) { return migrate_v1(db); }});
    adapter_migrations_.push_back(
        {2, [this](pacs_database_adapter& db) { return migrate_v2(db); }});
    adapter_migrations_.push_back(
        {3, [this](pacs_database_adapter& db) { return migrate_v3(db); }});
    adapter_migrations_.push_back(
        {4, [this](pacs_database_adapter& db) { return migrate_v4(db); }});
    adapter_migrations_.push_back(
        {5, [this](pacs_database_adapter& db) { return migrate_v5(db); }});
    adapter_migrations_.push_back(
        {6, [this](pacs_database_adapter& db) { return migrate_v6(db); }});
    adapter_migrations_.push_back(
        {7, [this](pacs_database_adapter& db) { return migrate_v7(db); }});
    adapter_migrations_.push_back(
        {8, [this](pacs_database_adapter& db) { return migrate_v8(db); }});
    adapter_migrations_.push_back(
        {9, [this](pacs_database_adapter& db) { return migrate_v9(db); }});
#endif
}
References migrate_v1(), migrate_v2(), migrate_v3(), migrate_v4(), migrate_v5(), migrate_v6(), migrate_v7(), migrate_v8(), migrate_v9(), and migrations_.
~migration_runner()
kcenon::pacs::storage::migration_runner::~migration_runner () default
Default destructor.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
migration_runner() [2/3]
kcenon::pacs::storage::migration_runner::migration_runner (const migration_runner &) delete
migration_runner() [3/3]
kcenon::pacs::storage::migration_runner::migration_runner (migration_runner &&) delete
Member Function Documentation
apply_migration()
auto kcenon::pacs::storage::migration_runner::apply_migration (sqlite3 * db, int version) -> VoidResult nodiscard private
Apply a single migration.
Parameters
db The SQLite database handle
version The migration version to apply
Returns
VoidResult Success or error information
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 231 of file migration_runner.cpp.
{
    // Find the migration function
    for (const auto& [ver, func] : migrations_) {
        if (ver == version) {
            return func(db);
        }
    }
    return make_error<std::monostate>(
        -1,
        kcenon::pacs::compat::format("Migration for version {} not found", version),
        "storage");
}
ensure_schema_version_table()
auto kcenon::pacs::storage::migration_runner::ensure_schema_version_table (sqlite3 * db) -> VoidResult nodiscard private
Create the schema_version table if it doesn't exist.
Parameters
db The SQLite database handle
Returns
VoidResult Success or error information
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 219 of file migration_runner.cpp.
{
    const char* sql = R"(
        CREATE TABLE IF NOT EXISTS schema_version (
            version     INTEGER PRIMARY KEY,
            description TEXT NOT NULL,
            applied_at  TEXT NOT NULL DEFAULT (datetime('now'))
        );
    )";
    return execute_sql(db, sql);
}
execute_sql()
auto kcenon::pacs::storage::migration_runner::execute_sql (sqlite3 * db, std::string_view sql) -> VoidResult nodiscard private
Execute SQL statement and handle errors.
Parameters
db The SQLite database handle
sql The SQL statement to execute
Returns
VoidResult Success or error information
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 279 of file migration_runner.cpp.
                  {
    char* errmsg = nullptr;
    auto rc = sqlite3_exec(db, sql.data(), nullptr, nullptr, &errmsg);
    if (rc != SQLITE_OK) {
        auto error_str = errmsg ? std::string(errmsg) : "Unknown error";
        sqlite3_free(errmsg);
        return make_error<std::monostate>(
            rc, kcenon::pacs::compat::format("SQL execution failed: {}", error_str),
            "storage");
    }
    return ok();
}
get_current_version()
auto kcenon::pacs::storage::migration_runner::get_current_version (sqlite3 * db) const -> int nodiscard
Get the current schema version.
Returns 0 if no migrations have been applied (schema_version table doesn't exist or is empty).
Parameters
db The SQLite database handle
Returns
Current schema version number
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 137 of file migration_runner.cpp.
{
    // Check if schema_version table exists
    const char* check_sql =
        "SELECT name FROM sqlite_master WHERE type='table' AND name='schema_version';";
    sqlite3_stmt* stmt = nullptr;
    auto rc = sqlite3_prepare_v2(db, check_sql, -1, &stmt, nullptr);
    if (rc != SQLITE_OK) {
        return 0;
    }
    rc = sqlite3_step(stmt);
    sqlite3_finalize(stmt);
    if (rc != SQLITE_ROW) {
        // Table doesn't exist
        return 0;
    }
    // Get max version from table
    const char* version_sql = "SELECT MAX(version) FROM schema_version;";
    rc = sqlite3_prepare_v2(db, version_sql, -1, &stmt, nullptr);
    if (rc != SQLITE_OK) {
        return 0;
    }
    int version = 0;
    if (sqlite3_step(stmt) == SQLITE_ROW) {
        // sqlite3_column_int returns 0 for NULL
        version = sqlite3_column_int(stmt, 0);
    }
    sqlite3_finalize(stmt);
    return version;
}
Referenced by kcenon::pacs::storage::index_database::schema_version().
get_history()
auto kcenon::pacs::storage::migration_runner::get_history (sqlite3 * db) const -> std::vector<migration_record> nodiscard
Get the migration history.
Returns all applied migrations in chronological order.
Parameters
db The SQLite database handle
Returns
Vector of migration records, empty if no migrations applied
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 185 of file migration_runner.cpp.
{
    std::vector<migration_record> history;
    const char* sql =
        "SELECT version, description, applied_at FROM schema_version ORDER BY version;";
    sqlite3_stmt* stmt = nullptr;
    auto rc = sqlite3_prepare_v2(db, sql, -1, &stmt, nullptr);
    if (rc != SQLITE_OK) {
        return history;
    }
    while (sqlite3_step(stmt) == SQLITE_ROW) {
        migration_record record;
        record.version = sqlite3_column_int(stmt, 0);
        const auto* desc = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 1));
        record.description = desc ? desc : "";
        const auto* applied = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 2));
        record.applied_at = applied ? applied : "";
        history.push_back(std::move(record));
    }
    sqlite3_finalize(stmt);
    return history;
}
get_latest_version()
auto kcenon::pacs::storage::migration_runner::get_latest_version () const -> int nodiscard noexcept
Get the latest available schema version.
Returns
The highest version number available for migration
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 173 of file migration_runner.cpp.
{
    return LATEST_VERSION;
}
References LATEST_VERSION.
migrate_v1()
auto kcenon::pacs::storage::migration_runner::migrate_v1 (sqlite3 * db) -> VoidResult nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 300 of file migration_runner.cpp.
{
    // V1: Initial schema - Create all base tables
    const char* sql = R"(
        -- =====================================================================
        -- PATIENTS TABLE
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS patients (
            patient_pk      INTEGER PRIMARY KEY AUTOINCREMENT,
            patient_id      TEXT NOT NULL UNIQUE,
            patient_name    TEXT,
            birth_date      TEXT,
            sex             TEXT,
            other_ids       TEXT,
            ethnic_group    TEXT,
            comments        TEXT,
            created_at      TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at      TEXT NOT NULL DEFAULT (datetime('now')),
            CHECK (length(patient_id) <= 64)
        );
        CREATE INDEX IF NOT EXISTS idx_patients_name ON patients(patient_name);
        CREATE INDEX IF NOT EXISTS idx_patients_birth ON patients(birth_date);
        -- =====================================================================
        -- STUDIES TABLE
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS studies (
            study_pk            INTEGER PRIMARY KEY AUTOINCREMENT,
            patient_pk          INTEGER NOT NULL REFERENCES patients(patient_pk)
                                ON DELETE CASCADE,
            study_uid           TEXT NOT NULL UNIQUE,
            study_id            TEXT,
            study_date          TEXT,
            study_time          TEXT,
            accession_number    TEXT,
            referring_physician TEXT,
            study_description   TEXT,
            modalities_in_study TEXT,
            num_series          INTEGER DEFAULT 0,
            num_instances       INTEGER DEFAULT 0,
            created_at          TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
            CHECK (length(study_uid) <= 64)
        );
        CREATE INDEX IF NOT EXISTS idx_studies_patient ON studies(patient_pk);
        CREATE INDEX IF NOT EXISTS idx_studies_date ON studies(study_date);
        CREATE INDEX IF NOT EXISTS idx_studies_accession ON studies(accession_number);
        -- =====================================================================
        -- SERIES TABLE
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS series (
            series_pk           INTEGER PRIMARY KEY AUTOINCREMENT,
            study_pk            INTEGER NOT NULL REFERENCES studies(study_pk)
                                ON DELETE CASCADE,
            series_uid          TEXT NOT NULL UNIQUE,
            series_number       INTEGER,
            modality            TEXT,
            series_description  TEXT,
            body_part_examined  TEXT,
            station_name        TEXT,
            num_instances       INTEGER DEFAULT 0,
            created_at          TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
            CHECK (length(series_uid) <= 64)
        );
        CREATE INDEX IF NOT EXISTS idx_series_study ON series(study_pk);
        CREATE INDEX IF NOT EXISTS idx_series_modality ON series(modality);
        -- =====================================================================
        -- INSTANCES TABLE
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS instances (
            instance_pk     INTEGER PRIMARY KEY AUTOINCREMENT,
            series_pk       INTEGER NOT NULL REFERENCES series(series_pk)
                            ON DELETE CASCADE,
            sop_uid         TEXT NOT NULL UNIQUE,
            sop_class_uid   TEXT NOT NULL,
            instance_number INTEGER,
            transfer_syntax TEXT,
            content_date    TEXT,
            content_time    TEXT,
            rows            INTEGER,
            columns         INTEGER,
            bits_allocated  INTEGER,
            number_of_frames INTEGER,
            file_path       TEXT NOT NULL,
            file_size       INTEGER NOT NULL,
            file_hash       TEXT,
            created_at      TEXT NOT NULL DEFAULT (datetime('now')),
            CHECK (length(sop_uid) <= 64),
            CHECK (file_size >= 0)
        );
        CREATE INDEX IF NOT EXISTS idx_instances_series ON instances(series_pk);
        CREATE INDEX IF NOT EXISTS idx_instances_sop_class ON instances(sop_class_uid);
        CREATE INDEX IF NOT EXISTS idx_instances_number ON instances(instance_number);
        CREATE INDEX IF NOT EXISTS idx_instances_created ON instances(created_at);
        -- =====================================================================
        -- MPPS TABLE (Modality Performed Procedure Step)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS mpps (
            mpps_pk             INTEGER PRIMARY KEY AUTOINCREMENT,
            mpps_uid            TEXT NOT NULL UNIQUE,
            status              TEXT NOT NULL,
            start_datetime      TEXT,
            end_datetime        TEXT,
            station_ae          TEXT,
            station_name        TEXT,
            modality            TEXT,
            study_uid           TEXT,
            accession_no        TEXT,
            scheduled_step_id   TEXT,
            requested_proc_id   TEXT,
            performed_series    TEXT,
            created_at          TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
            CHECK (status IN ('IN PROGRESS', 'COMPLETED', 'DISCONTINUED'))
        );
        CREATE INDEX IF NOT EXISTS idx_mpps_status ON mpps(status);
        CREATE INDEX IF NOT EXISTS idx_mpps_station ON mpps(station_ae);
        CREATE INDEX IF NOT EXISTS idx_mpps_study ON mpps(study_uid);
        CREATE INDEX IF NOT EXISTS idx_mpps_date ON mpps(start_datetime);
        -- =====================================================================
        -- WORKLIST TABLE (Modality Worklist)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS worklist (
            worklist_pk         INTEGER PRIMARY KEY AUTOINCREMENT,
            step_id             TEXT NOT NULL,
            step_status         TEXT DEFAULT 'SCHEDULED',
            patient_id          TEXT NOT NULL,
            patient_name        TEXT,
            birth_date          TEXT,
            sex                 TEXT,
            accession_no        TEXT,
            requested_proc_id   TEXT,
            study_uid           TEXT,
            scheduled_datetime  TEXT NOT NULL,
            station_ae          TEXT,
            station_name        TEXT,
            modality            TEXT NOT NULL,
            procedure_desc      TEXT,
            protocol_code       TEXT,
            referring_phys      TEXT,
            referring_phys_id   TEXT,
            created_at          TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
            UNIQUE (step_id, accession_no)
        );
        CREATE INDEX IF NOT EXISTS idx_worklist_station ON worklist(station_ae);
        CREATE INDEX IF NOT EXISTS idx_worklist_modality ON worklist(modality);
        CREATE INDEX IF NOT EXISTS idx_worklist_scheduled ON worklist(scheduled_datetime);
        CREATE INDEX IF NOT EXISTS idx_worklist_patient ON worklist(patient_id);
        CREATE INDEX IF NOT EXISTS idx_worklist_accession ON worklist(accession_no);
        CREATE INDEX IF NOT EXISTS idx_worklist_status ON worklist(step_status);
        CREATE INDEX IF NOT EXISTS idx_worklist_station_date_mod
            ON worklist(station_ae, scheduled_datetime, modality);
        -- =====================================================================
        -- TRIGGERS FOR PARENT COUNT UPDATES
        -- =====================================================================
        CREATE TRIGGER IF NOT EXISTS trg_instances_insert
        AFTER INSERT ON instances
        BEGIN
            UPDATE series
            SET num_instances = num_instances + 1,
                updated_at = datetime('now')
            WHERE series_pk = NEW.series_pk;
            UPDATE studies
            SET num_instances = num_instances + 1,
                updated_at = datetime('now')
            WHERE study_pk = (SELECT study_pk FROM series WHERE series_pk = NEW.series_pk);
        END;
        CREATE TRIGGER IF NOT EXISTS trg_instances_delete
        AFTER DELETE ON instances
        BEGIN
            UPDATE series
            SET num_instances = num_instances - 1,
                updated_at = datetime('now')
            WHERE series_pk = OLD.series_pk;
            UPDATE studies
            SET num_instances = num_instances - 1,
                updated_at = datetime('now')
            WHERE study_pk = (SELECT study_pk FROM series WHERE series_pk = OLD.series_pk);
        END;
        CREATE TRIGGER IF NOT EXISTS trg_series_insert
        AFTER INSERT ON series
        BEGIN
            UPDATE studies
            SET num_series = num_series + 1,
                updated_at = datetime('now')
            WHERE study_pk = NEW.study_pk;
        END;
        CREATE TRIGGER IF NOT EXISTS trg_series_delete
        AFTER DELETE ON series
        BEGIN
            UPDATE studies
            SET num_series = num_series - 1,
                updated_at = datetime('now')
            WHERE study_pk = OLD.study_pk;
        END;
    )";
    auto result = execute_sql(db, sql);
    if (result.is_err()) {
        return result;
    }
    return record_migration(db, 1, "Initial schema creation");
}
Referenced by migration_runner().
migrate_v2()
auto kcenon::pacs::storage::migration_runner::migrate_v2 (sqlite3 * db) -> VoidResult nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 522 of file migration_runner.cpp.
{
    // V2: Add audit_log table for REST API audit endpoints
    const char* sql = R"(
        -- =====================================================================
        -- AUDIT_LOG TABLE (for REST API and HIPAA compliance)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS audit_log (
            audit_pk        INTEGER PRIMARY KEY AUTOINCREMENT,
            event_type      TEXT NOT NULL,
            outcome         TEXT DEFAULT 'SUCCESS',
            timestamp       TEXT NOT NULL DEFAULT (datetime('now')),
            user_id         TEXT,
            source_ae       TEXT,
            target_ae       TEXT,
            source_ip       TEXT,
            patient_id      TEXT,
            study_uid       TEXT,
            message         TEXT,
            details         TEXT,
            CHECK (outcome IN ('SUCCESS', 'FAILURE', 'WARNING'))
        );
        CREATE INDEX IF NOT EXISTS idx_audit_event_type ON audit_log(event_type);
        CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit_log(timestamp);
        CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_log(user_id);
        CREATE INDEX IF NOT EXISTS idx_audit_source_ae ON audit_log(source_ae);
        CREATE INDEX IF NOT EXISTS idx_audit_patient ON audit_log(patient_id);
        CREATE INDEX IF NOT EXISTS idx_audit_study ON audit_log(study_uid);
        CREATE INDEX IF NOT EXISTS idx_audit_outcome ON audit_log(outcome);
    )";
    auto result = execute_sql(db, sql);
    if (result.is_err()) {
        return result;
    }
    return record_migration(db, 2, "Add audit_log table");
}
Referenced by migration_runner().
migrate_v3()
auto kcenon::pacs::storage::migration_runner::migrate_v3 (sqlite3 * db) -> VoidResult nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 561 of file migration_runner.cpp.
{
    // V3: Add remote_nodes table for PACS client remote node management
    const char* sql = R"(
        -- =====================================================================
        -- REMOTE_NODES TABLE (for PACS client SCU operations)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS remote_nodes (
            pk                      INTEGER PRIMARY KEY AUTOINCREMENT,
            node_id                 TEXT NOT NULL UNIQUE,
            name                    TEXT,
            ae_title                TEXT NOT NULL,
            host                    TEXT NOT NULL,
            port                    INTEGER NOT NULL DEFAULT 104,
            supports_find           INTEGER NOT NULL DEFAULT 1,
            supports_move           INTEGER NOT NULL DEFAULT 1,
            supports_get            INTEGER NOT NULL DEFAULT 0,
            supports_store          INTEGER NOT NULL DEFAULT 1,
            supports_worklist       INTEGER NOT NULL DEFAULT 0,
            connection_timeout_sec  INTEGER NOT NULL DEFAULT 30,
            dimse_timeout_sec       INTEGER NOT NULL DEFAULT 60,
            max_associations        INTEGER NOT NULL DEFAULT 4,
            status                  TEXT NOT NULL DEFAULT 'unknown',
            last_verified           TEXT,
            last_error              TEXT,
            last_error_message      TEXT,
            created_at              TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at              TEXT NOT NULL DEFAULT (datetime('now')),
            CHECK (port > 0 AND port <= 65535),
            CHECK (status IN ('unknown', 'online', 'offline', 'error', 'verifying'))
        );
        CREATE INDEX IF NOT EXISTS idx_remote_nodes_ae_title ON remote_nodes(ae_title);
        CREATE INDEX IF NOT EXISTS idx_remote_nodes_host ON remote_nodes(host);
        CREATE INDEX IF NOT EXISTS idx_remote_nodes_status ON remote_nodes(status);
    )";
    auto result = execute_sql(db, sql);
    if (result.is_err()) {
        return result;
    }
    return record_migration(db, 3, "Add remote_nodes table for PACS client");
}
Referenced by migration_runner().
migrate_v4()
auto kcenon::pacs::storage::migration_runner::migrate_v4 (sqlite3 * db) -> VoidResult nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 605 of file migration_runner.cpp.
{
    // V4: Add jobs table for async DICOM operations
    const char* sql = R"(
        -- =====================================================================
        -- JOBS TABLE (for async DICOM operations - Job Manager)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS jobs (
            pk                          INTEGER PRIMARY KEY AUTOINCREMENT,
            job_id                      TEXT NOT NULL UNIQUE,
            type                        TEXT NOT NULL,
            status                      TEXT NOT NULL DEFAULT 'pending',
            priority                    INTEGER NOT NULL DEFAULT 1,
            source_node_id              TEXT,
            destination_node_id         TEXT,
            patient_id                  TEXT,
            study_uid                   TEXT,
            series_uid                  TEXT,
            sop_instance_uid            TEXT,
            instance_uids_json          TEXT DEFAULT '[]',
            total_items                 INTEGER DEFAULT 0,
            completed_items             INTEGER DEFAULT 0,
            failed_items                INTEGER DEFAULT 0,
            skipped_items               INTEGER DEFAULT 0,
            bytes_transferred           INTEGER DEFAULT 0,
            current_item                TEXT,
            current_item_description    TEXT,
            error_message               TEXT,
            error_details               TEXT,
            retry_count                 INTEGER DEFAULT 0,
            max_retries                 INTEGER DEFAULT 3,
            created_by                  TEXT,
            metadata_json               TEXT DEFAULT '{}',
            created_at                  TEXT NOT NULL DEFAULT (datetime('now')),
            queued_at                   TEXT,
            started_at                  TEXT,
            completed_at                TEXT,
            CHECK (type IN ('query', 'retrieve', 'store', 'export', 'import', 'prefetch', 'sync')),
            CHECK (status IN ('pending', 'queued', 'running', 'completed', 'failed', 'cancelled', 'paused')),
            CHECK (priority >= 0 AND priority <= 3)
        );
        CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status);
        CREATE INDEX IF NOT EXISTS idx_jobs_type ON jobs(type);
        CREATE INDEX IF NOT EXISTS idx_jobs_priority ON jobs(priority DESC);
        CREATE INDEX IF NOT EXISTS idx_jobs_created_at ON jobs(created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_jobs_source_node ON jobs(source_node_id);
        CREATE INDEX IF NOT EXISTS idx_jobs_destination_node ON jobs(destination_node_id);
        CREATE INDEX IF NOT EXISTS idx_jobs_study ON jobs(study_uid);
        CREATE INDEX IF NOT EXISTS idx_jobs_patient ON jobs(patient_id);
    )";
    auto result = execute_sql(db, sql);
    if (result.is_err()) {
        return result;
    }
    return record_migration(db, 4, "Add jobs table for async DICOM operations");
}
Referenced by migration_runner().
migrate_v5()
auto kcenon::pacs::storage::migration_runner::migrate_v5 (sqlite3 * db) -> VoidResult nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 664 of file migration_runner.cpp.
{
    // V5: Add routing_rules table for auto-forwarding
    const char* sql = R"(
        -- =====================================================================
        -- ROUTING_RULES TABLE (for auto-forwarding - Routing Manager)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS routing_rules (
            pk                  INTEGER PRIMARY KEY AUTOINCREMENT,
            rule_id             TEXT NOT NULL UNIQUE,
            name                TEXT NOT NULL,
            description         TEXT,
            enabled             INTEGER NOT NULL DEFAULT 1,
            priority            INTEGER NOT NULL DEFAULT 0,
            conditions_json     TEXT NOT NULL DEFAULT '[]',
            actions_json        TEXT NOT NULL DEFAULT '[]',
            schedule_cron       TEXT,
            effective_from      TEXT,
            effective_until     TEXT,
            triggered_count     INTEGER DEFAULT 0,
            success_count       INTEGER DEFAULT 0,
            failure_count       INTEGER DEFAULT 0,
            last_triggered      TEXT,
            created_at          TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at          TEXT NOT NULL DEFAULT (datetime('now'))
        );
        CREATE INDEX IF NOT EXISTS idx_routing_rules_enabled ON routing_rules(enabled);
        CREATE INDEX IF NOT EXISTS idx_routing_rules_priority ON routing_rules(priority DESC);
    )";
    auto result = execute_sql(db, sql);
    if (result.is_err()) {
        return result;
    }
    return record_migration(db, 5, "Add routing_rules table for auto-forwarding");
}
Referenced by migration_runner().
migrate_v6()
auto kcenon::pacs::storage::migration_runner::migrate_v6 (sqlite3 * db) -> VoidResult nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 702 of file migration_runner.cpp.
{
    // V6: Add sync tables for bidirectional synchronization
    const char* sql = R"(
        -- =====================================================================
        -- SYNC_CONFIGS TABLE (for Sync Manager)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS sync_configs (
            pk                      INTEGER PRIMARY KEY AUTOINCREMENT,
            config_id               TEXT NOT NULL UNIQUE,
            source_node_id          TEXT NOT NULL,
            name                    TEXT NOT NULL,
            enabled                 INTEGER NOT NULL DEFAULT 1,
            lookback_hours          INTEGER NOT NULL DEFAULT 24,
            modalities_json         TEXT DEFAULT '[]',
            patient_patterns_json   TEXT DEFAULT '[]',
            sync_direction          TEXT NOT NULL DEFAULT 'pull',
            delete_missing          INTEGER NOT NULL DEFAULT 0,
            overwrite_existing      INTEGER NOT NULL DEFAULT 0,
            sync_metadata_only      INTEGER NOT NULL DEFAULT 0,
            schedule_cron           TEXT,
            last_sync               TEXT,
            last_successful_sync    TEXT,
            total_syncs             INTEGER DEFAULT 0,
            studies_synced          INTEGER DEFAULT 0,
            created_at              TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at              TEXT NOT NULL DEFAULT (datetime('now')),
            CHECK (sync_direction IN ('pull', 'push', 'bidirectional'))
        );
        CREATE INDEX IF NOT EXISTS idx_sync_configs_enabled ON sync_configs(enabled);
        CREATE INDEX IF NOT EXISTS idx_sync_configs_source ON sync_configs(source_node_id);
        -- =====================================================================
        -- SYNC_CONFLICTS TABLE (for conflict tracking)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS sync_conflicts (
            pk                      INTEGER PRIMARY KEY AUTOINCREMENT,
            config_id               TEXT NOT NULL,
            study_uid               TEXT NOT NULL,
            patient_id              TEXT,
            conflict_type           TEXT NOT NULL,
            local_modified          TEXT,
            remote_modified         TEXT,
            local_instance_count    INTEGER DEFAULT 0,
            remote_instance_count   INTEGER DEFAULT 0,
            resolved                INTEGER NOT NULL DEFAULT 0,
            resolution              TEXT,
            detected_at             TEXT NOT NULL DEFAULT (datetime('now')),
            resolved_at             TEXT,
            UNIQUE (config_id, study_uid),
            CHECK (conflict_type IN ('missing_local', 'missing_remote', 'modified', 'count_mismatch')),
            CHECK (resolution IS NULL OR resolution IN ('prefer_local', 'prefer_remote', 'prefer_newer'))
        );
        CREATE INDEX IF NOT EXISTS idx_sync_conflicts_config ON sync_conflicts(config_id);
        CREATE INDEX IF NOT EXISTS idx_sync_conflicts_resolved ON sync_conflicts(resolved);
        CREATE INDEX IF NOT EXISTS idx_sync_conflicts_study ON sync_conflicts(study_uid);
        -- =====================================================================
        -- SYNC_HISTORY TABLE (for sync operation history)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS sync_history (
            pk                  INTEGER PRIMARY KEY AUTOINCREMENT,
            config_id           TEXT NOT NULL,
            job_id              TEXT NOT NULL,
            success             INTEGER NOT NULL DEFAULT 0,
            studies_checked     INTEGER DEFAULT 0,
            studies_synced      INTEGER DEFAULT 0,
            conflicts_found     INTEGER DEFAULT 0,
            errors_json         TEXT DEFAULT '[]',
            started_at          TEXT NOT NULL,
            completed_at        TEXT NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_sync_history_config ON sync_history(config_id);
        CREATE INDEX IF NOT EXISTS idx_sync_history_started ON sync_history(started_at DESC);
    )";
    auto result = execute_sql(db, sql);
    if (result.is_err()) {
        return result;
    }
    return record_migration(db, 6, "Add sync tables for bidirectional synchronization");
}
Referenced by migration_runner().
migrate_v7()
auto kcenon::pacs::storage::migration_runner::migrate_v7 (sqlite3 * db) -> VoidResult nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 788 of file migration_runner.cpp.
{
    // V7: Add annotation and measurement tables for viewer functionality
    const char* sql = R"(
        -- =====================================================================
        -- ANNOTATIONS TABLE (for image annotations)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS annotations (
            pk                  INTEGER PRIMARY KEY AUTOINCREMENT,
            annotation_id       TEXT NOT NULL UNIQUE,
            study_uid           TEXT NOT NULL,
            series_uid          TEXT,
            sop_instance_uid    TEXT,
            frame_number        INTEGER,
            user_id             TEXT NOT NULL,
            annotation_type     TEXT NOT NULL,
            geometry_json       TEXT NOT NULL,
            text                TEXT,
            style_json          TEXT,
            created_at          TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
            CHECK (annotation_type IN ('arrow', 'line', 'rectangle', 'ellipse', 'polygon', 'freehand', 'text', 'angle', 'roi'))
        );
        CREATE INDEX IF NOT EXISTS idx_annotations_study ON annotations(study_uid);
        CREATE INDEX IF NOT EXISTS idx_annotations_instance ON annotations(sop_instance_uid);
        CREATE INDEX IF NOT EXISTS idx_annotations_user ON annotations(user_id);
        -- =====================================================================
        -- MEASUREMENTS TABLE (for image measurements)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS measurements (
            pk                  INTEGER PRIMARY KEY AUTOINCREMENT,
            measurement_id      TEXT NOT NULL UNIQUE,
            sop_instance_uid    TEXT NOT NULL,
            frame_number        INTEGER,
            user_id             TEXT NOT NULL,
            measurement_type    TEXT NOT NULL,
            geometry_json       TEXT NOT NULL,
            value               REAL NOT NULL,
            unit                TEXT NOT NULL,
            label               TEXT,
            created_at          TEXT NOT NULL DEFAULT (datetime('now')),
            CHECK (measurement_type IN ('length', 'area', 'angle', 'hounsfield', 'suv', 'ellipse_area', 'polygon_area'))
        );
        CREATE INDEX IF NOT EXISTS idx_measurements_instance ON measurements(sop_instance_uid);
        CREATE INDEX IF NOT EXISTS idx_measurements_user ON measurements(user_id);
        -- =====================================================================
        -- KEY_IMAGES TABLE (for key image markers)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS key_images (
            pk                  INTEGER PRIMARY KEY AUTOINCREMENT,
            key_image_id        TEXT NOT NULL UNIQUE,
            study_uid           TEXT NOT NULL,
            sop_instance_uid    TEXT NOT NULL,
            frame_number        INTEGER,
            user_id             TEXT NOT NULL,
            reason              TEXT,
            document_title      TEXT,
            created_at          TEXT NOT NULL DEFAULT (datetime('now'))
        );
        CREATE INDEX IF NOT EXISTS idx_key_images_study ON key_images(study_uid);
        -- =====================================================================
        -- VIEWER_STATES TABLE (for saved viewer configurations)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS viewer_states (
            pk                  INTEGER PRIMARY KEY AUTOINCREMENT,
            state_id            TEXT NOT NULL UNIQUE,
            study_uid           TEXT NOT NULL,
            user_id             TEXT NOT NULL,
            state_json          TEXT NOT NULL,
            created_at          TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at          TEXT NOT NULL DEFAULT (datetime('now'))
        );
        CREATE INDEX IF NOT EXISTS idx_viewer_states_study ON viewer_states(study_uid);
        CREATE INDEX IF NOT EXISTS idx_viewer_states_user ON viewer_states(user_id);
        -- =====================================================================
        -- RECENT_STUDIES TABLE (for tracking user study access)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS recent_studies (
            pk                  INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id             TEXT NOT NULL,
            study_uid           TEXT NOT NULL,
            accessed_at         TEXT NOT NULL DEFAULT (datetime('now')),
            UNIQUE (user_id, study_uid)
        );
        CREATE INDEX IF NOT EXISTS idx_recent_studies_user ON recent_studies(user_id, accessed_at DESC);
    )";
    auto result = execute_sql(db, sql);
    if (result.is_err()) {
        return result;
    }
    return record_migration(db, 7, "Add annotation and measurement tables");
}
Referenced by migration_runner().
migrate_v8()
auto kcenon::pacs::storage::migration_runner::migrate_v8 (sqlite3 * db) -> VoidResult nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 891 of file migration_runner.cpp.
{
    // V8: Add Storage Commitment tracking tables
    const char* sql = R"(
        -- =====================================================================
        -- STORAGE_COMMITMENT TABLE (transaction-level tracking)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS storage_commitment (
            transaction_uid     TEXT PRIMARY KEY,
            requesting_ae       TEXT NOT NULL,
            request_time        TEXT NOT NULL,
            completion_time     TEXT,
            status              TEXT NOT NULL DEFAULT 'pending',
            total_instances     INTEGER NOT NULL DEFAULT 0,
            success_count       INTEGER NOT NULL DEFAULT 0,
            failure_count       INTEGER NOT NULL DEFAULT 0,
            CHECK (status IN ('pending', 'success', 'partial', 'failed'))
        );
        CREATE INDEX IF NOT EXISTS idx_commitment_status
            ON storage_commitment(status);
        CREATE INDEX IF NOT EXISTS idx_commitment_request_time
            ON storage_commitment(request_time);
        -- =====================================================================
        -- COMMITMENT_REFERENCES TABLE (per-instance tracking)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS commitment_references (
            transaction_uid     TEXT NOT NULL
                REFERENCES storage_commitment(transaction_uid)
                ON DELETE CASCADE,
            sop_class_uid       TEXT NOT NULL,
            sop_instance_uid    TEXT NOT NULL,
            status              TEXT NOT NULL DEFAULT 'pending',
            failure_reason      INTEGER,
            PRIMARY KEY (transaction_uid, sop_instance_uid),
            CHECK (status IN ('pending', 'success', 'failed'))
        );
        CREATE INDEX IF NOT EXISTS idx_commitment_ref_instance
            ON commitment_references(sop_instance_uid);
    )";
    auto result = execute_sql(db, sql);
    if (result.is_err()) {
        return result;
    }
    return record_migration(db, 8, "Add Storage Commitment tracking tables");
}
Referenced by migration_runner().
migrate_v9()
auto kcenon::pacs::storage::migration_runner::migrate_v9 (sqlite3 * db) -> VoidResult nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 941 of file migration_runner.cpp.
{
    // V9: Add Unified Procedure Step (UPS) tables
    const char* sql = R"(
        -- =====================================================================
        -- UPS WORKITEMS TABLE (Unified Procedure Step - PS3.4 Annex CC)
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS ups_workitems (
            workitem_pk                     INTEGER PRIMARY KEY AUTOINCREMENT,
            workitem_uid                    TEXT NOT NULL UNIQUE,
            state                           TEXT NOT NULL DEFAULT 'SCHEDULED',
            procedure_step_label            TEXT,
            worklist_label                  TEXT,
            priority                        TEXT DEFAULT 'MEDIUM',
            scheduled_start_datetime        TEXT,
            expected_completion_datetime    TEXT,
            scheduled_station_name          TEXT,
            scheduled_station_class         TEXT,
            scheduled_station_geographic    TEXT,
            scheduled_human_performers      TEXT,
            input_information               TEXT,
            performing_ae                   TEXT,
            progress_description            TEXT,
            progress_percent                INTEGER DEFAULT 0,
            output_information              TEXT,
            transaction_uid                 TEXT,
            created_at                      TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at                      TEXT NOT NULL DEFAULT (datetime('now')),
            CHECK (state IN ('SCHEDULED', 'IN PROGRESS', 'COMPLETED', 'CANCELED')),
            CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
        );
        CREATE INDEX IF NOT EXISTS idx_ups_state ON ups_workitems(state);
        CREATE INDEX IF NOT EXISTS idx_ups_priority ON ups_workitems(priority);
        CREATE INDEX IF NOT EXISTS idx_ups_performing ON ups_workitems(performing_ae);
        CREATE INDEX IF NOT EXISTS idx_ups_scheduled ON ups_workitems(scheduled_start_datetime);
        CREATE INDEX IF NOT EXISTS idx_ups_worklist ON ups_workitems(worklist_label);
        -- =====================================================================
        -- UPS SUBSCRIPTIONS TABLE
        -- =====================================================================
        CREATE TABLE IF NOT EXISTS ups_subscriptions (
            subscription_pk     INTEGER PRIMARY KEY AUTOINCREMENT,
            subscriber_ae       TEXT NOT NULL,
            workitem_uid        TEXT,
            deletion_lock       INTEGER DEFAULT 0,
            filter_criteria     TEXT,
            created_at          TEXT NOT NULL DEFAULT (datetime('now')),
            UNIQUE (subscriber_ae, workitem_uid)
        );
        CREATE INDEX IF NOT EXISTS idx_ups_sub_ae ON ups_subscriptions(subscriber_ae);
        CREATE INDEX IF NOT EXISTS idx_ups_sub_workitem ON ups_subscriptions(workitem_uid);
    )";
    auto result = execute_sql(db, sql);
    if (result.is_err()) {
        return result;
    }
    return record_migration(db, 9, "Add Unified Procedure Step (UPS) tables");
}
Referenced by migration_runner().
needs_migration()
auto kcenon::pacs::storage::migration_runner::needs_migration (sqlite3 * db) const -> bool nodiscard
Check if migration is needed.
Parameters
db The SQLite database handle
Returns
true if current version is less than LATEST_VERSION
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 177 of file migration_runner.cpp.
{
    return get_current_version(db) < LATEST_VERSION;
}
operator=() [1/2]
auto kcenon::pacs::storage::migration_runner::operator= (const migration_runner &) -> migration_runner &=delete delete
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
operator=() [2/2]
auto kcenon::pacs::storage::migration_runner::operator= (migration_runner &&) -> migration_runner &=delete delete
record_migration()
auto kcenon::pacs::storage::migration_runner::record_migration (sqlite3 * db, int version, std::string_view description) -> VoidResult nodiscard private
Record a migration in the schema_version table.
Parameters
db The SQLite database handle
version The version that was applied
description Description of the migration
Returns
VoidResult Success or error information
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 245 of file migration_runner.cpp.
                  {
    const char* sql =
        "INSERT INTO schema_version (version, description) VALUES (?, ?);";
    sqlite3_stmt* stmt = nullptr;
    auto rc = sqlite3_prepare_v2(db, sql, -1, &stmt, nullptr);
    if (rc != SQLITE_OK) {
        return make_error<std::monostate>(
            rc,
            kcenon::pacs::compat::format("Failed to prepare statement: {}",
                       sqlite3_errmsg(db)),
            "storage");
    }
    sqlite3_bind_int(stmt, 1, version);
    sqlite3_bind_text(stmt, 2, description.data(),
                      static_cast<int>(description.size()), SQLITE_TRANSIENT);
    rc = sqlite3_step(stmt);
    sqlite3_finalize(stmt);
    if (rc != SQLITE_DONE) {
        return make_error<std::monostate>(
            rc,
            kcenon::pacs::compat::format("Failed to record migration: {}",
                       sqlite3_errmsg(db)),
            "storage");
    }
    return ok();
}
run_migrations()
auto kcenon::pacs::storage::migration_runner::run_migrations (sqlite3 * db) -> VoidResult nodiscard
Run all pending migrations.
Executes all migrations from the current version up to LATEST_VERSION. Each migration is run within a transaction for atomicity.
Parameters
db The SQLite database handle
Returns
VoidResult Success or error information
Note
If any migration fails, the database will be rolled back to its state before that migration started.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 75 of file migration_runner.cpp.
{
    return run_migrations_to(db, LATEST_VERSION);
}
run_migrations_to()
auto kcenon::pacs::storage::migration_runner::run_migrations_to (sqlite3 * db, int target_version) -> VoidResult nodiscard
Run migrations up to a specific version.
Parameters
db The SQLite database handle
target_version The version to migrate to
Returns
VoidResult Success or error information
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 79 of file migration_runner.cpp.
                  {
    if (target_version > LATEST_VERSION) {
        return make_error<std::monostate>(
            -1,
            kcenon::pacs::compat::format("Target version {} exceeds latest version {}",
                       target_version, LATEST_VERSION),
            "storage");
    }
    // Ensure schema_version table exists
    auto ensure_result = ensure_schema_version_table(db);
    if (ensure_result.is_err()) {
        return ensure_result;
    }
    auto current_version = get_current_version(db);
    // Nothing to do if already at or past target
    if (current_version >= target_version) {
        return ok();
    }
    // Apply each migration in a transaction
    while (current_version < target_version) {
        auto next_version = current_version + 1;
        // Begin transaction
        auto begin_result = execute_sql(db, "BEGIN TRANSACTION;");
        if (begin_result.is_err()) {
            return begin_result;
        }
        // Apply migration
        auto migration_result = apply_migration(db, next_version);
        if (migration_result.is_err()) {
            // Rollback on failure
            (void)execute_sql(db, "ROLLBACK;");
            return migration_result;
        }
        // Commit transaction
        auto commit_result = execute_sql(db, "COMMIT;");
        if (commit_result.is_err()) {
            (void)execute_sql(db, "ROLLBACK;");
            return commit_result;
        }
        current_version = next_version;
    }
    return ok();
}
Member Data Documentation
LATEST_VERSION
int kcenon::pacs::storage::migration_runner::LATEST_VERSION = 9 static constexpr private
Latest schema version (increment when adding migrations)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 367 of file migration_runner.h.
Referenced by get_latest_version().
migrations_
std::vector<std::pair<int, migration_function> > kcenon::pacs::storage::migration_runner::migrations_ private
Migration function registry.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 370 of file migration_runner.h.
Referenced by migration_runner().
The documentation for this class was generated from the following files:
include/kcenon/pacs/storage/migration_runner.h
src/storage/migration_runner.cpp