PACS System: kcenon::pacs::integration_test::test_server Class Reference
kcenon::pacs::integration_test::test_server Class Reference
RAII wrapper for a test DICOM server.
#include <test_fixtures.h>
Public Member Functions
test_server (uint16_t port=0, const std::string &ae_title=test_scp_ae_title)
Construct and start a test server.
~test_server ()
test_server (const test_server &)=delete
test_server & operator= (const test_server &)=delete
test_server (test_server &&)=delete
test_server & operator= (test_server &&)=delete
template<typename Service >
void register_service (std::shared_ptr< Service > service)
Register a service provider.
bool start ()
Start the server and wait for it to be ready.
void stop ()
Stop the server.
uint16_t port () const noexcept
const std::string & ae_title () const noexcept
bool is_running () const noexcept
network::dicom_server & server ()
Static Private Member Functions
static bool check_port_listening (uint16_t port)
Check if a port is listening (inline implementation)
Private Attributes
uint16_t port_
std::string ae_title_
std::unique_ptr< network::dicom_server > server_
bool running_ {false}
Detailed Description
RAII wrapper for a test DICOM server.
Provides automatic server lifecycle management for tests. Server is started on construction and stopped on destruction.
Definition at line 530 of file test_fixtures.h.
Constructor & Destructor Documentation
test_server() [1/3]
kcenon::pacs::integration_test::test_server::test_server (uint16_t port = 0, const std::string & ae_title = test_scp_ae_title) inline explicit
Construct and start a test server.
Parameters
port Port to listen on (0 = auto-select)
ae_title AE title for server
Definition at line 537 of file test_fixtures.h.
        : port_(port == 0 ? find_available_port() : port)
        , ae_title_(ae_title) {
        network::server_config config;
        config.ae_title = ae_title_;
        config.port = port_;
        config.max_associations = 20;
        config.idle_timeout = std::chrono::seconds{60};
        config.implementation_class_uid = "1.2.826.0.1.3680043.9.9999.1";
        config.implementation_version_name = "TEST_SCP";
        server_ = std::make_unique<network::dicom_server>(config);
    }
References kcenon::pacs::network::server_config::ae_title, ae_title_, kcenon::pacs::network::server_config::idle_timeout, kcenon::pacs::network::server_config::implementation_class_uid, kcenon::pacs::network::server_config::implementation_version_name, kcenon::pacs::network::server_config::max_associations, kcenon::pacs::network::server_config::port, port_, and server_.
~test_server()
kcenon::pacs::integration_test::test_server::~test_server () inline
Definition at line 554 of file test_fixtures.h.
                   {
        stop();
    }
References stop().
test_server() [2/3]
kcenon::pacs::integration_test::test_server::test_server (const test_server &) delete
test_server() [3/3]
kcenon::pacs::integration_test::test_server::test_server (test_server &&) delete
Member Function Documentation
ae_title()
const std::string & kcenon::pacs::integration_test::test_server::ae_title () const inline nodiscard noexcept
Returns
Server AE title
Definition at line 625 of file test_fixtures.h.
{ return ae_title_; }
References ae_title_.
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
check_port_listening()
static bool kcenon::pacs::integration_test::test_server::check_port_listening (uint16_t port) inline static private
Check if a port is listening (inline implementation)
This is a simplified version for use within test_server::start() since process_launcher is defined later in this file.
Definition at line 640 of file test_fixtures.h.
{
        const long timeout_us = is_ci_environment() ? 1000000 : 200000;
#ifdef _WIN32
        WSADATA wsa_data;
        if (WSAStartup(MAKEWORD(2, 2), &wsa_data) != 0) return false;
        SOCKET sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
        if (sock == INVALID_SOCKET) { WSACleanup(); return false; }
        u_long mode = 1;
        ioctlsocket(sock, FIONBIO, &mode);
        sockaddr_in addr{};
        addr.sin_family = AF_INET;
        addr.sin_port = htons(port);
        addr.sin_addr.s_addr = inet_addr("127.0.0.1");
        connect(sock, reinterpret_cast<sockaddr*>(&addr), sizeof(addr));
        fd_set writefds;
        FD_ZERO(&writefds);
        FD_SET(sock, &writefds);
        timeval tv{};
        tv.tv_sec = static_cast<decltype(tv.tv_sec)>(timeout_us / 1000000);
        tv.tv_usec = static_cast<decltype(tv.tv_usec)>(timeout_us % 1000000);
        int result = select(0, nullptr, &writefds, nullptr, &tv);
        bool listening = false;
        if (result > 0) {
            int error = 0;
            int len = sizeof(error);
            getsockopt(sock, SOL_SOCKET, SO_ERROR, reinterpret_cast<char*>(&error), &len);
            listening = (error == 0);
        }
        closesocket(sock);
        WSACleanup();
        return listening;
#else
        int sock = socket(AF_INET, SOCK_STREAM, 0);
        if (sock < 0) return false;
        int flags = fcntl(sock, F_GETFL, 0);
        fcntl(sock, F_SETFL, flags | O_NONBLOCK);
        sockaddr_in addr{};
        addr.sin_family = AF_INET;
        addr.sin_port = htons(port);
        addr.sin_addr.s_addr = inet_addr("127.0.0.1");
        connect(sock, reinterpret_cast<sockaddr*>(&addr), sizeof(addr));
        fd_set writefds;
        FD_ZERO(&writefds);
        FD_SET(sock, &writefds);
        timeval tv{};
        tv.tv_sec = static_cast<decltype(tv.tv_sec)>(timeout_us / 1000000);
        tv.tv_usec = static_cast<decltype(tv.tv_usec)>(timeout_us % 1000000);
        int result = select(sock + 1, nullptr, &writefds, nullptr, &tv);
        bool listening = false;
        if (result > 0) {
            int error = 0;
            socklen_t len = sizeof(error);
            getsockopt(sock, SOL_SOCKET, SO_ERROR, &error, &len);
            listening = (error == 0);
        }
        close(sock);
        return listening;
#endif
    }
References kcenon::pacs::integration_test::is_ci_environment(), and port().
Referenced by start().
is_running()
bool kcenon::pacs::integration_test::test_server::is_running () const inline nodiscard noexcept
Returns
true if server is running
Definition at line 628 of file test_fixtures.h.
{ return running_; }
References running_.
Referenced by TEST_CASE().
operator=() [1/2]
test_server & kcenon::pacs::integration_test::test_server::operator= (const test_server &) delete
operator=() [2/2]
test_server & kcenon::pacs::integration_test::test_server::operator= (test_server &&) delete
port()
uint16_t kcenon::pacs::integration_test::test_server::port () const inline nodiscard noexcept
Returns
Server port
Definition at line 622 of file test_fixtures.h.
{ return port_; }
References port_.
Referenced by check_port_listening().
register_service()
template<typename Service > void kcenon::pacs::integration_test::test_server::register_service (std::shared_ptr< Service > service) inline
Register a service provider.
Parameters
service Service provider to register
Definition at line 569 of file test_fixtures.h.
{
        server_->register_service(std::move(service));
    }
References server_.
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
server()
network::dicom_server & kcenon::pacs::integration_test::test_server::server () inline nodiscard
Returns
Reference to underlying server
Definition at line 631 of file test_fixtures.h.
{ return *server_; }
References server_.
start()
bool kcenon::pacs::integration_test::test_server::start () inline nodiscard
Start the server and wait for it to be ready.
Returns
true if server started and is accepting connections
This method:
Starts the underlying DICOM server
Waits for the port to actually be listening (with adaptive timeout)
The port listening check ensures the server is truly ready to accept connections, which is critical for reliable tests in CI environments where process startup can be slower.
Definition at line 585 of file test_fixtures.h.
{
        auto result = server_->start();
        if (!result.is_ok()) {
            return false;
        }
        running_ = true;
        // Wait for port to actually be listening
        // This is more reliable than a fixed delay, especially in CI
        auto timeout = server_ready_timeout();
        auto start_time = std::chrono::steady_clock::now();
        while (std::chrono::steady_clock::now() - start_time < timeout) {
            if (check_port_listening(port_)) {
                return true;
            }
            std::this_thread::sleep_for(std::chrono::milliseconds{50});
        }
        // Timeout waiting for port - stop the server and return failure
        server_->stop();
        running_ = false;
        return false;
    }
References check_port_listening(), port_, running_, server_, and kcenon::pacs::integration_test::server_ready_timeout().
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
stop()
void kcenon::pacs::integration_test::test_server::stop () inline
Stop the server.
Definition at line 614 of file test_fixtures.h.
                {
        if (running_) {
            server_->stop();
            running_ = false;
        }
    }
References running_, and server_.
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and ~test_server().
Member Data Documentation
ae_title_
std::string kcenon::pacs::integration_test::test_server::ae_title_ private
Definition at line 715 of file test_fixtures.h.
Referenced by ae_title(), and test_server().
port_
uint16_t kcenon::pacs::integration_test::test_server::port_ private
Definition at line 714 of file test_fixtures.h.
Referenced by port(), start(), and test_server().
running_
bool kcenon::pacs::integration_test::test_server::running_ {false} private
Definition at line 717 of file test_fixtures.h.
{false};
Referenced by is_running(), start(), and stop().
server_
std::unique_ptr<network::dicom_server> kcenon::pacs::integration_test::test_server::server_ private
Definition at line 716 of file test_fixtures.h.
Referenced by register_service(), server(), start(), stop(), and test_server().
The documentation for this class was generated from the following file:
examples/integration_tests/test_fixtures.h