PACS System: kcenon::pacs::services::validation::rt_plan_iod_validator Class Reference
kcenon::pacs::services::validation::rt_plan_iod_validator Class Reference
Validator for RT Plan IODs.
#include <rt_iod_validator.h>
Public Member Functions
rt_plan_iod_validator ()=default
rt_plan_iod_validator (const rt_validation_options &options)
validation_result validate (const core::dicom_dataset &dataset) const
bool quick_check (const core::dicom_dataset &dataset) const
const rt_validation_options & options () const noexcept
void set_options (const rt_validation_options &options)
Private Member Functions
void validate_patient_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_study_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_rt_series_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_frame_of_reference_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_rt_general_plan_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_rt_fraction_scheme_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_rt_beams_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_sop_common_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_type1_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_type2_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
Private Attributes
rt_validation_options options_
Detailed Description
Validator for RT Plan IODs.
Validates DICOM datasets against the RT Plan IOD specification. Checks required modules, attributes, and RT Plan specific constraints.
Validated Modules
Mandatory Modules
Patient Module (M)
General Study Module (M)
RT Series Module (M)
Frame of Reference Module (M)
General Equipment Module (M)
RT General Plan Module (M)
RT Prescription Module (U)
RT Tolerance Tables Module (U)
RT Patient Setup Module (U)
RT Fraction Scheme Module (C)
RT Beams Module (C)
RT Brachy Application Setups Module (C)
Approval Module (U)
SOP Common Module (M)
Definition at line 100 of file rt_iod_validator.h.
Constructor & Destructor Documentation
rt_plan_iod_validator() [1/2]
kcenon::pacs::services::validation::rt_plan_iod_validator::rt_plan_iod_validator () default
rt_plan_iod_validator() [2/2]
kcenon::pacs::services::validation::rt_plan_iod_validator::rt_plan_iod_validator (const rt_validation_options & options) explicit
Definition at line 88 of file rt_iod_validator.cpp.
    : options_(options) {}
Member Function Documentation
check_type1_attribute()
void kcenon::pacs::services::validation::rt_plan_iod_validator::check_type1_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Definition at line 387 of file rt_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::error,
            tag,
            std::string("Type 1 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "RTPLAN-TYPE1-MISSING"
        });
    } else {
        auto value = dataset.get_string(tag);
        if (value.empty()) {
            findings.push_back({
                validation_severity::error,
                tag,
                std::string("Type 1 attribute has empty value: ") +
                std::string(name) + " (" + tag.to_string() + ")",
                "RTPLAN-TYPE1-EMPTY"
            });
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), name, and kcenon::pacs::core::dicom_tag::to_string().
Referenced by validate_frame_of_reference_module(), validate_general_study_module(), validate_rt_fraction_scheme_module(), validate_rt_general_plan_module(), validate_rt_series_module(), and validate_sop_common_module().
check_type2_attribute()
void kcenon::pacs::services::validation::rt_plan_iod_validator::check_type2_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Definition at line 415 of file rt_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::warning,
            tag,
            std::string("Type 2 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "RTPLAN-TYPE2-MISSING"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), name, kcenon::pacs::core::dicom_tag::to_string(), and kcenon::pacs::services::validation::warning.
Referenced by validate_frame_of_reference_module(), validate_general_study_module(), validate_patient_module(), validate_rt_general_plan_module(), and validate_rt_series_module().
options()
const rt_validation_options & kcenon::pacs::services::validation::rt_plan_iod_validator::options () const nodiscard noexcept
Definition at line 143 of file rt_iod_validator.cpp.
{
    return options_;
}
References options_.
Referenced by set_options().
quick_check()
bool kcenon::pacs::services::validation::rt_plan_iod_validator::quick_check (const core::dicom_dataset & dataset) const nodiscard
Definition at line 126 of file rt_iod_validator.cpp.
{
    // Check Type 1 required attributes
    if (!dataset.contains(tags::study_instance_uid)) return false;
    if (!dataset.contains(tags::series_instance_uid)) return false;
    if (!dataset.contains(tags::modality)) return false;
    auto modality = dataset.get_string(tags::modality);
    if (modality != "RTPLAN") return false;
    if (!dataset.contains(rt_tags::rt_plan_label)) return false;
    if (!dataset.contains(rt_tags::rt_plan_geometry)) return false;
    if (!dataset.contains(tags::sop_class_uid)) return false;
    if (!dataset.contains(tags::sop_instance_uid)) return false;
    return true;
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::modality, kcenon::pacs::services::validation::rt_tags::rt_plan_geometry, kcenon::pacs::services::validation::rt_tags::rt_plan_label, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, and kcenon::pacs::core::tags::study_instance_uid.
Referenced by kcenon::pacs::services::validation::is_valid_rt_plan_dataset().
set_options()
void kcenon::pacs::services::validation::rt_plan_iod_validator::set_options (const rt_validation_options & options)
Definition at line 147 of file rt_iod_validator.cpp.
{
    options_ = options;
}
References options(), and options_.
validate()
validation_result kcenon::pacs::services::validation::rt_plan_iod_validator::validate (const core::dicom_dataset & dataset) const nodiscard
Definition at line 91 of file rt_iod_validator.cpp.
{
    validation_result result;
    result.is_valid = true;
    // Validate mandatory modules
    if (options_.check_type1 || options_.check_type2) {
        validate_patient_module(dataset, result.findings);
        validate_general_study_module(dataset, result.findings);
        validate_rt_series_module(dataset, result.findings);
        validate_frame_of_reference_module(dataset, result.findings);
        validate_rt_general_plan_module(dataset, result.findings);
        validate_sop_common_module(dataset, result.findings);
    }
    // RT Plan specific validation
    if (options_.validate_rt_plan) {
        validate_rt_fraction_scheme_module(dataset, result.findings);
        validate_rt_beams_module(dataset, result.findings);
    }
    // Check for errors
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
        if (options_.strict_mode && finding.severity == validation_severity::warning) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, kcenon::pacs::services::validation::rt_validation_options::check_type2, kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::services::validation::validation_result::is_valid, options_, kcenon::pacs::services::validation::rt_validation_options::strict_mode, validate_frame_of_reference_module(), validate_general_study_module(), validate_patient_module(), validate_rt_beams_module(), validate_rt_fraction_scheme_module(), validate_rt_general_plan_module(), kcenon::pacs::services::validation::rt_validation_options::validate_rt_plan, validate_rt_series_module(), validate_sop_common_module(), and kcenon::pacs::services::validation::warning.
Referenced by kcenon::pacs::services::validation::rt_iod_validator::validate(), and kcenon::pacs::services::validation::validate_rt_plan_iod().
validate_frame_of_reference_module()
void kcenon::pacs::services::validation::rt_plan_iod_validator::validate_frame_of_reference_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 207 of file rt_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, rt_tags::frame_of_reference_uid,
                              "FrameOfReferenceUID", findings);
    }
    if (options_.check_type2) {
        check_type2_attribute(dataset, rt_tags::position_reference_indicator,
                              "PositionReferenceIndicator", findings);
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::rt_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::services::validation::rt_tags::frame_of_reference_uid, options_, and kcenon::pacs::services::validation::rt_tags::position_reference_indicator.
Referenced by validate().
validate_general_study_module()
void kcenon::pacs::services::validation::rt_plan_iod_validator::validate_general_study_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 163 of file rt_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::study_instance_uid, "StudyInstanceUID", findings);
    }
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::study_date, "StudyDate", findings);
        check_type2_attribute(dataset, tags::study_time, "StudyTime", findings);
        check_type2_attribute(dataset, tags::referring_physician_name, "ReferringPhysicianName", findings);
        check_type2_attribute(dataset, tags::study_id, "StudyID", findings);
        check_type2_attribute(dataset, tags::accession_number, "AccessionNumber", findings);
    }
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::rt_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::core::tags::study_time.
Referenced by validate().
validate_patient_module()
void kcenon::pacs::services::validation::rt_plan_iod_validator::validate_patient_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 151 of file rt_iod_validator.cpp.
{
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::patient_name, "PatientName", findings);
        check_type2_attribute(dataset, tags::patient_id, "PatientID", findings);
        check_type2_attribute(dataset, tags::patient_birth_date, "PatientBirthDate", findings);
        check_type2_attribute(dataset, tags::patient_sex, "PatientSex", findings);
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, and kcenon::pacs::core::tags::patient_sex.
Referenced by validate().
validate_rt_beams_module()
void kcenon::pacs::services::validation::rt_plan_iod_validator::validate_rt_beams_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 303 of file rt_iod_validator.cpp.
{
    // Beam Sequence is Type 1C (required if NumberOfBeams > 0)
    if (dataset.contains(rt_tags::number_of_beams)) {
        auto num_beams = dataset.get_numeric<int32_t>(rt_tags::number_of_beams);
        if (num_beams && *num_beams > 0) {
            if (!dataset.contains(rt_tags::beam_sequence)) {
                findings.push_back({
                    validation_severity::error,
                    rt_tags::beam_sequence,
                    "BeamSequence required when NumberOfBeams > 0",
                    "RTPLAN-ERR-002"
                });
            }
        }
    }
    // Validate beam details if sequence exists
    if (dataset.contains(rt_tags::beam_sequence)) {
        // Check for treatment machine name
        if (!dataset.contains(rt_tags::treatment_machine_name)) {
            findings.push_back({
                validation_severity::info,
                rt_tags::treatment_machine_name,
                "TreatmentMachineName not specified",
                "RTPLAN-INFO-002"
            });
        }
        // Validate Beam Type if present
        if (dataset.contains(rt_tags::beam_type)) {
            auto beam_type = dataset.get_string(rt_tags::beam_type);
            if (beam_type != "STATIC" && beam_type != "DYNAMIC") {
                findings.push_back({
                    validation_severity::warning,
                    rt_tags::beam_type,
                    "Non-standard BeamType: " + beam_type + " (expected STATIC or DYNAMIC)",
                    "RTPLAN-WARN-004"
                });
            }
        }
        // Validate Radiation Type if present
        if (dataset.contains(rt_tags::radiation_type)) {
            auto radiation_type = dataset.get_string(rt_tags::radiation_type);
            if (radiation_type != "PHOTON" && radiation_type != "ELECTRON" &&
                radiation_type != "NEUTRON" && radiation_type != "PROTON" &&
                radiation_type != "ION") {
                findings.push_back({
                    validation_severity::warning,
                    rt_tags::radiation_type,
                    "Non-standard RadiationType: " + radiation_type,
                    "RTPLAN-WARN-005"
                });
            }
        }
    }
}
References kcenon::pacs::services::validation::rt_tags::beam_sequence, kcenon::pacs::services::validation::rt_tags::beam_type, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_numeric(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::info, kcenon::pacs::services::validation::rt_tags::number_of_beams, kcenon::pacs::services::validation::rt_tags::radiation_type, kcenon::pacs::services::validation::rt_tags::treatment_machine_name, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_rt_fraction_scheme_module()
void kcenon::pacs::services::validation::rt_plan_iod_validator::validate_rt_fraction_scheme_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 279 of file rt_iod_validator.cpp.
{
    // Fraction Group Sequence is Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, rt_tags::fraction_group_sequence,
                              "FractionGroupSequence", findings);
    }
    // Validate fraction scheme details if sequence exists
    if (dataset.contains(rt_tags::fraction_group_sequence)) {
        // NumberOfFractionsPlanned should be present
        if (!dataset.contains(rt_tags::number_of_fractions_planned)) {
            findings.push_back({
                validation_severity::warning,
                rt_tags::number_of_fractions_planned,
                "NumberOfFractionsPlanned not specified in FractionGroupSequence",
                "RTPLAN-WARN-003"
            });
        }
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::rt_tags::fraction_group_sequence, kcenon::pacs::services::validation::rt_tags::number_of_fractions_planned, options_, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_rt_general_plan_module()
void kcenon::pacs::services::validation::rt_plan_iod_validator::validate_rt_general_plan_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 222 of file rt_iod_validator.cpp.
{
    // Type 1 attributes
    if (options_.check_type1) {
        check_type1_attribute(dataset, rt_tags::rt_plan_label, "RTPlanLabel", findings);
        check_type1_attribute(dataset, rt_tags::rt_plan_geometry, "RTPlanGeometry", findings);
    }
    // Validate RTPlanGeometry value
    if (dataset.contains(rt_tags::rt_plan_geometry)) {
        auto geometry = dataset.get_string(rt_tags::rt_plan_geometry);
        if (geometry != "PATIENT" && geometry != "TREATMENT_DEVICE") {
            findings.push_back({
                validation_severity::warning,
                rt_tags::rt_plan_geometry,
                "Invalid RTPlanGeometry: " + geometry + " (expected PATIENT or TREATMENT_DEVICE)",
                "RTPLAN-WARN-001"
            });
        }
    }
    // Type 2 attributes
    if (options_.check_type2) {
        check_type2_attribute(dataset, rt_tags::rt_plan_date, "RTPlanDate", findings);
        check_type2_attribute(dataset, rt_tags::rt_plan_time, "RTPlanTime", findings);
    }
    // Type 3 but important: Plan Intent
    if (dataset.contains(rt_tags::plan_intent)) {
        auto intent = dataset.get_string(rt_tags::plan_intent);
        if (intent != "CURATIVE" && intent != "PALLIATIVE" && intent != "PROPHYLACTIC" &&
            intent != "VERIFICATION" && intent != "MACHINE_QA" && intent != "RESEARCH" &&
            intent != "SERVICE") {
            findings.push_back({
                validation_severity::info,
                rt_tags::plan_intent,
                "Non-standard PlanIntent: " + intent,
                "RTPLAN-INFO-001"
            });
        }
    }
    // Referenced Structure Set Sequence is important
    if (options_.validate_references) {
        if (!dataset.contains(rt_tags::referenced_structure_set_sequence)) {
            findings.push_back({
                validation_severity::warning,
                rt_tags::referenced_structure_set_sequence,
                "ReferencedStructureSetSequence not present - plan has no associated structures",
                "RTPLAN-WARN-002"
            });
        }
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::rt_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::info, options_, kcenon::pacs::services::validation::rt_tags::plan_intent, kcenon::pacs::services::validation::rt_tags::referenced_structure_set_sequence, kcenon::pacs::services::validation::rt_tags::rt_plan_date, kcenon::pacs::services::validation::rt_tags::rt_plan_geometry, kcenon::pacs::services::validation::rt_tags::rt_plan_label, kcenon::pacs::services::validation::rt_tags::rt_plan_time, kcenon::pacs::services::validation::rt_validation_options::validate_references, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_rt_series_module()
void kcenon::pacs::services::validation::rt_plan_iod_validator::validate_rt_series_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 180 of file rt_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::modality, "Modality", findings);
        check_type1_attribute(dataset, tags::series_instance_uid, "SeriesInstanceUID", findings);
        // Validate Modality is RTPLAN
        if (dataset.contains(tags::modality)) {
            auto modality = dataset.get_string(tags::modality);
            if (modality != "RTPLAN") {
                findings.push_back({
                    validation_severity::error,
                    tags::modality,
                    "Modality must be 'RTPLAN' for RT Plan, found: " + modality,
                    "RTPLAN-ERR-001"
                });
            }
        }
    }
    if (options_.check_type2) {
        check_type2_attribute(dataset, rt_tags::series_number, "SeriesNumber", findings);
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::rt_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::modality, options_, kcenon::pacs::core::tags::series_instance_uid, and kcenon::pacs::services::validation::rt_tags::series_number.
Referenced by validate().
validate_sop_common_module()
void kcenon::pacs::services::validation::rt_plan_iod_validator::validate_sop_common_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 364 of file rt_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::sop_class_uid, "SOPClassUID", findings);
        check_type1_attribute(dataset, tags::sop_instance_uid, "SOPInstanceUID", findings);
    }
    // Validate SOP Class UID is RT Plan
    if (dataset.contains(tags::sop_class_uid)) {
        auto sop_class = dataset.get_string(tags::sop_class_uid);
        if (!sop_classes::is_rt_plan_sop_class(sop_class)) {
            findings.push_back({
                validation_severity::error,
                tags::sop_class_uid,
                "SOPClassUID is not an RT Plan SOP Class: " + sop_class,
                "RTPLAN-ERR-003"
            });
        }
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_rt_plan_sop_class(), options_, kcenon::pacs::core::tags::sop_class_uid, and kcenon::pacs::core::tags::sop_instance_uid.
Referenced by validate().
Member Data Documentation
options_
rt_validation_options kcenon::pacs::services::validation::rt_plan_iod_validator::options_ private
Definition at line 156 of file rt_iod_validator.h.
Referenced by options(), set_options(), validate(), validate_frame_of_reference_module(), validate_general_study_module(), validate_patient_module(), validate_rt_fraction_scheme_module(), validate_rt_general_plan_module(), validate_rt_series_module(), and validate_sop_common_module().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/validation/rt_iod_validator.h
src/services/validation/rt_iod_validator.cpp