PACS System: kcenon::pacs::services::validation::pet_iod_validator Class Reference
kcenon::pacs::services::validation::pet_iod_validator Class Reference
#include <pet_iod_validator.h>
Public Member Functions
pet_iod_validator ()=default
Construct validator with default options.
pet_iod_validator (const pet_validation_options &options)
Construct validator with custom options.
validation_result validate (const core::dicom_dataset &dataset) const
Validate a DICOM dataset against PET IOD.
bool quick_check (const core::dicom_dataset &dataset) const
Quick check if dataset has minimum required attributes.
const pet_validation_options & options () const noexcept
Get the validation options.
void set_options (const pet_validation_options &options)
Set validation options.
Private Member Functions
void validate_patient_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_study_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_series_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_pet_series_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_frame_of_reference_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_pet_image_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_image_pixel_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_image_plane_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_sop_common_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_radiopharmaceutical_info (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_suv_parameters (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_reconstruction_info (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_corrections (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_type1_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_type2_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_modality (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_pixel_data_consistency (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
Private Attributes
pet_validation_options options_
Detailed Description
Definition at line 112 of file pet_iod_validator.h.
Constructor & Destructor Documentation
pet_iod_validator() [1/2]
kcenon::pacs::services::validation::pet_iod_validator::pet_iod_validator () default
Construct validator with default options.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
pet_iod_validator() [2/2]
kcenon::pacs::services::validation::pet_iod_validator::pet_iod_validator (const pet_validation_options & options) explicit
Construct validator with custom options.
Parameters
options Validation options
Definition at line 61 of file pet_iod_validator.cpp.
    : options_(options) {}
Member Function Documentation
check_modality()
void kcenon::pacs::services::validation::pet_iod_validator::check_modality (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 550 of file pet_iod_validator.cpp.
{
    if (!dataset.contains(tags::modality)) {
        return;  // Already reported as Type 1 missing
    }
    auto modality = dataset.get_string(tags::modality);
    if (modality != "PT") {
        findings.push_back({
            validation_severity::error,
            tags::modality,
            "Modality must be 'PT' for PET images, found: " + modality,
            "PT-ERR-003"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), and kcenon::pacs::core::tags::modality.
Referenced by validate_general_series_module().
check_pixel_data_consistency()
void kcenon::pacs::services::validation::pet_iod_validator::check_pixel_data_consistency (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 569 of file pet_iod_validator.cpp.
{
    // Check BitsStored <= BitsAllocated
    auto bits_allocated = dataset.get_numeric<uint16_t>(tags::bits_allocated);
    auto bits_stored = dataset.get_numeric<uint16_t>(tags::bits_stored);
    auto high_bit = dataset.get_numeric<uint16_t>(tags::high_bit);
    if (bits_allocated && bits_stored) {
        if (*bits_stored > *bits_allocated) {
            findings.push_back({
                validation_severity::error,
                tags::bits_stored,
                "BitsStored (" + std::to_string(*bits_stored) +
                ") exceeds BitsAllocated (" + std::to_string(*bits_allocated) + ")",
                "PT-ERR-004"
            });
        }
    }
    // Check HighBit == BitsStored - 1
    if (bits_stored && high_bit) {
        if (*high_bit != *bits_stored - 1) {
            findings.push_back({
                validation_severity::warning,
                tags::high_bit,
                "HighBit (" + std::to_string(*high_bit) +
                ") should typically be BitsStored - 1 (" +
                std::to_string(*bits_stored - 1) + ")",
                "PT-WARN-005"
            });
        }
    }
    // Check photometric interpretation is valid for PET
    if (dataset.contains(tags::photometric_interpretation)) {
        auto photometric = dataset.get_string(tags::photometric_interpretation);
        if (!sop_classes::is_valid_pet_photometric(photometric)) {
            findings.push_back({
                validation_severity::warning,
                tags::photometric_interpretation,
                "Unusual photometric interpretation for PET: " + photometric +
                " (expected MONOCHROME2)",
                "PT-WARN-006"
            });
        }
    }
    // PET images should be grayscale (SamplesPerPixel = 1)
    auto samples = dataset.get_numeric<uint16_t>(tags::samples_per_pixel);
    if (samples && *samples != 1) {
        findings.push_back({
            validation_severity::warning,
            tags::samples_per_pixel,
            "PET images should have SamplesPerPixel = 1, found: " +
            std::to_string(*samples),
            "PT-WARN-007"
        });
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_numeric(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::services::sop_classes::is_valid_pet_photometric(), kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::samples_per_pixel, and kcenon::pacs::services::validation::warning.
Referenced by validate_image_pixel_module().
check_type1_attribute()
void kcenon::pacs::services::validation::pet_iod_validator::check_type1_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 503 of file pet_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::error,
            tag,
            std::string("Type 1 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "PT-TYPE1-MISSING"
        });
    } else {
        // Type 1 must have a value (cannot be empty)
        auto value = dataset.get_string(tag);
        if (value.empty()) {
            findings.push_back({
                validation_severity::error,
                tag,
                std::string("Type 1 attribute has empty value: ") +
                std::string(name) + " (" + tag.to_string() + ")",
                "PT-TYPE1-EMPTY"
            });
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), name, and kcenon::pacs::core::dicom_tag::to_string().
Referenced by validate_frame_of_reference_module(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_image_plane_module(), validate_pet_image_module(), validate_pet_series_module(), and validate_sop_common_module().
check_type2_attribute()
void kcenon::pacs::services::validation::pet_iod_validator::check_type2_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 532 of file pet_iod_validator.cpp.
{
    // Type 2 must be present but can be empty
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::warning,
            tag,
            std::string("Type 2 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "PT-TYPE2-MISSING"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), name, kcenon::pacs::core::dicom_tag::to_string(), and kcenon::pacs::services::validation::warning.
Referenced by validate_frame_of_reference_module(), validate_general_series_module(), validate_general_study_module(), validate_image_plane_module(), validate_patient_module(), and validate_radiopharmaceutical_info().
options()
const pet_validation_options & kcenon::pacs::services::validation::pet_iod_validator::options () const nodiscard noexcept
Get the validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 146 of file pet_iod_validator.cpp.
{
    return options_;
}
References options_.
Referenced by set_options().
quick_check()
bool kcenon::pacs::services::validation::pet_iod_validator::quick_check (const core::dicom_dataset & dataset) const nodiscard
Quick check if dataset has minimum required attributes.
Faster than full validation - only checks Type 1 attributes.
Parameters
dataset The dataset to check
Returns
true if all Type 1 attributes are present
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 111 of file pet_iod_validator.cpp.
{
    // Check only Type 1 required attributes for quick validation
    // General Study Module Type 1
    if (!dataset.contains(tags::study_instance_uid)) return false;
    // General Series Module Type 1
    if (!dataset.contains(tags::modality)) return false;
    if (!dataset.contains(tags::series_instance_uid)) return false;
    // Check modality is PT
    auto modality = dataset.get_string(tags::modality);
    if (modality != "PT") return false;
    // Frame of Reference Module Type 1
    if (!dataset.contains(pet_tags::frame_of_reference_uid)) return false;
    // Image Pixel Module Type 1
    if (!dataset.contains(tags::samples_per_pixel)) return false;
    if (!dataset.contains(tags::photometric_interpretation)) return false;
    if (!dataset.contains(tags::rows)) return false;
    if (!dataset.contains(tags::columns)) return false;
    if (!dataset.contains(tags::bits_allocated)) return false;
    if (!dataset.contains(tags::bits_stored)) return false;
    if (!dataset.contains(tags::high_bit)) return false;
    if (!dataset.contains(tags::pixel_representation)) return false;
    if (!dataset.contains(tags::pixel_data)) return false;
    // SOP Common Module Type 1
    if (!dataset.contains(tags::sop_class_uid)) return false;
    if (!dataset.contains(tags::sop_instance_uid)) return false;
    return true;
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::tags::columns, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::pet_tags::frame_of_reference_uid, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, and kcenon::pacs::core::tags::study_instance_uid.
Referenced by kcenon::pacs::services::validation::is_valid_pet_dataset().
set_options()
void kcenon::pacs::services::validation::pet_iod_validator::set_options (const pet_validation_options & options)
Set validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 150 of file pet_iod_validator.cpp.
{
    options_ = options;
}
References options(), and options_.
validate()
validation_result kcenon::pacs::services::validation::pet_iod_validator::validate (const core::dicom_dataset & dataset) const nodiscard
Validate a DICOM dataset against PET IOD.
Parameters
dataset The dataset to validate
Returns
Validation result with all findings
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 64 of file pet_iod_validator.cpp.
{
    validation_result result;
    result.is_valid = true;
    // Validate mandatory modules
    if (options_.check_type1 || options_.check_type2) {
        validate_patient_module(dataset, result.findings);
        validate_general_study_module(dataset, result.findings);
        validate_general_series_module(dataset, result.findings);
        validate_pet_series_module(dataset, result.findings);
        validate_frame_of_reference_module(dataset, result.findings);
        validate_pet_image_module(dataset, result.findings);
        validate_sop_common_module(dataset, result.findings);
    }
    if (options_.validate_pixel_data) {
        validate_image_pixel_module(dataset, result.findings);
        validate_image_plane_module(dataset, result.findings);
    }
    // PET-specific validation
    if (options_.validate_pet_specific) {
        if (options_.validate_radiopharmaceutical) {
            validate_radiopharmaceutical_info(dataset, result.findings);
        }
        validate_suv_parameters(dataset, result.findings);
        validate_reconstruction_info(dataset, result.findings);
        if (options_.validate_corrections) {
            validate_corrections(dataset, result.findings);
        }
    }
    // Check for errors
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
        if (options_.strict_mode && finding.severity == validation_severity::warning) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References kcenon::pacs::services::validation::pet_validation_options::check_type1, kcenon::pacs::services::validation::pet_validation_options::check_type2, kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::services::validation::validation_result::is_valid, options_, kcenon::pacs::services::validation::pet_validation_options::strict_mode, validate_corrections(), kcenon::pacs::services::validation::pet_validation_options::validate_corrections, validate_frame_of_reference_module(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_image_plane_module(), validate_patient_module(), validate_pet_image_module(), validate_pet_series_module(), kcenon::pacs::services::validation::pet_validation_options::validate_pet_specific, kcenon::pacs::services::validation::pet_validation_options::validate_pixel_data, kcenon::pacs::services::validation::pet_validation_options::validate_radiopharmaceutical, validate_radiopharmaceutical_info(), validate_reconstruction_info(), validate_sop_common_module(), validate_suv_parameters(), and kcenon::pacs::services::validation::warning.
Referenced by kcenon::pacs::services::validation::validate_pet_iod().
validate_corrections()
void kcenon::pacs::services::validation::pet_iod_validator::validate_corrections (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 468 of file pet_iod_validator.cpp.
{
    // Attenuation Correction Method is Type 3 but important
    if (!dataset.contains(pet_tags::attenuation_correction_method)) {
        findings.push_back({
            validation_severity::info,
            pet_tags::attenuation_correction_method,
            "AttenuationCorrectionMethod not specified",
            "PT-INFO-005"
        });
    }
    // For quantitative PET, corrections are critical
    if (dataset.contains(pet_tags::units)) {
        auto units = dataset.get_string(pet_tags::units);
        if (units == "BQML" || units == "GML") {
            // Randoms correction
            if (!dataset.contains(pet_tags::randoms_correction_method)) {
                findings.push_back({
                    validation_severity::info,
                    pet_tags::randoms_correction_method,
                    "RandomsCorrectionMethod recommended for quantitative PET",
                    "PT-INFO-006"
                });
            }
        }
    }
}
References kcenon::pacs::services::validation::pet_tags::attenuation_correction_method, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::info, kcenon::pacs::services::validation::pet_tags::randoms_correction_method, and kcenon::pacs::services::validation::pet_tags::units.
Referenced by validate().
validate_frame_of_reference_module()
void kcenon::pacs::services::validation::pet_iod_validator::validate_frame_of_reference_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 250 of file pet_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, pet_tags::frame_of_reference_uid,
                              "FrameOfReferenceUID", findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, pet_tags::position_reference_indicator,
                              "PositionReferenceIndicator", findings);
    }
}
References kcenon::pacs::services::validation::pet_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::pet_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::services::validation::pet_tags::frame_of_reference_uid, options_, and kcenon::pacs::services::validation::pet_tags::position_reference_indicator.
Referenced by validate().
validate_general_series_module()
void kcenon::pacs::services::validation::pet_iod_validator::validate_general_series_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 190 of file pet_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::modality, "Modality", findings);
        check_type1_attribute(dataset, tags::series_instance_uid, "SeriesInstanceUID", findings);
        // Special check: Modality must be "PT"
        check_modality(dataset, findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::series_number, "SeriesNumber", findings);
    }
}
References check_modality(), kcenon::pacs::services::validation::pet_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::pet_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::tags::modality, options_, kcenon::pacs::core::tags::series_instance_uid, and kcenon::pacs::core::tags::series_number.
Referenced by validate().
validate_general_study_module()
void kcenon::pacs::services::validation::pet_iod_validator::validate_general_study_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 171 of file pet_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::study_instance_uid, "StudyInstanceUID", findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::study_date, "StudyDate", findings);
        check_type2_attribute(dataset, tags::study_time, "StudyTime", findings);
        check_type2_attribute(dataset, tags::referring_physician_name, "ReferringPhysicianName", findings);
        check_type2_attribute(dataset, tags::study_id, "StudyID", findings);
        check_type2_attribute(dataset, tags::accession_number, "AccessionNumber", findings);
    }
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::services::validation::pet_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::pet_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::core::tags::study_time.
Referenced by validate().
validate_image_pixel_module()
void kcenon::pacs::services::validation::pet_iod_validator::validate_image_pixel_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 310 of file pet_iod_validator.cpp.
{
    // Type 1 attributes
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::samples_per_pixel, "SamplesPerPixel", findings);
        check_type1_attribute(dataset, tags::photometric_interpretation,
                              "PhotometricInterpretation", findings);
        check_type1_attribute(dataset, tags::rows, "Rows", findings);
        check_type1_attribute(dataset, tags::columns, "Columns", findings);
        check_type1_attribute(dataset, tags::bits_allocated, "BitsAllocated", findings);
        check_type1_attribute(dataset, tags::bits_stored, "BitsStored", findings);
        check_type1_attribute(dataset, tags::high_bit, "HighBit", findings);
        check_type1_attribute(dataset, tags::pixel_representation, "PixelRepresentation", findings);
        check_type1_attribute(dataset, tags::pixel_data, "PixelData", findings);
    }
    // Validate pixel data consistency
    if (options_.validate_pixel_data) {
        check_pixel_data_consistency(dataset, findings);
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, check_pixel_data_consistency(), kcenon::pacs::services::validation::pet_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::tags::columns, kcenon::pacs::core::tags::high_bit, options_, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, and kcenon::pacs::services::validation::pet_validation_options::validate_pixel_data.
Referenced by validate().
validate_image_plane_module()
void kcenon::pacs::services::validation::pet_iod_validator::validate_image_plane_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 334 of file pet_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, pet_tags::pixel_spacing, "PixelSpacing", findings);
        check_type1_attribute(dataset, pet_tags::image_orientation_patient,
                              "ImageOrientationPatient", findings);
        check_type1_attribute(dataset, pet_tags::image_position_patient,
                              "ImagePositionPatient", findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, pet_tags::slice_thickness, "SliceThickness", findings);
    }
}
References kcenon::pacs::services::validation::pet_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::pet_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::services::validation::pet_tags::image_orientation_patient, kcenon::pacs::services::validation::pet_tags::image_position_patient, options_, kcenon::pacs::services::validation::pet_tags::pixel_spacing, and kcenon::pacs::services::validation::pet_tags::slice_thickness.
Referenced by validate().
validate_patient_module()
void kcenon::pacs::services::validation::pet_iod_validator::validate_patient_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 158 of file pet_iod_validator.cpp.
{
    // Patient Module - All attributes are Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::patient_name, "PatientName", findings);
        check_type2_attribute(dataset, tags::patient_id, "PatientID", findings);
        check_type2_attribute(dataset, tags::patient_birth_date, "PatientBirthDate", findings);
        check_type2_attribute(dataset, tags::patient_sex, "PatientSex", findings);
    }
}
References kcenon::pacs::services::validation::pet_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, and kcenon::pacs::core::tags::patient_sex.
Referenced by validate().
validate_pet_image_module()
void kcenon::pacs::services::validation::pet_iod_validator::validate_pet_image_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 267 of file pet_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, pet_tags::image_type, "ImageType", findings);
        check_type1_attribute(dataset, pet_tags::frame_reference_time,
                              "FrameReferenceTime", findings);
    }
    // Type 1C - Decay Correction (required if Units = BQML)
    if (options_.check_conditional) {
        if (dataset.contains(pet_tags::units)) {
            auto units = dataset.get_string(pet_tags::units);
            if (units == "BQML") {
                if (!dataset.contains(pet_tags::decay_correction)) {
                    findings.push_back({
                        validation_severity::error,
                        pet_tags::decay_correction,
                        "DecayCorrection is required when Units = BQML",
                        "PT-ERR-001"
                    });
                }
            }
        }
    }
    // Validate DecayCorrection value
    if (dataset.contains(pet_tags::decay_correction)) {
        auto decay = dataset.get_string(pet_tags::decay_correction);
        if (decay != "NONE" && decay != "START" && decay != "ADMIN") {
            findings.push_back({
                validation_severity::warning,
                pet_tags::decay_correction,
                "Invalid DecayCorrection value: " + decay +
                " (expected NONE, START, or ADMIN)",
                "PT-WARN-002"
            });
        }
    }
}
References kcenon::pacs::services::validation::pet_validation_options::check_conditional, kcenon::pacs::services::validation::pet_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::pet_tags::decay_correction, kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::pet_tags::frame_reference_time, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::pet_tags::image_type, options_, kcenon::pacs::services::validation::pet_tags::units, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_pet_series_module()
void kcenon::pacs::services::validation::pet_iod_validator::validate_pet_series_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 209 of file pet_iod_validator.cpp.
{
    // PET Series Module Type 1 attributes
    if (options_.check_type1) {
        check_type1_attribute(dataset, pet_tags::series_type, "SeriesType", findings);
        check_type1_attribute(dataset, pet_tags::units, "Units", findings);
        check_type1_attribute(dataset, pet_tags::counts_source, "CountsSource", findings);
    }
    // Validate Units value
    if (dataset.contains(pet_tags::units)) {
        auto units = dataset.get_string(pet_tags::units);
        if (units != "CNTS" && units != "BQML" && units != "GML" &&
            units != "PROPCNTS" && units != "NONE") {
            findings.push_back({
                validation_severity::warning,
                pet_tags::units,
                "Unusual Units value for PET: " + units +
                " (expected CNTS, BQML, or GML)",
                "PT-WARN-001"
            });
        }
    }
    // Validate SeriesType
    if (dataset.contains(pet_tags::series_type)) {
        auto series_type = dataset.get_string(pet_tags::series_type);
        // SeriesType should be like "STATIC\IMAGE" or "WHOLE BODY\IMAGE"
        if (series_type.find('\\') == std::string::npos) {
            findings.push_back({
                validation_severity::info,
                pet_tags::series_type,
                "SeriesType should contain backslash separator (e.g., STATIC\\IMAGE)",
                "PT-INFO-001"
            });
        }
    }
}
References kcenon::pacs::services::validation::pet_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::pet_tags::counts_source, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::info, options_, kcenon::pacs::services::validation::pet_tags::series_type, kcenon::pacs::services::validation::pet_tags::units, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_radiopharmaceutical_info()
void kcenon::pacs::services::validation::pet_iod_validator::validate_radiopharmaceutical_info (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 381 of file pet_iod_validator.cpp.
{
    // Radiopharmaceutical Information Sequence is Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, pet_tags::radiopharmaceutical_info_sequence,
                              "RadiopharmaceuticalInformationSequence", findings);
    }
    // If sequence is present, validate its contents
    if (dataset.contains(pet_tags::radiopharmaceutical_info_sequence)) {
        // For quantitative PET (BQML), dose and half-life are critical
        if (dataset.contains(pet_tags::units)) {
            auto units = dataset.get_string(pet_tags::units);
            if (units == "BQML" || units == "GML") {
                // Check for required dose information
                if (!dataset.contains(pet_tags::radionuclide_total_dose)) {
                    findings.push_back({
                        validation_severity::warning,
                        pet_tags::radionuclide_total_dose,
                        "RadionuclideTotalDose recommended for quantitative PET",
                        "PT-WARN-003"
                    });
                }
                if (!dataset.contains(pet_tags::radionuclide_half_life)) {
                    findings.push_back({
                        validation_severity::warning,
                        pet_tags::radionuclide_half_life,
                        "RadionuclideHalfLife recommended for quantitative PET",
                        "PT-WARN-004"
                    });
                }
            }
        }
    }
}
References kcenon::pacs::services::validation::pet_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), options_, kcenon::pacs::services::validation::pet_tags::radionuclide_half_life, kcenon::pacs::services::validation::pet_tags::radionuclide_total_dose, kcenon::pacs::services::validation::pet_tags::radiopharmaceutical_info_sequence, kcenon::pacs::services::validation::pet_tags::units, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_reconstruction_info()
void kcenon::pacs::services::validation::pet_iod_validator::validate_reconstruction_info (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 453 of file pet_iod_validator.cpp.
{
    // Reconstruction Method is informational but important for interpretation
    if (!dataset.contains(pet_tags::reconstruction_method)) {
        findings.push_back({
            validation_severity::info,
            pet_tags::reconstruction_method,
            "ReconstructionMethod not specified - helps with interpretation",
            "PT-INFO-004"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::info, and kcenon::pacs::services::validation::pet_tags::reconstruction_method.
Referenced by validate().
validate_sop_common_module()
void kcenon::pacs::services::validation::pet_iod_validator::validate_sop_common_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 353 of file pet_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::sop_class_uid, "SOPClassUID", findings);
        check_type1_attribute(dataset, tags::sop_instance_uid, "SOPInstanceUID", findings);
    }
    // Validate SOP Class UID is a PET storage class
    if (dataset.contains(tags::sop_class_uid)) {
        auto sop_class = dataset.get_string(tags::sop_class_uid);
        if (!sop_classes::is_pet_storage_sop_class(sop_class)) {
            findings.push_back({
                validation_severity::error,
                tags::sop_class_uid,
                "SOPClassUID is not a recognized PET Storage SOP Class: " + sop_class,
                "PT-ERR-002"
            });
        }
    }
}
References kcenon::pacs::services::validation::pet_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_pet_storage_sop_class(), options_, kcenon::pacs::core::tags::sop_class_uid, and kcenon::pacs::core::tags::sop_instance_uid.
Referenced by validate().
validate_suv_parameters()
void kcenon::pacs::services::validation::pet_iod_validator::validate_suv_parameters (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 419 of file pet_iod_validator.cpp.
{
    // SUV calculation requires specific parameters
    if (dataset.contains(pet_tags::units)) {
        auto units = dataset.get_string(pet_tags::units);
        // For SUV calculation, rescale parameters are important
        if (units == "BQML" || units == "GML") {
            if (!dataset.contains(pet_tags::rescale_slope)) {
                findings.push_back({
                    validation_severity::info,
                    pet_tags::rescale_slope,
                    "RescaleSlope recommended for accurate SUV calculation",
                    "PT-INFO-002"
                });
            }
        }
        // Decay factor for quantitative analysis
        if (units == "BQML") {
            if (!dataset.contains(pet_tags::decay_factor)) {
                findings.push_back({
                    validation_severity::info,
                    pet_tags::decay_factor,
                    "DecayFactor recommended for quantitative analysis",
                    "PT-INFO-003"
                });
            }
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::pet_tags::decay_factor, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::info, kcenon::pacs::services::validation::pet_tags::rescale_slope, and kcenon::pacs::services::validation::pet_tags::units.
Referenced by validate().
Member Data Documentation
options_
pet_validation_options kcenon::pacs::services::validation::pet_iod_validator::options_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 229 of file pet_iod_validator.h.
Referenced by options(), set_options(), validate(), validate_frame_of_reference_module(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_image_plane_module(), validate_patient_module(), validate_pet_image_module(), validate_pet_series_module(), validate_radiopharmaceutical_info(), and validate_sop_common_module().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/validation/pet_iod_validator.h
src/services/validation/pet_iod_validator.cpp