PACS System: kcenon::pacs::integration_test::background_process_guard Class Reference
kcenon::pacs::integration_test::background_process_guard Class Reference
RAII wrapper for a background process.
#include <test_fixtures.h>
Public Member Functions
background_process_guard (process_launcher::pid_type pid=process_launcher::invalid_pid)
~background_process_guard ()
background_process_guard (const background_process_guard &)=delete
background_process_guard & operator= (const background_process_guard &)=delete
background_process_guard (background_process_guard &&other) noexcept
background_process_guard & operator= (background_process_guard &&other) noexcept
void set_pid (process_launcher::pid_type pid)
Set the process ID.
process_launcher::pid_type pid () const noexcept
bool is_running () const
Check if process is running.
void stop ()
Stop the process.
process_launcher::pid_type release ()
Release ownership without stopping.
Private Attributes
process_launcher::pid_type pid_ {process_launcher::invalid_pid}
Detailed Description
RAII wrapper for a background process.
Automatically stops the process when the guard goes out of scope.
Definition at line 1448 of file test_fixtures.h.
Constructor & Destructor Documentation
background_process_guard() [1/3]
kcenon::pacs::integration_test::background_process_guard::background_process_guard (process_launcher::pid_type pid = process_launcher::invalid_pid) inline explicit
Definition at line 1450 of file test_fixtures.h.
        : pid_(pid) {}
~background_process_guard()
kcenon::pacs::integration_test::background_process_guard::~background_process_guard () inline
Definition at line 1454 of file test_fixtures.h.
{
        stop();
    }
References stop().
background_process_guard() [2/3]
kcenon::pacs::integration_test::background_process_guard::background_process_guard (const background_process_guard &) delete
background_process_guard() [3/3]
kcenon::pacs::integration_test::background_process_guard::background_process_guard (background_process_guard && other) inline noexcept
Definition at line 1463 of file test_fixtures.h.
        : pid_(other.pid_) {
        other.pid_ = process_launcher::invalid_pid;
    }
References kcenon::pacs::integration_test::process_launcher::invalid_pid.
Member Function Documentation
is_running()
bool kcenon::pacs::integration_test::background_process_guard::is_running () const inline nodiscard
Check if process is running.
Definition at line 1484 of file test_fixtures.h.
{
        return pid_ > 0 && process_launcher::is_running(pid_);
    }
References kcenon::pacs::integration_test::process_launcher::is_running(), and pid_.
Referenced by kcenon::pacs::integration_test::dcmtk_server_guard::is_running(), and TEST_CASE().
operator=() [1/2]
background_process_guard & kcenon::pacs::integration_test::background_process_guard::operator= (background_process_guard && other) inline noexcept
Definition at line 1468 of file test_fixtures.h.
{
        if (this != &other) {
            stop();
            pid_ = other.pid_;
            other.pid_ = process_launcher::invalid_pid;
        }
        return *this;
    }
References kcenon::pacs::integration_test::process_launcher::invalid_pid, pid_, and stop().
operator=() [2/2]
background_process_guard & kcenon::pacs::integration_test::background_process_guard::operator= (const background_process_guard &) delete
pid()
process_launcher::pid_type kcenon::pacs::integration_test::background_process_guard::pid () const inline nodiscard noexcept
Returns
Process ID
Definition at line 1481 of file test_fixtures.h.
{ return pid_; }
References pid_.
Referenced by kcenon::pacs::integration_test::dcmtk_server_guard::pid(), and set_pid().
release()
process_launcher::pid_type kcenon::pacs::integration_test::background_process_guard::release () inline
Release ownership without stopping.
Definition at line 1497 of file test_fixtures.h.
{
        auto p = pid_;
        pid_ = process_launcher::invalid_pid;
        return p;
    }
References kcenon::pacs::integration_test::process_launcher::invalid_pid, and pid_.
set_pid()
void kcenon::pacs::integration_test::background_process_guard::set_pid (process_launcher::pid_type pid) inline
Set the process ID.
Definition at line 1478 of file test_fixtures.h.
{ pid_ = pid; }
References pid(), and pid_.
Referenced by kcenon::pacs::integration_test::dcmtk_server_guard::dcmtk_server_guard().
stop()
void kcenon::pacs::integration_test::background_process_guard::stop () inline
Stop the process.
Definition at line 1489 of file test_fixtures.h.
                {
        if (pid_ > 0) {
            process_launcher::stop_background(pid_);
            pid_ = process_launcher::invalid_pid;
        }
    }
References kcenon::pacs::integration_test::process_launcher::invalid_pid, pid_, and kcenon::pacs::integration_test::process_launcher::stop_background().
Referenced by kcenon::pacs::integration_test::dcmtk_tool::echoscp(), operator=(), kcenon::pacs::integration_test::dcmtk_server_guard::stop(), kcenon::pacs::integration_test::dcmtk_tool::storescp(), TEST_CASE(), and ~background_process_guard().
Member Data Documentation
pid_
process_launcher::pid_type kcenon::pacs::integration_test::background_process_guard::pid_ {process_launcher::invalid_pid} private
Definition at line 1504 of file test_fixtures.h.
{process_launcher::invalid_pid};
Referenced by is_running(), operator=(), pid(), release(), set_pid(), and stop().
The documentation for this class was generated from the following file:
examples/integration_tests/test_fixtures.h