PACS System: kcenon::pacs::services::storage_commitment_scu Class Reference
kcenon::pacs::services::storage_commitment_scu Class Reference
Storage Commitment Push Model SCU.
#include <storage_commitment_scu.h>
Public Types
using commitment_callback
Callback type for commitment results.
Public Member Functions
storage_commitment_scu (std::shared_ptr< di::ILogger > logger=nullptr)
~storage_commitment_scu ()=default
void set_commitment_callback (commitment_callback cb)
Set callback for commitment result notifications.
network::Result< std::monostate > request_commitment (network::association &assoc, uint8_t context_id, const std::string &transaction_uid, const std::vector< sop_reference > &references)
Send N-ACTION request to commit stored instances.
network::Result< commitment_result > handle_event_report (const network::dimse::dimse_message &event_rq)
Handle an N-EVENT-REPORT-RQ received from the SCP.
size_t requests_sent () const noexcept
size_t event_reports_received () const noexcept
void reset_statistics () noexcept
Static Private Member Functions
static core::dicom_dataset build_action_dataset (const std::string &transaction_uid, const std::vector< sop_reference > &references)
static commitment_result parse_event_report_dataset (const core::dicom_dataset &dataset)
Private Attributes
std::shared_ptr< di::ILogger > logger_
commitment_callback callback_
std::atomic< size_t > requests_sent_ {0}
std::atomic< size_t > event_reports_received_ {0}
Detailed Description
Storage Commitment Push Model SCU.
Sends N-ACTION requests to an SCP to request storage commitment for specified SOP Instances, and handles N-EVENT-REPORT responses with per-instance verification results.
Usage
storage_commitment_scu scu;
// Set callback for commitment results
scu.set_commitment_callback([](const auto& uid, const auto& result) {
    // Handle commitment result
});
// Request commitment
auto result = scu.request_commitment(assoc, transaction_uid, references);
Definition at line 57 of file storage_commitment_scu.h.
Member Typedef Documentation
commitment_callback
using kcenon::pacs::services::storage_commitment_scu::commitment_callback
Initial value:
 std::function<void(
        const std::string& transaction_uid,
        const commitment_result& result)>
Callback type for commitment results.
Invoked when an N-EVENT-REPORT is received with the commitment result.
Definition at line 73 of file storage_commitment_scu.h.
Constructor & Destructor Documentation
storage_commitment_scu()
kcenon::pacs::services::storage_commitment_scu::storage_commitment_scu (std::shared_ptr< di::ILogger > logger = nullptr) explicit
Definition at line 23 of file storage_commitment_scu.cpp.
    : logger_(logger ? std::move(logger) : di::null_logger()) {}
~storage_commitment_scu()
kcenon::pacs::services::storage_commitment_scu::~storage_commitment_scu () default
Member Function Documentation
build_action_dataset()
core::dicom_dataset kcenon::pacs::services::storage_commitment_scu::build_action_dataset (const std::string & transaction_uid, const std::vector< sop_reference > & references) static nodiscard private
Definition at line 134 of file storage_commitment_scu.cpp.
{
    core::dicom_dataset ds;
    // Transaction UID (0008,1195)
    ds.set_string(core::tags::transaction_uid, encoding::vr_type::UI,
                  transaction_uid);
    // Referenced SOP Sequence (0008,1199)
    auto& seq = ds.get_or_create_sequence(core::tags::referenced_sop_sequence);
    for (const auto& ref : references) {
        core::dicom_dataset item;
        item.set_string(core::tags::referenced_sop_class_uid,
                        encoding::vr_type::UI, ref.sop_class_uid);
        item.set_string(core::tags::referenced_sop_instance_uid,
                        encoding::vr_type::UI, ref.sop_instance_uid);
        seq.push_back(std::move(item));
    }
    return ds;
}
References kcenon::pacs::core::dicom_dataset::get_or_create_sequence(), kcenon::pacs::core::tags::referenced_sop_class_uid, kcenon::pacs::core::tags::referenced_sop_instance_uid, kcenon::pacs::core::tags::referenced_sop_sequence, kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::core::tags::transaction_uid, and kcenon::pacs::encoding::UI.
Referenced by request_commitment().
event_reports_received()
size_t kcenon::pacs::services::storage_commitment_scu::event_reports_received () const nodiscard noexcept
Definition at line 121 of file storage_commitment_scu.cpp.
{
    return event_reports_received_.load();
}
References event_reports_received_.
handle_event_report()
network::Result< commitment_result > kcenon::pacs::services::storage_commitment_scu::handle_event_report (const network::dimse::dimse_message & event_rq) nodiscard
Handle an N-EVENT-REPORT-RQ received from the SCP.
Parses the event dataset to extract per-instance commitment status and invokes the registered callback.
Parameters
event_rq The N-EVENT-REPORT-RQ message
Returns
The parsed commitment result
Definition at line 78 of file storage_commitment_scu.cpp.
{
    using namespace network::dimse;
    // Verify command is N-EVENT-REPORT-RQ
    if (event_rq.command() != command_field::n_event_report_rq) {
        return kcenon::pacs::pacs_error<commitment_result>(
            kcenon::pacs::error_codes::storage_commitment_unexpected_command,
            "Expected N-EVENT-REPORT-RQ, got: " +
            std::string(to_string(event_rq.command())));
    }
    // Verify dataset is present
    if (!event_rq.has_dataset()) {
        return kcenon::pacs::pacs_error<commitment_result>(
            kcenon::pacs::error_codes::storage_commitment_missing_sequence,
            "N-EVENT-REPORT-RQ has no dataset");
    }
    const auto& dataset = event_rq.dataset().value().get();
    // Parse the event report dataset
    auto result = parse_event_report_dataset(dataset);
    ++event_reports_received_;
    // Invoke callback if registered
    if (callback_) {
        callback_(result.transaction_uid, result);
    }
    return kcenon::pacs::Result<commitment_result>::ok(std::move(result));
}
References callback_, kcenon::pacs::network::dimse::dimse_message::command(), kcenon::pacs::network::dimse::dimse_message::dataset(), event_reports_received_, kcenon::pacs::network::dimse::dimse_message::has_dataset(), kcenon::pacs::pacs_error(), parse_event_report_dataset(), kcenon::pacs::error_codes::storage_commitment_missing_sequence, kcenon::pacs::error_codes::storage_commitment_unexpected_command, and kcenon::pacs::services::to_string().
parse_event_report_dataset()
commitment_result kcenon::pacs::services::storage_commitment_scu::parse_event_report_dataset (const core::dicom_dataset & dataset) static nodiscard private
Definition at line 159 of file storage_commitment_scu.cpp.
{
    commitment_result result;
    // Extract Transaction UID (0008,1195)
    result.transaction_uid = dataset.get_string(core::tags::transaction_uid);
    result.timestamp = std::chrono::system_clock::now();
    // Parse Referenced SOP Sequence (0008,1199) — successful instances
    if (const auto* success_seq =
            dataset.get_sequence(core::tags::referenced_sop_sequence)) {
        for (const auto& item : *success_seq) {
            sop_reference ref;
            ref.sop_class_uid = item.get_string(
                core::tags::referenced_sop_class_uid);
            ref.sop_instance_uid = item.get_string(
                core::tags::referenced_sop_instance_uid);
            if (!ref.sop_class_uid.empty() && !ref.sop_instance_uid.empty()) {
                result.success_references.push_back(std::move(ref));
            }
        }
    }
    // Parse Failed SOP Sequence (0008,1198) — failed instances
    if (const auto* failed_seq =
            dataset.get_sequence(core::tags::failed_sop_sequence)) {
        for (const auto& item : *failed_seq) {
            sop_reference ref;
            ref.sop_class_uid = item.get_string(
                core::tags::referenced_sop_class_uid);
            ref.sop_instance_uid = item.get_string(
                core::tags::referenced_sop_instance_uid);
            auto reason = commitment_failure_reason::processing_failure;
            auto reason_val = item.get_numeric<uint16_t>(
                core::tags::failure_reason);
            if (reason_val.has_value()) {
                reason = static_cast<commitment_failure_reason>(
                    reason_val.value());
            }
            if (!ref.sop_class_uid.empty() && !ref.sop_instance_uid.empty()) {
                result.failed_references.emplace_back(std::move(ref), reason);
            }
        }
    }
    return result;
}
References kcenon::pacs::services::commitment_result::failed_references, kcenon::pacs::core::tags::failed_sop_sequence, kcenon::pacs::core::tags::failure_reason, kcenon::pacs::core::dicom_dataset::get_sequence(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::processing_failure, kcenon::pacs::core::tags::referenced_sop_class_uid, kcenon::pacs::core::tags::referenced_sop_instance_uid, kcenon::pacs::core::tags::referenced_sop_sequence, kcenon::pacs::services::sop_reference::sop_class_uid, kcenon::pacs::services::sop_reference::sop_instance_uid, kcenon::pacs::services::commitment_result::success_references, kcenon::pacs::services::commitment_result::timestamp, kcenon::pacs::core::tags::transaction_uid, and kcenon::pacs::services::commitment_result::transaction_uid.
Referenced by handle_event_report().
request_commitment()
network::Result< std::monostate > kcenon::pacs::services::storage_commitment_scu::request_commitment (network::association & assoc, uint8_t context_id, const std::string & transaction_uid, const std::vector< sop_reference > & references) nodiscard
Send N-ACTION request to commit stored instances.
Builds and sends an N-ACTION-RQ with the specified Transaction UID and Referenced SOP Sequence to the connected SCP.
Parameters
assoc The established association with the SCP
context_id The presentation context ID for Storage Commitment
transaction_uid Unique identifier for this commitment request
references SOP Instance references to commit
Returns
Success or error
Definition at line 39 of file storage_commitment_scu.cpp.
{
    using namespace network::dimse;
    if (transaction_uid.empty() || references.empty()) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::storage_commitment_missing_transaction_uid,
            "Transaction UID and references must not be empty");
    }
    // Build N-ACTION-RQ
    auto action_rq = make_n_action_rq(
        1,  // message_id
        storage_commitment_push_model_sop_class_uid,
        storage_commitment_push_model_sop_instance_uid,
        storage_commitment_action_type_request);
    // Build and attach action dataset
    auto action_dataset = build_action_dataset(transaction_uid, references);
    action_rq.set_dataset(std::move(action_dataset));
    // Send N-ACTION-RQ
    auto send_result = assoc.send_dimse(context_id, action_rq);
    if (send_result.is_err()) {
        return send_result;
    }
    ++requests_sent_;
    return kcenon::pacs::ok();
}
References build_action_dataset(), kcenon::pacs::pacs_void_error(), requests_sent_, kcenon::pacs::network::association::send_dimse(), kcenon::pacs::services::storage_commitment_action_type_request, kcenon::pacs::error_codes::storage_commitment_missing_transaction_uid, kcenon::pacs::services::storage_commitment_push_model_sop_class_uid, and kcenon::pacs::services::storage_commitment_push_model_sop_instance_uid.
requests_sent()
size_t kcenon::pacs::services::storage_commitment_scu::requests_sent () const nodiscard noexcept
Definition at line 117 of file storage_commitment_scu.cpp.
{
    return requests_sent_.load();
}
References requests_sent_.
reset_statistics()
void kcenon::pacs::services::storage_commitment_scu::reset_statistics () noexcept
Definition at line 125 of file storage_commitment_scu.cpp.
{
    requests_sent_ = 0;
    event_reports_received_ = 0;
}
References event_reports_received_, and requests_sent_.
set_commitment_callback()
void kcenon::pacs::services::storage_commitment_scu::set_commitment_callback (commitment_callback cb)
Set callback for commitment result notifications.
Parameters
cb The callback function
Definition at line 31 of file storage_commitment_scu.cpp.
{
    callback_ = std::move(cb);
}
References callback_.
Member Data Documentation
callback_
commitment_callback kcenon::pacs::services::storage_commitment_scu::callback_ private
Definition at line 146 of file storage_commitment_scu.h.
Referenced by handle_event_report(), and set_commitment_callback().
event_reports_received_
std::atomic<size_t> kcenon::pacs::services::storage_commitment_scu::event_reports_received_ {0} private
Definition at line 149 of file storage_commitment_scu.h.
{0};
Referenced by event_reports_received(), handle_event_report(), and reset_statistics().
logger_
std::shared_ptr<di::ILogger> kcenon::pacs::services::storage_commitment_scu::logger_ private
Definition at line 145 of file storage_commitment_scu.h.
requests_sent_
std::atomic<size_t> kcenon::pacs::services::storage_commitment_scu::requests_sent_ {0} private
Definition at line 148 of file storage_commitment_scu.h.
{0};
Referenced by request_commitment(), requests_sent(), and reset_statistics().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/storage_commitment_scu.h
src/services/storage_commitment_scu.cpp