PACS System: kcenon::pacs::web::rest_server Class Reference
kcenon::pacs::web::rest_server Class Reference
REST API server for PACS administration and monitoring.
#include <rest_server.h>
Classes
struct impl
Implementation details for rest_server.
Public Member Functions
rest_server ()
Construct REST server with default configuration.
rest_server (const rest_server_config &config)
Construct REST server with custom configuration.
~rest_server ()
Destructor - stops server if running.
rest_server (const rest_server &)=delete
Non-copyable.
rest_server & operator= (const rest_server &)=delete
rest_server (rest_server &&other) noexcept
Movable.
rest_server & operator= (rest_server &&other) noexcept
const rest_server_config & config () const noexcept
Get current configuration.
void set_config (const rest_server_config &config)
Update configuration (requires restart to apply)
void set_health_checker (std::shared_ptr< monitoring::health_checker > checker)
Set health checker for /api/v1/system/status endpoint.
void set_metrics_provider (std::shared_ptr< monitoring::pacs_metrics > metrics)
Set metrics provider for /api/v1/system/metrics endpoint.
void set_access_control_manager (std::shared_ptr< security::access_control_manager > manager)
Set access control manager for security.
void set_database (std::shared_ptr< storage::index_database > database)
Set index database for patient/study/series endpoints.
void set_file_storage (std::shared_ptr< storage::file_storage > storage)
Set file storage for DICOM instance persistence (STOW-RS)
void set_node_manager (std::shared_ptr< client::remote_node_manager > manager)
Set remote node manager for remote PACS node management.
void set_job_manager (std::shared_ptr< client::job_manager > manager)
Set job manager for async DICOM operations.
void set_routing_manager (std::shared_ptr< client::routing_manager > manager)
Set routing manager for auto-forwarding rules.
void set_dicom_server (std::shared_ptr< network::dicom_server > server)
Set DICOM server for live association management.
void set_oauth2_middleware (std::shared_ptr< auth::oauth2_middleware > middleware)
Set OAuth 2.0 middleware for DICOMweb endpoint authorization.
void start ()
Start the server (blocking)
void start_async ()
Start the server (non-blocking)
void stop ()
Stop the server.
bool is_running () const noexcept
Check if server is currently running.
void wait ()
Wait for server to stop.
std::uint16_t port () const noexcept
Get the actual port the server is listening on.
Private Attributes
std::unique_ptr< impl > impl_
Detailed Description
REST API server for PACS administration and monitoring.
The rest_server class provides a REST API for:
System health status and metrics
Configuration management
Future: Patient/Study browsing, Worklist management
Example
#include <kcenon/pacs/web/rest_server.h>
rest_server_config config;
config.port = 8080;
config.concurrency = 4;
rest_server server(config);
server.set_health_checker(health_checker_instance);
server.set_metrics_provider(metrics_instance);
server.start_async();  // Non-blocking
// ... do other work ...
server.stop();
Definition at line 85 of file rest_server.h.
Constructor & Destructor Documentation
rest_server() [1/4]
kcenon::pacs::web::rest_server::rest_server ()
Construct REST server with default configuration.
Definition at line 120 of file rest_server.cpp.
: impl_(std::make_unique<impl>()) {}
rest_server() [2/4]
kcenon::pacs::web::rest_server::rest_server (const rest_server_config & config) explicit
Construct REST server with custom configuration.
Parameters
config Server configuration
Definition at line 122 of file rest_server.cpp.
    : impl_(std::make_unique<impl>(config)) {}
~rest_server()
kcenon::pacs::web::rest_server::~rest_server ()
Destructor - stops server if running.
Definition at line 125 of file rest_server.cpp.
{ stop(); }
References stop().
rest_server() [3/4]
kcenon::pacs::web::rest_server::rest_server (const rest_server &) delete
Non-copyable.
rest_server() [4/4]
kcenon::pacs::web::rest_server::rest_server (rest_server && other) default noexcept
Movable.
Member Function Documentation
config()
const rest_server_config & kcenon::pacs::web::rest_server::config () const nodiscard noexcept
Get current configuration.
Returns
Current server configuration
Definition at line 130 of file rest_server.cpp.
{
  return impl_->config;
}
References kcenon::pacs::web::rest_server::impl::config, and impl_.
Referenced by set_config().
is_running()
bool kcenon::pacs::web::rest_server::is_running () const nodiscard noexcept
Check if server is currently running.
Returns
true if server is running
Definition at line 317 of file rest_server.cpp.
{ return impl_->running; }
References impl_, and kcenon::pacs::web::rest_server::impl::running.
operator=() [1/2]
rest_server & kcenon::pacs::web::rest_server::operator= (const rest_server &) delete
operator=() [2/2]
rest_server & kcenon::pacs::web::rest_server::operator= (rest_server && other) default noexcept
port()
std::uint16_t kcenon::pacs::web::rest_server::port () const nodiscard noexcept
Get the actual port the server is listening on.
Returns
Port number, or 0 if not running
Definition at line 325 of file rest_server.cpp.
{
  return impl_->running ? impl_->config.port : 0;
}
References kcenon::pacs::web::rest_server::impl::config, impl_, kcenon::pacs::web::rest_server_config::port, and kcenon::pacs::web::rest_server::impl::running.
set_access_control_manager()
void kcenon::pacs::web::rest_server::set_access_control_manager (std::shared_ptr< security::access_control_manager > manager)
Set access control manager for security.
Parameters
manager Access control manager instance
Definition at line 152 of file rest_server.cpp.
{
  std::lock_guard<std::mutex> lock(impl_->mutex);
  impl_->context->security_manager = std::move(manager);
}
References kcenon::pacs::web::rest_server::impl::context, impl_, and kcenon::pacs::web::rest_server::impl::mutex.
set_config()
void kcenon::pacs::web::rest_server::set_config (const rest_server_config & config)
Update configuration (requires restart to apply)
Parameters
config New configuration
Definition at line 134 of file rest_server.cpp.
{
  std::lock_guard<std::mutex> lock(impl_->mutex);
  impl_->config = config;
  impl_->context->config = &impl_->config;
}
References config(), kcenon::pacs::web::rest_server::impl::config, kcenon::pacs::web::rest_server::impl::context, impl_, and kcenon::pacs::web::rest_server::impl::mutex.
set_database()
void kcenon::pacs::web::rest_server::set_database (std::shared_ptr< storage::index_database > database)
Set index database for patient/study/series endpoints.
Parameters
database Index database instance
Definition at line 158 of file rest_server.cpp.
{
  std::lock_guard<std::mutex> lock(impl_->mutex);
  impl_->context->database = std::move(database);
}
References kcenon::pacs::web::rest_server::impl::context, impl_, and kcenon::pacs::web::rest_server::impl::mutex.
set_dicom_server()
void kcenon::pacs::web::rest_server::set_dicom_server (std::shared_ptr< network::dicom_server > server)
Set DICOM server for live association management.
Parameters
server DICOM server instance
Definition at line 188 of file rest_server.cpp.
{
  std::lock_guard<std::mutex> lock(impl_->mutex);
  impl_->context->dicom_server = std::move(server);
}
References kcenon::pacs::web::rest_server::impl::context, impl_, and kcenon::pacs::web::rest_server::impl::mutex.
set_file_storage()
void kcenon::pacs::web::rest_server::set_file_storage (std::shared_ptr< storage::file_storage > storage)
Set file storage for DICOM instance persistence (STOW-RS)
Parameters
storage File storage instance
Definition at line 164 of file rest_server.cpp.
{
  std::lock_guard<std::mutex> lock(impl_->mutex);
  impl_->context->file_storage = std::move(storage);
}
References kcenon::pacs::web::rest_server::impl::context, impl_, and kcenon::pacs::web::rest_server::impl::mutex.
set_health_checker()
void kcenon::pacs::web::rest_server::set_health_checker (std::shared_ptr< monitoring::health_checker > checker)
Set health checker for /api/v1/system/status endpoint.
Parameters
checker Health checker instance
Definition at line 140 of file rest_server.cpp.
{
  std::lock_guard<std::mutex> lock(impl_->mutex);
  impl_->context->health_checker = std::move(checker);
}
References kcenon::pacs::web::rest_server::impl::context, impl_, and kcenon::pacs::web::rest_server::impl::mutex.
set_job_manager()
void kcenon::pacs::web::rest_server::set_job_manager (std::shared_ptr< client::job_manager > manager)
Set job manager for async DICOM operations.
Parameters
manager Job manager instance
Definition at line 176 of file rest_server.cpp.
{
  std::lock_guard<std::mutex> lock(impl_->mutex);
  impl_->context->job_manager = std::move(manager);
}
References kcenon::pacs::web::rest_server::impl::context, impl_, and kcenon::pacs::web::rest_server::impl::mutex.
set_metrics_provider()
void kcenon::pacs::web::rest_server::set_metrics_provider (std::shared_ptr< monitoring::pacs_metrics > metrics)
Set metrics provider for /api/v1/system/metrics endpoint.
Parameters
metrics Metrics instance
Set metrics provider for /api/v1/system/metrics endpoint
Parameters
metrics Metrics instance
Definition at line 146 of file rest_server.cpp.
{
  std::lock_guard<std::mutex> lock(impl_->mutex);
  impl_->context->metrics = std::move(metrics);
}
References kcenon::pacs::web::rest_server::impl::context, impl_, and kcenon::pacs::web::rest_server::impl::mutex.
set_node_manager()
void kcenon::pacs::web::rest_server::set_node_manager (std::shared_ptr< client::remote_node_manager > manager)
Set remote node manager for remote PACS node management.
Parameters
manager Remote node manager instance
Definition at line 170 of file rest_server.cpp.
{
  std::lock_guard<std::mutex> lock(impl_->mutex);
  impl_->context->node_manager = std::move(manager);
}
References kcenon::pacs::web::rest_server::impl::context, impl_, and kcenon::pacs::web::rest_server::impl::mutex.
set_oauth2_middleware()
void kcenon::pacs::web::rest_server::set_oauth2_middleware (std::shared_ptr< auth::oauth2_middleware > middleware)
Set OAuth 2.0 middleware for DICOMweb endpoint authorization.
Parameters
middleware OAuth 2.0 middleware instance
Definition at line 194 of file rest_server.cpp.
{
  std::lock_guard<std::mutex> lock(impl_->mutex);
  impl_->context->oauth2 = std::move(middleware);
}
References kcenon::pacs::web::rest_server::impl::context, impl_, and kcenon::pacs::web::rest_server::impl::mutex.
set_routing_manager()
void kcenon::pacs::web::rest_server::set_routing_manager (std::shared_ptr< client::routing_manager > manager)
Set routing manager for auto-forwarding rules.
Parameters
manager Routing manager instance
Definition at line 182 of file rest_server.cpp.
{
  std::lock_guard<std::mutex> lock(impl_->mutex);
  impl_->context->routing_manager = std::move(manager);
}
References kcenon::pacs::web::rest_server::impl::context, impl_, and kcenon::pacs::web::rest_server::impl::mutex.
start()
void kcenon::pacs::web::rest_server::start ()
Start the server (blocking)
This method blocks until stop() is called from another thread.
Definition at line 200 of file rest_server.cpp.
{
  if (impl_->running.exchange(true)) {
    return; // Already running
  }
  impl_->app = std::make_unique<crow::SimpleApp>();
  auto &app = *impl_->app;
  // Register system endpoints
  endpoints::register_system_endpoints_impl(app, impl_->context);
  // Add CORS preflight handler
  if (impl_->config.enable_cors) {
    CROW_ROUTE(app, "/api/<path>")
        .methods(crow::HTTPMethod::OPTIONS)(
            [this](const crow::request & /*req*/,
                   const std::string & /*path*/) {
              crow::response res(204);
              res.add_header("Access-Control-Allow-Origin",
                             impl_->config.cors_allowed_origins);
              res.add_header("Access-Control-Allow-Methods",
                             "GET, POST, PUT, DELETE, OPTIONS");
              res.add_header("Access-Control-Allow-Headers",
                             "Content-Type, Authorization");
              res.add_header("Access-Control-Max-Age", "86400");
              return res;
            });
  }
  // Start server
  app.bindaddr(impl_->config.bind_address)
      .port(impl_->config.port)
      .concurrency(static_cast<uint16_t>(impl_->config.concurrency))
      .run();
  impl_->running = false;
}
References kcenon::pacs::web::rest_server::impl::app, kcenon::pacs::web::rest_server_config::bind_address, kcenon::pacs::web::rest_server_config::concurrency, kcenon::pacs::web::rest_server::impl::config, kcenon::pacs::web::rest_server::impl::context, kcenon::pacs::web::rest_server_config::cors_allowed_origins, kcenon::pacs::web::rest_server_config::enable_cors, impl_, kcenon::pacs::web::rest_server_config::port, kcenon::pacs::web::endpoints::register_system_endpoints_impl(), and kcenon::pacs::web::rest_server::impl::running.
start_async()
void kcenon::pacs::web::rest_server::start_async ()
Start the server (non-blocking)
Starts the server in a background thread and returns immediately.
Definition at line 238 of file rest_server.cpp.
{
  if (impl_->running.exchange(true)) {
    return; // Already running
  }
  impl_->server_thread = std::thread([this]() {
    impl_->app = std::make_unique<crow::SimpleApp>();
    auto &app = *impl_->app;
    // Register endpoints
    endpoints::register_system_endpoints_impl(app, impl_->context);
    endpoints::register_security_endpoints_impl(app, impl_->context);
    endpoints::register_patient_endpoints_impl(app, impl_->context);
    endpoints::register_study_endpoints_impl(app, impl_->context);
    endpoints::register_series_endpoints_impl(app, impl_->context);
    endpoints::register_worklist_endpoints_impl(app, impl_->context);
    endpoints::register_audit_endpoints_impl(app, impl_->context);
    endpoints::register_association_endpoints_impl(app, impl_->context);
    endpoints::register_dicomweb_endpoints_impl(app, impl_->context);
    endpoints::register_remote_nodes_endpoints_impl(app, impl_->context);
    endpoints::register_jobs_endpoints_impl(app, impl_->context);
    endpoints::register_routing_endpoints_impl(app, impl_->context);
    endpoints::register_thumbnail_endpoints_impl(app, impl_->context);
    endpoints::register_metadata_endpoints_impl(app, impl_->context);
    endpoints::register_annotation_endpoints_impl(app, impl_->context);
    endpoints::register_measurement_endpoints_impl(app, impl_->context);
    endpoints::register_key_image_endpoints_impl(app, impl_->context);
    endpoints::register_viewer_state_endpoints_impl(app, impl_->context);
    endpoints::register_wado_uri_endpoints_impl(app, impl_->context);
    endpoints::register_storage_commitment_endpoints_impl(app, impl_->context);
#ifdef PACS_WITH_DATABASE_SYSTEM
    endpoints::register_metrics_endpoints_impl(app, impl_->context);
#endif
    // Add CORS preflight handler
    if (impl_->config.enable_cors) {
      CROW_ROUTE(app, "/api/<path>")
          .methods(crow::HTTPMethod::OPTIONS)(
              [this](const crow::request & /*req*/,
                     const std::string & /*path*/) {
                crow::response res(204);
                res.add_header("Access-Control-Allow-Origin",
                               impl_->config.cors_allowed_origins);
                res.add_header("Access-Control-Allow-Methods",
                               "GET, POST, PUT, DELETE, OPTIONS");
                res.add_header("Access-Control-Allow-Headers",
                               "Content-Type, Authorization");
                res.add_header("Access-Control-Max-Age", "86400");
                return res;
              });
    }
    // Start server
    app.bindaddr(impl_->config.bind_address)
        .port(impl_->config.port)
        .concurrency(static_cast<uint16_t>(impl_->config.concurrency))
        .run();
    impl_->running = false;
  });
}
References kcenon::pacs::web::rest_server::impl::app, kcenon::pacs::web::rest_server_config::bind_address, kcenon::pacs::web::rest_server_config::concurrency, kcenon::pacs::web::rest_server::impl::config, kcenon::pacs::web::rest_server::impl::context, kcenon::pacs::web::rest_server_config::cors_allowed_origins, kcenon::pacs::web::rest_server_config::enable_cors, impl_, kcenon::pacs::web::rest_server_config::port, kcenon::pacs::web::endpoints::register_annotation_endpoints_impl(), kcenon::pacs::web::endpoints::register_association_endpoints_impl(), kcenon::pacs::web::endpoints::register_audit_endpoints_impl(), kcenon::pacs::web::endpoints::register_dicomweb_endpoints_impl(), kcenon::pacs::web::endpoints::register_jobs_endpoints_impl(), kcenon::pacs::web::endpoints::register_key_image_endpoints_impl(), kcenon::pacs::web::endpoints::register_measurement_endpoints_impl(), kcenon::pacs::web::endpoints::register_metadata_endpoints_impl(), kcenon::pacs::web::endpoints::register_patient_endpoints_impl(), kcenon::pacs::web::endpoints::register_remote_nodes_endpoints_impl(), kcenon::pacs::web::endpoints::register_routing_endpoints_impl(), kcenon::pacs::web::endpoints::register_security_endpoints_impl(), kcenon::pacs::web::endpoints::register_series_endpoints_impl(), kcenon::pacs::web::endpoints::register_storage_commitment_endpoints_impl(), kcenon::pacs::web::endpoints::register_study_endpoints_impl(), kcenon::pacs::web::endpoints::register_system_endpoints_impl(), kcenon::pacs::web::endpoints::register_thumbnail_endpoints_impl(), kcenon::pacs::web::endpoints::register_viewer_state_endpoints_impl(), kcenon::pacs::web::endpoints::register_wado_uri_endpoints_impl(), kcenon::pacs::web::endpoints::register_worklist_endpoints_impl(), kcenon::pacs::web::rest_server::impl::running, and kcenon::pacs::web::rest_server::impl::server_thread.
stop()
void kcenon::pacs::web::rest_server::stop ()
Stop the server.
Gracefully shuts down the server. Safe to call multiple times.
Definition at line 301 of file rest_server.cpp.
                       {
  if (!impl_->running) {
    return;
  }
  if (impl_->app) {
    impl_->app->stop();
  }
  if (impl_->server_thread.joinable()) {
    impl_->server_thread.join();
  }
  impl_->running = false;
}
References kcenon::pacs::web::rest_server::impl::app, impl_, kcenon::pacs::web::rest_server::impl::running, and kcenon::pacs::web::rest_server::impl::server_thread.
Referenced by ~rest_server().
wait()
void kcenon::pacs::web::rest_server::wait ()
Wait for server to stop.
Blocks until the server has completely stopped. Only valid after start_async() was called.
Definition at line 319 of file rest_server.cpp.
                       {
  if (impl_->server_thread.joinable()) {
    impl_->server_thread.join();
  }
}
References impl_, and kcenon::pacs::web::rest_server::impl::server_thread.
Member Data Documentation
impl_
std::unique_ptr<impl> kcenon::pacs::web::rest_server::impl_ private
Definition at line 244 of file rest_server.h.
Referenced by config(), is_running(), port(), set_access_control_manager(), set_config(), set_database(), set_dicom_server(), set_file_storage(), set_health_checker(), set_job_manager(), set_metrics_provider(), set_node_manager(), set_oauth2_middleware(), set_routing_manager(), start(), start_async(), stop(), and wait().
The documentation for this class was generated from the following files:
include/kcenon/pacs/web/rest_server.h
src/web/rest_server.cpp