PACS System: kcenon::pacs::services::validation::rt_iod_validator Class Reference
kcenon::pacs::services::validation::rt_iod_validator Class Reference
Unified validator for all RT IODs.
#include <rt_iod_validator.h>
Public Member Functions
rt_iod_validator ()=default
rt_iod_validator (const rt_validation_options &options)
validation_result validate (const core::dicom_dataset &dataset) const
Validate an RT dataset (auto-detects type)
bool quick_check (const core::dicom_dataset &dataset) const
Quick check if dataset has minimum required RT attributes.
const rt_validation_options & options () const noexcept
void set_options (const rt_validation_options &options)
Private Attributes
rt_validation_options options_
Detailed Description
Unified validator for all RT IODs.
Automatically detects the RT object type and applies appropriate validation. Supports RT Plan, RT Dose, RT Structure Set, RT Image, and treatment records.
Definition at line 336 of file rt_iod_validator.h.
Constructor & Destructor Documentation
rt_iod_validator() [1/2]
kcenon::pacs::services::validation::rt_iod_validator::rt_iod_validator () default
rt_iod_validator() [2/2]
kcenon::pacs::services::validation::rt_iod_validator::rt_iod_validator (const rt_validation_options & options) explicit
Definition at line 1058 of file rt_iod_validator.cpp.
    : options_(options) {}
Member Function Documentation
options()
const rt_validation_options & kcenon::pacs::services::validation::rt_iod_validator::options () const nodiscard noexcept
Definition at line 1125 of file rt_iod_validator.cpp.
{
    return options_;
}
References options_.
Referenced by set_options().
quick_check()
bool kcenon::pacs::services::validation::rt_iod_validator::quick_check (const core::dicom_dataset & dataset) const nodiscard
Quick check if dataset has minimum required RT attributes.
Parameters
dataset The dataset to check
Returns
true if all Type 1 attributes are present
Definition at line 1116 of file rt_iod_validator.cpp.
{
    // Try each RT type
    if (rt_plan_iod_validator(options_).quick_check(dataset)) return true;
    if (rt_dose_iod_validator(options_).quick_check(dataset)) return true;
    if (rt_structure_set_iod_validator(options_).quick_check(dataset)) return true;
    return false;
}
References options_, and quick_check().
Referenced by kcenon::pacs::services::validation::is_valid_rt_dataset(), and quick_check().
set_options()
void kcenon::pacs::services::validation::rt_iod_validator::set_options (const rt_validation_options & options)
Definition at line 1129 of file rt_iod_validator.cpp.
{
    options_ = options;
}
References options(), and options_.
validate()
validation_result kcenon::pacs::services::validation::rt_iod_validator::validate (const core::dicom_dataset & dataset) const nodiscard
Validate an RT dataset (auto-detects type)
Parameters
dataset The dataset to validate
Returns
Validation result with all findings
Definition at line 1061 of file rt_iod_validator.cpp.
{
    // Detect RT object type from SOP Class UID or Modality
    std::string sop_class;
    if (dataset.contains(tags::sop_class_uid)) {
        sop_class = dataset.get_string(tags::sop_class_uid);
    }
    // Route to appropriate validator
    if (sop_class == sop_classes::rt_plan_storage_uid ||
        sop_class == sop_classes::rt_ion_plan_storage_uid) {
        rt_plan_iod_validator validator(options_);
        return validator.validate(dataset);
    }
    if (sop_class == sop_classes::rt_dose_storage_uid) {
        rt_dose_iod_validator validator(options_);
        return validator.validate(dataset);
    }
    if (sop_class == sop_classes::rt_structure_set_storage_uid) {
        rt_structure_set_iod_validator validator(options_);
        return validator.validate(dataset);
    }
    // Try to detect from Modality if SOP Class not recognized
    if (dataset.contains(tags::modality)) {
        auto modality = dataset.get_string(tags::modality);
        if (modality == "RTPLAN") {
            rt_plan_iod_validator validator(options_);
            return validator.validate(dataset);
        }
        if (modality == "RTDOSE") {
            rt_dose_iod_validator validator(options_);
            return validator.validate(dataset);
        }
        if (modality == "RTSTRUCT") {
            rt_structure_set_iod_validator validator(options_);
            return validator.validate(dataset);
        }
    }
    // Unknown RT type
    validation_result result;
    result.is_valid = false;
    result.findings.push_back({
        validation_severity::error,
        tags::sop_class_uid,
        "Unable to determine RT object type from SOPClassUID or Modality",
        "RT-ERR-001"
    });
    return result;
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::validation_result::is_valid, kcenon::pacs::core::tags::modality, options_, kcenon::pacs::services::sop_classes::rt_dose_storage_uid, kcenon::pacs::services::sop_classes::rt_ion_plan_storage_uid, kcenon::pacs::services::sop_classes::rt_plan_storage_uid, kcenon::pacs::services::sop_classes::rt_structure_set_storage_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::services::validation::rt_dose_iod_validator::validate(), kcenon::pacs::services::validation::rt_plan_iod_validator::validate(), and kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate().
Referenced by kcenon::pacs::services::validation::validate_rt_iod().
Member Data Documentation
options_
rt_validation_options kcenon::pacs::services::validation::rt_iod_validator::options_ private
Definition at line 359 of file rt_iod_validator.h.
Referenced by options(), quick_check(), set_options(), and validate().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/validation/rt_iod_validator.h
src/services/validation/rt_iod_validator.cpp