PACS System: kcenon::pacs::services::scp_service Class Reference
kcenon::pacs::services::scp_service Class Reference abstract
#include <scp_service.h>
Public Member Functions
scp_service (std::shared_ptr< di::ILogger > logger=nullptr)
Construct SCP service with optional logger.
virtual ~scp_service ()=default
scp_service (const scp_service &)=delete
scp_service & operator= (const scp_service &)=delete
scp_service (scp_service &&)=default
scp_service & operator= (scp_service &&)=default
void set_logger (std::shared_ptr< di::ILogger > logger)
Set the logger instance.
const std::shared_ptr< di::ILogger > & logger () const noexcept
Get the current logger instance.
virtual std::vector< std::string > supported_sop_classes () const =0
Get the list of SOP Class UIDs supported by this service.
virtual network::Result< std::monostate > handle_message (network::association &assoc, uint8_t context_id, const network::dimse::dimse_message &request)=0
Handle an incoming DIMSE message.
virtual std::string_view service_name () const noexcept=0
Get the service name for logging/debugging.
bool supports_sop_class (std::string_view sop_class_uid) const
Check if this service supports a specific SOP Class.
Protected Attributes
std::shared_ptr< di::ILogger > logger_
Logger instance for service logging.
Detailed Description
Definition at line 53 of file scp_service.h.
Constructor & Destructor Documentation
scp_service() [1/3]
kcenon::pacs::services::scp_service::scp_service (std::shared_ptr< di::ILogger > logger = nullptr) inline explicit
Construct SCP service with optional logger.
Parameters
logger Logger instance for service logging (nullptr uses null_logger)
Definition at line 64 of file scp_service.h.
        : logger_(logger ? std::move(logger) : di::null_logger()) {}
~scp_service()
virtual kcenon::pacs::services::scp_service::~scp_service () virtual default
scp_service() [2/3]
kcenon::pacs::services::scp_service::scp_service (const scp_service &) delete
scp_service() [3/3]
kcenon::pacs::services::scp_service::scp_service (scp_service &&) default
Member Function Documentation
handle_message()
virtual network::Result< std::monostate > kcenon::pacs::services::scp_service::handle_message (network::association & assoc, uint8_t context_id, const network::dimse::dimse_message & request) nodiscard pure virtual
Handle an incoming DIMSE message.
Processes the request and sends appropriate response(s) via the association.
Parameters
assoc The association on which the message was received
context_id The presentation context ID for the message
request The incoming DIMSE request message
Returns
Success or error result
Implemented in kcenon::pacs::services::mpps_scp, kcenon::pacs::services::n_get_scp, kcenon::pacs::services::print_scp, kcenon::pacs::services::query_scp, kcenon::pacs::services::retrieve_scp, kcenon::pacs::services::storage_commitment_scp, kcenon::pacs::services::storage_scp, kcenon::pacs::services::ups_push_scp, kcenon::pacs::services::ups_query_scp, kcenon::pacs::services::ups_watch_scp, kcenon::pacs::services::verification_scp, and kcenon::pacs::services::worklist_scp.
logger()
const std::shared_ptr< di::ILogger > & kcenon::pacs::services::scp_service::logger () const inline nodiscard noexcept
Get the current logger instance.
Returns
Shared pointer to the logger
Definition at line 93 of file scp_service.h.
{
        return logger_;
    }
References logger_.
Referenced by set_logger().
operator=() [1/2]
scp_service & kcenon::pacs::services::scp_service::operator= (const scp_service &) delete
operator=() [2/2]
scp_service & kcenon::pacs::services::scp_service::operator= (scp_service &&) default
service_name()
virtual std::string_view kcenon::pacs::services::scp_service::service_name () const nodiscard pure virtual noexcept
Get the service name for logging/debugging.
Returns
Human-readable service name
Implemented in kcenon::pacs::services::mpps_scp, kcenon::pacs::services::n_get_scp, kcenon::pacs::services::print_scp, kcenon::pacs::services::query_scp, kcenon::pacs::services::retrieve_scp, kcenon::pacs::services::storage_commitment_scp, kcenon::pacs::services::storage_scp, kcenon::pacs::services::ups_push_scp, kcenon::pacs::services::ups_query_scp, kcenon::pacs::services::ups_watch_scp, kcenon::pacs::services::verification_scp, and kcenon::pacs::services::worklist_scp.
set_logger()
void kcenon::pacs::services::scp_service::set_logger (std::shared_ptr< di::ILogger > logger) inline
Set the logger instance.
Parameters
logger New logger instance (nullptr uses null_logger)
Definition at line 84 of file scp_service.h.
{
        logger_ = logger ? std::move(logger) : di::null_logger();
    }
References logger(), logger_, and kcenon::pacs::di::null_logger().
supported_sop_classes()
virtual std::vector< std::string > kcenon::pacs::services::scp_service::supported_sop_classes () const nodiscard pure virtual
Get the list of SOP Class UIDs supported by this service.
Returns
Vector of SOP Class UIDs that this service can handle
Implemented in kcenon::pacs::services::mpps_scp, kcenon::pacs::services::n_get_scp, kcenon::pacs::services::print_scp, kcenon::pacs::services::query_scp, kcenon::pacs::services::retrieve_scp, kcenon::pacs::services::storage_commitment_scp, kcenon::pacs::services::storage_scp, kcenon::pacs::services::ups_push_scp, kcenon::pacs::services::ups_query_scp, kcenon::pacs::services::ups_watch_scp, kcenon::pacs::services::verification_scp, and kcenon::pacs::services::worklist_scp.
Referenced by supports_sop_class().
supports_sop_class()
bool kcenon::pacs::services::scp_service::supports_sop_class (std::string_view sop_class_uid) const inline nodiscard
Check if this service supports a specific SOP Class.
Parameters
sop_class_uid The SOP Class UID to check
Returns
true if the SOP Class is supported
Definition at line 140 of file scp_service.h.
{
        const auto classes = supported_sop_classes();
        for (const auto& uid : classes) {
            if (uid == sop_class_uid) {
                return true;
            }
        }
        return false;
    }
References supported_sop_classes(), and uid.
Referenced by kcenon::pacs::services::n_get_scp::handle_message().
Member Data Documentation
logger_
std::shared_ptr<di::ILogger> kcenon::pacs::services::scp_service::logger_ protected
Logger instance for service logging.
Definition at line 156 of file scp_service.h.
Referenced by kcenon::pacs::services::ups_watch_scp::dispatch_event(), kcenon::pacs::services::n_get_scp::handle_message(), kcenon::pacs::services::ups_query_scp::handle_message(), kcenon::pacs::services::ups_watch_scp::handle_subscribe(), kcenon::pacs::services::ups_watch_scp::handle_suspend_global(), kcenon::pacs::services::ups_watch_scp::handle_unsubscribe(), logger(), and set_logger().
The documentation for this class was generated from the following file:
include/kcenon/pacs/services/scp_service.h