PACS System: kcenon::pacs::monitoring::pacs_metrics Class Reference
kcenon::pacs::monitoring::pacs_metrics Class Reference
Central metrics collection for PACS DICOM operations.
#include <pacs_metrics.h>
Public Member Functions
pacs_metrics ()=default
Default constructor.
pacs_metrics (const pacs_metrics &)=delete
Non-copyable.
pacs_metrics & operator= (const pacs_metrics &)=delete
pacs_metrics (pacs_metrics &&)=delete
Non-movable (singleton)
pacs_metrics & operator= (pacs_metrics &&)=delete
void record_store (bool success, std::chrono::microseconds duration, std::uint64_t bytes_stored=0) noexcept
Record a C-STORE operation.
void record_query (bool success, std::chrono::microseconds duration, std::uint32_t matches=0) noexcept
Record a C-FIND (query) operation.
void record_echo (bool success, std::chrono::microseconds duration) noexcept
Record a C-ECHO (verification) operation.
void record_move (bool success, std::chrono::microseconds duration, std::uint32_t images_moved=0) noexcept
Record a C-MOVE operation.
void record_get (bool success, std::chrono::microseconds duration, std::uint32_t images_retrieved=0, std::uint64_t bytes_retrieved=0) noexcept
Record a C-GET operation.
void record_operation (dimse_operation op, bool success, std::chrono::microseconds duration) noexcept
Record a generic DIMSE operation.
void record_bytes_sent (std::uint64_t bytes) noexcept
Record bytes sent over the network.
void record_bytes_received (std::uint64_t bytes) noexcept
Record bytes received from the network.
void record_association_established () noexcept
Record an association being established.
void record_association_released () noexcept
Record an association being released.
void record_association_rejected () noexcept
Record an association being rejected.
void record_association_aborted () noexcept
Record an association being aborted.
const operation_counter & get_counter (dimse_operation op) const noexcept
Get operation counter for a specific DIMSE operation.
operation_counter & get_counter (dimse_operation op) noexcept
Get mutable operation counter for a specific DIMSE operation.
const data_transfer_metrics & transfer () const noexcept
Get data transfer metrics.
const association_counters & associations () const noexcept
Get association counters.
const pool_counters & element_pool () const noexcept
Get element pool counters.
pool_counters & element_pool () noexcept
Get mutable element pool counters.
const pool_counters & dataset_pool () const noexcept
Get dataset pool counters.
pool_counters & dataset_pool () noexcept
Get mutable dataset pool counters.
const pool_counters & pdu_buffer_pool () const noexcept
Get PDU buffer pool counters.
pool_counters & pdu_buffer_pool () noexcept
Get mutable PDU buffer pool counters.
std::string to_json () const
Export metrics as JSON string.
std::string to_prometheus (std::string_view prefix="pacs") const
Export metrics in Prometheus text format.
void reset () noexcept
Reset all metrics to zero.
Static Public Member Functions
static pacs_metrics & global_metrics () noexcept
Get the global singleton instance.
Private Attributes
operation_counter c_echo_
operation_counter c_store_
operation_counter c_find_
operation_counter c_move_
operation_counter c_get_
operation_counter n_create_
operation_counter n_set_
operation_counter n_get_
operation_counter n_action_
operation_counter n_event_
operation_counter n_delete_
data_transfer_metrics transfer_
association_counters associations_
pool_counters element_pool_
pool_counters dataset_pool_
pool_counters pdu_buffer_pool_
Detailed Description
Central metrics collection for PACS DICOM operations.
The pacs_metrics class provides a thread-safe, low-overhead mechanism for tracking DICOM operation metrics including:
DIMSE operation counts and timing (C-ECHO, C-STORE, C-FIND, C-MOVE, C-GET)
Data transfer volumes (bytes sent/received, images stored/retrieved)
Association lifecycle events (established, rejected, aborted)
Thread Safety: All public methods are thread-safe using atomic operations.
Definition at line 354 of file pacs_metrics.h.
Constructor & Destructor Documentation
pacs_metrics() [1/3]
kcenon::pacs::monitoring::pacs_metrics::pacs_metrics () default
Default constructor.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
pacs_metrics() [2/3]
kcenon::pacs::monitoring::pacs_metrics::pacs_metrics (const pacs_metrics &) delete
Non-copyable.
pacs_metrics() [3/3]
kcenon::pacs::monitoring::pacs_metrics::pacs_metrics (pacs_metrics &&) delete
Non-movable (singleton)
Member Function Documentation
associations()
const association_counters & kcenon::pacs::monitoring::pacs_metrics::associations () const inline nodiscard noexcept
Get association counters.
Returns
Const reference to association counters
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/collectors/dicom_association_collector.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/collectors/dicom_metrics_collector.h, and /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 609 of file pacs_metrics.h.
{
        return associations_;
    }
References associations_.
Referenced by kcenon::pacs::monitoring::dicom_association_collector::collect(), and kcenon::pacs::monitoring::dicom_metrics_collector::collect_association_metrics().
dataset_pool() [1/2]
const pool_counters & kcenon::pacs::monitoring::pacs_metrics::dataset_pool () const inline nodiscard noexcept
Get dataset pool counters.
Returns
Const reference to dataset pool counters
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 637 of file pacs_metrics.h.
{
        return dataset_pool_;
    }
References dataset_pool_.
dataset_pool() [2/2]
pool_counters & kcenon::pacs::monitoring::pacs_metrics::dataset_pool () inline nodiscard noexcept
Get mutable dataset pool counters.
Returns
Reference to dataset pool counters
Definition at line 645 of file pacs_metrics.h.
{
        return dataset_pool_;
    }
References dataset_pool_.
element_pool() [1/2]
const pool_counters & kcenon::pacs::monitoring::pacs_metrics::element_pool () const inline nodiscard noexcept
Get element pool counters.
Returns
Const reference to element pool counters
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 621 of file pacs_metrics.h.
{
        return element_pool_;
    }
References element_pool_.
element_pool() [2/2]
pool_counters & kcenon::pacs::monitoring::pacs_metrics::element_pool () inline nodiscard noexcept
Get mutable element pool counters.
Returns
Reference to element pool counters
Definition at line 629 of file pacs_metrics.h.
{
        return element_pool_;
    }
References element_pool_.
get_counter() [1/2]
const operation_counter & kcenon::pacs::monitoring::pacs_metrics::get_counter (dimse_operation op) const inline nodiscard noexcept
Get operation counter for a specific DIMSE operation.
Parameters
op The DIMSE operation type
Returns
Const reference to the operation counter
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 558 of file pacs_metrics.h.
{
        switch (op) {
            case dimse_operation::c_echo:
                return c_echo_;
            case dimse_operation::c_store:
                return c_store_;
            case dimse_operation::c_find:
                return c_find_;
            case dimse_operation::c_move:
                return c_move_;
            case dimse_operation::c_get:
                return c_get_;
            case dimse_operation::n_create:
                return n_create_;
            case dimse_operation::n_set:
                return n_set_;
            case dimse_operation::n_get:
                return n_get_;
            case dimse_operation::n_action:
                return n_action_;
            case dimse_operation::n_event:
                return n_event_;
            case dimse_operation::n_delete:
                return n_delete_;
            default:
                return c_echo_;  // Should never happen
        }
    }
References kcenon::pacs::monitoring::c_echo, c_echo_, kcenon::pacs::monitoring::c_find, c_find_, kcenon::pacs::monitoring::c_get, c_get_, kcenon::pacs::monitoring::c_move, c_move_, kcenon::pacs::monitoring::c_store, c_store_, kcenon::pacs::monitoring::n_action, n_action_, kcenon::pacs::monitoring::n_create, n_create_, kcenon::pacs::monitoring::n_delete, n_delete_, kcenon::pacs::monitoring::n_event, n_event_, kcenon::pacs::monitoring::n_get, n_get_, kcenon::pacs::monitoring::n_set, and n_set_.
Referenced by get_counter(), and record_operation().
get_counter() [2/2]
operation_counter & kcenon::pacs::monitoring::pacs_metrics::get_counter (dimse_operation op) inline nodiscard noexcept
Get mutable operation counter for a specific DIMSE operation.
Parameters
op The DIMSE operation type
Returns
Reference to the operation counter
Definition at line 592 of file pacs_metrics.h.
{
        return const_cast<operation_counter&>(
            static_cast<const pacs_metrics*>(this)->get_counter(op));
    }
References get_counter().
global_metrics()
static pacs_metrics & kcenon::pacs::monitoring::pacs_metrics::global_metrics () inline static nodiscard noexcept
Get the global singleton instance.
Returns
Reference to the global metrics instance
Thread-safe lazy initialization using Meyer's singleton pattern.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/collectors/dicom_association_collector.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/collectors/dicom_metrics_collector.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/collectors/dicom_service_collector.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/collectors/dicom_storage_collector.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h, and /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_monitor.h.
Definition at line 371 of file pacs_metrics.h.
{
        static pacs_metrics instance;
        return instance;
    }
Referenced by kcenon::pacs::monitoring::dicom_association_collector::collect(), kcenon::pacs::monitoring::dicom_service_collector::collect(), kcenon::pacs::monitoring::dicom_metrics_collector::collect_association_metrics(), kcenon::pacs::monitoring::dicom_metrics_collector::collect_pool_metrics(), kcenon::pacs::monitoring::dicom_storage_collector::collect_pool_metrics(), kcenon::pacs::monitoring::dicom_metrics_collector::collect_query_metrics(), kcenon::pacs::monitoring::dicom_metrics_collector::collect_storage_metrics(), kcenon::pacs::monitoring::dicom_metrics_collector::collect_transfer_metrics(), kcenon::pacs::monitoring::dicom_storage_collector::collect_transfer_metrics(), kcenon::pacs::monitoring::dicom_metrics_collector::get_snapshot(), kcenon::pacs::monitoring::pacs_monitor::reset(), kcenon::pacs::monitoring::pacs_monitor::to_json(), and kcenon::pacs::monitoring::pacs_monitor::to_prometheus().
operator=() [1/2]
pacs_metrics & kcenon::pacs::monitoring::pacs_metrics::operator= (const pacs_metrics &) delete
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
operator=() [2/2]
pacs_metrics & kcenon::pacs::monitoring::pacs_metrics::operator= (pacs_metrics &&) delete
pdu_buffer_pool() [1/2]
const pool_counters & kcenon::pacs::monitoring::pacs_metrics::pdu_buffer_pool () const inline nodiscard noexcept
Get PDU buffer pool counters.
Returns
Const reference to PDU buffer pool counters
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 653 of file pacs_metrics.h.
{
        return pdu_buffer_pool_;
    }
References pdu_buffer_pool_.
pdu_buffer_pool() [2/2]
pool_counters & kcenon::pacs::monitoring::pacs_metrics::pdu_buffer_pool () inline nodiscard noexcept
Get mutable PDU buffer pool counters.
Returns
Reference to PDU buffer pool counters
Definition at line 661 of file pacs_metrics.h.
{
        return pdu_buffer_pool_;
    }
References pdu_buffer_pool_.
record_association_aborted()
void kcenon::pacs::monitoring::pacs_metrics::record_association_aborted () inline noexcept
Record an association being aborted.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 545 of file pacs_metrics.h.
{
        associations_.record_aborted();
    }
References associations_, and kcenon::pacs::monitoring::association_counters::record_aborted().
record_association_established()
void kcenon::pacs::monitoring::pacs_metrics::record_association_established () inline noexcept
Record an association being established.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 524 of file pacs_metrics.h.
{
        associations_.record_established();
    }
References associations_, and kcenon::pacs::monitoring::association_counters::record_established().
record_association_rejected()
void kcenon::pacs::monitoring::pacs_metrics::record_association_rejected () inline noexcept
Record an association being rejected.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 538 of file pacs_metrics.h.
{
        associations_.record_rejected();
    }
References associations_, and kcenon::pacs::monitoring::association_counters::record_rejected().
record_association_released()
void kcenon::pacs::monitoring::pacs_metrics::record_association_released () inline noexcept
Record an association being released.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 531 of file pacs_metrics.h.
{
        associations_.record_released();
    }
References associations_, and kcenon::pacs::monitoring::association_counters::record_released().
record_bytes_received()
void kcenon::pacs::monitoring::pacs_metrics::record_bytes_received (std::uint64_t bytes) inline noexcept
Record bytes received from the network.
Parameters
bytes Number of bytes received
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 513 of file pacs_metrics.h.
{
        transfer_.add_bytes_received(bytes);
    }
References kcenon::pacs::monitoring::data_transfer_metrics::add_bytes_received(), and transfer_.
record_bytes_sent()
void kcenon::pacs::monitoring::pacs_metrics::record_bytes_sent (std::uint64_t bytes) inline noexcept
Record bytes sent over the network.
Parameters
bytes Number of bytes sent
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 505 of file pacs_metrics.h.
{
        transfer_.add_bytes_sent(bytes);
    }
References kcenon::pacs::monitoring::data_transfer_metrics::add_bytes_sent(), and transfer_.
record_echo()
void kcenon::pacs::monitoring::pacs_metrics::record_echo (bool success, std::chrono::microseconds duration) inline noexcept
Record a C-ECHO (verification) operation.
Parameters
success Whether the operation succeeded
duration Operation duration
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 429 of file pacs_metrics.h.
{
        if (success) {
            c_echo_.record_success(duration);
        } else {
            c_echo_.record_failure(duration);
        }
    }
References c_echo_, kcenon::pacs::monitoring::operation_counter::record_failure(), and kcenon::pacs::monitoring::operation_counter::record_success().
record_get()
void kcenon::pacs::monitoring::pacs_metrics::record_get (bool success, std::chrono::microseconds duration, std::uint32_t images_retrieved = 0, std::uint64_t bytes_retrieved = 0) inline noexcept
Record a C-GET operation.
Parameters
success Whether the operation succeeded
duration Operation duration
images_retrieved Number of images retrieved
bytes_retrieved Number of bytes retrieved
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 463 of file pacs_metrics.h.
{
        if (success) {
            c_get_.record_success(duration);
            for (std::uint32_t i = 0; i < images_retrieved; ++i) {
                transfer_.increment_images_retrieved();
            }
            if (bytes_retrieved > 0) {
                transfer_.add_bytes_sent(bytes_retrieved);
            }
        } else {
            c_get_.record_failure(duration);
        }
    }
References kcenon::pacs::monitoring::data_transfer_metrics::add_bytes_sent(), c_get_, kcenon::pacs::monitoring::data_transfer_metrics::increment_images_retrieved(), kcenon::pacs::monitoring::operation_counter::record_failure(), kcenon::pacs::monitoring::operation_counter::record_success(), and transfer_.
record_move()
void kcenon::pacs::monitoring::pacs_metrics::record_move (bool success, std::chrono::microseconds duration, std::uint32_t images_moved = 0) inline noexcept
Record a C-MOVE operation.
Parameters
success Whether the operation succeeded
duration Operation duration
images_moved Number of images moved
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 443 of file pacs_metrics.h.
{
        if (success) {
            c_move_.record_success(duration);
            for (std::uint32_t i = 0; i < images_moved; ++i) {
                transfer_.increment_images_retrieved();
            }
        } else {
            c_move_.record_failure(duration);
        }
    }
References c_move_, kcenon::pacs::monitoring::data_transfer_metrics::increment_images_retrieved(), kcenon::pacs::monitoring::operation_counter::record_failure(), kcenon::pacs::monitoring::operation_counter::record_success(), and transfer_.
record_operation()
void kcenon::pacs::monitoring::pacs_metrics::record_operation (dimse_operation op, bool success, std::chrono::microseconds duration) inline noexcept
Record a generic DIMSE operation.
Parameters
op Operation type
success Whether the operation succeeded
duration Operation duration
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 486 of file pacs_metrics.h.
{
        auto& counter = get_counter(op);
        if (success) {
            counter.record_success(duration);
        } else {
            counter.record_failure(duration);
        }
    }
References kcenon::pacs::monitoring::counter, and get_counter().
record_query()
void kcenon::pacs::monitoring::pacs_metrics::record_query (bool success, std::chrono::microseconds duration, std::uint32_t matches = 0) inline noexcept
Record a C-FIND (query) operation.
Parameters
success Whether the operation succeeded
duration Operation duration
matches Number of matching results
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 414 of file pacs_metrics.h.
{
        if (success) {
            c_find_.record_success(duration);
        } else {
            c_find_.record_failure(duration);
        }
    }
References c_find_, kcenon::pacs::monitoring::operation_counter::record_failure(), and kcenon::pacs::monitoring::operation_counter::record_success().
record_store()
void kcenon::pacs::monitoring::pacs_metrics::record_store (bool success, std::chrono::microseconds duration, std::uint64_t bytes_stored = 0) inline noexcept
Record a C-STORE operation.
Parameters
success Whether the operation succeeded
duration Operation duration
bytes_stored Number of bytes stored (0 if failed)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 394 of file pacs_metrics.h.
{
        if (success) {
            c_store_.record_success(duration);
            if (bytes_stored > 0) {
                transfer_.add_bytes_received(bytes_stored);
                transfer_.increment_images_stored();
            }
        } else {
            c_store_.record_failure(duration);
        }
    }
References kcenon::pacs::monitoring::data_transfer_metrics::add_bytes_received(), c_store_, kcenon::pacs::monitoring::data_transfer_metrics::increment_images_stored(), kcenon::pacs::monitoring::operation_counter::record_failure(), kcenon::pacs::monitoring::operation_counter::record_success(), and transfer_.
reset()
void kcenon::pacs::monitoring::pacs_metrics::reset () inline noexcept
Reset all metrics to zero.
Thread-safe reset of all counters. Useful for testing or periodic metric collection windows.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h, and /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_monitor.h.
Definition at line 698 of file pacs_metrics.h.
{
        c_echo_.reset();
        c_store_.reset();
        c_find_.reset();
        c_move_.reset();
        c_get_.reset();
        n_create_.reset();
        n_set_.reset();
        n_get_.reset();
        n_action_.reset();
        n_event_.reset();
        n_delete_.reset();
        transfer_.reset();
        associations_.reset();
        element_pool_.reset();
        dataset_pool_.reset();
        pdu_buffer_pool_.reset();
    }
References associations_, c_echo_, c_find_, c_get_, c_move_, c_store_, dataset_pool_, element_pool_, n_action_, n_create_, n_delete_, n_event_, n_get_, n_set_, pdu_buffer_pool_, kcenon::pacs::monitoring::association_counters::reset(), kcenon::pacs::monitoring::data_transfer_metrics::reset(), kcenon::pacs::monitoring::operation_counter::reset(), kcenon::pacs::monitoring::pool_counters::reset(), and transfer_.
Referenced by kcenon::pacs::monitoring::pacs_monitor::reset().
to_json()
std::string kcenon::pacs::monitoring::pacs_metrics::to_json () const nodiscard
Export metrics as JSON string.
Returns
JSON representation of all metrics
The JSON format is suitable for REST API responses and integration with monitoring systems like Grafana.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h, and /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_monitor.h.
Definition at line 110 of file pacs_metrics.cpp.
{
    std::ostringstream oss;
    oss << "{";
    // DIMSE operations section
    oss << R"("dimse_operations":{)"
        << R"("c_echo":)" << counter_to_json(c_echo_)
        << R"(,"c_store":)" << counter_to_json(c_store_)
        << R"(,"c_find":)" << counter_to_json(c_find_)
        << R"(,"c_move":)" << counter_to_json(c_move_)
        << R"(,"c_get":)" << counter_to_json(c_get_)
        << R"(,"n_create":)" << counter_to_json(n_create_)
        << R"(,"n_set":)" << counter_to_json(n_set_)
        << R"(,"n_get":)" << counter_to_json(n_get_)
        << R"(,"n_action":)" << counter_to_json(n_action_)
        << R"(,"n_event":)" << counter_to_json(n_event_)
        << R"(,"n_delete":)" << counter_to_json(n_delete_)
        << "}";
    // Data transfer section
    oss << R"(,"data_transfer":{)"
        << R"("bytes_sent":)" << transfer_.bytes_sent.load(std::memory_order_relaxed)
        << R"(,"bytes_received":)" << transfer_.bytes_received.load(std::memory_order_relaxed)
        << R"(,"images_stored":)" << transfer_.images_stored.load(std::memory_order_relaxed)
        << R"(,"images_retrieved":)" << transfer_.images_retrieved.load(std::memory_order_relaxed)
        << "}";
    // Associations section
    oss << R"(,"associations":{)"
        << R"("total_established":)" << associations_.total_established.load(std::memory_order_relaxed)
        << R"(,"total_rejected":)" << associations_.total_rejected.load(std::memory_order_relaxed)
        << R"(,"total_aborted":)" << associations_.total_aborted.load(std::memory_order_relaxed)
        << R"(,"current_active":)" << associations_.current_active.load(std::memory_order_relaxed)
        << R"(,"peak_active":)" << associations_.peak_active.load(std::memory_order_relaxed)
        << "}";
    oss << "}";
    return oss.str();
}
References associations_, kcenon::pacs::monitoring::data_transfer_metrics::bytes_received, kcenon::pacs::monitoring::data_transfer_metrics::bytes_sent, c_echo_, c_find_, c_get_, c_move_, c_store_, kcenon::pacs::monitoring::association_counters::current_active, kcenon::pacs::monitoring::data_transfer_metrics::images_retrieved, kcenon::pacs::monitoring::data_transfer_metrics::images_stored, n_action_, n_create_, n_delete_, n_event_, n_get_, n_set_, kcenon::pacs::monitoring::association_counters::peak_active, kcenon::pacs::monitoring::association_counters::total_aborted, kcenon::pacs::monitoring::association_counters::total_established, kcenon::pacs::monitoring::association_counters::total_rejected, and transfer_.
Referenced by kcenon::pacs::monitoring::pacs_monitor::to_json().
to_prometheus()
std::string kcenon::pacs::monitoring::pacs_metrics::to_prometheus (std::string_view prefix = "pacs") const nodiscard
Export metrics in Prometheus text format.
Parameters
prefix Metric name prefix (default: "pacs")
Returns
Prometheus exposition format text
The output follows the Prometheus text-based format specification suitable for scraping by Prometheus servers.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h, and /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_monitor.h.
Definition at line 150 of file pacs_metrics.cpp.
{
    std::ostringstream oss;
    // DIMSE operation metrics
    counter_to_prometheus(oss, prefix, "c_echo", c_echo_);
    counter_to_prometheus(oss, prefix, "c_store", c_store_);
    counter_to_prometheus(oss, prefix, "c_find", c_find_);
    counter_to_prometheus(oss, prefix, "c_move", c_move_);
    counter_to_prometheus(oss, prefix, "c_get", c_get_);
    counter_to_prometheus(oss, prefix, "n_create", n_create_);
    counter_to_prometheus(oss, prefix, "n_set", n_set_);
    counter_to_prometheus(oss, prefix, "n_get", n_get_);
    counter_to_prometheus(oss, prefix, "n_action", n_action_);
    counter_to_prometheus(oss, prefix, "n_event", n_event_);
    counter_to_prometheus(oss, prefix, "n_delete", n_delete_);
    // Data transfer metrics
    oss << "# HELP " << prefix << "_bytes_sent_total Total bytes sent over network\n"
        << "# TYPE " << prefix << "_bytes_sent_total counter\n"
        << prefix << "_bytes_sent_total " << transfer_.bytes_sent.load(std::memory_order_relaxed) << "\n";
    oss << "# HELP " << prefix << "_bytes_received_total Total bytes received from network\n"
        << "# TYPE " << prefix << "_bytes_received_total counter\n"
        << prefix << "_bytes_received_total " << transfer_.bytes_received.load(std::memory_order_relaxed) << "\n";
    oss << "# HELP " << prefix << "_images_stored_total Total DICOM images stored\n"
        << "# TYPE " << prefix << "_images_stored_total counter\n"
        << prefix << "_images_stored_total " << transfer_.images_stored.load(std::memory_order_relaxed) << "\n";
    oss << "# HELP " << prefix << "_images_retrieved_total Total DICOM images retrieved\n"
        << "# TYPE " << prefix << "_images_retrieved_total counter\n"
        << prefix << "_images_retrieved_total " << transfer_.images_retrieved.load(std::memory_order_relaxed) << "\n";
    // Association metrics
    oss << "# HELP " << prefix << "_associations_established_total Total associations established\n"
        << "# TYPE " << prefix << "_associations_established_total counter\n"
        << prefix << "_associations_established_total " << associations_.total_established.load(std::memory_order_relaxed) << "\n";
    oss << "# HELP " << prefix << "_associations_rejected_total Total associations rejected\n"
        << "# TYPE " << prefix << "_associations_rejected_total counter\n"
        << prefix << "_associations_rejected_total " << associations_.total_rejected.load(std::memory_order_relaxed) << "\n";
    oss << "# HELP " << prefix << "_associations_aborted_total Total associations aborted\n"
        << "# TYPE " << prefix << "_associations_aborted_total counter\n"
        << prefix << "_associations_aborted_total " << associations_.total_aborted.load(std::memory_order_relaxed) << "\n";
    oss << "# HELP " << prefix << "_associations_active Current active associations\n"
        << "# TYPE " << prefix << "_associations_active gauge\n"
        << prefix << "_associations_active " << associations_.current_active.load(std::memory_order_relaxed) << "\n";
    oss << "# HELP " << prefix << "_associations_peak_active Peak concurrent associations\n"
        << "# TYPE " << prefix << "_associations_peak_active gauge\n"
        << prefix << "_associations_peak_active " << associations_.peak_active.load(std::memory_order_relaxed) << "\n";
    return oss.str();
}
References associations_, kcenon::pacs::monitoring::data_transfer_metrics::bytes_received, kcenon::pacs::monitoring::data_transfer_metrics::bytes_sent, c_echo_, c_find_, c_get_, c_move_, c_store_, kcenon::pacs::monitoring::association_counters::current_active, kcenon::pacs::monitoring::data_transfer_metrics::images_retrieved, kcenon::pacs::monitoring::data_transfer_metrics::images_stored, n_action_, n_create_, n_delete_, n_event_, n_get_, n_set_, kcenon::pacs::monitoring::association_counters::peak_active, kcenon::pacs::monitoring::association_counters::total_aborted, kcenon::pacs::monitoring::association_counters::total_established, kcenon::pacs::monitoring::association_counters::total_rejected, and transfer_.
Referenced by kcenon::pacs::monitoring::pacs_monitor::to_prometheus().
transfer()
const data_transfer_metrics & kcenon::pacs::monitoring::pacs_metrics::transfer () const inline nodiscard noexcept
Get data transfer metrics.
Returns
Const reference to transfer metrics
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/collectors/dicom_metrics_collector.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/collectors/dicom_storage_collector.h, and /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 601 of file pacs_metrics.h.
{
        return transfer_;
    }
References transfer_.
Referenced by kcenon::pacs::monitoring::dicom_metrics_collector::collect_transfer_metrics(), and kcenon::pacs::monitoring::dicom_storage_collector::collect_transfer_metrics().
Member Data Documentation
associations_
association_counters kcenon::pacs::monitoring::pacs_metrics::associations_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 735 of file pacs_metrics.h.
Referenced by associations(), record_association_aborted(), record_association_established(), record_association_rejected(), record_association_released(), reset(), to_json(), and to_prometheus().
c_echo_
operation_counter kcenon::pacs::monitoring::pacs_metrics::c_echo_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 719 of file pacs_metrics.h.
Referenced by get_counter(), record_echo(), reset(), to_json(), and to_prometheus().
c_find_
operation_counter kcenon::pacs::monitoring::pacs_metrics::c_find_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 721 of file pacs_metrics.h.
Referenced by get_counter(), record_query(), reset(), to_json(), and to_prometheus().
c_get_
operation_counter kcenon::pacs::monitoring::pacs_metrics::c_get_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 723 of file pacs_metrics.h.
Referenced by get_counter(), record_get(), reset(), to_json(), and to_prometheus().
c_move_
operation_counter kcenon::pacs::monitoring::pacs_metrics::c_move_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 722 of file pacs_metrics.h.
Referenced by get_counter(), record_move(), reset(), to_json(), and to_prometheus().
c_store_
operation_counter kcenon::pacs::monitoring::pacs_metrics::c_store_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 720 of file pacs_metrics.h.
Referenced by get_counter(), record_store(), reset(), to_json(), and to_prometheus().
dataset_pool_
pool_counters kcenon::pacs::monitoring::pacs_metrics::dataset_pool_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 739 of file pacs_metrics.h.
Referenced by dataset_pool(), dataset_pool(), and reset().
element_pool_
pool_counters kcenon::pacs::monitoring::pacs_metrics::element_pool_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 738 of file pacs_metrics.h.
Referenced by element_pool(), element_pool(), and reset().
n_action_
operation_counter kcenon::pacs::monitoring::pacs_metrics::n_action_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 727 of file pacs_metrics.h.
Referenced by get_counter(), reset(), to_json(), and to_prometheus().
n_create_
operation_counter kcenon::pacs::monitoring::pacs_metrics::n_create_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 724 of file pacs_metrics.h.
Referenced by get_counter(), reset(), to_json(), and to_prometheus().
n_delete_
operation_counter kcenon::pacs::monitoring::pacs_metrics::n_delete_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 729 of file pacs_metrics.h.
Referenced by get_counter(), reset(), to_json(), and to_prometheus().
n_event_
operation_counter kcenon::pacs::monitoring::pacs_metrics::n_event_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 728 of file pacs_metrics.h.
Referenced by get_counter(), reset(), to_json(), and to_prometheus().
n_get_
operation_counter kcenon::pacs::monitoring::pacs_metrics::n_get_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 726 of file pacs_metrics.h.
Referenced by get_counter(), reset(), to_json(), and to_prometheus().
n_set_
operation_counter kcenon::pacs::monitoring::pacs_metrics::n_set_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 725 of file pacs_metrics.h.
Referenced by get_counter(), reset(), to_json(), and to_prometheus().
pdu_buffer_pool_
pool_counters kcenon::pacs::monitoring::pacs_metrics::pdu_buffer_pool_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 740 of file pacs_metrics.h.
Referenced by pdu_buffer_pool(), pdu_buffer_pool(), and reset().
transfer_
data_transfer_metrics kcenon::pacs::monitoring::pacs_metrics::transfer_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 732 of file pacs_metrics.h.
Referenced by record_bytes_received(), record_bytes_sent(), record_get(), record_move(), record_store(), reset(), to_json(), to_prometheus(), and transfer().
The documentation for this class was generated from the following files:
include/kcenon/pacs/monitoring/pacs_metrics.h
src/monitoring/pacs_metrics.cpp