PACS System: kcenon::pacs::integration_test::test_association Class Reference
kcenon::pacs::integration_test::test_association Class Reference
Helper for establishing test associations.
#include <test_fixtures.h>
Static Public Member Functions
static network::Result< network::association > connect (const std::string &host, uint16_t port, const std::string &called_ae, const std::string &calling_ae=test_scu_ae_title, const std::vector< std::string > &sop_classes={"1.2.840.10008.1.1"})
Connect to a test server.
Detailed Description
Helper for establishing test associations.
Definition at line 727 of file test_fixtures.h.
Member Function Documentation
connect()
static network::Result< network::association > kcenon::pacs::integration_test::test_association::connect (const std::string & host, uint16_t port, const std::string & called_ae, const std::string & calling_ae = test_scu_ae_title, const std::vector< std::string > & sop_classes = {"1.2.840.10008.1.1"}) inline static
Connect to a test server.
Parameters
host Server host
port Server port
called_ae Called AE title
calling_ae Calling AE title
sop_classes SOP classes to propose
Returns
Result with association or error
Definition at line 738 of file test_fixtures.h.
                                                  {"1.2.840.10008.1.1"}) {
        network::association_config config;
        config.calling_ae_title = calling_ae;
        config.called_ae_title = called_ae;
        config.implementation_class_uid = "1.2.826.0.1.3680043.9.9999.2";
        config.implementation_version_name = "TEST_SCU";
        uint8_t context_id = 1;
        for (const auto& sop_class : sop_classes) {
            config.proposed_contexts.push_back({
                context_id,
                sop_class,
                {
                    "1.2.840.10008.1.2.1",  // Explicit VR Little Endian
                    "1.2.840.10008.1.2"     // Implicit VR Little Endian
                }
            });
            context_id += 2;
        }
        return network::association::connect(host, port, config, default_timeout());
    }
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
The documentation for this class was generated from the following file:
examples/integration_tests/test_fixtures.h