PACS System: kcenon::pacs::core::dicom_dataset Class Reference
kcenon::pacs::core::dicom_dataset Class Reference
#include <dicom_dataset.h>
Public Types
using storage_type = std::map<dicom_tag, dicom_element>
Storage type for elements (ordered by tag)
using iterator = storage_type::iterator
Iterator type.
using const_iterator = storage_type::const_iterator
Const iterator type.
Public Member Functions
dicom_dataset ()=default
Default constructor - creates an empty dataset.
dicom_dataset (const dicom_dataset &)=default
Copy constructor.
dicom_dataset (dicom_dataset &&) noexcept=default
Move constructor.
auto operator= (const dicom_dataset &) -> dicom_dataset &=default
Copy assignment.
auto operator= (dicom_dataset &&) noexcept -> dicom_dataset &=default
Move assignment.
~dicom_dataset ()=default
Default destructor.
auto contains (dicom_tag tag) const noexcept -> bool
Check if the dataset contains an element with the given tag.
auto get (dicom_tag tag) noexcept -> dicom_element *
Get a pointer to the element with the given tag.
auto get (dicom_tag tag) const noexcept -> const dicom_element *
Get a const pointer to the element with the given tag.
auto get_string (dicom_tag tag, std::string_view default_value="") const -> std::string
Get the string value of an element.
template<typename T >
requires std::is_arithmetic_v<T>
auto get_numeric (dicom_tag tag) const -> std::optional< T >
Get the numeric value of an element.
auto has_sequence (dicom_tag tag) const noexcept -> bool
Check if the dataset contains a sequence element with the given tag.
auto get_sequence (dicom_tag tag) const noexcept -> const std::vector< dicom_dataset > *
auto get_sequence (dicom_tag tag) noexcept -> std::vector< dicom_dataset > *
Get mutable access to sequence items for a given tag.
auto get_or_create_sequence (dicom_tag tag) -> std::vector< dicom_dataset > &
Insert or create a sequence element with the given tag.
auto get_private_creator (dicom_tag private_data_tag) const -> std::optional< std::string >
Get the Private Creator identification string for a private data element.
auto get_private_block (std::string_view creator_id, uint16_t group) const -> std::vector< const dicom_element * >
Get all private data elements belonging to a specific creator.
auto set_private_element (std::string_view creator_id, uint16_t group, uint8_t element_offset, encoding::vr_type vr, std::string_view value) -> std::optional< dicom_tag >
Insert a private data element with automatic creator management.
auto remove_private_block (std::string_view creator_id, uint16_t group) -> size_t
Remove all private data elements and their creator for a given creator.
auto cleanup_orphaned_creators () -> size_t
Remove orphaned Private Creator elements that have no data elements.
auto validate_private_tags () const -> std::vector< dicom_tag >
Validate private tag relationships in this dataset.
void insert (dicom_element element)
Insert or replace an element in the dataset.
void set_string (dicom_tag tag, encoding::vr_type vr, std::string_view value)
Set a string value for the given tag.
template<typename T >
requires std::is_arithmetic_v<T>
void set_numeric (dicom_tag tag, encoding::vr_type vr, T value)
Set a numeric value for the given tag.
auto remove (dicom_tag tag) -> bool
Remove an element from the dataset.
void clear () noexcept
Remove all elements from the dataset.
auto begin () noexcept -> iterator
Get iterator to the first element.
auto end () noexcept -> iterator
Get iterator past the last element.
auto begin () const noexcept -> const_iterator
Get const iterator to the first element.
auto end () const noexcept -> const_iterator
Get const iterator past the last element.
auto cbegin () const noexcept -> const_iterator
Get const iterator to the first element.
auto cend () const noexcept -> const_iterator
Get const iterator past the last element.
auto size () const noexcept -> size_t
Get the number of elements in the dataset.
auto empty () const noexcept -> bool
Check if the dataset is empty.
auto copy_with_tags (std::initializer_list< dicom_tag > tags) const -> dicom_dataset
Create a copy containing only the specified tags.
auto copy_with_tags (std::span< const dicom_tag > tags) const -> dicom_dataset
Create a copy containing only the specified tags.
void merge (const dicom_dataset &other)
Merge elements from another dataset.
void merge (dicom_dataset &&other)
Merge elements from another dataset (move version)
Private Attributes
storage_type elements_
Detailed Description
Examples
/home/runner/work/pacs_system/pacs_system/examples/query_scu/query_builder.h, dcm_anonymize/main.cpp, dcm_dir/main.cpp, dcm_dump/main.cpp, dcm_extract/main.cpp, dcm_modify/main.cpp, dcm_to_json/main.cpp, dcm_to_xml/main.cpp, find_scu/main.cpp, get_scu/main.cpp, img_to_dcm/main.cpp, json_to_dcm/main.cpp, module_example/main.cpp, move_scu/main.cpp, mpps_scp/main.cpp, qr_scp/main.cpp, retrieve_scu/main.cpp, worklist_scp/main.cpp, and xml_to_dcm/main.cpp.
Definition at line 65 of file dicom_dataset.h.
Member Typedef Documentation
const_iterator
using kcenon::pacs::core::dicom_dataset::const_iterator = storage_type::const_iterator
Const iterator type.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 74 of file dicom_dataset.h.
iterator
using kcenon::pacs::core::dicom_dataset::iterator = storage_type::iterator
Iterator type.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 71 of file dicom_dataset.h.
storage_type
using kcenon::pacs::core::dicom_dataset::storage_type = std::map<dicom_tag, dicom_element>
Storage type for elements (ordered by tag)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 68 of file dicom_dataset.h.
Constructor & Destructor Documentation
dicom_dataset() [1/3]
kcenon::pacs::core::dicom_dataset::dicom_dataset () default
Default constructor - creates an empty dataset.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
dicom_dataset() [2/3]
kcenon::pacs::core::dicom_dataset::dicom_dataset (const dicom_dataset &) default
Copy constructor.
dicom_dataset() [3/3]
kcenon::pacs::core::dicom_dataset::dicom_dataset (dicom_dataset &&) default noexcept
Move constructor.
~dicom_dataset()
kcenon::pacs::core::dicom_dataset::~dicom_dataset () default
Default destructor.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Member Function Documentation
begin() [1/2]
auto kcenon::pacs::core::dicom_dataset::begin () const -> const_iterator nodiscard noexcept
Get const iterator to the first element.
Returns
Const iterator to the beginning
Definition at line 311 of file dicom_dataset.cpp.
{
    return elements_.begin();
}
References elements_.
begin() [2/2]
auto kcenon::pacs::core::dicom_dataset::begin () -> iterator nodiscard noexcept
Get iterator to the first element.
Returns
Iterator to the beginning
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 303 of file dicom_dataset.cpp.
{
    return elements_.begin();
}
References elements_.
cbegin()
auto kcenon::pacs::core::dicom_dataset::cbegin () const -> const_iterator nodiscard noexcept
Get const iterator to the first element.
Returns
Const iterator to the beginning
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 319 of file dicom_dataset.cpp.
{
    return elements_.cbegin();
}
References elements_.
cend()
auto kcenon::pacs::core::dicom_dataset::cend () const -> const_iterator nodiscard noexcept
Get const iterator past the last element.
Returns
Const iterator to the end
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 323 of file dicom_dataset.cpp.
{
    return elements_.cend();
}
References elements_.
cleanup_orphaned_creators()
auto kcenon::pacs::core::dicom_dataset::cleanup_orphaned_creators () -> size_t
Remove orphaned Private Creator elements that have no data elements.
Returns
Number of orphaned creators removed
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 234 of file dicom_dataset.cpp.
{
    size_t removed = 0;
    std::vector<dicom_tag> orphans;
    for (const auto& [tag, elem] : elements_) {
        if (!tag.is_private_creator()) {
            continue;
        }
        // Check if any data elements exist in this creator's block
        const auto range = tag.private_data_range();
        if (!range) {
            continue;
        }
        const auto [first, last] = *range;
        auto it = elements_.lower_bound(first);
        if (it == elements_.end() || it->first > last) {
            orphans.push_back(tag);
        }
    }
    for (const auto& tag : orphans) {
        elements_.erase(tag);
        ++removed;
    }
    return removed;
}
clear()
void kcenon::pacs::core::dicom_dataset::clear () noexcept
Remove all elements from the dataset.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 295 of file dicom_dataset.cpp.
{
    elements_.clear();
}
References elements_.
contains()
auto kcenon::pacs::core::dicom_dataset::contains (dicom_tag tag) const -> bool nodiscard noexcept
Check if the dataset contains an element with the given tag.
Parameters
tag The DICOM tag to check
Returns
true if an element with this tag exists
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h, and dcm_modify/main.cpp.
Definition at line 18 of file dicom_dataset.cpp.
{
    return elements_.contains(tag);
}
Referenced by kcenon::pacs::services::validation::sr_iod_validator::check_completion_flag(), kcenon::pacs::services::validation::mg_iod_validator::check_compression_force_range(), kcenon::pacs::services::validation::rt_dose_iod_validator::check_dose_data_consistency(), kcenon::pacs::services::validation::ophthalmic_iod_validator::check_laterality(), kcenon::pacs::services::validation::mg_iod_validator::check_laterality_consistency(), kcenon::pacs::services::validation::ct_iod_validator::check_modality(), kcenon::pacs::services::validation::ct_processing_iod_validator::check_modality(), kcenon::pacs::services::validation::dx_iod_validator::check_modality(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::check_modality(), kcenon::pacs::services::validation::label_map_seg_iod_validator::check_modality(), kcenon::pacs::services::validation::mg_iod_validator::check_modality(), kcenon::pacs::services::validation::mr_iod_validator::check_modality(), kcenon::pacs::services::validation::nm_iod_validator::check_modality(), kcenon::pacs::services::validation::ophthalmic_iod_validator::check_modality(), kcenon::pacs::services::validation::parametric_map_iod_validator::check_modality(), kcenon::pacs::services::validation::pet_iod_validator::check_modality(), kcenon::pacs::services::validation::seg_iod_validator::check_modality(), kcenon::pacs::services::validation::sr_iod_validator::check_modality(), kcenon::pacs::services::validation::us_iod_validator::check_modality(), kcenon::pacs::services::validation::wsi_iod_validator::check_modality(), kcenon::pacs::services::validation::xa_iod_validator::check_modality(), kcenon::pacs::services::validation::dx_iod_validator::check_photometric_interpretation(), kcenon::pacs::services::validation::mg_iod_validator::check_photometric_interpretation(), kcenon::pacs::services::validation::ct_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::ct_processing_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::label_map_seg_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::mr_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::nm_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::ophthalmic_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::parametric_map_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::pet_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::seg_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::us_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::wsi_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::xa_iod_validator::check_positioner_angles(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::check_roi_consistency(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::check_segmentation_type(), kcenon::pacs::services::validation::label_map_seg_iod_validator::check_segmentation_type(), kcenon::pacs::services::validation::seg_iod_validator::check_segmentation_type(), kcenon::pacs::services::validation::ct_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::ct_processing_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::dx_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::label_map_seg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::mg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::mr_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::nm_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::ophthalmic_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::parametric_map_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::pet_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::rt_dose_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::rt_plan_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::seg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::sr_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::us_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::waveform_ps_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::wsi_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::xa_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::ct_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::ct_processing_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::dx_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::label_map_seg_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::mg_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::mr_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::nm_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::ophthalmic_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::parametric_map_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::pet_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::rt_dose_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::rt_plan_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::seg_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::sr_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::us_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::waveform_ps_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::wsi_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::xa_iod_validator::check_type2_attribute(), kcenon::pacs::services::validation::sr_iod_validator::check_verification_flag(), kcenon::pacs::services::validation::mg_iod_validator::check_view_position_validity(), kcenon::pacs::services::validation::xa_iod_validator::check_xa_photometric(), kcenon::pacs::services::validation::has_breast_implant(), kcenon::pacs::services::validation::has_qca_calibration(), kcenon::pacs::services::validation::is_binary_segmentation(), kcenon::pacs::services::validation::is_for_presentation_dx(), kcenon::pacs::services::validation::is_for_presentation_mg(), kcenon::pacs::services::validation::is_for_processing_dx(), kcenon::pacs::services::validation::is_for_processing_mg(), kcenon::pacs::services::validation::is_fractional_segmentation(), kcenon::pacs::services::validation::is_heightmap_segmentation(), kcenon::pacs::services::validation::is_label_map_segmentation(), kcenon::pacs::services::validation::is_screening_mammogram(), kcenon::pacs::services::validation::is_sr_complete(), kcenon::pacs::services::validation::is_sr_verified(), kcenon::pacs::network::dimse::dimse_message::is_valid(), kcenon::pacs::services::validation::ct_iod_validator::quick_check(), kcenon::pacs::services::validation::ct_processing_iod_validator::quick_check(), kcenon::pacs::services::validation::dx_iod_validator::quick_check(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::quick_check(), kcenon::pacs::services::validation::label_map_seg_iod_validator::quick_check(), kcenon::pacs::services::validation::mg_iod_validator::quick_check(), kcenon::pacs::services::validation::mr_iod_validator::quick_check(), kcenon::pacs::services::validation::nm_iod_validator::quick_check(), kcenon::pacs::services::validation::ophthalmic_iod_validator::quick_check(), kcenon::pacs::services::validation::parametric_map_iod_validator::quick_check(), kcenon::pacs::services::validation::pet_iod_validator::quick_check(), kcenon::pacs::services::validation::rt_dose_iod_validator::quick_check(), kcenon::pacs::services::validation::rt_plan_iod_validator::quick_check(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::quick_check(), kcenon::pacs::services::validation::seg_iod_validator::quick_check(), kcenon::pacs::services::validation::sr_iod_validator::quick_check(), kcenon::pacs::services::validation::us_iod_validator::quick_check(), kcenon::pacs::services::validation::waveform_ps_iod_validator::quick_check(), kcenon::pacs::services::validation::wsi_iod_validator::quick_check(), kcenon::pacs::services::validation::xa_iod_validator::quick_check(), kcenon::pacs::services::validation::rt_iod_validator::validate(), kcenon::pacs::services::validation::sr_iod_validator::validate(), kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_acquisition_context_module(), kcenon::pacs::services::validation::mg_iod_validator::validate_acquisition_dose_module(), kcenon::pacs::services::validation::mg_iod_validator::validate_breast_implant_module(), kcenon::pacs::services::validation::xa_iod_validator::validate_calibration_module(), kcenon::pacs::services::validation::sr_iod_validator::validate_coded_entry(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::validate_common_instance_reference_module(), kcenon::pacs::services::validation::label_map_seg_iod_validator::validate_common_instance_reference_module(), kcenon::pacs::services::validation::parametric_map_iod_validator::validate_common_instance_reference_module(), kcenon::pacs::services::validation::seg_iod_validator::validate_common_instance_reference_module(), kcenon::pacs::services::validation::sr_iod_validator::validate_content_sequence(), kcenon::pacs::services::validation::pet_iod_validator::validate_corrections(), kcenon::pacs::services::validation::ct_iod_validator::validate_ct_image_module(), kcenon::pacs::services::validation::ct_processing_iod_validator::validate_ct_image_module(), kcenon::pacs::services::validation::dx_iod_validator::validate_dx_anatomy_imaged_module(), kcenon::pacs::services::validation::mg_iod_validator::validate_dx_anatomy_imaged_module(), kcenon::pacs::services::validation::dx_iod_validator::validate_dx_detector_module(), kcenon::pacs::services::validation::mg_iod_validator::validate_dx_detector_module(), kcenon::pacs::services::validation::dx_iod_validator::validate_dx_image_module(), kcenon::pacs::services::validation::dx_iod_validator::validate_dx_positioning_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_energy_window_info(), kcenon::pacs::services::validation::sr_iod_validator::validate_evidence_sequences(), kcenon::pacs::services::validation::dx_iod_validator::validate_for_presentation(), kcenon::pacs::services::validation::mg_iod_validator::validate_for_presentation(), kcenon::pacs::services::validation::dx_iod_validator::validate_for_processing(), kcenon::pacs::services::validation::mg_iod_validator::validate_for_processing(), kcenon::pacs::services::validation::rt_dose_iod_validator::validate_image_pixel_module(), kcenon::pacs::services::validation::sr_iod_validator::validate_key_object_selection(), kcenon::pacs::services::validation::mg_iod_validator::validate_mammography_image_module(), kcenon::pacs::services::validation::mg_iod_validator::validate_mammography_series_module(), kcenon::pacs::services::validation::mr_iod_validator::validate_mr_image_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_multiframe(), kcenon::pacs::services::validation::parametric_map_iod_validator::validate_multiframe_dimension_module(), kcenon::pacs::services::validation::wsi_iod_validator::validate_multiframe_dimension_module(), kcenon::pacs::services::validation::parametric_map_iod_validator::validate_multiframe_functional_groups_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_multiframe_module(), kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_multiframe_module(), kcenon::pacs::services::validation::us_iod_validator::validate_multiframe_module(), kcenon::pacs::services::validation::xa_iod_validator::validate_multiframe_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_nm_detector_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_nm_gated_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_nm_image_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_nm_series_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_nm_tomo_module(), kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_ophthalmic_image_module(), kcenon::pacs::services::validation::wsi_iod_validator::validate_optical_path_module(), kcenon::pacs::services::validation::parametric_map_iod_validator::validate_parametric_map_image_module(), kcenon::pacs::services::validation::pet_iod_validator::validate_pet_image_module(), kcenon::pacs::services::validation::pet_iod_validator::validate_pet_series_module(), validate_private_tags(), kcenon::pacs::services::validation::nm_iod_validator::validate_radiopharmaceutical_info(), kcenon::pacs::services::validation::pet_iod_validator::validate_radiopharmaceutical_info(), kcenon::pacs::services::validation::pet_iod_validator::validate_reconstruction_info(), kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_references(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_roi_contour_module(), kcenon::pacs::services::validation::rt_plan_iod_validator::validate_rt_beams_module(), kcenon::pacs::services::validation::rt_dose_iod_validator::validate_rt_dose_module(), kcenon::pacs::services::validation::rt_plan_iod_validator::validate_rt_fraction_scheme_module(), kcenon::pacs::services::validation::rt_plan_iod_validator::validate_rt_general_plan_module(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_rt_roi_observations_module(), kcenon::pacs::services::validation::rt_dose_iod_validator::validate_rt_series_module(), kcenon::pacs::services::validation::rt_plan_iod_validator::validate_rt_series_module(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_rt_series_module(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::validate_segment_sequence(), kcenon::pacs::services::validation::label_map_seg_iod_validator::validate_segment_sequence(), kcenon::pacs::services::validation::seg_iod_validator::validate_segment_sequence(), kcenon::pacs::services::validation::seg_iod_validator::validate_segmentation_image_module(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::validate_single_segment(), kcenon::pacs::services::validation::label_map_seg_iod_validator::validate_single_segment(), kcenon::pacs::services::validation::seg_iod_validator::validate_single_segment(), kcenon::pacs::services::validation::ct_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::ct_processing_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::dx_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::label_map_seg_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::mg_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::mr_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::parametric_map_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::pet_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::rt_dose_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::rt_plan_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::seg_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::sr_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::us_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::wsi_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::xa_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::wsi_iod_validator::validate_specimen_module(), kcenon::pacs::services::validation::sr_iod_validator::validate_sr_document_content_module(), kcenon::pacs::services::validation::sr_iod_validator::validate_sr_document_general_module(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_structure_set_module(), kcenon::pacs::services::validation::pet_iod_validator::validate_suv_parameters(), kcenon::pacs::services::validation::us_iod_validator::validate_us_image_module(), kcenon::pacs::services::validation::dx_iod_validator::validate_voi_lut_module(), kcenon::pacs::services::validation::mg_iod_validator::validate_voi_lut_module(), kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_waveform_annotation_module(), kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_waveform_ps_module(), kcenon::pacs::services::validation::wsi_iod_validator::validate_wsi_image_module(), and kcenon::pacs::services::validation::xa_iod_validator::validate_xa_acquisition_module().
copy_with_tags() [1/2]
auto kcenon::pacs::core::dicom_dataset::copy_with_tags (std::initializer_list< dicom_tag > tags) const -> dicom_dataset nodiscard
Create a copy containing only the specified tags.
Parameters
tags List of tags to include in the copy
Returns
A new dataset containing only the specified elements
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 343 of file dicom_dataset.cpp.
                     {
    return copy_with_tags(std::span{tags.begin(), tags.size()});
}
copy_with_tags() [2/2]
auto kcenon::pacs::core::dicom_dataset::copy_with_tags (std::span< const dicom_tag > tags) const -> dicom_dataset nodiscard
Create a copy containing only the specified tags.
Parameters
tags Span of tags to include in the copy
Returns
A new dataset containing only the specified elements
Definition at line 348 of file dicom_dataset.cpp.
                     {
    dicom_dataset result;
    for (const auto& tag : tags) {
        const auto* elem = get(tag);
        if (elem != nullptr) {
            result.insert(*elem);
        }
    }
    return result;
}
References insert().
empty()
auto kcenon::pacs::core::dicom_dataset::empty () const -> bool nodiscard noexcept
Check if the dataset is empty.
Returns
true if no elements are present
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 335 of file dicom_dataset.cpp.
{
    return elements_.empty();
}
References elements_.
end() [1/2]
auto kcenon::pacs::core::dicom_dataset::end () const -> const_iterator nodiscard noexcept
Get const iterator past the last element.
Returns
Const iterator to the end
Definition at line 315 of file dicom_dataset.cpp.
{
    return elements_.end();
}
References elements_.
end() [2/2]
auto kcenon::pacs::core::dicom_dataset::end () -> iterator nodiscard noexcept
Get iterator past the last element.
Returns
Iterator to the end
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 307 of file dicom_dataset.cpp.
{
    return elements_.end();
}
References elements_.
get() [1/2]
auto kcenon::pacs::core::dicom_dataset::get (dicom_tag tag) const -> const dicom_element* nodiscard noexcept
Get a const pointer to the element with the given tag.
Parameters
tag The DICOM tag to look up
Returns
Const pointer to the element, or nullptr if not found
Definition at line 30 of file dicom_dataset.cpp.
{
    auto it = elements_.find(tag);
    if (it == elements_.end()) {
        return nullptr;
    }
    return &it->second;
}
get() [2/2]
auto kcenon::pacs::core::dicom_dataset::get (dicom_tag tag) -> dicom_element* nodiscard noexcept
Get a pointer to the element with the given tag.
Parameters
tag The DICOM tag to look up
Returns
Pointer to the element, or nullptr if not found
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h, dcm_dump/main.cpp, dcm_extract/main.cpp, get_scu/main.cpp, and retrieve_scu/main.cpp.
Definition at line 22 of file dicom_dataset.cpp.
{
    auto it = elements_.find(tag);
    if (it == elements_.end()) {
        return nullptr;
    }
    return &it->second;
}
Referenced by kcenon::pacs::network::dimse::dimse_message::attribute_identifier_list(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::label_map_seg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::parametric_map_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::seg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::sr_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::waveform_ps_iod_validator::check_type1_attribute(), kcenon::pacs::services::print_scu::create_film_box(), kcenon::pacs::services::xds::imaging_document_consumer::extract_references(), kcenon::pacs::services::n_get_scu::get(), kcenon::pacs::services::ups_push_scu::get(), kcenon::pacs::services::validation::get_content_item_count(), kcenon::pacs::encoding::get_decoded_string(), get_numeric(), kcenon::pacs::services::validation::get_segment_count(), kcenon::pacs::services::validation::get_sr_document_title(), kcenon::pacs::services::print_scu::query_printer_status(), kcenon::pacs::services::validation::sr_iod_validator::validate_content_sequence(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::validate_segment_sequence(), kcenon::pacs::services::validation::label_map_seg_iod_validator::validate_segment_sequence(), kcenon::pacs::services::validation::seg_iod_validator::validate_segment_sequence(), and kcenon::pacs::services::validation::sr_iod_validator::validate_sr_document_content_module().
get_numeric()
template<typename T > requires std::is_arithmetic_v<T> auto kcenon::pacs::core::dicom_dataset::get_numeric (dicom_tag tag) const -> std::optional<T> nodiscard
Get the numeric value of an element.
Template Parameters
T The numeric type to return
Parameters
tag The DICOM tag to look up
Returns
Optional containing the value, or nullopt if not found/conversion fails
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h, dcm_dump/main.cpp, and dcm_extract/main.cpp.
Definition at line 433 of file dicom_dataset.h.
{
    const auto* elem = get(tag);
    if (elem == nullptr) {
        return std::nullopt;
    }
    auto result = elem->as_numeric<T>();
    if (result.is_ok()) {
        return result.value();
    }
    return std::nullopt;
}
References get().
Referenced by kcenon::pacs::network::dimse::dimse_message::action_type_id(), kcenon::pacs::services::validation::mg_iod_validator::check_compression_force_range(), kcenon::pacs::services::validation::rt_dose_iod_validator::check_dose_data_consistency(), kcenon::pacs::services::validation::ct_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::ct_processing_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::dx_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::label_map_seg_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::mg_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::mr_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::nm_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::ophthalmic_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::parametric_map_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::pet_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::seg_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::us_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::wsi_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::xa_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::xa_iod_validator::check_positioner_angles(), kcenon::pacs::network::dimse::dimse_message::completed_subops(), kcenon::pacs::network::dimse::dimse_message::event_type_id(), kcenon::pacs::network::dimse::dimse_message::failed_subops(), kcenon::pacs::services::validation::has_qca_calibration(), kcenon::pacs::network::dimse::dimse_message::message_id_responded_to(), kcenon::pacs::network::dimse::dimse_message::priority(), kcenon::pacs::network::dimse::dimse_message::remaining_subops(), kcenon::pacs::network::dimse::dimse_message::status(), kcenon::pacs::services::validation::mg_iod_validator::validate_acquisition_dose_module(), kcenon::pacs::services::validation::xa_iod_validator::validate_calibration_module(), kcenon::pacs::services::validation::dx_iod_validator::validate_dx_image_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_multiframe_module(), kcenon::pacs::services::validation::rt_plan_iod_validator::validate_rt_beams_module(), and kcenon::pacs::network::dimse::dimse_message::warning_subops().
get_or_create_sequence()
auto kcenon::pacs::core::dicom_dataset::get_or_create_sequence (dicom_tag tag) -> std::vector<dicom_dataset>& nodiscard
Insert or create a sequence element with the given tag.
Parameters
tag The DICOM tag for the sequence
Returns
Reference to the sequence items vector (creates empty sequence if not exists)
If an element with the tag already exists and is not a sequence, it will be replaced with an empty sequence.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 79 of file dicom_dataset.cpp.
{
    auto* elem = get(tag);
    if (elem != nullptr && elem->is_sequence()) {
        return elem->sequence_items();
    }
    // Create or replace with empty sequence
    insert(dicom_element{tag, encoding::vr_type::SQ});
    return get(tag)->sequence_items();
}
References kcenon::pacs::encoding::SQ.
Referenced by kcenon::pacs::services::storage_commitment_scu::build_action_dataset(), kcenon::pacs::services::storage_commitment_scp::build_event_report_dataset(), kcenon::pacs::services::print_scp::create_film_box(), and kcenon::pacs::services::print_scu::create_film_box().
get_private_block()
auto kcenon::pacs::core::dicom_dataset::get_private_block (std::string_view creator_id, uint16_t group) const -> std::vector<const dicom_element*> nodiscard
Get all private data elements belonging to a specific creator.
Searches the given group for a Private Creator element matching creator_id, then returns all data elements in that creator's block.
Parameters
creator_id The Private Creator identification string (e.g. "SIEMENS CSA HEADER")
group The private group number (must be odd)
Returns
Vector of pointers to matching data elements (empty if none found)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 111 of file dicom_dataset.cpp.
{
    std::vector<const dicom_element*> result;
    // Scan Private Creator elements (gggg,0010)-(gggg,00FF) for a match
    for (uint16_t slot = 0x0010; slot <= 0x00FF; ++slot) {
        const dicom_tag creator_tag{group, slot};
        const auto* creator_elem = get(creator_tag);
        if (creator_elem == nullptr) {
            continue;
        }
        auto str_result = creator_elem->as_string();
        if (str_result.is_err() || str_result.value() != creator_id) {
            continue;
        }
        // Found the creator — collect all data elements in its block
        const auto range = creator_tag.private_data_range();
        if (!range) {
            break;
        }
        const auto [first, last] = *range;
        auto it = elements_.lower_bound(first);
        while (it != elements_.end() && it->first <= last) {
            result.push_back(&it->second);
            ++it;
        }
        break;
    }
    return result;
}
get_private_creator()
auto kcenon::pacs::core::dicom_dataset::get_private_creator (dicom_tag private_data_tag) const -> std::optional<std::string> nodiscard
Get the Private Creator identification string for a private data element.
Looks up the Private Creator element (gggg,00xx) for a given private data element (gggg,xxyy) and returns its string value.
Parameters
private_data_tag A private data element tag
Returns
The creator identification string, or nullopt if not found
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 94 of file dicom_dataset.cpp.
{
    const auto creator_tag = private_data_tag.private_creator_tag();
    if (!creator_tag) {
        return std::nullopt;
    }
    const auto* elem = get(*creator_tag);
    if (elem == nullptr) {
        return std::nullopt;
    }
    auto result = elem->as_string();
    if (result.is_ok()) {
        return result.value();
    }
    return std::nullopt;
}
Referenced by kcenon::pacs::core::dicom_file::decode_implicit_vr_le().
get_sequence() [1/2]
auto kcenon::pacs::core::dicom_dataset::get_sequence (dicom_tag tag) const -> const std::vector<dicom_dataset>* nodiscard noexcept
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 61 of file dicom_dataset.cpp.
{
    const auto* elem = get(tag);
    if (elem == nullptr || !elem->is_sequence()) {
        return nullptr;
    }
    return &elem->sequence_items();
}
Referenced by kcenon::pacs::services::storage_commitment_scu::parse_event_report_dataset(), and kcenon::pacs::services::storage_commitment_scp::parse_referenced_sop_sequence().
get_sequence() [2/2]
auto kcenon::pacs::core::dicom_dataset::get_sequence (dicom_tag tag) -> std::vector<dicom_dataset>* nodiscard noexcept
Get mutable access to sequence items for a given tag.
Parameters
tag The DICOM tag of the sequence element
Returns
Pointer to the sequence items vector, or nullptr if not found or not a sequence
Definition at line 70 of file dicom_dataset.cpp.
{
    auto* elem = get(tag);
    if (elem == nullptr || !elem->is_sequence()) {
        return nullptr;
    }
    return &elem->sequence_items();
}
get_string()
auto kcenon::pacs::core::dicom_dataset::get_string (dicom_tag tag, std::string_view default_value = "") const -> std::string nodiscard
Get the string value of an element.
Parameters
tag The DICOM tag to look up
default_value Value to return if element not found
Returns
The element's string value, or default_value if not found
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h, dcm_anonymize/main.cpp, dcm_dump/main.cpp, dcm_extract/main.cpp, find_scu/main.cpp, get_scu/main.cpp, mpps_scp/main.cpp, qr_scp/main.cpp, retrieve_scu/main.cpp, and worklist_scp/main.cpp.
Definition at line 42 of file dicom_dataset.cpp.
                 {
    const auto* elem = get(tag);
    if (elem == nullptr) {
        return std::string{default_value};
    }
    return elem->as_string().unwrap_or(std::string{default_value});
}
Referenced by kcenon::pacs::services::pir::patient_reconciliation_service::add_instance(), kcenon::pacs::network::dimse::dimse_message::affected_sop_class_uid(), kcenon::pacs::network::dimse::dimse_message::affected_sop_instance_uid(), kcenon::pacs::dcm_modify::anonymizer::anonymize_uids(), kcenon::pacs::services::xds::imaging_document_source::build_document_entry(), kcenon::pacs::services::validation::sr_iod_validator::check_completion_flag(), kcenon::pacs::services::validation::ophthalmic_iod_validator::check_laterality(), kcenon::pacs::services::validation::mg_iod_validator::check_laterality_consistency(), kcenon::pacs::services::validation::ct_iod_validator::check_modality(), kcenon::pacs::services::validation::ct_processing_iod_validator::check_modality(), kcenon::pacs::services::validation::dx_iod_validator::check_modality(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::check_modality(), kcenon::pacs::services::validation::label_map_seg_iod_validator::check_modality(), kcenon::pacs::services::validation::mg_iod_validator::check_modality(), kcenon::pacs::services::validation::mr_iod_validator::check_modality(), kcenon::pacs::services::validation::nm_iod_validator::check_modality(), kcenon::pacs::services::validation::ophthalmic_iod_validator::check_modality(), kcenon::pacs::services::validation::parametric_map_iod_validator::check_modality(), kcenon::pacs::services::validation::pet_iod_validator::check_modality(), kcenon::pacs::services::validation::seg_iod_validator::check_modality(), kcenon::pacs::services::validation::sr_iod_validator::check_modality(), kcenon::pacs::services::validation::us_iod_validator::check_modality(), kcenon::pacs::services::validation::wsi_iod_validator::check_modality(), kcenon::pacs::services::validation::xa_iod_validator::check_modality(), kcenon::pacs::services::validation::dx_iod_validator::check_photometric_interpretation(), kcenon::pacs::services::validation::mg_iod_validator::check_photometric_interpretation(), kcenon::pacs::services::validation::ct_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::ct_processing_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::label_map_seg_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::mr_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::nm_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::ophthalmic_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::parametric_map_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::pet_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::seg_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::us_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::wsi_iod_validator::check_pixel_data_consistency(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::check_segmentation_type(), kcenon::pacs::services::validation::label_map_seg_iod_validator::check_segmentation_type(), kcenon::pacs::services::validation::seg_iod_validator::check_segmentation_type(), kcenon::pacs::services::validation::ct_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::ct_processing_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::dx_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::label_map_seg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::mg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::mr_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::nm_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::ophthalmic_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::parametric_map_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::pet_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::rt_dose_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::rt_plan_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::seg_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::sr_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::us_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::waveform_ps_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::wsi_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::xa_iod_validator::check_type1_attribute(), kcenon::pacs::services::validation::sr_iod_validator::check_verification_flag(), kcenon::pacs::services::validation::mg_iod_validator::check_view_position_validity(), kcenon::pacs::services::validation::xa_iod_validator::check_xa_photometric(), worklist_cli::worklist_result_formatter::extract_item(), kcenon::pacs::services::query_scp::extract_query_level(), kcenon::pacs::encoding::get_decoded_string(), kcenon::pacs::client::routing_manager::get_field_value(), query_scu::result_formatter::get_tag_value(), kcenon::pacs::example::pacs_server_app::handle_query(), kcenon::pacs::example::pacs_server_app::handle_retrieve(), kcenon::pacs::example::pacs_server_app::handle_store(), kcenon::pacs::example::pacs_server_app::handle_worklist_query(), kcenon::pacs::services::validation::has_breast_implant(), kcenon::pacs::services::validation::is_binary_segmentation(), kcenon::pacs::services::validation::is_for_presentation_dx(), kcenon::pacs::services::validation::is_for_presentation_mg(), kcenon::pacs::services::validation::is_for_processing_dx(), kcenon::pacs::services::validation::is_for_processing_mg(), kcenon::pacs::services::validation::is_fractional_segmentation(), kcenon::pacs::services::validation::is_heightmap_segmentation(), kcenon::pacs::services::validation::is_label_map_segmentation(), kcenon::pacs::services::validation::is_screening_mammogram(), kcenon::pacs::services::validation::is_sr_complete(), kcenon::pacs::services::validation::is_sr_verified(), kcenon::pacs::services::ups_watch_scu::parse_event_dataset(), kcenon::pacs::services::storage_commitment_scu::parse_event_report_dataset(), kcenon::pacs::services::worklist_scu::parse_worklist_item(), kcenon::pacs::services::validation::ct_iod_validator::quick_check(), kcenon::pacs::services::validation::ct_processing_iod_validator::quick_check(), kcenon::pacs::services::validation::dx_iod_validator::quick_check(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::quick_check(), kcenon::pacs::services::validation::label_map_seg_iod_validator::quick_check(), kcenon::pacs::services::validation::mg_iod_validator::quick_check(), kcenon::pacs::services::validation::mr_iod_validator::quick_check(), kcenon::pacs::services::validation::nm_iod_validator::quick_check(), kcenon::pacs::services::validation::ophthalmic_iod_validator::quick_check(), kcenon::pacs::services::validation::parametric_map_iod_validator::quick_check(), kcenon::pacs::services::validation::pet_iod_validator::quick_check(), kcenon::pacs::services::validation::rt_dose_iod_validator::quick_check(), kcenon::pacs::services::validation::rt_plan_iod_validator::quick_check(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::quick_check(), kcenon::pacs::services::validation::seg_iod_validator::quick_check(), kcenon::pacs::services::validation::sr_iod_validator::quick_check(), kcenon::pacs::services::validation::us_iod_validator::quick_check(), kcenon::pacs::services::validation::waveform_ps_iod_validator::quick_check(), kcenon::pacs::services::validation::wsi_iod_validator::quick_check(), kcenon::pacs::services::validation::xa_iod_validator::quick_check(), kcenon::pacs::network::dimse::dimse_message::requested_sop_class_uid(), kcenon::pacs::network::dimse::dimse_message::requested_sop_instance_uid(), kcenon::pacs::client::routing_manager::route(), kcenon::pacs::encoding::set_encoded_string(), kcenon::pacs::core::dicom_file::sop_class_uid(), kcenon::pacs::core::dicom_file::sop_instance_uid(), kcenon::pacs::di::test::MockStorage::store(), kcenon::pacs::ai::assessment_manager::store_assessment(), kcenon::pacs::services::storage_scu::store_impl(), TEST_CASE(), kcenon::pacs::core::dicom_file::transfer_syntax(), kcenon::pacs::storage::hsm_storage::update_metadata(), kcenon::pacs::services::validation::rt_iod_validator::validate(), kcenon::pacs::services::validation::sr_iod_validator::validate(), kcenon::pacs::services::validation::waveform_ps_iod_validator::validate(), kcenon::pacs::services::validation::mg_iod_validator::validate_breast_implant_module(), kcenon::pacs::services::validation::sr_iod_validator::validate_content_sequence(), kcenon::pacs::services::validation::pet_iod_validator::validate_corrections(), kcenon::pacs::services::validation::mg_iod_validator::validate_dx_anatomy_imaged_module(), kcenon::pacs::services::validation::dx_iod_validator::validate_dx_detector_module(), kcenon::pacs::services::validation::mg_iod_validator::validate_dx_detector_module(), kcenon::pacs::services::validation::dx_iod_validator::validate_dx_image_module(), kcenon::pacs::services::validation::dx_iod_validator::validate_dx_positioning_module(), kcenon::pacs::services::validation::dx_iod_validator::validate_for_presentation(), kcenon::pacs::services::validation::mg_iod_validator::validate_for_presentation(), kcenon::pacs::services::validation::dx_iod_validator::validate_for_processing(), kcenon::pacs::services::validation::mg_iod_validator::validate_for_processing(), kcenon::pacs::services::validation::mg_iod_validator::validate_mammography_image_module(), kcenon::pacs::services::validation::mr_iod_validator::validate_mr_image_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_multiframe(), kcenon::pacs::services::validation::wsi_iod_validator::validate_multiframe_dimension_module(), kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_multiframe_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_nm_detector_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_nm_image_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_nm_series_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_nm_tomo_module(), kcenon::pacs::services::validation::pet_iod_validator::validate_pet_image_module(), kcenon::pacs::services::validation::pet_iod_validator::validate_pet_series_module(), kcenon::pacs::services::validation::pet_iod_validator::validate_radiopharmaceutical_info(), kcenon::pacs::services::validation::rt_plan_iod_validator::validate_rt_beams_module(), kcenon::pacs::services::validation::rt_dose_iod_validator::validate_rt_dose_module(), kcenon::pacs::services::validation::rt_plan_iod_validator::validate_rt_general_plan_module(), kcenon::pacs::services::validation::rt_dose_iod_validator::validate_rt_series_module(), kcenon::pacs::services::validation::rt_plan_iod_validator::validate_rt_series_module(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_rt_series_module(), kcenon::pacs::services::validation::seg_iod_validator::validate_segmentation_image_module(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::validate_single_segment(), kcenon::pacs::services::validation::label_map_seg_iod_validator::validate_single_segment(), kcenon::pacs::services::validation::seg_iod_validator::validate_single_segment(), kcenon::pacs::services::validation::ct_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::ct_processing_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::dx_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::heightmap_seg_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::label_map_seg_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::mg_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::mr_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::nm_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::parametric_map_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::pet_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::rt_dose_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::rt_plan_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::seg_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::sr_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::us_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::wsi_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::xa_iod_validator::validate_sop_common_module(), kcenon::pacs::services::validation::sr_iod_validator::validate_sr_document_content_module(), kcenon::pacs::services::validation::sr_iod_validator::validate_sr_document_general_module(), and kcenon::pacs::services::validation::pet_iod_validator::validate_suv_parameters().
has_sequence()
auto kcenon::pacs::core::dicom_dataset::has_sequence (dicom_tag tag) const -> bool nodiscard noexcept
Check if the dataset contains a sequence element with the given tag.
Parameters
tag The DICOM tag to check
Returns
true if an element with this tag exists and is a sequence (VR = SQ)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 56 of file dicom_dataset.cpp.
{
    const auto* elem = get(tag);
    return elem != nullptr && elem->is_sequence();
}
insert()
void kcenon::pacs::core::dicom_dataset::insert (dicom_element element)
Insert or replace an element in the dataset.
Parameters
element The element to insert (copied or moved)
If an element with the same tag already exists, it will be replaced. Use std::move() when passing the element to avoid unnecessary copies.
Examples
json_to_dcm/main.cpp, and xml_to_dcm/main.cpp.
Definition at line 282 of file dicom_dataset.cpp.
{
    elements_.insert_or_assign(element.tag(), std::move(element));
}
References elements_, and kcenon::pacs::core::dicom_element::tag().
Referenced by kcenon::pacs::integration_test::test_data_generator::add_multiframe_pixel_data(), kcenon::pacs::integration_test::test_data_generator::add_pixel_data(), copy_with_tags(), kcenon::pacs::encoding::explicit_vr_big_endian_codec::decode(), kcenon::pacs::encoding::explicit_vr_codec::decode(), kcenon::pacs::encoding::implicit_vr_codec::decode(), kcenon::pacs::core::dicom_file::decode_explicit_vr_be(), kcenon::pacs::core::dicom_file::decode_explicit_vr_le(), kcenon::pacs::core::dicom_file::decode_implicit_vr_le(), kcenon::pacs::integration::container_adapter::deserialize_dataset(), kcenon::pacs::integration_test::generate_ct_dataset(), kcenon::pacs::core::dicom_file::generate_meta_information(), kcenon::pacs::integration_test::generate_mr_dataset(), kcenon::pacs::integration_test::generate_xa_dataset(), kcenon::pacs::integration_test::test_data_generator::invalid(), merge(), merge(), kcenon::pacs::core::dicom_file::parse_meta_information(), kcenon::pacs::network::dimse::dimse_message::set_attribute_identifier_list(), kcenon::pacs::encoding::set_encoded_string(), set_numeric(), set_string(), and TEST_CASE().
merge() [1/2]
void kcenon::pacs::core::dicom_dataset::merge (const dicom_dataset & other)
Merge elements from another dataset.
Parameters
other The dataset to merge from
Elements from 'other' will overwrite existing elements with the same tag.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 362 of file dicom_dataset.cpp.
{
    for (const auto& [tag, element] : other) {
        insert(element);
    }
}
References insert().
merge() [2/2]
void kcenon::pacs::core::dicom_dataset::merge (dicom_dataset && other)
Merge elements from another dataset (move version)
Parameters
other The dataset to merge from (moved)
Definition at line 368 of file dicom_dataset.cpp.
{
    for (auto& [tag, element] : other.elements_) {
        insert(std::move(element));
    }
    other.clear();
}
References insert().
operator=() [1/2]
auto kcenon::pacs::core::dicom_dataset::operator= (const dicom_dataset &) -> dicom_dataset &=default default
Copy assignment.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
operator=() [2/2]
auto kcenon::pacs::core::dicom_dataset::operator= (dicom_dataset &&) -> dicom_dataset &=default default noexcept
Move assignment.
remove()
auto kcenon::pacs::core::dicom_dataset::remove (dicom_tag tag) -> bool
Remove an element from the dataset.
Parameters
tag The tag of the element to remove
Returns
true if an element was removed, false if not found
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h, and dcm_modify/main.cpp.
Definition at line 291 of file dicom_dataset.cpp.
{
    return elements_.erase(tag) > 0;
}
Referenced by kcenon::pacs::dcm_modify::anonymizer::anonymize(), kcenon::pacs::dcm_modify::anonymizer::anonymize_patient_info(), kcenon::pacs::integration_test::test_data_generator::invalid(), kcenon::pacs::dcm_modify::anonymizer::remove_additional_phi(), kcenon::pacs::dcm_modify::anonymizer::remove_private_tags(), and kcenon::pacs::network::dimse::dimse_message::update_command_group_length().
remove_private_block()
auto kcenon::pacs::core::dicom_dataset::remove_private_block (std::string_view creator_id, uint16_t group) -> size_t
Remove all private data elements and their creator for a given creator.
Removes both the Private Creator element and all associated data elements in the specified group.
Parameters
creator_id The Private Creator identification string
group The private group number (must be odd)
Returns
Number of elements removed (including the creator)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 199 of file dicom_dataset.cpp.
{
    size_t removed = 0;
    for (uint16_t slot = 0x0010; slot <= 0x00FF; ++slot) {
        const dicom_tag creator_tag{group, slot};
        const auto* creator_elem = get(creator_tag);
        if (creator_elem == nullptr) {
            continue;
        }
        auto str_result = creator_elem->as_string();
        if (str_result.is_err() || str_result.value() != creator_id) {
            continue;
        }
        // Found the creator — remove all data elements in its block
        const auto range = creator_tag.private_data_range();
        if (range) {
            const auto [first, last] = *range;
            auto it = elements_.lower_bound(first);
            while (it != elements_.end() && it->first <= last) {
                it = elements_.erase(it);
                ++removed;
            }
        }
        // Remove the creator element itself
        elements_.erase(creator_tag);
        ++removed;
        break;
    }
    return removed;
}
set_numeric()
template<typename T > requires std::is_arithmetic_v<T> void kcenon::pacs::core::dicom_dataset::set_numeric (dicom_tag tag, encoding::vr_type vr, T value)
Set a numeric value for the given tag.
Template Parameters
T The numeric type
Parameters
tag The DICOM tag
vr The value representation
value The numeric value
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 448 of file dicom_dataset.h.
{
    insert(dicom_element::from_numeric<T>(tag, vr, value));
}
References kcenon::pacs::core::dicom_element::from_numeric(), insert(), and vr.
Referenced by kcenon::pacs::integration_test::test_data_generator::add_image_pixel_module(), kcenon::pacs::network::dimse::dimse_message::dimse_message(), kcenon::pacs::integration_test::generate_ct_dataset(), kcenon::pacs::integration_test::generate_mr_dataset(), kcenon::pacs::integration_test::generate_xa_dataset(), kcenon::pacs::integration_test::test_data_generator::invalid(), kcenon::pacs::network::dimse::dimse_message::set_action_type_id(), kcenon::pacs::network::dimse::dimse_message::set_completed_subops(), kcenon::pacs::network::dimse::dimse_message::set_event_type_id(), kcenon::pacs::network::dimse::dimse_message::set_failed_subops(), kcenon::pacs::network::dimse::dimse_message::set_message_id_responded_to(), kcenon::pacs::network::dimse::dimse_message::set_priority(), kcenon::pacs::network::dimse::dimse_message::set_remaining_subops(), kcenon::pacs::network::dimse::dimse_message::set_status(), kcenon::pacs::network::dimse::dimse_message::set_warning_subops(), TEST_CASE(), kcenon::pacs::network::dimse::dimse_message::update_command_group_length(), and kcenon::pacs::network::dimse::dimse_message::update_data_set_type().
set_private_element()
auto kcenon::pacs::core::dicom_dataset::set_private_element (std::string_view creator_id, uint16_t group, uint8_t element_offset, encoding::vr_type vr, std::string_view value) -> std::optional<dicom_tag>
Insert a private data element with automatic creator management.
Automatically ensures the corresponding Private Creator element exists. If the creator already owns a block in the given group, reuses that block. Otherwise, allocates the next available slot.
Per DICOM PS3.5 §7.8.1, Private Creator elements are placed at (gggg,00xx) and data elements at (gggg,xxyy).
Parameters
creator_id Private Creator identification (e.g. "SIEMENS CSA HEADER")
group Odd group number (e.g. 0x0009)
element_offset Offset within the block (0x00-0xFF)
vr Value Representation for the data element
value The element value
Returns
The actual tag assigned, or nullopt if allocation failed
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 145 of file dicom_dataset.cpp.
{
    // Group must be odd and > 0x0008 for private tags
    if ((group & 1) == 0 || group <= 0x0008) {
        return std::nullopt;
    }
    // Find existing block for this creator, or allocate a new slot
    uint16_t block_number = 0;
    bool found = false;
    for (uint16_t slot = 0x0010; slot <= 0x00FF; ++slot) {
        const dicom_tag creator_tag{group, slot};
        const auto* creator_elem = get(creator_tag);
        if (creator_elem == nullptr) {
            // Empty slot — allocate if we haven't found a match yet
            if (!found) {
                block_number = slot;
                found = true;
            }
            continue;
        }
        auto str_result = creator_elem->as_string();
        if (str_result.is_ok() && str_result.value() == creator_id) {
            // Creator already owns this slot
            block_number = slot;
            found = true;
            break;
        }
    }
    if (!found) {
        return std::nullopt;  // No available slots
    }
    // Ensure the Private Creator element exists
    const dicom_tag creator_tag{group, block_number};
    if (get(creator_tag) == nullptr) {
        set_string(creator_tag, encoding::vr_type::LO, creator_id);
    }
    // Place the data element at (group, block_number << 8 | element_offset)
    const auto data_element_num = static_cast<uint16_t>(
        (block_number << 8) | element_offset);
    const dicom_tag data_tag{group, data_element_num};
    set_string(data_tag, vr, value);
    return data_tag;
}
References kcenon::pacs::encoding::LO, and vr.
set_string()
void kcenon::pacs::core::dicom_dataset::set_string (dicom_tag tag, encoding::vr_type vr, std::string_view value)
Set a string value for the given tag.
Parameters
tag The DICOM tag
vr The value representation
value The string value
Creates a new element or updates an existing one.
Examples
/home/runner/work/pacs_system/pacs_system/examples/query_scu/query_builder.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h, and dcm_modify/main.cpp.
Definition at line 286 of file dicom_dataset.cpp.
{
    insert(dicom_element::from_string(tag, vr, value));
}
References kcenon::pacs::core::dicom_element::from_string(), insert(), and vr.
Referenced by kcenon::pacs::integration_test::test_data_generator::add_image_pixel_module(), query_scu::query_builder::add_instance_keys(), kcenon::pacs::integration_test::test_data_generator::add_multiframe_pixel_data(), query_scu::query_builder::add_patient_keys(), kcenon::pacs::integration_test::test_data_generator::add_patient_module(), query_scu::query_builder::add_series_keys(), kcenon::pacs::integration_test::test_data_generator::add_series_module(), query_scu::query_builder::add_study_keys(), kcenon::pacs::integration_test::test_data_generator::add_study_module(), kcenon::pacs::dcm_modify::anonymizer::anonymize_patient_info(), kcenon::pacs::dcm_modify::anonymizer::anonymize_uids(), kcenon::pacs::services::pir::patient_reconciliation_service::apply_demographics(), kcenon::pacs::services::storage_commitment_scu::build_action_dataset(), kcenon::pacs::services::storage_commitment_scp::build_event_report_dataset(), kcenon::pacs::services::xds::imaging_document_source::build_evidence_sequence(), kcenon::pacs::ai::assessment_creator::build_referenced_sop_sequence(), kcenon::pacs::ai::assessment_creator::build_sr_content(), kcenon::pacs::services::print_scp::create_film_box(), kcenon::pacs::services::print_scu::create_film_box(), kcenon::pacs::services::print_scu::create_film_session(), kcenon::pacs::services::xds::imaging_document_source::create_kos_document(), kcenon::pacs::integration_test::test_data_generator::ct(), kcenon::pacs::integration_test::test_data_generator::enhanced_ct(), kcenon::pacs::integration_test::test_data_generator::enhanced_mr(), kcenon::pacs::client::job_manager::impl::execute_prefetch_job(), kcenon::pacs::client::job_manager::impl::execute_query_job(), kcenon::pacs::client::job_manager::impl::execute_sync_job(), kcenon::pacs::integration_test::generate_ct_dataset(), kcenon::pacs::core::dicom_file::generate_meta_information(), kcenon::pacs::integration_test::generate_mr_dataset(), kcenon::pacs::integration_test::generate_worklist_item(), kcenon::pacs::integration_test::generate_xa_dataset(), kcenon::pacs::services::print_scp::handle_n_get(), kcenon::pacs::services::ups_push_scp::handle_n_get(), kcenon::pacs::example::pacs_server_app::handle_query(), kcenon::pacs::example::pacs_server_app::handle_worklist_query(), kcenon::pacs::integration_test::test_data_generator::invalid(), kcenon::pacs::integration_test::test_data_generator::large(), kcenon::pacs::integration_test::test_data_generator::mr(), kcenon::pacs::services::ups_watch_scp::notify_cancel_requested(), kcenon::pacs::services::ups_watch_scp::notify_progress(), kcenon::pacs::services::ups_watch_scp::notify_state_change(), kcenon::pacs::integration_test::test_data_generator::patient_journey(), kcenon::pacs::client::sync_manager::impl::query_remote_studies(), kcenon::pacs::network::dimse::dimse_message::set_affected_sop_class_uid(), kcenon::pacs::network::dimse::dimse_message::set_affected_sop_instance_uid(), kcenon::pacs::services::print_scu::set_image_box(), kcenon::pacs::network::dimse::dimse_message::set_requested_sop_class_uid(), kcenon::pacs::network::dimse::dimse_message::set_requested_sop_instance_uid(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), kcenon::pacs::integration_test::test_data_generator::unicode(), kcenon::pacs::integration_test::test_data_generator::us(), kcenon::pacs::integration_test::test_data_generator::us_cine(), kcenon::pacs::integration_test::test_data_generator::with_private_tags(), kcenon::pacs::integration_test::test_data_generator::worklist(), kcenon::pacs::integration_test::test_data_generator::xa(), and kcenon::pacs::integration_test::test_data_generator::xa_cine().
size()
auto kcenon::pacs::core::dicom_dataset::size () const -> size_t nodiscard noexcept
Get the number of elements in the dataset.
Returns
The element count
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h, and module_example/main.cpp.
Definition at line 331 of file dicom_dataset.cpp.
{
    return elements_.size();
}
References elements_.
Referenced by kcenon::pacs::services::storage_scu::store_impl().
validate_private_tags()
auto kcenon::pacs::core::dicom_dataset::validate_private_tags () const -> std::vector<dicom_tag> nodiscard
Validate private tag relationships in this dataset.
Checks that every private data element has a corresponding Private Creator element and returns tags that are missing their creator.
Returns
Vector of private data element tags missing their Private Creator
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 262 of file dicom_dataset.cpp.
{
    std::vector<dicom_tag> missing_creators;
    for (const auto& [tag, elem] : elements_) {
        if (!tag.is_private_data()) {
            continue;
        }
        const auto creator_tag = tag.private_creator_tag();
        if (!creator_tag || !contains(*creator_tag)) {
            missing_creators.push_back(tag);
        }
    }
    return missing_creators;
}
References contains(), and elements_.
Member Data Documentation
elements_
storage_type kcenon::pacs::core::dicom_dataset::elements_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h.
Definition at line 424 of file dicom_dataset.h.
Referenced by begin(), begin(), cbegin(), cend(), clear(), empty(), end(), end(), insert(), size(), and validate_private_tags().
The documentation for this class was generated from the following files:
include/kcenon/pacs/core/dicom_dataset.h
src/core/dicom_dataset.cpp