PACS System: kcenon::pacs::services::validation::nm_iod_validator Class Reference
kcenon::pacs::services::validation::nm_iod_validator Class Reference
#include <nm_iod_validator.hpp>
Public Member Functions
nm_iod_validator ()=default
Construct validator with default options.
nm_iod_validator (const nm_validation_options &options)
Construct validator with custom options.
validation_result validate (const core::dicom_dataset &dataset) const
Validate a DICOM dataset against NM IOD.
validation_result validate_multiframe (const core::dicom_dataset &dataset) const
Validate a multi-frame NM dataset.
bool quick_check (const core::dicom_dataset &dataset) const
Quick check if dataset has minimum required attributes.
const nm_validation_options & options () const noexcept
Get the validation options.
void set_options (const nm_validation_options &options)
Set validation options.
Private Member Functions
void validate_patient_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_study_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_series_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_nm_series_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_nm_image_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_nm_isotope_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_nm_detector_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_nm_tomo_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_nm_gated_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_image_pixel_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_multiframe_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_sop_common_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_energy_window_info (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_radiopharmaceutical_info (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_type1_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_type2_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_modality (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_pixel_data_consistency (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
Private Attributes
nm_validation_options options_
Detailed Description
Definition at line 138 of file nm_iod_validator.hpp.
Constructor & Destructor Documentation
nm_iod_validator() [1/2]
kcenon::pacs::services::validation::nm_iod_validator::nm_iod_validator () default
Construct validator with default options.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
nm_iod_validator() [2/2]
kcenon::pacs::services::validation::nm_iod_validator::nm_iod_validator (const nm_validation_options & options) explicit
Construct validator with custom options.
Parameters
options Validation options
Definition at line 81 of file nm_iod_validator.cpp.
    : options_(options) {}
Member Function Documentation
check_modality()
void kcenon::pacs::services::validation::nm_iod_validator::check_modality (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 620 of file nm_iod_validator.cpp.
{
    if (!dataset.contains(tags::modality)) {
        return;  // Already reported as Type 1 missing
    }
    auto modality = dataset.get_string(tags::modality);
    if (modality != "NM") {
        findings.push_back({
            validation_severity::error,
            tags::modality,
            "Modality must be 'NM' for nuclear medicine images, found: " + modality,
            "NM-ERR-002"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), and kcenon::pacs::core::tags::modality.
Referenced by validate_general_series_module().
check_pixel_data_consistency()
void kcenon::pacs::services::validation::nm_iod_validator::check_pixel_data_consistency (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 639 of file nm_iod_validator.cpp.
{
    // Check BitsStored <= BitsAllocated
    auto bits_allocated = dataset.get_numeric<uint16_t>(tags::bits_allocated);
    auto bits_stored = dataset.get_numeric<uint16_t>(tags::bits_stored);
    auto high_bit = dataset.get_numeric<uint16_t>(tags::high_bit);
    if (bits_allocated && bits_stored) {
        if (*bits_stored > *bits_allocated) {
            findings.push_back({
                validation_severity::error,
                tags::bits_stored,
                "BitsStored (" + std::to_string(*bits_stored) +
                ") exceeds BitsAllocated (" + std::to_string(*bits_allocated) + ")",
                "NM-ERR-003"
            });
        }
    }
    // Check HighBit == BitsStored - 1
    if (bits_stored && high_bit) {
        if (*high_bit != *bits_stored - 1) {
            findings.push_back({
                validation_severity::warning,
                tags::high_bit,
                "HighBit (" + std::to_string(*high_bit) +
                ") should typically be BitsStored - 1 (" +
                std::to_string(*bits_stored - 1) + ")",
                "NM-WARN-009"
            });
        }
    }
    // Check photometric interpretation is valid for NM
    if (dataset.contains(tags::photometric_interpretation)) {
        auto photometric = dataset.get_string(tags::photometric_interpretation);
        if (!sop_classes::is_valid_nm_photometric(photometric)) {
            findings.push_back({
                validation_severity::warning,
                tags::photometric_interpretation,
                "Unusual photometric interpretation for NM: " + photometric +
                " (expected MONOCHROME2 or PALETTE COLOR)",
                "NM-WARN-010"
            });
        }
    }
    // NM images should be grayscale (SamplesPerPixel = 1)
    auto samples = dataset.get_numeric<uint16_t>(tags::samples_per_pixel);
    if (samples && *samples != 1) {
        findings.push_back({
            validation_severity::warning,
            tags::samples_per_pixel,
            "NM images should have SamplesPerPixel = 1, found: " +
            std::to_string(*samples),
            "NM-WARN-011"
        });
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_numeric(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::services::sop_classes::is_valid_nm_photometric(), kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::samples_per_pixel, and kcenon::pacs::services::validation::warning.
Referenced by validate_image_pixel_module().
check_type1_attribute()
void kcenon::pacs::services::validation::nm_iod_validator::check_type1_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 573 of file nm_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::error,
            tag,
            std::string("Type 1 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "NM-TYPE1-MISSING"
        });
    } else {
        // Type 1 must have a value (cannot be empty)
        auto value = dataset.get_string(tag);
        if (value.empty()) {
            findings.push_back({
                validation_severity::error,
                tag,
                std::string("Type 1 attribute has empty value: ") +
                std::string(name) + " (" + tag.to_string() + ")",
                "NM-TYPE1-EMPTY"
            });
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), name, and kcenon::pacs::core::dicom_tag::to_string().
Referenced by validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_multiframe_module(), validate_nm_image_module(), validate_nm_series_module(), and validate_sop_common_module().
check_type2_attribute()
void kcenon::pacs::services::validation::nm_iod_validator::check_type2_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 602 of file nm_iod_validator.cpp.
{
    // Type 2 must be present but can be empty
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::warning,
            tag,
            std::string("Type 2 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "NM-TYPE2-MISSING"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), name, kcenon::pacs::core::dicom_tag::to_string(), and kcenon::pacs::services::validation::warning.
Referenced by validate_general_series_module(), validate_general_study_module(), validate_nm_detector_module(), validate_nm_gated_module(), validate_nm_isotope_module(), validate_nm_tomo_module(), and validate_patient_module().
options()
const nm_validation_options & kcenon::pacs::services::validation::nm_iod_validator::options () const noexcept
Get the validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 191 of file nm_iod_validator.cpp.
{
    return options_;
}
References options_.
Referenced by set_options().
quick_check()
bool kcenon::pacs::services::validation::nm_iod_validator::quick_check (const core::dicom_dataset & dataset) const
Quick check if dataset has minimum required attributes.
Faster than full validation - only checks Type 1 attributes.
Parameters
dataset The dataset to check
Returns
true if all Type 1 attributes are present
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 159 of file nm_iod_validator.cpp.
{
    // Check only Type 1 required attributes for quick validation
    // General Study Module Type 1
    if (!dataset.contains(tags::study_instance_uid)) return false;
    // General Series Module Type 1
    if (!dataset.contains(tags::modality)) return false;
    if (!dataset.contains(tags::series_instance_uid)) return false;
    // Check modality is NM
    auto modality = dataset.get_string(tags::modality);
    if (modality != "NM") return false;
    // Image Pixel Module Type 1
    if (!dataset.contains(tags::samples_per_pixel)) return false;
    if (!dataset.contains(tags::photometric_interpretation)) return false;
    if (!dataset.contains(tags::rows)) return false;
    if (!dataset.contains(tags::columns)) return false;
    if (!dataset.contains(tags::bits_allocated)) return false;
    if (!dataset.contains(tags::bits_stored)) return false;
    if (!dataset.contains(tags::high_bit)) return false;
    if (!dataset.contains(tags::pixel_representation)) return false;
    if (!dataset.contains(tags::pixel_data)) return false;
    // SOP Common Module Type 1
    if (!dataset.contains(tags::sop_class_uid)) return false;
    if (!dataset.contains(tags::sop_instance_uid)) return false;
    return true;
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::tags::columns, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, and kcenon::pacs::core::tags::study_instance_uid.
Referenced by kcenon::pacs::services::validation::is_valid_nm_dataset().
set_options()
void kcenon::pacs::services::validation::nm_iod_validator::set_options (const nm_validation_options & options)
Set validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 195 of file nm_iod_validator.cpp.
{
    options_ = options;
}
References options(), and options_.
validate()
validation_result kcenon::pacs::services::validation::nm_iod_validator::validate (const core::dicom_dataset & dataset) const
Validate a DICOM dataset against NM IOD.
Parameters
dataset The dataset to validate
Returns
Validation result with all findings
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 84 of file nm_iod_validator.cpp.
{
    validation_result result;
    result.is_valid = true;
    // Validate mandatory modules
    if (options_.check_type1 || options_.check_type2) {
        validate_patient_module(dataset, result.findings);
        validate_general_study_module(dataset, result.findings);
        validate_general_series_module(dataset, result.findings);
        validate_nm_series_module(dataset, result.findings);
        validate_nm_image_module(dataset, result.findings);
        validate_sop_common_module(dataset, result.findings);
    }
    if (options_.validate_pixel_data) {
        validate_image_pixel_module(dataset, result.findings);
    }
    // NM-specific validation
    if (options_.validate_nm_specific) {
        if (options_.validate_energy_windows) {
            validate_energy_window_info(dataset, result.findings);
        }
        if (options_.validate_isotope) {
            validate_nm_isotope_module(dataset, result.findings);
            validate_radiopharmaceutical_info(dataset, result.findings);
        }
        validate_nm_detector_module(dataset, result.findings);
    }
    // Check for errors
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
        if (options_.strict_mode && finding.severity == validation_severity::warning) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References kcenon::pacs::services::validation::nm_validation_options::check_type1, kcenon::pacs::services::validation::nm_validation_options::check_type2, kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::services::validation::validation_result::is_valid, options_, kcenon::pacs::services::validation::nm_validation_options::strict_mode, validate_energy_window_info(), kcenon::pacs::services::validation::nm_validation_options::validate_energy_windows, validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), kcenon::pacs::services::validation::nm_validation_options::validate_isotope, validate_nm_detector_module(), validate_nm_image_module(), validate_nm_isotope_module(), validate_nm_series_module(), kcenon::pacs::services::validation::nm_validation_options::validate_nm_specific, validate_patient_module(), kcenon::pacs::services::validation::nm_validation_options::validate_pixel_data, validate_radiopharmaceutical_info(), validate_sop_common_module(), and kcenon::pacs::services::validation::warning.
Referenced by validate_multiframe(), and kcenon::pacs::services::validation::validate_nm_iod().
validate_energy_window_info()
void kcenon::pacs::services::validation::nm_iod_validator::validate_energy_window_info (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 510 of file nm_iod_validator.cpp.
{
    // Energy Window Information Sequence is Type 1
    if (!dataset.contains(nm_tags::energy_window_info_sequence)) {
        // Already reported as Type 1 missing
        return;
    }
    // Energy Window Range Sequence should be present
    if (!dataset.contains(nm_tags::energy_window_range_sequence)) {
        findings.push_back({
            validation_severity::warning,
            nm_tags::energy_window_range_sequence,
            "EnergyWindowRangeSequence not present - energy window details missing",
            "NM-WARN-008"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::nm_tags::energy_window_info_sequence, kcenon::pacs::services::validation::nm_tags::energy_window_range_sequence, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_general_series_module()
void kcenon::pacs::services::validation::nm_iod_validator::validate_general_series_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 235 of file nm_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::modality, "Modality", findings);
        check_type1_attribute(dataset, tags::series_instance_uid, "SeriesInstanceUID", findings);
        // Special check: Modality must be "NM"
        check_modality(dataset, findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::series_number, "SeriesNumber", findings);
    }
}
References check_modality(), kcenon::pacs::services::validation::nm_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::nm_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::tags::modality, options_, kcenon::pacs::core::tags::series_instance_uid, and kcenon::pacs::core::tags::series_number.
Referenced by validate().
validate_general_study_module()
void kcenon::pacs::services::validation::nm_iod_validator::validate_general_study_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 216 of file nm_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::study_instance_uid, "StudyInstanceUID", findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::study_date, "StudyDate", findings);
        check_type2_attribute(dataset, tags::study_time, "StudyTime", findings);
        check_type2_attribute(dataset, tags::referring_physician_name, "ReferringPhysicianName", findings);
        check_type2_attribute(dataset, tags::study_id, "StudyID", findings);
        check_type2_attribute(dataset, tags::accession_number, "AccessionNumber", findings);
    }
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::services::validation::nm_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::nm_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::core::tags::study_time.
Referenced by validate().
validate_image_pixel_module()
void kcenon::pacs::services::validation::nm_iod_validator::validate_image_pixel_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 433 of file nm_iod_validator.cpp.
{
    // Type 1 attributes
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::samples_per_pixel, "SamplesPerPixel", findings);
        check_type1_attribute(dataset, tags::photometric_interpretation,
                              "PhotometricInterpretation", findings);
        check_type1_attribute(dataset, tags::rows, "Rows", findings);
        check_type1_attribute(dataset, tags::columns, "Columns", findings);
        check_type1_attribute(dataset, tags::bits_allocated, "BitsAllocated", findings);
        check_type1_attribute(dataset, tags::bits_stored, "BitsStored", findings);
        check_type1_attribute(dataset, tags::high_bit, "HighBit", findings);
        check_type1_attribute(dataset, tags::pixel_representation, "PixelRepresentation", findings);
        check_type1_attribute(dataset, tags::pixel_data, "PixelData", findings);
    }
    // Validate pixel data consistency
    if (options_.validate_pixel_data) {
        check_pixel_data_consistency(dataset, findings);
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, check_pixel_data_consistency(), kcenon::pacs::services::validation::nm_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::tags::columns, kcenon::pacs::core::tags::high_bit, options_, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, and kcenon::pacs::services::validation::nm_validation_options::validate_pixel_data.
Referenced by validate().
validate_multiframe()
validation_result kcenon::pacs::services::validation::nm_iod_validator::validate_multiframe (const core::dicom_dataset & dataset) const
Validate a multi-frame NM dataset.
Performs additional validation for SPECT, dynamic, and gated acquisitions.
Parameters
dataset The dataset to validate
Returns
Validation result with all findings
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 130 of file nm_iod_validator.cpp.
{
    // First do standard validation
    auto result = validate(dataset);
    // Then add multi-frame specific validation
    validate_multiframe_module(dataset, result.findings);
    // Validate SPECT-specific if applicable
    if (dataset.contains(nm_tags::type_of_data)) {
        auto type = dataset.get_string(nm_tags::type_of_data);
        if (type.find("TOMO") != std::string::npos) {
            validate_nm_tomo_module(dataset, result.findings);
        }
        if (type.find("GATED") != std::string::npos) {
            validate_nm_gated_module(dataset, result.findings);
        }
    }
    // Re-check validity after multi-frame validation
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::nm_tags::type_of_data, validate(), validate_multiframe_module(), validate_nm_gated_module(), and validate_nm_tomo_module().
validate_multiframe_module()
void kcenon::pacs::services::validation::nm_iod_validator::validate_multiframe_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 457 of file nm_iod_validator.cpp.
{
    // NumberOfFrames should be present for multi-frame NM
    if (options_.check_type1) {
        check_type1_attribute(dataset, nm_tags::number_of_frames, "NumberOfFrames", findings);
    }
    // FrameIncrementPointer is Type 1C for multi-frame
    if (options_.check_conditional) {
        auto num_frames = dataset.get_numeric<int32_t>(nm_tags::number_of_frames);
        if (num_frames && *num_frames > 1) {
            if (!dataset.contains(nm_tags::frame_increment_pointer)) {
                findings.push_back({
                    validation_severity::warning,
                    nm_tags::frame_increment_pointer,
                    "FrameIncrementPointer recommended for multi-frame NM images",
                    "NM-WARN-007"
                });
            }
        }
    }
}
References kcenon::pacs::services::validation::nm_validation_options::check_conditional, kcenon::pacs::services::validation::nm_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::nm_tags::frame_increment_pointer, kcenon::pacs::core::dicom_dataset::get_numeric(), kcenon::pacs::services::validation::nm_tags::number_of_frames, options_, and kcenon::pacs::services::validation::warning.
Referenced by validate_multiframe().
validate_nm_detector_module()
void kcenon::pacs::services::validation::nm_iod_validator::validate_nm_detector_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 326 of file nm_iod_validator.cpp.
{
    // Detector Information Sequence is Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, nm_tags::detector_info_sequence,
                              "DetectorInformationSequence", findings);
    }
    // Collimator Type is informational but important
    if (!dataset.contains(nm_tags::collimator_type)) {
        findings.push_back({
            validation_severity::info,
            nm_tags::collimator_type,
            "CollimatorType not specified - helps with interpretation",
            "NM-INFO-002"
        });
    } else {
        auto collimator = dataset.get_string(nm_tags::collimator_type);
        // Validate collimator type
        if (collimator != "PARA" && collimator != "FANB" && collimator != "CONE" &&
            collimator != "PINH" && collimator != "DIVG" && collimator != "NONE") {
            findings.push_back({
                validation_severity::warning,
                nm_tags::collimator_type,
                "Non-standard CollimatorType: " + collimator,
                "NM-WARN-002"
            });
        }
    }
}
References kcenon::pacs::services::validation::nm_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::services::validation::nm_tags::collimator_type, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::nm_tags::detector_info_sequence, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::info, options_, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_nm_gated_module()
void kcenon::pacs::services::validation::nm_iod_validator::validate_nm_gated_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 402 of file nm_iod_validator.cpp.
{
    // Gated Information Sequence is Type 2 for gated acquisitions
    if (options_.check_type2) {
        check_type2_attribute(dataset, nm_tags::gated_info_sequence,
                              "GatedInformationSequence", findings);
    }
    // Trigger Source for gated acquisition
    if (!dataset.contains(nm_tags::trigger_source_or_type)) {
        findings.push_back({
            validation_severity::info,
            nm_tags::trigger_source_or_type,
            "TriggerSourceOrType not specified for gated acquisition",
            "NM-INFO-003"
        });
    }
    // Number of Time Slots is important for gated analysis
    if (!dataset.contains(nm_tags::number_of_time_slots)) {
        findings.push_back({
            validation_severity::warning,
            nm_tags::number_of_time_slots,
            "NumberOfTimeSlots not specified for gated acquisition",
            "NM-WARN-006"
        });
    }
}
References kcenon::pacs::services::validation::nm_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::nm_tags::gated_info_sequence, kcenon::pacs::services::validation::info, kcenon::pacs::services::validation::nm_tags::number_of_time_slots, options_, kcenon::pacs::services::validation::nm_tags::trigger_source_or_type, and kcenon::pacs::services::validation::warning.
Referenced by validate_multiframe().
validate_nm_image_module()
void kcenon::pacs::services::validation::nm_iod_validator::validate_nm_image_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 280 of file nm_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, nm_tags::image_type, "ImageType", findings);
    }
    // NumberOfFrames is Type 1 for NM (often multi-frame)
    if (options_.check_type1) {
        check_type1_attribute(dataset, nm_tags::number_of_frames, "NumberOfFrames", findings);
    }
    // Validate ImageType format
    if (dataset.contains(nm_tags::image_type)) {
        auto image_type = dataset.get_string(nm_tags::image_type);
        if (image_type.find('\\') == std::string::npos) {
            findings.push_back({
                validation_severity::info,
                nm_tags::image_type,
                "ImageType should contain backslash separators",
                "NM-INFO-001"
            });
        }
    }
}
References kcenon::pacs::services::validation::nm_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::nm_tags::image_type, kcenon::pacs::services::validation::info, kcenon::pacs::services::validation::nm_tags::number_of_frames, and options_.
Referenced by validate().
validate_nm_isotope_module()
void kcenon::pacs::services::validation::nm_iod_validator::validate_nm_isotope_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 308 of file nm_iod_validator.cpp.
{
    // Energy Window Information Sequence is Type 2 per DICOM standard
    // (Required, but may be empty)
    if (options_.check_type2) {
        check_type2_attribute(dataset, nm_tags::energy_window_info_sequence,
                              "EnergyWindowInformationSequence", findings);
    }
    // Radiopharmaceutical Information Sequence is Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, nm_tags::radiopharmaceutical_info_sequence,
                              "RadiopharmaceuticalInformationSequence", findings);
    }
}
References kcenon::pacs::services::validation::nm_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::services::validation::nm_tags::energy_window_info_sequence, options_, and kcenon::pacs::services::validation::nm_tags::radiopharmaceutical_info_sequence.
Referenced by validate().
validate_nm_series_module()
void kcenon::pacs::services::validation::nm_iod_validator::validate_nm_series_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 254 of file nm_iod_validator.cpp.
{
    // Type of Data is important for NM series classification
    if (options_.check_type1) {
        check_type1_attribute(dataset, nm_tags::type_of_data, "TypeOfData", findings);
    }
    // Validate TypeOfData value
    if (dataset.contains(nm_tags::type_of_data)) {
        auto type = dataset.get_string(nm_tags::type_of_data);
        // Valid values: STATIC, DYNAMIC, GATED, WHOLE BODY, TOMO, GATED TOMO, RECON TOMO, RECON GATED TOMO
        if (type != "STATIC" && type != "DYNAMIC" && type != "GATED" &&
            type != "WHOLE BODY" && type != "TOMO" && type != "GATED TOMO" &&
            type != "RECON TOMO" && type != "RECON GATED TOMO") {
            findings.push_back({
                validation_severity::warning,
                nm_tags::type_of_data,
                "Unusual TypeOfData value for NM: " + type,
                "NM-WARN-001"
            });
        }
    }
}
References kcenon::pacs::services::validation::nm_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), options_, kcenon::pacs::services::validation::nm_tags::type_of_data, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_nm_tomo_module()
void kcenon::pacs::services::validation::nm_iod_validator::validate_nm_tomo_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 359 of file nm_iod_validator.cpp.
{
    // Rotation Information Sequence is Type 2 for SPECT
    if (options_.check_type2) {
        check_type2_attribute(dataset, nm_tags::rotation_info_sequence,
                              "RotationInformationSequence", findings);
    }
    // Start Angle and Scan Arc are important for SPECT reconstruction
    if (!dataset.contains(nm_tags::start_angle)) {
        findings.push_back({
            validation_severity::warning,
            nm_tags::start_angle,
            "StartAngle not specified for SPECT acquisition",
            "NM-WARN-003"
        });
    }
    if (!dataset.contains(nm_tags::scan_arc)) {
        findings.push_back({
            validation_severity::warning,
            nm_tags::scan_arc,
            "ScanArc not specified for SPECT acquisition",
            "NM-WARN-004"
        });
    }
    // Rotation Direction
    if (dataset.contains(nm_tags::rotation_direction)) {
        auto direction = dataset.get_string(nm_tags::rotation_direction);
        if (direction != "CW" && direction != "CC") {
            findings.push_back({
                validation_severity::warning,
                nm_tags::rotation_direction,
                "Invalid RotationDirection: " + direction + " (expected CW or CC)",
                "NM-WARN-005"
            });
        }
    }
}
References kcenon::pacs::services::validation::nm_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), options_, kcenon::pacs::services::validation::nm_tags::rotation_direction, kcenon::pacs::services::validation::nm_tags::rotation_info_sequence, kcenon::pacs::services::validation::nm_tags::scan_arc, kcenon::pacs::services::validation::nm_tags::start_angle, and kcenon::pacs::services::validation::warning.
Referenced by validate_multiframe().
validate_patient_module()
void kcenon::pacs::services::validation::nm_iod_validator::validate_patient_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 203 of file nm_iod_validator.cpp.
{
    // Patient Module - All attributes are Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::patient_name, "PatientName", findings);
        check_type2_attribute(dataset, tags::patient_id, "PatientID", findings);
        check_type2_attribute(dataset, tags::patient_birth_date, "PatientBirthDate", findings);
        check_type2_attribute(dataset, tags::patient_sex, "PatientSex", findings);
    }
}
References kcenon::pacs::services::validation::nm_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, and kcenon::pacs::core::tags::patient_sex.
Referenced by validate().
validate_radiopharmaceutical_info()
void kcenon::pacs::services::validation::nm_iod_validator::validate_radiopharmaceutical_info (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 531 of file nm_iod_validator.cpp.
{
    // If sequence is present, validate its contents
    if (dataset.contains(nm_tags::radiopharmaceutical_info_sequence)) {
        // Radionuclide Total Dose is important for quantitative analysis
        if (!dataset.contains(nm_tags::radionuclide_total_dose)) {
            findings.push_back({
                validation_severity::info,
                nm_tags::radionuclide_total_dose,
                "RadionuclideTotalDose not specified",
                "NM-INFO-004"
            });
        }
        // Radionuclide Half Life is important for decay correction
        if (!dataset.contains(nm_tags::radionuclide_half_life)) {
            findings.push_back({
                validation_severity::info,
                nm_tags::radionuclide_half_life,
                "RadionuclideHalfLife not specified",
                "NM-INFO-005"
            });
        }
        // Radiopharmaceutical Start Time for timing calculations
        if (!dataset.contains(nm_tags::radiopharmaceutical_start_time)) {
            findings.push_back({
                validation_severity::info,
                nm_tags::radiopharmaceutical_start_time,
                "RadiopharmaceuticalStartTime not specified",
                "NM-INFO-006"
            });
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::info, kcenon::pacs::services::validation::nm_tags::radionuclide_half_life, kcenon::pacs::services::validation::nm_tags::radionuclide_total_dose, kcenon::pacs::services::validation::nm_tags::radiopharmaceutical_info_sequence, and kcenon::pacs::services::validation::nm_tags::radiopharmaceutical_start_time.
Referenced by validate().
validate_sop_common_module()
void kcenon::pacs::services::validation::nm_iod_validator::validate_sop_common_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 482 of file nm_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::sop_class_uid, "SOPClassUID", findings);
        check_type1_attribute(dataset, tags::sop_instance_uid, "SOPInstanceUID", findings);
    }
    // Validate SOP Class UID is a NM storage class
    if (dataset.contains(tags::sop_class_uid)) {
        auto sop_class = dataset.get_string(tags::sop_class_uid);
        if (!sop_classes::is_nm_storage_sop_class(sop_class)) {
            findings.push_back({
                validation_severity::error,
                tags::sop_class_uid,
                "SOPClassUID is not a recognized NM Storage SOP Class: " + sop_class,
                "NM-ERR-001"
            });
        }
    }
}
References kcenon::pacs::services::validation::nm_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_nm_storage_sop_class(), options_, kcenon::pacs::core::tags::sop_class_uid, and kcenon::pacs::core::tags::sop_instance_uid.
Referenced by validate().
Member Data Documentation
options_
nm_validation_options kcenon::pacs::services::validation::nm_iod_validator::options_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/nm_iod_validator.hpp.
Definition at line 270 of file nm_iod_validator.hpp.
Referenced by options(), set_options(), validate(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_multiframe_module(), validate_nm_detector_module(), validate_nm_gated_module(), validate_nm_image_module(), validate_nm_isotope_module(), validate_nm_series_module(), validate_nm_tomo_module(), validate_patient_module(), and validate_sop_common_module().
The documentation for this class was generated from the following files:
include/pacs/services/validation/nm_iod_validator.hpp
src/services/validation/nm_iod_validator.cpp