PACS System: kcenon::pacs::services::mpps_scp Class Reference
kcenon::pacs::services::mpps_scp Class Reference final
#include <mpps_scp.h>
Public Member Functions
mpps_scp (std::shared_ptr< di::ILogger > logger=nullptr)
Construct MPPS SCP with optional logger.
~mpps_scp () override=default
void set_create_handler (mpps_create_handler handler)
Set the N-CREATE handler function.
void set_set_handler (mpps_set_handler handler)
Set the N-SET handler function.
std::vector< std::string > supported_sop_classes () const override
Get supported SOP Class UIDs.
network::Result< std::monostate > handle_message (network::association &assoc, uint8_t context_id, const network::dimse::dimse_message &request) override
Handle an incoming DIMSE message (N-CREATE-RQ or N-SET-RQ)
std::string_view service_name () const noexcept override
Get the service name.
size_t creates_processed () const noexcept
Get total number of N-CREATE requests processed.
size_t sets_processed () const noexcept
Get total number of N-SET requests processed.
size_t mpps_completed () const noexcept
Get number of MPPS completed successfully.
size_t mpps_discontinued () const noexcept
Get number of MPPS discontinued.
void reset_statistics () noexcept
Reset statistics counters.
Public Member Functions inherited from kcenon::pacs::services::scp_service
scp_service (std::shared_ptr< di::ILogger > logger=nullptr)
Construct SCP service with optional logger.
virtual ~scp_service ()=default
scp_service (const scp_service &)=delete
scp_service & operator= (const scp_service &)=delete
scp_service (scp_service &&)=default
scp_service & operator= (scp_service &&)=default
void set_logger (std::shared_ptr< di::ILogger > logger)
Set the logger instance.
const std::shared_ptr< di::ILogger > & logger () const noexcept
Get the current logger instance.
bool supports_sop_class (std::string_view sop_class_uid) const
Check if this service supports a specific SOP Class.
Private Member Functions
network::Result< std::monostate > handle_n_create (network::association &assoc, uint8_t context_id, const network::dimse::dimse_message &request)
Handle N-CREATE request.
network::Result< std::monostate > handle_n_set (network::association &assoc, uint8_t context_id, const network::dimse::dimse_message &request)
Handle N-SET request.
network::Result< std::monostate > send_n_create_response (network::association &assoc, uint8_t context_id, uint16_t message_id, const std::string &sop_instance_uid, network::dimse::status_code status)
Send N-CREATE response.
network::Result< std::monostate > send_n_set_response (network::association &assoc, uint8_t context_id, uint16_t message_id, const std::string &sop_instance_uid, network::dimse::status_code status)
Send N-SET response.
Private Attributes
mpps_create_handler create_handler_
mpps_set_handler set_handler_
std::atomic< size_t > creates_processed_ {0}
std::atomic< size_t > sets_processed_ {0}
std::atomic< size_t > mpps_completed_ {0}
std::atomic< size_t > mpps_discontinued_ {0}
Additional Inherited Members
Protected Attributes inherited from kcenon::pacs::services::scp_service
std::shared_ptr< di::ILogger > logger_
Logger instance for service logging.
Detailed Description
Definition at line 231 of file mpps_scp.h.
Constructor & Destructor Documentation
mpps_scp()
kcenon::pacs::services::mpps_scp::mpps_scp (std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct MPPS SCP with optional logger.
Parameters
logger Logger instance for service logging (nullptr uses null_logger)
Definition at line 23 of file mpps_scp.cpp.
    : scp_service(std::move(logger)) {}
~mpps_scp()
kcenon::pacs::services::mpps_scp::~mpps_scp () override default
Member Function Documentation
creates_processed()
size_t kcenon::pacs::services::mpps_scp::creates_processed () const nodiscard noexcept
Get total number of N-CREATE requests processed.
Returns
Number of MPPS instances created
Definition at line 77 of file mpps_scp.cpp.
{
    return creates_processed_.load();
}
References creates_processed_.
handle_message()
network::Result< std::monostate > kcenon::pacs::services::mpps_scp::handle_message (network::association & assoc, uint8_t context_id, const network::dimse::dimse_message & request) nodiscard override virtual
Handle an incoming DIMSE message (N-CREATE-RQ or N-SET-RQ)
Processes N-CREATE and N-SET requests for MPPS management.
Parameters
assoc The association on which the message was received
context_id The presentation context ID for the message
request The incoming N-CREATE-RQ or N-SET-RQ message
Returns
Success or error if the message cannot be processed
Implements kcenon::pacs::services::scp_service.
Definition at line 46 of file mpps_scp.cpp.
{
    using namespace network::dimse;
    // Route to appropriate handler based on command type
    switch (request.command()) {
        case command_field::n_create_rq:
            return handle_n_create(assoc, context_id, request);
        case command_field::n_set_rq:
            return handle_n_set(assoc, context_id, request);
        default:
            return kcenon::pacs::pacs_void_error(
                kcenon::pacs::error_codes::mpps_unexpected_command,
                "Unexpected command for MPPS SCP: " +
                std::string(to_string(request.command())));
    }
}
References kcenon::pacs::network::dimse::dimse_message::command(), handle_n_create(), handle_n_set(), kcenon::pacs::error_codes::mpps_unexpected_command, kcenon::pacs::pacs_void_error(), and kcenon::pacs::services::to_string().
handle_n_create()
network::Result< std::monostate > kcenon::pacs::services::mpps_scp::handle_n_create (network::association & assoc, uint8_t context_id, const network::dimse::dimse_message & request) nodiscard private
Handle N-CREATE request.
Creates a new MPPS instance with IN PROGRESS status.
Parameters
assoc The association
context_id The presentation context ID
request The N-CREATE-RQ message
Returns
Success or error
Definition at line 104 of file mpps_scp.cpp.
{
    using namespace network::dimse;
    // Verify we have a handler configured
    if (!create_handler_) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::mpps_handler_not_set,
            "No N-CREATE handler configured for MPPS SCP");
    }
    // Verify the SOP Class is MPPS
    auto sop_class_uid = request.affected_sop_class_uid();
    if (sop_class_uid != mpps_sop_class_uid) {
        return send_n_create_response(
            assoc, context_id, request.message_id(),
            "", status_refused_sop_class_not_supported);
    }
    // Get the SOP Instance UID from the request
    auto sop_instance_uid = request.affected_sop_instance_uid();
    if (sop_instance_uid.empty()) {
        return send_n_create_response(
            assoc, context_id, request.message_id(),
            "", status_error_missing_attribute);
    }
    // Verify we have a dataset
    if (!request.has_dataset()) {
        return send_n_create_response(
            assoc, context_id, request.message_id(),
            sop_instance_uid, status_error_cannot_understand);
    }
    const auto& dataset = request.dataset().value().get();
    // Build MPPS instance from request data
    mpps_instance instance;
    instance.sop_instance_uid = sop_instance_uid;
    instance.status = mpps_status::in_progress;
    instance.data = dataset;
    // Extract Performed Station AE Title if present
    if (dataset.contains(mpps_tags::performed_station_ae_title)) {
        instance.station_ae = dataset.get_string(mpps_tags::performed_station_ae_title);
    }
    // Validate initial status is IN PROGRESS
    if (dataset.contains(mpps_tags::performed_procedure_step_status)) {
        auto status_str = dataset.get_string(mpps_tags::performed_procedure_step_status);
        auto parsed_status = parse_mpps_status(status_str);
        if (!parsed_status.has_value() ||
            parsed_status.value() != mpps_status::in_progress) {
            // N-CREATE must have IN PROGRESS status
            return send_n_create_response(
                assoc, context_id, request.message_id(),
                sop_instance_uid, status_error_cannot_understand);
        }
    }
    // Call the handler to create the MPPS instance
    auto result = create_handler_(instance);
    if (result.is_err()) {
        return send_n_create_response(
            assoc, context_id, request.message_id(),
            sop_instance_uid, status_error_unable_to_process);
    }
    // Update statistics
    ++creates_processed_;
    // Send success response
    return send_n_create_response(
        assoc, context_id, request.message_id(),
        sop_instance_uid, status_success);
}
References kcenon::pacs::network::dimse::dimse_message::affected_sop_class_uid(), kcenon::pacs::network::dimse::dimse_message::affected_sop_instance_uid(), create_handler_, creates_processed_, kcenon::pacs::services::mpps_instance::data, kcenon::pacs::network::dimse::dimse_message::dataset(), kcenon::pacs::network::dimse::dimse_message::has_dataset(), kcenon::pacs::services::in_progress, kcenon::pacs::network::dimse::dimse_message::message_id(), kcenon::pacs::error_codes::mpps_handler_not_set, kcenon::pacs::services::mpps_sop_class_uid, kcenon::pacs::pacs_void_error(), kcenon::pacs::services::parse_mpps_status(), kcenon::pacs::services::mpps_tags::performed_procedure_step_status, kcenon::pacs::services::mpps_tags::performed_station_ae_title, send_n_create_response(), kcenon::pacs::services::mpps_instance::sop_instance_uid, kcenon::pacs::services::mpps_instance::station_ae, and kcenon::pacs::services::mpps_instance::status.
Referenced by handle_message().
handle_n_set()
network::Result< std::monostate > kcenon::pacs::services::mpps_scp::handle_n_set (network::association & assoc, uint8_t context_id, const network::dimse::dimse_message & request) nodiscard private
Handle N-SET request.
Updates an existing MPPS instance to COMPLETED or DISCONTINUED.
Parameters
assoc The association
context_id The presentation context ID
request The N-SET-RQ message
Returns
Success or error
Definition at line 189 of file mpps_scp.cpp.
{
    using namespace network::dimse;
    // Verify we have a handler configured
    if (!set_handler_) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::mpps_handler_not_set,
            "No N-SET handler configured for MPPS SCP");
    }
    // Verify the SOP Class is MPPS
    auto sop_class_uid = request.affected_sop_class_uid();
    if (sop_class_uid.empty()) {
        // For N-SET, use requested SOP class if affected is empty
        sop_class_uid = request.command_set().get_string(
            tag_requested_sop_class_uid);
    }
    if (sop_class_uid != mpps_sop_class_uid) {
        return send_n_set_response(
            assoc, context_id, request.message_id(),
            "", status_refused_sop_class_not_supported);
    }
    // Get the SOP Instance UID (from Requested SOP Instance UID for N-SET)
    auto sop_instance_uid = request.command_set().get_string(
        tag_requested_sop_instance_uid);
    if (sop_instance_uid.empty()) {
        // Try affected SOP instance UID as fallback
        sop_instance_uid = request.affected_sop_instance_uid();
    }
    if (sop_instance_uid.empty()) {
        return send_n_set_response(
            assoc, context_id, request.message_id(),
            "", status_error_missing_attribute);
    }
    // Verify we have a dataset with modifications
    if (!request.has_dataset()) {
        return send_n_set_response(
            assoc, context_id, request.message_id(),
            sop_instance_uid, status_error_cannot_understand);
    }
    const auto& dataset = request.dataset().value().get();
    // Extract and validate the new status
    if (!dataset.contains(mpps_tags::performed_procedure_step_status)) {
        return send_n_set_response(
            assoc, context_id, request.message_id(),
            sop_instance_uid, status_error_missing_attribute);
    }
    auto status_str = dataset.get_string(mpps_tags::performed_procedure_step_status);
    auto new_status = parse_mpps_status(status_str);
    if (!new_status.has_value()) {
        return send_n_set_response(
            assoc, context_id, request.message_id(),
            sop_instance_uid, status_error_cannot_understand);
    }
    // Validate status transition (must be to COMPLETED or DISCONTINUED)
    if (new_status.value() == mpps_status::in_progress) {
        // Cannot set back to IN PROGRESS
        return send_n_set_response(
            assoc, context_id, request.message_id(),
            sop_instance_uid, status_error_cannot_understand);
    }
    // Call the handler to update the MPPS instance
    auto result = set_handler_(sop_instance_uid, dataset, new_status.value());
    if (result.is_err()) {
        return send_n_set_response(
            assoc, context_id, request.message_id(),
            sop_instance_uid, status_error_unable_to_process);
    }
    // Update statistics
    ++sets_processed_;
    if (new_status.value() == mpps_status::completed) {
        ++mpps_completed_;
    } else if (new_status.value() == mpps_status::discontinued) {
        ++mpps_discontinued_;
    }
    // Send success response
    return send_n_set_response(
        assoc, context_id, request.message_id(),
        sop_instance_uid, status_success);
}
References kcenon::pacs::network::dimse::dimse_message::affected_sop_class_uid(), kcenon::pacs::network::dimse::dimse_message::affected_sop_instance_uid(), kcenon::pacs::network::dimse::dimse_message::command_set(), kcenon::pacs::services::completed, kcenon::pacs::network::dimse::dimse_message::dataset(), kcenon::pacs::services::discontinued, kcenon::pacs::network::dimse::dimse_message::has_dataset(), kcenon::pacs::services::in_progress, kcenon::pacs::network::dimse::dimse_message::message_id(), mpps_completed_, mpps_discontinued_, kcenon::pacs::error_codes::mpps_handler_not_set, kcenon::pacs::services::mpps_sop_class_uid, kcenon::pacs::pacs_void_error(), kcenon::pacs::services::parse_mpps_status(), kcenon::pacs::services::mpps_tags::performed_procedure_step_status, send_n_set_response(), set_handler_, and sets_processed_.
Referenced by handle_message().
mpps_completed()
size_t kcenon::pacs::services::mpps_scp::mpps_completed () const nodiscard noexcept
Get number of MPPS completed successfully.
Returns
Number of MPPS with COMPLETED status
Definition at line 85 of file mpps_scp.cpp.
{
    return mpps_completed_.load();
}
References mpps_completed_.
mpps_discontinued()
size_t kcenon::pacs::services::mpps_scp::mpps_discontinued () const nodiscard noexcept
Get number of MPPS discontinued.
Returns
Number of MPPS with DISCONTINUED status
Definition at line 89 of file mpps_scp.cpp.
{
    return mpps_discontinued_.load();
}
References mpps_discontinued_.
reset_statistics()
void kcenon::pacs::services::mpps_scp::reset_statistics () noexcept
Reset statistics counters.
Definition at line 93 of file mpps_scp.cpp.
{
    creates_processed_ = 0;
    sets_processed_ = 0;
    mpps_completed_ = 0;
    mpps_discontinued_ = 0;
}
References creates_processed_, mpps_completed_, mpps_discontinued_, and sets_processed_.
send_n_create_response()
network::Result< std::monostate > kcenon::pacs::services::mpps_scp::send_n_create_response (network::association & assoc, uint8_t context_id, uint16_t message_id, const std::string & sop_instance_uid, network::dimse::status_code status) nodiscard private
Send N-CREATE response.
Parameters
assoc The association
context_id The presentation context ID
message_id The original request message ID
sop_instance_uid The SOP Instance UID
status The response status code
Returns
Success or error
Definition at line 291 of file mpps_scp.cpp.
{
    using namespace network::dimse;
    // Create N-CREATE response message
    dimse_message response{command_field::n_create_rsp, 0};
    response.set_message_id_responded_to(message_id);
    response.set_affected_sop_class_uid(mpps_sop_class_uid);
    response.set_status(status);
    if (!sop_instance_uid.empty()) {
        response.set_affected_sop_instance_uid(sop_instance_uid);
    }
    // Send the response
    return assoc.send_dimse(context_id, response);
}
References kcenon::pacs::services::mpps_sop_class_uid, and kcenon::pacs::network::association::send_dimse().
Referenced by handle_n_create().
send_n_set_response()
network::Result< std::monostate > kcenon::pacs::services::mpps_scp::send_n_set_response (network::association & assoc, uint8_t context_id, uint16_t message_id, const std::string & sop_instance_uid, network::dimse::status_code status) nodiscard private
Send N-SET response.
Parameters
assoc The association
context_id The presentation context ID
message_id The original request message ID
sop_instance_uid The SOP Instance UID
status The response status code
Returns
Success or error
Definition at line 314 of file mpps_scp.cpp.
{
    using namespace network::dimse;
    // Create N-SET response message
    dimse_message response{command_field::n_set_rsp, 0};
    response.set_message_id_responded_to(message_id);
    response.set_affected_sop_class_uid(mpps_sop_class_uid);
    response.set_status(status);
    if (!sop_instance_uid.empty()) {
        response.set_affected_sop_instance_uid(sop_instance_uid);
    }
    // Send the response
    return assoc.send_dimse(context_id, response);
}
References kcenon::pacs::services::mpps_sop_class_uid, and kcenon::pacs::network::association::send_dimse().
Referenced by handle_n_set().
service_name()
std::string_view kcenon::pacs::services::mpps_scp::service_name () const nodiscard override virtual noexcept
Get the service name.
Returns
"MPPS SCP"
Implements kcenon::pacs::services::scp_service.
Definition at line 69 of file mpps_scp.cpp.
{
    return "MPPS SCP";
}
set_create_handler()
void kcenon::pacs::services::mpps_scp::set_create_handler (mpps_create_handler handler)
Set the N-CREATE handler function.
The handler is called for each N-CREATE request to create a new MPPS instance in the database or forward to RIS/HIS.
Parameters
handler The N-CREATE handler function
Definition at line 30 of file mpps_scp.cpp.
{
    create_handler_ = std::move(handler);
}
References create_handler_.
set_set_handler()
void kcenon::pacs::services::mpps_scp::set_set_handler (mpps_set_handler handler)
Set the N-SET handler function.
The handler is called for each N-SET request to update an existing MPPS instance with COMPLETED or DISCONTINUED status.
Parameters
handler The N-SET handler function
Definition at line 34 of file mpps_scp.cpp.
{
    set_handler_ = std::move(handler);
}
References set_handler_.
sets_processed()
size_t kcenon::pacs::services::mpps_scp::sets_processed () const nodiscard noexcept
Get total number of N-SET requests processed.
Returns
Number of MPPS instances updated
Definition at line 81 of file mpps_scp.cpp.
{
    return sets_processed_.load();
}
References sets_processed_.
supported_sop_classes()
std::vector< std::string > kcenon::pacs::services::mpps_scp::supported_sop_classes () const nodiscard override virtual
Get supported SOP Class UIDs.
Returns
Vector containing MPPS SOP Class UID
Implements kcenon::pacs::services::scp_service.
Definition at line 42 of file mpps_scp.cpp.
{
    return {std::string(mpps_sop_class_uid)};
}
References kcenon::pacs::services::mpps_sop_class_uid.
Member Data Documentation
create_handler_
mpps_create_handler kcenon::pacs::services::mpps_scp::create_handler_ private
Definition at line 413 of file mpps_scp.h.
Referenced by handle_n_create(), and set_create_handler().
creates_processed_
std::atomic<size_t> kcenon::pacs::services::mpps_scp::creates_processed_ {0} private
Definition at line 416 of file mpps_scp.h.
{0};
Referenced by creates_processed(), handle_n_create(), and reset_statistics().
mpps_completed_
std::atomic<size_t> kcenon::pacs::services::mpps_scp::mpps_completed_ {0} private
Definition at line 418 of file mpps_scp.h.
{0};
Referenced by handle_n_set(), mpps_completed(), and reset_statistics().
mpps_discontinued_
std::atomic<size_t> kcenon::pacs::services::mpps_scp::mpps_discontinued_ {0} private
Definition at line 419 of file mpps_scp.h.
{0};
Referenced by handle_n_set(), mpps_discontinued(), and reset_statistics().
set_handler_
mpps_set_handler kcenon::pacs::services::mpps_scp::set_handler_ private
Definition at line 414 of file mpps_scp.h.
Referenced by handle_n_set(), and set_set_handler().
sets_processed_
std::atomic<size_t> kcenon::pacs::services::mpps_scp::sets_processed_ {0} private
Definition at line 417 of file mpps_scp.h.
{0};
Referenced by handle_n_set(), reset_statistics(), and sets_processed().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/mpps_scp.h
src/services/mpps_scp.cpp