PACS System: kcenon::pacs::services::xds::imaging_document_source Class Reference
kcenon::pacs::services::xds::imaging_document_source Class Reference
#include <imaging_document_source.hpp>
Public Member Functions
imaging_document_source ()=default
imaging_document_source (const imaging_document_source_config &config)
kos_creation_result create_kos_document (const std::string &study_instance_uid, const std::vector< kos_instance_reference > &references, const std::optional< core::dicom_dataset > &patient_demographics=std::nullopt) const
Create a KOS document from a set of DICOM instance references.
xds_document_entry build_document_entry (const core::dicom_dataset &kos_dataset) const
Build XDS document entry metadata from a KOS dataset.
xds_submission_set build_submission_set (const std::string &patient_id) const
Build XDS submission set metadata.
publication_result publish_document (const core::dicom_dataset &kos_dataset, const xds_document_entry &entry) const
Publish a KOS document to the XDS registry/repository.
const imaging_document_source_config & config () const noexcept
Get current configuration.
void set_config (const imaging_document_source_config &config)
Set configuration.
Private Member Functions
std::string generate_uid () const
Generate a new UID for KOS instances.
void build_evidence_sequence (core::dicom_dataset &kos_dataset, const std::vector< kos_instance_reference > &references) const
Build the Current Requested Procedure Evidence Sequence.
Private Attributes
imaging_document_source_config config_
Detailed Description
Definition at line 286 of file imaging_document_source.hpp.
Constructor & Destructor Documentation
imaging_document_source() [1/2]
kcenon::pacs::services::xds::imaging_document_source::imaging_document_source () default
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_source.hpp.
imaging_document_source() [2/2]
kcenon::pacs::services::xds::imaging_document_source::imaging_document_source (const imaging_document_source_config & config) explicit
Definition at line 116 of file imaging_document_source.cpp.
    : config_(config) {}
Member Function Documentation
build_document_entry()
xds_document_entry kcenon::pacs::services::xds::imaging_document_source::build_document_entry (const core::dicom_dataset & kos_dataset) const
Build XDS document entry metadata from a KOS dataset.
Extracts patient and study metadata from the KOS dataset and populates an xds_document_entry structure suitable for registry submission.
Parameters
kos_dataset The KOS dataset to extract metadata from
Returns
Populated document entry metadata
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_source.hpp.
Definition at line 210 of file imaging_document_source.cpp.
{
    xds_document_entry entry;
    entry.entry_uuid = "urn:uuid:" + generate_uid();
    entry.unique_id = kos_dataset.get_string(tags::sop_instance_uid);
    entry.patient_id = kos_dataset.get_string(tags::patient_id);
    entry.source_patient_id = entry.patient_id;
    entry.class_code = "IMG";
    entry.class_code_scheme = "1.3.6.1.4.1.19376.3.840.1.1.4";
    entry.class_code_display = "Imaging Procedure";
    entry.type_code = "KOS";
    entry.type_code_scheme = "1.2.840.10008.2.16.4";
    entry.type_code_display = "Key Object Selection";
    entry.format_code = std::string(sop_classes::key_object_selection_document_storage_uid);
    entry.format_code_scheme = "1.2.840.10008.2.6.1";
    entry.creation_time = current_datetime();
    entry.service_start_time = entry.creation_time;
    entry.service_stop_time = entry.creation_time;
    entry.facility_type_code = config_.facility_type_code;
    entry.facility_type_code_scheme = config_.facility_type_code_scheme;
    entry.practice_setting_code = config_.practice_setting_code;
    entry.practice_setting_code_scheme = config_.practice_setting_code_scheme;
    // Extract author from patient demographics if available
    auto ref_physician = kos_dataset.get_string(tags::referring_physician_name);
    if (!ref_physician.empty()) {
        entry.author_person = ref_physician;
    }
    entry.title = "Key Object Selection Document";
    return entry;
}
References kcenon::pacs::services::xds::xds_document_entry::author_person, kcenon::pacs::services::xds::xds_document_entry::class_code, kcenon::pacs::services::xds::xds_document_entry::class_code_display, kcenon::pacs::services::xds::xds_document_entry::class_code_scheme, config_, kcenon::pacs::services::xds::xds_document_entry::creation_time, kcenon::pacs::services::xds::xds_document_entry::entry_uuid, kcenon::pacs::services::xds::xds_document_entry::facility_type_code, kcenon::pacs::services::xds::imaging_document_source_config::facility_type_code, kcenon::pacs::services::xds::xds_document_entry::facility_type_code_scheme, kcenon::pacs::services::xds::imaging_document_source_config::facility_type_code_scheme, kcenon::pacs::services::xds::xds_document_entry::format_code, kcenon::pacs::services::xds::xds_document_entry::format_code_scheme, generate_uid(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::key_object_selection_document_storage_uid, kcenon::pacs::core::tags::patient_id, kcenon::pacs::services::xds::xds_document_entry::patient_id, kcenon::pacs::services::xds::xds_document_entry::practice_setting_code, kcenon::pacs::services::xds::imaging_document_source_config::practice_setting_code, kcenon::pacs::services::xds::xds_document_entry::practice_setting_code_scheme, kcenon::pacs::services::xds::imaging_document_source_config::practice_setting_code_scheme, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::services::xds::xds_document_entry::service_start_time, kcenon::pacs::services::xds::xds_document_entry::service_stop_time, kcenon::pacs::core::tags::sop_instance_uid, kcenon::pacs::services::xds::xds_document_entry::source_patient_id, kcenon::pacs::services::xds::xds_document_entry::title, kcenon::pacs::services::xds::xds_document_entry::type_code, kcenon::pacs::services::xds::xds_document_entry::type_code_display, kcenon::pacs::services::xds::xds_document_entry::type_code_scheme, and kcenon::pacs::services::xds::xds_document_entry::unique_id.
build_evidence_sequence()
void kcenon::pacs::services::xds::imaging_document_source::build_evidence_sequence (core::dicom_dataset & kos_dataset, const std::vector< kos_instance_reference > & references) const private
Build the Current Requested Procedure Evidence Sequence.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_source.hpp.
Definition at line 311 of file imaging_document_source.cpp.
{
    // Group references by study -> series -> instances
    struct series_group {
        std::string series_uid;
        std::vector<std::pair<std::string, std::string>> instances;  // sop_class, sop_instance
    };
    std::unordered_map<std::string, std::vector<series_group>> study_map;
    for (const auto& ref : references) {
        auto& series_list = study_map[ref.study_instance_uid];
        auto it = std::find_if(series_list.begin(), series_list.end(),
                               [&](const series_group& sg) {
                                   return sg.series_uid == ref.series_instance_uid;
                               });
        if (it != series_list.end()) {
            it->instances.emplace_back(ref.sop_class_uid, ref.sop_instance_uid);
        } else {
            series_group sg;
            sg.series_uid = ref.series_instance_uid;
            sg.instances.emplace_back(ref.sop_class_uid, ref.sop_instance_uid);
            series_list.push_back(std::move(sg));
        }
    }
    // Build the sequence structure
    std::vector<dicom_dataset> study_items;
    for (const auto& [study_uid, series_list] : study_map) {
        dicom_dataset study_item;
        study_item.set_string(tags::study_instance_uid, vr_type::UI, study_uid);
        std::vector<dicom_dataset> series_items;
        for (const auto& sg : series_list) {
            dicom_dataset series_item;
            series_item.set_string(tags::series_instance_uid, vr_type::UI, sg.series_uid);
            std::vector<dicom_dataset> sop_items;
            for (const auto& [sop_class, sop_instance] : sg.instances) {
                dicom_dataset sop_item;
                sop_item.set_string(kos_tags::referenced_sop_class_uid, vr_type::UI, sop_class);
                sop_item.set_string(kos_tags::referenced_sop_instance_uid, vr_type::UI, sop_instance);
                sop_items.push_back(std::move(sop_item));
            }
            insert_sequence(series_item, kos_tags::referenced_sop_sequence, std::move(sop_items));
            series_items.push_back(std::move(series_item));
        }
        insert_sequence(study_item, kos_tags::referenced_series_sequence, std::move(series_items));
        study_items.push_back(std::move(study_item));
    }
    insert_sequence(kos_dataset,
                    kos_tags::current_requested_procedure_evidence_sequence,
                    std::move(study_items));
}
References kcenon::pacs::services::xds::kos_tags::current_requested_procedure_evidence_sequence, kcenon::pacs::services::xds::kos_tags::referenced_series_sequence, kcenon::pacs::services::xds::kos_tags::referenced_sop_class_uid, kcenon::pacs::services::xds::kos_tags::referenced_sop_instance_uid, kcenon::pacs::services::xds::kos_tags::referenced_sop_sequence, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::dicom_dataset::set_string(), and kcenon::pacs::core::tags::study_instance_uid.
Referenced by create_kos_document().
build_submission_set()
xds_submission_set kcenon::pacs::services::xds::imaging_document_source::build_submission_set (const std::string & patient_id) const
Build XDS submission set metadata.
Creates a submission set entry for ITI-41 Provide and Register Document Set-b transaction.
Parameters
patient_id Patient ID for the submission
Returns
Populated submission set metadata
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_source.hpp.
Definition at line 251 of file imaging_document_source.cpp.
{
    xds_submission_set set;
    set.unique_id = generate_uid();
    set.source_id = config_.source_oid;
    set.patient_id = patient_id;
    set.content_type_code = "IMG";
    set.content_type_code_scheme = "1.3.6.1.4.1.19376.3.840.1.1.4";
    set.content_type_code_display = "Imaging Procedure";
    set.submission_time = current_datetime();
    return set;
}
References config_, kcenon::pacs::services::xds::xds_submission_set::content_type_code, kcenon::pacs::services::xds::xds_submission_set::content_type_code_display, kcenon::pacs::services::xds::xds_submission_set::content_type_code_scheme, generate_uid(), kcenon::pacs::services::xds::xds_submission_set::patient_id, kcenon::pacs::services::xds::xds_submission_set::source_id, kcenon::pacs::services::xds::imaging_document_source_config::source_oid, kcenon::pacs::services::xds::xds_submission_set::submission_time, and kcenon::pacs::services::xds::xds_submission_set::unique_id.
config()
const imaging_document_source_config & kcenon::pacs::services::xds::imaging_document_source::config () const noexcept
Get current configuration.
Returns
Reference to configuration
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_source.hpp.
Definition at line 289 of file imaging_document_source.cpp.
{
    return config_;
}
References config_.
Referenced by set_config().
create_kos_document()
kos_creation_result kcenon::pacs::services::xds::imaging_document_source::create_kos_document (const std::string & study_instance_uid, const std::vector< kos_instance_reference > & references, const std::optional< core::dicom_dataset > & patient_demographics = std::nullopt) const
Create a KOS document from a set of DICOM instance references.
Generates a Key Object Selection Document (SOP Class 1.2.840.10008.5.1.4.1.1.88.59) containing references to the specified instances, following TID 2010.
Parameters
study_instance_uid The Study Instance UID
references Vector of instance references to include
patient_demographics Optional patient demographics dataset
Returns
KOS creation result with the generated dataset
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_source.hpp.
Definition at line 120 of file imaging_document_source.cpp.
{
    kos_creation_result result;
    if (references.empty()) {
        result.error_message = "No instance references provided";
        return result;
    }
    core::dicom_dataset kos;
    // --- SOP Common Module ---
    kos.set_string(tags::sop_class_uid, vr_type::UI,
                   std::string(sop_classes::key_object_selection_document_storage_uid));
    result.kos_instance_uid = generate_uid();
    kos.set_string(tags::sop_instance_uid, vr_type::UI, result.kos_instance_uid);
    // --- Patient Module (Type 2) ---
    if (patient_demographics) {
        auto copy_if_present = [&](dicom_tag tag, vr_type vr) {
            if (patient_demographics->contains(tag)) {
                kos.set_string(tag, vr, patient_demographics->get_string(tag));
            } else {
                kos.set_string(tag, vr, "");
            }
        };
        copy_if_present(tags::patient_name, vr_type::PN);
        copy_if_present(tags::patient_id, vr_type::LO);
        copy_if_present(tags::patient_birth_date, vr_type::DA);
        copy_if_present(tags::patient_sex, vr_type::CS);
    } else {
        kos.set_string(tags::patient_name, vr_type::PN, "");
        kos.set_string(tags::patient_id, vr_type::LO, "");
        kos.set_string(tags::patient_birth_date, vr_type::DA, "");
        kos.set_string(tags::patient_sex, vr_type::CS, "");
    }
    // --- General Study Module ---
    kos.set_string(tags::study_instance_uid, vr_type::UI, study_instance_uid);
    kos.set_string(tags::study_date, vr_type::DA, current_date());
    kos.set_string(tags::study_time, vr_type::TM, current_time());
    kos.set_string(tags::referring_physician_name, vr_type::PN, "");
    kos.set_string(tags::study_id, vr_type::SH, "");
    kos.set_string(tags::accession_number, vr_type::SH, "");
    // --- General Series Module ---
    kos.set_string(tags::modality, vr_type::CS, "KO");
    kos.set_string(tags::series_instance_uid, vr_type::UI, generate_uid());
    kos.set_string(tags::series_number, vr_type::IS, "1");
    // --- General Equipment Module ---
    kos.set_string(dicom_tag{0x0008, 0x0070}, vr_type::LO, "");  // Manufacturer
    // --- SR Document General Module ---
    kos.set_string(tags::instance_number, vr_type::IS, "1");
    kos.set_string(tags::content_date, vr_type::DA, current_date());
    kos.set_string(tags::content_time, vr_type::TM, current_time());
    kos.set_string(kos_tags::completion_flag, vr_type::CS, "COMPLETE");
    kos.set_string(kos_tags::verification_flag, vr_type::CS, "UNVERIFIED");
    // --- SR Document Content Module ---
    // Value type: CONTAINER (root)
    kos.set_string(kos_tags::value_type, vr_type::CS, "CONTAINER");
    // Concept Name Code Sequence: Key Object Selection (113000, DCM)
    dicom_dataset concept_name;
    concept_name.set_string(kos_tags::code_value, vr_type::SH, "113000");
    concept_name.set_string(kos_tags::coding_scheme_designator, vr_type::SH, "DCM");
    concept_name.set_string(kos_tags::code_meaning, vr_type::LO, "Of Interest");
    insert_sequence(kos, kos_tags::concept_name_code_sequence, {concept_name});
    // Content Template Sequence: TID 2010
    dicom_dataset template_item;
    template_item.set_string(kos_tags::template_identifier, vr_type::CS, "2010");
    template_item.set_string(kos_tags::mapping_resource, vr_type::CS, "DCMR");
    insert_sequence(kos, kos_tags::content_template_sequence, {template_item});
    // --- Current Requested Procedure Evidence Sequence ---
    build_evidence_sequence(kos, references);
    result.success = true;
    result.reference_count = references.size();
    result.kos_dataset = std::move(kos);
    return result;
}
References kcenon::pacs::core::tags::accession_number, build_evidence_sequence(), kcenon::pacs::services::xds::kos_tags::code_meaning, kcenon::pacs::services::xds::kos_tags::code_value, kcenon::pacs::services::xds::kos_tags::coding_scheme_designator, kcenon::pacs::services::xds::kos_tags::completion_flag, kcenon::pacs::services::xds::kos_tags::concept_name_code_sequence, kcenon::pacs::core::tags::content_date, kcenon::pacs::services::xds::kos_tags::content_template_sequence, kcenon::pacs::core::tags::content_time, kcenon::pacs::services::xds::kos_creation_result::error_message, generate_uid(), kcenon::pacs::core::tags::instance_number, kcenon::pacs::services::sop_classes::key_object_selection_document_storage_uid, kcenon::pacs::services::xds::kos_creation_result::kos_dataset, kcenon::pacs::services::xds::kos_creation_result::kos_instance_uid, kcenon::pacs::services::xds::kos_tags::mapping_resource, kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, kcenon::pacs::core::tags::patient_sex, kcenon::pacs::services::xds::kos_creation_result::reference_count, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::series_number, kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, kcenon::pacs::core::tags::study_time, kcenon::pacs::services::xds::kos_creation_result::success, kcenon::pacs::services::xds::kos_tags::template_identifier, kcenon::pacs::services::xds::kos_tags::value_type, kcenon::pacs::services::xds::kos_tags::verification_flag, and vr.
generate_uid()
std::string kcenon::pacs::services::xds::imaging_document_source::generate_uid () const private
Generate a new UID for KOS instances.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_source.hpp.
Definition at line 298 of file imaging_document_source.cpp.
{
    static constexpr const char* uid_root = "1.2.826.0.1.3680043.2.1545.1";
    static std::mt19937_64 gen{std::random_device{}()};
    static std::uniform_int_distribution<uint64_t> dist;
    auto now = std::chrono::system_clock::now();
    auto timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(
        now.time_since_epoch()).count();
    return std::string(uid_root) + "." + std::to_string(timestamp) +
           "." + std::to_string(dist(gen) % 100000);
}
Referenced by build_document_entry(), build_submission_set(), and create_kos_document().
publish_document()
publication_result kcenon::pacs::services::xds::imaging_document_source::publish_document (const core::dicom_dataset & kos_dataset, const xds_document_entry & entry) const
Publish a KOS document to the XDS registry/repository.
Performs the ITI-41 (Provide and Register Document Set-b) transaction to publish the KOS document and its metadata to the configured XDS registry/repository.
Parameters
kos_dataset The KOS dataset to publish
entry The document entry metadata
Returns
Publication result
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_source.hpp.
Definition at line 267 of file imaging_document_source.cpp.
{
    publication_result result;
    if (config_.registry_url.empty()) {
        result.error_message = "XDS registry URL not configured";
        return result;
    }
    // NOTE: Actual HTTP POST to the XDS registry/repository (ITI-41)
    // would be implemented here using the network layer.
    // The ITI-41 transaction uses SOAP/MTOM encoding.
    // For now, return success to indicate the interface is operational.
    result.success = true;
    result.document_entry_uuid = entry.entry_uuid;
    return result;
}
References config_, kcenon::pacs::services::xds::publication_result::document_entry_uuid, kcenon::pacs::services::xds::publication_result::error_message, kcenon::pacs::services::xds::imaging_document_source_config::registry_url, and kcenon::pacs::services::xds::publication_result::success.
set_config()
void kcenon::pacs::services::xds::imaging_document_source::set_config (const imaging_document_source_config & config)
Set configuration.
Parameters
config New configuration
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_source.hpp.
Definition at line 293 of file imaging_document_source.cpp.
{
    config_ = config;
}
References config(), and config_.
Member Data Documentation
config_
imaging_document_source_config kcenon::pacs::services::xds::imaging_document_source::config_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_source.hpp.
Definition at line 360 of file imaging_document_source.hpp.
Referenced by build_document_entry(), build_submission_set(), config(), publish_document(), and set_config().
The documentation for this class was generated from the following files:
include/pacs/services/xds/imaging_document_source.hpp
src/services/xds/imaging_document_source.cpp