PACS System: kcenon::pacs::services::validation::rt_dose_iod_validator Class Reference
kcenon::pacs::services::validation::rt_dose_iod_validator Class Reference
Validator for RT Dose IODs.
#include <rt_iod_validator.hpp>
Public Member Functions
rt_dose_iod_validator ()=default
rt_dose_iod_validator (const rt_validation_options &options)
validation_result validate (const core::dicom_dataset &dataset) const
bool quick_check (const core::dicom_dataset &dataset) const
const rt_validation_options & options () const noexcept
void set_options (const rt_validation_options &options)
Private Member Functions
void validate_patient_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_study_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_rt_series_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_frame_of_reference_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_rt_dose_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_image_pixel_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_sop_common_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_type1_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_type2_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_dose_data_consistency (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
Private Attributes
rt_validation_options options_
Detailed Description
Validator for RT Dose IODs.
Validates DICOM datasets against the RT Dose IOD specification. Checks dose grid attributes, units, and summation type.
Validated Modules
Mandatory Modules
Patient Module (M)
General Study Module (M)
RT Series Module (M)
Frame of Reference Module (M)
General Equipment Module (M)
General Image Module (M)
Image Plane Module (C)
Image Pixel Module (C)
Multi-frame Module (C)
RT Dose Module (M)
RT DVH Module (U)
SOP Common Module (M)
Definition at line 210 of file rt_iod_validator.hpp.
Constructor & Destructor Documentation
rt_dose_iod_validator() [1/2]
kcenon::pacs::services::validation::rt_dose_iod_validator::rt_dose_iod_validator () default
rt_dose_iod_validator() [2/2]
kcenon::pacs::services::validation::rt_dose_iod_validator::rt_dose_iod_validator (const rt_validation_options & options) explicit
Definition at line 461 of file rt_iod_validator.cpp.
    : options_(options) {}
Member Function Documentation
check_dose_data_consistency()
void kcenon::pacs::services::validation::rt_dose_iod_validator::check_dose_data_consistency (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 756 of file rt_iod_validator.cpp.
{
    // Check bits consistency
    auto bits_allocated = dataset.get_numeric<uint16_t>(rt_tags::bits_allocated);
    auto bits_stored = dataset.get_numeric<uint16_t>(rt_tags::bits_stored);
    auto high_bit = dataset.get_numeric<uint16_t>(rt_tags::high_bit);
    if (bits_allocated && bits_stored) {
        if (*bits_stored > *bits_allocated) {
            findings.push_back({
                validation_severity::error,
                rt_tags::bits_stored,
                "BitsStored exceeds BitsAllocated",
                "RTDOSE-ERR-003"
            });
        }
    }
    if (bits_stored && high_bit) {
        if (*high_bit != *bits_stored - 1) {
            findings.push_back({
                validation_severity::warning,
                rt_tags::high_bit,
                "HighBit should typically be BitsStored - 1",
                "RTDOSE-WARN-005"
            });
        }
    }
    // Multi-frame dose grids should have GridFrameOffsetVector
    auto num_frames = dataset.get_numeric<int32_t>(rt_tags::number_of_frames);
    if (num_frames && *num_frames > 1) {
        if (!dataset.contains(rt_tags::grid_frame_offset_vector)) {
            findings.push_back({
                validation_severity::warning,
                rt_tags::grid_frame_offset_vector,
                "GridFrameOffsetVector recommended for multi-frame dose grids",
                "RTDOSE-WARN-006"
            });
        }
    }
}
References kcenon::pacs::services::validation::rt_tags::bits_allocated, kcenon::pacs::services::validation::rt_tags::bits_stored, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_numeric(), kcenon::pacs::services::validation::rt_tags::grid_frame_offset_vector, kcenon::pacs::services::validation::rt_tags::high_bit, kcenon::pacs::services::validation::rt_tags::number_of_frames, and kcenon::pacs::services::validation::warning.
Referenced by validate_rt_dose_module().
check_type1_attribute()
void kcenon::pacs::services::validation::rt_dose_iod_validator::check_type1_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Definition at line 711 of file rt_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::error,
            tag,
            std::string("Type 1 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "RTDOSE-TYPE1-MISSING"
        });
    } else {
        auto value = dataset.get_string(tag);
        if (value.empty()) {
            findings.push_back({
                validation_severity::error,
                tag,
                std::string("Type 1 attribute has empty value: ") +
                std::string(name) + " (" + tag.to_string() + ")",
                "RTDOSE-TYPE1-EMPTY"
            });
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), name, and kcenon::pacs::core::dicom_tag::to_string().
Referenced by validate_frame_of_reference_module(), validate_general_study_module(), validate_image_pixel_module(), validate_rt_dose_module(), validate_rt_series_module(), and validate_sop_common_module().
check_type2_attribute()
void kcenon::pacs::services::validation::rt_dose_iod_validator::check_type2_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Definition at line 739 of file rt_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::warning,
            tag,
            std::string("Type 2 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "RTDOSE-TYPE2-MISSING"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), name, kcenon::pacs::core::dicom_tag::to_string(), and kcenon::pacs::services::validation::warning.
Referenced by validate_general_study_module(), and validate_patient_module().
options()
const rt_validation_options & kcenon::pacs::services::validation::rt_dose_iod_validator::options () const noexcept
Definition at line 515 of file rt_iod_validator.cpp.
{
    return options_;
}
References options_.
Referenced by set_options().
quick_check()
bool kcenon::pacs::services::validation::rt_dose_iod_validator::quick_check (const core::dicom_dataset & dataset) const
Definition at line 498 of file rt_iod_validator.cpp.
{
    if (!dataset.contains(tags::study_instance_uid)) return false;
    if (!dataset.contains(tags::series_instance_uid)) return false;
    if (!dataset.contains(tags::modality)) return false;
    auto modality = dataset.get_string(tags::modality);
    if (modality != "RTDOSE") return false;
    if (!dataset.contains(rt_tags::dose_units)) return false;
    if (!dataset.contains(rt_tags::dose_type)) return false;
    if (!dataset.contains(rt_tags::dose_summation_type)) return false;
    if (!dataset.contains(tags::sop_class_uid)) return false;
    if (!dataset.contains(tags::sop_instance_uid)) return false;
    return true;
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::rt_tags::dose_summation_type, kcenon::pacs::services::validation::rt_tags::dose_type, kcenon::pacs::services::validation::rt_tags::dose_units, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, and kcenon::pacs::core::tags::study_instance_uid.
Referenced by kcenon::pacs::services::validation::is_valid_rt_dose_dataset().
set_options()
void kcenon::pacs::services::validation::rt_dose_iod_validator::set_options (const rt_validation_options & options)
Definition at line 519 of file rt_iod_validator.cpp.
{
    options_ = options;
}
References options(), and options_.
validate()
validation_result kcenon::pacs::services::validation::rt_dose_iod_validator::validate (const core::dicom_dataset & dataset) const
Definition at line 464 of file rt_iod_validator.cpp.
{
    validation_result result;
    result.is_valid = true;
    // Validate mandatory modules
    if (options_.check_type1 || options_.check_type2) {
        validate_patient_module(dataset, result.findings);
        validate_general_study_module(dataset, result.findings);
        validate_rt_series_module(dataset, result.findings);
        validate_frame_of_reference_module(dataset, result.findings);
        validate_rt_dose_module(dataset, result.findings);
        validate_sop_common_module(dataset, result.findings);
    }
    // Validate pixel data for dose grid
    if (options_.validate_pixel_data) {
        validate_image_pixel_module(dataset, result.findings);
    }
    // Check for errors
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
        if (options_.strict_mode && finding.severity == validation_severity::warning) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, kcenon::pacs::services::validation::rt_validation_options::check_type2, kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::services::validation::validation_result::is_valid, options_, kcenon::pacs::services::validation::rt_validation_options::strict_mode, validate_frame_of_reference_module(), validate_general_study_module(), validate_image_pixel_module(), validate_patient_module(), kcenon::pacs::services::validation::rt_validation_options::validate_pixel_data, validate_rt_dose_module(), validate_rt_series_module(), validate_sop_common_module(), and kcenon::pacs::services::validation::warning.
Referenced by kcenon::pacs::services::validation::rt_iod_validator::validate(), and kcenon::pacs::services::validation::validate_rt_dose_iod().
validate_frame_of_reference_module()
void kcenon::pacs::services::validation::rt_dose_iod_validator::validate_frame_of_reference_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 573 of file rt_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, rt_tags::frame_of_reference_uid,
                              "FrameOfReferenceUID", findings);
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::rt_tags::frame_of_reference_uid, and options_.
Referenced by validate().
validate_general_study_module()
void kcenon::pacs::services::validation::rt_dose_iod_validator::validate_general_study_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 535 of file rt_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::study_instance_uid, "StudyInstanceUID", findings);
    }
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::study_date, "StudyDate", findings);
        check_type2_attribute(dataset, tags::study_time, "StudyTime", findings);
        check_type2_attribute(dataset, tags::study_id, "StudyID", findings);
        check_type2_attribute(dataset, tags::accession_number, "AccessionNumber", findings);
    }
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::rt_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::core::tags::study_time.
Referenced by validate().
validate_image_pixel_module()
void kcenon::pacs::services::validation::rt_dose_iod_validator::validate_image_pixel_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 664 of file rt_iod_validator.cpp.
{
    // For dose grids, pixel data is required
    if (options_.check_type1) {
        check_type1_attribute(dataset, rt_tags::rows, "Rows", findings);
        check_type1_attribute(dataset, rt_tags::columns, "Columns", findings);
        check_type1_attribute(dataset, rt_tags::bits_allocated, "BitsAllocated", findings);
        check_type1_attribute(dataset, rt_tags::bits_stored, "BitsStored", findings);
        check_type1_attribute(dataset, rt_tags::high_bit, "HighBit", findings);
        check_type1_attribute(dataset, rt_tags::pixel_representation, "PixelRepresentation", findings);
    }
    // Pixel Data may not be present for point doses
    if (!dataset.contains(rt_tags::pixel_data)) {
        findings.push_back({
            validation_severity::info,
            rt_tags::pixel_data,
            "PixelData not present - this may be a point dose or DVH-only object",
            "RTDOSE-INFO-002"
        });
    }
}
References kcenon::pacs::services::validation::rt_tags::bits_allocated, kcenon::pacs::services::validation::rt_tags::bits_stored, kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::rt_tags::columns, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::rt_tags::high_bit, kcenon::pacs::services::validation::info, options_, kcenon::pacs::services::validation::rt_tags::pixel_data, kcenon::pacs::services::validation::rt_tags::pixel_representation, and kcenon::pacs::services::validation::rt_tags::rows.
Referenced by validate().
validate_patient_module()
void kcenon::pacs::services::validation::rt_dose_iod_validator::validate_patient_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 523 of file rt_iod_validator.cpp.
{
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::patient_name, "PatientName", findings);
        check_type2_attribute(dataset, tags::patient_id, "PatientID", findings);
        check_type2_attribute(dataset, tags::patient_birth_date, "PatientBirthDate", findings);
        check_type2_attribute(dataset, tags::patient_sex, "PatientSex", findings);
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, and kcenon::pacs::core::tags::patient_sex.
Referenced by validate().
validate_rt_dose_module()
void kcenon::pacs::services::validation::rt_dose_iod_validator::validate_rt_dose_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 583 of file rt_iod_validator.cpp.
{
    // Type 1 attributes
    if (options_.check_type1) {
        check_type1_attribute(dataset, rt_tags::dose_units, "DoseUnits", findings);
        check_type1_attribute(dataset, rt_tags::dose_type, "DoseType", findings);
        check_type1_attribute(dataset, rt_tags::dose_summation_type, "DoseSummationType", findings);
    }
    // Validate DoseUnits
    if (dataset.contains(rt_tags::dose_units)) {
        auto units = dataset.get_string(rt_tags::dose_units);
        if (units != "GY" && units != "RELATIVE") {
            findings.push_back({
                validation_severity::warning,
                rt_tags::dose_units,
                "Non-standard DoseUnits: " + units + " (expected GY or RELATIVE)",
                "RTDOSE-WARN-001"
            });
        }
    }
    // Validate DoseType
    if (dataset.contains(rt_tags::dose_type)) {
        auto dose_type = dataset.get_string(rt_tags::dose_type);
        if (dose_type != "PHYSICAL" && dose_type != "EFFECTIVE" && dose_type != "ERROR") {
            findings.push_back({
                validation_severity::warning,
                rt_tags::dose_type,
                "Non-standard DoseType: " + dose_type,
                "RTDOSE-WARN-002"
            });
        }
    }
    // Validate DoseSummationType
    if (dataset.contains(rt_tags::dose_summation_type)) {
        auto summation = dataset.get_string(rt_tags::dose_summation_type);
        if (summation != "PLAN" && summation != "MULTI_PLAN" && summation != "FRACTION" &&
            summation != "BEAM" && summation != "BRACHY" && summation != "FRACTION_SESSION" &&
            summation != "BEAM_SESSION" && summation != "BRACHY_SESSION" &&
            summation != "CONTROL_POINT" && summation != "RECORD") {
            findings.push_back({
                validation_severity::warning,
                rt_tags::dose_summation_type,
                "Non-standard DoseSummationType: " + summation,
                "RTDOSE-WARN-003"
            });
        }
    }
    // DoseGridScaling is required for proper dose value interpretation
    if (!dataset.contains(rt_tags::dose_grid_scaling)) {
        findings.push_back({
            validation_severity::warning,
            rt_tags::dose_grid_scaling,
            "DoseGridScaling not present - dose values may not be properly scaled",
            "RTDOSE-WARN-004"
        });
    }
    // ReferencedRTPlanSequence for traceability
    if (options_.validate_references) {
        if (!dataset.contains(rt_tags::referenced_rt_plan_sequence)) {
            findings.push_back({
                validation_severity::info,
                rt_tags::referenced_rt_plan_sequence,
                "ReferencedRTPlanSequence not present - dose has no associated plan reference",
                "RTDOSE-INFO-001"
            });
        }
    }
    // Validate dose data consistency
    if (options_.validate_pixel_data) {
        check_dose_data_consistency(dataset, findings);
    }
}
References check_dose_data_consistency(), kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::rt_tags::dose_grid_scaling, kcenon::pacs::services::validation::rt_tags::dose_summation_type, kcenon::pacs::services::validation::rt_tags::dose_type, kcenon::pacs::services::validation::rt_tags::dose_units, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::info, options_, kcenon::pacs::services::validation::rt_tags::referenced_rt_plan_sequence, kcenon::pacs::services::validation::rt_validation_options::validate_pixel_data, kcenon::pacs::services::validation::rt_validation_options::validate_references, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_rt_series_module()
void kcenon::pacs::services::validation::rt_dose_iod_validator::validate_rt_series_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 551 of file rt_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::modality, "Modality", findings);
        check_type1_attribute(dataset, tags::series_instance_uid, "SeriesInstanceUID", findings);
        if (dataset.contains(tags::modality)) {
            auto modality = dataset.get_string(tags::modality);
            if (modality != "RTDOSE") {
                findings.push_back({
                    validation_severity::error,
                    tags::modality,
                    "Modality must be 'RTDOSE' for RT Dose, found: " + modality,
                    "RTDOSE-ERR-001"
                });
            }
        }
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::modality, options_, and kcenon::pacs::core::tags::series_instance_uid.
Referenced by validate().
validate_sop_common_module()
void kcenon::pacs::services::validation::rt_dose_iod_validator::validate_sop_common_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Definition at line 689 of file rt_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::sop_class_uid, "SOPClassUID", findings);
        check_type1_attribute(dataset, tags::sop_instance_uid, "SOPInstanceUID", findings);
    }
    if (dataset.contains(tags::sop_class_uid)) {
        auto sop_class = dataset.get_string(tags::sop_class_uid);
        if (sop_class != sop_classes::rt_dose_storage_uid) {
            findings.push_back({
                validation_severity::error,
                tags::sop_class_uid,
                "SOPClassUID is not RT Dose Storage: " + sop_class,
                "RTDOSE-ERR-002"
            });
        }
    }
}
References kcenon::pacs::services::validation::rt_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), options_, kcenon::pacs::services::sop_classes::rt_dose_storage_uid, kcenon::pacs::core::tags::sop_class_uid, and kcenon::pacs::core::tags::sop_instance_uid.
Referenced by validate().
Member Data Documentation
options_
rt_validation_options kcenon::pacs::services::validation::rt_dose_iod_validator::options_ private
Definition at line 266 of file rt_iod_validator.hpp.
Referenced by options(), set_options(), validate(), validate_frame_of_reference_module(), validate_general_study_module(), validate_image_pixel_module(), validate_patient_module(), validate_rt_dose_module(), validate_rt_series_module(), and validate_sop_common_module().
The documentation for this class was generated from the following files:
include/pacs/services/validation/rt_iod_validator.hpp
src/services/validation/rt_iod_validator.cpp