PACS System: kcenon::pacs::services::validation::mr_iod_validator Class Reference
kcenon::pacs::services::validation::mr_iod_validator Class Reference
#include <mr_iod_validator.hpp>
Public Member Functions
mr_iod_validator ()=default
Construct validator with default options.
mr_iod_validator (const mr_validation_options &options)
Construct validator with custom options.
validation_result validate (const core::dicom_dataset &dataset) const
Validate a DICOM dataset against MR IOD.
bool quick_check (const core::dicom_dataset &dataset) const
Quick check if dataset has minimum required MR attributes.
const mr_validation_options & options () const noexcept
Get the validation options.
void set_options (const mr_validation_options &options)
Set validation options.
Private Member Functions
void validate_patient_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_study_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_series_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_frame_of_reference_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_equipment_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_mr_image_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_image_pixel_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_sop_common_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_type1_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_type2_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_modality (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_pixel_data_consistency (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
Private Attributes
mr_validation_options options_
Detailed Description
Definition at line 198 of file mr_iod_validator.hpp.
Constructor & Destructor Documentation
mr_iod_validator() [1/2]
kcenon::pacs::services::validation::mr_iod_validator::mr_iod_validator () default
Construct validator with default options.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
mr_iod_validator() [2/2]
kcenon::pacs::services::validation::mr_iod_validator::mr_iod_validator (const mr_validation_options & options) explicit
Construct validator with custom options.
Parameters
options Validation options
Definition at line 50 of file mr_iod_validator.cpp.
    : options_(options) {}
Member Function Documentation
check_modality()
void kcenon::pacs::services::validation::mr_iod_validator::check_modality (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 420 of file mr_iod_validator.cpp.
{
    if (!dataset.contains(tags::modality)) {
        return;  // Already reported as Type 1 missing
    }
    auto modality = dataset.get_string(tags::modality);
    if (modality != "MR") {
        findings.push_back(
            {validation_severity::error, tags::modality,
             "Modality must be 'MR' for MR images, found: " + modality,
             "MR-ERR-002"});
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), and kcenon::pacs::core::tags::modality.
Referenced by validate_general_series_module().
check_pixel_data_consistency()
void kcenon::pacs::services::validation::mr_iod_validator::check_pixel_data_consistency (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 437 of file mr_iod_validator.cpp.
{
    // Check BitsStored <= BitsAllocated
    auto bits_allocated =
        dataset.get_numeric<uint16_t>(tags::bits_allocated);
    auto bits_stored = dataset.get_numeric<uint16_t>(tags::bits_stored);
    auto high_bit = dataset.get_numeric<uint16_t>(tags::high_bit);
    if (bits_allocated && bits_stored) {
        if (*bits_stored > *bits_allocated) {
            findings.push_back(
                {validation_severity::error, tags::bits_stored,
                 "BitsStored (" + std::to_string(*bits_stored) +
                     ") exceeds BitsAllocated (" +
                     std::to_string(*bits_allocated) + ")",
                 "MR-ERR-003"});
        }
    }
    // Check HighBit == BitsStored - 1
    if (bits_stored && high_bit) {
        if (*high_bit != *bits_stored - 1) {
            findings.push_back(
                {validation_severity::warning, tags::high_bit,
                 "HighBit (" + std::to_string(*high_bit) +
                     ") should typically be BitsStored - 1 (" +
                     std::to_string(*bits_stored - 1) + ")",
                 "MR-WARN-005"});
        }
    }
    // MR images must be grayscale (MONOCHROME1 or MONOCHROME2)
    if (dataset.contains(tags::photometric_interpretation)) {
        auto photometric =
            dataset.get_string(tags::photometric_interpretation);
        if (!sop_classes::is_valid_mr_photometric(photometric)) {
            findings.push_back(
                {validation_severity::error,
                 tags::photometric_interpretation,
                 "MR images must use MONOCHROME1 or MONOCHROME2, found: " +
                     photometric,
                 "MR-ERR-004"});
        }
    }
    // MR images must have SamplesPerPixel = 1
    auto samples = dataset.get_numeric<uint16_t>(tags::samples_per_pixel);
    if (samples && *samples != 1) {
        findings.push_back(
            {validation_severity::error, tags::samples_per_pixel,
             "MR images require SamplesPerPixel = 1, found: " +
                 std::to_string(*samples),
             "MR-ERR-005"});
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_numeric(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::services::sop_classes::is_valid_mr_photometric(), kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::samples_per_pixel, and kcenon::pacs::services::validation::warning.
Referenced by validate_image_pixel_module().
check_type1_attribute()
void kcenon::pacs::services::validation::mr_iod_validator::check_type1_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 383 of file mr_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back(
            {validation_severity::error, tag,
             std::string("Type 1 attribute missing: ") + std::string(name) +
                 " (" + tag.to_string() + ")",
             "MR-TYPE1-MISSING"});
    } else {
        // Type 1 must have a value (cannot be empty)
        auto value = dataset.get_string(tag);
        if (value.empty()) {
            findings.push_back(
                {validation_severity::error, tag,
                 std::string("Type 1 attribute has empty value: ") +
                     std::string(name) + " (" + tag.to_string() + ")",
                 "MR-TYPE1-EMPTY"});
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), name, and kcenon::pacs::core::dicom_tag::to_string().
Referenced by validate_frame_of_reference_module(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_mr_image_module(), and validate_sop_common_module().
check_type2_attribute()
void kcenon::pacs::services::validation::mr_iod_validator::check_type2_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 406 of file mr_iod_validator.cpp.
{
    // Type 2 must be present but can be empty
    if (!dataset.contains(tag)) {
        findings.push_back(
            {validation_severity::warning, tag,
             std::string("Type 2 attribute missing: ") + std::string(name) +
                 " (" + tag.to_string() + ")",
             "MR-TYPE2-MISSING"});
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), name, kcenon::pacs::core::dicom_tag::to_string(), and kcenon::pacs::services::validation::warning.
Referenced by validate_frame_of_reference_module(), validate_general_equipment_module(), validate_general_series_module(), validate_general_study_module(), validate_mr_image_module(), and validate_patient_module().
options()
const mr_validation_options & kcenon::pacs::services::validation::mr_iod_validator::options () const noexcept
Get the validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 131 of file mr_iod_validator.cpp.
{
    return options_;
}
References options_.
Referenced by set_options().
quick_check()
bool kcenon::pacs::services::validation::mr_iod_validator::quick_check (const core::dicom_dataset & dataset) const
Quick check if dataset has minimum required MR attributes.
Parameters
dataset The dataset to check
Returns
true if all Type 1 attributes are present
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 92 of file mr_iod_validator.cpp.
{
    // Check only Type 1 required attributes for quick validation
    // General Study Module Type 1
    if (!dataset.contains(tags::study_instance_uid)) return false;
    // General Series Module Type 1
    if (!dataset.contains(tags::modality)) return false;
    if (!dataset.contains(tags::series_instance_uid)) return false;
    // Check modality is MR
    auto modality = dataset.get_string(tags::modality);
    if (modality != "MR") return false;
    // Frame of Reference Module Type 1
    if (!dataset.contains(tags::frame_of_reference_uid)) return false;
    // MR Image Module Type 1
    if (!dataset.contains(mr_tags::scanning_sequence)) return false;
    if (!dataset.contains(mr_tags::sequence_variant)) return false;
    // Image Pixel Module Type 1
    if (!dataset.contains(tags::samples_per_pixel)) return false;
    if (!dataset.contains(tags::photometric_interpretation)) return false;
    if (!dataset.contains(tags::rows)) return false;
    if (!dataset.contains(tags::columns)) return false;
    if (!dataset.contains(tags::bits_allocated)) return false;
    if (!dataset.contains(tags::bits_stored)) return false;
    if (!dataset.contains(tags::high_bit)) return false;
    if (!dataset.contains(tags::pixel_representation)) return false;
    if (!dataset.contains(tags::pixel_data)) return false;
    // SOP Common Module Type 1
    if (!dataset.contains(tags::sop_class_uid)) return false;
    if (!dataset.contains(tags::sop_instance_uid)) return false;
    return true;
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::tags::columns, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::tags::frame_of_reference_uid, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, kcenon::pacs::services::validation::mr_tags::scanning_sequence, kcenon::pacs::services::validation::mr_tags::sequence_variant, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, and kcenon::pacs::core::tags::study_instance_uid.
Referenced by kcenon::pacs::services::validation::is_valid_mr_dataset().
set_options()
void kcenon::pacs::services::validation::mr_iod_validator::set_options (const mr_validation_options & options)
Set validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 135 of file mr_iod_validator.cpp.
{
    options_ = options;
}
References options(), and options_.
validate()
validation_result kcenon::pacs::services::validation::mr_iod_validator::validate (const core::dicom_dataset & dataset) const
Validate a DICOM dataset against MR IOD.
Parameters
dataset The dataset to validate
Returns
Validation result with all findings
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 53 of file mr_iod_validator.cpp.
{
    validation_result result;
    result.is_valid = true;
    // Validate mandatory modules (PS3.3 Table A.4-1)
    if (options_.check_type1 || options_.check_type2) {
        validate_patient_module(dataset, result.findings);
        validate_general_study_module(dataset, result.findings);
        validate_general_series_module(dataset, result.findings);
        validate_frame_of_reference_module(dataset, result.findings);
        validate_general_equipment_module(dataset, result.findings);
        validate_sop_common_module(dataset, result.findings);
    }
    if (options_.validate_mr_params) {
        validate_mr_image_module(dataset, result.findings);
    }
    if (options_.validate_pixel_data) {
        validate_image_pixel_module(dataset, result.findings);
    }
    // Determine overall validity
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
        if (options_.strict_mode &&
            finding.severity == validation_severity::warning) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References kcenon::pacs::services::validation::mr_validation_options::check_type1, kcenon::pacs::services::validation::mr_validation_options::check_type2, kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::services::validation::validation_result::is_valid, options_, kcenon::pacs::services::validation::mr_validation_options::strict_mode, validate_frame_of_reference_module(), validate_general_equipment_module(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_mr_image_module(), kcenon::pacs::services::validation::mr_validation_options::validate_mr_params, validate_patient_module(), kcenon::pacs::services::validation::mr_validation_options::validate_pixel_data, validate_sop_common_module(), and kcenon::pacs::services::validation::warning.
Referenced by kcenon::pacs::services::validation::validate_mr_iod().
validate_frame_of_reference_module()
void kcenon::pacs::services::validation::mr_iod_validator::validate_frame_of_reference_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 205 of file mr_iod_validator.cpp.
{
    // Frame of Reference UID is Type 1 for MR
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::frame_of_reference_uid,
                              "FrameOfReferenceUID", findings);
    }
    // Position Reference Indicator is Type 2
    if (options_.check_type2) {
        constexpr dicom_tag position_reference_indicator{0x0020, 0x1040};
        check_type2_attribute(dataset, position_reference_indicator,
                              "PositionReferenceIndicator", findings);
    }
}
References kcenon::pacs::services::validation::mr_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::mr_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::tags::frame_of_reference_uid, and options_.
Referenced by validate().
validate_general_equipment_module()
void kcenon::pacs::services::validation::mr_iod_validator::validate_general_equipment_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 223 of file mr_iod_validator.cpp.
{
    // Manufacturer is Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::manufacturer, "Manufacturer",
                              findings);
    }
}
References kcenon::pacs::services::validation::mr_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::tags::manufacturer, and options_.
Referenced by validate().
validate_general_series_module()
void kcenon::pacs::services::validation::mr_iod_validator::validate_general_series_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 184 of file mr_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::modality, "Modality", findings);
        check_type1_attribute(dataset, tags::series_instance_uid,
                              "SeriesInstanceUID", findings);
        // Modality must be "MR"
        check_modality(dataset, findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::series_number, "SeriesNumber",
                              findings);
    }
}
References check_modality(), kcenon::pacs::services::validation::mr_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::mr_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::tags::modality, options_, kcenon::pacs::core::tags::series_instance_uid, and kcenon::pacs::core::tags::series_number.
Referenced by validate().
validate_general_study_module()
void kcenon::pacs::services::validation::mr_iod_validator::validate_general_study_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 160 of file mr_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::study_instance_uid,
                              "StudyInstanceUID", findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::study_date, "StudyDate",
                              findings);
        check_type2_attribute(dataset, tags::study_time, "StudyTime",
                              findings);
        check_type2_attribute(dataset, tags::referring_physician_name,
                              "ReferringPhysicianName", findings);
        check_type2_attribute(dataset, tags::study_id, "StudyID", findings);
        check_type2_attribute(dataset, tags::accession_number,
                              "AccessionNumber", findings);
    }
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::services::validation::mr_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::mr_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::core::tags::study_time.
Referenced by validate().
validate_image_pixel_module()
void kcenon::pacs::services::validation::mr_iod_validator::validate_image_pixel_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 325 of file mr_iod_validator.cpp.
{
    // Type 1 attributes
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::samples_per_pixel,
                              "SamplesPerPixel", findings);
        check_type1_attribute(dataset, tags::photometric_interpretation,
                              "PhotometricInterpretation", findings);
        check_type1_attribute(dataset, tags::rows, "Rows", findings);
        check_type1_attribute(dataset, tags::columns, "Columns", findings);
        check_type1_attribute(dataset, tags::bits_allocated, "BitsAllocated",
                              findings);
        check_type1_attribute(dataset, tags::bits_stored, "BitsStored",
                              findings);
        check_type1_attribute(dataset, tags::high_bit, "HighBit", findings);
        check_type1_attribute(dataset, tags::pixel_representation,
                              "PixelRepresentation", findings);
        check_type1_attribute(dataset, tags::pixel_data, "PixelData",
                              findings);
    }
    // Validate pixel data consistency
    if (options_.validate_pixel_data) {
        check_pixel_data_consistency(dataset, findings);
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, check_pixel_data_consistency(), kcenon::pacs::services::validation::mr_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::tags::columns, kcenon::pacs::core::tags::high_bit, options_, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, and kcenon::pacs::services::validation::mr_validation_options::validate_pixel_data.
Referenced by validate().
validate_mr_image_module()
void kcenon::pacs::services::validation::mr_iod_validator::validate_mr_image_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 234 of file mr_iod_validator.cpp.
{
    // MR Image Module (PS3.3 Section C.8.3.1)
    // Type 1 attributes
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::image_type, "ImageType",
                              findings);
        check_type1_attribute(dataset, mr_tags::scanning_sequence,
                              "ScanningSequence", findings);
        check_type1_attribute(dataset, mr_tags::sequence_variant,
                              "SequenceVariant", findings);
    }
    // Type 2 attributes specific to MR Image Module
    if (options_.check_type2) {
        check_type2_attribute(dataset, mr_tags::scan_options, "ScanOptions",
                              findings);
        check_type2_attribute(dataset, mr_tags::mr_acquisition_type,
                              "MRAcquisitionType", findings);
        check_type2_attribute(dataset, mr_tags::echo_time, "EchoTime",
                              findings);
        check_type2_attribute(dataset, mr_tags::echo_train_length,
                              "EchoTrainLength", findings);
        check_type2_attribute(dataset, mr_tags::magnetic_field_strength,
                              "MagneticFieldStrength", findings);
    }
    // Type 2C - RepetitionTime is required if ImageType Value 1 is ORIGINAL
    if (options_.check_conditional) {
        if (dataset.contains(tags::image_type)) {
            auto image_type = dataset.get_string(tags::image_type);
            if (image_type.find("ORIGINAL") != std::string::npos &&
                !dataset.contains(mr_tags::repetition_time)) {
                findings.push_back(
                    {validation_severity::warning, mr_tags::repetition_time,
                     "RepetitionTime (0018,0080) missing - required when "
                     "ImageType Value 1 is ORIGINAL",
                     "MR-WARN-001"});
            }
        }
        // InversionTime is Type 2C - required if ScanningSequence contains IR
        if (dataset.contains(mr_tags::scanning_sequence)) {
            auto seq = dataset.get_string(mr_tags::scanning_sequence);
            if (seq.find("IR") != std::string::npos &&
                !dataset.contains(mr_tags::inversion_time)) {
                findings.push_back(
                    {validation_severity::warning, mr_tags::inversion_time,
                     "InversionTime (0018,0082) missing - required when "
                     "ScanningSequence contains IR",
                     "MR-WARN-002"});
            }
        }
        // SliceThickness informational check
        if (!dataset.contains(mr_tags::slice_thickness)) {
            findings.push_back(
                {validation_severity::info, mr_tags::slice_thickness,
                 "SliceThickness (0018,0050) not present - slice geometry "
                 "information unavailable",
                 "MR-INFO-001"});
        }
        // Image Position (Patient) is Type 1C - required if
        // Frame of Reference Module is present
        if (dataset.contains(tags::frame_of_reference_uid) &&
            !dataset.contains(mr_tags::image_position_patient)) {
            findings.push_back(
                {validation_severity::warning,
                 mr_tags::image_position_patient,
                 "ImagePositionPatient (0020,0032) missing - required when "
                 "Frame of Reference is present",
                 "MR-WARN-003"});
        }
        // Image Orientation (Patient) is Type 1C
        if (dataset.contains(tags::frame_of_reference_uid) &&
            !dataset.contains(mr_tags::image_orientation_patient)) {
            findings.push_back(
                {validation_severity::warning,
                 mr_tags::image_orientation_patient,
                 "ImageOrientationPatient (0020,0037) missing - required when "
                 "Frame of Reference is present",
                 "MR-WARN-004"});
        }
    }
}
References kcenon::pacs::services::validation::mr_validation_options::check_conditional, kcenon::pacs::services::validation::mr_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::mr_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::mr_tags::echo_time, kcenon::pacs::services::validation::mr_tags::echo_train_length, kcenon::pacs::core::tags::frame_of_reference_uid, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::mr_tags::image_orientation_patient, kcenon::pacs::services::validation::mr_tags::image_position_patient, kcenon::pacs::core::tags::image_type, kcenon::pacs::services::validation::info, kcenon::pacs::services::validation::mr_tags::inversion_time, kcenon::pacs::services::validation::mr_tags::magnetic_field_strength, kcenon::pacs::services::validation::mr_tags::mr_acquisition_type, options_, kcenon::pacs::services::validation::mr_tags::repetition_time, kcenon::pacs::services::validation::mr_tags::scan_options, kcenon::pacs::services::validation::mr_tags::scanning_sequence, kcenon::pacs::services::validation::mr_tags::sequence_variant, kcenon::pacs::services::validation::mr_tags::slice_thickness, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_patient_module()
void kcenon::pacs::services::validation::mr_iod_validator::validate_patient_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 143 of file mr_iod_validator.cpp.
{
    // Patient Module - All attributes are Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::patient_name, "PatientName",
                              findings);
        check_type2_attribute(dataset, tags::patient_id, "PatientID",
                              findings);
        check_type2_attribute(dataset, tags::patient_birth_date,
                              "PatientBirthDate", findings);
        check_type2_attribute(dataset, tags::patient_sex, "PatientSex",
                              findings);
    }
}
References kcenon::pacs::services::validation::mr_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, and kcenon::pacs::core::tags::patient_sex.
Referenced by validate().
validate_sop_common_module()
void kcenon::pacs::services::validation::mr_iod_validator::validate_sop_common_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 354 of file mr_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::sop_class_uid, "SOPClassUID",
                              findings);
        check_type1_attribute(dataset, tags::sop_instance_uid,
                              "SOPInstanceUID", findings);
    }
    // Validate SOP Class UID is an MR storage class
    if (dataset.contains(tags::sop_class_uid)) {
        auto sop_class = dataset.get_string(tags::sop_class_uid);
        if (!sop_classes::is_mr_storage_sop_class(sop_class)) {
            findings.push_back(
                {validation_severity::error, tags::sop_class_uid,
                 "SOPClassUID is not a recognized MR Storage SOP Class: " +
                     sop_class,
                 "MR-ERR-001"});
        }
    }
}
References kcenon::pacs::services::validation::mr_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_mr_storage_sop_class(), options_, kcenon::pacs::core::tags::sop_class_uid, and kcenon::pacs::core::tags::sop_instance_uid.
Referenced by validate().
Member Data Documentation
options_
mr_validation_options kcenon::pacs::services::validation::mr_iod_validator::options_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/validation/mr_iod_validator.hpp.
Definition at line 292 of file mr_iod_validator.hpp.
Referenced by options(), set_options(), validate(), validate_frame_of_reference_module(), validate_general_equipment_module(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_mr_image_module(), validate_patient_module(), and validate_sop_common_module().
The documentation for this class was generated from the following files:
include/pacs/services/validation/mr_iod_validator.hpp
src/services/validation/mr_iod_validator.cpp