PACS System: kcenon::pacs::di::test::TestContainerBuilder Class Reference
kcenon::pacs::di::test::TestContainerBuilder Class Reference
#include <test_support.h>
Public Member Functions
TestContainerBuilder ()=default
TestContainerBuilder & with_storage (std::shared_ptr< MockStorage > storage)
Use a specific mock storage instance.
TestContainerBuilder & with_mock_storage ()
Create and use a new mock storage.
TestContainerBuilder & with_network (std::shared_ptr< MockNetwork > network)
Use a specific mock network instance.
TestContainerBuilder & with_mock_network ()
Create and use a new mock network.
std::shared_ptr< kcenon::common::di::service_container > build ()
Build the configured container.
std::shared_ptr< MockStorage > storage () const
Get the mock storage instance (for test assertions)
std::shared_ptr< MockNetwork > network () const
Get the mock network instance (for test assertions)
Private Attributes
std::shared_ptr< MockStorage > mock_storage_
std::shared_ptr< MockNetwork > mock_network_
Detailed Description
Definition at line 281 of file test_support.h.
Constructor & Destructor Documentation
TestContainerBuilder()
kcenon::pacs::di::test::TestContainerBuilder::TestContainerBuilder () default
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h.
Member Function Documentation
build()
std::shared_ptr< kcenon::common::di::service_container > kcenon::pacs::di::test::TestContainerBuilder::build () inline nodiscard
Build the configured container.
Returns
Shared pointer to configured service container
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h.
Definition at line 322 of file test_support.h.
{
        auto container = std::make_shared<kcenon::common::di::service_container>();
        if (mock_storage_) {
            container->register_instance<IDicomStorage>(mock_storage_);
        }
        if (mock_network_) {
            container->register_instance<IDicomNetwork>(mock_network_);
        }
        return container;
    }
References mock_network_, and mock_storage_.
Referenced by kcenon::pacs::di::test::create_test_container().
network()
std::shared_ptr< MockNetwork > kcenon::pacs::di::test::TestContainerBuilder::network () const inline nodiscard
Get the mock network instance (for test assertions)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h.
Definition at line 346 of file test_support.h.
{
        return mock_network_;
    }
References mock_network_.
Referenced by with_network().
storage()
std::shared_ptr< MockStorage > kcenon::pacs::di::test::TestContainerBuilder::storage () const inline nodiscard
Get the mock storage instance (for test assertions)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h.
Definition at line 339 of file test_support.h.
{
        return mock_storage_;
    }
References mock_storage_.
Referenced by with_storage().
with_mock_network()
TestContainerBuilder & kcenon::pacs::di::test::TestContainerBuilder::with_mock_network () inline
Create and use a new mock network.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h.
Definition at line 312 of file test_support.h.
{
        mock_network_ = std::make_shared<MockNetwork>();
        return *this;
    }
References mock_network_.
Referenced by kcenon::pacs::di::test::create_test_container().
with_mock_storage()
TestContainerBuilder & kcenon::pacs::di::test::TestContainerBuilder::with_mock_storage () inline
Create and use a new mock storage.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h.
Definition at line 296 of file test_support.h.
{
        mock_storage_ = std::make_shared<MockStorage>();
        return *this;
    }
References mock_storage_.
Referenced by kcenon::pacs::di::test::create_test_container().
with_network()
TestContainerBuilder & kcenon::pacs::di::test::TestContainerBuilder::with_network (std::shared_ptr< MockNetwork > network) inline
Use a specific mock network instance.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h.
Definition at line 304 of file test_support.h.
{
        mock_network_ = std::move(network);
        return *this;
    }
References mock_network_, and network().
with_storage()
TestContainerBuilder & kcenon::pacs::di::test::TestContainerBuilder::with_storage (std::shared_ptr< MockStorage > storage) inline
Use a specific mock storage instance.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h.
Definition at line 288 of file test_support.h.
{
        mock_storage_ = std::move(storage);
        return *this;
    }
References mock_storage_, and storage().
Member Data Documentation
mock_network_
std::shared_ptr<MockNetwork> kcenon::pacs::di::test::TestContainerBuilder::mock_network_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h.
Definition at line 352 of file test_support.h.
Referenced by build(), network(), with_mock_network(), and with_network().
mock_storage_
std::shared_ptr<MockStorage> kcenon::pacs::di::test::TestContainerBuilder::mock_storage_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h.
Definition at line 351 of file test_support.h.
Referenced by build(), storage(), with_mock_storage(), and with_storage().
The documentation for this class was generated from the following file:
include/kcenon/pacs/di/test_support.h