PACS System: kcenon::pacs::di::LoggerService Class Reference
kcenon::pacs::di::LoggerService Class Reference final
Default implementation of ILogger using logger_adapter.
#include <ilogger.hpp>
Public Member Functions
LoggerService ()=default
~LoggerService () override=default
void trace (std::string_view message) override
Log a trace-level message.
void debug (std::string_view message) override
Log a debug-level message.
void info (std::string_view message) override
Log an info-level message.
void warn (std::string_view message) override
Log a warning-level message.
void error (std::string_view message) override
Log an error-level message.
void fatal (std::string_view message) override
Log a fatal-level message.
bool is_enabled (integration::log_level level) const noexcept override
Check if a log level is enabled.
Public Member Functions inherited from kcenon::pacs::di::ILogger
virtual ~ILogger ()=default
template<typename... Args>
void trace_fmt (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args)
Log a formatted trace-level message.
template<typename... Args>
void debug_fmt (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args)
Log a formatted debug-level message.
template<typename... Args>
void info_fmt (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args)
Log a formatted info-level message.
template<typename... Args>
void warn_fmt (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args)
Log a formatted warning-level message.
template<typename... Args>
void error_fmt (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args)
Log a formatted error-level message.
template<typename... Args>
void fatal_fmt (kcenon::pacs::compat::format_string< Args... > fmt, Args &&... args)
Log a formatted fatal-level message.
Additional Inherited Members
Protected Member Functions inherited from kcenon::pacs::di::ILogger
ILogger ()=default
ILogger (const ILogger &)=default
ILogger & operator= (const ILogger &)=default
ILogger (ILogger &&)=default
ILogger & operator= (ILogger &&)=default
Detailed Description
Default implementation of ILogger using logger_adapter.
LoggerService delegates all logging operations to the static logger_adapter methods, providing dependency injection support for the existing logging infrastructure.
Thread Safety:
All methods are thread-safe (delegates to thread-safe logger_adapter)
Definition at line 250 of file ilogger.hpp.
Constructor & Destructor Documentation
LoggerService()
kcenon::pacs::di::LoggerService::LoggerService () default
~LoggerService()
kcenon::pacs::di::LoggerService::~LoggerService () override default
Member Function Documentation
debug()
void kcenon::pacs::di::LoggerService::debug (std::string_view message) inline override virtual
Log a debug-level message.
Parameters
message The message to log
Implements kcenon::pacs::di::ILogger.
Definition at line 259 of file ilogger.hpp.
{
        integration::logger_adapter::log(integration::log_level::debug, std::string{message});
    }
References kcenon::pacs::integration::debug, and kcenon::pacs::integration::logger_adapter::log().
error()
void kcenon::pacs::di::LoggerService::error (std::string_view message) inline override virtual
Log an error-level message.
Parameters
message The message to log
Implements kcenon::pacs::di::ILogger.
Definition at line 271 of file ilogger.hpp.
{
        integration::logger_adapter::log(integration::log_level::error, std::string{message});
    }
References kcenon::pacs::integration::error, and kcenon::pacs::integration::logger_adapter::log().
fatal()
void kcenon::pacs::di::LoggerService::fatal (std::string_view message) inline override virtual
Log a fatal-level message.
Parameters
message The message to log
Implements kcenon::pacs::di::ILogger.
Definition at line 275 of file ilogger.hpp.
{
        integration::logger_adapter::log(integration::log_level::fatal, std::string{message});
    }
References kcenon::pacs::integration::fatal, and kcenon::pacs::integration::logger_adapter::log().
info()
void kcenon::pacs::di::LoggerService::info (std::string_view message) inline override virtual
Log an info-level message.
Parameters
message The message to log
Implements kcenon::pacs::di::ILogger.
Definition at line 263 of file ilogger.hpp.
{
        integration::logger_adapter::log(integration::log_level::info, std::string{message});
    }
References kcenon::pacs::integration::info, and kcenon::pacs::integration::logger_adapter::log().
is_enabled()
bool kcenon::pacs::di::LoggerService::is_enabled (integration::log_level level) const inline override virtual noexcept
Check if a log level is enabled.
Parameters
level The level to check
Returns
true if messages at this level will be logged
Implements kcenon::pacs::di::ILogger.
Definition at line 279 of file ilogger.hpp.
{
        return integration::logger_adapter::is_level_enabled(level);
    }
References kcenon::pacs::integration::logger_adapter::is_level_enabled().
trace()
void kcenon::pacs::di::LoggerService::trace (std::string_view message) inline override virtual
Log a trace-level message.
Parameters
message The message to log
Implements kcenon::pacs::di::ILogger.
Definition at line 255 of file ilogger.hpp.
{
        integration::logger_adapter::log(integration::log_level::trace, std::string{message});
    }
References kcenon::pacs::integration::logger_adapter::log(), and kcenon::pacs::integration::trace.
warn()
void kcenon::pacs::di::LoggerService::warn (std::string_view message) inline override virtual
Log a warning-level message.
Parameters
message The message to log
Implements kcenon::pacs::di::ILogger.
Definition at line 267 of file ilogger.hpp.
{
        integration::logger_adapter::log(integration::log_level::warn, std::string{message});
    }
References kcenon::pacs::integration::logger_adapter::log(), and kcenon::pacs::integration::warn.
The documentation for this class was generated from the following file:
include/pacs/di/ilogger.hpp