PACS System: kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl Class Reference
kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl Class Reference
PIMPL implementation for jpeg_lossless_codec.
Public Member Functions
impl (int predictor, int point_transform)
int predictor () const noexcept
int point_transform () const noexcept
codec_result encode (std::span< const uint8_t > pixel_data, const image_params &params, const compression_options &options) const
codec_result decode (std::span< const uint8_t > compressed_data, const image_params &params) const
Private Member Functions
bool valid_for_jpeg_lossless (const image_params &params) const noexcept
codec_result encode_frame (std::span< const uint8_t > pixel_data, const image_params &params) const
void write_sof3 (std::vector< uint8_t > &output, const image_params &params) const
void write_dht (std::vector< uint8_t > &output, int precision) const
void write_sos (std::vector< uint8_t > &output) const
codec_result decode_frame (std::span< const uint8_t > compressed_data, const image_params &params) const
int decode_huffman_category (bit_reader &reader, const huffman_table &ht) const
Private Attributes
int predictor_
int point_transform_
Detailed Description
PIMPL implementation for jpeg_lossless_codec.
Definition at line 283 of file jpeg_lossless_codec.cpp.
Constructor & Destructor Documentation
impl()
kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::impl (int predictor, int point_transform) inline
Definition at line 285 of file jpeg_lossless_codec.cpp.
        : predictor_(std::clamp(predictor, 1, 7)),
          point_transform_(std::clamp(point_transform, 0, 15)) {}
Member Function Documentation
decode()
codec_result kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::decode (std::span< const uint8_t > compressed_data, const image_params & params) const inline
Definition at line 320 of file jpeg_lossless_codec.cpp.
{
        if (compressed_data.empty()) {
            return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error, "Empty compressed data");
        }
        try {
            return decode_frame(compressed_data, params);
        } catch (const std::exception& e) {
            return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error, std::string("JPEG Lossless decoding failed: ") + e.what());
        }
    }
References decode_frame(), and kcenon::pacs::error_codes::decompression_error.
decode_frame()
codec_result kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::decode_frame (std::span< const uint8_t > compressed_data, const image_params & params) const inline private
Definition at line 547 of file jpeg_lossless_codec.cpp.
{
        const uint8_t* data = compressed_data.data();
        size_t size = compressed_data.size();
        size_t pos = 0;
        // Parse SOI
        if (size < 2 || data[0] != kMarkerPrefix || data[1] != kSOI) {
            return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error, "Invalid JPEG: missing SOI marker");
        }
        pos = 2;
        int precision = 0;
        int width = 0;
        int height = 0;
        int predictor = predictor_;
        int point_transform = point_transform_;
        huffman_table ht;
        bool found_sof = false;
        bool found_sos = false;
        size_t scan_start = 0;
        // Parse markers
        while (pos < size - 1) {
            if (data[pos] != kMarkerPrefix) {
                return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error, "Invalid JPEG: expected marker");
            }
            uint8_t marker = data[pos + 1];
            pos += 2;
            if (marker == kEOI) {
                break;
            }
            // Skip fill bytes (0xFF)
            if (marker == kMarkerPrefix) {
                --pos;
                continue;
            }
            // Markers with no length
            if (marker >= 0xD0 && marker <= 0xD7) {  // RST markers
                continue;
            }
            // Read marker length
            if (pos + 2 > size) {
                return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error, "Invalid JPEG: truncated marker");
            }
            uint16_t length = read_be16(&data[pos]);
            pos += 2;
            if (pos + length - 2 > size) {
                return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error, "Invalid JPEG: truncated marker data");
            }
            if (marker == kSOF3) {
                // Parse SOF3
                if (length < 8) {
                    return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error, "Invalid SOF3 marker");
                }
                precision = data[pos];
                height = read_be16(&data[pos + 1]);
                width = read_be16(&data[pos + 3]);
                found_sof = true;
            } else if (marker == kDHT) {
                // Parse DHT - use the table from the file
                // For simplicity, we use our default table
                // A full implementation would parse and use the embedded table
            } else if (marker == kSOS) {
                // Parse SOS
                if (length >= 6) {
                    predictor = data[pos + 3];
                    point_transform = data[pos + 5] & 0x0F;
                }
                found_sos = true;
                pos += length - 2;
                scan_start = pos;
                break;
            }
            pos += length - 2;
        }
        if (!found_sof || !found_sos) {
            return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error, "Invalid JPEG: missing required markers");
        }
        // Validate against params if provided
        if (params.width > 0 && params.width != width) {
            return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error, "Width mismatch");
        }
        if (params.height > 0 && params.height != height) {
            return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error, "Height mismatch");
        }
        // Find scan data end (EOI marker)
        size_t scan_end = size;
        for (size_t i = scan_start; i < size - 1; ++i) {
            if (data[i] == kMarkerPrefix && data[i + 1] == kEOI) {
                scan_end = i;
                break;
            }
        }
        // Decode image data
        bool is_16bit = precision > 8;
        size_t output_size = static_cast<size_t>(width) * height * (is_16bit ? 2 : 1);
        std::vector<uint8_t> output(output_size);
        bit_reader reader(&data[scan_start], scan_end - scan_start);
        auto set_pixel = [&](int x, int y, int value) {
            size_t idx = static_cast<size_t>(y) * width + x;
            if (is_16bit) {
                idx *= 2;
                output[idx] = static_cast<uint8_t>(value & 0xFF);
                output[idx + 1] = static_cast<uint8_t>((value >> 8) & 0xFF);
            } else {
                output[idx] = static_cast<uint8_t>(value);
            }
        };
        auto get_decoded_pixel = [&](int x, int y) -> int {
            if (x < 0 || y < 0) return 0;
            size_t idx = static_cast<size_t>(y) * width + x;
            if (is_16bit) {
                idx *= 2;
                return output[idx] | (output[idx + 1] << 8);
            }
            return output[idx];
        };
        int mod_range = 1 << (precision - point_transform);
        int max_value = (1 << precision) - 1;
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                // Decode Huffman category
                int cat = decode_huffman_category(reader, ht);
                if (cat < 0 || cat > 16) {
                    return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error, "Invalid Huffman code");
                }
                // Read additional bits
                int encoded = 0;
                if (cat > 0) {
                    encoded = reader.read_bits(cat);
                }
                // Decode difference
                int diff = decode_diff(encoded, cat);
                // Compute prediction
                int ra = get_decoded_pixel(x - 1, y);
                int rb = get_decoded_pixel(x, y - 1);
                int rc = get_decoded_pixel(x - 1, y - 1);
                int pred;
                if (x == 0 && y == 0) {
                    pred = 1 << (precision - point_transform - 1);
                } else if (y == 0) {
                    pred = ra >> point_transform;
                } else if (x == 0) {
                    pred = rb >> point_transform;
                } else {
                    pred = predict(ra >> point_transform,
                                   rb >> point_transform,
                                   rc >> point_transform,
                                   predictor);
                }
                // Reconstruct pixel
                int shifted_pixel = (pred + diff) & (mod_range - 1);
                int pixel = shifted_pixel << point_transform;
                pixel = std::clamp(pixel, 0, max_value);
                set_pixel(x, y, pixel);
            }
        }
        // Build output parameters
        image_params output_params;
        output_params.width = static_cast<uint16_t>(width);
        output_params.height = static_cast<uint16_t>(height);
        output_params.bits_allocated = is_16bit ? 16 : 8;
        output_params.bits_stored = static_cast<uint16_t>(precision);
        output_params.high_bit = static_cast<uint16_t>(precision - 1);
        output_params.samples_per_pixel = 1;
        output_params.planar_configuration = 0;
        output_params.pixel_representation = 0;
        output_params.photometric = photometric_interpretation::monochrome2;
        return kcenon::pacs::ok<compression_result>(compression_result{std::move(output), output_params});
    }
References kcenon::pacs::encoding::compression::image_params::bits_allocated, kcenon::pacs::encoding::compression::image_params::bits_stored, decode_huffman_category(), kcenon::pacs::error_codes::decompression_error, kcenon::pacs::encoding::compression::image_params::height, kcenon::pacs::encoding::compression::image_params::high_bit, kcenon::pacs::encoding::compression::monochrome2, kcenon::pacs::encoding::compression::image_params::photometric, kcenon::pacs::encoding::compression::image_params::pixel_representation, kcenon::pacs::encoding::compression::image_params::planar_configuration, point_transform(), point_transform_, predictor(), predictor_, kcenon::pacs::encoding::read_be16(), kcenon::pacs::encoding::compression::image_params::samples_per_pixel, and kcenon::pacs::encoding::compression::image_params::width.
Referenced by decode().
decode_huffman_category()
int kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::decode_huffman_category (bit_reader & reader, const huffman_table & ht) const inline private
Definition at line 746 of file jpeg_lossless_codec.cpp.
{
        // Simple Huffman decoding - match against known codes
        uint32_t code = 0;
        for (int bits = 1; bits <= 16; ++bits) {
            code = (code << 1) | reader.read_bits(1);
            for (int cat = 0; cat <= 16; ++cat) {
                if (ht.code_lengths[cat] == bits && ht.codes[cat] == code) {
                    return cat;
                }
            }
        }
        return -1;  // Error
    }
References code.
Referenced by decode_frame().
encode()
codec_result kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::encode (std::span< const uint8_t > pixel_data, const image_params & params, const compression_options & options) const inline
Definition at line 292 of file jpeg_lossless_codec.cpp.
{
        if (pixel_data.empty()) {
            return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error, "Empty pixel data");
        }
        if (!valid_for_jpeg_lossless(params)) {
            return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error,
                "Invalid parameters for JPEG Lossless: requires 8/12/16-bit grayscale");
        }
        size_t expected_size = params.frame_size_bytes();
        if (pixel_data.size() != expected_size) {
            return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error,
                "Pixel data size mismatch: expected " + std::to_string(expected_size) +
                ", got " + std::to_string(pixel_data.size()));
        }
        try {
            return encode_frame(pixel_data, params);
        } catch (const std::exception& e) {
            return kcenon::pacs::pacs_error<compression_result>(kcenon::pacs::error_codes::decompression_error, std::string("JPEG Lossless encoding failed: ") + e.what());
        }
    }
References kcenon::pacs::error_codes::decompression_error, encode_frame(), kcenon::pacs::encoding::compression::image_params::frame_size_bytes(), and valid_for_jpeg_lossless().
encode_frame()
codec_result kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::encode_frame (std::span< const uint8_t > pixel_data, const image_params & params) const inline private
Definition at line 352 of file jpeg_lossless_codec.cpp.
{
        std::vector<uint8_t> output;
        output.reserve(pixel_data.size());  // Reserve worst-case
        int precision = params.bits_stored;
        bool is_16bit = params.bits_allocated == 16;
        // Write SOI marker
        output.push_back(kMarkerPrefix);
        output.push_back(kSOI);
        // Write SOF3 (Start of Frame - Lossless)
        write_sof3(output, params);
        // Write DHT (Huffman Table)
        write_dht(output, precision);
        // Write SOS (Start of Scan)
        write_sos(output);
        // Encode image data
        huffman_table ht;
        bit_writer writer(output);
        int width = params.width;
        int height = params.height;
        auto get_pixel = [&](int x, int y) -> int {
            if (x < 0 || y < 0) return 0;
            size_t idx = static_cast<size_t>(y) * width + x;
            if (is_16bit) {
                idx *= 2;
                // Little-endian pixel data
                return pixel_data[idx] | (pixel_data[idx + 1] << 8);
            }
            return pixel_data[idx];
        };
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                int pixel = get_pixel(x, y);
                int ra = get_pixel(x - 1, y);
                int rb = get_pixel(x, y - 1);
                int rc = get_pixel(x - 1, y - 1);
                // Apply point transform
                int shifted_pixel = pixel >> point_transform_;
                // Compute prediction
                int pred;
                if (x == 0 && y == 0) {
                    // First pixel: use 2^(P-Pt-1) as prediction
                    pred = 1 << (precision - point_transform_ - 1);
                } else if (y == 0) {
                    // First row: use Ra
                    pred = ra >> point_transform_;
                } else if (x == 0) {
                    // First column: use Rb
                    pred = rb >> point_transform_;
                } else {
                    // Use selected predictor
                    pred = predict(ra >> point_transform_,
                                   rb >> point_transform_,
                                   rc >> point_transform_,
                                   predictor_);
                }
                // Compute difference
                int diff = shifted_pixel - pred;
                // Modulo operation for precision
                int mod_range = 1 << (precision - point_transform_);
                if (diff < -mod_range / 2) {
                    diff += mod_range;
                } else if (diff >= mod_range / 2) {
                    diff -= mod_range;
                }
                // Encode difference
                int cat = category(diff);
                int encoded = encode_diff(diff, cat);
                // Write Huffman code for category
                writer.write_bits(ht.codes[cat], ht.code_lengths[cat]);
                // Write additional bits for actual value
                if (cat > 0) {
                    writer.write_bits(static_cast<uint32_t>(encoded), cat);
                }
            }
        }
        writer.flush();
        // Write EOI marker
        output.push_back(kMarkerPrefix);
        output.push_back(kEOI);
        image_params output_params = params;
        return kcenon::pacs::ok<compression_result>(compression_result{std::move(output), output_params});
    }
References kcenon::pacs::encoding::compression::image_params::bits_allocated, kcenon::pacs::encoding::compression::image_params::bits_stored, kcenon::pacs::encoding::compression::image_params::height, point_transform_, predictor_, kcenon::pacs::encoding::compression::image_params::width, write_dht(), write_sof3(), and write_sos().
Referenced by encode().
point_transform()
int kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::point_transform () const inline noexcept
Definition at line 290 of file jpeg_lossless_codec.cpp.
{ return point_transform_; }
References point_transform_.
Referenced by decode_frame().
predictor()
int kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::predictor () const inline noexcept
Definition at line 289 of file jpeg_lossless_codec.cpp.
{ return predictor_; }
References predictor_.
Referenced by decode_frame().
valid_for_jpeg_lossless()
bool kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::valid_for_jpeg_lossless (const image_params & params) const inline private noexcept
Definition at line 336 of file jpeg_lossless_codec.cpp.
{
        // JPEG Lossless supports 2-16 bit precision
        if (params.bits_stored < kMinPrecision || params.bits_stored > kMaxPrecision) {
            return false;
        }
        // bits_allocated must be 8 or 16
        if (params.bits_allocated != 8 && params.bits_allocated != 16) {
            return false;
        }
        // Grayscale only for DICOM JPEG Lossless
        if (params.samples_per_pixel != 1) {
            return false;
        }
        return true;
    }
Referenced by encode().
write_dht()
void kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::write_dht (std::vector< uint8_t > & output, int precision) const inline private
Definition at line 483 of file jpeg_lossless_codec.cpp.
{
        huffman_table ht;
        output.push_back(kMarkerPrefix);
        output.push_back(kDHT);
        // Calculate table data
        std::vector<uint8_t> table_data;
        table_data.push_back(0x00);  // DC table, ID 0
        // Count codes of each length
        std::array<int, 16> length_counts{};
        for (int i = 0; i <= 16; ++i) {
            int len = ht.code_lengths[i];
            if (len >= 1 && len <= 16) {
                ++length_counts[len - 1];
            }
        }
        // Write length counts
        for (int i = 0; i < 16; ++i) {
            table_data.push_back(static_cast<uint8_t>(length_counts[i]));
        }
        // Write symbols in order of code length
        for (int len = 1; len <= 16; ++len) {
            for (int i = 0; i <= 16; ++i) {
                if (ht.code_lengths[i] == len) {
                    table_data.push_back(static_cast<uint8_t>(i));
                }
            }
        }
        // Write length
        write_be16(output, static_cast<uint16_t>(2 + table_data.size()));
        // Write table data
        output.insert(output.end(), table_data.begin(), table_data.end());
    }
References kcenon::pacs::encoding::write_be16().
Referenced by encode_frame().
write_sof3()
void kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::write_sof3 (std::vector< uint8_t > & output, const image_params & params) const inline private
Definition at line 457 of file jpeg_lossless_codec.cpp.
{
        output.push_back(kMarkerPrefix);
        output.push_back(kSOF3);
        // Length = 8 + 3 * number_of_components
        uint16_t length = 8 + 3 * 1;  // 1 component (grayscale)
        write_be16(output, length);
        // Precision
        output.push_back(static_cast<uint8_t>(params.bits_stored));
        // Height
        write_be16(output, params.height);
        // Width
        write_be16(output, params.width);
        // Number of components
        output.push_back(1);
        // Component specification
        output.push_back(1);  // Component ID
        output.push_back(0x11);  // Sampling factors (1x1)
        output.push_back(0);  // Quantization table (not used for lossless)
    }
References kcenon::pacs::encoding::compression::image_params::bits_stored, kcenon::pacs::encoding::compression::image_params::height, kcenon::pacs::encoding::compression::image_params::width, and kcenon::pacs::encoding::write_be16().
Referenced by encode_frame().
write_sos()
void kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::write_sos (std::vector< uint8_t > & output) const inline private
Definition at line 523 of file jpeg_lossless_codec.cpp.
{
        output.push_back(kMarkerPrefix);
        output.push_back(kSOS);
        // Length
        write_be16(output, 8);  // Fixed length for 1 component
        // Number of components
        output.push_back(1);
        // Component selector and Huffman table
        output.push_back(1);  // Component ID
        output.push_back(0x00);  // DC=0, AC=0
        // Spectral selection (predictor for lossless)
        output.push_back(static_cast<uint8_t>(predictor_));
        // Spectral selection end (not used)
        output.push_back(0);
        // Successive approximation (point transform)
        output.push_back(static_cast<uint8_t>(point_transform_));
    }
References point_transform_, predictor_, and kcenon::pacs::encoding::write_be16().
Referenced by encode_frame().
Member Data Documentation
point_transform_
int kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::point_transform_ private
Definition at line 761 of file jpeg_lossless_codec.cpp.
Referenced by decode_frame(), encode_frame(), point_transform(), and write_sos().
predictor_
int kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::predictor_ private
Definition at line 760 of file jpeg_lossless_codec.cpp.
Referenced by decode_frame(), encode_frame(), predictor(), and write_sos().
The documentation for this class was generated from the following file:
src/encoding/compression/jpeg_lossless_codec.cpp