PACS System: kcenon::pacs::services::xds::imaging_document_consumer Class Reference
kcenon::pacs::services::xds::imaging_document_consumer Class Reference
#include <imaging_document_consumer.hpp>
Public Member Functions
imaging_document_consumer ()=default
imaging_document_consumer (const imaging_document_consumer_config &config)
registry_query_result query_registry (const registry_query_params &params) const
Query the XDS registry for imaging documents.
document_retrieval_result retrieve_document (const document_reference &doc_ref) const
Retrieve a specific document from the XDS repository.
document_retrieval_result extract_references (const core::dicom_dataset &kos_dataset) const
Extract image references from a KOS dataset.
std::string build_wado_rs_url (const std::string &study_uid, const std::string &series_uid, const std::string &instance_uid) const
Build a WADO-RS URL for retrieving a specific instance.
const imaging_document_consumer_config & config () const noexcept
Get current configuration.
void set_config (const imaging_document_consumer_config &config)
Set configuration.
Private Attributes
imaging_document_consumer_config config_
Detailed Description
Definition at line 230 of file imaging_document_consumer.hpp.
Constructor & Destructor Documentation
imaging_document_consumer() [1/2]
kcenon::pacs::services::xds::imaging_document_consumer::imaging_document_consumer () default
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_consumer.hpp.
imaging_document_consumer() [2/2]
kcenon::pacs::services::xds::imaging_document_consumer::imaging_document_consumer (const imaging_document_consumer_config & config) explicit
Definition at line 62 of file imaging_document_consumer.cpp.
    : config_(config) {}
Member Function Documentation
build_wado_rs_url()
std::string kcenon::pacs::services::xds::imaging_document_consumer::build_wado_rs_url (const std::string & study_uid, const std::string & series_uid, const std::string & instance_uid) const
Build a WADO-RS URL for retrieving a specific instance.
Constructs a WADO-RS retrieve URL based on the configured WADO-RS base URL and the instance identifiers.
Parameters
study_uid Study Instance UID
series_uid Series Instance UID
instance_uid SOP Instance UID
Returns
The WADO-RS retrieve URL
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_consumer.hpp.
Definition at line 167 of file imaging_document_consumer.cpp.
{
    std::ostringstream url;
    url << config_.wado_rs_url;
    // Ensure base URL doesn't end with '/'
    if (!config_.wado_rs_url.empty() && config_.wado_rs_url.back() == '/') {
        // Remove the trailing '/' already added
    } else {
        url << '/';
    }
    url << "studies/" << study_uid
        << "/series/" << series_uid
        << "/instances/" << instance_uid;
    return url.str();
}
References config_, and kcenon::pacs::services::xds::imaging_document_consumer_config::wado_rs_url.
config()
const imaging_document_consumer_config & kcenon::pacs::services::xds::imaging_document_consumer::config () const noexcept
Get current configuration.
Returns
Reference to configuration
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_consumer.hpp.
Definition at line 190 of file imaging_document_consumer.cpp.
{
    return config_;
}
References config_.
Referenced by set_config().
extract_references()
document_retrieval_result kcenon::pacs::services::xds::imaging_document_consumer::extract_references (const core::dicom_dataset & kos_dataset) const
Extract image references from a KOS dataset.
Parses a KOS (Key Object Selection) document and extracts the referenced SOP Instance UIDs, organized by study and series.
Parameters
kos_dataset The KOS dataset to parse
Returns
Retrieval result with extracted references
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_consumer.hpp.
Definition at line 103 of file imaging_document_consumer.cpp.
{
    document_retrieval_result result;
    result.success = true;
    // Parse Current Requested Procedure Evidence Sequence (0040,A375)
    const auto* evidence_elem = kos_dataset.get(
        consumer_tags::current_requested_procedure_evidence_sequence);
    if (!evidence_elem || !evidence_elem->is_sequence()) {
        result.error_message = "KOS document does not contain evidence sequence";
        result.success = false;
        return result;
    }
    for (const auto& study_item : evidence_elem->sequence_items()) {
        // Extract Study Instance UID
        auto study_uid = study_item.get_string(tags::study_instance_uid);
        if (!study_uid.empty()) {
            if (std::find(result.referenced_study_uids.begin(),
                         result.referenced_study_uids.end(),
                         study_uid) == result.referenced_study_uids.end()) {
                result.referenced_study_uids.push_back(study_uid);
            }
        }
        // Parse Referenced Series Sequence
        const auto* series_elem = study_item.get(
            consumer_tags::referenced_series_sequence);
        if (!series_elem || !series_elem->is_sequence()) {
            continue;
        }
        for (const auto& series_item : series_elem->sequence_items()) {
            auto series_uid = series_item.get_string(tags::series_instance_uid);
            if (!series_uid.empty()) {
                if (std::find(result.referenced_series_uids.begin(),
                             result.referenced_series_uids.end(),
                             series_uid) == result.referenced_series_uids.end()) {
                    result.referenced_series_uids.push_back(series_uid);
                }
            }
            // Parse Referenced SOP Sequence
            const auto* sop_elem = series_item.get(
                consumer_tags::referenced_sop_sequence);
            if (!sop_elem || !sop_elem->is_sequence()) {
                continue;
            }
            for (const auto& sop_item : sop_elem->sequence_items()) {
                auto instance_uid = sop_item.get_string(
                    consumer_tags::referenced_sop_instance_uid);
                if (!instance_uid.empty()) {
                    result.referenced_instance_uids.push_back(instance_uid);
                }
            }
        }
    }
    return result;
}
References kcenon::pacs::services::xds::consumer_tags::current_requested_procedure_evidence_sequence, kcenon::pacs::services::xds::document_retrieval_result::error_message, kcenon::pacs::core::dicom_dataset::get(), kcenon::pacs::services::xds::document_retrieval_result::referenced_instance_uids, kcenon::pacs::services::xds::consumer_tags::referenced_series_sequence, kcenon::pacs::services::xds::document_retrieval_result::referenced_series_uids, kcenon::pacs::services::xds::consumer_tags::referenced_sop_instance_uid, kcenon::pacs::services::xds::consumer_tags::referenced_sop_sequence, kcenon::pacs::services::xds::document_retrieval_result::referenced_study_uids, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::services::xds::document_retrieval_result::success.
query_registry()
registry_query_result kcenon::pacs::services::xds::imaging_document_consumer::query_registry (const registry_query_params & params) const
Query the XDS registry for imaging documents.
Performs an ITI-18 (Registry Stored Query) to find imaging documents matching the specified criteria.
Parameters
params Query parameters
Returns
Query result with document references
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_consumer.hpp.
Definition at line 66 of file imaging_document_consumer.cpp.
{
    registry_query_result result;
    if (config_.registry_url.empty()) {
        result.error_message = "XDS registry URL not configured";
        return result;
    }
    // NOTE: Actual SOAP request to the XDS registry (ITI-18)
    // would be implemented here using the network layer.
    // The ITI-18 transaction uses SOAP/XML encoding with
    // the AdhocQueryRequest/AdhocQueryResponse pattern.
    result.success = true;
    return result;
}
References config_, kcenon::pacs::services::xds::registry_query_result::error_message, kcenon::pacs::services::xds::imaging_document_consumer_config::registry_url, and kcenon::pacs::services::xds::registry_query_result::success.
retrieve_document()
document_retrieval_result kcenon::pacs::services::xds::imaging_document_consumer::retrieve_document (const document_reference & doc_ref) const
Retrieve a specific document from the XDS repository.
Performs an ITI-43 (Retrieve Document Set) to fetch a KOS document identified by the document reference.
Parameters
doc_ref The document reference from a registry query
Returns
Retrieval result with the KOS dataset
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_consumer.hpp.
Definition at line 85 of file imaging_document_consumer.cpp.
{
    document_retrieval_result result;
    if (config_.repository_url.empty()) {
        result.error_message = "XDS repository URL not configured";
        return result;
    }
    // NOTE: Actual SOAP/MTOM request to the XDS repository (ITI-43)
    // would be implemented here. The response contains the KOS
    // document as an MTOM attachment.
    result.success = true;
    return result;
}
References config_, kcenon::pacs::services::xds::document_retrieval_result::error_message, kcenon::pacs::services::xds::imaging_document_consumer_config::repository_url, and kcenon::pacs::services::xds::document_retrieval_result::success.
set_config()
void kcenon::pacs::services::xds::imaging_document_consumer::set_config (const imaging_document_consumer_config & config)
Set configuration.
Parameters
config New configuration
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_consumer.hpp.
Definition at line 194 of file imaging_document_consumer.cpp.
{
    config_ = config;
}
References config(), and config_.
Member Data Documentation
config_
imaging_document_consumer_config kcenon::pacs::services::xds::imaging_document_consumer::config_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/services/xds/imaging_document_consumer.hpp.
Definition at line 300 of file imaging_document_consumer.hpp.
Referenced by build_wado_rs_url(), config(), query_registry(), retrieve_document(), and set_config().
The documentation for this class was generated from the following files:
include/pacs/services/xds/imaging_document_consumer.hpp
src/services/xds/imaging_document_consumer.cpp