PACS System: kcenon::pacs::services::query_scp Class Reference
kcenon::pacs::services::query_scp Class Reference final
#include <query_scp.h>
Public Member Functions
query_scp (std::shared_ptr< di::ILogger > logger=nullptr)
Construct Query SCP with optional logger.
~query_scp () override=default
void set_handler (query_handler handler)
Set the query handler function.
void set_max_results (size_t max) noexcept
Set maximum number of results to return.
size_t max_results () const noexcept
Get maximum number of results.
void set_cancel_check (cancel_check check)
Set the cancel check function.
void set_audit_handler (std::shared_ptr< kcenon::pacs::security::atna_service_auditor > auditor)
Set the ATNA audit handler for C-FIND operations.
std::vector< std::string > supported_sop_classes () const override
Get supported SOP Class UIDs.
network::Result< std::monostate > handle_message (network::association &assoc, uint8_t context_id, const network::dimse::dimse_message &request) override
Handle an incoming DIMSE message (C-FIND-RQ)
std::string_view service_name () const noexcept override
Get the service name.
size_t queries_processed () const noexcept
Get total number of queries processed.
void reset_statistics () noexcept
Reset statistics counters.
Public Member Functions inherited from kcenon::pacs::services::scp_service
scp_service (std::shared_ptr< di::ILogger > logger=nullptr)
Construct SCP service with optional logger.
virtual ~scp_service ()=default
scp_service (const scp_service &)=delete
scp_service & operator= (const scp_service &)=delete
scp_service (scp_service &&)=default
scp_service & operator= (scp_service &&)=default
void set_logger (std::shared_ptr< di::ILogger > logger)
Set the logger instance.
const std::shared_ptr< di::ILogger > & logger () const noexcept
Get the current logger instance.
bool supports_sop_class (std::string_view sop_class_uid) const
Check if this service supports a specific SOP Class.
Private Member Functions
std::optional< query_level > extract_query_level (const core::dicom_dataset &dataset) const
Extract query level from request dataset.
network::Result< std::monostate > send_pending_response (network::association &assoc, uint8_t context_id, uint16_t message_id, std::string_view sop_class_uid, const core::dicom_dataset &result)
Send a pending C-FIND response with matching dataset.
network::Result< std::monostate > send_final_response (network::association &assoc, uint8_t context_id, uint16_t message_id, std::string_view sop_class_uid, network::dimse::status_code status)
Send the final C-FIND response (success or cancel)
Private Attributes
query_handler handler_
cancel_check cancel_check_
std::shared_ptr< kcenon::pacs::security::atna_service_auditor > auditor_
size_t max_results_ {0}
std::atomic< size_t > queries_processed_ {0}
Additional Inherited Members
Protected Attributes inherited from kcenon::pacs::services::scp_service
std::shared_ptr< di::ILogger > logger_
Logger instance for service logging.
Detailed Description
Definition at line 189 of file query_scp.h.
Constructor & Destructor Documentation
query_scp()
kcenon::pacs::services::query_scp::query_scp (std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct Query SCP with optional logger.
Parameters
logger Logger instance for service logging (nullptr uses null_logger)
Definition at line 40 of file query_scp.cpp.
    : scp_service(std::move(logger)) {}
~query_scp()
kcenon::pacs::services::query_scp::~query_scp () override default
Member Function Documentation
extract_query_level()
std::optional< query_level > kcenon::pacs::services::query_scp::extract_query_level (const core::dicom_dataset & dataset) const nodiscard private
Extract query level from request dataset.
Parameters
dataset The query dataset
Returns
Parsed query level, or std::nullopt if invalid
Definition at line 215 of file query_scp.cpp.
{
    // Get Query/Retrieve Level tag (0008,0052)
    auto level_str = dataset.get_string(core::tags::query_retrieve_level);
    if (level_str.empty()) {
        return std::nullopt;
    }
    return parse_query_level(level_str);
}
References kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::parse_query_level(), and kcenon::pacs::core::tags::query_retrieve_level.
Referenced by handle_message().
handle_message()
network::Result< std::monostate > kcenon::pacs::services::query_scp::handle_message (network::association & assoc, uint8_t context_id, const network::dimse::dimse_message & request) nodiscard override virtual
Handle an incoming DIMSE message (C-FIND-RQ)
Processes the C-FIND request, queries the database through the handler, and sends pending responses for each match followed by a final success.
Parameters
assoc The association on which the message was received
context_id The presentation context ID for the message
request The incoming C-FIND-RQ message
Returns
Success or error if the message is not a valid C-FIND-RQ
Implements kcenon::pacs::services::scp_service.
Definition at line 79 of file query_scp.cpp.
{
    using namespace network::dimse;
    auto start_time = std::chrono::steady_clock::now();
    std::string calling_ae{assoc.calling_ae()};
    // Verify the message is a C-FIND request
    if (request.command() != command_field::c_find_rq) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::find_unexpected_command,
            "Expected C-FIND-RQ but received " +
            std::string(to_string(request.command())));
    }
    // Verify we have a handler
    if (!handler_) {
        kcenon::common::get_event_bus().publish(
            kcenon::pacs::events::query_failed_event{
                calling_ae,
                static_cast<int>(kcenon::pacs::error_codes::find_handler_not_set),
                "No query handler configured"
            }
        );
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::find_handler_not_set,
            "No query handler configured");
    }
    // Get the SOP Class UID from the request
    auto sop_class_uid = request.affected_sop_class_uid();
    // Verify we have a dataset
    if (!request.has_dataset()) {
        return send_final_response(
            assoc, context_id, request.message_id(),
            sop_class_uid, status_error_cannot_understand);
    }
    // Extract query level
    const auto& query_keys = request.dataset().value().get();
    auto level = extract_query_level(query_keys);
    if (!level.has_value()) {
        // Invalid or missing query level
        return send_final_response(
            assoc, context_id, request.message_id(),
            sop_class_uid, status_error_cannot_understand);
    }
    // Call the handler to get matching results
    auto results = handler_(level.value(), query_keys, calling_ae);
    // Apply max results limit if configured
    if (max_results_ > 0 && results.size() > max_results_) {
        results.resize(max_results_);
    }
    // Send pending responses for each result
    for (const auto& result : results) {
        // Check for cancel request
        if (cancel_check_ && cancel_check_()) {
            // Increment statistics
            ++queries_processed_;
            // Send cancel response
            return send_final_response(
                assoc, context_id, request.message_id(),
                sop_class_uid, status_cancel);
        }
        // Send pending response with matching dataset
        auto send_result = send_pending_response(
            assoc, context_id, request.message_id(),
            sop_class_uid, result);
        if (send_result.is_err()) {
            return send_result;
        }
    }
    // Increment statistics
    ++queries_processed_;
    // Calculate execution time
    auto end_time = std::chrono::steady_clock::now();
    auto execution_time_ms = std::chrono::duration_cast<std::chrono::milliseconds>(
        end_time - start_time).count();
    // Publish query executed event
    kcenon::common::get_event_bus().publish(
        kcenon::pacs::events::query_executed_event{
            to_event_level(level.value()),
            calling_ae,
            results.size(),
            static_cast<uint64_t>(execution_time_ms)
        }
    );
    // Emit ATNA audit event
    if (auditor_) {
        auditor_->audit_query(
            calling_ae,
            std::string(assoc.called_ae()),
            std::string(to_string(level.value())),
            true);
    }
    // Send final success response (no dataset)
    return send_final_response(
        assoc, context_id, request.message_id(),
        sop_class_uid, status_success);
}
References kcenon::pacs::network::dimse::dimse_message::affected_sop_class_uid(), kcenon::pacs::security::atna_service_auditor::audit_query(), auditor_, kcenon::pacs::network::association::called_ae(), kcenon::pacs::network::association::calling_ae(), cancel_check_, kcenon::pacs::network::dimse::dimse_message::command(), kcenon::pacs::network::dimse::dimse_message::dataset(), extract_query_level(), kcenon::pacs::error_codes::find_handler_not_set, kcenon::pacs::error_codes::find_unexpected_command, handler_, kcenon::pacs::network::dimse::dimse_message::has_dataset(), max_results_, kcenon::pacs::network::dimse::dimse_message::message_id(), kcenon::pacs::pacs_void_error(), queries_processed_, send_final_response(), send_pending_response(), and kcenon::pacs::services::to_string().
max_results()
size_t kcenon::pacs::services::query_scp::max_results () const nodiscard noexcept
Get maximum number of results.
Returns
Maximum results (0 = unlimited)
Definition at line 55 of file query_scp.cpp.
{
    return max_results_;
}
References max_results_.
queries_processed()
size_t kcenon::pacs::services::query_scp::queries_processed () const nodiscard noexcept
Get total number of queries processed.
Returns
Number of C-FIND requests handled
Definition at line 203 of file query_scp.cpp.
{
    return queries_processed_.load();
}
References queries_processed_.
reset_statistics()
void kcenon::pacs::services::query_scp::reset_statistics () noexcept
Reset statistics counters.
Definition at line 207 of file query_scp.cpp.
{
    queries_processed_ = 0;
}
References queries_processed_.
send_final_response()
network::Result< std::monostate > kcenon::pacs::services::query_scp::send_final_response (network::association & assoc, uint8_t context_id, uint16_t message_id, std::string_view sop_class_uid, network::dimse::status_code status) nodiscard private
Send the final C-FIND response (success or cancel)
Parameters
assoc The association
context_id The presentation context ID
message_id The original request message ID
sop_class_uid The SOP Class UID
status The final status code
Returns
Success or error
Definition at line 251 of file query_scp.cpp.
{
    using namespace network::dimse;
    // Create C-FIND response with final status (no dataset)
    auto response = make_c_find_rsp(
        message_id,
        sop_class_uid,
        status
    );
    // Send the response
    return assoc.send_dimse(context_id, response);
}
References kcenon::pacs::network::association::send_dimse().
Referenced by handle_message().
send_pending_response()
network::Result< std::monostate > kcenon::pacs::services::query_scp::send_pending_response (network::association & assoc, uint8_t context_id, uint16_t message_id, std::string_view sop_class_uid, const core::dicom_dataset & result) nodiscard private
Send a pending C-FIND response with matching dataset.
Parameters
assoc The association
context_id The presentation context ID
message_id The original request message ID
sop_class_uid The SOP Class UID
result The matching dataset
Returns
Success or error
Definition at line 228 of file query_scp.cpp.
{
    using namespace network::dimse;
    // Create C-FIND response with pending status
    auto response = make_c_find_rsp(
        message_id,
        sop_class_uid,
        status_pending
    );
    // Attach the matching dataset
    response.set_dataset(result);
    // Send the response
    return assoc.send_dimse(context_id, response);
}
References kcenon::pacs::network::association::send_dimse().
Referenced by handle_message().
service_name()
std::string_view kcenon::pacs::services::query_scp::service_name () const nodiscard override virtual noexcept
Get the service name.
Returns
"Query SCP"
Implements kcenon::pacs::services::scp_service.
Definition at line 195 of file query_scp.cpp.
{
    return "Query SCP";
}
set_audit_handler()
void kcenon::pacs::services::query_scp::set_audit_handler (std::shared_ptr< kcenon::pacs::security::atna_service_auditor > auditor)
Set the ATNA audit handler for C-FIND operations.
When set, audit events are emitted for each completed C-FIND operation.
Parameters
auditor Shared pointer to an ATNA service auditor
Definition at line 63 of file query_scp.cpp.
{
    auditor_ = std::move(auditor);
}
References auditor_.
set_cancel_check()
void kcenon::pacs::services::query_scp::set_cancel_check (cancel_check check)
Set the cancel check function.
The cancel check is called periodically during query processing to check if a C-CANCEL has been received.
Parameters
check The cancel check function
Definition at line 59 of file query_scp.cpp.
{
    cancel_check_ = std::move(check);
}
References cancel_check_.
set_handler()
void kcenon::pacs::services::query_scp::set_handler (query_handler handler)
Set the query handler function.
The handler is called for each C-FIND request to retrieve matching records from the database.
Parameters
handler The query handler function
Definition at line 47 of file query_scp.cpp.
{
    handler_ = std::move(handler);
}
References handler_.
set_max_results()
void kcenon::pacs::services::query_scp::set_max_results (size_t max) noexcept
Set maximum number of results to return.
Parameters
max Maximum results (0 = unlimited)
Definition at line 51 of file query_scp.cpp.
{
    max_results_ = max;
}
supported_sop_classes()
std::vector< std::string > kcenon::pacs::services::query_scp::supported_sop_classes () const nodiscard override virtual
Get supported SOP Class UIDs.
Returns
Vector containing Patient Root and Study Root Find SOP Classes
Implements kcenon::pacs::services::scp_service.
Definition at line 72 of file query_scp.cpp.
{
    return {
        std::string(patient_root_find_sop_class_uid),
        std::string(study_root_find_sop_class_uid)
    };
}
References kcenon::pacs::services::patient_root_find_sop_class_uid, and kcenon::pacs::services::study_root_find_sop_class_uid.
Member Data Documentation
auditor_
std::shared_ptr<kcenon::pacs::security::atna_service_auditor> kcenon::pacs::services::query_scp::auditor_ private
Definition at line 356 of file query_scp.h.
Referenced by handle_message(), and set_audit_handler().
cancel_check_
cancel_check kcenon::pacs::services::query_scp::cancel_check_ private
Definition at line 355 of file query_scp.h.
Referenced by handle_message(), and set_cancel_check().
handler_
query_handler kcenon::pacs::services::query_scp::handler_ private
Definition at line 354 of file query_scp.h.
Referenced by handle_message(), and set_handler().
max_results_
size_t kcenon::pacs::services::query_scp::max_results_ {0} private
Definition at line 357 of file query_scp.h.
{0};  // 0 = unlimited
Referenced by handle_message(), and max_results().
queries_processed_
std::atomic<size_t> kcenon::pacs::services::query_scp::queries_processed_ {0} private
Definition at line 358 of file query_scp.h.
{0};
Referenced by handle_message(), queries_processed(), and reset_statistics().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/query_scp.h
src/services/query_scp.cpp