PACS System: kcenon::pacs::security::user_context Class Reference
kcenon::pacs::security::user_context Class Reference
Represents the security context for a user session.
#include <user_context.h>
Public Types
using clock = std::chrono::steady_clock
using time_point = clock::time_point
Public Member Functions
user_context (User user, std::string session_id)
Construct a user context.
const User & user () const noexcept
const std::string & session_id () const noexcept
time_point created_at () const noexcept
time_point last_activity () const noexcept
bool is_valid () const noexcept
Check if the context is valid (user is active)
bool has_role (Role role) const
Check if user has a specific role.
void touch ()
Update last activity timestamp.
void set_source_ae_title (std::string ae)
const std::optional< std::string > & source_ae_title () const noexcept
void set_source_ip (std::string ip)
const std::optional< std::string > & source_ip () const noexcept
Static Public Member Functions
static user_context system_context ()
Create a system context for internal operations.
static user_context anonymous_context (const std::string &session_id)
Create an anonymous context with minimal permissions.
Private Attributes
User user_
std::string session_id_
time_point created_at_
time_point last_activity_
std::optional< std::string > source_ae_title_
std::optional< std::string > source_ip_
Detailed Description
Represents the security context for a user session.
Encapsulates user information along with session-specific data for access control decisions.
Definition at line 29 of file user_context.h.
Member Typedef Documentation
clock
using kcenon::pacs::security::user_context::clock = std::chrono::steady_clock
Definition at line 31 of file user_context.h.
time_point
using kcenon::pacs::security::user_context::time_point = clock::time_point
Definition at line 32 of file user_context.h.
Constructor & Destructor Documentation
user_context()
kcenon::pacs::security::user_context::user_context (User user, std::string session_id) inline
Construct a user context.
Parameters
user The authenticated user
session_id Unique session identifier
Definition at line 39 of file user_context.h.
      : user_(std::move(user)), session_id_(std::move(session_id)),
        created_at_(clock::now()), last_activity_(clock::now()) {}
Referenced by anonymous_context(), and system_context().
Member Function Documentation
anonymous_context()
static user_context kcenon::pacs::security::user_context::anonymous_context (const std::string & session_id) inline static
Create an anonymous context with minimal permissions.
Definition at line 58 of file user_context.h.
{
    User anon_user;
    anon_user.id = "anonymous";
    anon_user.username = "anonymous";
    anon_user.roles = {}; // No roles = no permissions
    anon_user.active = true;
    return user_context(std::move(anon_user), session_id);
  }
References kcenon::pacs::security::User::active, kcenon::pacs::security::User::id, kcenon::pacs::security::User::roles, session_id(), user_context(), and kcenon::pacs::security::User::username.
created_at()
time_point kcenon::pacs::security::user_context::created_at () const inline nodiscard noexcept
Definition at line 72 of file user_context.h.
{ return created_at_; }
References created_at_.
has_role()
bool kcenon::pacs::security::user_context::has_role (Role role) const inline nodiscard
Check if user has a specific role.
Definition at line 85 of file user_context.h.
{ return user_.has_role(role); }
References kcenon::pacs::security::User::has_role(), and user_.
is_valid()
bool kcenon::pacs::security::user_context::is_valid () const inline nodiscard noexcept
Check if the context is valid (user is active)
Definition at line 80 of file user_context.h.
{ return user_.active; }
References kcenon::pacs::security::User::active, and user_.
Referenced by kcenon::pacs::security::access_control_manager::check_dicom_operation().
last_activity()
time_point kcenon::pacs::security::user_context::last_activity () const inline nodiscard noexcept
Definition at line 73 of file user_context.h.
{
    return last_activity_;
  }
References last_activity_.
session_id()
const std::string & kcenon::pacs::security::user_context::session_id () const inline nodiscard noexcept
Definition at line 69 of file user_context.h.
{
    return session_id_;
  }
References session_id_.
Referenced by anonymous_context().
set_source_ae_title()
void kcenon::pacs::security::user_context::set_source_ae_title (std::string ae) inline
Definition at line 93 of file user_context.h.
{
    source_ae_title_ = std::move(ae);
  }
References source_ae_title_.
set_source_ip()
void kcenon::pacs::security::user_context::set_source_ip (std::string ip) inline
Definition at line 101 of file user_context.h.
{ source_ip_ = std::move(ip); }
References source_ip_.
source_ae_title()
const std::optional< std::string > & kcenon::pacs::security::user_context::source_ae_title () const inline nodiscard noexcept
Definition at line 97 of file user_context.h.
{
    return source_ae_title_;
  }
References source_ae_title_.
source_ip()
const std::optional< std::string > & kcenon::pacs::security::user_context::source_ip () const inline nodiscard noexcept
Definition at line 102 of file user_context.h.
{
    return source_ip_;
  }
References source_ip_.
system_context()
static user_context kcenon::pacs::security::user_context::system_context () inline static
Create a system context for internal operations.
Definition at line 46 of file user_context.h.
{
    User system_user;
    system_user.id = "system";
    system_user.username = "system";
    system_user.roles = {Role::System};
    system_user.active = true;
    return user_context(std::move(system_user), "system-internal");
  }
References kcenon::pacs::security::User::active, kcenon::pacs::security::User::id, kcenon::pacs::security::User::roles, kcenon::pacs::security::System, user_context(), and kcenon::pacs::security::User::username.
touch()
void kcenon::pacs::security::user_context::touch () inline
Update last activity timestamp.
Definition at line 90 of file user_context.h.
{ last_activity_ = clock::now(); }
References last_activity_.
user()
const User & kcenon::pacs::security::user_context::user () const inline nodiscard noexcept
Definition at line 68 of file user_context.h.
{ return user_; }
References user_.
Referenced by kcenon::pacs::security::access_control_manager::check_dicom_operation().
Member Data Documentation
created_at_
time_point kcenon::pacs::security::user_context::created_at_ private
Definition at line 109 of file user_context.h.
Referenced by created_at().
last_activity_
time_point kcenon::pacs::security::user_context::last_activity_ private
Definition at line 110 of file user_context.h.
Referenced by last_activity(), and touch().
session_id_
std::string kcenon::pacs::security::user_context::session_id_ private
Definition at line 108 of file user_context.h.
Referenced by session_id().
source_ae_title_
std::optional<std::string> kcenon::pacs::security::user_context::source_ae_title_ private
Definition at line 111 of file user_context.h.
Referenced by set_source_ae_title(), and source_ae_title().
source_ip_
std::optional<std::string> kcenon::pacs::security::user_context::source_ip_ private
Definition at line 112 of file user_context.h.
Referenced by set_source_ip(), and source_ip().
user_
User kcenon::pacs::security::user_context::user_ private
Definition at line 107 of file user_context.h.
Referenced by has_role(), is_valid(), and user().
The documentation for this class was generated from the following file:
include/kcenon/pacs/security/user_context.h