PACS System: kcenon::pacs::network::pipeline::pipeline_coordinator Class Reference
kcenon::pacs::network::pipeline::pipeline_coordinator Class Reference
Coordinates the 6-stage DICOM I/O pipeline.
#include <pipeline_coordinator.h>
Public Types
using job_completion_callback = std::function<void(const job_context&, bool success)>
Callback type for job completion notification.
using backpressure_callback = std::function<void(pipeline_stage, size_t queue_depth)>
Callback type for backpressure notification.
Public Member Functions
pipeline_coordinator ()
Construct coordinator with default configuration.
pipeline_coordinator (const pipeline_config &config)
Construct coordinator with custom configuration.
~pipeline_coordinator ()
Destructor - ensures graceful shutdown.
pipeline_coordinator (const pipeline_coordinator &)=delete
pipeline_coordinator & operator= (const pipeline_coordinator &)=delete
pipeline_coordinator (pipeline_coordinator &&)=delete
pipeline_coordinator & operator= (pipeline_coordinator &&)=delete
auto start () -> VoidResult
Start the pipeline.
auto stop () -> VoidResult
Stop the pipeline gracefully.
auto is_running () const noexcept -> bool
Check if the pipeline is running.
auto submit_to_stage (pipeline_stage stage, std::unique_ptr< pipeline_job_base > job) -> VoidResult
Submit a job to a specific stage.
auto submit_to_stage (pipeline_stage stage, std::unique_ptr< pipeline_job_base > job, const job_context &ctx) -> VoidResult
Submit a job with specific context.
auto submit_task (pipeline_stage stage, std::function< void()> task) -> VoidResult
Submit a raw function to a stage (for simple tasks)
auto get_stage_pool (pipeline_stage stage) -> std::shared_ptr< kcenon::pacs::integration::thread_pool_interface >
Get the thread pool for a specific stage.
auto get_queue_depth (pipeline_stage stage) const noexcept -> size_t
Get queue depth for a specific stage.
auto is_backpressure_active (pipeline_stage stage) const noexcept -> bool
Check if backpressure is active for a stage.
auto get_config () const noexcept -> const pipeline_config &
Get the current configuration.
void set_job_completion_callback (job_completion_callback callback)
Set the job completion callback.
void set_backpressure_callback (backpressure_callback callback)
Set the backpressure callback.
auto get_metrics () noexcept -> pipeline_metrics &
Get the metrics collector.
auto get_metrics () const noexcept -> const pipeline_metrics &
Get the metrics collector (const)
void reset_metrics () noexcept
Reset all metrics.
auto get_total_worker_count () const noexcept -> size_t
Get total number of workers across all stages.
auto get_total_pending_jobs () const noexcept -> size_t
Get total pending jobs across all stages.
auto generate_job_id () noexcept -> uint64_t
Generate a unique job ID.
Private Types
using pool_ptr = std::shared_ptr<kcenon::pacs::integration::thread_pool_interface>
Private Member Functions
auto create_stage_pool (pipeline_stage stage) -> pool_ptr
void notify_job_completion (const job_context &ctx, bool success)
void check_backpressure (pipeline_stage stage)
Private Attributes
std::array< pool_ptr, stage_count > stage_pools_
pipeline_config config_
std::atomic< bool > running_ {false}
std::mutex mutex_
pipeline_metrics metrics_
job_completion_callback job_completion_callback_
backpressure_callback backpressure_callback_
std::atomic< uint64_t > next_job_id_ {1}
Static Private Attributes
static constexpr size_t stage_count
Detailed Description
Coordinates the 6-stage DICOM I/O pipeline.
The coordinator manages:
Per-stage thread pools with dedicated workers
Job submission and routing between stages
Backpressure handling when queues are full
Graceful shutdown with timeout
Metrics collection for monitoring
Thread Safety: All public methods are thread-safe.
Definition at line 141 of file pipeline_coordinator.h.
Member Typedef Documentation
backpressure_callback
using kcenon::pacs::network::pipeline::pipeline_coordinator::backpressure_callback = std::function<void(pipeline_stage, size_t queue_depth)>
Callback type for backpressure notification.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 147 of file pipeline_coordinator.h.
job_completion_callback
using kcenon::pacs::network::pipeline::pipeline_coordinator::job_completion_callback = std::function<void(const job_context&, bool success)>
Callback type for job completion notification.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 144 of file pipeline_coordinator.h.
pool_ptr
using kcenon::pacs::network::pipeline::pipeline_coordinator::pool_ptr = std::shared_ptr<kcenon::pacs::integration::thread_pool_interface> private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 350 of file pipeline_coordinator.h.
Constructor & Destructor Documentation
pipeline_coordinator() [1/4]
kcenon::pacs::network::pipeline::pipeline_coordinator::pipeline_coordinator ()
Construct coordinator with default configuration.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 23 of file pipeline_coordinator.cpp.
    : pipeline_coordinator(pipeline_config{}) {
}
pipeline_coordinator() [2/4]
kcenon::pacs::network::pipeline::pipeline_coordinator::pipeline_coordinator (const pipeline_config & config) explicit
Construct coordinator with custom configuration.
Parameters
config Pipeline configuration options
Definition at line 27 of file pipeline_coordinator.cpp.
    : config_(config) {
    if (config_.enable_metrics) {
        metrics_.mark_start_time();
    }
}
References config_, and kcenon::pacs::network::pipeline::pipeline_config::enable_metrics.
~pipeline_coordinator()
kcenon::pacs::network::pipeline::pipeline_coordinator::~pipeline_coordinator ()
Destructor - ensures graceful shutdown.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 34 of file pipeline_coordinator.cpp.
{
    if (running_.load(std::memory_order_acquire)) {
        static_cast<void>(stop());
    }
}
References running_, and stop().
pipeline_coordinator() [3/4]
kcenon::pacs::network::pipeline::pipeline_coordinator::pipeline_coordinator (const pipeline_coordinator &) delete
pipeline_coordinator() [4/4]
kcenon::pacs::network::pipeline::pipeline_coordinator::pipeline_coordinator (pipeline_coordinator &&) delete
Member Function Documentation
check_backpressure()
void kcenon::pacs::network::pipeline::pipeline_coordinator::check_backpressure (pipeline_stage stage) private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 344 of file pipeline_coordinator.cpp.
{
    size_t depth = get_queue_depth(stage);
    if (depth >= config_.max_queue_depth) {
        backpressure_callback callback;
        {
            std::lock_guard<std::mutex> lock(mutex_);
            callback = backpressure_callback_;
        }
        if (callback) {
            try {
                callback(stage, depth);
            } catch (...) {
                // Swallow exceptions from callback
            }
        }
    }
}
References backpressure_callback_, config_, get_queue_depth(), kcenon::pacs::network::pipeline::pipeline_config::max_queue_depth, and mutex_.
create_stage_pool()
auto kcenon::pacs::network::pipeline::pipeline_coordinator::create_stage_pool (pipeline_stage stage) -> pool_ptr nodiscard private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 318 of file pipeline_coordinator.cpp.
                {
    kcenon::pacs::integration::thread_pool_config pool_config;
    pool_config.min_threads = config_.get_workers_for_stage(stage);
    pool_config.max_threads = config_.get_workers_for_stage(stage);
    pool_config.pool_name = config_.name_prefix + "_" + std::string(get_stage_name(stage));
    return std::make_shared<kcenon::pacs::integration::thread_pool_adapter>(pool_config);
}
References kcenon::pacs::network::pipeline::get_stage_name(), kcenon::pacs::integration::thread_pool_config::max_threads, kcenon::pacs::integration::thread_pool_config::min_threads, and kcenon::pacs::integration::thread_pool_config::pool_name.
generate_job_id()
auto kcenon::pacs::network::pipeline::pipeline_coordinator::generate_job_id () -> uint64_t nodiscard noexcept
Generate a unique job ID.
Returns
Monotonically increasing job ID
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 310 of file pipeline_coordinator.cpp.
{
    return next_job_id_.fetch_add(1, std::memory_order_relaxed);
}
References next_job_id_.
get_config()
auto kcenon::pacs::network::pipeline::pipeline_coordinator::get_config () const -> const pipeline_config& nodiscard noexcept
Get the current configuration.
Returns
Reference to the pipeline configuration
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 255 of file pipeline_coordinator.cpp.
{
    return config_;
}
References config_.
get_metrics() [1/2]
auto kcenon::pacs::network::pipeline::pipeline_coordinator::get_metrics () const -> const pipeline_metrics& nodiscard noexcept
Get the metrics collector (const)
Definition at line 277 of file pipeline_coordinator.cpp.
{
    return metrics_;
}
References metrics_.
get_metrics() [2/2]
auto kcenon::pacs::network::pipeline::pipeline_coordinator::get_metrics () -> pipeline_metrics& nodiscard noexcept
Get the metrics collector.
Returns
Reference to the pipeline metrics
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 273 of file pipeline_coordinator.cpp.
{
    return metrics_;
}
References metrics_.
get_queue_depth()
auto kcenon::pacs::network::pipeline::pipeline_coordinator::get_queue_depth (pipeline_stage stage) const -> size_t nodiscard noexcept
Get queue depth for a specific stage.
Parameters
stage The pipeline stage
Returns
Number of pending jobs in the stage's queue
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 237 of file pipeline_coordinator.cpp.
              {
    size_t stage_idx = static_cast<size_t>(stage);
    if (stage_idx >= stage_count || !stage_pools_[stage_idx]) {
        return 0;
    }
    return stage_pools_[stage_idx]->get_pending_task_count();
}
References kcenon::pacs::network::pipeline::stage_count.
Referenced by check_backpressure().
get_stage_pool()
auto kcenon::pacs::network::pipeline::pipeline_coordinator::get_stage_pool (pipeline_stage stage) -> std::shared_ptr<kcenon::pacs::integration::thread_pool_interface> nodiscard
Get the thread pool for a specific stage.
Parameters
stage The pipeline stage
Returns
Shared pointer to the stage's thread pool, or nullptr if not running
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 228 of file pipeline_coordinator.cpp.
{
    size_t stage_idx = static_cast<size_t>(stage);
    if (stage_idx >= stage_count) {
        return nullptr;
    }
    return stage_pools_[stage_idx];
}
References kcenon::pacs::network::pipeline::stage_count.
get_total_pending_jobs()
auto kcenon::pacs::network::pipeline::pipeline_coordinator::get_total_pending_jobs () const -> size_t nodiscard noexcept
Get total pending jobs across all stages.
Returns
Total pending job count
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 300 of file pipeline_coordinator.cpp.
{
    size_t total = 0;
    for (const auto& pool : stage_pools_) {
        if (pool) {
            total += pool->get_pending_task_count();
        }
    }
    return total;
}
References stage_pools_.
get_total_worker_count()
auto kcenon::pacs::network::pipeline::pipeline_coordinator::get_total_worker_count () const -> size_t nodiscard noexcept
Get total number of workers across all stages.
Returns
Total worker count
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 290 of file pipeline_coordinator.cpp.
{
    size_t total = 0;
    for (const auto& pool : stage_pools_) {
        if (pool) {
            total += pool->get_thread_count();
        }
    }
    return total;
}
References stage_pools_.
is_backpressure_active()
auto kcenon::pacs::network::pipeline::pipeline_coordinator::is_backpressure_active (pipeline_stage stage) const -> bool nodiscard noexcept
Check if backpressure is active for a stage.
Parameters
stage The pipeline stage
Returns
true if queue depth exceeds threshold
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 246 of file pipeline_coordinator.cpp.
            {
    return get_queue_depth(stage) >= config_.max_queue_depth;
}
is_running()
auto kcenon::pacs::network::pipeline::pipeline_coordinator::is_running () const -> bool nodiscard noexcept
Check if the pipeline is running.
Returns
true if the pipeline is active
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 122 of file pipeline_coordinator.cpp.
{
    return running_.load(std::memory_order_acquire);
}
References running_.
notify_job_completion()
void kcenon::pacs::network::pipeline::pipeline_coordinator::notify_job_completion (const job_context & ctx, bool success) private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 328 of file pipeline_coordinator.cpp.
{
    job_completion_callback callback;
    {
        std::lock_guard<std::mutex> lock(mutex_);
        callback = job_completion_callback_;
    }
    if (callback) {
        try {
            callback(ctx, success);
        } catch (...) {
            // Swallow exceptions from callback to prevent pipeline disruption
        }
    }
}
References job_completion_callback_, mutex_, and kcenon::pacs::network::pipeline::success.
operator=() [1/2]
pipeline_coordinator & kcenon::pacs::network::pipeline::pipeline_coordinator::operator= (const pipeline_coordinator &) delete
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
operator=() [2/2]
pipeline_coordinator & kcenon::pacs::network::pipeline::pipeline_coordinator::operator= (pipeline_coordinator &&) delete
reset_metrics()
void kcenon::pacs::network::pipeline::pipeline_coordinator::reset_metrics () noexcept
Reset all metrics.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 281 of file pipeline_coordinator.cpp.
{
    metrics_.reset();
    metrics_.mark_start_time();
}
References kcenon::pacs::network::pipeline::pipeline_metrics::mark_start_time(), metrics_, and kcenon::pacs::network::pipeline::pipeline_metrics::reset().
set_backpressure_callback()
void kcenon::pacs::network::pipeline::pipeline_coordinator::set_backpressure_callback (backpressure_callback callback)
Set the backpressure callback.
Called when a stage's queue depth exceeds threshold.
Parameters
callback Callback function
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 264 of file pipeline_coordinator.cpp.
{
    std::lock_guard<std::mutex> lock(mutex_);
    backpressure_callback_ = std::move(callback);
}
References backpressure_callback_, and mutex_.
set_job_completion_callback()
void kcenon::pacs::network::pipeline::pipeline_coordinator::set_job_completion_callback (job_completion_callback callback)
Set the job completion callback.
Called when any job completes (success or failure).
Parameters
callback Callback function
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 259 of file pipeline_coordinator.cpp.
{
    std::lock_guard<std::mutex> lock(mutex_);
    job_completion_callback_ = std::move(callback);
}
References job_completion_callback_, and mutex_.
start()
auto kcenon::pacs::network::pipeline::pipeline_coordinator::start () -> VoidResult nodiscard
Start the pipeline.
Initializes and starts all stage thread pools.
Returns
VoidResult indicating success or error
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 44 of file pipeline_coordinator.cpp.
{
    std::lock_guard<std::mutex> lock(mutex_);
    if (running_.load(std::memory_order_acquire)) {
        return pacs_void_error(error_codes::already_exists,
                               "Pipeline coordinator is already running");
    }
    // Create and start thread pools for each stage
    for (size_t i = 0; i < stage_count; ++i) {
        auto stage = static_cast<pipeline_stage>(i);
        try {
            stage_pools_[i] = create_stage_pool(stage);
            if (!stage_pools_[i]->start()) {
                // Cleanup already started pools
                for (size_t j = 0; j < i; ++j) {
                    if (stage_pools_[j]) {
                        stage_pools_[j]->shutdown(false);
                        stage_pools_[j].reset();
                    }
                }
                return pacs_void_error(error_codes::internal_error,
                    "Failed to start thread pool for stage: " +
                    std::string(get_stage_name(stage)));
            }
            // Update metrics
            if (config_.enable_metrics) {
                auto& stage_metrics = metrics_.get_stage_metrics(stage);
                stage_metrics.active_workers.store(
                    static_cast<uint32_t>(config_.get_workers_for_stage(stage)),
                    std::memory_order_relaxed);
            }
        } catch (const std::exception& e) {
            // Cleanup already started pools
            for (size_t j = 0; j < i; ++j) {
                if (stage_pools_[j]) {
                    stage_pools_[j]->shutdown(false);
                    stage_pools_[j].reset();
                }
            }
            return pacs_void_error(error_codes::internal_error,
                "Exception creating thread pool for stage " +
                std::string(get_stage_name(stage)) + ": " + e.what());
        }
    }
    running_.store(true, std::memory_order_release);
    return ok();
}
References kcenon::pacs::network::pipeline::stage_metrics::active_workers, kcenon::pacs::network::pipeline::get_stage_name(), kcenon::pacs::pacs_void_error(), and kcenon::pacs::network::pipeline::stage_count.
stop()
auto kcenon::pacs::network::pipeline::pipeline_coordinator::stop () -> VoidResult nodiscard
Stop the pipeline gracefully.
Stops accepting new jobs and waits for pending jobs to complete up to the configured shutdown timeout.
Returns
VoidResult indicating success or error
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 95 of file pipeline_coordinator.cpp.
{
    std::lock_guard<std::mutex> lock(mutex_);
    if (!running_.load(std::memory_order_acquire)) {
        return ok();  // Already stopped
    }
    running_.store(false, std::memory_order_release);
    // Stop all stage pools with timeout consideration
    bool all_stopped = true;
    for (size_t i = 0; i < stage_count; ++i) {
        if (stage_pools_[i]) {
            // Use wait_for_completion=true to drain queues gracefully
            stage_pools_[i]->shutdown(true);
            stage_pools_[i].reset();
        }
    }
    if (!all_stopped) {
        return pacs_void_error(error_codes::internal_error,
                               "Some stage pools did not shutdown cleanly");
    }
    return ok();
}
References kcenon::pacs::pacs_void_error(), and kcenon::pacs::network::pipeline::stage_count.
Referenced by ~pipeline_coordinator().
submit_task()
auto kcenon::pacs::network::pipeline::pipeline_coordinator::submit_task (pipeline_stage stage, std::function< void()> task) -> VoidResult nodiscard
Submit a raw function to a stage (for simple tasks)
Parameters
stage Target pipeline stage
task Function to execute
Returns
VoidResult indicating success or error
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 196 of file pipeline_coordinator.cpp.
{
    if (!running_.load(std::memory_order_acquire)) {
        return pacs_void_error(error_codes::not_initialized,
                               "Pipeline coordinator is not running");
    }
    size_t stage_idx = static_cast<size_t>(stage);
    if (stage_idx >= stage_count || !stage_pools_[stage_idx]) {
        return pacs_void_error(error_codes::invalid_argument,
                               "Invalid pipeline stage");
    }
    if (config_.enable_metrics) {
        metrics_.increment_stage_queue(stage);
    }
    stage_pools_[stage_idx]->submit_fire_and_forget(
        [this, stage, task = std::move(task)]() {
            task();
            if (config_.enable_metrics) {
                metrics_.decrement_stage_queue(stage);
            }
        });
    return ok();
}
References kcenon::pacs::pacs_void_error(), and kcenon::pacs::network::pipeline::stage_count.
submit_to_stage() [1/2]
auto kcenon::pacs::network::pipeline::pipeline_coordinator::submit_to_stage (pipeline_stage stage, std::unique_ptr< pipeline_job_base > job) -> VoidResult nodiscard
Submit a job to a specific stage.
Jobs are executed asynchronously by the stage's worker pool. If the queue is full, backpressure callback is invoked.
Parameters
stage Target pipeline stage
job Job to execute (ownership transferred)
Returns
VoidResult indicating success or error
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 130 of file pipeline_coordinator.cpp.
                  {
    if (!job) {
        return pacs_void_error(error_codes::invalid_argument,
                               "Cannot submit null job");
    }
    // Extract context before moving job to avoid undefined behavior
    // (evaluation order of function arguments is unspecified in C++)
    auto ctx = job->get_context();
    return submit_to_stage(stage, std::move(job), ctx);
}
References kcenon::pacs::pacs_void_error().
submit_to_stage() [2/2]
auto kcenon::pacs::network::pipeline::pipeline_coordinator::submit_to_stage (pipeline_stage stage, std::unique_ptr< pipeline_job_base > job, const job_context & ctx) -> VoidResult nodiscard
Submit a job with specific context.
Parameters
stage Target pipeline stage
job Job to execute
ctx Job context for tracking
Returns
VoidResult indicating success or error
Definition at line 143 of file pipeline_coordinator.cpp.
{
    if (!running_.load(std::memory_order_acquire)) {
        return pacs_void_error(error_codes::not_initialized,
                               "Pipeline coordinator is not running");
    }
    size_t stage_idx = static_cast<size_t>(stage);
    if (stage_idx >= stage_count || !stage_pools_[stage_idx]) {
        return pacs_void_error(error_codes::invalid_argument,
                               "Invalid pipeline stage");
    }
    // Check backpressure
    check_backpressure(stage);
    // Update metrics
    if (config_.enable_metrics) {
        metrics_.increment_stage_queue(stage);
    }
    // Capture job for lambda
    auto job_ptr = job.release();
    auto start_time = std::chrono::steady_clock::now();
    // Submit to stage pool
    stage_pools_[stage_idx]->submit_fire_and_forget(
        [this, job_ptr, stage, ctx_copy = ctx, start_time]() mutable {
            std::unique_ptr<pipeline_job_base> owned_job(job_ptr);
            // Execute the job
            auto result = owned_job->execute(*this);
            // Record completion
            auto end_time = std::chrono::steady_clock::now();
            auto duration_ns = std::chrono::duration_cast<std::chrono::nanoseconds>(
                end_time - start_time).count();
            bool success = result.is_ok();
            if (config_.enable_metrics) {
                metrics_.decrement_stage_queue(stage);
                metrics_.record_stage_completion(stage,
                    static_cast<uint64_t>(duration_ns), success);
            }
            notify_job_completion(ctx_copy, success);
        });
    return ok();
}
References kcenon::pacs::pacs_void_error(), kcenon::pacs::network::pipeline::stage_count, and kcenon::pacs::network::pipeline::success.
Member Data Documentation
backpressure_callback_
backpressure_callback kcenon::pacs::network::pipeline::pipeline_coordinator::backpressure_callback_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 365 of file pipeline_coordinator.h.
Referenced by check_backpressure(), and set_backpressure_callback().
config_
pipeline_config kcenon::pacs::network::pipeline::pipeline_coordinator::config_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 354 of file pipeline_coordinator.h.
Referenced by check_backpressure(), get_config(), and pipeline_coordinator().
job_completion_callback_
job_completion_callback kcenon::pacs::network::pipeline::pipeline_coordinator::job_completion_callback_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 364 of file pipeline_coordinator.h.
Referenced by notify_job_completion(), and set_job_completion_callback().
metrics_
pipeline_metrics kcenon::pacs::network::pipeline::pipeline_coordinator::metrics_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 361 of file pipeline_coordinator.h.
Referenced by get_metrics(), get_metrics(), and reset_metrics().
mutex_
std::mutex kcenon::pacs::network::pipeline::pipeline_coordinator::mutex_ mutable private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 358 of file pipeline_coordinator.h.
Referenced by check_backpressure(), notify_job_completion(), set_backpressure_callback(), and set_job_completion_callback().
next_job_id_
std::atomic<uint64_t> kcenon::pacs::network::pipeline::pipeline_coordinator::next_job_id_ {1} private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 368 of file pipeline_coordinator.h.
{1};
Referenced by generate_job_id().
running_
std::atomic<bool> kcenon::pacs::network::pipeline::pipeline_coordinator::running_ {false} private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 357 of file pipeline_coordinator.h.
{false};
Referenced by is_running(), and ~pipeline_coordinator().
stage_count
size_t kcenon::pacs::network::pipeline::pipeline_coordinator::stage_count static constexpr private
Initial value:
=
        static_cast<size_t>(pipeline_stage::stage_count)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 347 of file pipeline_coordinator.h.
stage_pools_
std::array<pool_ptr, stage_count> kcenon::pacs::network::pipeline::pipeline_coordinator::stage_pools_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/pipeline/pipeline_coordinator.h.
Definition at line 351 of file pipeline_coordinator.h.
Referenced by get_total_pending_jobs(), and get_total_worker_count().
The documentation for this class was generated from the following files:
include/kcenon/pacs/network/pipeline/pipeline_coordinator.h
src/network/pipeline/pipeline_coordinator.cpp