PACS System: kcenon::pacs::core::dicom_element Class Reference
kcenon::pacs::core::dicom_element Class Reference
#include <dicom_element.h>
Public Member Functions
dicom_element (dicom_tag tag, encoding::vr_type vr) noexcept
Construct an empty element with given tag and VR.
dicom_element (dicom_tag tag, encoding::vr_type vr, std::span< const uint8_t > data)
Construct an element with raw data.
dicom_element (const dicom_element &)
Copy constructor.
dicom_element (dicom_element &&) noexcept
Move constructor.
auto operator= (const dicom_element &) -> dicom_element &
Copy assignment.
auto operator= (dicom_element &&) noexcept -> dicom_element &
Move assignment.
~dicom_element ()
Destructor.
constexpr auto tag () const noexcept -> dicom_tag
Get the element's tag.
constexpr auto vr () const noexcept -> encoding::vr_type
Get the element's VR.
auto length () const noexcept -> uint32_t
Get the value length in bytes.
auto raw_data () const noexcept -> std::span< const uint8_t >
Get the raw data bytes.
auto is_empty () const noexcept -> bool
Check if the element has no value.
auto as_string () const -> kcenon::pacs::Result< std::string >
Get the value as a string.
auto as_string_list () const -> kcenon::pacs::Result< std::vector< std::string > >
Get multi-valued string as a list.
template<typename T >
requires std::is_arithmetic_v<T>
auto as_numeric () const -> kcenon::pacs::Result< T >
Get the value as a numeric type.
template<typename T >
requires std::is_arithmetic_v<T>
auto as_numeric_list () const -> kcenon::pacs::Result< std::vector< T > >
Get multi-valued numeric data as a list.
auto is_sequence () const noexcept -> bool
Check if this element is a sequence.
auto sequence_item_count () const noexcept -> std::size_t
Get the number of items in the sequence.
auto sequence_item (std::size_t index) const -> const dicom_dataset &
Get a specific sequence item by index.
auto sequence_item (std::size_t index) -> dicom_dataset &
Get a specific sequence item by index (mutable)
auto sequence_items () -> std::vector< dicom_dataset > &
Get mutable access to sequence items.
auto sequence_items () const -> const std::vector< dicom_dataset > &
Get read-only access to sequence items.
void add_sequence_item (dicom_dataset item)
Add a new item to the sequence.
void set_value (std::span< const uint8_t > data)
Set the raw value data.
void set_string (std::string_view value)
Set the value from a string.
template<typename T >
requires std::is_arithmetic_v<T>
void set_numeric (T value)
Set the value from a numeric value.
Static Public Member Functions
static auto from_string (dicom_tag tag, encoding::vr_type vr, std::string_view value) -> dicom_element
Create an element from a string value.
template<typename T >
requires std::is_arithmetic_v<T>
static auto from_numeric (dicom_tag tag, encoding::vr_type vr, T value) -> dicom_element
Create an element from a numeric value.
template<typename T >
requires std::is_arithmetic_v<T>
static auto from_numeric_list (dicom_tag tag, encoding::vr_type vr, std::span< const T > values) -> dicom_element
Create an element from multiple numeric values.
Private Member Functions
auto apply_padding (std::string_view str) const -> std::string
Apply DICOM padding to ensure even length.
Static Private Member Functions
static auto remove_padding (std::string_view str, encoding::vr_type vr) -> std::string
Remove DICOM padding from a string value.
Private Attributes
dicom_tag tag_
encoding::vr_type vr_
std::vector< uint8_t > data_
std::vector< dicom_dataset > sequence_items_
Detailed Description
Examples
dcm_dump/main.cpp, dcm_to_json/main.cpp, dcm_to_xml/main.cpp, json_to_dcm/main.cpp, and xml_to_dcm/main.cpp.
Definition at line 67 of file dicom_element.h.
Constructor & Destructor Documentation
dicom_element() [1/4]
kcenon::pacs::core::dicom_element::dicom_element (dicom_tag tag, encoding::vr_type vr) noexcept
Construct an empty element with given tag and VR.
Parameters
tag The DICOM tag
vr The value representation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 24 of file dicom_element.cpp.
    : tag_{tag}, vr_{vr}, data_{}, sequence_items_{} {}
dicom_element() [2/4]
kcenon::pacs::core::dicom_element::dicom_element (dicom_tag tag, encoding::vr_type vr, std::span< const uint8_t > data)
Construct an element with raw data.
Parameters
tag The DICOM tag
vr The value representation
data The raw byte data
Definition at line 27 of file dicom_element.cpp.
    : tag_{tag}, vr_{vr}, data_(data.begin(), data.end()), sequence_items_{} {}
dicom_element() [3/4]
kcenon::pacs::core::dicom_element::dicom_element (const dicom_element &) default
Copy constructor.
dicom_element() [4/4]
kcenon::pacs::core::dicom_element::dicom_element (dicom_element &&) default noexcept
Move constructor.
~dicom_element()
kcenon::pacs::core::dicom_element::~dicom_element () default
Destructor.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Member Function Documentation
add_sequence_item()
void kcenon::pacs::core::dicom_element::add_sequence_item (dicom_dataset item)
Add a new item to the sequence.
Parameters
item The dataset to add (will be moved)
Note
Only valid if is_sequence() returns true
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 179 of file dicom_element.cpp.
{
    sequence_items_.push_back(std::move(item));
}
References sequence_items_.
apply_padding()
auto kcenon::pacs::core::dicom_element::apply_padding (std::string_view str) const -> std::string nodiscard private
Apply DICOM padding to ensure even length.
Parameters
str The input string
Returns
Padded string with even length
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 201 of file dicom_element.cpp.
{
    std::string result{str};
    // DICOM requires even length for all values
    if (result.length() % 2 != 0) {
        result += encoding::padding_char(vr_);
    }
    return result;
}
References kcenon::pacs::encoding::padding_char().
Referenced by set_string().
as_numeric()
template<typename T > requires std::is_arithmetic_v<T> auto kcenon::pacs::core::dicom_element::as_numeric () const -> kcenon::pacs::Result<T> nodiscard
Get the value as a numeric type.
Template Parameters
T The target numeric type
Returns
Result containing the numeric value, or error if conversion fails
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h, and dcm_dump/main.cpp.
Definition at line 369 of file dicom_element.h.
{
    if (data_.size() < sizeof(T)) {
        return kcenon::pacs::pacs_error<T>(
            kcenon::pacs::error_codes::data_size_mismatch,
            "Insufficient data for numeric conversion: expected " +
                std::to_string(sizeof(T)) + " bytes, got " +
                std::to_string(data_.size()));
    }
    T result{};
    std::memcpy(&result, data_.data(), sizeof(T));
    return kcenon::pacs::ok(result);
}
References data_, kcenon::pacs::error_codes::data_size_mismatch, and kcenon::pacs::pacs_error().
Referenced by as_string().
as_numeric_list()
template<typename T > requires std::is_arithmetic_v<T> auto kcenon::pacs::core::dicom_element::as_numeric_list () const -> kcenon::pacs::Result<std::vector<T>> nodiscard
Get multi-valued numeric data as a list.
Template Parameters
T The target numeric type
Returns
Result containing vector of numeric values, or error if conversion fails
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h, dcm_to_json/main.cpp, and dcm_to_xml/main.cpp.
Definition at line 385 of file dicom_element.h.
{
    if (data_.size() % sizeof(T) != 0) {
        return kcenon::pacs::pacs_error<std::vector<T>>(
            kcenon::pacs::error_codes::data_size_mismatch,
            "Data size not aligned for numeric type: " +
                std::to_string(data_.size()) + " bytes is not divisible by " +
                std::to_string(sizeof(T)));
    }
    const size_t count = data_.size() / sizeof(T);
    std::vector<T> result(count);
    for (size_t i = 0; i < count; ++i) {
        std::memcpy(&result[i], data_.data() + i * sizeof(T), sizeof(T));
    }
    return kcenon::pacs::ok(result);
}
References data_, and kcenon::pacs::error_codes::data_size_mismatch.
as_string()
auto kcenon::pacs::core::dicom_element::as_string () const -> kcenon::pacs::Result<std::string> nodiscard
Get the value as a string.
For string VRs, returns the value with trailing padding removed. For numeric VRs, converts the value to a string representation.
Returns
Result containing the string value, or error if conversion fails
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h, dcm_dump/main.cpp, dcm_to_json/main.cpp, and dcm_to_xml/main.cpp.
Definition at line 52 of file dicom_element.cpp.
{
    if (data_.empty()) {
        return kcenon::pacs::ok(std::string{});
    }
    // For string VRs, convert bytes to string and remove padding
    if (encoding::is_string_vr(vr_)) {
        std::string_view raw{reinterpret_cast<const char*>(data_.data()),
                             data_.size()};
        return kcenon::pacs::ok(remove_padding(raw, vr_));
    }
    // For numeric VRs, convert to string representation
    if (encoding::is_numeric_vr(vr_)) {
        switch (vr_) {
            case encoding::vr_type::US:
                if (data_.size() >= 2) {
                    if (auto val = as_numeric<uint16_t>(); val.is_ok())
                        return kcenon::pacs::ok(std::to_string(val.value()));
                }
                break;
            case encoding::vr_type::SS:
                if (data_.size() >= 2) {
                    if (auto val = as_numeric<int16_t>(); val.is_ok())
                        return kcenon::pacs::ok(std::to_string(val.value()));
                }
                break;
            case encoding::vr_type::UL:
                if (data_.size() >= 4) {
                    if (auto val = as_numeric<uint32_t>(); val.is_ok())
                        return kcenon::pacs::ok(std::to_string(val.value()));
                }
                break;
            case encoding::vr_type::SL:
                if (data_.size() >= 4) {
                    if (auto val = as_numeric<int32_t>(); val.is_ok())
                        return kcenon::pacs::ok(std::to_string(val.value()));
                }
                break;
            case encoding::vr_type::UV:
                if (data_.size() >= 8) {
                    if (auto val = as_numeric<uint64_t>(); val.is_ok())
                        return kcenon::pacs::ok(std::to_string(val.value()));
                }
                break;
            case encoding::vr_type::SV:
                if (data_.size() >= 8) {
                    if (auto val = as_numeric<int64_t>(); val.is_ok())
                        return kcenon::pacs::ok(std::to_string(val.value()));
                }
                break;
            case encoding::vr_type::FL:
                if (data_.size() >= 4) {
                    if (auto val = as_numeric<float>(); val.is_ok())
                        return kcenon::pacs::ok(std::to_string(val.value()));
                }
                break;
            case encoding::vr_type::FD:
                if (data_.size() >= 8) {
                    if (auto val = as_numeric<double>(); val.is_ok())
                        return kcenon::pacs::ok(std::to_string(val.value()));
                }
                break;
            default:
                break;
        }
    }
    // For binary VRs or unknown, return raw bytes as string
    return kcenon::pacs::ok(
        std::string{reinterpret_cast<const char*>(data_.data()), data_.size()});
}
References as_numeric(), data_, kcenon::pacs::encoding::FD, kcenon::pacs::encoding::FL, kcenon::pacs::encoding::is_numeric_vr(), kcenon::pacs::encoding::is_string_vr(), remove_padding(), kcenon::pacs::encoding::SL, kcenon::pacs::encoding::SS, kcenon::pacs::encoding::SV, kcenon::pacs::encoding::UL, kcenon::pacs::encoding::US, kcenon::pacs::encoding::UV, and vr_.
Referenced by as_string_list().
as_string_list()
auto kcenon::pacs::core::dicom_element::as_string_list () const -> kcenon::pacs::Result<std::vector<std::string>> nodiscard
Get multi-valued string as a list.
Splits the value by backslash delimiter (DICOM VM > 1).
Returns
Result containing vector of individual string values, or error
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 125 of file dicom_element.cpp.
{
    auto str_result = as_string();
    if (str_result.is_err()) {
        return kcenon::pacs::pacs_error<std::vector<std::string>>(
            str_result.error().code, str_result.error().message);
    }
    const std::string str = str_result.value();
    std::vector<std::string> result;
    if (str.empty()) {
        return kcenon::pacs::ok(result);
    }
    // Split by backslash (DICOM VM delimiter)
    std::string::size_type start = 0;
    std::string::size_type pos = 0;
    while ((pos = str.find('\\', start)) != std::string::npos) {
        result.push_back(str.substr(start, pos - start));
        start = pos + 1;
    }
    // Add the last segment
    result.push_back(str.substr(start));
    return kcenon::pacs::ok(result);
}
References as_string(), and code.
from_numeric()
template<typename T > requires std::is_arithmetic_v<T> auto kcenon::pacs::core::dicom_element::from_numeric (dicom_tag tag, encoding::vr_type vr, T value) -> dicom_element static nodiscard
Create an element from a numeric value.
Template Parameters
T The numeric type (uint16_t, int32_t, float, double, etc.)
Parameters
tag The DICOM tag
vr The value representation (should be a numeric VR)
value The numeric value
Returns
A new dicom_element containing the value
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_dataset.h, and /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 345 of file dicom_element.h.
{
    dicom_element elem{tag, vr};
    elem.set_numeric(value);
    return elem;
}
References set_numeric(), tag(), and vr().
Referenced by kcenon::pacs::integration::container_adapter::from_container_value(), and kcenon::pacs::core::dicom_dataset::set_numeric().
from_numeric_list()
template<typename T > requires std::is_arithmetic_v<T> auto kcenon::pacs::core::dicom_element::from_numeric_list (dicom_tag tag, encoding::vr_type vr, std::span< const T > values) -> dicom_element static nodiscard
Create an element from multiple numeric values.
Template Parameters
T The numeric type
Parameters
tag The DICOM tag
vr The value representation
values The numeric values
Returns
A new dicom_element containing all values
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 354 of file dicom_element.h.
{
    dicom_element elem{tag, vr};
    std::vector<uint8_t> data(values.size() * sizeof(T));
    for (size_t i = 0; i < values.size(); ++i) {
        std::memcpy(data.data() + i * sizeof(T), &values[i], sizeof(T));
    }
    elem.set_value(data);
    return elem;
}
References tag(), and vr().
from_string()
auto kcenon::pacs::core::dicom_element::from_string (dicom_tag tag, encoding::vr_type vr, std::string_view value) -> dicom_element static nodiscard
Create an element from a string value.
Parameters
tag The DICOM tag
vr The value representation (should be a string VR)
value The string value
Returns
A new dicom_element containing the string
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 41 of file dicom_element.cpp.
{
    dicom_element elem{tag, vr};
    elem.set_string(value);
    return elem;
}
References set_string(), and vr.
Referenced by kcenon::pacs::integration::container_adapter::from_container_value(), kcenon::pacs::encoding::set_encoded_string(), and kcenon::pacs::core::dicom_dataset::set_string().
is_empty()
auto kcenon::pacs::core::dicom_element::is_empty () const -> bool inline nodiscard noexcept
Check if the element has no value.
Returns
true if the value is empty
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h, dcm_dump/main.cpp, dcm_to_json/main.cpp, and dcm_to_xml/main.cpp.
Definition at line 186 of file dicom_element.h.
{ return data_.empty(); }
References data_.
is_sequence()
auto kcenon::pacs::core::dicom_element::is_sequence () const -> bool inline nodiscard noexcept
Check if this element is a sequence.
Returns
true if VR is SQ
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h, dcm_dump/main.cpp, dcm_to_json/main.cpp, and dcm_to_xml/main.cpp.
Definition at line 242 of file dicom_element.h.
{
        return vr_ == encoding::vr_type::SQ;
    }
References kcenon::pacs::encoding::SQ, and vr_.
Referenced by kcenon::pacs::encoding::explicit_vr_big_endian_codec::encode_element(), kcenon::pacs::encoding::explicit_vr_codec::encode_element(), and kcenon::pacs::encoding::implicit_vr_codec::encode_element().
length()
auto kcenon::pacs::core::dicom_element::length () const -> uint32_t inline nodiscard noexcept
Get the value length in bytes.
Returns
The number of bytes in the value
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 170 of file dicom_element.h.
{
        return static_cast<uint32_t>(data_.size());
    }
References data_.
operator=() [1/2]
auto kcenon::pacs::core::dicom_element::operator= (const dicom_element &) -> dicom_element & default
Copy assignment.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
operator=() [2/2]
auto kcenon::pacs::core::dicom_element::operator= (dicom_element &&) -> dicom_element & default noexcept
Move assignment.
raw_data()
auto kcenon::pacs::core::dicom_element::raw_data () const -> std::span<const uint8_t> inline nodiscard noexcept
Get the raw data bytes.
Returns
A span view of the raw data
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h, dcm_dump/main.cpp, dcm_to_json/main.cpp, and dcm_to_xml/main.cpp.
Definition at line 178 of file dicom_element.h.
{
        return data_;
    }
References data_.
Referenced by kcenon::pacs::encoding::explicit_vr_big_endian_codec::encode_element(), kcenon::pacs::encoding::explicit_vr_codec::encode_element(), and kcenon::pacs::encoding::implicit_vr_codec::encode_element().
remove_padding()
auto kcenon::pacs::core::dicom_element::remove_padding (std::string_view str, encoding::vr_type vr) -> std::string static nodiscard private
Remove DICOM padding from a string value.
Parameters
str The padded string
Returns
String with padding removed
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 212 of file dicom_element.cpp.
{
    if (str.empty()) {
        return {};
    }
    std::string result{str};
    // Determine padding character based on VR
    const char pad = encoding::padding_char(vr);
    // Remove trailing padding characters
    while (!result.empty() && result.back() == pad) {
        result.pop_back();
    }
    // For string VRs (except UI), also trim trailing spaces
    if (encoding::is_string_vr(vr) && vr != encoding::vr_type::UI) {
        while (!result.empty() && result.back() == ' ') {
            result.pop_back();
        }
    }
    return result;
}
References kcenon::pacs::encoding::is_string_vr(), kcenon::pacs::encoding::padding_char(), kcenon::pacs::encoding::UI, and vr.
Referenced by as_string().
sequence_item() [1/2]
auto kcenon::pacs::core::dicom_element::sequence_item (std::size_t index) -> dicom_dataset& nodiscard
Get a specific sequence item by index (mutable)
Parameters
index The zero-based index of the item
Returns
Reference to the dataset at the given index
Exceptions
std::out_of_range if index >= sequence_item_count()
Note
Only valid if is_sequence() returns true
Definition at line 167 of file dicom_element.cpp.
{
    return sequence_items_.at(index);
}
sequence_item() [2/2]
auto kcenon::pacs::core::dicom_element::sequence_item (std::size_t index) const -> const dicom_dataset& nodiscard
Get a specific sequence item by index.
Parameters
index The zero-based index of the item
Returns
Const reference to the dataset at the given index
Exceptions
std::out_of_range if index >= sequence_item_count()
Note
Only valid if is_sequence() returns true
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 162 of file dicom_element.cpp.
{
    return sequence_items_.at(index);
}
sequence_item_count()
auto kcenon::pacs::core::dicom_element::sequence_item_count () const -> std::size_t nodiscard noexcept
Get the number of items in the sequence.
Returns
Number of sequence items, or 0 if not a sequence or empty
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 158 of file dicom_element.cpp.
{
    return sequence_items_.size();
}
References sequence_items_.
sequence_items() [1/2]
auto kcenon::pacs::core::dicom_element::sequence_items () -> std::vector<dicom_dataset>& nodiscard
Get mutable access to sequence items.
Returns
Reference to the sequence items vector
Note
Only valid if is_sequence() returns true
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h, dcm_dump/main.cpp, dcm_to_json/main.cpp, and dcm_to_xml/main.cpp.
Definition at line 171 of file dicom_element.cpp.
{
    return sequence_items_;
}
Referenced by kcenon::pacs::encoding::explicit_vr_big_endian_codec::decode_undefined_length(), kcenon::pacs::encoding::explicit_vr_codec::decode_undefined_length(), kcenon::pacs::encoding::implicit_vr_codec::decode_undefined_length(), kcenon::pacs::encoding::explicit_vr_big_endian_codec::encode_sequence(), kcenon::pacs::encoding::explicit_vr_codec::encode_sequence(), and kcenon::pacs::encoding::implicit_vr_codec::encode_sequence().
sequence_items() [2/2]
auto kcenon::pacs::core::dicom_element::sequence_items () const -> const std::vector<dicom_dataset>& nodiscard
Get read-only access to sequence items.
Returns
Const reference to the sequence items vector
Note
Only valid if is_sequence() returns true
Definition at line 175 of file dicom_element.cpp.
{
    return sequence_items_;
}
References sequence_items_.
set_numeric()
template<typename T > requires std::is_arithmetic_v<T> void kcenon::pacs::core::dicom_element::set_numeric (T value)
Set the value from a numeric value.
Template Parameters
T The numeric type
Parameters
value The numeric value
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 406 of file dicom_element.h.
{
    data_.resize(sizeof(T));
    std::memcpy(data_.data(), &value, sizeof(T));
}
References data_.
Referenced by from_numeric().
set_string()
void kcenon::pacs::core::dicom_element::set_string (std::string_view value)
Set the value from a string.
Parameters
value The string value (will be padded if needed)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 191 of file dicom_element.cpp.
{
    // Apply padding for string VRs
    std::string padded = apply_padding(value);
    data_.assign(padded.begin(), padded.end());
}
References apply_padding(), and data_.
Referenced by from_string().
set_value()
void kcenon::pacs::core::dicom_element::set_value (std::span< const uint8_t > data)
Set the raw value data.
Parameters
data The new raw data
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 187 of file dicom_element.cpp.
{
    data_.assign(data.begin(), data.end());
}
References data_.
Referenced by kcenon::pacs::integration_test::test_data_generator::add_multiframe_pixel_data(), kcenon::pacs::integration_test::test_data_generator::add_pixel_data(), kcenon::pacs::integration_test::generate_ct_dataset(), kcenon::pacs::integration_test::generate_mr_dataset(), kcenon::pacs::integration_test::generate_xa_dataset(), and kcenon::pacs::integration_test::test_data_generator::invalid().
tag()
auto kcenon::pacs::core::dicom_element::tag () const -> dicom_tag inline nodiscard constexpr noexcept
Get the element's tag.
Returns
The DICOM tag
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 158 of file dicom_element.h.
{ return tag_; }
References tag_.
Referenced by kcenon::pacs::encoding::explicit_vr_big_endian_codec::encode_element(), kcenon::pacs::encoding::explicit_vr_codec::encode_element(), kcenon::pacs::encoding::implicit_vr_codec::encode_element(), from_numeric(), from_numeric_list(), and kcenon::pacs::core::dicom_dataset::insert().
vr()
auto kcenon::pacs::core::dicom_element::vr () const -> encoding::vr_type inline nodiscard constexpr noexcept
Get the element's VR.
Returns
The value representation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h, dcm_dump/main.cpp, dcm_to_json/main.cpp, and dcm_to_xml/main.cpp.
Definition at line 164 of file dicom_element.h.
{ return vr_; }
References vr_.
Referenced by kcenon::pacs::encoding::explicit_vr_big_endian_codec::encode_element(), kcenon::pacs::encoding::explicit_vr_codec::encode_element(), kcenon::pacs::encoding::implicit_vr_codec::encode_element(), from_numeric(), and from_numeric_list().
Member Data Documentation
data_
std::vector<uint8_t> kcenon::pacs::core::dicom_element::data_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 320 of file dicom_element.h.
Referenced by as_numeric(), as_numeric_list(), as_string(), is_empty(), length(), raw_data(), set_numeric(), set_string(), and set_value().
sequence_items_
std::vector<dicom_dataset> kcenon::pacs::core::dicom_element::sequence_items_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 321 of file dicom_element.h.
Referenced by add_sequence_item(), sequence_item_count(), and sequence_items().
tag_
dicom_tag kcenon::pacs::core::dicom_element::tag_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 318 of file dicom_element.h.
Referenced by tag().
vr_
encoding::vr_type kcenon::pacs::core::dicom_element::vr_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h.
Definition at line 319 of file dicom_element.h.
Referenced by as_string(), is_sequence(), and vr().
The documentation for this class was generated from the following files:
include/kcenon/pacs/core/dicom_element.h
src/core/dicom_element.cpp