PACS System: kcenon::pacs::services::validation::us_iod_validator Class Reference
kcenon::pacs::services::validation::us_iod_validator Class Reference
#include <us_iod_validator.h>
Public Member Functions
us_iod_validator ()=default
Construct validator with default options.
us_iod_validator (const us_validation_options &options)
Construct validator with custom options.
validation_result validate (const core::dicom_dataset &dataset) const
Validate a DICOM dataset against US IOD.
validation_result validate_multiframe (const core::dicom_dataset &dataset) const
Validate a multi-frame US dataset.
bool quick_check (const core::dicom_dataset &dataset) const
Quick check if dataset has minimum required attributes.
const us_validation_options & options () const noexcept
Get the validation options.
void set_options (const us_validation_options &options)
Set validation options.
Private Member Functions
void validate_patient_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_study_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_series_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_us_image_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_image_pixel_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_multiframe_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_sop_common_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_type1_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_type2_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_modality (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_pixel_data_consistency (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
Private Attributes
us_validation_options options_
Detailed Description
Definition at line 157 of file us_iod_validator.h.
Constructor & Destructor Documentation
us_iod_validator() [1/2]
kcenon::pacs::services::validation::us_iod_validator::us_iod_validator () default
Construct validator with default options.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
us_iod_validator() [2/2]
kcenon::pacs::services::validation::us_iod_validator::us_iod_validator (const us_validation_options & options) explicit
Construct validator with custom options.
Parameters
options Validation options
Definition at line 74 of file us_iod_validator.cpp.
    : options_(options) {}
Member Function Documentation
check_modality()
void kcenon::pacs::services::validation::us_iod_validator::check_modality (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 375 of file us_iod_validator.cpp.
{
    if (!dataset.contains(tags::modality)) {
        return;  // Already reported as Type 1 missing
    }
    auto modality = dataset.get_string(tags::modality);
    if (modality != "US") {
        findings.push_back({
            validation_severity::error,
            tags::modality,
            "Modality must be 'US' for ultrasound images, found: " + modality,
            "US-ERR-002"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), and kcenon::pacs::core::tags::modality.
Referenced by validate_general_series_module().
check_pixel_data_consistency()
void kcenon::pacs::services::validation::us_iod_validator::check_pixel_data_consistency (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 394 of file us_iod_validator.cpp.
{
    // Check BitsStored <= BitsAllocated
    auto bits_allocated = dataset.get_numeric<uint16_t>(tags::bits_allocated);
    auto bits_stored = dataset.get_numeric<uint16_t>(tags::bits_stored);
    auto high_bit = dataset.get_numeric<uint16_t>(tags::high_bit);
    if (bits_allocated && bits_stored) {
        if (*bits_stored > *bits_allocated) {
            findings.push_back({
                validation_severity::error,
                tags::bits_stored,
                "BitsStored (" + std::to_string(*bits_stored) +
                ") exceeds BitsAllocated (" + std::to_string(*bits_allocated) + ")",
                "US-ERR-003"
            });
        }
    }
    // Check HighBit == BitsStored - 1
    if (bits_stored && high_bit) {
        if (*high_bit != *bits_stored - 1) {
            findings.push_back({
                validation_severity::warning,
                tags::high_bit,
                "HighBit (" + std::to_string(*high_bit) +
                ") should typically be BitsStored - 1 (" +
                std::to_string(*bits_stored - 1) + ")",
                "US-WARN-002"
            });
        }
    }
    // Check photometric interpretation is valid for US
    if (dataset.contains(tags::photometric_interpretation)) {
        auto photometric = dataset.get_string(tags::photometric_interpretation);
        if (!sop_classes::is_valid_us_photometric(photometric)) {
            findings.push_back({
                validation_severity::warning,
                tags::photometric_interpretation,
                "Unusual photometric interpretation for US: " + photometric,
                "US-WARN-003"
            });
        }
    }
    // Check SamplesPerPixel consistency with photometric
    auto samples = dataset.get_numeric<uint16_t>(tags::samples_per_pixel);
    if (samples && dataset.contains(tags::photometric_interpretation)) {
        auto photometric = dataset.get_string(tags::photometric_interpretation);
        bool is_color = (photometric == "RGB" || photometric == "YBR_FULL" ||
                        photometric == "YBR_FULL_422" || photometric == "PALETTE COLOR");
        if (is_color && *samples != 3) {
            findings.push_back({
                validation_severity::error,
                tags::samples_per_pixel,
                "Color photometric interpretation requires SamplesPerPixel = 3",
                "US-ERR-004"
            });
        }
        if (!is_color && *samples != 1) {
            findings.push_back({
                validation_severity::error,
                tags::samples_per_pixel,
                "Grayscale photometric interpretation requires SamplesPerPixel = 1",
                "US-ERR-005"
            });
        }
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_numeric(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::services::sop_classes::is_valid_us_photometric(), kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::samples_per_pixel, and kcenon::pacs::services::validation::warning.
Referenced by validate_image_pixel_module().
check_type1_attribute()
void kcenon::pacs::services::validation::us_iod_validator::check_type1_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 328 of file us_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::error,
            tag,
            std::string("Type 1 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "US-TYPE1-MISSING"
        });
    } else {
        // Type 1 must have a value (cannot be empty)
        auto value = dataset.get_string(tag);
        if (value.empty()) {
            findings.push_back({
                validation_severity::error,
                tag,
                std::string("Type 1 attribute has empty value: ") +
                std::string(name) + " (" + tag.to_string() + ")",
                "US-TYPE1-EMPTY"
            });
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), name, and kcenon::pacs::core::dicom_tag::to_string().
Referenced by validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_multiframe_module(), and validate_sop_common_module().
check_type2_attribute()
void kcenon::pacs::services::validation::us_iod_validator::check_type2_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 357 of file us_iod_validator.cpp.
{
    // Type 2 must be present but can be empty
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::warning,
            tag,
            std::string("Type 2 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "US-TYPE2-MISSING"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), name, kcenon::pacs::core::dicom_tag::to_string(), and kcenon::pacs::services::validation::warning.
Referenced by validate_general_series_module(), validate_general_study_module(), and validate_patient_module().
options()
const us_validation_options & kcenon::pacs::services::validation::us_iod_validator::options () const nodiscard noexcept
Get the validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 163 of file us_iod_validator.cpp.
{
    return options_;
}
References options_.
Referenced by set_options().
quick_check()
bool kcenon::pacs::services::validation::us_iod_validator::quick_check (const core::dicom_dataset & dataset) const nodiscard
Quick check if dataset has minimum required attributes.
Faster than full validation - only checks Type 1 attributes.
Parameters
dataset The dataset to check
Returns
true if all Type 1 attributes are present
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 128 of file us_iod_validator.cpp.
{
    // Check only Type 1 required attributes for quick validation
    // Patient Module Type 1
    // (Patient module has Type 2 attributes, no Type 1)
    // General Study Module Type 1
    if (!dataset.contains(tags::study_instance_uid)) return false;
    // General Series Module Type 1
    if (!dataset.contains(tags::modality)) return false;
    if (!dataset.contains(tags::series_instance_uid)) return false;
    // Check modality is US
    auto modality = dataset.get_string(tags::modality);
    if (modality != "US") return false;
    // Image Pixel Module Type 1
    if (!dataset.contains(tags::samples_per_pixel)) return false;
    if (!dataset.contains(tags::photometric_interpretation)) return false;
    if (!dataset.contains(tags::rows)) return false;
    if (!dataset.contains(tags::columns)) return false;
    if (!dataset.contains(tags::bits_allocated)) return false;
    if (!dataset.contains(tags::bits_stored)) return false;
    if (!dataset.contains(tags::high_bit)) return false;
    if (!dataset.contains(tags::pixel_representation)) return false;
    if (!dataset.contains(tags::pixel_data)) return false;
    // SOP Common Module Type 1
    if (!dataset.contains(tags::sop_class_uid)) return false;
    if (!dataset.contains(tags::sop_instance_uid)) return false;
    return true;
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::tags::columns, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, and kcenon::pacs::core::tags::study_instance_uid.
Referenced by kcenon::pacs::services::validation::is_valid_us_dataset().
set_options()
void kcenon::pacs::services::validation::us_iod_validator::set_options (const us_validation_options & options)
Set validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 167 of file us_iod_validator.cpp.
{
    options_ = options;
}
References options(), and options_.
validate()
validation_result kcenon::pacs::services::validation::us_iod_validator::validate (const core::dicom_dataset & dataset) const nodiscard
Validate a DICOM dataset against US IOD.
Parameters
dataset The dataset to validate
Returns
Validation result with all findings
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 77 of file us_iod_validator.cpp.
{
    validation_result result;
    result.is_valid = true;
    // Validate mandatory modules
    if (options_.check_type1 || options_.check_type2) {
        validate_patient_module(dataset, result.findings);
        validate_general_study_module(dataset, result.findings);
        validate_general_series_module(dataset, result.findings);
        validate_us_image_module(dataset, result.findings);
        validate_sop_common_module(dataset, result.findings);
    }
    if (options_.validate_pixel_data) {
        validate_image_pixel_module(dataset, result.findings);
    }
    // Check for errors
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
        if (options_.strict_mode && finding.severity == validation_severity::warning) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References kcenon::pacs::services::validation::us_validation_options::check_type1, kcenon::pacs::services::validation::us_validation_options::check_type2, kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::services::validation::validation_result::is_valid, options_, kcenon::pacs::services::validation::us_validation_options::strict_mode, validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_patient_module(), kcenon::pacs::services::validation::us_validation_options::validate_pixel_data, validate_sop_common_module(), validate_us_image_module(), and kcenon::pacs::services::validation::warning.
Referenced by validate_multiframe(), and kcenon::pacs::services::validation::validate_us_iod().
validate_general_series_module()
void kcenon::pacs::services::validation::us_iod_validator::validate_general_series_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 207 of file us_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::modality, "Modality", findings);
        check_type1_attribute(dataset, tags::series_instance_uid, "SeriesInstanceUID", findings);
        // Special check: Modality must be "US"
        check_modality(dataset, findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::series_number, "SeriesNumber", findings);
    }
}
References check_modality(), kcenon::pacs::services::validation::us_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::us_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::tags::modality, options_, kcenon::pacs::core::tags::series_instance_uid, and kcenon::pacs::core::tags::series_number.
Referenced by validate().
validate_general_study_module()
void kcenon::pacs::services::validation::us_iod_validator::validate_general_study_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 188 of file us_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::study_instance_uid, "StudyInstanceUID", findings);
    }
    // Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::study_date, "StudyDate", findings);
        check_type2_attribute(dataset, tags::study_time, "StudyTime", findings);
        check_type2_attribute(dataset, tags::referring_physician_name, "ReferringPhysicianName", findings);
        check_type2_attribute(dataset, tags::study_id, "StudyID", findings);
        check_type2_attribute(dataset, tags::accession_number, "AccessionNumber", findings);
    }
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::services::validation::us_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::us_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::core::tags::study_time.
Referenced by validate().
validate_image_pixel_module()
void kcenon::pacs::services::validation::us_iod_validator::validate_image_pixel_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 250 of file us_iod_validator.cpp.
{
    // Type 1 attributes
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::samples_per_pixel, "SamplesPerPixel", findings);
        check_type1_attribute(dataset, tags::photometric_interpretation, "PhotometricInterpretation", findings);
        check_type1_attribute(dataset, tags::rows, "Rows", findings);
        check_type1_attribute(dataset, tags::columns, "Columns", findings);
        check_type1_attribute(dataset, tags::bits_allocated, "BitsAllocated", findings);
        check_type1_attribute(dataset, tags::bits_stored, "BitsStored", findings);
        check_type1_attribute(dataset, tags::high_bit, "HighBit", findings);
        check_type1_attribute(dataset, tags::pixel_representation, "PixelRepresentation", findings);
        check_type1_attribute(dataset, tags::pixel_data, "PixelData", findings);
    }
    // Validate pixel data consistency
    if (options_.validate_pixel_data) {
        check_pixel_data_consistency(dataset, findings);
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, check_pixel_data_consistency(), kcenon::pacs::services::validation::us_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::tags::columns, kcenon::pacs::core::tags::high_bit, options_, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, and kcenon::pacs::services::validation::us_validation_options::validate_pixel_data.
Referenced by validate().
validate_multiframe()
validation_result kcenon::pacs::services::validation::us_iod_validator::validate_multiframe (const core::dicom_dataset & dataset) const nodiscard
Validate a multi-frame US dataset.
Performs additional validation for multi-frame specific attributes.
Parameters
dataset The dataset to validate
Returns
Validation result with all findings
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 110 of file us_iod_validator.cpp.
{
    // First do standard validation
    auto result = validate(dataset);
    // Then add multi-frame specific validation
    validate_multiframe_module(dataset, result.findings);
    // Re-check validity after multi-frame validation
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References kcenon::pacs::services::validation::error, validate(), and validate_multiframe_module().
validate_multiframe_module()
void kcenon::pacs::services::validation::us_iod_validator::validate_multiframe_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 273 of file us_iod_validator.cpp.
{
    constexpr dicom_tag number_of_frames{0x0028, 0x0008};
    constexpr dicom_tag frame_time{0x0018, 0x1063};
    constexpr dicom_tag frame_time_vector{0x0018, 0x1065};
    // NumberOfFrames is Type 1 for multi-frame
    if (options_.check_type1) {
        check_type1_attribute(dataset, number_of_frames, "NumberOfFrames", findings);
    }
    // FrameTime or FrameTimeVector should be present (Type 1C)
    if (options_.check_conditional) {
        if (!dataset.contains(frame_time) && !dataset.contains(frame_time_vector)) {
            findings.push_back({
                validation_severity::warning,
                frame_time,
                "Neither FrameTime nor FrameTimeVector present - "
                "frame timing information missing",
                "US-WARN-001"
            });
        }
    }
}
References kcenon::pacs::services::validation::us_validation_options::check_conditional, kcenon::pacs::services::validation::us_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), number_of_frames, options_, and kcenon::pacs::services::validation::warning.
Referenced by validate_multiframe().
validate_patient_module()
void kcenon::pacs::services::validation::us_iod_validator::validate_patient_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 175 of file us_iod_validator.cpp.
{
    // Patient Module - All attributes are Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::patient_name, "PatientName", findings);
        check_type2_attribute(dataset, tags::patient_id, "PatientID", findings);
        check_type2_attribute(dataset, tags::patient_birth_date, "PatientBirthDate", findings);
        check_type2_attribute(dataset, tags::patient_sex, "PatientSex", findings);
    }
}
References kcenon::pacs::services::validation::us_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, and kcenon::pacs::core::tags::patient_sex.
Referenced by validate().
validate_sop_common_module()
void kcenon::pacs::services::validation::us_iod_validator::validate_sop_common_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 300 of file us_iod_validator.cpp.
{
    // Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::sop_class_uid, "SOPClassUID", findings);
        check_type1_attribute(dataset, tags::sop_instance_uid, "SOPInstanceUID", findings);
    }
    // Validate SOP Class UID is a US storage class
    if (dataset.contains(tags::sop_class_uid)) {
        auto sop_class = dataset.get_string(tags::sop_class_uid);
        if (!sop_classes::is_us_storage_sop_class(sop_class)) {
            findings.push_back({
                validation_severity::error,
                tags::sop_class_uid,
                "SOPClassUID is not a recognized US Storage SOP Class: " + sop_class,
                "US-ERR-001"
            });
        }
    }
}
References kcenon::pacs::services::validation::us_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_us_storage_sop_class(), options_, kcenon::pacs::core::tags::sop_class_uid, and kcenon::pacs::core::tags::sop_instance_uid.
Referenced by validate().
validate_us_image_module()
void kcenon::pacs::services::validation::us_iod_validator::validate_us_image_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 226 of file us_iod_validator.cpp.
{
    // US Image Module validation
    // Sequence of Ultrasound Regions (0018,6011) is Type 1C - required if
    // the Ultrasound image contains calibrated regions
    // Note: The exact conditional logic depends on the presence of
    // calibration data. For now, we add an info finding if it's missing.
    if (options_.check_conditional) {
        constexpr dicom_tag sequence_of_ultrasound_regions{0x0018, 0x6011};
        if (!dataset.contains(sequence_of_ultrasound_regions)) {
            findings.push_back({
                validation_severity::info,
                sequence_of_ultrasound_regions,
                "SequenceOfUltrasoundRegions (0018,6011) not present - "
                "no calibration information available",
                "US-INFO-001"
            });
        }
    }
}
References kcenon::pacs::services::validation::us_validation_options::check_conditional, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::info, and options_.
Referenced by validate().
Member Data Documentation
options_
us_validation_options kcenon::pacs::services::validation::us_iod_validator::options_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 260 of file us_iod_validator.h.
Referenced by options(), set_options(), validate(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_multiframe_module(), validate_patient_module(), validate_sop_common_module(), and validate_us_image_module().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/validation/us_iod_validator.h
src/services/validation/us_iod_validator.cpp