PACS System: kcenon::pacs::services::storage_scp Class Reference
kcenon::pacs::services::storage_scp Class Reference final
#include <storage_scp.h>
Public Member Functions
storage_scp (std::shared_ptr< di::ILogger > logger=nullptr)
Construct a Storage SCP with default configuration.
storage_scp (const storage_scp_config &config, std::shared_ptr< di::ILogger > logger=nullptr)
Construct a Storage SCP with custom configuration.
~storage_scp () override=default
void set_handler (storage_handler handler)
Set the storage handler callback.
void set_pre_store_handler (pre_store_handler handler)
Set the pre-store validation handler.
void set_post_store_handler (post_store_handler handler)
void set_audit_handler (std::shared_ptr< kcenon::pacs::security::atna_service_auditor > auditor)
Set the ATNA audit handler for C-STORE operations.
std::vector< std::string > supported_sop_classes () const override
Get supported SOP Class UIDs.
network::Result< std::monostate > handle_message (network::association &assoc, uint8_t context_id, const network::dimse::dimse_message &request) override
Handle an incoming DIMSE message (C-STORE-RQ)
std::string_view service_name () const noexcept override
Get the service name.
size_t images_received () const noexcept
Get the number of images received since construction.
size_t bytes_received () const noexcept
Get the total bytes received since construction.
void reset_statistics () noexcept
Reset statistics counters to zero.
Public Member Functions inherited from kcenon::pacs::services::scp_service
scp_service (std::shared_ptr< di::ILogger > logger=nullptr)
Construct SCP service with optional logger.
virtual ~scp_service ()=default
scp_service (const scp_service &)=delete
scp_service & operator= (const scp_service &)=delete
scp_service (scp_service &&)=default
scp_service & operator= (scp_service &&)=default
void set_logger (std::shared_ptr< di::ILogger > logger)
Set the logger instance.
const std::shared_ptr< di::ILogger > & logger () const noexcept
Get the current logger instance.
bool supports_sop_class (std::string_view sop_class_uid) const
Check if this service supports a specific SOP Class.
Private Attributes
storage_scp_config config_
Configuration.
storage_handler handler_
Main storage handler.
pre_store_handler pre_store_handler_
Pre-store validation handler.
post_store_handler post_store_handler_
Post-store notification handler.
std::shared_ptr< kcenon::pacs::security::atna_service_auditor > auditor_
ATNA audit handler.
std::atomic< size_t > images_received_ {0}
Statistics: number of images received.
std::atomic< size_t > bytes_received_ {0}
Statistics: total bytes received.
Additional Inherited Members
Protected Attributes inherited from kcenon::pacs::services::scp_service
std::shared_ptr< di::ILogger > logger_
Logger instance for service logging.
Detailed Description
Definition at line 161 of file storage_scp.h.
Constructor & Destructor Documentation
storage_scp() [1/2]
kcenon::pacs::services::storage_scp::storage_scp (std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct a Storage SCP with default configuration.
Parameters
logger Logger instance for service logging (nullptr uses null_logger)
Definition at line 26 of file storage_scp.cpp.
    : scp_service(std::move(logger)) {}
storage_scp() [2/2]
kcenon::pacs::services::storage_scp::storage_scp (const storage_scp_config & config, std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct a Storage SCP with custom configuration.
Parameters
config Configuration options
logger Logger instance for service logging (nullptr uses null_logger)
Definition at line 29 of file storage_scp.cpp.
    : scp_service(std::move(logger)), config_(config) {}
~storage_scp()
kcenon::pacs::services::storage_scp::~storage_scp () override default
Member Function Documentation
bytes_received()
size_t kcenon::pacs::services::storage_scp::bytes_received () const nodiscard noexcept
Get the total bytes received since construction.
Returns
Total bytes of dataset data received
Definition at line 209 of file storage_scp.cpp.
{
    return bytes_received_.load(std::memory_order_relaxed);
}
References bytes_received_.
handle_message()
network::Result< std::monostate > kcenon::pacs::services::storage_scp::handle_message (network::association & assoc, uint8_t context_id, const network::dimse::dimse_message & request) nodiscard override virtual
Handle an incoming DIMSE message (C-STORE-RQ)
Processes the C-STORE request:
Validates the message is a C-STORE-RQ
Extracts SOP Class/Instance UIDs
Calls pre-store handler (if registered)
Calls storage handler
Sends C-STORE-RSP with appropriate status
Parameters
assoc The association on which the message was received
context_id The presentation context ID for the message
request The incoming C-STORE-RQ message
Returns
Success or error
Implements kcenon::pacs::services::scp_service.
Definition at line 65 of file storage_scp.cpp.
{
    using namespace network::dimse;
    // Verify the message is a C-STORE request
    if (request.command() != command_field::c_store_rq) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::store_unexpected_command,
            "Expected C-STORE-RQ but received " +
            std::string(to_string(request.command())));
    }
    // Extract SOP Class and Instance UIDs from the command set
    const auto sop_class_uid = request.affected_sop_class_uid();
    const auto sop_instance_uid = request.affected_sop_instance_uid();
    // Verify the request has a dataset
    if (!request.has_dataset()) {
        auto response = make_c_store_rsp(
            request.message_id(),
            sop_class_uid,
            sop_instance_uid,
            static_cast<status_code>(storage_status::cannot_understand)
        );
        return assoc.send_dimse(context_id, response);
    }
    // Get dataset reference (already validated above)
    const auto& dataset = request.dataset().value().get();
    // Pre-store validation
    if (pre_store_handler_ && !pre_store_handler_(dataset)) {
        auto response = make_c_store_rsp(
            request.message_id(),
            sop_class_uid,
            sop_instance_uid,
            static_cast<status_code>(storage_status::cannot_understand)
        );
        return assoc.send_dimse(context_id, response);
    }
    // Determine storage status
    storage_status status = storage_status::success;
    if (handler_) {
        // Call the registered storage handler
        status = handler_(
            dataset,
            std::string(assoc.calling_ae()),
            sop_class_uid,
            sop_instance_uid
        );
    }
    // Update statistics and notify on success or warning
    if (!is_failure(status)) {
        images_received_.fetch_add(1, std::memory_order_relaxed);
        // Estimate dataset size - use element count as approximation
        // In production, this would use actual serialized size
        bytes_received_.fetch_add(
            dataset.size() * sizeof(uint32_t),
            std::memory_order_relaxed
        );
        // Call post-store handler for cache invalidation and notifications
        auto patient_id = dataset.get_string(core::tags::patient_id);
        auto study_uid = dataset.get_string(core::tags::study_instance_uid);
        auto series_uid = dataset.get_string(core::tags::series_instance_uid);
        if (post_store_handler_) {
            post_store_handler_(
                dataset,
                patient_id,
                study_uid,
                series_uid,
                sop_instance_uid
            );
        }
        // Publish image received event
        kcenon::common::get_event_bus().publish(
            kcenon::pacs::events::image_received_event{
                patient_id,
                study_uid,
                series_uid,
                sop_instance_uid,
                sop_class_uid,
                std::string(assoc.calling_ae()),
                bytes_received_.load(std::memory_order_relaxed)
            }
        );
    } else {
        // Storage failed - publish failure event
        auto patient_id = dataset.get_string(core::tags::patient_id);
        kcenon::common::get_event_bus().publish(
            kcenon::pacs::events::storage_failed_event{
                patient_id,
                sop_instance_uid,
                std::string(assoc.calling_ae()),
                static_cast<int>(status),
                "C-STORE operation failed"
            }
        );
    }
    // Emit ATNA audit event
    if (auditor_) {
        auto audit_study_uid = dataset.get_string(core::tags::study_instance_uid);
        auto audit_patient_id = dataset.get_string(core::tags::patient_id);
        auditor_->audit_instance_stored(
            std::string(assoc.calling_ae()),
            std::string(assoc.called_ae()),
            audit_study_uid,
            audit_patient_id,
            !is_failure(status));
    }
    // Build and send the response
    auto response = make_c_store_rsp(
        request.message_id(),
        sop_class_uid,
        sop_instance_uid,
        static_cast<status_code>(status)
    );
    return assoc.send_dimse(context_id, response);
}
References kcenon::pacs::network::dimse::dimse_message::affected_sop_class_uid(), kcenon::pacs::network::dimse::dimse_message::affected_sop_instance_uid(), kcenon::pacs::security::atna_service_auditor::audit_instance_stored(), auditor_, bytes_received_, kcenon::pacs::network::association::called_ae(), kcenon::pacs::network::association::calling_ae(), kcenon::pacs::services::cannot_understand, kcenon::pacs::network::dimse::dimse_message::command(), kcenon::pacs::network::dimse::dimse_message::dataset(), handler_, kcenon::pacs::network::dimse::dimse_message::has_dataset(), images_received_, kcenon::pacs::services::is_failure(), kcenon::pacs::network::dimse::dimse_message::message_id(), kcenon::pacs::pacs_void_error(), kcenon::pacs::core::tags::patient_id, post_store_handler_, pre_store_handler_, kcenon::pacs::network::association::send_dimse(), kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::error_codes::store_unexpected_command, kcenon::pacs::core::tags::study_instance_uid, kcenon::pacs::services::success, and kcenon::pacs::services::to_string().
images_received()
size_t kcenon::pacs::services::storage_scp::images_received () const nodiscard noexcept
Get the number of images received since construction.
Returns
Count of successfully received images
Definition at line 205 of file storage_scp.cpp.
{
    return images_received_.load(std::memory_order_relaxed);
}
References images_received_.
reset_statistics()
void kcenon::pacs::services::storage_scp::reset_statistics () noexcept
Reset statistics counters to zero.
Definition at line 213 of file storage_scp.cpp.
{
    images_received_.store(0, std::memory_order_relaxed);
    bytes_received_.store(0, std::memory_order_relaxed);
}
References bytes_received_, and images_received_.
service_name()
std::string_view kcenon::pacs::services::storage_scp::service_name () const nodiscard override virtual noexcept
Get the service name.
Returns
"Storage SCP"
Implements kcenon::pacs::services::scp_service.
Definition at line 197 of file storage_scp.cpp.
{
    return "Storage SCP";
}
set_audit_handler()
void kcenon::pacs::services::storage_scp::set_audit_handler (std::shared_ptr< kcenon::pacs::security::atna_service_auditor > auditor)
Set the ATNA audit handler for C-STORE operations.
When set, audit events are emitted for each C-STORE operation (both success and failure).
Parameters
auditor Shared pointer to an ATNA service auditor
Definition at line 49 of file storage_scp.cpp.
{
    auditor_ = std::move(auditor);
}
References auditor_.
set_handler()
void kcenon::pacs::services::storage_scp::set_handler (storage_handler handler)
Set the storage handler callback.
This handler is called for each received C-STORE request after pre-validation passes. It should perform the actual storage operation.
Parameters
handler The storage callback function
Definition at line 37 of file storage_scp.cpp.
{
    handler_ = std::move(handler);
}
References handler_.
set_post_store_handler()
void kcenon::pacs::services::storage_scp::set_post_store_handler (post_store_handler handler)
Definition at line 45 of file storage_scp.cpp.
{
    post_store_handler_ = std::move(handler);
}
References post_store_handler_.
Referenced by kcenon::pacs::client::routing_manager::attach_to_storage_scp(), and kcenon::pacs::client::routing_manager::detach_from_storage_scp().
set_pre_store_handler()
void kcenon::pacs::services::storage_scp::set_pre_store_handler (pre_store_handler handler)
Set the pre-store validation handler.
This handler is called before the main storage handler to validate incoming datasets. Return false to reject the storage request.
Parameters
handler The pre-validation callback function
Definition at line 41 of file storage_scp.cpp.
{
    pre_store_handler_ = std::move(handler);
}
References pre_store_handler_.
supported_sop_classes()
std::vector< std::string > kcenon::pacs::services::storage_scp::supported_sop_classes () const nodiscard override virtual
Get supported SOP Class UIDs.
Returns the list of Storage SOP Classes this service accepts. If no specific classes are configured, returns all standard storage classes.
Returns
Vector of accepted SOP Class UIDs
Implements kcenon::pacs::services::scp_service.
Definition at line 58 of file storage_scp.cpp.
{
    if (!config_.accepted_sop_classes.empty()) {
        return config_.accepted_sop_classes;
    }
    return get_standard_storage_sop_classes();
}
References kcenon::pacs::services::storage_scp_config::accepted_sop_classes, config_, and kcenon::pacs::services::get_standard_storage_sop_classes().
Member Data Documentation
auditor_
std::shared_ptr<kcenon::pacs::security::atna_service_auditor> kcenon::pacs::services::storage_scp::auditor_ private
ATNA audit handler.
Definition at line 328 of file storage_scp.h.
Referenced by handle_message(), and set_audit_handler().
bytes_received_
std::atomic<size_t> kcenon::pacs::services::storage_scp::bytes_received_ {0} private
Statistics: total bytes received.
Definition at line 334 of file storage_scp.h.
{0};
Referenced by bytes_received(), handle_message(), and reset_statistics().
config_
storage_scp_config kcenon::pacs::services::storage_scp::config_ private
Configuration.
Definition at line 316 of file storage_scp.h.
Referenced by supported_sop_classes().
handler_
storage_handler kcenon::pacs::services::storage_scp::handler_ private
Main storage handler.
Definition at line 319 of file storage_scp.h.
Referenced by handle_message(), and set_handler().
images_received_
std::atomic<size_t> kcenon::pacs::services::storage_scp::images_received_ {0} private
Statistics: number of images received.
Definition at line 331 of file storage_scp.h.
{0};
Referenced by handle_message(), images_received(), and reset_statistics().
post_store_handler_
post_store_handler kcenon::pacs::services::storage_scp::post_store_handler_ private
Post-store notification handler.
Definition at line 325 of file storage_scp.h.
Referenced by handle_message(), and set_post_store_handler().
pre_store_handler_
pre_store_handler kcenon::pacs::services::storage_scp::pre_store_handler_ private
Pre-store validation handler.
Definition at line 322 of file storage_scp.h.
Referenced by handle_message(), and set_pre_store_handler().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/storage_scp.h
src/services/storage_scp.cpp