PACS System: kcenon::pacs::services::ups_query_scp Class Reference
kcenon::pacs::services::ups_query_scp Class Reference final
UPS Query SCP service for handling workitem C-FIND requests.
#include <ups_query_scp.h>
Public Member Functions
ups_query_scp (std::shared_ptr< di::ILogger > logger=nullptr)
Construct UPS Query SCP with optional logger.
~ups_query_scp () override=default
void set_handler (ups_query_handler handler)
void set_max_results (size_t max) noexcept
size_t max_results () const noexcept
void set_cancel_check (ups_query_cancel_check check)
std::vector< std::string > supported_sop_classes () const override
Get the list of SOP Class UIDs supported by this service.
network::Result< std::monostate > handle_message (network::association &assoc, uint8_t context_id, const network::dimse::dimse_message &request) override
Handle an incoming DIMSE message.
std::string_view service_name () const noexcept override
Get the service name for logging/debugging.
size_t queries_processed () const noexcept
size_t items_returned () const noexcept
void reset_statistics () noexcept
Public Member Functions inherited from kcenon::pacs::services::scp_service
scp_service (std::shared_ptr< di::ILogger > logger=nullptr)
Construct SCP service with optional logger.
virtual ~scp_service ()=default
scp_service (const scp_service &)=delete
scp_service & operator= (const scp_service &)=delete
scp_service (scp_service &&)=default
scp_service & operator= (scp_service &&)=default
void set_logger (std::shared_ptr< di::ILogger > logger)
Set the logger instance.
const std::shared_ptr< di::ILogger > & logger () const noexcept
Get the current logger instance.
bool supports_sop_class (std::string_view sop_class_uid) const
Check if this service supports a specific SOP Class.
Private Member Functions
network::Result< std::monostate > send_pending_response (network::association &assoc, uint8_t context_id, uint16_t message_id, const core::dicom_dataset &result)
network::Result< std::monostate > send_final_response (network::association &assoc, uint8_t context_id, uint16_t message_id, network::dimse::status_code status)
Private Attributes
ups_query_handler handler_
ups_query_cancel_check cancel_check_
size_t max_results_ {0}
std::atomic< size_t > queries_processed_ {0}
std::atomic< size_t > items_returned_ {0}
Additional Inherited Members
Protected Attributes inherited from kcenon::pacs::services::scp_service
std::shared_ptr< di::ILogger > logger_
Logger instance for service logging.
Detailed Description
UPS Query SCP service for handling workitem C-FIND requests.
The UPS Query SCP (Service Class Provider) responds to C-FIND requests to search for UPS workitems. It follows the same pending/final response pattern as the Modality Worklist SCP.
UPS C-FIND Message Flow
SCU (Scheduler/Performer)              UPS Query SCP
 |                                     |
 |  C-FIND-RQ                          |
 |  +-------------------------------+  |
 |  | SOPClass: ...34.6.4           |  |
 |  | ProcedureStepState: SCHEDULED |  |
 |  | Priority: HIGH               |  |
 |  +-------------------------------+  |
 |------------------------------------>|
 |                                     |
 |  C-FIND-RSP (Pending, 0xFF00)       |
 |  +-------------------------------+  |
 |  | WorkitemUID: 1.2.3.4...       |  |
 |  | Label: "AI Analysis"         |  |
 |  | State: SCHEDULED             |  |
 |  +-------------------------------+  |
 |<------------------------------------|
 |                                     |
 |  ... (repeat for each match)        |
 |                                     |
 |  C-FIND-RSP (Success, 0x0000)       |
 |  (No dataset)                       |
 |<------------------------------------|
Definition at line 106 of file ups_query_scp.h.
Constructor & Destructor Documentation
ups_query_scp()
kcenon::pacs::services::ups_query_scp::ups_query_scp (std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct UPS Query SCP with optional logger.
Parameters
logger Logger instance (nullptr uses null_logger)
Definition at line 19 of file ups_query_scp.cpp.
    : scp_service(std::move(logger)) {}
~ups_query_scp()
kcenon::pacs::services::ups_query_scp::~ups_query_scp () override default
Member Function Documentation
handle_message()
network::Result< std::monostate > kcenon::pacs::services::ups_query_scp::handle_message (network::association & assoc, uint8_t context_id, const network::dimse::dimse_message & request) nodiscard override virtual
Handle an incoming DIMSE message.
Processes the request and sends appropriate response(s) via the association.
Parameters
assoc The association on which the message was received
context_id The presentation context ID for the message
request The incoming DIMSE request message
Returns
Success or error result
Implements kcenon::pacs::services::scp_service.
Definition at line 52 of file ups_query_scp.cpp.
{
    using namespace network::dimse;
    // Verify the message is a C-FIND request
    if (request.command() != command_field::c_find_rq) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::ups_unexpected_command,
            "Expected C-FIND-RQ but received " +
            std::string(to_string(request.command())));
    }
    // Verify we have a handler
    if (!handler_) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::ups_handler_not_set,
            "No UPS query handler configured");
    }
    // Get the SOP Class UID from the request
    auto sop_class_uid = request.affected_sop_class_uid();
    // Verify the SOP Class is UPS Query FIND
    if (sop_class_uid != ups_query_find_sop_class_uid) {
        return send_final_response(
            assoc, context_id, request.message_id(),
            status_refused_sop_class_not_supported);
    }
    // Verify we have a dataset (query keys)
    if (!request.has_dataset()) {
        return send_final_response(
            assoc, context_id, request.message_id(),
            status_error_cannot_understand);
    }
    // Get the query keys from the request
    const auto& query_keys = request.dataset().value().get();
    // Get calling AE for logging and access control
    std::string calling_ae{assoc.calling_ae()};
    logger_->debug("Processing UPS C-FIND query from " + calling_ae);
    // Call the handler to get matching workitems
    auto results = handler_(query_keys, calling_ae);
    // Apply max results limit if configured
    if (max_results_ > 0 && results.size() > max_results_) {
        results.resize(max_results_);
    }
    // Send pending responses for each result
    for (const auto& result : results) {
        // Check for cancel request
        if (cancel_check_ && cancel_check_()) {
            ++queries_processed_;
            return send_final_response(
                assoc, context_id, request.message_id(),
                status_cancel);
        }
        // Send pending response with matching workitem
        auto send_result = send_pending_response(
            assoc, context_id, request.message_id(),
            result);
        if (send_result.is_err()) {
            return send_result;
        }
        ++items_returned_;
    }
    // Increment statistics
    ++queries_processed_;
    logger_->info("UPS C-FIND completed: " + std::to_string(results.size()) +
                  " workitems matched");
    // Send final success response (no dataset)
    return send_final_response(
        assoc, context_id, request.message_id(),
        status_success);
}
References kcenon::pacs::network::dimse::dimse_message::affected_sop_class_uid(), kcenon::pacs::network::association::calling_ae(), cancel_check_, kcenon::pacs::network::dimse::dimse_message::command(), kcenon::pacs::network::dimse::dimse_message::dataset(), handler_, kcenon::pacs::network::dimse::dimse_message::has_dataset(), items_returned_, kcenon::pacs::services::scp_service::logger_, max_results_, kcenon::pacs::network::dimse::dimse_message::message_id(), kcenon::pacs::pacs_void_error(), queries_processed_, send_final_response(), send_pending_response(), kcenon::pacs::services::to_string(), kcenon::pacs::error_codes::ups_handler_not_set, kcenon::pacs::services::ups_query_find_sop_class_uid, and kcenon::pacs::error_codes::ups_unexpected_command.
items_returned()
size_t kcenon::pacs::services::ups_query_scp::items_returned () const nodiscard noexcept
Definition at line 154 of file ups_query_scp.cpp.
{
    return items_returned_.load();
}
References items_returned_.
max_results()
size_t kcenon::pacs::services::ups_query_scp::max_results () const nodiscard noexcept
Definition at line 34 of file ups_query_scp.cpp.
{
    return max_results_;
}
References max_results_.
queries_processed()
size_t kcenon::pacs::services::ups_query_scp::queries_processed () const nodiscard noexcept
Definition at line 150 of file ups_query_scp.cpp.
{
    return queries_processed_.load();
}
References queries_processed_.
reset_statistics()
void kcenon::pacs::services::ups_query_scp::reset_statistics () noexcept
Definition at line 158 of file ups_query_scp.cpp.
{
    queries_processed_ = 0;
    items_returned_ = 0;
}
References items_returned_, and queries_processed_.
send_final_response()
network::Result< std::monostate > kcenon::pacs::services::ups_query_scp::send_final_response (network::association & assoc, uint8_t context_id, uint16_t message_id, network::dimse::status_code status) nodiscard private
Definition at line 186 of file ups_query_scp.cpp.
{
    using namespace network::dimse;
    auto response = make_c_find_rsp(
        message_id,
        ups_query_find_sop_class_uid,
        status
    );
    return assoc.send_dimse(context_id, response);
}
References kcenon::pacs::network::association::send_dimse(), and kcenon::pacs::services::ups_query_find_sop_class_uid.
Referenced by handle_message().
send_pending_response()
network::Result< std::monostate > kcenon::pacs::services::ups_query_scp::send_pending_response (network::association & assoc, uint8_t context_id, uint16_t message_id, const core::dicom_dataset & result) nodiscard private
Definition at line 167 of file ups_query_scp.cpp.
{
    using namespace network::dimse;
    auto response = make_c_find_rsp(
        message_id,
        ups_query_find_sop_class_uid,
        status_pending
    );
    response.set_dataset(result);
    return assoc.send_dimse(context_id, response);
}
References kcenon::pacs::network::association::send_dimse(), and kcenon::pacs::services::ups_query_find_sop_class_uid.
Referenced by handle_message().
service_name()
std::string_view kcenon::pacs::services::ups_query_scp::service_name () const nodiscard override virtual noexcept
Get the service name for logging/debugging.
Returns
Human-readable service name
Implements kcenon::pacs::services::scp_service.
Definition at line 142 of file ups_query_scp.cpp.
{
    return "UPS Query SCP";
}
set_cancel_check()
void kcenon::pacs::services::ups_query_scp::set_cancel_check (ups_query_cancel_check check)
Definition at line 38 of file ups_query_scp.cpp.
{
    cancel_check_ = std::move(check);
}
References cancel_check_.
set_handler()
void kcenon::pacs::services::ups_query_scp::set_handler (ups_query_handler handler)
Definition at line 26 of file ups_query_scp.cpp.
{
    handler_ = std::move(handler);
}
References handler_.
set_max_results()
void kcenon::pacs::services::ups_query_scp::set_max_results (size_t max) noexcept
Definition at line 30 of file ups_query_scp.cpp.
{
    max_results_ = max;
}
supported_sop_classes()
std::vector< std::string > kcenon::pacs::services::ups_query_scp::supported_sop_classes () const nodiscard override virtual
Get the list of SOP Class UIDs supported by this service.
Returns
Vector of SOP Class UIDs that this service can handle
Implements kcenon::pacs::services::scp_service.
Definition at line 46 of file ups_query_scp.cpp.
{
    return {
        std::string(ups_query_find_sop_class_uid)
    };
}
References kcenon::pacs::services::ups_query_find_sop_class_uid.
Member Data Documentation
cancel_check_
ups_query_cancel_check kcenon::pacs::services::ups_query_scp::cancel_check_ private
Definition at line 174 of file ups_query_scp.h.
Referenced by handle_message(), and set_cancel_check().
handler_
ups_query_handler kcenon::pacs::services::ups_query_scp::handler_ private
Definition at line 173 of file ups_query_scp.h.
Referenced by handle_message(), and set_handler().
items_returned_
std::atomic<size_t> kcenon::pacs::services::ups_query_scp::items_returned_ {0} private
Definition at line 177 of file ups_query_scp.h.
{0};
Referenced by handle_message(), items_returned(), and reset_statistics().
max_results_
size_t kcenon::pacs::services::ups_query_scp::max_results_ {0} private
Definition at line 175 of file ups_query_scp.h.
{0};  // 0 = unlimited
Referenced by handle_message(), and max_results().
queries_processed_
std::atomic<size_t> kcenon::pacs::services::ups_query_scp::queries_processed_ {0} private
Definition at line 176 of file ups_query_scp.h.
{0};
Referenced by handle_message(), queries_processed(), and reset_statistics().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/ups/ups_query_scp.h
src/services/ups/ups_query_scp.cpp