PACS System: kcenon::pacs::services::worklist_scp Class Reference
kcenon::pacs::services::worklist_scp Class Reference final
#include <worklist_scp.h>
Public Member Functions
worklist_scp (std::shared_ptr< di::ILogger > logger=nullptr)
Construct Worklist SCP with optional logger.
~worklist_scp () override=default
void set_handler (worklist_handler handler)
Set the worklist handler function.
void set_max_results (size_t max) noexcept
Set maximum number of results to return.
size_t max_results () const noexcept
Get maximum number of results.
void set_cancel_check (worklist_cancel_check check)
Set the cancel check function.
std::vector< std::string > supported_sop_classes () const override
Get supported SOP Class UIDs.
network::Result< std::monostate > handle_message (network::association &assoc, uint8_t context_id, const network::dimse::dimse_message &request) override
Handle an incoming DIMSE message (MWL C-FIND-RQ)
std::string_view service_name () const noexcept override
Get the service name.
size_t queries_processed () const noexcept
Get total number of worklist queries processed.
size_t items_returned () const noexcept
Get total number of worklist items returned.
void reset_statistics () noexcept
Reset statistics counters.
Public Member Functions inherited from kcenon::pacs::services::scp_service
scp_service (std::shared_ptr< di::ILogger > logger=nullptr)
Construct SCP service with optional logger.
virtual ~scp_service ()=default
scp_service (const scp_service &)=delete
scp_service & operator= (const scp_service &)=delete
scp_service (scp_service &&)=default
scp_service & operator= (scp_service &&)=default
void set_logger (std::shared_ptr< di::ILogger > logger)
Set the logger instance.
const std::shared_ptr< di::ILogger > & logger () const noexcept
Get the current logger instance.
bool supports_sop_class (std::string_view sop_class_uid) const
Check if this service supports a specific SOP Class.
Private Member Functions
network::Result< std::monostate > send_pending_response (network::association &assoc, uint8_t context_id, uint16_t message_id, const core::dicom_dataset &result)
Send a pending C-FIND response with matching worklist item.
network::Result< std::monostate > send_final_response (network::association &assoc, uint8_t context_id, uint16_t message_id, network::dimse::status_code status)
Send the final C-FIND response (success or cancel)
Private Attributes
worklist_handler handler_
worklist_cancel_check cancel_check_
size_t max_results_ {0}
std::atomic< size_t > queries_processed_ {0}
std::atomic< size_t > items_returned_ {0}
Additional Inherited Members
Protected Attributes inherited from kcenon::pacs::services::scp_service
std::shared_ptr< di::ILogger > logger_
Logger instance for service logging.
Detailed Description
Definition at line 192 of file worklist_scp.h.
Constructor & Destructor Documentation
worklist_scp()
kcenon::pacs::services::worklist_scp::worklist_scp (std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct Worklist SCP with optional logger.
Parameters
logger Logger instance for service logging (nullptr uses null_logger)
Definition at line 23 of file worklist_scp.cpp.
    : scp_service(std::move(logger)) {}
~worklist_scp()
kcenon::pacs::services::worklist_scp::~worklist_scp () override default
Member Function Documentation
handle_message()
network::Result< std::monostate > kcenon::pacs::services::worklist_scp::handle_message (network::association & assoc, uint8_t context_id, const network::dimse::dimse_message & request) nodiscard override virtual
Handle an incoming DIMSE message (MWL C-FIND-RQ)
Processes the Modality Worklist C-FIND request, queries the worklist repository through the handler, and sends pending responses for each match followed by a final success.
Parameters
assoc The association on which the message was received
context_id The presentation context ID for the message
request The incoming C-FIND-RQ message
Returns
Success or error if the message is not a valid MWL C-FIND-RQ
Implements kcenon::pacs::services::scp_service.
Definition at line 56 of file worklist_scp.cpp.
{
    using namespace network::dimse;
    // Verify the message is a C-FIND request
    if (request.command() != command_field::c_find_rq) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::worklist_unexpected_command,
            "Expected C-FIND-RQ but received " +
            std::string(to_string(request.command())));
    }
    // Verify we have a handler
    if (!handler_) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::worklist_handler_not_set,
            "No worklist handler configured");
    }
    // Get the SOP Class UID from the request
    auto sop_class_uid = request.affected_sop_class_uid();
    // Verify the SOP Class is Modality Worklist
    if (sop_class_uid != worklist_find_sop_class_uid) {
        return send_final_response(
            assoc, context_id, request.message_id(),
            status_refused_sop_class_not_supported);
    }
    // Verify we have a dataset (query keys)
    if (!request.has_dataset()) {
        return send_final_response(
            assoc, context_id, request.message_id(),
            status_error_cannot_understand);
    }
    // Get the query keys from the request
    const auto& query_keys = request.dataset().value().get();
    // Get calling AE for logging and access control
    std::string calling_ae{assoc.calling_ae()};
    // Call the handler to get matching worklist items
    auto results = handler_(query_keys, calling_ae);
    // Apply max results limit if configured
    if (max_results_ > 0 && results.size() > max_results_) {
        results.resize(max_results_);
    }
    // Send pending responses for each result
    for (const auto& result : results) {
        // Check for cancel request
        if (cancel_check_ && cancel_check_()) {
            // Increment statistics
            ++queries_processed_;
            // Send cancel response
            return send_final_response(
                assoc, context_id, request.message_id(),
                status_cancel);
        }
        // Send pending response with matching worklist item
        auto send_result = send_pending_response(
            assoc, context_id, request.message_id(),
            result);
        if (send_result.is_err()) {
            return send_result;
        }
        // Track items returned
        ++items_returned_;
    }
    // Increment statistics
    ++queries_processed_;
    // Send final success response (no dataset)
    return send_final_response(
        assoc, context_id, request.message_id(),
        status_success);
}
References kcenon::pacs::network::dimse::dimse_message::affected_sop_class_uid(), kcenon::pacs::network::association::calling_ae(), cancel_check_, kcenon::pacs::network::dimse::dimse_message::command(), kcenon::pacs::network::dimse::dimse_message::dataset(), handler_, kcenon::pacs::network::dimse::dimse_message::has_dataset(), items_returned_, max_results_, kcenon::pacs::network::dimse::dimse_message::message_id(), kcenon::pacs::pacs_void_error(), queries_processed_, send_final_response(), send_pending_response(), kcenon::pacs::services::to_string(), kcenon::pacs::services::worklist_find_sop_class_uid, kcenon::pacs::error_codes::worklist_handler_not_set, and kcenon::pacs::error_codes::worklist_unexpected_command.
items_returned()
size_t kcenon::pacs::services::worklist_scp::items_returned () const nodiscard noexcept
Get total number of worklist items returned.
Returns
Total count of scheduled procedure items returned
Definition at line 156 of file worklist_scp.cpp.
{
    return items_returned_.load();
}
References items_returned_.
max_results()
size_t kcenon::pacs::services::worklist_scp::max_results () const nodiscard noexcept
Get maximum number of results.
Returns
Maximum results (0 = unlimited)
Definition at line 38 of file worklist_scp.cpp.
{
    return max_results_;
}
References max_results_.
queries_processed()
size_t kcenon::pacs::services::worklist_scp::queries_processed () const nodiscard noexcept
Get total number of worklist queries processed.
Returns
Number of MWL C-FIND requests handled
Definition at line 152 of file worklist_scp.cpp.
{
    return queries_processed_.load();
}
References queries_processed_.
reset_statistics()
void kcenon::pacs::services::worklist_scp::reset_statistics () noexcept
Reset statistics counters.
Definition at line 160 of file worklist_scp.cpp.
{
    queries_processed_ = 0;
    items_returned_ = 0;
}
References items_returned_, and queries_processed_.
send_final_response()
network::Result< std::monostate > kcenon::pacs::services::worklist_scp::send_final_response (network::association & assoc, uint8_t context_id, uint16_t message_id, network::dimse::status_code status) nodiscard private
Send the final C-FIND response (success or cancel)
Parameters
assoc The association
context_id The presentation context ID
message_id The original request message ID
status The final status code
Returns
Success or error
Definition at line 191 of file worklist_scp.cpp.
{
    using namespace network::dimse;
    // Create C-FIND response with final status (no dataset)
    auto response = make_c_find_rsp(
        message_id,
        worklist_find_sop_class_uid,
        status
    );
    // Send the response
    return assoc.send_dimse(context_id, response);
}
References kcenon::pacs::network::association::send_dimse(), and kcenon::pacs::services::worklist_find_sop_class_uid.
Referenced by handle_message().
send_pending_response()
network::Result< std::monostate > kcenon::pacs::services::worklist_scp::send_pending_response (network::association & assoc, uint8_t context_id, uint16_t message_id, const core::dicom_dataset & result) nodiscard private
Send a pending C-FIND response with matching worklist item.
Parameters
assoc The association
context_id The presentation context ID
message_id The original request message ID
result The matching worklist item dataset
Returns
Success or error
Definition at line 169 of file worklist_scp.cpp.
{
    using namespace network::dimse;
    // Create C-FIND response with pending status
    auto response = make_c_find_rsp(
        message_id,
        worklist_find_sop_class_uid,
        status_pending
    );
    // Attach the matching worklist item dataset
    response.set_dataset(result);
    // Send the response
    return assoc.send_dimse(context_id, response);
}
References kcenon::pacs::network::association::send_dimse(), and kcenon::pacs::services::worklist_find_sop_class_uid.
Referenced by handle_message().
service_name()
std::string_view kcenon::pacs::services::worklist_scp::service_name () const nodiscard override virtual noexcept
Get the service name.
Returns
"Worklist SCP"
Implements kcenon::pacs::services::scp_service.
Definition at line 144 of file worklist_scp.cpp.
{
    return "Worklist SCP";
}
set_cancel_check()
void kcenon::pacs::services::worklist_scp::set_cancel_check (worklist_cancel_check check)
Set the cancel check function.
The cancel check is called periodically during query processing to check if a C-CANCEL has been received.
Parameters
check The cancel check function
Definition at line 42 of file worklist_scp.cpp.
{
    cancel_check_ = std::move(check);
}
References cancel_check_.
set_handler()
void kcenon::pacs::services::worklist_scp::set_handler (worklist_handler handler)
Set the worklist handler function.
The handler is called for each MWL C-FIND request to retrieve matching scheduled procedure items from the RIS/HIS database.
Parameters
handler The worklist handler function
Definition at line 30 of file worklist_scp.cpp.
{
    handler_ = std::move(handler);
}
References handler_.
set_max_results()
void kcenon::pacs::services::worklist_scp::set_max_results (size_t max) noexcept
Set maximum number of results to return.
Parameters
max Maximum results (0 = unlimited)
Definition at line 34 of file worklist_scp.cpp.
{
    max_results_ = max;
}
supported_sop_classes()
std::vector< std::string > kcenon::pacs::services::worklist_scp::supported_sop_classes () const nodiscard override virtual
Get supported SOP Class UIDs.
Returns
Vector containing Modality Worklist Find SOP Class UID
Implements kcenon::pacs::services::scp_service.
Definition at line 50 of file worklist_scp.cpp.
{
    return {
        std::string(worklist_find_sop_class_uid)
    };
}
References kcenon::pacs::services::worklist_find_sop_class_uid.
Member Data Documentation
cancel_check_
worklist_cancel_check kcenon::pacs::services::worklist_scp::cancel_check_ private
Definition at line 343 of file worklist_scp.h.
Referenced by handle_message(), and set_cancel_check().
handler_
worklist_handler kcenon::pacs::services::worklist_scp::handler_ private
Definition at line 342 of file worklist_scp.h.
Referenced by handle_message(), and set_handler().
items_returned_
std::atomic<size_t> kcenon::pacs::services::worklist_scp::items_returned_ {0} private
Definition at line 346 of file worklist_scp.h.
{0};
Referenced by handle_message(), items_returned(), and reset_statistics().
max_results_
size_t kcenon::pacs::services::worklist_scp::max_results_ {0} private
Definition at line 344 of file worklist_scp.h.
{0};  // 0 = unlimited
Referenced by handle_message(), and max_results().
queries_processed_
std::atomic<size_t> kcenon::pacs::services::worklist_scp::queries_processed_ {0} private
Definition at line 345 of file worklist_scp.h.
{0};
Referenced by handle_message(), queries_processed(), and reset_statistics().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/worklist_scp.h
src/services/worklist_scp.cpp