PACS System: kcenon::pacs::core::pool_manager Class Reference
kcenon::pacs::core::pool_manager Class Reference
#include <pool_manager.h>
Public Member Functions
auto acquire_element (dicom_tag tag, encoding::vr_type vr) -> tracked_pool< dicom_element >::unique_ptr_type
Acquire a dicom_element from the pool.
auto acquire_dataset () -> tracked_pool< dicom_dataset >::unique_ptr_type
Acquire a dicom_dataset from the pool.
auto element_statistics () const noexcept -> const pool_statistics &
Get element pool statistics.
auto dataset_statistics () const noexcept -> const pool_statistics &
Get dataset pool statistics.
void reserve_elements (std::size_t count)
Reserve capacity in element pool.
void reserve_datasets (std::size_t count)
Reserve capacity in dataset pool.
void clear_all ()
Clear all pools.
void reset_statistics ()
Reset all statistics.
pool_manager (const pool_manager &)=delete
pool_manager (pool_manager &&)=delete
auto operator= (const pool_manager &) -> pool_manager &=delete
auto operator= (pool_manager &&) -> pool_manager &=delete
Static Public Member Functions
static auto get () noexcept -> pool_manager &
Get the thread-local pool manager instance.
Static Public Attributes
static constexpr std::size_t DEFAULT_ELEMENT_POOL_SIZE = 1024
Default pool sizes.
static constexpr std::size_t DEFAULT_DATASET_POOL_SIZE = 128
Private Member Functions
pool_manager ()
~pool_manager ()=default
Private Attributes
tracked_pool< dicom_element > element_pool_
tracked_pool< dicom_dataset > dataset_pool_
Detailed Description
Definition at line 156 of file pool_manager.h.
Constructor & Destructor Documentation
pool_manager() [1/3]
kcenon::pacs::core::pool_manager::pool_manager (const pool_manager &) delete
pool_manager() [2/3]
kcenon::pacs::core::pool_manager::pool_manager (pool_manager &&) delete
pool_manager() [3/3]
kcenon::pacs::core::pool_manager::pool_manager () private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 18 of file pool_manager.cpp.
    : element_pool_(DEFAULT_ELEMENT_POOL_SIZE)
    , dataset_pool_(DEFAULT_DATASET_POOL_SIZE) {}
~pool_manager()
kcenon::pacs::core::pool_manager::~pool_manager () private default
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Member Function Documentation
acquire_dataset()
auto kcenon::pacs::core::pool_manager::acquire_dataset () -> tracked_pool<dicom_dataset>::unique_ptr_type
Acquire a dicom_dataset from the pool.
Returns
A pooled dicom_dataset
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 32 of file pool_manager.cpp.
{
    return dataset_pool_.acquire();
}
acquire_element()
auto kcenon::pacs::core::pool_manager::acquire_element (dicom_tag tag, encoding::vr_type vr) -> tracked_pool<dicom_element>::unique_ptr_type
Acquire a dicom_element from the pool.
Parameters
tag The DICOM tag
vr The value representation
Returns
A pooled dicom_element
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 27 of file pool_manager.cpp.
{
    return element_pool_.acquire(tag, vr);
}
References vr.
clear_all()
void kcenon::pacs::core::pool_manager::clear_all ()
Clear all pools.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 53 of file pool_manager.cpp.
{
    element_pool_.clear();
    dataset_pool_.clear();
}
References dataset_pool_, and element_pool_.
dataset_statistics()
auto kcenon::pacs::core::pool_manager::dataset_statistics () const -> const pool_statistics& nodiscard noexcept
Get dataset pool statistics.
Returns
Reference to dataset pool statistics
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 41 of file pool_manager.cpp.
{
    return dataset_pool_.statistics();
}
References dataset_pool_.
element_statistics()
auto kcenon::pacs::core::pool_manager::element_statistics () const -> const pool_statistics& nodiscard noexcept
Get element pool statistics.
Returns
Reference to element pool statistics
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 37 of file pool_manager.cpp.
{
    return element_pool_.statistics();
}
References element_pool_.
get()
auto kcenon::pacs::core::pool_manager::get () -> pool_manager& static noexcept
Get the thread-local pool manager instance.
Returns
Reference to the current thread's pool manager
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 22 of file pool_manager.cpp.
{
    thread_local pool_manager instance;
    return instance;
}
Referenced by kcenon::pacs::core::make_pooled_dataset(), kcenon::pacs::core::make_pooled_element(), and kcenon::pacs::core::make_pooled_element().
operator=() [1/2]
auto kcenon::pacs::core::pool_manager::operator= (const pool_manager &) -> pool_manager &=delete delete
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
operator=() [2/2]
auto kcenon::pacs::core::pool_manager::operator= (pool_manager &&) -> pool_manager &=delete delete
reserve_datasets()
void kcenon::pacs::core::pool_manager::reserve_datasets (std::size_t count)
Reserve capacity in dataset pool.
Parameters
count Number of datasets to pre-allocate
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 49 of file pool_manager.cpp.
{
    dataset_pool_.reserve(count);
}
References dataset_pool_.
reserve_elements()
void kcenon::pacs::core::pool_manager::reserve_elements (std::size_t count)
Reserve capacity in element pool.
Parameters
count Number of elements to pre-allocate
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 45 of file pool_manager.cpp.
{
    element_pool_.reserve(count);
}
References element_pool_.
reset_statistics()
void kcenon::pacs::core::pool_manager::reset_statistics ()
Reset all statistics.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 58 of file pool_manager.cpp.
{
    const_cast<pool_statistics&>(element_pool_.statistics()).reset();
    const_cast<pool_statistics&>(dataset_pool_.statistics()).reset();
}
References dataset_pool_, element_pool_, and kcenon::pacs::core::pool_statistics::reset().
Member Data Documentation
dataset_pool_
tracked_pool<dicom_dataset> kcenon::pacs::core::pool_manager::dataset_pool_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 229 of file pool_manager.h.
Referenced by clear_all(), dataset_statistics(), reserve_datasets(), and reset_statistics().
DEFAULT_DATASET_POOL_SIZE
std::size_t kcenon::pacs::core::pool_manager::DEFAULT_DATASET_POOL_SIZE = 128 static constexpr
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 160 of file pool_manager.h.
DEFAULT_ELEMENT_POOL_SIZE
std::size_t kcenon::pacs::core::pool_manager::DEFAULT_ELEMENT_POOL_SIZE = 1024 static constexpr
Default pool sizes.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 159 of file pool_manager.h.
element_pool_
tracked_pool<dicom_element> kcenon::pacs::core::pool_manager::element_pool_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/pool_manager.h.
Definition at line 228 of file pool_manager.h.
Referenced by clear_all(), element_statistics(), reserve_elements(), and reset_statistics().
The documentation for this class was generated from the following files:
include/kcenon/pacs/core/pool_manager.h
src/core/pool_manager.cpp