PACS System: kcenon::pacs::services::n_get_scu Class Reference
kcenon::pacs::services::n_get_scu Class Reference
#include <n_get_scu.h>
Public Member Functions
n_get_scu (std::shared_ptr< di::ILogger > logger=nullptr)
Construct N-GET SCU with default configuration.
n_get_scu (const n_get_scu_config &config, std::shared_ptr< di::ILogger > logger=nullptr)
Construct N-GET SCU with custom configuration.
~n_get_scu ()=default
n_get_scu (const n_get_scu &)=delete
n_get_scu & operator= (const n_get_scu &)=delete
n_get_scu (n_get_scu &&)=delete
n_get_scu & operator= (n_get_scu &&)=delete
network::Result< n_get_result > get (network::association &assoc, std::string_view sop_class_uid, std::string_view sop_instance_uid, const std::vector< core::dicom_tag > &attribute_tags={})
Retrieve attributes from a managed SOP Instance.
size_t gets_performed () const noexcept
Get the number of N-GET operations performed.
void reset_statistics () noexcept
Reset statistics counters to zero.
Private Member Functions
uint16_t next_message_id () noexcept
Get the next message ID for DIMSE operations.
Private Attributes
std::shared_ptr< di::ILogger > logger_
n_get_scu_config config_
std::atomic< uint16_t > message_id_counter_ {1}
std::atomic< size_t > gets_performed_ {0}
Detailed Description
Definition at line 126 of file n_get_scu.h.
Constructor & Destructor Documentation
n_get_scu() [1/4]
kcenon::pacs::services::n_get_scu::n_get_scu (std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct N-GET SCU with default configuration.
Parameters
logger Logger instance (nullptr uses null_logger)
Definition at line 25 of file n_get_scu.cpp.
    : logger_(logger ? std::move(logger) : di::null_logger()) {}
n_get_scu() [2/4]
kcenon::pacs::services::n_get_scu::n_get_scu (const n_get_scu_config & config, std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct N-GET SCU with custom configuration.
Parameters
config Configuration options
logger Logger instance (nullptr uses null_logger)
Definition at line 28 of file n_get_scu.cpp.
    : logger_(logger ? std::move(logger) : di::null_logger()),
      config_(config) {}
~n_get_scu()
kcenon::pacs::services::n_get_scu::~n_get_scu () default
n_get_scu() [3/4]
kcenon::pacs::services::n_get_scu::n_get_scu (const n_get_scu &) delete
n_get_scu() [4/4]
kcenon::pacs::services::n_get_scu::n_get_scu (n_get_scu &&) delete
Member Function Documentation
get()
network::Result< n_get_result > kcenon::pacs::services::n_get_scu::get (network::association & assoc, std::string_view sop_class_uid, std::string_view sop_instance_uid, const std::vector< core::dicom_tag > & attribute_tags = {}) nodiscard
Retrieve attributes from a managed SOP Instance.
Sends an N-GET-RQ and returns the retrieved attributes.
Parameters
assoc The established association to use
sop_class_uid The SOP Class UID of the instance
sop_instance_uid The SOP Instance UID to query
attribute_tags Tags to retrieve (empty = all attributes)
Returns
Result containing n_get_result, or error
Definition at line 37 of file n_get_scu.cpp.
{
    using namespace network::dimse;
    auto start_time = std::chrono::steady_clock::now();
    // Verify association is established
    if (!assoc.is_established()) {
        return kcenon::pacs::pacs_error<n_get_result>(
            kcenon::pacs::error_codes::association_not_established,
            "Association not established");
    }
    // Validate UIDs
    if (sop_class_uid.empty()) {
        return kcenon::pacs::pacs_error<n_get_result>(
            kcenon::pacs::error_codes::n_get_missing_uid,
            "SOP Class UID is required for N-GET");
    }
    if (sop_instance_uid.empty()) {
        return kcenon::pacs::pacs_error<n_get_result>(
            kcenon::pacs::error_codes::n_get_missing_uid,
            "SOP Instance UID is required for N-GET");
    }
    // Get accepted presentation context
    auto context_id = assoc.accepted_context_id(sop_class_uid);
    if (!context_id) {
        return kcenon::pacs::pacs_error<n_get_result>(
            kcenon::pacs::error_codes::n_get_context_not_accepted,
            "No accepted presentation context for SOP Class: " +
            std::string(sop_class_uid));
    }
    // Build N-GET request using factory function
    auto request = make_n_get_rq(
        next_message_id(), sop_class_uid, sop_instance_uid, attribute_tags);
    logger_->debug("Sending N-GET request for instance: " +
                   std::string(sop_instance_uid) +
                   " (attributes: " +
                   (attribute_tags.empty() ? "all" :
                    std::to_string(attribute_tags.size())) + ")");
    // Send the request
    auto send_result = assoc.send_dimse(*context_id, request);
    if (send_result.is_err()) {
        logger_->error("Failed to send N-GET: " + send_result.error().message);
        return send_result.error();
    }
    // Receive the response
    auto recv_result = assoc.receive_dimse(config_.timeout);
    if (recv_result.is_err()) {
        logger_->error("Failed to receive N-GET response: " +
                       recv_result.error().message);
        return recv_result.error();
    }
    const auto& [recv_context_id, response] = recv_result.value();
    // Verify it's an N-GET response
    if (response.command() != command_field::n_get_rsp) {
        return kcenon::pacs::pacs_error<n_get_result>(
            kcenon::pacs::error_codes::n_get_unexpected_command,
            "Expected N-GET-RSP but received " +
            std::string(to_string(response.command())));
    }
    auto end_time = std::chrono::steady_clock::now();
    auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
        end_time - start_time);
    // Build result
    n_get_result result;
    result.status = static_cast<uint16_t>(response.status());
    result.elapsed = elapsed;
    // Extract error comment if present
    if (response.command_set().contains(tag_error_comment)) {
        result.error_comment = response.command_set().get_string(
            tag_error_comment);
    }
    // Extract dataset (returned attributes) if present
    if (response.has_dataset()) {
        auto dataset_result = response.dataset();
        if (dataset_result.is_ok()) {
            result.attributes = dataset_result.value().get();
        }
    }
    // Update statistics
    gets_performed_.fetch_add(1, std::memory_order_relaxed);
    if (result.is_success()) {
        logger_->info("N-GET successful for instance: " +
                      std::string(sop_instance_uid));
    } else {
        logger_->warn("N-GET returned status 0x" +
                      std::to_string(result.status) +
                      " for instance: " + std::string(sop_instance_uid));
    }
    return result;
}
References kcenon::pacs::network::association::accepted_context_id(), kcenon::pacs::error_codes::association_not_established, kcenon::pacs::services::n_get_result::attributes, config_, kcenon::pacs::services::n_get_result::elapsed, kcenon::pacs::services::n_get_result::error_comment, kcenon::pacs::core::dicom_dataset::get(), gets_performed_, kcenon::pacs::network::association::is_established(), kcenon::pacs::services::n_get_result::is_success(), logger_, kcenon::pacs::error_codes::n_get_context_not_accepted, kcenon::pacs::error_codes::n_get_missing_uid, kcenon::pacs::error_codes::n_get_unexpected_command, next_message_id(), kcenon::pacs::pacs_error(), kcenon::pacs::network::association::receive_dimse(), kcenon::pacs::network::association::send_dimse(), kcenon::pacs::services::n_get_result::status, kcenon::pacs::services::n_get_scu_config::timeout, and kcenon::pacs::services::to_string().
gets_performed()
size_t kcenon::pacs::services::n_get_scu::gets_performed () const nodiscard noexcept
Get the number of N-GET operations performed.
Definition at line 153 of file n_get_scu.cpp.
{
    return gets_performed_.load(std::memory_order_relaxed);
}
References gets_performed_.
next_message_id()
uint16_t kcenon::pacs::services::n_get_scu::next_message_id () nodiscard private noexcept
Get the next message ID for DIMSE operations.
Definition at line 165 of file n_get_scu.cpp.
{
    uint16_t id = message_id_counter_.fetch_add(1, std::memory_order_relaxed);
    if (id == 0) {
        id = message_id_counter_.fetch_add(1, std::memory_order_relaxed);
    }
    return id;
}
References message_id_counter_.
Referenced by get().
operator=() [1/2]
n_get_scu & kcenon::pacs::services::n_get_scu::operator= (const n_get_scu &) delete
operator=() [2/2]
n_get_scu & kcenon::pacs::services::n_get_scu::operator= (n_get_scu &&) delete
reset_statistics()
void kcenon::pacs::services::n_get_scu::reset_statistics () noexcept
Reset statistics counters to zero.
Definition at line 157 of file n_get_scu.cpp.
{
    gets_performed_.store(0, std::memory_order_relaxed);
}
References gets_performed_.
Member Data Documentation
config_
n_get_scu_config kcenon::pacs::services::n_get_scu::config_ private
Definition at line 206 of file n_get_scu.h.
Referenced by get().
gets_performed_
std::atomic<size_t> kcenon::pacs::services::n_get_scu::gets_performed_ {0} private
Definition at line 208 of file n_get_scu.h.
{0};
Referenced by get(), gets_performed(), and reset_statistics().
logger_
std::shared_ptr<di::ILogger> kcenon::pacs::services::n_get_scu::logger_ private
Definition at line 205 of file n_get_scu.h.
Referenced by get().
message_id_counter_
std::atomic<uint16_t> kcenon::pacs::services::n_get_scu::message_id_counter_ {1} private
Definition at line 207 of file n_get_scu.h.
{1};
Referenced by next_message_id().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/n_get_scu.h
src/services/n_get_scu.cpp