PACS System: kcenon::pacs::services::validation::parametric_map_iod_validator Class Reference
kcenon::pacs::services::validation::parametric_map_iod_validator Class Reference
#include <parametric_map_iod_validator.h>
Public Member Functions
parametric_map_iod_validator ()=default
Construct validator with default options.
parametric_map_iod_validator (const pmap_validation_options &options)
Construct validator with custom options.
validation_result validate (const core::dicom_dataset &dataset) const
Validate a DICOM dataset against Parametric Map IOD.
bool quick_check (const core::dicom_dataset &dataset) const
Quick check if dataset has minimum required parametric map attributes.
const pmap_validation_options & options () const noexcept
Get the validation options.
void set_options (const pmap_validation_options &options)
Set validation options.
Private Member Functions
void validate_patient_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_study_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_series_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_general_equipment_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_enhanced_general_equipment_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_image_pixel_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_parametric_map_image_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_multiframe_functional_groups_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_multiframe_dimension_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_common_instance_reference_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void validate_sop_common_module (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_type1_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_type2_attribute (const core::dicom_dataset &dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > &findings) const
void check_modality (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
void check_pixel_data_consistency (const core::dicom_dataset &dataset, std::vector< validation_finding > &findings) const
Private Attributes
pmap_validation_options options_
Detailed Description
Definition at line 171 of file parametric_map_iod_validator.h.
Constructor & Destructor Documentation
parametric_map_iod_validator() [1/2]
kcenon::pacs::services::validation::parametric_map_iod_validator::parametric_map_iod_validator () default
Construct validator with default options.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
parametric_map_iod_validator() [2/2]
kcenon::pacs::services::validation::parametric_map_iod_validator::parametric_map_iod_validator (const pmap_validation_options & options) explicit
Construct validator with custom options.
Parameters
options Validation options
Definition at line 24 of file parametric_map_iod_validator.cpp.
    : options_(options) {}
Member Function Documentation
check_modality()
void kcenon::pacs::services::validation::parametric_map_iod_validator::check_modality (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 441 of file parametric_map_iod_validator.cpp.
{
    if (!dataset.contains(tags::modality)) {
        return;  // Already reported
    }
    auto modality = dataset.get_string(tags::modality);
    if (modality != "RWV" && modality != "PMAP") {
        findings.push_back({
            validation_severity::error,
            tags::modality,
            "Modality must be 'RWV' or 'PMAP' for Parametric Map objects, "
            "found: " + modality,
            "PMAP-ERR-003"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), and kcenon::pacs::core::tags::modality.
Referenced by validate_general_series_module().
check_pixel_data_consistency()
void kcenon::pacs::services::validation::parametric_map_iod_validator::check_pixel_data_consistency (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 461 of file parametric_map_iod_validator.cpp.
{
    // SamplesPerPixel must be 1
    auto samples = dataset.get_numeric<uint16_t>(tags::samples_per_pixel);
    if (samples && *samples != 1) {
        findings.push_back({
            validation_severity::error,
            tags::samples_per_pixel,
            "SamplesPerPixel must be 1 for Parametric Map objects",
            "PMAP-ERR-007"
        });
    }
    // PhotometricInterpretation must be MONOCHROME2
    if (dataset.contains(tags::photometric_interpretation)) {
        auto photometric = dataset.get_string(
            tags::photometric_interpretation);
        if (!sop_classes::is_valid_parametric_map_photometric(photometric)) {
            findings.push_back({
                validation_severity::error,
                tags::photometric_interpretation,
                "PhotometricInterpretation must be MONOCHROME2 for Parametric "
                "Map objects, found: " + photometric,
                "PMAP-ERR-006"
            });
        }
    }
    // BitsAllocated must be 32 or 64 (float or double)
    auto bits_allocated = dataset.get_numeric<uint16_t>(tags::bits_allocated);
    if (bits_allocated
        && !sop_classes::is_valid_parametric_map_bits_allocated(
               *bits_allocated)) {
        findings.push_back({
            validation_severity::error,
            tags::bits_allocated,
            "BitsAllocated must be 32 or 64 for Parametric Map objects "
            "(float or double), found: " +
            std::to_string(*bits_allocated),
            "PMAP-ERR-008"
        });
    }
    // BitsStored must not exceed BitsAllocated
    auto bits_stored = dataset.get_numeric<uint16_t>(tags::bits_stored);
    if (bits_allocated && bits_stored && *bits_stored > *bits_allocated) {
        findings.push_back({
            validation_severity::error,
            tags::bits_stored,
            "BitsStored (" + std::to_string(*bits_stored) +
            ") exceeds BitsAllocated (" +
            std::to_string(*bits_allocated) + ")",
            "PMAP-ERR-005"
        });
    }
    // HighBit should be BitsStored - 1
    auto high_bit = dataset.get_numeric<uint16_t>(tags::high_bit);
    if (bits_stored && high_bit && *high_bit != (*bits_stored - 1)) {
        findings.push_back({
            validation_severity::warning,
            tags::high_bit,
            "HighBit (" + std::to_string(*high_bit) +
            ") does not match BitsStored-1 (" +
            std::to_string(*bits_stored - 1) + ")",
            "PMAP-WARN-002"
        });
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_numeric(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::services::sop_classes::is_valid_parametric_map_bits_allocated(), kcenon::pacs::services::sop_classes::is_valid_parametric_map_photometric(), kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::samples_per_pixel, and kcenon::pacs::services::validation::warning.
Referenced by validate_image_pixel_module().
check_type1_attribute()
void kcenon::pacs::services::validation::parametric_map_iod_validator::check_type1_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 381 of file parametric_map_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::error,
            tag,
            std::string("Type 1 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "PMAP-TYPE1-MISSING"
        });
    } else {
        const auto* element = dataset.get(tag);
        if (element != nullptr) {
            if (element->is_sequence()) {
                if (element->sequence_items().empty()) {
                    findings.push_back({
                        validation_severity::error,
                        tag,
                        std::string("Type 1 sequence has no items: ") +
                        std::string(name) + " (" + tag.to_string() + ")",
                        "PMAP-TYPE1-EMPTY"
                    });
                }
            } else {
                auto value = dataset.get_string(tag);
                if (value.empty()) {
                    findings.push_back({
                        validation_severity::error,
                        tag,
                        std::string("Type 1 attribute has empty value: ") +
                        std::string(name) + " (" + tag.to_string() + ")",
                        "PMAP-TYPE1-EMPTY"
                    });
                }
            }
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get(), kcenon::pacs::core::dicom_dataset::get_string(), name, and kcenon::pacs::core::dicom_tag::to_string().
Referenced by validate_enhanced_general_equipment_module(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_parametric_map_image_module(), and validate_sop_common_module().
check_type2_attribute()
void kcenon::pacs::services::validation::parametric_map_iod_validator::check_type2_attribute (const core::dicom_dataset & dataset, core::dicom_tag tag, std::string_view name, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 424 of file parametric_map_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        findings.push_back({
            validation_severity::warning,
            tag,
            std::string("Type 2 attribute missing: ") + std::string(name) +
            " (" + tag.to_string() + ")",
            "PMAP-TYPE2-MISSING"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), name, kcenon::pacs::core::dicom_tag::to_string(), and kcenon::pacs::services::validation::warning.
Referenced by validate_general_equipment_module(), validate_general_series_module(), validate_general_study_module(), validate_parametric_map_image_module(), and validate_patient_module().
options()
const pmap_validation_options & kcenon::pacs::services::validation::parametric_map_iod_validator::options () const nodiscard noexcept
Get the validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 114 of file parametric_map_iod_validator.cpp.
{
    return options_;
}
References options_.
Referenced by set_options().
quick_check()
bool kcenon::pacs::services::validation::parametric_map_iod_validator::quick_check (const core::dicom_dataset & dataset) const nodiscard
Quick check if dataset has minimum required parametric map attributes.
Parameters
dataset The dataset to check
Returns
true if all Type 1 attributes are present
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 75 of file parametric_map_iod_validator.cpp.
{
    // General Study Module
    if (!dataset.contains(tags::study_instance_uid)) return false;
    // General Series Module
    if (!dataset.contains(tags::modality)) return false;
    if (!dataset.contains(tags::series_instance_uid)) return false;
    // Check modality
    auto modality = dataset.get_string(tags::modality);
    if (modality != "RWV" && modality != "PMAP") return false;
    // Parametric Map Image Module
    if (!dataset.contains(pmap_iod_tags::content_label)) return false;
    if (!dataset.contains(pmap_iod_tags::real_world_value_mapping_sequence))
        return false;
    // Multi-frame
    if (!dataset.contains(pmap_iod_tags::number_of_frames)) return false;
    // Image Pixel Module
    if (!dataset.contains(tags::rows)) return false;
    if (!dataset.contains(tags::columns)) return false;
    // SOP Common Module
    if (!dataset.contains(tags::sop_class_uid)) return false;
    if (!dataset.contains(tags::sop_instance_uid)) return false;
    // Verify SOP Class is Parametric Map
    auto sop_class = dataset.get_string(tags::sop_class_uid);
    if (!sop_classes::is_parametric_map_storage_sop_class(sop_class))
        return false;
    return true;
}
References kcenon::pacs::core::tags::columns, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::pmap_iod_tags::content_label, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_parametric_map_storage_sop_class(), kcenon::pacs::core::tags::modality, kcenon::pacs::services::validation::pmap_iod_tags::number_of_frames, kcenon::pacs::services::validation::pmap_iod_tags::real_world_value_mapping_sequence, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, and kcenon::pacs::core::tags::study_instance_uid.
Referenced by kcenon::pacs::services::validation::is_valid_parametric_map_dataset().
set_options()
void kcenon::pacs::services::validation::parametric_map_iod_validator::set_options (const pmap_validation_options & options)
Set validation options.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 118 of file parametric_map_iod_validator.cpp.
{
    options_ = options;
}
References options(), and options_.
validate()
validation_result kcenon::pacs::services::validation::parametric_map_iod_validator::validate (const core::dicom_dataset & dataset) const nodiscard
Validate a DICOM dataset against Parametric Map IOD.
Parameters
dataset The dataset to validate
Returns
Validation result with all findings
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 29 of file parametric_map_iod_validator.cpp.
{
    validation_result result;
    result.is_valid = true;
    // Validate mandatory modules
    if (options_.check_type1 || options_.check_type2) {
        validate_patient_module(dataset, result.findings);
        validate_general_study_module(dataset, result.findings);
        validate_general_series_module(dataset, result.findings);
        validate_general_equipment_module(dataset, result.findings);
        validate_enhanced_general_equipment_module(dataset, result.findings);
        validate_sop_common_module(dataset, result.findings);
    }
    // Parametric Map Image Module (Content Label, RWVM)
    validate_parametric_map_image_module(dataset, result.findings);
    if (options_.validate_pixel_data) {
        validate_image_pixel_module(dataset, result.findings);
    }
    if (options_.validate_multiframe) {
        validate_multiframe_functional_groups_module(dataset, result.findings);
        validate_multiframe_dimension_module(dataset, result.findings);
    }
    if (options_.validate_references) {
        validate_common_instance_reference_module(dataset, result.findings);
    }
    // Check for errors
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
        if (options_.strict_mode
            && finding.severity == validation_severity::warning) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References kcenon::pacs::services::validation::pmap_validation_options::check_type1, kcenon::pacs::services::validation::pmap_validation_options::check_type2, kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::services::validation::validation_result::is_valid, options_, kcenon::pacs::services::validation::pmap_validation_options::strict_mode, validate_common_instance_reference_module(), validate_enhanced_general_equipment_module(), validate_general_equipment_module(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), kcenon::pacs::services::validation::pmap_validation_options::validate_multiframe, validate_multiframe_dimension_module(), validate_multiframe_functional_groups_module(), validate_parametric_map_image_module(), validate_patient_module(), kcenon::pacs::services::validation::pmap_validation_options::validate_pixel_data, kcenon::pacs::services::validation::pmap_validation_options::validate_references, validate_sop_common_module(), and kcenon::pacs::services::validation::warning.
Referenced by kcenon::pacs::services::validation::validate_parametric_map_iod().
validate_common_instance_reference_module()
void kcenon::pacs::services::validation::parametric_map_iod_validator::validate_common_instance_reference_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 334 of file parametric_map_iod_validator.cpp.
{
    if (options_.check_conditional) {
        if (!dataset.contains(pmap_iod_tags::referenced_series_sequence)) {
            findings.push_back({
                validation_severity::warning,
                pmap_iod_tags::referenced_series_sequence,
                "ReferencedSeriesSequence (0008,1115) should be present for "
                "source image references",
                "PMAP-WARN-003"
            });
        }
    }
}
References kcenon::pacs::services::validation::pmap_validation_options::check_conditional, kcenon::pacs::core::dicom_dataset::contains(), options_, kcenon::pacs::services::validation::pmap_iod_tags::referenced_series_sequence, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_enhanced_general_equipment_module()
void kcenon::pacs::services::validation::parametric_map_iod_validator::validate_enhanced_general_equipment_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 194 of file parametric_map_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, pmap_iod_tags::manufacturer,
                             "Manufacturer", findings);
        check_type1_attribute(dataset, pmap_iod_tags::manufacturer_model_name,
                             "ManufacturerModelName", findings);
        check_type1_attribute(dataset, pmap_iod_tags::device_serial_number,
                             "DeviceSerialNumber", findings);
        check_type1_attribute(dataset, pmap_iod_tags::software_versions,
                             "SoftwareVersions", findings);
    }
}
References kcenon::pacs::services::validation::pmap_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::pmap_iod_tags::device_serial_number, kcenon::pacs::services::validation::pmap_iod_tags::manufacturer, kcenon::pacs::services::validation::pmap_iod_tags::manufacturer_model_name, options_, and kcenon::pacs::services::validation::pmap_iod_tags::software_versions.
Referenced by validate().
validate_general_equipment_module()
void kcenon::pacs::services::validation::parametric_map_iod_validator::validate_general_equipment_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 184 of file parametric_map_iod_validator.cpp.
{
    if (options_.check_type2) {
        check_type2_attribute(dataset, pmap_iod_tags::manufacturer,
                             "Manufacturer", findings);
    }
}
References kcenon::pacs::services::validation::pmap_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::services::validation::pmap_iod_tags::manufacturer, and options_.
Referenced by validate().
validate_general_series_module()
void kcenon::pacs::services::validation::parametric_map_iod_validator::validate_general_series_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 166 of file parametric_map_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::modality,
                             "Modality", findings);
        check_type1_attribute(dataset, tags::series_instance_uid,
                             "SeriesInstanceUID", findings);
        check_modality(dataset, findings);
    }
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::series_number,
                             "SeriesNumber", findings);
    }
}
References check_modality(), kcenon::pacs::services::validation::pmap_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::pmap_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::tags::modality, options_, kcenon::pacs::core::tags::series_instance_uid, and kcenon::pacs::core::tags::series_number.
Referenced by validate().
validate_general_study_module()
void kcenon::pacs::services::validation::parametric_map_iod_validator::validate_general_study_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 143 of file parametric_map_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::study_instance_uid,
                             "StudyInstanceUID", findings);
    }
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::study_date,
                             "StudyDate", findings);
        check_type2_attribute(dataset, tags::study_time,
                             "StudyTime", findings);
        check_type2_attribute(dataset, tags::referring_physician_name,
                             "ReferringPhysicianName", findings);
        check_type2_attribute(dataset, tags::study_id,
                             "StudyID", findings);
        check_type2_attribute(dataset, tags::accession_number,
                             "AccessionNumber", findings);
    }
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::services::validation::pmap_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::pmap_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::core::tags::study_time.
Referenced by validate().
validate_image_pixel_module()
void kcenon::pacs::services::validation::parametric_map_iod_validator::validate_image_pixel_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 210 of file parametric_map_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::samples_per_pixel,
                             "SamplesPerPixel", findings);
        check_type1_attribute(dataset, tags::photometric_interpretation,
                             "PhotometricInterpretation", findings);
        check_type1_attribute(dataset, tags::rows, "Rows", findings);
        check_type1_attribute(dataset, tags::columns, "Columns", findings);
        check_type1_attribute(dataset, tags::bits_allocated,
                             "BitsAllocated", findings);
        check_type1_attribute(dataset, tags::bits_stored,
                             "BitsStored", findings);
        check_type1_attribute(dataset, tags::high_bit,
                             "HighBit", findings);
        check_type1_attribute(dataset, tags::pixel_representation,
                             "PixelRepresentation", findings);
    }
    // Parametric Map-specific pixel data constraints
    check_pixel_data_consistency(dataset, findings);
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, check_pixel_data_consistency(), kcenon::pacs::services::validation::pmap_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::tags::columns, kcenon::pacs::core::tags::high_bit, options_, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::core::tags::rows, and kcenon::pacs::core::tags::samples_per_pixel.
Referenced by validate().
validate_multiframe_dimension_module()
void kcenon::pacs::services::validation::parametric_map_iod_validator::validate_multiframe_dimension_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 307 of file parametric_map_iod_validator.cpp.
{
    if (options_.check_type1) {
        if (!dataset.contains(
                pmap_iod_tags::dimension_organization_sequence)) {
            findings.push_back({
                validation_severity::error,
                pmap_iod_tags::dimension_organization_sequence,
                "Type 1 attribute missing: DimensionOrganizationSequence "
                "(0020,9221)",
                "PMAP-TYPE1-MISSING"
            });
        }
        if (!dataset.contains(pmap_iod_tags::dimension_index_sequence)) {
            findings.push_back({
                validation_severity::error,
                pmap_iod_tags::dimension_index_sequence,
                "Type 1 attribute missing: DimensionIndexSequence "
                "(0020,9222)",
                "PMAP-TYPE1-MISSING"
            });
        }
    }
}
References kcenon::pacs::services::validation::pmap_validation_options::check_type1, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::pmap_iod_tags::dimension_index_sequence, kcenon::pacs::services::validation::pmap_iod_tags::dimension_organization_sequence, kcenon::pacs::services::validation::error, and options_.
Referenced by validate().
validate_multiframe_functional_groups_module()
void kcenon::pacs::services::validation::parametric_map_iod_validator::validate_multiframe_functional_groups_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 267 of file parametric_map_iod_validator.cpp.
{
    // NumberOfFrames is Type 1 (Parametric Maps are always multi-frame)
    if (!dataset.contains(pmap_iod_tags::number_of_frames)) {
        findings.push_back({
            validation_severity::error,
            pmap_iod_tags::number_of_frames,
            "NumberOfFrames (0028,0008) is required for Parametric Map objects "
            "(always multi-frame)",
            "PMAP-ERR-001"
        });
    }
    if (options_.check_type1) {
        if (!dataset.contains(
                pmap_iod_tags::shared_functional_groups_sequence)) {
            findings.push_back({
                validation_severity::warning,
                pmap_iod_tags::shared_functional_groups_sequence,
                "SharedFunctionalGroupsSequence (5200,9229) should be present "
                "for multi-frame Parametric Map objects",
                "PMAP-WARN-001"
            });
        }
        if (!dataset.contains(
                pmap_iod_tags::per_frame_functional_groups_sequence)) {
            findings.push_back({
                validation_severity::warning,
                pmap_iod_tags::per_frame_functional_groups_sequence,
                "PerFrameFunctionalGroupsSequence (5200,9230) should be present "
                "for multi-frame Parametric Map objects",
                "PMAP-WARN-004"
            });
        }
    }
}
References kcenon::pacs::services::validation::pmap_validation_options::check_type1, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::pmap_iod_tags::number_of_frames, options_, kcenon::pacs::services::validation::pmap_iod_tags::per_frame_functional_groups_sequence, kcenon::pacs::services::validation::pmap_iod_tags::shared_functional_groups_sequence, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_parametric_map_image_module()
void kcenon::pacs::services::validation::parametric_map_iod_validator::validate_parametric_map_image_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 235 of file parametric_map_iod_validator.cpp.
{
    // Content Label is Type 1
    if (options_.check_type1) {
        check_type1_attribute(dataset, pmap_iod_tags::content_label,
                             "ContentLabel", findings);
    }
    // Content Description is Type 2
    if (options_.check_type2) {
        check_type2_attribute(dataset, pmap_iod_tags::content_description,
                             "ContentDescription", findings);
        check_type2_attribute(dataset, pmap_iod_tags::content_creator_name,
                             "ContentCreatorName", findings);
    }
    // Real World Value Mapping Sequence is Type 1
    if (options_.validate_rwvm) {
        if (!dataset.contains(pmap_iod_tags::real_world_value_mapping_sequence)) {
            findings.push_back({
                validation_severity::error,
                pmap_iod_tags::real_world_value_mapping_sequence,
                "RealWorldValueMappingSequence (0040,9096) is required for "
                "Parametric Map objects",
                "PMAP-ERR-004"
            });
        }
    }
}
References kcenon::pacs::services::validation::pmap_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::pmap_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::pmap_iod_tags::content_creator_name, kcenon::pacs::services::validation::pmap_iod_tags::content_description, kcenon::pacs::services::validation::pmap_iod_tags::content_label, kcenon::pacs::services::validation::error, options_, kcenon::pacs::services::validation::pmap_iod_tags::real_world_value_mapping_sequence, and kcenon::pacs::services::validation::pmap_validation_options::validate_rwvm.
Referenced by validate().
validate_patient_module()
void kcenon::pacs::services::validation::parametric_map_iod_validator::validate_patient_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 127 of file parametric_map_iod_validator.cpp.
{
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::patient_name,
                             "PatientName", findings);
        check_type2_attribute(dataset, tags::patient_id,
                             "PatientID", findings);
        check_type2_attribute(dataset, tags::patient_birth_date,
                             "PatientBirthDate", findings);
        check_type2_attribute(dataset, tags::patient_sex,
                             "PatientSex", findings);
    }
}
References kcenon::pacs::services::validation::pmap_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, and kcenon::pacs::core::tags::patient_sex.
Referenced by validate().
validate_sop_common_module()
void kcenon::pacs::services::validation::parametric_map_iod_validator::validate_sop_common_module (const core::dicom_dataset & dataset, std::vector< validation_finding > & findings) const private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 351 of file parametric_map_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::sop_class_uid,
                             "SOPClassUID", findings);
        check_type1_attribute(dataset, tags::sop_instance_uid,
                             "SOPInstanceUID", findings);
    }
    // Validate SOP Class UID is a Parametric Map storage class
    if (dataset.contains(tags::sop_class_uid)) {
        auto sop_class = dataset.get_string(tags::sop_class_uid);
        if (!sop_classes::is_parametric_map_storage_sop_class(sop_class)) {
            findings.push_back({
                validation_severity::error,
                tags::sop_class_uid,
                "SOPClassUID is not a recognized Parametric Map Storage SOP "
                "Class: " + sop_class,
                "PMAP-ERR-002"
            });
        }
    }
}
References kcenon::pacs::services::validation::pmap_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_parametric_map_storage_sop_class(), options_, kcenon::pacs::core::tags::sop_class_uid, and kcenon::pacs::core::tags::sop_instance_uid.
Referenced by validate().
Member Data Documentation
options_
pmap_validation_options kcenon::pacs::services::validation::parametric_map_iod_validator::options_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 277 of file parametric_map_iod_validator.h.
Referenced by options(), set_options(), validate(), validate_common_instance_reference_module(), validate_enhanced_general_equipment_module(), validate_general_equipment_module(), validate_general_series_module(), validate_general_study_module(), validate_image_pixel_module(), validate_multiframe_dimension_module(), validate_multiframe_functional_groups_module(), validate_parametric_map_image_module(), validate_patient_module(), and validate_sop_common_module().
The documentation for this class was generated from the following files:
include/kcenon/pacs/services/validation/parametric_map_iod_validator.h
src/services/validation/parametric_map_iod_validator.cpp