PACS System: kcenon::pacs::network::dimse::dimse_message Class Reference
kcenon::pacs::network::dimse::dimse_message Class Reference
#include <dimse_message.h>
Public Types
using encoded_message = std::pair<std::vector<uint8_t>, std::vector<uint8_t>>
Encoded message result type: pair of (command_set_bytes, dataset_bytes)
Public Member Functions
dimse_message (command_field cmd, uint16_t message_id)
Construct a new DIMSE message.
dimse_message ()=default
Default constructor (creates an invalid message)
dimse_message (const dimse_message &)=default
Copy constructor.
dimse_message (dimse_message &&) noexcept=default
Move constructor.
auto operator= (const dimse_message &) -> dimse_message &=default
Copy assignment.
auto operator= (dimse_message &&) noexcept -> dimse_message &=default
Move assignment.
~dimse_message ()=default
Destructor.
auto command () const noexcept -> command_field
Get the command field.
auto message_id () const noexcept -> uint16_t
Get the message ID.
auto command_set () noexcept -> core::dicom_dataset &
Get mutable reference to the command set.
auto command_set () const noexcept -> const core::dicom_dataset &
Get const reference to the command set.
auto has_dataset () const noexcept -> bool
Check if the message has an associated data set.
auto dataset () -> kcenon::pacs::Result< std::reference_wrapper< core::dicom_dataset > >
Get mutable reference to the data set.
auto dataset () const -> kcenon::pacs::Result< std::reference_wrapper< const core::dicom_dataset > >
Get const reference to the data set.
void set_dataset (core::dicom_dataset ds)
Set the data set for this message.
void clear_dataset () noexcept
Remove the data set from this message.
auto status () const -> status_code
Get the status code (for response messages)
void set_status (status_code status)
Set the status code (for response messages)
auto affected_sop_class_uid () const -> std::string
Get the Affected SOP Class UID.
void set_affected_sop_class_uid (std::string_view uid)
Set the Affected SOP Class UID.
auto affected_sop_instance_uid () const -> std::string
Get the Affected SOP Instance UID.
void set_affected_sop_instance_uid (std::string_view uid)
Set the Affected SOP Instance UID.
auto priority () const -> uint16_t
Get the priority.
void set_priority (uint16_t priority)
Set the priority.
auto message_id_responded_to () const -> uint16_t
Get the Message ID Being Responded To (for responses)
void set_message_id_responded_to (uint16_t id)
Set the Message ID Being Responded To (for responses)
auto requested_sop_class_uid () const -> std::string
Get the Requested SOP Class UID (for N-SET, N-GET, N-ACTION, N-DELETE)
void set_requested_sop_class_uid (std::string_view uid)
Set the Requested SOP Class UID.
auto requested_sop_instance_uid () const -> std::string
Get the Requested SOP Instance UID (for N-SET, N-GET, N-ACTION, N-DELETE)
void set_requested_sop_instance_uid (std::string_view uid)
Set the Requested SOP Instance UID.
auto event_type_id () const -> std::optional< uint16_t >
Get the Event Type ID (for N-EVENT-REPORT)
void set_event_type_id (uint16_t type_id)
Set the Event Type ID.
auto action_type_id () const -> std::optional< uint16_t >
Get the Action Type ID (for N-ACTION)
void set_action_type_id (uint16_t type_id)
Set the Action Type ID.
auto attribute_identifier_list () const -> std::vector< core::dicom_tag >
Get the Attribute Identifier List (for N-GET)
void set_attribute_identifier_list (const std::vector< core::dicom_tag > &tags)
Set the Attribute Identifier List.
auto remaining_subops () const -> std::optional< uint16_t >
Get the number of remaining sub-operations.
void set_remaining_subops (uint16_t count)
Set the number of remaining sub-operations.
auto completed_subops () const -> std::optional< uint16_t >
Get the number of completed sub-operations.
void set_completed_subops (uint16_t count)
Set the number of completed sub-operations.
auto failed_subops () const -> std::optional< uint16_t >
Get the number of failed sub-operations.
void set_failed_subops (uint16_t count)
Set the number of failed sub-operations.
auto warning_subops () const -> std::optional< uint16_t >
Get the number of warning sub-operations.
void set_warning_subops (uint16_t count)
Set the number of warning sub-operations.
auto is_valid () const noexcept -> bool
Check if the message is valid.
auto is_request () const noexcept -> bool
Check if this is a request message.
auto is_response () const noexcept -> bool
Check if this is a response message.
Static Public Member Functions
static auto encode (const dimse_message &msg, const encoding::transfer_syntax &dataset_ts) -> dimse_result< encoded_message >
Encode the DIMSE message to bytes.
static auto decode (std::span< const uint8_t > command_data, std::span< const uint8_t > dataset_data, const encoding::transfer_syntax &dataset_ts) -> dimse_result< dimse_message >
Decode a DIMSE message from bytes.
Private Member Functions
void update_data_set_type ()
Update the CommandDataSetType field based on dataset presence.
void update_command_group_length ()
Calculate and set CommandGroupLength.
Private Attributes
command_field command_ {}
uint16_t message_id_ {0}
core::dicom_dataset command_set_
std::optional< core::dicom_dataset > dataset_
Detailed Description
Examples
get_scu/main.cpp, move_scu/main.cpp, and retrieve_scu/main.cpp.
Definition at line 202 of file dimse_message.h.
Member Typedef Documentation
encoded_message
using kcenon::pacs::network::dimse::dimse_message::encoded_message = std::pair<std::vector<uint8_t>, std::vector<uint8_t>>
Encoded message result type: pair of (command_set_bytes, dataset_bytes)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 488 of file dimse_message.h.
Constructor & Destructor Documentation
dimse_message() [1/4]
kcenon::pacs::network::dimse::dimse_message::dimse_message (command_field cmd, uint16_t message_id)
Construct a new DIMSE message.
Parameters
cmd The command field (type of operation)
message_id Unique message identifier
Definition at line 35 of file dimse_message.cpp.
    : command_(cmd), message_id_(message_id) {
    // Initialize the command set with required fields
    command_set_.set_numeric(tag_command_field, encoding::vr_type::US,
                             static_cast<uint16_t>(cmd));
    command_set_.set_numeric(tag_message_id, encoding::vr_type::US, message_id);
    update_data_set_type();
}
References command_set_, message_id(), kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::network::dimse::tag_command_field, kcenon::pacs::network::dimse::tag_message_id, update_data_set_type(), and kcenon::pacs::encoding::US.
dimse_message() [2/4]
kcenon::pacs::network::dimse::dimse_message::dimse_message () default
Default constructor (creates an invalid message)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
dimse_message() [3/4]
kcenon::pacs::network::dimse::dimse_message::dimse_message (const dimse_message &) default
Copy constructor.
dimse_message() [4/4]
kcenon::pacs::network::dimse::dimse_message::dimse_message (dimse_message &&) default noexcept
Move constructor.
~dimse_message()
kcenon::pacs::network::dimse::dimse_message::~dimse_message () default
Destructor.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Member Function Documentation
action_type_id()
auto kcenon::pacs::network::dimse::dimse_message::action_type_id () const -> std::optional<uint16_t> nodiscard
Get the Action Type ID (for N-ACTION)
Returns
The action type ID if present
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 174 of file dimse_message.cpp.
{
    return command_set_.get_numeric<uint16_t>(tag_action_type_id);
}
References command_set_, kcenon::pacs::core::dicom_dataset::get_numeric(), and kcenon::pacs::network::dimse::tag_action_type_id.
Referenced by kcenon::pacs::services::print_scp::handle_n_action(), kcenon::pacs::services::storage_commitment_scp::handle_n_action(), kcenon::pacs::services::ups_push_scp::handle_n_action(), and kcenon::pacs::services::ups_watch_scp::handle_n_action().
affected_sop_class_uid()
auto kcenon::pacs::network::dimse::dimse_message::affected_sop_class_uid () const -> std::string nodiscard
Get the Affected SOP Class UID.
Returns
The SOP Class UID if present
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 112 of file dimse_message.cpp.
{
    return command_set_.get_string(tag_affected_sop_class_uid);
}
References command_set_, kcenon::pacs::core::dicom_dataset::get_string(), and kcenon::pacs::network::dimse::tag_affected_sop_class_uid.
Referenced by kcenon::pacs::network::dicom_server::dispatch_to_service(), kcenon::pacs::services::retrieve_scp::handle_c_get(), kcenon::pacs::services::retrieve_scp::handle_c_move(), kcenon::pacs::services::query_scp::handle_message(), kcenon::pacs::services::storage_scp::handle_message(), kcenon::pacs::services::ups_query_scp::handle_message(), kcenon::pacs::services::worklist_scp::handle_message(), kcenon::pacs::services::print_scp::handle_n_action(), kcenon::pacs::services::storage_commitment_scp::handle_n_action(), kcenon::pacs::services::mpps_scp::handle_n_create(), kcenon::pacs::services::print_scp::handle_n_create(), kcenon::pacs::services::ups_push_scp::handle_n_create(), kcenon::pacs::services::print_scp::handle_n_delete(), kcenon::pacs::services::print_scp::handle_n_get(), kcenon::pacs::services::mpps_scp::handle_n_set(), and kcenon::pacs::services::print_scp::handle_n_set().
affected_sop_instance_uid()
auto kcenon::pacs::network::dimse::dimse_message::affected_sop_instance_uid () const -> std::string nodiscard
Get the Affected SOP Instance UID.
Returns
The SOP Instance UID if present
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 121 of file dimse_message.cpp.
{
    return command_set_.get_string(tag_affected_sop_instance_uid);
}
References command_set_, kcenon::pacs::core::dicom_dataset::get_string(), and kcenon::pacs::network::dimse::tag_affected_sop_instance_uid.
Referenced by kcenon::pacs::services::print_scp::create_film_box(), kcenon::pacs::services::print_scp::create_film_session(), kcenon::pacs::services::ups_watch_scu::handle_event_report(), kcenon::pacs::services::storage_scp::handle_message(), kcenon::pacs::services::print_scp::handle_n_action(), kcenon::pacs::services::ups_push_scp::handle_n_action(), kcenon::pacs::services::ups_watch_scp::handle_n_action(), kcenon::pacs::services::mpps_scp::handle_n_create(), kcenon::pacs::services::ups_push_scp::handle_n_create(), kcenon::pacs::services::print_scp::handle_n_delete(), kcenon::pacs::services::print_scp::handle_n_get(), kcenon::pacs::services::mpps_scp::handle_n_set(), kcenon::pacs::services::print_scp::handle_n_set(), and kcenon::pacs::services::ups_push_scp::handle_n_set().
attribute_identifier_list()
auto kcenon::pacs::network::dimse::dimse_message::attribute_identifier_list () const -> std::vector<core::dicom_tag> nodiscard
Get the Attribute Identifier List (for N-GET)
Returns
Vector of tags to retrieve
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 182 of file dimse_message.cpp.
{
    std::vector<core::dicom_tag> tags;
    const auto* elem = command_set_.get(tag_attribute_identifier_list);
    if (elem == nullptr) {
        return tags;
    }
    auto bytes = elem->raw_data();
    if (bytes.empty()) {
        return tags;
    }
    // Each tag is 4 bytes (group:2 + element:2), little-endian
    for (size_t i = 0; i + 3 < bytes.size(); i += 4) {
        uint16_t group = static_cast<uint16_t>(bytes[i]) |
                         (static_cast<uint16_t>(bytes[i + 1]) << 8);
        uint16_t element = static_cast<uint16_t>(bytes[i + 2]) |
                           (static_cast<uint16_t>(bytes[i + 3]) << 8);
        tags.emplace_back(group, element);
    }
    return tags;
}
References command_set_, kcenon::pacs::core::dicom_dataset::get(), and kcenon::pacs::network::dimse::tag_attribute_identifier_list.
Referenced by kcenon::pacs::services::n_get_scp::handle_message().
clear_dataset()
void kcenon::pacs::network::dimse::dimse_message::clear_dataset () noexcept
Remove the data set from this message.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 91 of file dimse_message.cpp.
{
    dataset_.reset();
    update_data_set_type();
}
References dataset_, and update_data_set_type().
command()
auto kcenon::pacs::network::dimse::dimse_message::command () const -> command_field nodiscard noexcept
Get the command field.
Returns
The command field value
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 48 of file dimse_message.cpp.
{
    return command_;
}
References command_.
Referenced by kcenon::pacs::network::v2::dicom_association_handler::dispatch_to_service(), kcenon::pacs::services::storage_commitment_scu::handle_event_report(), kcenon::pacs::services::ups_watch_scu::handle_event_report(), kcenon::pacs::services::mpps_scp::handle_message(), kcenon::pacs::services::n_get_scp::handle_message(), kcenon::pacs::services::print_scp::handle_message(), kcenon::pacs::services::query_scp::handle_message(), kcenon::pacs::services::retrieve_scp::handle_message(), kcenon::pacs::services::storage_commitment_scp::handle_message(), kcenon::pacs::services::storage_scp::handle_message(), kcenon::pacs::services::ups_push_scp::handle_message(), kcenon::pacs::services::ups_query_scp::handle_message(), kcenon::pacs::services::ups_watch_scp::handle_message(), kcenon::pacs::services::verification_scp::handle_message(), and kcenon::pacs::services::worklist_scp::handle_message().
command_set() [1/2]
auto kcenon::pacs::network::dimse::dimse_message::command_set () const -> const core::dicom_dataset& nodiscard noexcept
Get const reference to the command set.
Returns
Const reference to the command dataset
Definition at line 60 of file dimse_message.cpp.
{
    return command_set_;
}
References command_set_.
command_set() [2/2]
auto kcenon::pacs::network::dimse::dimse_message::command_set () -> core::dicom_dataset& nodiscard noexcept
Get mutable reference to the command set.
Returns
Reference to the command dataset
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 56 of file dimse_message.cpp.
{
    return command_set_;
}
References command_set_.
Referenced by kcenon::pacs::services::retrieve_scp::get_move_destination(), kcenon::pacs::services::storage_commitment_scp::handle_n_action(), kcenon::pacs::services::print_scp::handle_n_get(), kcenon::pacs::services::mpps_scp::handle_n_set(), kcenon::pacs::services::print_scp::handle_n_set(), and kcenon::pacs::services::ups_push_scp::handle_n_set().
completed_subops()
auto kcenon::pacs::network::dimse::dimse_message::completed_subops () const -> std::optional<uint16_t> nodiscard
Get the number of completed sub-operations.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 235 of file dimse_message.cpp.
{
    return command_set_.get_numeric<uint16_t>(tag_number_of_completed_subops);
}
References command_set_, kcenon::pacs::core::dicom_dataset::get_numeric(), and kcenon::pacs::network::dimse::tag_number_of_completed_subops.
dataset() [1/2]
auto kcenon::pacs::network::dimse::dimse_message::dataset () -> kcenon::pacs::Result<std::reference_wrapper<core::dicom_dataset>> nodiscard
Get mutable reference to the data set.
Returns
Result containing reference to the data set or error if not present
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 72 of file dimse_message.cpp.
{
    if (!dataset_) {
        return make_dimse_error(dimse_error::invalid_data_format, "DIMSE message has no dataset");
    }
    return std::ref(*dataset_);
}
References kcenon::pacs::network::dimse::invalid_data_format.
Referenced by kcenon::pacs::services::print_scp::create_film_box(), kcenon::pacs::services::print_scp::create_film_session(), encode(), kcenon::pacs::services::retrieve_scp::handle_c_get(), kcenon::pacs::services::retrieve_scp::handle_c_move(), kcenon::pacs::services::storage_commitment_scu::handle_event_report(), kcenon::pacs::services::ups_watch_scu::handle_event_report(), kcenon::pacs::services::query_scp::handle_message(), kcenon::pacs::services::storage_scp::handle_message(), kcenon::pacs::services::ups_query_scp::handle_message(), kcenon::pacs::services::worklist_scp::handle_message(), kcenon::pacs::services::storage_commitment_scp::handle_n_action(), kcenon::pacs::services::ups_push_scp::handle_n_action(), kcenon::pacs::services::mpps_scp::handle_n_create(), kcenon::pacs::services::ups_push_scp::handle_n_create(), kcenon::pacs::services::mpps_scp::handle_n_set(), kcenon::pacs::services::print_scp::handle_n_set(), and kcenon::pacs::services::ups_push_scp::handle_n_set().
dataset() [2/2]
auto kcenon::pacs::network::dimse::dimse_message::dataset () const -> kcenon::pacs::Result<std::reference_wrapper<const core::dicom_dataset>> nodiscard
Get const reference to the data set.
Returns
Result containing reference to the data set or error if not present
Definition at line 79 of file dimse_message.cpp.
{
    if (!dataset_) {
        return make_dimse_error(dimse_error::invalid_data_format, "DIMSE message has no dataset");
    }
    return std::cref(*dataset_);
}
References dataset_, and kcenon::pacs::network::dimse::invalid_data_format.
decode()
auto kcenon::pacs::network::dimse::dimse_message::decode (std::span< const uint8_t > command_data, std::span< const uint8_t > dataset_data, const encoding::transfer_syntax & dataset_ts) -> dimse_result<dimse_message> static nodiscard
Decode a DIMSE message from bytes.
Parameters
command_data The encoded command set (Implicit VR LE)
dataset_data The encoded data set (per transfer syntax)
dataset_ts The transfer syntax of the data set
Returns
The decoded message or an error
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 293 of file dimse_message.cpp.
{
    // Decode command set (always Implicit VR Little Endian)
    auto cmd_result = encoding::implicit_vr_codec::decode(command_data);
    if (cmd_result.is_err()) {
        return make_dimse_error(dimse_error::decoding_error, "Failed to decode command set");
    }
    auto command_set = std::move(cmd_result.value());
    // Extract command field
    auto cmd_value = command_set.get_numeric<uint16_t>(tag_command_field);
    if (!cmd_value) {
        return make_dimse_error(dimse_error::missing_required_field, "CommandField tag not found");
    }
    auto cmd = static_cast<command_field>(*cmd_value);
    // Extract message ID
    auto msg_id = command_set.get_numeric<uint16_t>(tag_message_id);
    if (!msg_id && dimse::is_request(cmd)) {
        return make_dimse_error(dimse_error::missing_required_field, "MessageID tag not found for request");
    }
    // For responses, use message_id_responded_to if message_id is not present
    uint16_t message_id = msg_id.value_or(0);
    dimse_message msg(cmd, message_id);
    msg.command_set_ = std::move(command_set);
    // Decode dataset if present
    if (!dataset_data.empty()) {
        kcenon::pacs::Result<core::dicom_dataset> ds_result =
            (dataset_ts.vr_type() == encoding::vr_encoding::implicit)
                ? encoding::implicit_vr_codec::decode(dataset_data)
                : encoding::explicit_vr_codec::decode(dataset_data);
        if (ds_result.is_err()) {
            return make_dimse_error(dimse_error::decoding_error, "Failed to decode dataset");
        }
        msg.dataset_ = std::move(ds_result.value());
    }
    return msg;
}
References command_set_, dataset_, kcenon::pacs::encoding::explicit_vr_codec::decode(), kcenon::pacs::encoding::implicit_vr_codec::decode(), kcenon::pacs::network::dimse::decoding_error, kcenon::pacs::encoding::implicit, kcenon::pacs::network::dimse::is_request(), kcenon::pacs::network::dimse::missing_required_field, kcenon::pacs::network::dimse::tag_command_field, and kcenon::pacs::network::dimse::tag_message_id.
Referenced by kcenon::pacs::network::v2::dicom_association_handler::handle_p_data_tf().
encode()
auto kcenon::pacs::network::dimse::dimse_message::encode (const dimse_message & msg, const encoding::transfer_syntax & dataset_ts) -> dimse_result<encoded_message> static nodiscard
Encode the DIMSE message to bytes.
Parameters
msg The message to encode
dataset_ts The transfer syntax for the data set
Returns
Encoded command set and data set bytes as a pair
The command set is always encoded using Implicit VR Little Endian. The data set uses the specified transfer syntax.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 266 of file dimse_message.cpp.
{
    // Create a mutable copy for encoding
    dimse_message copy = msg;
    copy.update_command_group_length();
    // Command set is always Implicit VR Little Endian
    auto command_bytes = encoding::implicit_vr_codec::encode(copy.command_set_);
    // Encode dataset if present
    std::vector<uint8_t> dataset_bytes;
    if (copy.has_dataset()) {
        auto ds_result = copy.dataset();
        if (ds_result.is_err()) {
            return ds_result.error();
        }
        if (dataset_ts.vr_type() == encoding::vr_encoding::implicit) {
            dataset_bytes = encoding::implicit_vr_codec::encode(ds_result.value().get());
        } else {
            dataset_bytes = encoding::explicit_vr_codec::encode(ds_result.value().get());
        }
    }
    return encoded_message{std::move(command_bytes), std::move(dataset_bytes)};
}
References command_set_, dataset(), kcenon::pacs::encoding::explicit_vr_codec::encode(), kcenon::pacs::encoding::implicit_vr_codec::encode(), has_dataset(), kcenon::pacs::encoding::implicit, and update_command_group_length().
event_type_id()
auto kcenon::pacs::network::dimse::dimse_message::event_type_id () const -> std::optional<uint16_t> nodiscard
Get the Event Type ID (for N-EVENT-REPORT)
Returns
The event type ID if present
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 166 of file dimse_message.cpp.
{
    return command_set_.get_numeric<uint16_t>(tag_event_type_id);
}
References command_set_, kcenon::pacs::core::dicom_dataset::get_numeric(), and kcenon::pacs::network::dimse::tag_event_type_id.
Referenced by kcenon::pacs::services::ups_watch_scu::handle_event_report().
failed_subops()
auto kcenon::pacs::network::dimse::dimse_message::failed_subops () const -> std::optional<uint16_t> nodiscard
Get the number of failed sub-operations.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 244 of file dimse_message.cpp.
{
    return command_set_.get_numeric<uint16_t>(tag_number_of_failed_subops);
}
References command_set_, kcenon::pacs::core::dicom_dataset::get_numeric(), and kcenon::pacs::network::dimse::tag_number_of_failed_subops.
has_dataset()
auto kcenon::pacs::network::dimse::dimse_message::has_dataset () const -> bool nodiscard noexcept
Check if the message has an associated data set.
Returns
true if a data set is present
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 68 of file dimse_message.cpp.
{
    return dataset_.has_value();
}
References dataset_.
Referenced by kcenon::pacs::services::print_scp::create_film_box(), kcenon::pacs::services::print_scp::create_film_session(), encode(), kcenon::pacs::services::retrieve_scp::handle_c_get(), kcenon::pacs::services::retrieve_scp::handle_c_move(), kcenon::pacs::services::storage_commitment_scu::handle_event_report(), kcenon::pacs::services::ups_watch_scu::handle_event_report(), kcenon::pacs::services::query_scp::handle_message(), kcenon::pacs::services::storage_scp::handle_message(), kcenon::pacs::services::ups_query_scp::handle_message(), kcenon::pacs::services::worklist_scp::handle_message(), kcenon::pacs::services::storage_commitment_scp::handle_n_action(), kcenon::pacs::services::ups_push_scp::handle_n_action(), kcenon::pacs::services::mpps_scp::handle_n_create(), kcenon::pacs::services::ups_push_scp::handle_n_create(), kcenon::pacs::services::mpps_scp::handle_n_set(), kcenon::pacs::services::print_scp::handle_n_set(), and kcenon::pacs::services::ups_push_scp::handle_n_set().
is_request()
auto kcenon::pacs::network::dimse::dimse_message::is_request () const -> bool nodiscard noexcept
Check if this is a request message.
Returns
true if the command field represents a request
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 348 of file dimse_message.cpp.
{
    return dimse::is_request(command_);
}
References command_, and kcenon::pacs::network::dimse::is_request().
is_response()
auto kcenon::pacs::network::dimse::dimse_message::is_response () const -> bool nodiscard noexcept
Check if this is a response message.
Returns
true if the command field represents a response
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 352 of file dimse_message.cpp.
{
    return dimse::is_response(command_);
}
References command_, and kcenon::pacs::network::dimse::is_response().
is_valid()
auto kcenon::pacs::network::dimse::dimse_message::is_valid () const -> bool nodiscard noexcept
Check if the message is valid.
Returns
true if the message has valid command field and message ID
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 343 of file dimse_message.cpp.
{
    return command_set_.contains(tag_command_field) &&
           command_set_.contains(tag_message_id);
}
References command_set_, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::network::dimse::tag_command_field, and kcenon::pacs::network::dimse::tag_message_id.
Referenced by kcenon::pacs::network::association::send_dimse().
message_id()
auto kcenon::pacs::network::dimse::dimse_message::message_id () const -> uint16_t nodiscard noexcept
Get the message ID.
Returns
The message ID
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 52 of file dimse_message.cpp.
{
    return message_id_;
}
References message_id_.
Referenced by kcenon::pacs::services::print_scp::create_film_box(), kcenon::pacs::services::print_scp::create_film_session(), dimse_message(), kcenon::pacs::services::retrieve_scp::handle_c_get(), kcenon::pacs::services::retrieve_scp::handle_c_move(), kcenon::pacs::services::n_get_scp::handle_message(), kcenon::pacs::services::query_scp::handle_message(), kcenon::pacs::services::storage_scp::handle_message(), kcenon::pacs::services::ups_query_scp::handle_message(), kcenon::pacs::services::verification_scp::handle_message(), kcenon::pacs::services::worklist_scp::handle_message(), kcenon::pacs::services::print_scp::handle_n_action(), kcenon::pacs::services::storage_commitment_scp::handle_n_action(), kcenon::pacs::services::ups_push_scp::handle_n_action(), kcenon::pacs::services::ups_watch_scp::handle_n_action(), kcenon::pacs::services::mpps_scp::handle_n_create(), kcenon::pacs::services::print_scp::handle_n_create(), kcenon::pacs::services::ups_push_scp::handle_n_create(), kcenon::pacs::services::print_scp::handle_n_delete(), kcenon::pacs::services::print_scp::handle_n_get(), kcenon::pacs::services::ups_push_scp::handle_n_get(), kcenon::pacs::services::mpps_scp::handle_n_set(), kcenon::pacs::services::print_scp::handle_n_set(), and kcenon::pacs::services::ups_push_scp::handle_n_set().
message_id_responded_to()
auto kcenon::pacs::network::dimse::dimse_message::message_id_responded_to () const -> uint16_t nodiscard
Get the Message ID Being Responded To (for responses)
Returns
The message ID being responded to
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 138 of file dimse_message.cpp.
{
    return command_set_.get_numeric<uint16_t>(tag_message_id_responded_to).value_or(0);
}
References command_set_, kcenon::pacs::core::dicom_dataset::get_numeric(), and kcenon::pacs::network::dimse::tag_message_id_responded_to.
operator=() [1/2]
auto kcenon::pacs::network::dimse::dimse_message::operator= (const dimse_message &) -> dimse_message &=default default
Copy assignment.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
operator=() [2/2]
auto kcenon::pacs::network::dimse::dimse_message::operator= (dimse_message &&) -> dimse_message &=default default noexcept
Move assignment.
priority()
auto kcenon::pacs::network::dimse::dimse_message::priority () const -> uint16_t nodiscard
Get the priority.
Returns
The priority value (0=medium, 1=high, 2=low)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 130 of file dimse_message.cpp.
{
    return command_set_.get_numeric<uint16_t>(tag_priority).value_or(priority_medium);
}
References command_set_, kcenon::pacs::core::dicom_dataset::get_numeric(), kcenon::pacs::network::dimse::priority_medium, and kcenon::pacs::network::dimse::tag_priority.
Referenced by set_priority().
remaining_subops()
auto kcenon::pacs::network::dimse::dimse_message::remaining_subops () const -> std::optional<uint16_t> nodiscard
Get the number of remaining sub-operations.
Returns
Optional count of remaining sub-operations
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 226 of file dimse_message.cpp.
{
    return command_set_.get_numeric<uint16_t>(tag_number_of_remaining_subops);
}
References command_set_, kcenon::pacs::core::dicom_dataset::get_numeric(), and kcenon::pacs::network::dimse::tag_number_of_remaining_subops.
requested_sop_class_uid()
auto kcenon::pacs::network::dimse::dimse_message::requested_sop_class_uid () const -> std::string nodiscard
Get the Requested SOP Class UID (for N-SET, N-GET, N-ACTION, N-DELETE)
Returns
The SOP Class UID if present
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 150 of file dimse_message.cpp.
{
    return command_set_.get_string(tag_requested_sop_class_uid);
}
References command_set_, kcenon::pacs::core::dicom_dataset::get_string(), and kcenon::pacs::network::dimse::tag_requested_sop_class_uid.
Referenced by kcenon::pacs::services::n_get_scp::handle_message().
requested_sop_instance_uid()
auto kcenon::pacs::network::dimse::dimse_message::requested_sop_instance_uid () const -> std::string nodiscard
Get the Requested SOP Instance UID (for N-SET, N-GET, N-ACTION, N-DELETE)
Returns
The SOP Instance UID if present
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 158 of file dimse_message.cpp.
{
    return command_set_.get_string(tag_requested_sop_instance_uid);
}
References command_set_, kcenon::pacs::core::dicom_dataset::get_string(), and kcenon::pacs::network::dimse::tag_requested_sop_instance_uid.
Referenced by kcenon::pacs::services::n_get_scp::handle_message(), kcenon::pacs::services::ups_push_scp::handle_n_action(), kcenon::pacs::services::ups_watch_scp::handle_n_action(), and kcenon::pacs::services::ups_push_scp::handle_n_get().
set_action_type_id()
void kcenon::pacs::network::dimse::dimse_message::set_action_type_id (uint16_t type_id)
Set the Action Type ID.
Parameters
type_id The action type ID
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 178 of file dimse_message.cpp.
{
    command_set_.set_numeric(tag_action_type_id, encoding::vr_type::US, type_id);
}
References command_set_, kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::network::dimse::tag_action_type_id, and kcenon::pacs::encoding::US.
Referenced by kcenon::pacs::network::dimse::make_n_action_rq(), and kcenon::pacs::network::dimse::make_n_action_rsp().
set_affected_sop_class_uid()
void kcenon::pacs::network::dimse::dimse_message::set_affected_sop_class_uid (std::string_view uid)
Set the Affected SOP Class UID.
Parameters
uid The SOP Class UID
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 116 of file dimse_message.cpp.
{
    command_set_.set_string(tag_affected_sop_class_uid, encoding::vr_type::UI,
                            uid);
}
References command_set_, kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::network::dimse::tag_affected_sop_class_uid, kcenon::pacs::encoding::UI, and uid.
Referenced by kcenon::pacs::network::dimse::make_c_echo_rq(), kcenon::pacs::network::dimse::make_c_echo_rsp(), kcenon::pacs::network::dimse::make_c_find_rq(), kcenon::pacs::network::dimse::make_c_find_rsp(), kcenon::pacs::network::dimse::make_c_store_rq(), kcenon::pacs::network::dimse::make_c_store_rsp(), kcenon::pacs::network::dimse::make_n_action_rsp(), kcenon::pacs::network::dimse::make_n_create_rq(), kcenon::pacs::network::dimse::make_n_create_rsp(), kcenon::pacs::network::dimse::make_n_delete_rsp(), kcenon::pacs::network::dimse::make_n_event_report_rq(), kcenon::pacs::network::dimse::make_n_event_report_rsp(), kcenon::pacs::network::dimse::make_n_get_rsp(), and kcenon::pacs::network::dimse::make_n_set_rsp().
set_affected_sop_instance_uid()
void kcenon::pacs::network::dimse::dimse_message::set_affected_sop_instance_uid (std::string_view uid)
Set the Affected SOP Instance UID.
Parameters
uid The SOP Instance UID
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 125 of file dimse_message.cpp.
{
    command_set_.set_string(tag_affected_sop_instance_uid, encoding::vr_type::UI,
                            uid);
}
References command_set_, kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::network::dimse::tag_affected_sop_instance_uid, kcenon::pacs::encoding::UI, and uid.
Referenced by kcenon::pacs::network::dimse::make_c_store_rq(), kcenon::pacs::network::dimse::make_c_store_rsp(), kcenon::pacs::network::dimse::make_n_action_rsp(), kcenon::pacs::network::dimse::make_n_create_rq(), kcenon::pacs::network::dimse::make_n_create_rsp(), kcenon::pacs::network::dimse::make_n_delete_rsp(), kcenon::pacs::network::dimse::make_n_event_report_rq(), kcenon::pacs::network::dimse::make_n_event_report_rsp(), kcenon::pacs::network::dimse::make_n_get_rsp(), and kcenon::pacs::network::dimse::make_n_set_rsp().
set_attribute_identifier_list()
void kcenon::pacs::network::dimse::dimse_message::set_attribute_identifier_list (const std::vector< core::dicom_tag > & tags)
Set the Attribute Identifier List.
Parameters
tags Vector of tags to retrieve
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 205 of file dimse_message.cpp.
{
    std::vector<uint8_t> bytes;
    bytes.reserve(tags.size() * 4);
    for (const auto& tag : tags) {
        // Little-endian encoding
        bytes.push_back(static_cast<uint8_t>(tag.group() & 0xFF));
        bytes.push_back(static_cast<uint8_t>((tag.group() >> 8) & 0xFF));
        bytes.push_back(static_cast<uint8_t>(tag.element() & 0xFF));
        bytes.push_back(static_cast<uint8_t>((tag.element() >> 8) & 0xFF));
    }
    command_set_.insert(core::dicom_element(tag_attribute_identifier_list,
                                            encoding::vr_type::AT, bytes));
}
References kcenon::pacs::encoding::AT, command_set_, kcenon::pacs::core::dicom_dataset::insert(), and kcenon::pacs::network::dimse::tag_attribute_identifier_list.
Referenced by kcenon::pacs::network::dimse::make_n_get_rq().
set_completed_subops()
void kcenon::pacs::network::dimse::dimse_message::set_completed_subops (uint16_t count)
Set the number of completed sub-operations.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 239 of file dimse_message.cpp.
{
    command_set_.set_numeric(tag_number_of_completed_subops, encoding::vr_type::US,
                             count);
}
References command_set_, kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::network::dimse::tag_number_of_completed_subops, and kcenon::pacs::encoding::US.
set_dataset()
void kcenon::pacs::network::dimse::dimse_message::set_dataset (core::dicom_dataset ds)
Set the data set for this message.
Parameters
ds The data set to associate with this message
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 86 of file dimse_message.cpp.
{
    dataset_ = std::move(ds);
    update_data_set_type();
}
References dataset_, and update_data_set_type().
set_event_type_id()
void kcenon::pacs::network::dimse::dimse_message::set_event_type_id (uint16_t type_id)
Set the Event Type ID.
Parameters
type_id The event type ID
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 170 of file dimse_message.cpp.
{
    command_set_.set_numeric(tag_event_type_id, encoding::vr_type::US, type_id);
}
References command_set_, kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::network::dimse::tag_event_type_id, and kcenon::pacs::encoding::US.
Referenced by kcenon::pacs::network::dimse::make_n_event_report_rq(), and kcenon::pacs::network::dimse::make_n_event_report_rsp().
set_failed_subops()
void kcenon::pacs::network::dimse::dimse_message::set_failed_subops (uint16_t count)
Set the number of failed sub-operations.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 248 of file dimse_message.cpp.
{
    command_set_.set_numeric(tag_number_of_failed_subops, encoding::vr_type::US,
                             count);
}
References command_set_, kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::network::dimse::tag_number_of_failed_subops, and kcenon::pacs::encoding::US.
set_message_id_responded_to()
void kcenon::pacs::network::dimse::dimse_message::set_message_id_responded_to (uint16_t id)
Set the Message ID Being Responded To (for responses)
Parameters
id The message ID being responded to
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 142 of file dimse_message.cpp.
{
    command_set_.set_numeric(tag_message_id_responded_to, encoding::vr_type::US, id);
}
References command_set_, kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::network::dimse::tag_message_id_responded_to, and kcenon::pacs::encoding::US.
Referenced by kcenon::pacs::network::dimse::make_c_echo_rsp(), kcenon::pacs::network::dimse::make_c_find_rsp(), kcenon::pacs::network::dimse::make_c_store_rsp(), kcenon::pacs::network::dimse::make_n_action_rsp(), kcenon::pacs::network::dimse::make_n_create_rsp(), kcenon::pacs::network::dimse::make_n_delete_rsp(), kcenon::pacs::network::dimse::make_n_event_report_rsp(), kcenon::pacs::network::dimse::make_n_get_rsp(), and kcenon::pacs::network::dimse::make_n_set_rsp().
set_priority()
void kcenon::pacs::network::dimse::dimse_message::set_priority (uint16_t priority)
Set the priority.
Parameters
priority The priority value
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 134 of file dimse_message.cpp.
{
    command_set_.set_numeric(tag_priority, encoding::vr_type::US, priority);
}
References command_set_, priority(), kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::network::dimse::tag_priority, and kcenon::pacs::encoding::US.
Referenced by kcenon::pacs::network::dimse::make_c_find_rq(), and kcenon::pacs::network::dimse::make_c_store_rq().
set_remaining_subops()
void kcenon::pacs::network::dimse::dimse_message::set_remaining_subops (uint16_t count)
Set the number of remaining sub-operations.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 230 of file dimse_message.cpp.
{
    command_set_.set_numeric(tag_number_of_remaining_subops, encoding::vr_type::US,
                             count);
}
References command_set_, kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::network::dimse::tag_number_of_remaining_subops, and kcenon::pacs::encoding::US.
set_requested_sop_class_uid()
void kcenon::pacs::network::dimse::dimse_message::set_requested_sop_class_uid (std::string_view uid)
Set the Requested SOP Class UID.
Parameters
uid The SOP Class UID
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 154 of file dimse_message.cpp.
{
    command_set_.set_string(tag_requested_sop_class_uid, encoding::vr_type::UI, uid);
}
References command_set_, kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::network::dimse::tag_requested_sop_class_uid, kcenon::pacs::encoding::UI, and uid.
Referenced by kcenon::pacs::network::dimse::make_n_action_rq(), kcenon::pacs::network::dimse::make_n_delete_rq(), kcenon::pacs::network::dimse::make_n_get_rq(), and kcenon::pacs::network::dimse::make_n_set_rq().
set_requested_sop_instance_uid()
void kcenon::pacs::network::dimse::dimse_message::set_requested_sop_instance_uid (std::string_view uid)
Set the Requested SOP Instance UID.
Parameters
uid The SOP Instance UID
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 162 of file dimse_message.cpp.
{
    command_set_.set_string(tag_requested_sop_instance_uid, encoding::vr_type::UI, uid);
}
References command_set_, kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::network::dimse::tag_requested_sop_instance_uid, kcenon::pacs::encoding::UI, and uid.
Referenced by kcenon::pacs::network::dimse::make_n_action_rq(), kcenon::pacs::network::dimse::make_n_delete_rq(), kcenon::pacs::network::dimse::make_n_get_rq(), and kcenon::pacs::network::dimse::make_n_set_rq().
set_status()
void kcenon::pacs::network::dimse::dimse_message::set_status (status_code status)
Set the status code (for response messages)
Parameters
status The status code to set
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 104 of file dimse_message.cpp.
{
    command_set_.set_numeric(tag_status, encoding::vr_type::US, status);
}
References command_set_, kcenon::pacs::core::dicom_dataset::set_numeric(), status(), kcenon::pacs::network::dimse::tag_status, and kcenon::pacs::encoding::US.
Referenced by kcenon::pacs::network::dimse::make_c_echo_rsp(), kcenon::pacs::network::dimse::make_c_find_rsp(), kcenon::pacs::network::dimse::make_c_store_rsp(), kcenon::pacs::network::dimse::make_n_action_rsp(), kcenon::pacs::network::dimse::make_n_create_rsp(), kcenon::pacs::network::dimse::make_n_delete_rsp(), kcenon::pacs::network::dimse::make_n_event_report_rsp(), kcenon::pacs::network::dimse::make_n_get_rsp(), and kcenon::pacs::network::dimse::make_n_set_rsp().
set_warning_subops()
void kcenon::pacs::network::dimse::dimse_message::set_warning_subops (uint16_t count)
Set the number of warning sub-operations.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 257 of file dimse_message.cpp.
{
    command_set_.set_numeric(tag_number_of_warning_subops, encoding::vr_type::US,
                             count);
}
References command_set_, kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::network::dimse::tag_number_of_warning_subops, and kcenon::pacs::encoding::US.
status()
auto kcenon::pacs::network::dimse::dimse_message::status () const -> status_code nodiscard
Get the status code (for response messages)
Returns
The status code value
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 100 of file dimse_message.cpp.
{
    return command_set_.get_numeric<uint16_t>(tag_status).value_or(0);
}
References command_set_, kcenon::pacs::core::dicom_dataset::get_numeric(), and kcenon::pacs::network::dimse::tag_status.
Referenced by set_status().
update_command_group_length()
void kcenon::pacs::network::dimse::dimse_message::update_command_group_length () private
Calculate and set CommandGroupLength.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 370 of file dimse_message.cpp.
{
    // First, remove CommandGroupLength to calculate without it
    command_set_.remove(tag_command_group_length);
    // Encode command set to get the size
    auto encoded = encoding::implicit_vr_codec::encode(command_set_);
    auto length = static_cast<uint32_t>(encoded.size());
    // Set CommandGroupLength
    command_set_.set_numeric(tag_command_group_length, encoding::vr_type::UL, length);
}
References command_set_, kcenon::pacs::encoding::implicit_vr_codec::encode(), kcenon::pacs::core::dicom_dataset::remove(), kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::network::dimse::tag_command_group_length, and kcenon::pacs::encoding::UL.
Referenced by encode().
update_data_set_type()
void kcenon::pacs::network::dimse::dimse_message::update_data_set_type () private
Update the CommandDataSetType field based on dataset presence.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 360 of file dimse_message.cpp.
{
    if (dataset_) {
        command_set_.set_numeric(tag_command_data_set_type, encoding::vr_type::US,
                                 command_data_set_type_present);
    } else {
        command_set_.set_numeric(tag_command_data_set_type, encoding::vr_type::US,
                                 command_data_set_type_null);
    }
}
References kcenon::pacs::network::dimse::command_data_set_type_null, kcenon::pacs::network::dimse::command_data_set_type_present, command_set_, dataset_, kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::network::dimse::tag_command_data_set_type, and kcenon::pacs::encoding::US.
Referenced by clear_dataset(), dimse_message(), and set_dataset().
warning_subops()
auto kcenon::pacs::network::dimse::dimse_message::warning_subops () const -> std::optional<uint16_t> nodiscard
Get the number of warning sub-operations.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 253 of file dimse_message.cpp.
{
    return command_set_.get_numeric<uint16_t>(tag_number_of_warning_subops);
}
References command_set_, kcenon::pacs::core::dicom_dataset::get_numeric(), and kcenon::pacs::network::dimse::tag_number_of_warning_subops.
Member Data Documentation
command_
command_field kcenon::pacs::network::dimse::dimse_message::command_ {} private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 546 of file dimse_message.h.
{};
Referenced by command(), is_request(), and is_response().
command_set_
core::dicom_dataset kcenon::pacs::network::dimse::dimse_message::command_set_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 548 of file dimse_message.h.
Referenced by action_type_id(), affected_sop_class_uid(), affected_sop_instance_uid(), attribute_identifier_list(), command_set(), command_set(), completed_subops(), decode(), dimse_message(), encode(), event_type_id(), failed_subops(), is_valid(), message_id_responded_to(), priority(), remaining_subops(), requested_sop_class_uid(), requested_sop_instance_uid(), set_action_type_id(), set_affected_sop_class_uid(), set_affected_sop_instance_uid(), set_attribute_identifier_list(), set_completed_subops(), set_event_type_id(), set_failed_subops(), set_message_id_responded_to(), set_priority(), set_remaining_subops(), set_requested_sop_class_uid(), set_requested_sop_instance_uid(), set_status(), set_warning_subops(), status(), update_command_group_length(), update_data_set_type(), and warning_subops().
dataset_
std::optional<core::dicom_dataset> kcenon::pacs::network::dimse::dimse_message::dataset_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 549 of file dimse_message.h.
Referenced by clear_dataset(), dataset(), decode(), has_dataset(), set_dataset(), and update_data_set_type().
message_id_
uint16_t kcenon::pacs::network::dimse::dimse_message::message_id_ {0} private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/network/dimse/dimse_message.h.
Definition at line 547 of file dimse_message.h.
{0};
Referenced by message_id().
The documentation for this class was generated from the following files:
include/kcenon/pacs/network/dimse/dimse_message.h
src/network/dimse/dimse_message.cpp