PACS System: job_tracker Class Reference
job_tracker Class Reference
Tracks active inference jobs.
Public Member Functions
void add_job (const std::string &job_id, const inference_request &request)
void update_status (const std::string &job_id, const inference_status &status)
void remove_job (const std::string &job_id)
std::optional< inference_status > get_status (const std::string &job_id) const
std::vector< inference_status > get_active_jobs () const
Private Attributes
std::shared_mutex mutex_
std::unordered_map< std::string, inference_status > jobs_
std::unordered_map< std::string, inference_request > request_map_
Detailed Description
Tracks active inference jobs.
Definition at line 809 of file ai_service_connector.cpp.
Member Function Documentation
add_job()
void job_tracker::add_job (const std::string & job_id, const inference_request & request) inline
Definition at line 811 of file ai_service_connector.cpp.
{
        std::lock_guard lock(mutex_);
        inference_status status;
        status.job_id = job_id;
        status.status = inference_status_code::pending;
        status.progress = 0;
        status.message = "Job submitted";
        status.created_at = std::chrono::system_clock::now();
        jobs_[job_id] = status;
        request_map_[job_id] = request;
        kcenon::pacs::integration::monitoring_adapter::set_gauge(
            metrics::active_jobs, static_cast<double>(jobs_.size()));
    }
References kcenon::pacs::integration::monitoring_adapter::set_gauge().
get_active_jobs()
std::vector< inference_status > job_tracker::get_active_jobs () const inline nodiscard
Definition at line 877 of file ai_service_connector.cpp.
{
        std::shared_lock lock(mutex_);
        std::vector<inference_status> result;
        for (const auto& [id, status] : jobs_) {
            if (status.status == inference_status_code::pending ||
                status.status == inference_status_code::running) {
                result.push_back(status);
            }
        }
        return result;
    }
get_status()
std::optional< inference_status > job_tracker::get_status (const std::string & job_id) const inline nodiscard
Definition at line 868 of file ai_service_connector.cpp.
{
        std::shared_lock lock(mutex_);
        auto it = jobs_.find(job_id);
        if (it != jobs_.end()) {
            return it->second;
        }
        return std::nullopt;
    }
remove_job()
void job_tracker::remove_job (const std::string & job_id) inline
Definition at line 859 of file ai_service_connector.cpp.
{
        std::lock_guard lock(mutex_);
        jobs_.erase(job_id);
        request_map_.erase(job_id);
        kcenon::pacs::integration::monitoring_adapter::set_gauge(
            metrics::active_jobs, static_cast<double>(jobs_.size()));
    }
References kcenon::pacs::integration::monitoring_adapter::set_gauge().
update_status()
void job_tracker::update_status (const std::string & job_id, const inference_status & status) inline
Definition at line 828 of file ai_service_connector.cpp.
{
        std::lock_guard lock(mutex_);
        auto it = jobs_.find(job_id);
        if (it != jobs_.end()) {
            it->second = status;
            // If job completed or failed, record metrics
            if (status.status == inference_status_code::completed ||
                status.status == inference_status_code::failed) {
                // Note: request_map_ entry may be used for future logging
                (void)request_map_[job_id];
                auto duration = status.completed_at.value_or(std::chrono::system_clock::now())
                              - status.created_at;
                kcenon::pacs::integration::monitoring_adapter::record_timing(
                    metrics::inference_duration,
                    std::chrono::duration_cast<std::chrono::nanoseconds>(duration));
                if (status.status == inference_status_code::completed) {
                    kcenon::pacs::integration::monitoring_adapter::increment_counter(
                        metrics::inference_requests_success);
                } else {
                    kcenon::pacs::integration::monitoring_adapter::increment_counter(
                        metrics::inference_requests_failed);
                }
            }
        }
    }
References kcenon::pacs::integration::monitoring_adapter::increment_counter(), and kcenon::pacs::integration::monitoring_adapter::record_timing().
Member Data Documentation
jobs_
std::unordered_map<std::string, inference_status> job_tracker::jobs_ private
Definition at line 891 of file ai_service_connector.cpp.
mutex_
std::shared_mutex job_tracker::mutex_ mutable private
Definition at line 890 of file ai_service_connector.cpp.
request_map_
std::unordered_map<std::string, inference_request> job_tracker::request_map_ private
Definition at line 892 of file ai_service_connector.cpp.
The documentation for this class was generated from the following file:
src/ai/ai_service_connector.cpp