PACS System: kcenon::pacs::integration_test::dcmtk_server_guard Class Reference
kcenon::pacs::integration_test::dcmtk_server_guard Class Reference
RAII guard for DCMTK server processes.
#include <dcmtk_tool.h>
Public Member Functions
dcmtk_server_guard (const std::string &tool_name, uint16_t port, const std::vector< std::string > &args)
Construct a server guard.
~dcmtk_server_guard ()
dcmtk_server_guard (const dcmtk_server_guard &)=delete
dcmtk_server_guard & operator= (const dcmtk_server_guard &)=delete
dcmtk_server_guard (dcmtk_server_guard &&other) noexcept
dcmtk_server_guard & operator= (dcmtk_server_guard &&other) noexcept
bool wait_for_ready (std::chrono::seconds timeout=std::chrono::seconds{10}) const
Wait for the server to be ready (accepting connections)
void stop ()
Stop the server.
bool is_running () const
uint16_t port () const noexcept
process_launcher::pid_type pid () const noexcept
Static Private Member Functions
static std::string find_tool_path (const std::string &tool_name)
Private Attributes
background_process_guard process_
uint16_t port_ {0}
Detailed Description
RAII guard for DCMTK server processes.
Provides lifecycle management for DCMTK server processes with automatic cleanup on destruction.
Definition at line 415 of file dcmtk_tool.h.
Constructor & Destructor Documentation
dcmtk_server_guard() [1/3]
kcenon::pacs::integration_test::dcmtk_server_guard::dcmtk_server_guard (const std::string & tool_name, uint16_t port, const std::vector< std::string > & args) inline
Construct a server guard.
Parameters
tool_name Name of the DCMTK server tool
port Port the server is listening on
args Command-line arguments
Definition at line 423 of file dcmtk_tool.h.
        : port_(port) {
        // Build full command path
        std::string tool_path = find_tool_path(tool_name);
        auto pid = process_launcher::start_background(tool_path, args);
        process_.set_pid(pid);
    }
References find_tool_path(), pid(), process_, kcenon::pacs::integration_test::background_process_guard::set_pid(), and kcenon::pacs::integration_test::process_launcher::start_background().
~dcmtk_server_guard()
kcenon::pacs::integration_test::dcmtk_server_guard::~dcmtk_server_guard () inline
Definition at line 435 of file dcmtk_tool.h.
{
        stop();
    }
References stop().
dcmtk_server_guard() [2/3]
kcenon::pacs::integration_test::dcmtk_server_guard::dcmtk_server_guard (const dcmtk_server_guard &) delete
dcmtk_server_guard() [3/3]
kcenon::pacs::integration_test::dcmtk_server_guard::dcmtk_server_guard (dcmtk_server_guard && other) inline noexcept
Definition at line 444 of file dcmtk_tool.h.
        : process_(std::move(other.process_))
        , port_(other.port_) {
        other.port_ = 0;
    }
Member Function Documentation
find_tool_path()
static std::string kcenon::pacs::integration_test::dcmtk_server_guard::find_tool_path (const std::string & tool_name) inline static private
Definition at line 492 of file dcmtk_tool.h.
{
        std::vector<std::string> search_paths = {
            "/usr/local/bin",
            "/usr/bin",
            "/opt/homebrew/bin",
            "/opt/local/bin"
        };
        for (const auto& path : search_paths) {
            std::filesystem::path full_path = std::filesystem::path(path) / tool_name;
            if (std::filesystem::exists(full_path)) {
                return full_path.string();
            }
        }
        return tool_name;
    }
Referenced by dcmtk_server_guard().
is_running()
bool kcenon::pacs::integration_test::dcmtk_server_guard::is_running () const inline nodiscard
Returns
true if server process is running
Definition at line 479 of file dcmtk_tool.h.
{
        return process_.is_running();
    }
References kcenon::pacs::integration_test::background_process_guard::is_running(), and process_.
Referenced by TEST_CASE().
operator=() [1/2]
dcmtk_server_guard & kcenon::pacs::integration_test::dcmtk_server_guard::operator= (const dcmtk_server_guard &) delete
operator=() [2/2]
dcmtk_server_guard & kcenon::pacs::integration_test::dcmtk_server_guard::operator= (dcmtk_server_guard && other) inline noexcept
Definition at line 450 of file dcmtk_tool.h.
{
        if (this != &other) {
            stop();
            process_ = std::move(other.process_);
            port_ = other.port_;
            other.port_ = 0;
        }
        return *this;
    }
References port_, process_, and stop().
pid()
process_launcher::pid_type kcenon::pacs::integration_test::dcmtk_server_guard::pid () const inline nodiscard noexcept
Returns
Process ID
Definition at line 487 of file dcmtk_tool.h.
{
        return process_.pid();
    }
References kcenon::pacs::integration_test::background_process_guard::pid(), and process_.
Referenced by dcmtk_server_guard(), and TEST_CASE().
port()
uint16_t kcenon::pacs::integration_test::dcmtk_server_guard::port () const inline nodiscard noexcept
Returns
Server port
Definition at line 484 of file dcmtk_tool.h.
{ return port_; }
References port_.
stop()
void kcenon::pacs::integration_test::dcmtk_server_guard::stop () inline
Stop the server.
Definition at line 474 of file dcmtk_tool.h.
                {
        process_.stop();
    }
References process_, and kcenon::pacs::integration_test::background_process_guard::stop().
Referenced by operator=(), and ~dcmtk_server_guard().
wait_for_ready()
bool kcenon::pacs::integration_test::dcmtk_server_guard::wait_for_ready (std::chrono::seconds timeout = std::chrono::seconds{10}) const inline nodiscard
Wait for the server to be ready (accepting connections)
Parameters
timeout Maximum wait time
Returns
true if server is ready
Definition at line 465 of file dcmtk_tool.h.
                                                   {10}) const {
        return process_launcher::wait_for_port(port_, timeout);
    }
Member Data Documentation
port_
uint16_t kcenon::pacs::integration_test::dcmtk_server_guard::port_ {0} private
Definition at line 511 of file dcmtk_tool.h.
{0};
Referenced by operator=(), and port().
process_
background_process_guard kcenon::pacs::integration_test::dcmtk_server_guard::process_ private
Definition at line 510 of file dcmtk_tool.h.
Referenced by dcmtk_server_guard(), is_running(), operator=(), pid(), and stop().
The documentation for this class was generated from the following file:
examples/integration_tests/dcmtk_tool.h