PACS System: kcenon::pacs::integration_test::test_directory Class Reference
kcenon::pacs::integration_test::test_directory Class Reference
RAII wrapper for temporary test directory.
#include <test_fixtures.h>
Public Member Functions
test_directory (const std::string &prefix="pacs_test_")
~test_directory ()
test_directory (const test_directory &)=delete
test_directory & operator= (const test_directory &)=delete
test_directory (test_directory &&)=delete
test_directory & operator= (test_directory &&)=delete
const std::filesystem::path & path () const noexcept
std::string string () const
Private Attributes
std::filesystem::path path_
Detailed Description
RAII wrapper for temporary test directory.
Definition at line 775 of file test_fixtures.h.
Constructor & Destructor Documentation
test_directory() [1/3]
kcenon::pacs::integration_test::test_directory::test_directory (const std::string & prefix = "pacs_test_") inline explicit
Definition at line 777 of file test_fixtures.h.
{
        auto temp_base = std::filesystem::temp_directory_path();
        path_ = temp_base / (prefix + std::to_string(
            std::chrono::system_clock::now().time_since_epoch().count()));
        std::filesystem::create_directories(path_);
    }
References path_.
~test_directory()
kcenon::pacs::integration_test::test_directory::~test_directory () inline
Definition at line 784 of file test_fixtures.h.
                      {
        if (std::filesystem::exists(path_)) {
            std::filesystem::remove_all(path_);
        }
    }
References path_.
test_directory() [2/3]
kcenon::pacs::integration_test::test_directory::test_directory (const test_directory &) delete
test_directory() [3/3]
kcenon::pacs::integration_test::test_directory::test_directory (test_directory &&) delete
Member Function Documentation
operator=() [1/2]
test_directory & kcenon::pacs::integration_test::test_directory::operator= (const test_directory &) delete
operator=() [2/2]
test_directory & kcenon::pacs::integration_test::test_directory::operator= (test_directory &&) delete
path()
const std::filesystem::path & kcenon::pacs::integration_test::test_directory::path () const inline nodiscard noexcept
Returns
Path to test directory
Definition at line 797 of file test_fixtures.h.
{ return path_; }
References path_.
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
string()
std::string kcenon::pacs::integration_test::test_directory::string () const inline nodiscard
Returns
Path as string
Definition at line 800 of file test_fixtures.h.
{ return path_.string(); }
References path_.
Member Data Documentation
path_
std::filesystem::path kcenon::pacs::integration_test::test_directory::path_ private
Definition at line 803 of file test_fixtures.h.
Referenced by path(), string(), test_directory(), and ~test_directory().
The documentation for this class was generated from the following file:
examples/integration_tests/test_fixtures.h