PACS System: kcenon::pacs::client::sync_manager Class Reference
kcenon::pacs::client::sync_manager Class Reference
#include <sync_manager.h>
Classes
struct impl
Public Member Functions
sync_manager (sync_repositories repositories, std::shared_ptr< remote_node_manager > node_manager, std::shared_ptr< job_manager > job_manager, std::shared_ptr< services::query_scu > query_scu, std::shared_ptr< di::ILogger > logger=nullptr)
Construct a sync manager from split repositories.
sync_manager (const sync_manager_config &config, sync_repositories repositories, std::shared_ptr< remote_node_manager > node_manager, std::shared_ptr< job_manager > job_manager, std::shared_ptr< services::query_scu > query_scu, std::shared_ptr< di::ILogger > logger=nullptr)
Construct a sync manager from split repositories with custom configuration.
sync_manager (std::shared_ptr< storage::sync_repository > repo, std::shared_ptr< remote_node_manager > node_manager, std::shared_ptr< job_manager > job_manager, std::shared_ptr< services::query_scu > query_scu, std::shared_ptr< di::ILogger > logger=nullptr)
Construct a sync manager with default configuration.
sync_manager (const sync_manager_config &config, std::shared_ptr< storage::sync_repository > repo, std::shared_ptr< remote_node_manager > node_manager, std::shared_ptr< job_manager > job_manager, std::shared_ptr< services::query_scu > query_scu, std::shared_ptr< di::ILogger > logger=nullptr)
Construct a sync manager with custom configuration.
~sync_manager ()
Destructor - stops scheduler if running.
sync_manager (const sync_manager &)=delete
auto operator= (const sync_manager &) -> sync_manager &=delete
sync_manager (sync_manager &&)=delete
auto operator= (sync_manager &&) -> sync_manager &=delete
auto add_config (const sync_config &config) -> kcenon::pacs::VoidResult
Add a new sync configuration.
auto update_config (const sync_config &config) -> kcenon::pacs::VoidResult
Update an existing sync configuration.
auto remove_config (std::string_view config_id) -> kcenon::pacs::VoidResult
Remove a sync configuration.
auto get_config (std::string_view config_id) const -> std::optional< sync_config >
Get a sync configuration by ID.
auto list_configs () const -> std::vector< sync_config >
List all sync configurations.
auto sync_now (std::string_view config_id) -> std::string
Start sync immediately for a configuration.
auto full_sync (std::string_view config_id) -> std::string
Perform a full sync for a configuration.
auto incremental_sync (std::string_view config_id) -> std::string
Perform an incremental sync for a configuration.
auto wait_for_sync (std::string_view job_id) -> std::future< sync_result >
Wait for a sync operation to complete.
auto compare (std::string_view config_id) -> sync_result
Compare local and remote data without syncing.
auto compare_async (std::string_view config_id) -> std::future< sync_result >
Compare local and remote data asynchronously.
auto get_conflicts () const -> std::vector< sync_conflict >
Get all unresolved conflicts.
auto get_conflicts (std::string_view config_id) const -> std::vector< sync_conflict >
Get unresolved conflicts for a specific configuration.
auto resolve_conflict (std::string_view study_uid, conflict_resolution resolution) -> kcenon::pacs::VoidResult
Resolve a specific conflict.
auto resolve_all_conflicts (std::string_view config_id, conflict_resolution resolution) -> kcenon::pacs::VoidResult
Resolve all conflicts for a configuration.
void start_scheduler ()
Start the sync scheduler.
void stop_scheduler ()
Stop the sync scheduler.
auto is_scheduler_running () const noexcept -> bool
Check if scheduler is running.
auto is_syncing (std::string_view config_id) const -> bool
Check if a sync is currently running for a configuration.
auto get_last_result (std::string_view config_id) const -> sync_result
Get the last sync result for a configuration.
auto get_statistics () const -> sync_statistics
Get overall sync statistics.
auto get_statistics (std::string_view config_id) const -> sync_statistics
Get statistics for a specific configuration.
void set_progress_callback (sync_progress_callback callback)
Set callback for sync progress updates.
void set_completion_callback (sync_completion_callback callback)
Set callback for sync completion.
void set_conflict_callback (sync_conflict_callback callback)
Set callback for conflict detection.
auto config () const noexcept -> const sync_manager_config &
Get current manager configuration.
Private Attributes
std::unique_ptr< impl > impl_
Detailed Description
Definition at line 102 of file sync_manager.h.
Constructor & Destructor Documentation
sync_manager() [1/6]
kcenon::pacs::client::sync_manager::sync_manager (sync_repositories repositories, std::shared_ptr< remote_node_manager > node_manager, std::shared_ptr< job_manager > job_manager, std::shared_ptr< services::query_scu > query_scu, std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct a sync manager from split repositories.
Parameters
repositories Split sync repositories for configs, conflicts, and history
node_manager Remote node manager (required)
job_manager Job manager for async operations (required)
query_scu Query SCU for study comparisons (required)
logger Logger instance (optional)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 733 of file sync_manager.cpp.
    : sync_manager(sync_manager_config{}, std::move(repositories),
                   std::move(node_manager), std::move(job_manager),
                   std::move(query_scu), std::move(logger)) {}
sync_manager() [2/6]
kcenon::pacs::client::sync_manager::sync_manager (const sync_manager_config & config, sync_repositories repositories, std::shared_ptr< remote_node_manager > node_manager, std::shared_ptr< job_manager > job_manager, std::shared_ptr< services::query_scu > query_scu, std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct a sync manager from split repositories with custom configuration.
Parameters
config Manager configuration
repositories Split sync repositories for configs, conflicts, and history
node_manager Remote node manager (required)
job_manager Job manager for async operations (required)
query_scu Query SCU for study comparisons (required)
logger Logger instance (optional)
Definition at line 743 of file sync_manager.cpp.
    : impl_(std::make_unique<impl>()) {
    impl_->config = config;
    impl_->repositories = std::move(repositories);
    impl_->node_manager = std::move(node_manager);
    impl_->job_mgr = std::move(job_manager);
    impl_->query_scu = std::move(query_scu);
    impl_->logger = logger ? std::move(logger) : di::null_logger();
    impl_->load_configs_from_repo();
    impl_->load_conflicts_from_repo();
}
References config(), kcenon::pacs::client::sync_manager::impl::config, impl_, kcenon::pacs::client::sync_manager::impl::job_mgr, kcenon::pacs::client::sync_manager::impl::load_configs_from_repo(), kcenon::pacs::client::sync_manager::impl::load_conflicts_from_repo(), kcenon::pacs::client::sync_manager::impl::logger, kcenon::pacs::client::sync_manager::impl::node_manager, kcenon::pacs::di::null_logger(), kcenon::pacs::client::sync_manager::impl::query_scu, and kcenon::pacs::client::sync_manager::impl::repositories.
sync_manager() [3/6]
kcenon::pacs::client::sync_manager::sync_manager (std::shared_ptr< storage::sync_repository > repo, std::shared_ptr< remote_node_manager > node_manager, std::shared_ptr< job_manager > job_manager, std::shared_ptr< services::query_scu > query_scu, std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct a sync manager with default configuration.
Compatibility-only overload. Prefer split repositories for new wiring.
Parameters
repo Sync repository for persistence (required)
node_manager Remote node manager (required)
job_manager Job manager for async operations (required)
query_scu Query SCU for study comparisons (required)
logger Logger instance (optional)
Definition at line 763 of file sync_manager.cpp.
    : sync_manager(sync_manager_config{}, std::move(repo), std::move(node_manager),
                   std::move(job_manager), std::move(query_scu), std::move(logger)) {
}
sync_manager() [4/6]
kcenon::pacs::client::sync_manager::sync_manager (const sync_manager_config & config, std::shared_ptr< storage::sync_repository > repo, std::shared_ptr< remote_node_manager > node_manager, std::shared_ptr< job_manager > job_manager, std::shared_ptr< services::query_scu > query_scu, std::shared_ptr< di::ILogger > logger = nullptr) explicit
Construct a sync manager with custom configuration.
Compatibility-only overload. Prefer split repositories for new wiring.
Parameters
config Manager configuration
repo Sync repository for persistence (required)
node_manager Remote node manager (required)
job_manager Job manager for async operations (required)
query_scu Query SCU for study comparisons (required)
logger Logger instance (optional)
Definition at line 773 of file sync_manager.cpp.
    : impl_(std::make_unique<impl>()) {
    impl_->config = config;
    impl_->compatibility_repo = std::move(repo);
    impl_->node_manager = std::move(node_manager);
    impl_->job_mgr = std::move(job_manager);
    impl_->query_scu = std::move(query_scu);
    impl_->logger = logger ? std::move(logger) : di::null_logger();
    impl_->load_configs_from_repo();
    impl_->load_conflicts_from_repo();
}
References kcenon::pacs::client::sync_manager::impl::compatibility_repo, config(), kcenon::pacs::client::sync_manager::impl::config, impl_, kcenon::pacs::client::sync_manager::impl::job_mgr, kcenon::pacs::client::sync_manager::impl::load_configs_from_repo(), kcenon::pacs::client::sync_manager::impl::load_conflicts_from_repo(), kcenon::pacs::client::sync_manager::impl::logger, kcenon::pacs::client::sync_manager::impl::node_manager, kcenon::pacs::di::null_logger(), and kcenon::pacs::client::sync_manager::impl::query_scu.
~sync_manager()
kcenon::pacs::client::sync_manager::~sync_manager ()
Destructor - stops scheduler if running.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 793 of file sync_manager.cpp.
{
    stop_scheduler();
}
References stop_scheduler().
sync_manager() [5/6]
kcenon::pacs::client::sync_manager::sync_manager (const sync_manager &) delete
sync_manager() [6/6]
kcenon::pacs::client::sync_manager::sync_manager (sync_manager &&) delete
Member Function Documentation
add_config()
kcenon::pacs::VoidResult kcenon::pacs::client::sync_manager::add_config (const sync_config & config) -> kcenon::pacs::VoidResult nodiscard
Add a new sync configuration.
Parameters
config The configuration to add
Returns
VoidResult indicating success or error
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 801 of file sync_manager.cpp.
{
    if (config.config_id.empty()) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::invalid_argument,
            "Config ID cannot be empty");
    }
    if (config.source_node_id.empty()) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::invalid_argument,
            "Source node ID cannot be empty");
    }
    // Check for duplicate
    if (impl_->get_config_from_cache(config.config_id).has_value()) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::already_exists,
            "Config already exists: " + config.config_id);
    }
    impl_->save_config(config);
    if (impl_->logger) {
        impl_->logger->info_fmt("Added sync config '{}' for node '{}'",
            config.config_id, config.source_node_id);
    }
    return kcenon::pacs::ok();
}
References config(), kcenon::pacs::client::sync_manager::impl::get_config_from_cache(), impl_, kcenon::pacs::client::sync_manager::impl::logger, kcenon::pacs::pacs_void_error(), and kcenon::pacs::client::sync_manager::impl::save_config().
compare()
sync_result kcenon::pacs::client::sync_manager::compare (std::string_view config_id) -> sync_result nodiscard
Compare local and remote data without syncing.
Returns a sync_result showing what would be synced.
Parameters
config_id The configuration ID to compare
Returns
Sync result with comparison data
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 959 of file sync_manager.cpp.
{
    sync_result result;
    result.config_id = std::string(config_id);
    result.started_at = std::chrono::system_clock::now();
    auto config_opt = impl_->get_config_from_cache(config_id);
    if (!config_opt) {
        result.errors.push_back("Config not found: " + std::string(config_id));
        result.completed_at = std::chrono::system_clock::now();
        return result;
    }
    const auto& cfg = *config_opt;
    // Query remote studies
    auto sync_start_time = std::chrono::system_clock::now() - cfg.lookback;
    auto remote_studies = impl_->query_remote_studies(cfg, sync_start_time, result);
    if (!result.errors.empty()) {
        result.completed_at = std::chrono::system_clock::now();
        return result;
    }
    result.studies_checked = remote_studies.size();
    // Compare with local
    auto conflicts = impl_->compare_with_local(cfg, remote_studies, result);
    result.conflicts = conflicts;
    result.success = true;
    result.completed_at = std::chrono::system_clock::now();
    result.elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
        result.completed_at - result.started_at);
    return result;
}
References kcenon::pacs::client::sync_manager::impl::compare_with_local(), kcenon::pacs::client::sync_result::completed_at, kcenon::pacs::client::sync_result::config_id, kcenon::pacs::client::sync_result::conflicts, kcenon::pacs::client::sync_result::elapsed, kcenon::pacs::client::sync_result::errors, kcenon::pacs::client::sync_manager::impl::get_config_from_cache(), impl_, kcenon::pacs::client::sync_manager::impl::query_remote_studies(), kcenon::pacs::client::sync_result::started_at, kcenon::pacs::client::sync_result::studies_checked, and kcenon::pacs::client::sync_result::success.
Referenced by compare_async().
compare_async()
std::future< sync_result > kcenon::pacs::client::sync_manager::compare_async (std::string_view config_id) -> std::future<sync_result> nodiscard
Compare local and remote data asynchronously.
Parameters
config_id The configuration ID to compare
Returns
Future containing the comparison result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 996 of file sync_manager.cpp.
{
    return std::async(std::launch::async, [this, id = std::string(config_id)]() {
        return compare(id);
    });
}
References compare().
config()
const sync_manager_config & kcenon::pacs::client::sync_manager::config () const -> const sync_manager_config& nodiscard noexcept
Get current manager configuration.
Returns
Current configuration
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 1225 of file sync_manager.cpp.
{
    return impl_->config;
}
References kcenon::pacs::client::sync_manager::impl::config, and impl_.
Referenced by add_config(), sync_manager(), sync_manager(), and update_config().
full_sync()
std::string kcenon::pacs::client::sync_manager::full_sync (std::string_view config_id) -> std::string nodiscard
Perform a full sync for a configuration.
Syncs all data within the lookback period, ignoring last sync time.
Parameters
config_id The configuration ID to sync
Returns
Job ID for tracking progress
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 915 of file sync_manager.cpp.
{
    auto config_opt = impl_->get_config_from_cache(config_id);
    if (!config_opt) {
        return "";
    }
    impl_->mark_sync_active(config_id);
    auto result = impl_->perform_sync(*config_opt, true);
    impl_->mark_sync_inactive(config_id);
    impl_->notify_completion(std::string(config_id), result);
    return result.job_id;
}
References kcenon::pacs::client::sync_manager::impl::get_config_from_cache(), impl_, kcenon::pacs::client::sync_manager::impl::mark_sync_active(), kcenon::pacs::client::sync_manager::impl::mark_sync_inactive(), kcenon::pacs::client::sync_manager::impl::notify_completion(), and kcenon::pacs::client::sync_manager::impl::perform_sync().
Referenced by kcenon::pacs::client::sync_manager::impl::perform_sync().
get_config()
std::optional< sync_config > kcenon::pacs::client::sync_manager::get_config (std::string_view config_id) const -> std::optional<sync_config> nodiscard
Get a sync configuration by ID.
Parameters
config_id The configuration ID to retrieve
Returns
Optional containing the config if found
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 884 of file sync_manager.cpp.
{
    return impl_->get_config_from_cache(config_id);
}
References kcenon::pacs::client::sync_manager::impl::get_config_from_cache(), and impl_.
get_conflicts() [1/2]
std::vector< sync_conflict > kcenon::pacs::client::sync_manager::get_conflicts () const -> std::vector<sync_conflict> nodiscard
Get all unresolved conflicts.
Returns
Vector of all unresolved conflicts
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 1006 of file sync_manager.cpp.
{
    std::lock_guard lock(impl_->conflicts_mutex);
    std::vector<sync_conflict> unresolved;
    std::copy_if(impl_->conflicts.begin(), impl_->conflicts.end(),
                 std::back_inserter(unresolved),
                 [](const sync_conflict& c) { return !c.resolved; });
    return unresolved;
}
References kcenon::pacs::client::sync_manager::impl::conflicts, kcenon::pacs::client::sync_manager::impl::conflicts_mutex, and impl_.
get_conflicts() [2/2]
std::vector< sync_conflict > kcenon::pacs::client::sync_manager::get_conflicts (std::string_view config_id) const -> std::vector<sync_conflict> nodiscard
Get unresolved conflicts for a specific configuration.
Parameters
config_id The configuration ID
Returns
Vector of unresolved conflicts for that config
Definition at line 1015 of file sync_manager.cpp.
{
    std::lock_guard lock(impl_->conflicts_mutex);
    std::vector<sync_conflict> filtered;
    std::copy_if(impl_->conflicts.begin(), impl_->conflicts.end(),
                 std::back_inserter(filtered),
                 [&config_id](const sync_conflict& c) {
                     return !c.resolved && c.config_id == config_id;
                 });
    return filtered;
}
References kcenon::pacs::client::sync_manager::impl::conflicts, kcenon::pacs::client::sync_manager::impl::conflicts_mutex, and impl_.
get_last_result()
sync_result kcenon::pacs::client::sync_manager::get_last_result (std::string_view config_id) const -> sync_result nodiscard
Get the last sync result for a configuration.
Parameters
config_id The configuration ID
Returns
Last sync result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 1152 of file sync_manager.cpp.
{
    std::shared_lock lock(impl_->results_mutex);
    auto it = impl_->last_results.find(std::string(config_id));
    if (it != impl_->last_results.end()) {
        return it->second;
    }
    return sync_result{};
}
References impl_, kcenon::pacs::client::sync_manager::impl::last_results, and kcenon::pacs::client::sync_manager::impl::results_mutex.
get_statistics() [1/2]
sync_statistics kcenon::pacs::client::sync_manager::get_statistics () const -> sync_statistics nodiscard
Get overall sync statistics.
Returns
Aggregate statistics for all sync operations
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 1165 of file sync_manager.cpp.
{
    sync_statistics stats;
    stats.total_syncs = impl_->total_syncs.load(std::memory_order_relaxed);
    stats.successful_syncs = impl_->successful_syncs.load(std::memory_order_relaxed);
    stats.failed_syncs = impl_->failed_syncs.load(std::memory_order_relaxed);
    stats.total_studies_synced = impl_->total_studies_synced.load(std::memory_order_relaxed);
    stats.total_bytes_transferred = impl_->total_bytes_transferred.load(std::memory_order_relaxed);
    stats.total_conflicts_detected = impl_->total_conflicts_detected.load(std::memory_order_relaxed);
    stats.total_conflicts_resolved = impl_->total_conflicts_resolved.load(std::memory_order_relaxed);
    return stats;
}
References kcenon::pacs::client::sync_manager::impl::failed_syncs, impl_, kcenon::pacs::client::sync_manager::impl::successful_syncs, kcenon::pacs::client::sync_manager::impl::total_bytes_transferred, kcenon::pacs::client::sync_manager::impl::total_conflicts_detected, kcenon::pacs::client::sync_manager::impl::total_conflicts_resolved, kcenon::pacs::client::sync_manager::impl::total_studies_synced, and kcenon::pacs::client::sync_manager::impl::total_syncs.
get_statistics() [2/2]
sync_statistics kcenon::pacs::client::sync_manager::get_statistics (std::string_view config_id) const -> sync_statistics nodiscard
Get statistics for a specific configuration.
Parameters
config_id The configuration ID
Returns
Statistics for that configuration
Definition at line 1177 of file sync_manager.cpp.
{
    sync_statistics stats;
    auto config_opt = impl_->get_config_from_cache(config_id);
    if (config_opt) {
        stats.total_syncs = config_opt->total_syncs;
        stats.total_studies_synced = config_opt->studies_synced;
    }
    // Count conflicts for this config
    {
        std::lock_guard lock(impl_->conflicts_mutex);
        for (const auto& c : impl_->conflicts) {
            if (c.config_id == config_id) {
                stats.total_conflicts_detected++;
                if (c.resolved) {
                    stats.total_conflicts_resolved++;
                }
            }
        }
    }
    return stats;
}
References kcenon::pacs::client::sync_manager::impl::conflicts, kcenon::pacs::client::sync_manager::impl::conflicts_mutex, kcenon::pacs::client::sync_manager::impl::get_config_from_cache(), and impl_.
incremental_sync()
std::string kcenon::pacs::client::sync_manager::incremental_sync (std::string_view config_id) -> std::string nodiscard
Perform an incremental sync for a configuration.
Only syncs data modified since the last successful sync.
Parameters
config_id The configuration ID to sync
Returns
Job ID for tracking progress
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 929 of file sync_manager.cpp.
{
    auto config_opt = impl_->get_config_from_cache(config_id);
    if (!config_opt) {
        return "";
    }
    impl_->mark_sync_active(config_id);
    auto result = impl_->perform_sync(*config_opt, false);
    impl_->mark_sync_inactive(config_id);
    impl_->notify_completion(std::string(config_id), result);
    return result.job_id;
}
References kcenon::pacs::client::sync_manager::impl::get_config_from_cache(), impl_, kcenon::pacs::client::sync_manager::impl::mark_sync_active(), kcenon::pacs::client::sync_manager::impl::mark_sync_inactive(), kcenon::pacs::client::sync_manager::impl::notify_completion(), and kcenon::pacs::client::sync_manager::impl::perform_sync().
is_scheduler_running()
bool kcenon::pacs::client::sync_manager::is_scheduler_running () const -> bool nodiscard noexcept
Check if scheduler is running.
Returns
true if scheduler is active
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 1140 of file sync_manager.cpp.
{
    return impl_->scheduler_running.load();
}
References impl_, and kcenon::pacs::client::sync_manager::impl::scheduler_running.
is_syncing()
bool kcenon::pacs::client::sync_manager::is_syncing (std::string_view config_id) const -> bool nodiscard
Check if a sync is currently running for a configuration.
Parameters
config_id The configuration ID to check
Returns
true if sync is in progress
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 1148 of file sync_manager.cpp.
{
    return impl_->is_sync_active(config_id);
}
References impl_, and kcenon::pacs::client::sync_manager::impl::is_sync_active().
list_configs()
std::vector< sync_config > kcenon::pacs::client::sync_manager::list_configs () const -> std::vector<sync_config> nodiscard
List all sync configurations.
Returns
Vector of all configurations
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 888 of file sync_manager.cpp.
{
    std::shared_lock lock(impl_->configs_mutex);
    return impl_->configs;
}
References kcenon::pacs::client::sync_manager::impl::configs, kcenon::pacs::client::sync_manager::impl::configs_mutex, and impl_.
operator=() [1/2]
auto kcenon::pacs::client::sync_manager::operator= (const sync_manager &) -> sync_manager &=delete delete
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
operator=() [2/2]
auto kcenon::pacs::client::sync_manager::operator= (sync_manager &&) -> sync_manager &=delete delete
remove_config()
kcenon::pacs::VoidResult kcenon::pacs::client::sync_manager::remove_config (std::string_view config_id) -> kcenon::pacs::VoidResult nodiscard
Remove a sync configuration.
Parameters
config_id The ID of the configuration to remove
Returns
VoidResult indicating success or error
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 847 of file sync_manager.cpp.
{
    {
        std::unique_lock lock(impl_->configs_mutex);
        auto it = std::find_if(impl_->configs.begin(), impl_->configs.end(),
            [&config_id](const sync_config& c) {
                return c.config_id == config_id;
            });
        if (it == impl_->configs.end()) {
            return kcenon::pacs::pacs_void_error(
                kcenon::pacs::error_codes::not_found,
                "Config not found: " + std::string(config_id));
        }
        impl_->configs.erase(it);
    }
    #ifdef PACS_WITH_DATABASE_SYSTEM
    if (impl_->repositories.configs) {
        [[maybe_unused]] auto result =
            impl_->repositories.configs->remove(std::string(config_id));
    } else if (impl_->compatibility_repo) {
        [[maybe_unused]] auto result =
            impl_->compatibility_repo->remove_config(config_id);
    }
    #else
    if (impl_->compatibility_repo) {
        [[maybe_unused]] auto result =
            impl_->compatibility_repo->remove_config(config_id);
    }
    #endif
    if (impl_->logger) {
        impl_->logger->info_fmt("Removed sync config '{}'", config_id);
    }
    return kcenon::pacs::ok();
}
References kcenon::pacs::client::sync_manager::impl::compatibility_repo, kcenon::pacs::client::sync_manager::impl::configs, kcenon::pacs::client::sync_repositories::configs, kcenon::pacs::client::sync_manager::impl::configs_mutex, impl_, kcenon::pacs::client::sync_manager::impl::logger, kcenon::pacs::pacs_void_error(), and kcenon::pacs::client::sync_manager::impl::repositories.
resolve_all_conflicts()
kcenon::pacs::VoidResult kcenon::pacs::client::sync_manager::resolve_all_conflicts (std::string_view config_id, conflict_resolution resolution) -> kcenon::pacs::VoidResult nodiscard
Resolve all conflicts for a configuration.
Parameters
config_id The configuration ID
resolution How to resolve all conflicts
Returns
VoidResult indicating success or error
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 1074 of file sync_manager.cpp.
{
    std::vector<std::string> study_uids;
    {
        std::lock_guard lock(impl_->conflicts_mutex);
        for (const auto& c : impl_->conflicts) {
            if (c.config_id == config_id && !c.resolved) {
                study_uids.push_back(c.study_uid);
            }
        }
    }
    for (const auto& uid : study_uids) {
        auto result = resolve_conflict(uid, resolution);
        if (result.is_err()) {
            return result;
        }
    }
    if (impl_->logger) {
        impl_->logger->info_fmt("Resolved {} conflicts for config '{}'",
            study_uids.size(), config_id);
    }
    return kcenon::pacs::ok();
}
References kcenon::pacs::client::sync_manager::impl::conflicts, kcenon::pacs::client::sync_manager::impl::conflicts_mutex, impl_, kcenon::pacs::client::sync_manager::impl::logger, resolve_conflict(), and uid.
resolve_conflict()
kcenon::pacs::VoidResult kcenon::pacs::client::sync_manager::resolve_conflict (std::string_view study_uid, conflict_resolution resolution) -> kcenon::pacs::VoidResult nodiscard
Resolve a specific conflict.
Parameters
study_uid The Study Instance UID of the conflict
resolution How to resolve the conflict
Returns
VoidResult indicating success or error
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 1026 of file sync_manager.cpp.
{
    std::lock_guard lock(impl_->conflicts_mutex);
    auto it = std::find_if(impl_->conflicts.begin(), impl_->conflicts.end(),
        [&study_uid](const sync_conflict& c) {
            return c.study_uid == study_uid && !c.resolved;
        });
    if (it == impl_->conflicts.end()) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::not_found,
            "Conflict not found: " + std::string(study_uid));
    }
    // Apply resolution
    sync_result dummy_result;
    impl_->resolve_conflict_internal(*it, resolution, dummy_result);
    it->resolved = true;
    it->resolution_used = resolution;
    it->resolved_at = std::chrono::system_clock::now();
    #ifdef PACS_WITH_DATABASE_SYSTEM
    if (impl_->repositories.conflicts) {
        [[maybe_unused]] auto result =
            impl_->repositories.conflicts->resolve(study_uid, resolution);
    } else if (impl_->compatibility_repo) {
        [[maybe_unused]] auto result =
            impl_->compatibility_repo->resolve_conflict(study_uid, resolution);
    }
    #else
    if (impl_->compatibility_repo) {
        [[maybe_unused]] auto result =
            impl_->compatibility_repo->resolve_conflict(study_uid, resolution);
    }
    #endif
    if (impl_->logger) {
        impl_->logger->info_fmt("Resolved conflict for study '{}' using {}",
            study_uid, to_string(resolution));
    }
    return kcenon::pacs::ok();
}
References kcenon::pacs::client::sync_manager::impl::compatibility_repo, kcenon::pacs::client::sync_manager::impl::conflicts, kcenon::pacs::client::sync_repositories::conflicts, kcenon::pacs::client::sync_manager::impl::conflicts_mutex, impl_, kcenon::pacs::client::sync_manager::impl::logger, kcenon::pacs::pacs_void_error(), kcenon::pacs::client::sync_manager::impl::repositories, kcenon::pacs::client::sync_manager::impl::resolve_conflict_internal(), and kcenon::pacs::client::to_string().
Referenced by resolve_all_conflicts().
set_completion_callback()
void kcenon::pacs::client::sync_manager::set_completion_callback (sync_completion_callback callback)
Set callback for sync completion.
Parameters
callback The callback function
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 1211 of file sync_manager.cpp.
{
    std::unique_lock lock(impl_->callbacks_mutex);
    impl_->completion_callback = std::move(callback);
}
References kcenon::pacs::client::sync_manager::impl::callbacks_mutex, kcenon::pacs::client::sync_manager::impl::completion_callback, and impl_.
set_conflict_callback()
void kcenon::pacs::client::sync_manager::set_conflict_callback (sync_conflict_callback callback)
Set callback for conflict detection.
Parameters
callback The callback function
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 1216 of file sync_manager.cpp.
{
    std::unique_lock lock(impl_->callbacks_mutex);
    impl_->conflict_callback = std::move(callback);
}
References kcenon::pacs::client::sync_manager::impl::callbacks_mutex, kcenon::pacs::client::sync_manager::impl::conflict_callback, and impl_.
set_progress_callback()
void kcenon::pacs::client::sync_manager::set_progress_callback (sync_progress_callback callback)
Set callback for sync progress updates.
Parameters
callback The callback function
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 1206 of file sync_manager.cpp.
{
    std::unique_lock lock(impl_->callbacks_mutex);
    impl_->progress_callback = std::move(callback);
}
References kcenon::pacs::client::sync_manager::impl::callbacks_mutex, impl_, and kcenon::pacs::client::sync_manager::impl::progress_callback.
start_scheduler()
void kcenon::pacs::client::sync_manager::start_scheduler ()
Start the sync scheduler.
Schedules syncs based on each config's schedule_cron setting.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 1108 of file sync_manager.cpp.
{
    if (impl_->scheduler_running.load()) {
        return;
    }
    impl_->scheduler_running.store(true);
    impl_->scheduler_thread = std::thread([this]() {
        impl_->scheduler_loop();
    });
    if (impl_->logger) {
        impl_->logger->info("Sync scheduler started");
    }
}
References impl_, kcenon::pacs::client::sync_manager::impl::logger, kcenon::pacs::client::sync_manager::impl::scheduler_loop(), kcenon::pacs::client::sync_manager::impl::scheduler_running, and kcenon::pacs::client::sync_manager::impl::scheduler_thread.
stop_scheduler()
void kcenon::pacs::client::sync_manager::stop_scheduler ()
Stop the sync scheduler.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 1123 of file sync_manager.cpp.
{
    if (!impl_->scheduler_running.load()) {
        return;
    }
    impl_->scheduler_running.store(false);
    impl_->scheduler_cv.notify_all();
    if (impl_->scheduler_thread.joinable()) {
        impl_->scheduler_thread.join();
    }
    if (impl_->logger) {
        impl_->logger->info("Sync scheduler stopped");
    }
}
References impl_, kcenon::pacs::client::sync_manager::impl::logger, kcenon::pacs::client::sync_manager::impl::scheduler_cv, kcenon::pacs::client::sync_manager::impl::scheduler_running, and kcenon::pacs::client::sync_manager::impl::scheduler_thread.
Referenced by ~sync_manager().
sync_now()
std::string kcenon::pacs::client::sync_manager::sync_now (std::string_view config_id) -> std::string nodiscard
Start sync immediately for a configuration.
Uses the config's existing settings (incremental or full based on last_sync).
Parameters
config_id The configuration ID to sync
Returns
Job ID for tracking progress
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 897 of file sync_manager.cpp.
{
    auto config_opt = impl_->get_config_from_cache(config_id);
    if (!config_opt) {
        return "";
    }
    impl_->mark_sync_active(config_id);
    // Determine if incremental or full based on last_successful_sync
    bool full = config_opt->last_successful_sync == std::chrono::system_clock::time_point{};
    auto result = impl_->perform_sync(*config_opt, full);
    impl_->mark_sync_inactive(config_id);
    impl_->notify_completion(std::string(config_id), result);
    return result.job_id;
}
References kcenon::pacs::client::sync_manager::impl::get_config_from_cache(), impl_, kcenon::pacs::client::sync_manager::impl::mark_sync_active(), kcenon::pacs::client::sync_manager::impl::mark_sync_inactive(), kcenon::pacs::client::sync_manager::impl::notify_completion(), and kcenon::pacs::client::sync_manager::impl::perform_sync().
update_config()
kcenon::pacs::VoidResult kcenon::pacs::client::sync_manager::update_config (const sync_config & config) -> kcenon::pacs::VoidResult nodiscard
Update an existing sync configuration.
Parameters
config The configuration to update (identified by config_id)
Returns
VoidResult indicating success or error
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 831 of file sync_manager.cpp.
{
    if (!impl_->get_config_from_cache(config.config_id).has_value()) {
        return kcenon::pacs::pacs_void_error(
            kcenon::pacs::error_codes::not_found,
            "Config not found: " + config.config_id);
    }
    impl_->save_config(config);
    if (impl_->logger) {
        impl_->logger->info_fmt("Updated sync config '{}'", config.config_id);
    }
    return kcenon::pacs::ok();
}
References config(), kcenon::pacs::client::sync_manager::impl::get_config_from_cache(), impl_, kcenon::pacs::client::sync_manager::impl::logger, kcenon::pacs::pacs_void_error(), and kcenon::pacs::client::sync_manager::impl::save_config().
wait_for_sync()
std::future< sync_result > kcenon::pacs::client::sync_manager::wait_for_sync (std::string_view job_id) -> std::future<sync_result> nodiscard
Wait for a sync operation to complete.
Parameters
job_id The job ID returned from sync operations
Returns
Future containing the sync result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 943 of file sync_manager.cpp.
{
    auto promise = std::make_shared<std::promise<sync_result>>();
    auto future = promise->get_future();
    {
        std::lock_guard lock(impl_->promises_mutex);
        impl_->completion_promises[std::string(job_id)] = promise;
    }
    return future;
}
References kcenon::pacs::client::sync_manager::impl::completion_promises, impl_, and kcenon::pacs::client::sync_manager::impl::promises_mutex.
Member Data Documentation
impl_
std::unique_ptr<impl> kcenon::pacs::client::sync_manager::impl_ private
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/sync_manager.h.
Definition at line 452 of file sync_manager.h.
Referenced by add_config(), compare(), config(), full_sync(), get_config(), get_conflicts(), get_conflicts(), get_last_result(), get_statistics(), get_statistics(), incremental_sync(), is_scheduler_running(), is_syncing(), list_configs(), remove_config(), resolve_all_conflicts(), resolve_conflict(), set_completion_callback(), set_conflict_callback(), set_progress_callback(), start_scheduler(), stop_scheduler(), sync_manager(), sync_manager(), sync_now(), update_config(), and wait_for_sync().
The documentation for this class was generated from the following files:
include/kcenon/pacs/client/sync_manager.h
src/client/sync_manager.cpp