PACS System: kcenon::pacs::services::validation::waveform_ps_iod_validator Class Reference
kcenon::pacs::services::validation::waveform_ps_iod_validator Class Reference
Validates Waveform Presentation State and Annotation IODs.
#include <waveform_ps_iod_validator.hpp>
Public Member Functions
waveform_ps_iod_validator ()=default
waveform_ps_iod_validator (const waveform_ps_validation_options &options)
validation_result validate (const core::dicom_dataset &dataset) const
Validate a complete Waveform Presentation State or Annotation dataset.
validation_result validate_references (const core::dicom_dataset &dataset) const
Validate referenced waveform sequences.
bool quick_check (const core::dicom_dataset &dataset) const
Quick validation of essential Type 1 attributes only.
const waveform_ps_validation_options & options () const noexcept
Get current validation options.
void set_options (const waveform_ps_validation_options &options)
Set validation options.
Private Member Functions
void validate_patient_module (const core::dicom_dataset &dataset, validation_result &result) const
void validate_general_study_module (const core::dicom_dataset &dataset, validation_result &result) const
void validate_general_series_module (const core::dicom_dataset &dataset, validation_result &result) const
void validate_general_equipment_module (const core::dicom_dataset &dataset, validation_result &result) const
void validate_sop_common_module (const core::dicom_dataset &dataset, validation_result &result) const
void validate_waveform_ps_module (const core::dicom_dataset &dataset, validation_result &result) const
void validate_waveform_annotation_module (const core::dicom_dataset &dataset, validation_result &result) const
void check_type1_attribute (const core::dicom_dataset &dataset, const core::dicom_tag &tag, const std::string &description, validation_result &result) const
void check_type2_attribute (const core::dicom_dataset &dataset, const core::dicom_tag &tag, const std::string &description, validation_result &result) const
Private Attributes
waveform_ps_validation_options options_
Detailed Description
Validates Waveform Presentation State and Annotation IODs.
Supports validation of:
Waveform Presentation State Storage (1.2.840.10008.5.1.4.1.1.11.11)
Waveform Annotation Storage (1.2.840.10008.5.1.4.1.1.11.12)
Validated Modules:
Patient Module (M)
General Study Module (M)
General Series Module (M)
General Equipment Module (M)
Waveform Presentation State Module (M) [for PS]
Waveform Annotation Module (M) [for Annotation]
SOP Common Module (M)
Definition at line 105 of file waveform_ps_iod_validator.hpp.
Constructor & Destructor Documentation
waveform_ps_iod_validator() [1/2]
kcenon::pacs::services::validation::waveform_ps_iod_validator::waveform_ps_iod_validator () default
waveform_ps_iod_validator() [2/2]
kcenon::pacs::services::validation::waveform_ps_iod_validator::waveform_ps_iod_validator (const waveform_ps_validation_options & options) explicit
Definition at line 67 of file waveform_ps_iod_validator.cpp.
    : options_(options) {}
Member Function Documentation
check_type1_attribute()
void kcenon::pacs::services::validation::waveform_ps_iod_validator::check_type1_attribute (const core::dicom_dataset & dataset, const core::dicom_tag & tag, const std::string & description, validation_result & result) const private
Definition at line 291 of file waveform_ps_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        result.findings.push_back({
            validation_severity::error,
            tag,
            "Type 1 attribute missing: " + description +
            " (" + tag.to_string() + ")",
            "WF-TYPE1-MISSING"
        });
    } else {
        const auto* element = dataset.get(tag);
        if (element != nullptr && !element->is_sequence()) {
            auto value = dataset.get_string(tag);
            if (value.empty()) {
                result.findings.push_back({
                    validation_severity::error,
                    tag,
                    "Type 1 attribute has empty value: " + description +
                    " (" + tag.to_string() + ")",
                    "WF-TYPE1-EMPTY"
                });
            }
        }
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::core::dicom_dataset::get(), kcenon::pacs::core::dicom_dataset::get_string(), and kcenon::pacs::core::dicom_tag::to_string().
Referenced by validate_general_series_module(), validate_general_study_module(), and validate_sop_common_module().
check_type2_attribute()
void kcenon::pacs::services::validation::waveform_ps_iod_validator::check_type2_attribute (const core::dicom_dataset & dataset, const core::dicom_tag & tag, const std::string & description, validation_result & result) const private
Definition at line 322 of file waveform_ps_iod_validator.cpp.
{
    if (!dataset.contains(tag)) {
        result.findings.push_back({
            validation_severity::warning,
            tag,
            "Type 2 attribute missing: " + description +
            " (" + tag.to_string() + ")",
            "WF-TYPE2-MISSING"
        });
    }
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::core::dicom_tag::to_string(), and kcenon::pacs::services::validation::warning.
Referenced by validate_general_equipment_module(), validate_general_series_module(), validate_general_study_module(), and validate_patient_module().
options()
const waveform_ps_validation_options & kcenon::pacs::services::validation::waveform_ps_iod_validator::options () const noexcept
Get current validation options.
Returns
Reference to validation options
Definition at line 162 of file waveform_ps_iod_validator.cpp.
{
    return options_;
}
References options_.
Referenced by set_options().
quick_check()
bool kcenon::pacs::services::validation::waveform_ps_iod_validator::quick_check (const core::dicom_dataset & dataset) const
Quick validation of essential Type 1 attributes only.
Parameters
dataset The DICOM dataset to validate
Returns
true if essential attributes are present and valid
Definition at line 143 of file waveform_ps_iod_validator.cpp.
{
    // Check essential Type 1 attributes
    if (!dataset.contains(tags::study_instance_uid)) return false;
    if (!dataset.contains(tags::series_instance_uid)) return false;
    if (!dataset.contains(tags::sop_class_uid)) return false;
    if (!dataset.contains(tags::sop_instance_uid)) return false;
    // Verify SOP Class is a waveform PS or annotation class
    auto sop_class = dataset.get_string(tags::sop_class_uid);
    if (!sop_classes::is_waveform_presentation_state_sop_class(sop_class) &&
        !sop_classes::is_waveform_annotation_sop_class(sop_class)) {
        return false;
    }
    return true;
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_waveform_annotation_sop_class(), kcenon::pacs::services::sop_classes::is_waveform_presentation_state_sop_class(), kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, and kcenon::pacs::core::tags::study_instance_uid.
set_options()
void kcenon::pacs::services::validation::waveform_ps_iod_validator::set_options (const waveform_ps_validation_options & options)
Set validation options.
Parameters
options New validation options
Definition at line 166 of file waveform_ps_iod_validator.cpp.
{
    options_ = options;
}
References options(), and options_.
validate()
validation_result kcenon::pacs::services::validation::waveform_ps_iod_validator::validate (const core::dicom_dataset & dataset) const
Validate a complete Waveform Presentation State or Annotation dataset.
Parameters
dataset The DICOM dataset to validate
Returns
Validation result with findings
Definition at line 71 of file waveform_ps_iod_validator.cpp.
{
    validation_result result;
    result.is_valid = true;
    // Validate mandatory modules
    if (options_.check_type1 || options_.check_type2) {
        validate_patient_module(dataset, result);
        validate_general_study_module(dataset, result);
        validate_general_series_module(dataset, result);
        validate_general_equipment_module(dataset, result);
        validate_sop_common_module(dataset, result);
    }
    // Determine if this is a Presentation State or Annotation
    auto sop_class = dataset.get_string(tags::sop_class_uid);
    if (sop_classes::is_waveform_presentation_state_sop_class(sop_class)) {
        if (options_.validate_display_config) {
            validate_waveform_ps_module(dataset, result);
        }
    } else if (sop_classes::is_waveform_annotation_sop_class(sop_class)) {
        if (options_.validate_annotations) {
            validate_waveform_annotation_module(dataset, result);
        }
    }
    if (options_.validate_references) {
        auto ref_result = validate_references(dataset);
        result.findings.insert(result.findings.end(),
                               ref_result.findings.begin(),
                               ref_result.findings.end());
    }
    // Check for errors
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
        if (options_.strict_mode && finding.severity == validation_severity::warning) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References kcenon::pacs::services::validation::waveform_ps_validation_options::check_type1, kcenon::pacs::services::validation::waveform_ps_validation_options::check_type2, kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::validation::validation_result::is_valid, kcenon::pacs::services::sop_classes::is_waveform_annotation_sop_class(), kcenon::pacs::services::sop_classes::is_waveform_presentation_state_sop_class(), options_, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::services::validation::waveform_ps_validation_options::strict_mode, kcenon::pacs::services::validation::waveform_ps_validation_options::validate_annotations, kcenon::pacs::services::validation::waveform_ps_validation_options::validate_display_config, validate_general_equipment_module(), validate_general_series_module(), validate_general_study_module(), validate_patient_module(), kcenon::pacs::services::validation::waveform_ps_validation_options::validate_references, validate_references(), validate_sop_common_module(), validate_waveform_annotation_module(), validate_waveform_ps_module(), and kcenon::pacs::services::validation::warning.
validate_general_equipment_module()
void kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_general_equipment_module (const core::dicom_dataset & dataset, validation_result & result) const private
Definition at line 218 of file waveform_ps_iod_validator.cpp.
{
    if (options_.check_type2) {
        check_type2_attribute(dataset, waveform_tags::manufacturer, "Manufacturer", result);
    }
}
References kcenon::pacs::services::validation::waveform_ps_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::services::validation::waveform_tags::manufacturer, and options_.
Referenced by validate().
validate_general_series_module()
void kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_general_series_module (const core::dicom_dataset & dataset, validation_result & result) const private
Definition at line 204 of file waveform_ps_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::modality, "Modality", result);
        check_type1_attribute(dataset, tags::series_instance_uid, "SeriesInstanceUID", result);
    }
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::series_number, "SeriesNumber", result);
    }
}
References kcenon::pacs::services::validation::waveform_ps_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::waveform_ps_validation_options::check_type2, check_type2_attribute(), kcenon::pacs::core::tags::modality, options_, kcenon::pacs::core::tags::series_instance_uid, and kcenon::pacs::core::tags::series_number.
Referenced by validate().
validate_general_study_module()
void kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_general_study_module (const core::dicom_dataset & dataset, validation_result & result) const private
Definition at line 187 of file waveform_ps_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::study_instance_uid, "StudyInstanceUID", result);
    }
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::study_date, "StudyDate", result);
        check_type2_attribute(dataset, tags::study_time, "StudyTime", result);
        check_type2_attribute(dataset, tags::referring_physician_name, "ReferringPhysicianName", result);
        check_type2_attribute(dataset, tags::study_id, "StudyID", result);
        check_type2_attribute(dataset, tags::accession_number, "AccessionNumber", result);
    }
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::services::validation::waveform_ps_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::services::validation::waveform_ps_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::core::tags::study_time.
Referenced by validate().
validate_patient_module()
void kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_patient_module (const core::dicom_dataset & dataset, validation_result & result) const private
Definition at line 175 of file waveform_ps_iod_validator.cpp.
{
    if (options_.check_type2) {
        check_type2_attribute(dataset, tags::patient_name, "PatientName", result);
        check_type2_attribute(dataset, tags::patient_id, "PatientID", result);
        check_type2_attribute(dataset, tags::patient_birth_date, "PatientBirthDate", result);
        check_type2_attribute(dataset, tags::patient_sex, "PatientSex", result);
    }
}
References kcenon::pacs::services::validation::waveform_ps_validation_options::check_type2, check_type2_attribute(), options_, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, and kcenon::pacs::core::tags::patient_sex.
Referenced by validate().
validate_references()
validation_result kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_references (const core::dicom_dataset & dataset) const
Validate referenced waveform sequences.
Parameters
dataset The DICOM dataset to validate
Returns
Validation result with reference-specific findings
Definition at line 119 of file waveform_ps_iod_validator.cpp.
{
    validation_result result;
    result.is_valid = true;
    if (!dataset.contains(waveform_tags::referenced_series_sequence)) {
        result.findings.push_back({
            validation_severity::warning,
            waveform_tags::referenced_series_sequence,
            "ReferencedSeriesSequence (0008,1115) should be present for waveform references",
            "WF-REF-WARN-001"
        });
    }
    for (const auto& finding : result.findings) {
        if (finding.severity == validation_severity::error) {
            result.is_valid = false;
            break;
        }
    }
    return result;
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::services::validation::validation_result::is_valid, kcenon::pacs::services::validation::waveform_tags::referenced_series_sequence, and kcenon::pacs::services::validation::warning.
Referenced by validate().
validate_sop_common_module()
void kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_sop_common_module (const core::dicom_dataset & dataset, validation_result & result) const private
Definition at line 227 of file waveform_ps_iod_validator.cpp.
{
    if (options_.check_type1) {
        check_type1_attribute(dataset, tags::sop_class_uid, "SOPClassUID", result);
        check_type1_attribute(dataset, tags::sop_instance_uid, "SOPInstanceUID", result);
    }
    // Validate SOP Class UID is a waveform PS or annotation class
    if (dataset.contains(tags::sop_class_uid)) {
        auto sop_class = dataset.get_string(tags::sop_class_uid);
        if (!sop_classes::is_waveform_presentation_state_sop_class(sop_class) &&
            !sop_classes::is_waveform_annotation_sop_class(sop_class)) {
            result.findings.push_back({
                validation_severity::error,
                tags::sop_class_uid,
                "SOPClassUID is not a recognized Waveform PS/Annotation SOP Class: " + sop_class,
                "WF-ERR-001"
            });
        }
    }
}
References kcenon::pacs::services::validation::waveform_ps_validation_options::check_type1, check_type1_attribute(), kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::error, kcenon::pacs::services::validation::validation_result::findings, kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_waveform_annotation_sop_class(), kcenon::pacs::services::sop_classes::is_waveform_presentation_state_sop_class(), options_, kcenon::pacs::core::tags::sop_class_uid, and kcenon::pacs::core::tags::sop_instance_uid.
Referenced by validate().
validate_waveform_annotation_module()
void kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_waveform_annotation_module (const core::dicom_dataset & dataset, validation_result & result) const private
Definition at line 269 of file waveform_ps_iod_validator.cpp.
{
    // Waveform Annotation Sequence is expected for annotation objects
    if (options_.check_conditional) {
        if (!dataset.contains(waveform_tags::waveform_annotation_sequence)) {
            result.findings.push_back({
                validation_severity::warning,
                waveform_tags::waveform_annotation_sequence,
                "WaveformAnnotationSequence (0040,B020) should be present for "
                "Waveform Annotation objects",
                "WF-ANN-WARN-001"
            });
        }
    }
}
References kcenon::pacs::services::validation::waveform_ps_validation_options::check_conditional, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::validation_result::findings, options_, kcenon::pacs::services::validation::warning, and kcenon::pacs::services::validation::waveform_tags::waveform_annotation_sequence.
Referenced by validate().
validate_waveform_ps_module()
void kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_waveform_ps_module (const core::dicom_dataset & dataset, validation_result & result) const private
Definition at line 251 of file waveform_ps_iod_validator.cpp.
{
    // Waveform Presentation Sequence is expected for PS objects
    if (options_.check_conditional) {
        if (!dataset.contains(waveform_tags::waveform_presentation_sequence)) {
            result.findings.push_back({
                validation_severity::warning,
                waveform_tags::waveform_presentation_sequence,
                "WaveformPresentationSequence (0070,0001) should be present for "
                "Waveform Presentation State objects",
                "WF-PS-WARN-001"
            });
        }
    }
}
References kcenon::pacs::services::validation::waveform_ps_validation_options::check_conditional, kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::validation_result::findings, options_, kcenon::pacs::services::validation::warning, and kcenon::pacs::services::validation::waveform_tags::waveform_presentation_sequence.
Referenced by validate().
Member Data Documentation
options_
waveform_ps_validation_options kcenon::pacs::services::validation::waveform_ps_iod_validator::options_ private
Definition at line 144 of file waveform_ps_iod_validator.hpp.
Referenced by options(), set_options(), validate(), validate_general_equipment_module(), validate_general_series_module(), validate_general_study_module(), validate_patient_module(), validate_sop_common_module(), validate_waveform_annotation_module(), and validate_waveform_ps_module().
The documentation for this class was generated from the following files:
include/pacs/services/validation/waveform_ps_iod_validator.hpp
src/services/validation/waveform_ps_iod_validator.cpp