var dir_3af994d6c5a28949be5d0000f3a86207 =
[
    [ "scripts", "dir_d2b04266d70ed1385874cbc780aa2aa3.html", null ],
    [ "test_data", "dir_77447e75c03c731a8d8ab74f5321f3e4.html", null ],
    [ "dcmtk_tool.h", "dcmtk__tool_8h.html", "dcmtk__tool_8h" ],
    [ "generate_test_data.cpp", "generate__test__data_8cpp.html", "generate__test__data_8cpp" ],
    [ "main.cpp", "integration__tests_2main_8cpp.html", "integration__tests_2main_8cpp" ],
    [ "test_cli_roundtrip.cpp", "test__cli__roundtrip_8cpp.html", "test__cli__roundtrip_8cpp" ],
    [ "test_connectivity.cpp", "test__connectivity_8cpp.html", "test__connectivity_8cpp" ],
    [ "test_data_generator.cpp", "test__data__generator_8cpp.html", null ],
    [ "test_data_generator.h", "test__data__generator_8h.html", "test__data__generator_8h" ],
    [ "test_data_generator_test.cpp", "test__data__generator__test_8cpp.html", "test__data__generator__test_8cpp" ],
    [ "test_dcmtk_echo.cpp", "test__dcmtk__echo_8cpp.html", "test__dcmtk__echo_8cpp" ],
    [ "test_dcmtk_find.cpp", "test__dcmtk__find_8cpp.html", "test__dcmtk__find_8cpp" ],
    [ "test_dcmtk_move.cpp", "test__dcmtk__move_8cpp.html", "test__dcmtk__move_8cpp" ],
    [ "test_dcmtk_store.cpp", "test__dcmtk__store_8cpp.html", "test__dcmtk__store_8cpp" ],
    [ "test_dcmtk_tool.cpp", "test__dcmtk__tool_8cpp.html", "test__dcmtk__tool_8cpp" ],
    [ "test_dicom_server_v2_integration.cpp", "test__dicom__server__v2__integration_8cpp.html", "test__dicom__server__v2__integration_8cpp" ],
    [ "test_error_recovery.cpp", "test__error__recovery_8cpp.html", "test__error__recovery_8cpp" ],
    [ "test_fixtures.h", "test__fixtures_8h.html", "test__fixtures_8h" ],
    [ "test_multimodal_workflow.cpp", "test__multimodal__workflow_8cpp.html", "test__multimodal__workflow_8cpp" ],
    [ "test_stability.cpp", "test__stability_8cpp.html", "test__stability_8cpp" ],
    [ "test_store_query.cpp", "test__store__query_8cpp.html", "test__store__query_8cpp" ],
    [ "test_stress.cpp", "test__stress_8cpp.html", "test__stress_8cpp" ],
    [ "test_tls_integration.cpp", "test__tls__integration_8cpp.html", "test__tls__integration_8cpp" ],
    [ "test_worklist_mpps.cpp", "test__worklist__mpps_8cpp.html", "test__worklist__mpps_8cpp" ],
    [ "test_xa_storage.cpp", "test__xa__storage_8cpp.html", "test__xa__storage_8cpp" ]
];