PACS System: kcenon::pacs::web::wado_uri Namespace Reference
kcenon::pacs::web::wado_uri Namespace Reference
Classes
struct validation_result
Result of WADO-URI request validation.
struct wado_uri_request
Parsed WADO-URI request parameters.
Functions
wado_uri_request parse_wado_uri_params (const char *study_uid, const char *series_uid, const char *object_uid, const char *content_type, const char *transfer_syntax, const char *anonymize, const char *rows, const char *columns, const char *window_center, const char *window_width, const char *frame_number)
Parse WADO-URI query parameters from an HTTP request.
validation_result validate_wado_uri_request (const wado_uri_request &request)
Validate a WADO-URI request.
bool is_supported_content_type (std::string_view content_type)
Check if a content type is supported by WADO-URI.
Function Documentation
is_supported_content_type()
bool kcenon::pacs::web::wado_uri::is_supported_content_type (std::string_view content_type) nodiscard
Check if a content type is supported by WADO-URI.
Parameters
content_type The content type to check
Returns
true if the content type is supported
Definition at line 149 of file wado_uri_endpoints.cpp.
{
    return content_type == "application/dicom"
        || content_type == "image/jpeg"
        || content_type == "image/png"
        || content_type == "application/dicom+json";
}
Referenced by validate_wado_uri_request().
parse_wado_uri_params()
wado_uri_request kcenon::pacs::web::wado_uri::parse_wado_uri_params (const char * study_uid, const char * series_uid, const char * object_uid, const char * content_type, const char * transfer_syntax, const char * anonymize, const char * rows, const char * columns, const char * window_center, const char * window_width, const char * frame_number) nodiscard
Parse WADO-URI query parameters from an HTTP request.
Parameters
request_type The requestType parameter value
study_uid The studyUID parameter value
series_uid The seriesUID parameter value
object_uid The objectUID parameter value
content_type The contentType parameter value (optional)
transfer_syntax The transferSyntax parameter value (optional)
anonymize The anonymize parameter value (optional)
rows The rows parameter value (optional)
columns The columns parameter value (optional)
window_center The windowCenter parameter value (optional)
window_width The windowWidth parameter value (optional)
frame_number The frameNumber parameter value (optional)
Returns
Parsed WADO-URI request parameters
Definition at line 45 of file wado_uri_endpoints.cpp.
{
    wado_uri_request request;
    if (study_uid != nullptr) {
        request.study_uid = study_uid;
    }
    if (series_uid != nullptr) {
        request.series_uid = series_uid;
    }
    if (object_uid != nullptr) {
        request.object_uid = object_uid;
    }
    if (content_type != nullptr && content_type[0] != '\0') {
        request.content_type = content_type;
    }
    if (transfer_syntax != nullptr && transfer_syntax[0] != '\0') {
        request.transfer_syntax = std::string(transfer_syntax);
    }
    if (anonymize != nullptr) {
        std::string anon_str(anonymize);
        request.anonymize = (anon_str == "yes" || anon_str == "true"
                             || anon_str == "1");
    }
    if (rows != nullptr) {
        try {
            int val = std::stoi(rows);
            if (val > 0 && val <= 65535) {
                request.rows = static_cast<uint16_t>(val);
            }
        } catch (...) {
            // Ignore invalid values
        }
    }
    if (columns != nullptr) {
        try {
            int val = std::stoi(columns);
            if (val > 0 && val <= 65535) {
                request.columns = static_cast<uint16_t>(val);
            }
        } catch (...) {
            // Ignore invalid values
        }
    }
    if (window_center != nullptr) {
        try {
            request.window_center = std::stod(window_center);
        } catch (...) {
            // Ignore invalid values
        }
    }
    if (window_width != nullptr) {
        try {
            request.window_width = std::stod(window_width);
        } catch (...) {
            // Ignore invalid values
        }
    }
    if (frame_number != nullptr) {
        try {
            int val = std::stoi(frame_number);
            if (val > 0) {
                request.frame_number = static_cast<uint32_t>(val);
            }
        } catch (...) {
            // Ignore invalid values
        }
    }
    return request;
}
References kcenon::pacs::web::wado_uri::wado_uri_request::anonymize, kcenon::pacs::web::wado_uri::wado_uri_request::columns, kcenon::pacs::web::wado_uri::wado_uri_request::content_type, kcenon::pacs::web::wado_uri::wado_uri_request::frame_number, kcenon::pacs::web::wado_uri::wado_uri_request::object_uid, kcenon::pacs::web::wado_uri::wado_uri_request::rows, kcenon::pacs::web::wado_uri::wado_uri_request::series_uid, kcenon::pacs::web::wado_uri::wado_uri_request::study_uid, kcenon::pacs::web::wado_uri::wado_uri_request::transfer_syntax, kcenon::pacs::web::wado_uri::wado_uri_request::window_center, and kcenon::pacs::web::wado_uri::wado_uri_request::window_width.
Referenced by kcenon::pacs::web::endpoints::register_wado_uri_endpoints_impl().
validate_wado_uri_request()
validation_result kcenon::pacs::web::wado_uri::validate_wado_uri_request (const wado_uri_request & request) nodiscard
Validate a WADO-URI request.
Parameters
request The parsed request parameters
Returns
Validation result
Definition at line 128 of file wado_uri_endpoints.cpp.
{
    if (request.study_uid.empty()) {
        return validation_result::error(
            400, "MISSING_PARAMETER", "studyUID parameter is required");
    }
    if (request.series_uid.empty()) {
        return validation_result::error(
            400, "MISSING_PARAMETER", "seriesUID parameter is required");
    }
    if (request.object_uid.empty()) {
        return validation_result::error(
            400, "MISSING_PARAMETER", "objectUID parameter is required");
    }
    if (!is_supported_content_type(request.content_type)) {
        return validation_result::error(
            406, "UNSUPPORTED_MEDIA_TYPE",
            "Unsupported contentType: " + request.content_type);
    }
    return validation_result::ok();
}
References kcenon::pacs::web::wado_uri::wado_uri_request::content_type, kcenon::pacs::web::wado_uri::validation_result::error(), is_supported_content_type(), kcenon::pacs::web::wado_uri::wado_uri_request::object_uid, kcenon::pacs::web::wado_uri::validation_result::ok(), kcenon::pacs::web::wado_uri::wado_uri_request::series_uid, and kcenon::pacs::web::wado_uri::wado_uri_request::study_uid.
Referenced by kcenon::pacs::web::endpoints::register_wado_uri_endpoints_impl().