PACS System: kcenon::pacs::security::hipaa_identifiers Namespace Reference
kcenon::pacs::security::hipaa_identifiers Namespace Reference
HIPAA Safe Harbor identifiers (18 categories)
Functions
auto get_name_tags () -> std::vector< core::dicom_tag >
Tags containing names.
auto get_geographic_tags () -> std::vector< core::dicom_tag >
Tags containing geographic identifiers.
auto get_date_tags () -> std::vector< core::dicom_tag >
Tags containing dates (except year)
auto get_communication_tags () -> std::vector< core::dicom_tag >
Tags containing communication identifiers.
auto get_unique_id_tags () -> std::vector< core::dicom_tag >
Tags containing unique identifiers.
auto get_all_identifier_tags () -> std::vector< core::dicom_tag >
Get all HIPAA identifier tags.
Detailed Description
HIPAA Safe Harbor identifiers (18 categories)
These correspond to the 18 categories of identifiers specified in 45 CFR 164.514(b)(2) for HIPAA Safe Harbor de-identification.
Function Documentation
get_all_identifier_tags()
auto kcenon::pacs::security::hipaa_identifiers::get_all_identifier_tags () -> std::vector<core::dicom_tag> nodiscard
Get all HIPAA identifier tags.
Definition at line 71 of file tag_action.cpp.
{
    std::vector<dicom_tag> all_tags;
    auto names = get_name_tags();
    auto geo = get_geographic_tags();
    auto dates = get_date_tags();
    auto comm = get_communication_tags();
    auto ids = get_unique_id_tags();
    all_tags.reserve(names.size() + geo.size() + dates.size() +
                     comm.size() + ids.size());
    all_tags.insert(all_tags.end(), names.begin(), names.end());
    all_tags.insert(all_tags.end(), geo.begin(), geo.end());
    all_tags.insert(all_tags.end(), dates.begin(), dates.end());
    all_tags.insert(all_tags.end(), comm.begin(), comm.end());
    all_tags.insert(all_tags.end(), ids.begin(), ids.end());
    return all_tags;
}
References get_communication_tags(), get_date_tags(), get_geographic_tags(), get_name_tags(), and get_unique_id_tags().
Referenced by kcenon::pacs::security::anonymizer::get_hipaa_identifier_tags().
get_communication_tags()
auto kcenon::pacs::security::hipaa_identifiers::get_communication_tags () -> std::vector<core::dicom_tag> nodiscard
Tags containing communication identifiers.
Definition at line 53 of file tag_action.cpp.
{
    // Phone, fax, email - not typically in standard DICOM tags
    // These would be in private tags or extended attributes
    return {};
}
Referenced by get_all_identifier_tags().
get_date_tags()
auto kcenon::pacs::security::hipaa_identifiers::get_date_tags () -> std::vector<core::dicom_tag> nodiscard
Tags containing dates (except year)
Definition at line 39 of file tag_action.cpp.
{
    return {
        tags::patient_birth_date,
        tags::study_date,
        tags::series_date,
        tags::acquisition_date,
        tags::content_date,
        tags::instance_creation_date,
        tags::scheduled_procedure_step_start_date,
        tags::scheduled_procedure_step_end_date,
        tags::performed_procedure_step_start_date
    };
}
References kcenon::pacs::core::tags::acquisition_date, kcenon::pacs::core::tags::content_date, kcenon::pacs::core::tags::instance_creation_date, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::performed_procedure_step_start_date, kcenon::pacs::core::tags::scheduled_procedure_step_end_date, kcenon::pacs::core::tags::scheduled_procedure_step_start_date, kcenon::pacs::core::tags::series_date, and kcenon::pacs::core::tags::study_date.
Referenced by get_all_identifier_tags().
get_geographic_tags()
auto kcenon::pacs::security::hipaa_identifiers::get_geographic_tags () -> std::vector<core::dicom_tag> nodiscard
Tags containing geographic identifiers.
Definition at line 30 of file tag_action.cpp.
{
    return {
        tags::institution_name,
        tags::institution_address,
        tags::patient_address,
        tags::station_name
    };
}
References kcenon::pacs::core::tags::institution_address, kcenon::pacs::core::tags::institution_name, kcenon::pacs::core::tags::patient_address, and kcenon::pacs::core::tags::station_name.
Referenced by get_all_identifier_tags().
get_name_tags()
auto kcenon::pacs::security::hipaa_identifiers::get_name_tags () -> std::vector<core::dicom_tag> nodiscard
Tags containing names.
Definition at line 19 of file tag_action.cpp.
{
    return {
        tags::patient_name,
        tags::referring_physician_name,
        tags::performing_physician_name,
        tags::name_of_physicians_reading_study,
        tags::operators_name,
        tags::scheduled_performing_physician_name
    };
}
References kcenon::pacs::core::tags::name_of_physicians_reading_study, kcenon::pacs::core::tags::operators_name, kcenon::pacs::core::tags::patient_name, kcenon::pacs::core::tags::performing_physician_name, kcenon::pacs::core::tags::referring_physician_name, and kcenon::pacs::core::tags::scheduled_performing_physician_name.
Referenced by get_all_identifier_tags().
get_unique_id_tags()
auto kcenon::pacs::security::hipaa_identifiers::get_unique_id_tags () -> std::vector<core::dicom_tag> nodiscard
Tags containing unique identifiers.
Definition at line 59 of file tag_action.cpp.
{
    return {
        tags::patient_id,
        tags::issuer_of_patient_id,
        tags::accession_number,
        tags::study_id,
        tags::requested_procedure_id,
        tags::scheduled_procedure_step_id,
        tags::performed_procedure_step_id
    };
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::core::tags::issuer_of_patient_id, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::performed_procedure_step_id, kcenon::pacs::core::tags::requested_procedure_id, kcenon::pacs::core::tags::scheduled_procedure_step_id, and kcenon::pacs::core::tags::study_id.
Referenced by get_all_identifier_tags().