PACS System: kcenon::pacs::services::sop_classes Namespace Reference
kcenon::pacs::services::sop_classes Namespace Reference
Namespaces
namespace ophthalmic_tags
namespace parametric_map_tags
namespace sr_template
Common SR Template IDs (TID)
namespace wsi_tags
Classes
struct dx_sop_class_info
Information about a DX Storage SOP Class.
struct mg_acquisition_params
Mammography acquisition parameters structure.
struct mg_sop_class_info
Information about a Mammography Storage SOP Class.
struct nm_energy_window_info
Energy window information for NM acquisition.
struct nm_sop_class_info
Information about a NM Storage SOP Class.
struct parametric_map_sop_class_info
Information about the Parametric Map Storage SOP Class.
struct pet_sop_class_info
Information about a PET Storage SOP Class.
struct rt_sop_class_info
Information about an RT Storage SOP Class.
struct seg_sop_class_info
Information about a SEG Storage SOP Class.
struct segment_color
Standard segment colors for common anatomical structures.
struct sr_sop_class_info
Information about an SR Storage SOP Class.
struct us_sop_class_info
Information about an US Storage SOP Class.
struct waveform_sop_class_info
Information about a Waveform Storage SOP Class.
struct xa_calibration_data
XA calibration data for quantitative analysis.
struct xa_positioner_angles
Positioner angle information.
struct xa_sop_class_info
Information about an XA/XRF Storage SOP Class.
Enumerations
enum class dx_photometric_interpretation { monochrome1 , monochrome2 }
Supported photometric interpretations for DX images.
enum class dx_image_type { for_presentation , for_processing }
DX image purpose classification.
enum class dx_view_position {
ap , pa , lateral , oblique ,
other
}
Common radiographic view positions for DX images.
enum class dx_detector_type { direct , indirect , storage , film }
DX detector technology types.
enum class dx_body_part {
chest , abdomen , pelvis , spine ,
skull , hand , foot , knee ,
elbow , shoulder , hip , wrist ,
ankle , extremity , breast , other
}
Common body parts for DX imaging.
enum class breast_laterality { left , right , bilateral , unknown }
Breast laterality enumeration.
enum class mg_view_position {
cc , mlo , ml , lm ,
xccl , xccm , fb , sio ,
iso , cv , at , spot ,
mag , spot_mag , rl , rm ,
rs , ri , tangen , implant ,
id , other
}
Mammography-specific view positions.
enum class mg_image_type { for_presentation , for_processing }
Mammography image purpose classification.
enum class cad_processing_status {
not_processed , processed_no_findings , processed_findings , processing_failed ,
pending
}
CAD (Computer-Aided Detection) processing status.
enum class nm_photometric_interpretation { monochrome2 , palette_color }
Supported photometric interpretations for NM images.
enum class nm_type_of_data {
static_image , dynamic , gated , whole_body ,
recon_tomo , recon_gated_tomo , tomo , gated_tomo
}
NM image type (Type of Data)
enum class nm_detector_geometry {
planar , ring , partial_ring , curved ,
cylindrical
}
NM detector geometry type.
enum class nm_collimator_type {
parallel , fan_beam , cone_beam , pinhole ,
diverging , converging , none
}
NM collimator type.
enum class nm_radioisotope {
tc99m , i131 , i123 , tl201 ,
ga67 , in111 , f18 , other
}
Common radioisotopes used in NM imaging.
enum class nm_rotation_direction { cw , cc }
NM rotation direction for SPECT.
enum class nm_scan_arc { arc_180 , arc_360 }
NM scan arc for SPECT.
enum class nm_whole_body_technique { single_pass , multi_pass , stepping }
Patient orientation for whole body scan.
enum class pixel_value_representation { float32 , float64 }
Pixel value representation for parametric map data.
enum class pet_photometric_interpretation { monochrome2 }
Supported photometric interpretations for PET images.
enum class pet_image_type { original , derived , primary , secondary }
PET image type indicating the nature of the image.
enum class pet_series_type { static_image , dynamic , gated , whole_body }
PET series type code.
enum class pet_attenuation_correction { none , measured , calculated , ct_based }
Attenuation correction method.
enum class pet_scatter_correction { none , single_scatter , convolution , model_based }
Scatter correction method.
enum class pet_reconstruction_type {
fbp , osem , mlem , tof_osem ,
psf_osem , other
}
PET reconstruction algorithm type.
enum class pet_units {
cnts , bqml , gml , suv_bw ,
suv_lbm , suv_bsa , percent_id_gram , other
}
PET units type (Units attribute 0054,1001)
enum class pet_radiotracer {
fdg , naf , flt , fdopa ,
ammonia , rubidium , gallium_dotatate , psma ,
other
}
Common PET radiotracers.
enum class rt_plan_intent {
curative , palliative , prophylactic , verification ,
machine_qa , research , service
}
RT Plan Intent.
enum class rt_plan_geometry { patient , treatment_device }
RT Plan Geometry.
enum class rt_dose_type { physical , effective , error }
RT Dose Type.
enum class rt_dose_summation_type {
plan , multi_plan , fraction , beam ,
brachy , fraction_session , beam_session , brachy_session ,
control_point , record
}
RT Dose Summation Type.
enum class rt_dose_units { gy , relative }
RT Dose Units.
enum class rt_roi_interpreted_type {
external , ptv , ctv , gtv ,
organ , avoidance , treated_volume , irrad_volume ,
bolus , brachy_channel , brachy_accessory , brachy_src_appl ,
brachy_chnl_shld , support , fixation , dose_region ,
contrast_agent , cavity , marker , registration ,
isocenter , control_point
}
RT ROI Interpreted Type.
enum class rt_roi_generation_algorithm { automatic , semiautomatic , manual }
RT ROI Generation Algorithm.
enum class rt_beam_type { static_beam , dynamic }
RT Beam Type.
enum class rt_radiation_type {
photon , electron , neutron , proton ,
ion
}
RT Radiation Type.
enum class rt_treatment_delivery_type {
treatment , open_portfilm , trmt_portfilm , continuation ,
setup
}
RT Treatment Delivery Type.
enum class rt_image_plane {
axial , localizer , drr , portal ,
fluence
}
RT Image Type values (as used in Image Type attribute)
enum class segmentation_type { binary , fractional }
Segmentation type (0062,0001)
enum class segmentation_fractional_type { probability , occupancy }
Segmentation fractional type (0062,0010)
enum class segment_algorithm_type { automatic , semiautomatic , manual }
Segment algorithm type (0062,0008)
enum class segment_category {
tissue , anatomical_structure , physical_object , morphologically_abnormal ,
function , spatial , body_substance
}
Common anatomical property categories (CID 7150)
enum class sr_document_type {
basic_text , enhanced , comprehensive , comprehensive_3d ,
extensible , key_object_selection , cad , dose_report ,
procedure_log , other
}
SR Document type classification.
enum class sr_value_type {
text , code , num , datetime ,
date , time , uidref , pname ,
composite , image , waveform , scoord ,
scoord3d , tcoord , container , table ,
unknown
}
SR Content Item Value Type (0040,A040)
enum class sr_relationship_type {
contains , has_obs_context , has_acq_context , has_concept_mod ,
has_properties , inferred_from , selected_from , unknown
}
SR Content Item Relationship Type (0040,A010)
enum class sr_completion_flag { partial , complete }
SR Completion Flag (0040,A491)
enum class sr_verification_flag { unverified , verified }
SR Verification Flag (0040,A493)
enum class us_photometric_interpretation {
monochrome1 , monochrome2 , palette_color , rgb ,
ybr_full , ybr_full_422
}
Supported photometric interpretations for US images.
enum class us_region_spatial_format : uint16_t {
none = 0x0000 , two_d = 0x0001 , m_mode = 0x0002 , spectral = 0x0003 ,
wave_form = 0x0004 , graphics = 0x0005
}
US Region spatial format.
enum class us_region_data_type : uint16_t {
tissue = 0x0001 , blood = 0x0002 , color_flow = 0x0003 , elastography = 0x0004 ,
b_mode = 0x0005
}
US Region data type.
enum class waveform_type {
ecg_12lead , ecg_general , ecg_ambulatory , hemodynamic ,
cardiac_ep , audio_basic , audio_general , arterial_pulse ,
respiratory , respiratory_multi , eeg_routine , emg ,
eog , eeg_sleep , body_position , presentation_state ,
annotation , unknown
}
Waveform type classification.
enum class xa_photometric_interpretation { monochrome1 , monochrome2 }
Supported photometric interpretations for XA/XRF images.
enum class xa_positioner_motion { stationary , dynamic }
Positioner motion type.
enum class xa_frame_rate : uint16_t { fps_7_5 = 8 , fps_15 = 15 , fps_30 = 30 }
Common XA frame rates in frames per second.
Functions
std::vector< std::string > get_ct_storage_sop_classes ()
Get all CT Storage SOP Class UIDs.
bool is_ct_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a CT Storage SOP Class.
bool is_valid_ct_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for CT.
std::vector< std::string > get_dx_transfer_syntaxes ()
Get recommended transfer syntaxes for DX images.
std::string_view to_string (dx_photometric_interpretation interp) noexcept
Convert photometric interpretation enum to DICOM string.
dx_photometric_interpretation parse_dx_photometric_interpretation (std::string_view value) noexcept
Parse DICOM photometric interpretation string for DX.
bool is_valid_dx_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for DX.
std::string_view to_string (dx_image_type type) noexcept
Convert DX image type to string.
std::string_view to_string (dx_view_position position) noexcept
Convert view position enum to DICOM string.
dx_view_position parse_view_position (std::string_view value) noexcept
Parse DICOM view position string.
std::string_view to_string (dx_detector_type type) noexcept
Convert detector type enum to DICOM string.
dx_detector_type parse_detector_type (std::string_view value) noexcept
Parse DICOM detector type string.
std::vector< std::string > get_dx_storage_sop_classes (bool include_mammography=true, bool include_intraoral=true)
Get all DX Storage SOP Class UIDs.
const dx_sop_class_info * get_dx_sop_class_info (std::string_view uid) noexcept
Get information about a specific DX SOP Class.
bool is_dx_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a DX Storage SOP Class.
bool is_dx_for_processing_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a For Processing SOP Class.
bool is_dx_for_presentation_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a For Presentation SOP Class.
bool is_mammography_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a mammography SOP Class.
std::string_view to_string (dx_body_part part) noexcept
Convert body part enum to DICOM string.
dx_body_part parse_body_part (std::string_view value) noexcept
Parse DICOM body part examined string.
std::string_view to_string (breast_laterality laterality) noexcept
Convert breast laterality enum to DICOM string.
breast_laterality parse_breast_laterality (std::string_view value) noexcept
Parse DICOM laterality string to enum.
bool is_valid_breast_laterality (std::string_view value) noexcept
Check if a laterality value is valid for mammography.
std::string_view to_string (mg_view_position position) noexcept
Convert mammography view position enum to DICOM string.
mg_view_position parse_mg_view_position (std::string_view value) noexcept
Parse DICOM view position string to mammography view enum.
bool is_screening_view (mg_view_position position) noexcept
Check if a view position is a standard screening view.
bool is_magnification_view (mg_view_position position) noexcept
Check if a view position requires magnification.
bool is_spot_compression_view (mg_view_position position) noexcept
Check if a view position involves spot compression.
std::vector< std::string_view > get_valid_mg_view_positions () noexcept
Get all valid mammography view position strings.
bool is_valid_compression_force (double force_n) noexcept
Validate compression force value.
std::pair< double, double > get_typical_compression_force_range () noexcept
Get typical compression force range.
bool is_valid_compressed_breast_thickness (double thickness_mm) noexcept
Validate compressed breast thickness.
std::string_view to_string (mg_image_type type) noexcept
Convert mammography image type to string.
std::string_view to_string (cad_processing_status status) noexcept
Convert CAD processing status to display string.
std::vector< std::string > get_mg_storage_sop_classes (bool include_tomosynthesis=true)
Get all Mammography Storage SOP Class UIDs.
const mg_sop_class_info * get_mg_sop_class_info (std::string_view uid) noexcept
Get information about a specific Mammography SOP Class.
bool is_mg_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a Mammography Storage SOP Class.
bool is_breast_tomosynthesis_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a breast tomosynthesis SOP Class.
bool is_mg_for_processing_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a For Processing mammography SOP Class.
bool is_mg_for_presentation_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a For Presentation mammography SOP Class.
std::vector< std::string > get_mg_transfer_syntaxes ()
Get recommended transfer syntaxes for mammography images.
bool is_valid_laterality_view_combination (breast_laterality laterality, mg_view_position view) noexcept
Check if laterality and view position are consistent.
std::vector< std::pair< breast_laterality, mg_view_position > > get_standard_screening_views () noexcept
Get standard four-view screening exam views.
std::string create_mg_image_type (bool is_original, bool is_primary, mg_image_type type)
Create DICOM-compliant image type value for mammography.
std::vector< std::string > get_mr_storage_sop_classes ()
Get all MR Storage SOP Class UIDs.
bool is_mr_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an MR Storage SOP Class.
bool is_valid_mr_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for MR.
std::vector< std::string > get_nm_transfer_syntaxes ()
Get recommended transfer syntaxes for NM images.
std::string_view to_string (nm_photometric_interpretation interp) noexcept
Convert photometric interpretation enum to DICOM string.
nm_photometric_interpretation parse_nm_photometric_interpretation (std::string_view value) noexcept
Parse DICOM photometric interpretation string.
bool is_valid_nm_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for NM.
std::vector< std::string > get_nm_storage_sop_classes (bool include_retired=true)
Get all NM Storage SOP Class UIDs.
const nm_sop_class_info * get_nm_sop_class_info (std::string_view uid) noexcept
Get information about a specific NM SOP Class.
bool is_nm_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a NM Storage SOP Class.
bool is_nm_multiframe_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID supports multi-frame.
std::string_view to_string (nm_type_of_data type) noexcept
Convert NM type of data to DICOM string.
nm_type_of_data parse_nm_type_of_data (std::string_view value) noexcept
Parse NM type of data from DICOM string.
std::string_view to_string (nm_collimator_type collimator) noexcept
Convert collimator type to DICOM string.
nm_collimator_type parse_nm_collimator_type (std::string_view value) noexcept
Parse collimator type from DICOM string.
std::string_view to_string (nm_radioisotope isotope) noexcept
Get radioisotope name string.
double get_primary_energy_kev (nm_radioisotope isotope) noexcept
Get primary photopeak energy for radioisotope.
std::string_view to_string (nm_whole_body_technique technique) noexcept
Convert whole body technique to string.
std::vector< std::string > get_ophthalmic_storage_sop_classes ()
Get all Ophthalmic Storage SOP Class UIDs.
bool is_ophthalmic_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an Ophthalmic Storage SOP Class.
bool is_valid_ophthalmic_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for ophthalmic imaging.
std::vector< std::string > get_parametric_map_transfer_syntaxes ()
Get recommended transfer syntaxes for Parametric Map objects.
uint16_t get_bits_allocated (pixel_value_representation repr) noexcept
Get bits allocated for a pixel value representation.
pixel_value_representation parse_pixel_value_representation (uint16_t bits_allocated) noexcept
Parse pixel value representation from BitsAllocated value.
bool is_valid_parametric_map_bits_allocated (uint16_t bits_allocated) noexcept
Check if a BitsAllocated value is valid for parametric maps.
std::vector< std::string > get_parametric_map_storage_sop_classes ()
Get all Parametric Map Storage SOP Class UIDs.
const parametric_map_sop_class_info * get_parametric_map_sop_class_info (std::string_view uid) noexcept
Get information about the Parametric Map SOP Class.
bool is_parametric_map_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is Parametric Map Storage.
bool is_valid_parametric_map_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for parametric maps.
std::vector< std::string > get_pet_transfer_syntaxes ()
Get recommended transfer syntaxes for PET images.
std::string_view to_string (pet_photometric_interpretation interp) noexcept
Convert photometric interpretation enum to DICOM string.
pet_photometric_interpretation parse_pet_photometric_interpretation (std::string_view value) noexcept
Parse DICOM photometric interpretation string.
bool is_valid_pet_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for PET.
std::vector< std::string > get_pet_storage_sop_classes (bool include_retired=true)
Get all PET Storage SOP Class UIDs.
const pet_sop_class_info * get_pet_sop_class_info (std::string_view uid) noexcept
Get information about a specific PET SOP Class.
bool is_pet_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a PET Storage SOP Class.
bool is_enhanced_pet_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an Enhanced PET Storage SOP Class.
std::string_view to_string (pet_reconstruction_type recon) noexcept
Convert PET reconstruction type to string.
pet_reconstruction_type parse_pet_reconstruction_type (std::string_view value) noexcept
Parse PET reconstruction type from string.
std::string_view to_string (pet_units units) noexcept
Convert PET units to DICOM string.
pet_units parse_pet_units (std::string_view value) noexcept
Parse PET units from DICOM string.
std::string_view to_string (pet_radiotracer tracer) noexcept
Get radiotracer name string.
std::vector< std::string > get_rt_transfer_syntaxes ()
Get recommended transfer syntaxes for RT objects.
std::vector< std::string > get_rt_storage_sop_classes (bool include_retired=true)
Get all RT Storage SOP Class UIDs.
const rt_sop_class_info * get_rt_sop_class_info (std::string_view uid) noexcept
Get information about a specific RT SOP Class.
bool is_rt_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an RT Storage SOP Class.
bool is_rt_plan_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an RT Plan type.
bool rt_sop_class_has_pixel_data (std::string_view uid) noexcept
Check if a SOP Class UID contains pixel data.
std::string_view to_string (rt_plan_intent intent) noexcept
Convert RT plan intent to DICOM string.
rt_plan_intent parse_rt_plan_intent (std::string_view value) noexcept
Parse RT plan intent from DICOM string.
std::string_view to_string (rt_plan_geometry geometry) noexcept
Convert RT plan geometry to DICOM string.
rt_plan_geometry parse_rt_plan_geometry (std::string_view value) noexcept
Parse RT plan geometry from DICOM string.
std::string_view to_string (rt_dose_type type) noexcept
Convert RT dose type to DICOM string.
rt_dose_type parse_rt_dose_type (std::string_view value) noexcept
Parse RT dose type from DICOM string.
std::string_view to_string (rt_dose_summation_type type) noexcept
Convert RT dose summation type to DICOM string.
rt_dose_summation_type parse_rt_dose_summation_type (std::string_view value) noexcept
Parse RT dose summation type from DICOM string.
std::string_view to_string (rt_dose_units units) noexcept
Convert RT dose units to DICOM string.
rt_dose_units parse_rt_dose_units (std::string_view value) noexcept
Parse RT dose units from DICOM string.
std::string_view to_string (rt_roi_interpreted_type type) noexcept
Convert RT ROI interpreted type to DICOM string.
rt_roi_interpreted_type parse_rt_roi_interpreted_type (std::string_view value) noexcept
Parse RT ROI interpreted type from DICOM string.
std::string_view to_string (rt_roi_generation_algorithm algorithm) noexcept
Convert RT ROI generation algorithm to DICOM string.
rt_roi_generation_algorithm parse_rt_roi_generation_algorithm (std::string_view value) noexcept
Parse RT ROI generation algorithm from DICOM string.
std::string_view to_string (rt_beam_type type) noexcept
Convert RT beam type to DICOM string.
rt_beam_type parse_rt_beam_type (std::string_view value) noexcept
Parse RT beam type from DICOM string.
std::string_view to_string (rt_radiation_type type) noexcept
Convert RT radiation type to DICOM string.
rt_radiation_type parse_rt_radiation_type (std::string_view value) noexcept
Parse RT radiation type from DICOM string.
std::string_view to_string (rt_treatment_delivery_type type) noexcept
Convert RT treatment delivery type to DICOM string.
rt_treatment_delivery_type parse_rt_treatment_delivery_type (std::string_view value) noexcept
Parse RT treatment delivery type from DICOM string.
std::string_view to_string (rt_image_plane plane) noexcept
Convert RT image plane to DICOM string.
rt_image_plane parse_rt_image_plane (std::string_view value) noexcept
Parse RT image plane from DICOM string.
std::vector< std::string > get_seg_transfer_syntaxes ()
Get recommended transfer syntaxes for SEG objects.
std::string_view to_string (segmentation_type type) noexcept
Convert segmentation type to DICOM string.
segmentation_type parse_segmentation_type (std::string_view value) noexcept
Parse segmentation type from DICOM string.
bool is_valid_segmentation_type (std::string_view value) noexcept
Check if segmentation type string is valid.
std::string_view to_string (segmentation_fractional_type type) noexcept
Convert segmentation fractional type to DICOM string.
segmentation_fractional_type parse_segmentation_fractional_type (std::string_view value) noexcept
Parse segmentation fractional type from DICOM string.
std::string_view to_string (segment_algorithm_type type) noexcept
Convert segment algorithm type to DICOM string.
segment_algorithm_type parse_segment_algorithm_type (std::string_view value) noexcept
Parse segment algorithm type from DICOM string.
bool is_valid_segment_algorithm_type (std::string_view value) noexcept
Check if segment algorithm type string is valid.
segment_color get_recommended_segment_color (std::string_view segment_label) noexcept
Get recommended color for common segment types.
std::vector< std::string > get_seg_storage_sop_classes (bool include_surface=true)
Get all SEG Storage SOP Class UIDs.
const seg_sop_class_info * get_seg_sop_class_info (std::string_view uid) noexcept
Get information about a specific SEG SOP Class.
bool is_seg_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a SEG Storage SOP Class.
bool is_surface_segmentation_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is Surface Segmentation.
std::string_view get_segment_category_code (segment_category category) noexcept
Get SNOMED CT code for segment category.
std::string_view get_segment_category_meaning (segment_category category) noexcept
Get code meaning for segment category.
std::vector< std::string > get_sr_transfer_syntaxes ()
Get recommended transfer syntaxes for SR objects.
sr_document_type get_sr_document_type (std::string_view uid) noexcept
Get SR document type for a SOP Class UID.
std::string_view to_string (sr_document_type type) noexcept
Get human-readable name for SR document type.
std::string_view to_string (sr_value_type type) noexcept
Convert SR value type to DICOM string.
sr_value_type parse_sr_value_type (std::string_view value) noexcept
Parse SR value type from DICOM string.
bool is_valid_sr_value_type (std::string_view value) noexcept
Check if SR value type string is valid.
std::string_view to_string (sr_relationship_type type) noexcept
Convert SR relationship type to DICOM string.
sr_relationship_type parse_sr_relationship_type (std::string_view value) noexcept
Parse SR relationship type from DICOM string.
std::string_view to_string (sr_completion_flag flag) noexcept
Convert SR completion flag to DICOM string.
sr_completion_flag parse_sr_completion_flag (std::string_view value) noexcept
Parse SR completion flag from DICOM string.
std::string_view to_string (sr_verification_flag flag) noexcept
Convert SR verification flag to DICOM string.
sr_verification_flag parse_sr_verification_flag (std::string_view value) noexcept
Parse SR verification flag from DICOM string.
std::vector< std::string > get_sr_storage_sop_classes (bool include_cad=true, bool include_dose=true)
Get all SR Storage SOP Class UIDs.
const sr_sop_class_info * get_sr_sop_class_info (std::string_view uid) noexcept
Get information about a specific SR SOP Class.
bool is_sr_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an SR Storage SOP Class.
bool is_cad_sr_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a CAD SR Storage SOP Class.
bool is_dose_sr_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a Dose Report SR Storage SOP Class.
bool sr_supports_spatial_coords (std::string_view uid) noexcept
Check if an SR SOP Class supports spatial coordinates.
std::string_view get_recommended_sr_template (std::string_view uid) noexcept
Get recommended template ID for an SR SOP Class.
std::vector< std::string > get_us_transfer_syntaxes ()
Get recommended transfer syntaxes for US images.
std::string_view to_string (us_photometric_interpretation interp) noexcept
Convert photometric interpretation enum to DICOM string.
us_photometric_interpretation parse_photometric_interpretation (std::string_view value) noexcept
Parse DICOM photometric interpretation string.
bool is_valid_us_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for US.
std::vector< std::string > get_us_storage_sop_classes (bool include_retired=true)
Get all US Storage SOP Class UIDs.
const us_sop_class_info * get_us_sop_class_info (std::string_view uid) noexcept
Get information about a specific US SOP Class.
bool is_us_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a US Storage SOP Class.
bool is_us_multiframe_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a multi-frame US Storage SOP Class.
waveform_type get_waveform_type (std::string_view uid) noexcept
Get waveform type from SOP Class UID.
std::string_view to_string (waveform_type type) noexcept
Get human-readable name for waveform type.
std::vector< std::string > get_waveform_storage_sop_classes (bool include_presentation_state=true, bool include_annotation=true)
Get all Waveform Storage SOP Class UIDs.
const waveform_sop_class_info * get_waveform_sop_class_info (std::string_view uid) noexcept
Get information about a specific Waveform SOP Class.
bool is_waveform_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a Waveform Storage SOP Class.
bool is_waveform_presentation_state_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a Waveform Presentation State SOP Class.
bool is_waveform_annotation_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a Waveform Annotation SOP Class.
std::vector< std::string > get_waveform_transfer_syntaxes ()
Get recommended transfer syntaxes for waveform objects.
std::vector< std::string > get_wsi_storage_sop_classes ()
Get all WSI Storage SOP Class UIDs.
bool is_wsi_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a WSI Storage SOP Class.
bool is_valid_wsi_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for WSI.
std::vector< std::string > get_xa_transfer_syntaxes ()
Get recommended transfer syntaxes for XA images.
std::string_view to_string (xa_photometric_interpretation interp) noexcept
Convert photometric interpretation enum to DICOM string.
xa_photometric_interpretation parse_xa_photometric_interpretation (std::string_view value) noexcept
Parse DICOM photometric interpretation string for XA.
bool is_valid_xa_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for XA.
std::vector< std::string > get_xa_storage_sop_classes (bool include_3d=true)
Get all XA/XRF Storage SOP Class UIDs.
const xa_sop_class_info * get_xa_sop_class_info (std::string_view uid) noexcept
Get information about a specific XA SOP Class.
bool is_xa_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an XA/XRF Storage SOP Class.
bool is_xa_multiframe_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a multi-frame XA Storage SOP Class.
bool is_enhanced_xa_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an enhanced XA SOP Class.
bool is_xa_3d_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a 3D XA SOP Class.
std::string_view to_string (xa_positioner_motion motion) noexcept
Convert positioner motion enum to DICOM string.
constexpr uint16_t get_default_xa_cine_rate () noexcept
Get typical cine rate for cardiac XA.
constexpr size_t get_max_xa_frame_count () noexcept
Get maximum recommended frame count for XA acquisitions.
Variables
constexpr std::string_view ct_image_storage_uid
CT Image Storage SOP Class UID.
constexpr std::string_view enhanced_ct_image_storage_uid
Enhanced CT Image Storage SOP Class UID.
constexpr std::string_view ct_for_processing_image_storage_uid
CT For Processing Image Storage SOP Class UID Multi-energy/spectral CT basis material decomposition images.
constexpr std::string_view mr_image_storage_uid
MR Image Storage SOP Class UID.
constexpr std::string_view enhanced_mr_image_storage_uid
Enhanced MR Image Storage SOP Class UID.
constexpr std::string_view ophthalmic_photo_8bit_storage_uid
Ophthalmic Photography 8 Bit Image Storage.
constexpr std::string_view ophthalmic_photo_16bit_storage_uid
Ophthalmic Photography 16 Bit Image Storage.
constexpr std::string_view ophthalmic_tomography_storage_uid
Ophthalmic Tomography Image Storage (OCT)
constexpr std::string_view wide_field_ophthalmic_photo_storage_uid
Wide Field Ophthalmic Photography SOP Class Storage.
constexpr std::string_view ophthalmic_oct_bscan_analysis_storage_uid
Ophthalmic Optical Coherence Tomography B-scan Volume Analysis Storage.
constexpr std::string_view parametric_map_storage_uid
Parametric Map Storage SOP Class UID.
constexpr std::string_view wsi_image_storage_uid
VL Whole Slide Microscopy Image Storage SOP Class UID.
Primary DX SOP Classes
constexpr std::string_view dx_image_storage_for_presentation_uid
Digital X-Ray Image Storage - For Presentation SOP Class UID Used for images ready for display and clinical review.
constexpr std::string_view dx_image_storage_for_processing_uid
Digital X-Ray Image Storage - For Processing SOP Class UID Used for raw detector data requiring additional processing.
Digital Mammography X-Ray SOP Classes
constexpr std::string_view mammography_image_storage_for_presentation_uid
Digital Mammography X-Ray Image Storage - For Presentation.
constexpr std::string_view mammography_image_storage_for_processing_uid
Digital Mammography X-Ray Image Storage - For Processing.
constexpr std::string_view mg_image_storage_for_presentation_uid
Digital Mammography X-Ray Image Storage - For Presentation SOP Class UID.
constexpr std::string_view mg_image_storage_for_processing_uid
Digital Mammography X-Ray Image Storage - For Processing SOP Class UID.
constexpr std::string_view breast_tomosynthesis_image_storage_uid
Breast Tomosynthesis Image Storage SOP Class UID.
constexpr std::string_view breast_projection_image_storage_for_presentation_uid
Breast Projection X-Ray Image Storage - For Presentation SOP Class UID.
constexpr std::string_view breast_projection_image_storage_for_processing_uid
Breast Projection X-Ray Image Storage - For Processing SOP Class UID.
Digital Intra-Oral X-Ray SOP Classes
constexpr std::string_view intraoral_image_storage_for_presentation_uid
Digital Intra-Oral X-Ray Image Storage - For Presentation.
constexpr std::string_view intraoral_image_storage_for_processing_uid
Digital Intra-Oral X-Ray Image Storage - For Processing.
Primary NM SOP Classes
constexpr std::string_view nm_image_storage_uid
Nuclear Medicine Image Storage SOP Class UID.
Retired NM SOP Classes (Legacy Support)
constexpr std::string_view nm_image_storage_retired_uid
Nuclear Medicine Image Storage (Retired) - for legacy systems.
Primary PET SOP Classes
constexpr std::string_view pet_image_storage_uid
PET Image Storage SOP Class UID.
constexpr std::string_view enhanced_pet_image_storage_uid
Enhanced PET Image Storage SOP Class UID.
constexpr std::string_view legacy_converted_enhanced_pet_image_storage_uid
Legacy Converted Enhanced PET Image Storage SOP Class UID.
Primary RT SOP Classes
constexpr std::string_view rt_plan_storage_uid
RT Plan Storage SOP Class UID.
constexpr std::string_view rt_dose_storage_uid
RT Dose Storage SOP Class UID.
constexpr std::string_view rt_structure_set_storage_uid
RT Structure Set Storage SOP Class UID.
constexpr std::string_view rt_image_storage_uid
RT Image Storage SOP Class UID.
constexpr std::string_view rt_beams_treatment_record_storage_uid
RT Beams Treatment Record Storage SOP Class UID.
constexpr std::string_view rt_brachy_treatment_record_storage_uid
RT Brachy Treatment Record Storage SOP Class UID.
constexpr std::string_view rt_treatment_summary_record_storage_uid
RT Treatment Summary Record Storage SOP Class UID.
constexpr std::string_view rt_ion_plan_storage_uid
RT Ion Plan Storage SOP Class UID.
constexpr std::string_view rt_ion_beams_treatment_record_storage_uid
RT Ion Beams Treatment Record Storage SOP Class UID.
Primary SEG SOP Classes
constexpr std::string_view segmentation_storage_uid
Segmentation Storage SOP Class UID.
constexpr std::string_view surface_segmentation_storage_uid
Surface Segmentation Storage SOP Class UID.
constexpr std::string_view heightmap_segmentation_storage_uid
Heightmap Segmentation Storage SOP Class UID (Supplement 240)
constexpr std::string_view label_map_segmentation_storage_uid
Label Map Segmentation Storage SOP Class UID (Supplement 243)
Basic SR SOP Classes
constexpr std::string_view basic_text_sr_storage_uid
Basic Text SR Storage SOP Class UID.
constexpr std::string_view enhanced_sr_storage_uid
Enhanced SR Storage SOP Class UID.
constexpr std::string_view comprehensive_sr_storage_uid
Comprehensive SR Storage SOP Class UID.
constexpr std::string_view comprehensive_3d_sr_storage_uid
Comprehensive 3D SR Storage SOP Class UID.
constexpr std::string_view extensible_sr_storage_uid
Extensible SR Storage SOP Class UID.
Specialized SR SOP Classes
constexpr std::string_view mammography_cad_sr_storage_uid
Mammography CAD SR Storage SOP Class UID.
constexpr std::string_view chest_cad_sr_storage_uid
Chest CAD SR Storage SOP Class UID.
constexpr std::string_view colon_cad_sr_storage_uid
Colon CAD SR Storage SOP Class UID.
constexpr std::string_view xray_radiation_dose_sr_storage_uid
X-Ray Radiation Dose SR Storage SOP Class UID.
constexpr std::string_view radiopharmaceutical_radiation_dose_sr_storage_uid
Radiopharmaceutical Radiation Dose SR Storage SOP Class UID.
constexpr std::string_view acquisition_context_sr_storage_uid
Acquisition Context SR Storage SOP Class UID.
constexpr std::string_view simplified_adult_echo_sr_storage_uid
Simplified Adult Echo SR Storage SOP Class UID.
constexpr std::string_view patient_radiation_dose_sr_storage_uid
Patient Radiation Dose SR Storage SOP Class UID.
constexpr std::string_view planned_imaging_agent_admin_sr_storage_uid
Planned Imaging Agent Administration SR Storage SOP Class UID.
constexpr std::string_view performed_imaging_agent_admin_sr_storage_uid
Performed Imaging Agent Administration SR Storage SOP Class UID.
constexpr std::string_view enhanced_xray_radiation_dose_sr_storage_uid
Enhanced X-Ray Radiation Dose SR Storage SOP Class UID.
Key Object Selection Document
constexpr std::string_view key_object_selection_document_storage_uid
Key Object Selection Document Storage SOP Class UID.
Primary US SOP Classes
constexpr std::string_view us_image_storage_uid
US Image Storage SOP Class UID (single-frame)
constexpr std::string_view us_multiframe_image_storage_uid
US Multi-frame Image Storage SOP Class UID (cine loops)
Retired US SOP Classes (Legacy Support)
constexpr std::string_view us_image_storage_retired_uid
US Image Storage (Retired) - for legacy systems.
constexpr std::string_view us_multiframe_image_storage_retired_uid
US Multi-frame Image Storage (Retired) - for legacy systems.
Base Waveform Storage SOP Classes
constexpr std::string_view twelve_lead_ecg_storage_uid
12-lead ECG Waveform Storage SOP Class UID
constexpr std::string_view general_ecg_storage_uid
General ECG Waveform Storage SOP Class UID.
constexpr std::string_view ambulatory_ecg_storage_uid
Ambulatory ECG Waveform Storage SOP Class UID.
constexpr std::string_view hemodynamic_waveform_storage_uid
Hemodynamic Waveform Storage SOP Class UID.
constexpr std::string_view cardiac_ep_waveform_storage_uid
Basic Cardiac Electrophysiology Waveform Storage SOP Class UID.
constexpr std::string_view basic_voice_audio_storage_uid
Basic Voice Audio Waveform Storage SOP Class UID.
constexpr std::string_view general_audio_waveform_storage_uid
General Audio Waveform Storage SOP Class UID.
constexpr std::string_view arterial_pulse_waveform_storage_uid
Arterial Pulse Waveform Storage SOP Class UID.
constexpr std::string_view respiratory_waveform_storage_uid
Respiratory Waveform Storage SOP Class UID.
constexpr std::string_view multichannel_respiratory_waveform_storage_uid
Multi-channel Respiratory Waveform Storage SOP Class UID.
constexpr std::string_view routine_scalp_eeg_storage_uid
Routine Scalp Electroencephalogram Waveform Storage SOP Class UID.
constexpr std::string_view emg_waveform_storage_uid
Electromyogram Waveform Storage SOP Class UID.
constexpr std::string_view eog_waveform_storage_uid
Electrooculogram Waveform Storage SOP Class UID.
constexpr std::string_view sleep_eeg_storage_uid
Sleep Electroencephalogram Waveform Storage SOP Class UID.
constexpr std::string_view body_position_waveform_storage_uid
Body Position Waveform Storage SOP Class UID.
Waveform Presentation State and Annotation SOP Classes
constexpr std::string_view waveform_presentation_state_storage_uid
Waveform Presentation State Storage SOP Class UID.
constexpr std::string_view waveform_annotation_storage_uid
Waveform Annotation Storage SOP Class UID.
Primary XA/XRF SOP Classes
constexpr std::string_view xa_image_storage_uid
XA Image Storage SOP Class UID (single/multi-frame)
constexpr std::string_view enhanced_xa_image_storage_uid
Enhanced XA Image Storage SOP Class UID (enhanced IOD)
constexpr std::string_view xrf_image_storage_uid
XRF Image Storage SOP Class UID (X-Ray Radiofluoroscopic)
3D Angiographic SOP Classes
constexpr std::string_view xray_3d_angiographic_image_storage_uid
X-Ray 3D Angiographic Image Storage SOP Class UID (3D rotational)
constexpr std::string_view xray_3d_craniofacial_image_storage_uid
X-Ray 3D Craniofacial Image Storage SOP Class UID.
Enumeration Type Documentation
breast_laterality
enum class kcenon::pacs::services::sop_classes::breast_laterality strong
Breast laterality enumeration.
Specifies which breast is being imaged. This is a critical attribute for mammography workflow and helps prevent laterality errors in clinical practice.
See also
DICOM Tag (0020,0060) - Laterality
DICOM Tag (0020,0062) - Image Laterality
Enumerator
left
Left breast (DICOM value: "L")
right
Right breast (DICOM value: "R")
bilateral
Both breasts (DICOM value: "B") - used for comparison views.
unknown
Unknown or unspecified laterality.
Definition at line 105 of file mg_storage.hpp.
{
    left,
    right,
    bilateral,
    unknown
};
cad_processing_status
enum class kcenon::pacs::services::sop_classes::cad_processing_status strong
CAD (Computer-Aided Detection) processing status.
Indicates whether and how CAD analysis has been performed on the image.
Enumerator
not_processed
CAD has not been run on this image.
processed_no_findings
CAD completed with no findings.
processed_findings
CAD completed with findings.
processing_failed
CAD processing failed.
pending
CAD processing is pending.
Definition at line 350 of file mg_storage.hpp.
{
    not_processed,
    processed_no_findings,
    processed_findings,
    processing_failed,
    pending
};
dx_body_part
enum class kcenon::pacs::services::sop_classes::dx_body_part strong
Common body parts for DX imaging.
These correspond to standard DICOM Body Part Examined (0018,0015) values.
Enumerator
chest
CHEST.
abdomen
ABDOMEN.
pelvis
PELVIS.
spine
SPINE.
skull
SKULL.
hand
HAND.
foot
FOOT.
knee
KNEE.
elbow
ELBOW.
shoulder
SHOULDER.
hip
HIP.
wrist
WRIST.
ankle
ANKLE.
extremity
EXTREMITY (general)
breast
BREAST (for mammography)
other
Other/unspecified.
Definition at line 325 of file dx_storage.hpp.
{
    chest,
    abdomen,
    pelvis,
    spine,
    skull,
    hand,
    foot,
    knee,
    elbow,
    shoulder,
    hip,
    wrist,
    ankle,
    extremity,
    breast,
    other
};
dx_detector_type
enum class kcenon::pacs::services::sop_classes::dx_detector_type strong
DX detector technology types.
Indicates the type of digital detector used for image acquisition.
Enumerator
direct
Direct conversion (a-Se based)
indirect
Indirect conversion (scintillator + photodiode)
storage
Storage phosphor (CR-like)
film
Film digitizer (rare for DX)
Definition at line 217 of file dx_storage.hpp.
{
    direct,
    indirect,
    storage,
    film
};
dx_image_type
enum class kcenon::pacs::services::sop_classes::dx_image_type strong
DX image purpose classification.
Enumerator
for_presentation
Ready for display and diagnosis.
for_processing
Raw data requiring further processing.
Definition at line 164 of file dx_storage.hpp.
{
    for_presentation,
    for_processing
};
dx_photometric_interpretation
enum class kcenon::pacs::services::sop_classes::dx_photometric_interpretation strong
Supported photometric interpretations for DX images.
DX images are always grayscale. MONOCHROME1 means high values are dark (as on film), while MONOCHROME2 means high values are bright.
Enumerator
monochrome1
Minimum pixel value = white (inverted)
monochrome2
Minimum pixel value = black (standard)
Definition at line 130 of file dx_storage.hpp.
{
    monochrome1,
    monochrome2
};
dx_view_position
enum class kcenon::pacs::services::sop_classes::dx_view_position strong
Common radiographic view positions for DX images.
View position indicates the direction of the X-ray beam relative to the patient and detector.
Enumerator
ap
Anterior-Posterior.
pa
Posterior-Anterior.
lateral
Lateral (left or right)
oblique
Oblique projection.
other
Other/unspecified.
Definition at line 186 of file dx_storage.hpp.
{
    ap,
    pa,
    lateral,
    oblique,
    other
};
mg_image_type
enum class kcenon::pacs::services::sop_classes::mg_image_type strong
Mammography image purpose classification.
Mammography images can be either for presentation (display-ready with applied processing) or for processing (raw data requiring additional image processing).
Enumerator
for_presentation
Ready for display and diagnosis.
for_processing
Raw data requiring further processing.
Definition at line 329 of file mg_storage.hpp.
{
    for_presentation,
    for_processing
};
mg_view_position
enum class kcenon::pacs::services::sop_classes::mg_view_position strong
Mammography-specific view positions.
Standard mammography views as defined by the ACR (American College of Radiology) and used in DICOM. View position is essential for proper image interpretation and comparison studies.
See also
DICOM Tag (0018,5101) - View Position
ACR BI-RADS Mammography Atlas
Enumerator
cc
Craniocaudal - standard superior-inferior view.
mlo
Mediolateral Oblique - angled lateral view (most common)
ml
Mediolateral - true lateral (medial to lateral)
lm
Lateromedial - true lateral (lateral to medial)
xccl
Exaggerated CC Laterally - for lateral breast tissue.
xccm
Exaggerated CC Medially - for medial breast tissue.
fb
From Below - inferior to superior view.
sio
Superolateral to Inferomedial Oblique.
iso
Inferomedial to Superolateral Oblique.
cv
Cleavage View - for medial breast tissue.
at
Axillary Tail - for axillary extension.
spot
Spot compression view.
mag
Magnification view.
spot_mag
Spot compression with magnification.
rl
Rolled Lateral.
rm
Rolled Medial.
rs
Rolled Superior.
ri
Rolled Inferior.
tangen
Tangential view.
implant
Implant displaced view (Eklund technique)
id
Implant Displaced (alternate code)
other
Other or unspecified view.
Definition at line 147 of file mg_storage.hpp.
{
    // Standard screening views
    cc,
    mlo,
    // Additional diagnostic views
    ml,
    lm,
    xccl,
    xccm,
    fb,
    sio,
    iso,
    cv,
    at,
    // Spot/magnification views
    spot,
    mag,
    spot_mag,
    rl,
    rm,
    rs,
    ri,
    // Specialized views
    tangen,
    implant,
    id,
    // Other
    other
};
nm_collimator_type
enum class kcenon::pacs::services::sop_classes::nm_collimator_type strong
NM collimator type.
Enumerator
parallel
PARA - Parallel hole.
fan_beam
FANB - Fan beam.
cone_beam
CONE - Cone beam.
pinhole
PINH - Pinhole.
diverging
DIVG - Diverging.
converging
CVGB - Converging.
none
NONE - No collimator.
Definition at line 230 of file nm_storage.hpp.
{
    parallel,
    fan_beam,
    cone_beam,
    pinhole,
    diverging,
    converging,
    none
};
nm_detector_geometry
enum class kcenon::pacs::services::sop_classes::nm_detector_geometry strong
NM detector geometry type.
Enumerator
planar
Planar detector (2D)
ring
Ring detector (PET-like)
partial_ring
Partial ring.
curved
Curved detector.
cylindrical
Cylindrical detector.
Definition at line 219 of file nm_storage.hpp.
{
    planar,
    ring,
    partial_ring,
    curved,
    cylindrical
};
nm_photometric_interpretation
enum class kcenon::pacs::services::sop_classes::nm_photometric_interpretation strong
Supported photometric interpretations for NM images.
NM images are typically grayscale, representing count or activity values.
Enumerator
monochrome2
Minimum pixel = black (standard)
palette_color
Pseudo-color via lookup table (for display)
Definition at line 101 of file nm_storage.hpp.
{
    monochrome2,
    palette_color
};
nm_radioisotope
enum class kcenon::pacs::services::sop_classes::nm_radioisotope strong
Common radioisotopes used in NM imaging.
Enumerator
tc99m
Technetium-99m (140 keV)
i131
Iodine-131 (364 keV)
i123
Iodine-123 (159 keV)
tl201
Thallium-201 (71, 167 keV)
ga67
Gallium-67 (93, 185, 300 keV)
in111
Indium-111 (171, 245 keV)
f18
Fluorine-18 (511 keV - for PET)
other
Other radioisotope.
Definition at line 270 of file nm_storage.hpp.
{
    tc99m,
    i131,
    i123,
    tl201,
    ga67,
    in111,
    f18,
    other
};
nm_rotation_direction
enum class kcenon::pacs::services::sop_classes::nm_rotation_direction strong
NM rotation direction for SPECT.
Enumerator
cw
CW - Clockwise.
cc
CC - Counter-clockwise.
Definition at line 302 of file nm_storage.hpp.
{
    cw,
    cc
};
nm_scan_arc
enum class kcenon::pacs::services::sop_classes::nm_scan_arc strong
NM scan arc for SPECT.
Enumerator
arc_180
180 degree arc
arc_360
360 degree arc (full rotation)
Definition at line 310 of file nm_storage.hpp.
                       {
    arc_180,
    arc_360
};
nm_type_of_data
enum class kcenon::pacs::services::sop_classes::nm_type_of_data strong
NM image type (Type of Data)
Enumerator
static_image
STATIC - static planar image.
dynamic
DYNAMIC - dynamic study (time series)
gated
GATED - cardiac gated acquisition.
whole_body
WHOLE BODY - whole body scan.
recon_tomo
RECON TOMO - reconstructed SPECT.
recon_gated_tomo
RECON GATED TOMO - reconstructed gated SPECT.
tomo
TOMO - SPECT raw projection data.
gated_tomo
GATED TOMO - gated SPECT projections.
Definition at line 187 of file nm_storage.hpp.
{
    static_image,
    dynamic,
    gated,
    whole_body,
    recon_tomo,
    recon_gated_tomo,
    tomo,
    gated_tomo
};
nm_whole_body_technique
enum class kcenon::pacs::services::sop_classes::nm_whole_body_technique strong
Patient orientation for whole body scan.
Enumerator
single_pass
1PASS - Single pass
multi_pass
2PASS - Multiple pass (anterior/posterior)
stepping
STEP - Stepping acquisition.
Definition at line 318 of file nm_storage.hpp.
{
    single_pass,
    multi_pass,
    stepping
};
pet_attenuation_correction
enum class kcenon::pacs::services::sop_classes::pet_attenuation_correction strong
Attenuation correction method.
Enumerator
none
No attenuation correction.
measured
Measured (transmission scan)
calculated
Calculated from CT.
ct_based
CT-based attenuation correction (PET/CT)
Definition at line 206 of file pet_storage.hpp.
{
    none,
    measured,
    calculated,
    ct_based
};
pet_image_type
enum class kcenon::pacs::services::sop_classes::pet_image_type strong
PET image type indicating the nature of the image.
Enumerator
original
ORIGINAL - directly acquired.
derived
DERIVED - post-processed.
primary
PRIMARY - primary image.
secondary
SECONDARY - secondary reconstruction.
Definition at line 186 of file pet_storage.hpp.
{
    original,
    derived,
    primary,
    secondary
};
pet_photometric_interpretation
enum class kcenon::pacs::services::sop_classes::pet_photometric_interpretation strong
Supported photometric interpretations for PET images.
PET images are typically grayscale, representing radiotracer uptake values.
Enumerator
monochrome2
Minimum pixel = black (standard for PET)
Definition at line 100 of file pet_storage.hpp.
{
    monochrome2
};
pet_radiotracer
enum class kcenon::pacs::services::sop_classes::pet_radiotracer strong
Common PET radiotracers.
Enumerator
fdg
18F-FDG (Fluorodeoxyglucose)
naf
18F-NaF (Sodium Fluoride)
flt
18F-FLT (Fluorothymidine)
fdopa
18F-FDOPA
ammonia
13N-Ammonia
rubidium
82Rb (Rubidium-82)
gallium_dotatate
68Ga-DOTATATE
psma
PSMA agents.
other
Other tracers.
Definition at line 289 of file pet_storage.hpp.
{
    fdg,
    naf,
    flt,
    fdopa,
    ammonia,
    rubidium,
    gallium_dotatate,
    psma,
    other
};
pet_reconstruction_type
enum class kcenon::pacs::services::sop_classes::pet_reconstruction_type strong
PET reconstruction algorithm type.
Enumerator
fbp
Filtered Back Projection.
osem
Ordered Subset Expectation Maximization.
mlem
Maximum Likelihood Expectation Maximization.
tof_osem
Time-of-Flight OSEM.
psf_osem
Point Spread Function OSEM.
other
Other algorithm.
Definition at line 226 of file pet_storage.hpp.
{
    fbp,
    osem,
    mlem,
    tof_osem,
    psf_osem,
    other
};
pet_scatter_correction
enum class kcenon::pacs::services::sop_classes::pet_scatter_correction strong
Scatter correction method.
Enumerator
none
No scatter correction.
single_scatter
Single scatter simulation.
convolution
Convolution-subtraction method.
model_based
Model-based scatter correction.
Definition at line 216 of file pet_storage.hpp.
{
    none,
    single_scatter,
    convolution,
    model_based
};
pet_series_type
enum class kcenon::pacs::services::sop_classes::pet_series_type strong
PET series type code.
Enumerator
static_image
STATIC - static acquisition.
dynamic
DYNAMIC - dynamic (time series)
gated
GATED - cardiac/respiratory gated.
whole_body
WHOLE BODY - whole body scan.
Definition at line 196 of file pet_storage.hpp.
{
    static_image,
    dynamic,
    gated,
    whole_body
};
pet_units
enum class kcenon::pacs::services::sop_classes::pet_units strong
PET units type (Units attribute 0054,1001)
Enumerator
cnts
Counts.
bqml
Bq/ml (Becquerels per milliliter)
gml
g/ml (SUVbw)
suv_bw
Standardized Uptake Value (body weight)
suv_lbm
SUV (lean body mass)
suv_bsa
SUV (body surface area)
percent_id_gram
Percent injected dose per gram.
other
Other units.
Definition at line 257 of file pet_storage.hpp.
                     {
    cnts,
    bqml,
    gml,
    suv_bw,
    suv_lbm,
    suv_bsa,
    percent_id_gram,
    other
};
pixel_value_representation
enum class kcenon::pacs::services::sop_classes::pixel_value_representation strong
Pixel value representation for parametric map data.
Defines how the pixel data is encoded in the Parametric Map. Per DICOM PS3.3 C.7.6.16.2.17, parametric maps use float or double.
Enumerator
float32
32-bit IEEE 754 floating point (BitsAllocated=32)
float64
64-bit IEEE 754 floating point (BitsAllocated=64)
Definition at line 88 of file parametric_map_storage.hpp.
{
    float32,
    float64
};
rt_beam_type
enum class kcenon::pacs::services::sop_classes::rt_beam_type strong
RT Beam Type.
Enumerator
static_beam
STATIC - Static beam.
dynamic
DYNAMIC - Dynamic beam (IMRT, VMAT)
Definition at line 385 of file rt_storage.hpp.
{
    static_beam,
    dynamic
};
rt_dose_summation_type
enum class kcenon::pacs::services::sop_classes::rt_dose_summation_type strong
RT Dose Summation Type.
Enumerator
plan
PLAN - Single plan dose.
multi_plan
MULTI_PLAN - Multi-plan sum.
fraction
FRACTION - Single fraction dose.
beam
BEAM - Single beam dose.
brachy
BRACHY - Brachytherapy dose.
fraction_session
FRACTION_SESSION - Single fraction session dose.
beam_session
BEAM_SESSION - Single beam session dose.
brachy_session
BRACHY_SESSION - Brachytherapy session dose.
control_point
CONTROL_POINT - Single control point dose.
record
RECORD - Treatment record dose.
Definition at line 259 of file rt_storage.hpp.
{
    plan,
    multi_plan,
    fraction,
    beam,
    brachy,
    fraction_session,
    beam_session,
    brachy_session,
    control_point,
    record
};
rt_dose_type
enum class kcenon::pacs::services::sop_classes::rt_dose_type strong
RT Dose Type.
Enumerator
physical
PHYSICAL - Physical dose.
effective
EFFECTIVE - Effective dose (RBE weighted)
error
ERROR - Dose error/uncertainty.
Definition at line 236 of file rt_storage.hpp.
{
    physical,
    effective,
    error
};
rt_dose_units
enum class kcenon::pacs::services::sop_classes::rt_dose_units strong
RT Dose Units.
Enumerator
gy
GY - Gray (absorbed dose)
relative
RELATIVE - Relative dose.
Definition at line 289 of file rt_storage.hpp.
{
    gy,
    relative
};
rt_image_plane
enum class kcenon::pacs::services::sop_classes::rt_image_plane strong
RT Image Type values (as used in Image Type attribute)
Enumerator
axial
AXIAL - Axial plane.
localizer
LOCALIZER - Localizer/scout image.
drr
DRR - Digitally Reconstructed Radiograph.
portal
PORTAL - Portal image.
fluence
FLUENCE - Fluence map.
Definition at line 462 of file rt_storage.hpp.
{
    axial,
    localizer,
    drr,
    portal,
    fluence
};
rt_plan_geometry
enum class kcenon::pacs::services::sop_classes::rt_plan_geometry strong
RT Plan Geometry.
Enumerator
patient
PATIENT - Patient-based plan.
treatment_device
TREATMENT_DEVICE - Device-based plan.
Definition at line 210 of file rt_storage.hpp.
{
    patient,
    treatment_device
};
rt_plan_intent
enum class kcenon::pacs::services::sop_classes::rt_plan_intent strong
RT Plan Intent.
Enumerator
curative
CURATIVE - Treatment with curative intent.
palliative
PALLIATIVE - Treatment for symptom relief.
prophylactic
PROPHYLACTIC - Preventive treatment.
verification
VERIFICATION - Plan verification.
machine_qa
MACHINE_QA - Machine quality assurance.
research
RESEARCH - Research protocol.
service
SERVICE - Equipment service.
Definition at line 183 of file rt_storage.hpp.
{
    curative,
    palliative,
    prophylactic,
    verification,
    machine_qa,
    research,
    service
};
rt_radiation_type
enum class kcenon::pacs::services::sop_classes::rt_radiation_type strong
RT Radiation Type.
Enumerator
photon
PHOTON - X-ray photons.
electron
ELECTRON - Electrons.
neutron
NEUTRON - Neutrons.
proton
PROTON - Protons.
ion
ION - Heavy ions (carbon, etc.)
Definition at line 407 of file rt_storage.hpp.
{
    photon,
    electron,
    neutron,
    proton,
    ion
};
rt_roi_generation_algorithm
enum class kcenon::pacs::services::sop_classes::rt_roi_generation_algorithm strong
RT ROI Generation Algorithm.
Enumerator
automatic
AUTOMATIC - Automated segmentation.
semiautomatic
SEMIAUTOMATIC - Semi-automated with user input.
manual
MANUAL - Manual contouring.
Definition at line 357 of file rt_storage.hpp.
{
    automatic,
    semiautomatic,
    manual
};
rt_roi_interpreted_type
enum class kcenon::pacs::services::sop_classes::rt_roi_interpreted_type strong
RT ROI Interpreted Type.
Enumerator
external
EXTERNAL - External patient surface.
ptv
PTV - Planning Target Volume.
ctv
CTV - Clinical Target Volume.
gtv
GTV - Gross Tumor Volume.
organ
ORGAN - Organ at risk.
avoidance
AVOIDANCE - Avoidance structure.
treated_volume
TREATED_VOLUME - Treated volume.
irrad_volume
IRRAD_VOLUME - Irradiated volume.
bolus
BOLUS - Bolus material.
brachy_channel
BRACHY_CHANNEL - Brachytherapy channel.
brachy_accessory
BRACHY_ACCESSORY - Brachytherapy accessory.
brachy_src_appl
BRACHY_SRC_APPL - Brachytherapy source applicator.
brachy_chnl_shld
BRACHY_CHNL_SHLD - Brachytherapy channel shield.
support
SUPPORT - Patient support structure.
fixation
FIXATION - Patient fixation device.
dose_region
DOSE_REGION - Dose reference region.
contrast_agent
CONTRAST_AGENT - Contrast agent region.
cavity
CAVITY - Cavity structure.
marker
MARKER - Marker structure.
registration
REGISTRATION - Registration structure.
isocenter
ISOCENTER - Isocenter point.
control_point
CONTROL - Control point marker.
Definition at line 315 of file rt_storage.hpp.
{
    external,
    ptv,
    ctv,
    gtv,
    organ,
    avoidance,
    treated_volume,
    irrad_volume,
    bolus,
    brachy_channel,
    brachy_accessory,
    brachy_src_appl,
    brachy_chnl_shld,
    support,
    fixation,
    dose_region,
    contrast_agent,
    cavity,
    marker,
    registration,
    isocenter,
    control_point
};
rt_treatment_delivery_type
enum class kcenon::pacs::services::sop_classes::rt_treatment_delivery_type strong
RT Treatment Delivery Type.
Enumerator
treatment
TREATMENT - Actual treatment.
open_portfilm
OPEN_PORTFILM - Open field portal image.
trmt_portfilm
TRMT_PORTFILM - Treatment field portal image.
continuation
CONTINUATION - Continuation of interrupted treatment.
setup
SETUP - Setup verification.
Definition at line 432 of file rt_storage.hpp.
{
    treatment,
    open_portfilm,
    trmt_portfilm,
    continuation,
    setup
};
segment_algorithm_type
enum class kcenon::pacs::services::sop_classes::segment_algorithm_type strong
Segment algorithm type (0062,0008)
Defines how the segment was created.
Enumerator
automatic
AUTOMATIC - Fully automated segmentation.
semiautomatic
SEMIAUTOMATIC - Semi-automated with user input.
manual
MANUAL - Manual segmentation.
Definition at line 168 of file seg_storage.hpp.
{
    automatic,
    semiautomatic,
    manual
};
segment_category
enum class kcenon::pacs::services::sop_classes::segment_category strong
Common anatomical property categories (CID 7150)
Predefined category codes for segment categorization
Enumerator
tissue
Tissue type (organ, muscle, etc.)
anatomical_structure
Named anatomical structure.
physical_object
Physical object (implant, etc.)
morphologically_abnormal
Tumor, lesion, etc.
function
Functional region.
spatial
Spatial reference.
body_substance
Body fluid, substance.
Definition at line 276 of file seg_storage.hpp.
{
    tissue,
    anatomical_structure,
    physical_object,
    morphologically_abnormal,
    function,
    spatial,
    body_substance
};
segmentation_fractional_type
enum class kcenon::pacs::services::sop_classes::segmentation_fractional_type strong
Segmentation fractional type (0062,0010)
Defines the meaning of fractional values when Segmentation Type is FRACTIONAL.
Enumerator
probability
PROBABILITY - Values represent probability (0.0-1.0)
occupancy
OCCUPANCY - Values represent fractional occupancy.
Definition at line 139 of file seg_storage.hpp.
{
    probability,
    occupancy
};
segmentation_type
enum class kcenon::pacs::services::sop_classes::segmentation_type strong
Segmentation type (0062,0001)
Defines whether the segmentation is binary or fractional.
Enumerator
binary
BINARY - Binary segmentation (0 or 1)
fractional
FRACTIONAL - Fractional/probabilistic segmentation.
Definition at line 104 of file seg_storage.hpp.
{
    binary,
    fractional
};
sr_completion_flag
enum class kcenon::pacs::services::sop_classes::sr_completion_flag strong
SR Completion Flag (0040,A491)
Enumerator
partial
PARTIAL - Document is not complete.
complete
COMPLETE - Document is complete.
Definition at line 284 of file sr_storage.hpp.
{
    partial,
    complete
};
sr_document_type
enum class kcenon::pacs::services::sop_classes::sr_document_type strong
SR Document type classification.
Categorizes SR documents by their primary purpose.
Enumerator
basic_text
Basic Text SR - Simple text reports.
enhanced
Enhanced SR - References to images/waveforms.
comprehensive
Comprehensive SR - Complex with spatial coords.
comprehensive_3d
Comprehensive 3D SR - 3D spatial coordinates.
extensible
Extensible SR - Template-based.
key_object_selection
Key Object Selection - Image selection.
cad
CAD SR - Computer-aided detection results.
dose_report
Dose Report - Radiation dose information.
procedure_log
Procedure Log - Procedure documentation.
other
Other specialized SR types.
Definition at line 166 of file sr_storage.hpp.
{
    basic_text,
    enhanced,
    comprehensive,
    comprehensive_3d,
    extensible,
    key_object_selection,
    cad,
    dose_report,
    procedure_log,
    other
};
sr_relationship_type
enum class kcenon::pacs::services::sop_classes::sr_relationship_type strong
SR Content Item Relationship Type (0040,A010)
Defines the relationship between content items in the SR tree.
Enumerator
contains
CONTAINS - Parent contains child.
has_obs_context
HAS OBS CONTEXT - Observation context.
has_acq_context
HAS ACQ CONTEXT - Acquisition context.
has_concept_mod
HAS CONCEPT MOD - Concept modifier.
has_properties
HAS PROPERTIES - Property value.
inferred_from
INFERRED FROM - Inference source.
selected_from
SELECTED FROM - Selection source.
unknown
Unknown relationship.
Definition at line 252 of file sr_storage.hpp.
{
    contains,
    has_obs_context,
    has_acq_context,
    has_concept_mod,
    has_properties,
    inferred_from,
    selected_from,
    unknown
};
sr_value_type
enum class kcenon::pacs::services::sop_classes::sr_value_type strong
SR Content Item Value Type (0040,A040)
Defines the type of value contained in a content item.
Enumerator
text
TEXT - Free text.
code
CODE - Coded entry.
num
NUM - Numeric measurement.
datetime
DATETIME - Date/time value.
date
DATE - Date value.
time
TIME - Time value.
uidref
UIDREF - UID reference.
pname
PNAME - Person name.
composite
COMPOSITE - Reference to composite object.
image
IMAGE - Reference to image.
waveform
WAVEFORM - Reference to waveform.
scoord
SCOORD - Spatial coordinates (2D)
scoord3d
SCOORD3D - Spatial coordinates (3D)
tcoord
TCOORD - Temporal coordinates.
container
CONTAINER - Container for other items.
table
TABLE - Tabular data (Extensible SR)
unknown
Unknown value type.
Definition at line 202 of file sr_storage.hpp.
{
    text,
    code,
    num,
    datetime,
    date,
    time,
    uidref,
    pname,
    composite,
    image,
    waveform,
    scoord,
    scoord3d,
    tcoord,
    container,
    table,
    unknown
};
sr_verification_flag
enum class kcenon::pacs::services::sop_classes::sr_verification_flag strong
SR Verification Flag (0040,A493)
Enumerator
unverified
UNVERIFIED - Not verified.
verified
VERIFIED - Verified by authorized person.
Definition at line 306 of file sr_storage.hpp.
{
    unverified,
    verified
};
us_photometric_interpretation
enum class kcenon::pacs::services::sop_classes::us_photometric_interpretation strong
Supported photometric interpretations for US images.
Enumerator
monochrome1
Minimum pixel = white.
monochrome2
Minimum pixel = black (most common)
palette_color
Pseudo-color via lookup table.
rgb
Full color RGB.
ybr_full
YCbCr full range.
ybr_full_422
YCbCr 4:2:2 subsampled.
Definition at line 108 of file us_storage.hpp.
{
    monochrome1,
    monochrome2,
    palette_color,
    rgb,
    ybr_full,
    ybr_full_422
};
us_region_data_type
enum class kcenon::pacs::services::sop_classes::us_region_data_type : uint16_t strong
US Region data type.
Defines the type of data in an ultrasound region
Enumerator
tissue
Tissue characterization.
blood
Blood/flow.
color_flow
Color flow Doppler.
elastography
Tissue stiffness.
b_mode
B-mode amplitude.
Definition at line 215 of file us_storage.hpp.
                               : uint16_t {
    tissue = 0x0001,
    blood = 0x0002,
    color_flow = 0x0003,
    elastography = 0x0004,
    b_mode = 0x0005
};
us_region_spatial_format
enum class kcenon::pacs::services::sop_classes::us_region_spatial_format : uint16_t strong
US Region spatial format.
Defines the spatial organization of ultrasound regions as specified in DICOM PS3.3 Section C.8.5.5
Enumerator
none
No geometric information.
two_d
2D format (sector, linear, etc.)
m_mode
M-mode (time-motion)
spectral
Spectral Doppler.
wave_form
Physiological waveform.
graphics
Graphics overlay.
Definition at line 201 of file us_storage.hpp.
                                    : uint16_t {
    none = 0x0000,
    two_d = 0x0001,
    m_mode = 0x0002,
    spectral = 0x0003,
    wave_form = 0x0004,
    graphics = 0x0005
};
waveform_type
enum class kcenon::pacs::services::sop_classes::waveform_type strong
Waveform type classification.
Enumerator
ecg_12lead
12-lead ECG
ecg_general
General ECG.
ecg_ambulatory
Ambulatory ECG (Holter)
hemodynamic
Hemodynamic monitoring.
cardiac_ep
Cardiac electrophysiology.
audio_basic
Basic voice audio.
audio_general
General audio.
arterial_pulse
Arterial pulse waveform.
respiratory
Single-channel respiratory.
respiratory_multi
Multi-channel respiratory.
eeg_routine
Routine scalp EEG.
emg
Electromyogram.
eog
Electrooculogram.
eeg_sleep
Sleep EEG.
body_position
Body position.
presentation_state
Waveform Presentation State.
annotation
Waveform Annotation.
unknown
Unknown waveform type.
Definition at line 143 of file waveform_storage.hpp.
{
    ecg_12lead,
    ecg_general,
    ecg_ambulatory,
    hemodynamic,
    cardiac_ep,
    audio_basic,
    audio_general,
    arterial_pulse,
    respiratory,
    respiratory_multi,
    eeg_routine,
    emg,
    eog,
    eeg_sleep,
    body_position,
    presentation_state,
    annotation,
    unknown
};
xa_frame_rate
enum class kcenon::pacs::services::sop_classes::xa_frame_rate : uint16_t strong
Common XA frame rates in frames per second.
XA acquisitions typically use specific standardized frame rates for cardiac and vascular imaging.
Enumerator
fps_7_5
7.5 fps (low dose)
fps_15
15 fps (standard)
fps_30
30 fps (high temporal resolution)
Definition at line 268 of file xa_storage.hpp.
                         : uint16_t {
    fps_7_5 = 8,
    fps_15 = 15,
    fps_30 = 30
};
xa_photometric_interpretation
enum class kcenon::pacs::services::sop_classes::xa_photometric_interpretation strong
Supported photometric interpretations for XA/XRF images.
XA images are grayscale-only. MONOCHROME1 is traditional for XA (minimum pixel = white, like a lightbox view), while MONOCHROME2 is also supported.
Enumerator
monochrome1
Minimum pixel = white (traditional X-ray view)
monochrome2
Minimum pixel = black.
Definition at line 124 of file xa_storage.hpp.
{
    monochrome1,
    monochrome2
};
xa_positioner_motion
enum class kcenon::pacs::services::sop_classes::xa_positioner_motion strong
Positioner motion type.
Describes the type of positioner movement during acquisition.
Enumerator
stationary
No movement during acquisition.
dynamic
Positioner moves during acquisition (e.g., rotational)
Definition at line 229 of file xa_storage.hpp.
{
    stationary,
    dynamic
};
Function Documentation
create_mg_image_type()
std::string kcenon::pacs::services::sop_classes::create_mg_image_type (bool is_original, bool is_primary, mg_image_type type)
Create DICOM-compliant image type value for mammography.
Constructs the Image Type (0008,0008) value for mammography images according to DICOM specifications.
Parameters
is_original true if ORIGINAL, false if DERIVED
is_primary true if PRIMARY, false if SECONDARY
type For Presentation or For Processing
Returns
Properly formatted Image Type value
Definition at line 408 of file mg_storage.cpp.
{
    std::string result;
    // Value 1: ORIGINAL or DERIVED
    result += is_original ? "ORIGINAL" : "DERIVED";
    result += "\\";
    // Value 2: PRIMARY or SECONDARY
    result += is_primary ? "PRIMARY" : "SECONDARY";
    result += "\\";
    // Value 3: Image flavor - empty for mammography typically
    result += "\\";
    // Value 4: Derived Pixel Contrast - specific for For Presentation/Processing
    if (type == mg_image_type::for_presentation) {
        result += "NONE";  // or specific processing type
    } else {
        result += "";  // empty for processing images
    }
    return result;
}
References for_presentation.
get_bits_allocated()
uint16_t kcenon::pacs::services::sop_classes::get_bits_allocated (pixel_value_representation repr) noexcept
Get bits allocated for a pixel value representation.
Parameters
repr The pixel value representation
Returns
BitsAllocated value (32 or 64)
Definition at line 66 of file parametric_map_storage.cpp.
{
    switch (repr) {
        case pixel_value_representation::float32:
            return 32;
        case pixel_value_representation::float64:
            return 64;
    }
    return 32;
}
References float32, and float64.
get_ct_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_ct_storage_sop_classes ()
Get all CT Storage SOP Class UIDs.
Returns
Vector of CT Storage SOP Class UIDs
Definition at line 42 of file ct_storage.cpp.
{
    return {
        std::string(ct_image_storage_uid),
        std::string(enhanced_ct_image_storage_uid),
        std::string(ct_for_processing_image_storage_uid),
    };
}
References ct_for_processing_image_storage_uid, ct_image_storage_uid, and enhanced_ct_image_storage_uid.
get_default_xa_cine_rate()
constexpr uint16_t kcenon::pacs::services::sop_classes::get_default_xa_cine_rate () constexpr noexcept
Get typical cine rate for cardiac XA.
Returns
Default cine rate in frames per second
Definition at line 278 of file xa_storage.hpp.
{
    return 15;
}
get_dx_sop_class_info()
const dx_sop_class_info * kcenon::pacs::services::sop_classes::get_dx_sop_class_info (std::string_view uid) noexcept
Get information about a specific DX SOP Class.
Parameters
uid The SOP Class UID to look up
Returns
Pointer to sop class info, or nullptr if not a DX storage class
Definition at line 302 of file dx_storage.cpp.
{
    auto it = std::find_if(
        dx_sop_classes.begin(),
        dx_sop_classes.end(),
        [uid](const auto& info) { return info.uid == uid; }
    );
    if (it != dx_sop_classes.end()) {
        return &(*it);
    }
    return nullptr;
}
References uid.
Referenced by is_dx_for_presentation_sop_class(), is_dx_for_processing_sop_class(), is_dx_storage_sop_class(), and is_mammography_sop_class().
get_dx_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_dx_storage_sop_classes (bool include_mammography = true, bool include_intraoral = true)
Get all DX Storage SOP Class UIDs.
Returns all DX-related SOP Class UIDs including general radiography, mammography, and intra-oral imaging.
Parameters
include_mammography Include mammography SOP classes (default: true)
include_intraoral Include intra-oral SOP classes (default: true)
Returns
Vector of DX Storage SOP Class UIDs
Definition at line 278 of file dx_storage.cpp.
{
    std::vector<std::string> result;
    result.reserve(6);
    for (const auto& info : dx_sop_classes) {
        // Always include general DX
        if (!info.is_mammography && !info.is_intraoral) {
            result.emplace_back(info.uid);
        }
        // Include mammography if requested
        else if (info.is_mammography && include_mammography) {
            result.emplace_back(info.uid);
        }
        // Include intra-oral if requested
        else if (info.is_intraoral && include_intraoral) {
            result.emplace_back(info.uid);
        }
    }
    return result;
}
get_dx_transfer_syntaxes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_dx_transfer_syntaxes ()
Get recommended transfer syntaxes for DX images.
Returns a prioritized list of transfer syntaxes suitable for digital X-ray image storage. DX images are typically grayscale with high bit depth (12-16 bits).
Returns
Vector of transfer syntax UIDs in priority order
Definition at line 46 of file dx_storage.cpp.
{
    return {
        // Explicit VR Little Endian (preferred for interoperability)
        "1.2.840.10008.1.2.1",
        // Implicit VR Little Endian (universal baseline)
        "1.2.840.10008.1.2",
        // HTJ2K Lossless (high-throughput lossless for large DX images)
        "1.2.840.10008.1.2.4.201",
        // JPEG Lossless (for diagnostic quality - most important for DX)
        "1.2.840.10008.1.2.4.70",
        // JPEG 2000 Lossless (better compression, good for large DX images)
        "1.2.840.10008.1.2.4.90",
        // JPEG 2000 Lossy (for archival with acceptable quality loss)
        "1.2.840.10008.1.2.4.91",
        // RLE Lossless (simple lossless compression)
        "1.2.840.10008.1.2.5"
    };
}
get_max_xa_frame_count()
constexpr size_t kcenon::pacs::services::sop_classes::get_max_xa_frame_count () constexpr noexcept
Get maximum recommended frame count for XA acquisitions.
Large XA acquisitions can have many frames. This returns a reasonable upper limit for memory pre-allocation.
Returns
Maximum expected frame count
Definition at line 290 of file xa_storage.hpp.
{
    return 2000;  // Typical max for long cardiac runs
}
get_mg_sop_class_info()
const mg_sop_class_info * kcenon::pacs::services::sop_classes::get_mg_sop_class_info (std::string_view uid) noexcept
Get information about a specific Mammography SOP Class.
Parameters
uid The SOP Class UID to look up
Returns
Pointer to sop class info, or nullptr if not a mammography storage class
Definition at line 317 of file mg_storage.cpp.
{
    auto it = std::find_if(mg_sop_classes.begin(), mg_sop_classes.end(),
        [uid](const mg_sop_class_info& info) {
            return info.uid == uid;
        });
    if (it != mg_sop_classes.end()) {
        return &(*it);
    }
    return nullptr;
}
References uid.
Referenced by is_breast_tomosynthesis_sop_class(), is_mg_for_presentation_sop_class(), is_mg_for_processing_sop_class(), and is_mg_storage_sop_class().
get_mg_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_mg_storage_sop_classes (bool include_tomosynthesis = true)
Get all Mammography Storage SOP Class UIDs.
Returns all mammography-related SOP Class UIDs including standard 2D mammography and breast tomosynthesis.
Parameters
include_tomosynthesis Include breast tomosynthesis SOP classes (default: true)
Returns
Vector of Mammography Storage SOP Class UIDs
Definition at line 303 of file mg_storage.cpp.
{
    std::vector<std::string> result;
    result.reserve(mg_sop_classes.size());
    for (const auto& info : mg_sop_classes) {
        if (!include_tomosynthesis && info.is_tomosynthesis) {
            continue;
        }
        result.emplace_back(info.uid);
    }
    return result;
}
get_mg_transfer_syntaxes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_mg_transfer_syntaxes ()
Get recommended transfer syntaxes for mammography images.
Returns a prioritized list of transfer syntaxes suitable for mammography image storage. Mammography images typically have very high spatial resolution and benefit from specific compression approaches.
Returns
Vector of transfer syntax UIDs in priority order
Definition at line 352 of file mg_storage.cpp.
{
    return {
        // HTJ2K Lossless - high-throughput lossless for large mammography images
        "1.2.840.10008.1.2.4.201",
        // JPEG 2000 Lossless - excellent for high-resolution mammography
        "1.2.840.10008.1.2.4.90",
        // JPEG Lossless - widely supported
        "1.2.840.10008.1.2.4.70",
        // JPEG 2000 Lossy - good compression for storage
        "1.2.840.10008.1.2.4.91",
        // Explicit VR Little Endian - universal compatibility
        "1.2.840.10008.1.2.1",
        // Implicit VR Little Endian - legacy support
        "1.2.840.10008.1.2"
    };
}
get_mr_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_mr_storage_sop_classes ()
Get all MR Storage SOP Class UIDs.
Returns
Vector of MR Storage SOP Class UIDs
Definition at line 41 of file mr_storage.cpp.
{
    return {
        std::string(mr_image_storage_uid),
        std::string(enhanced_mr_image_storage_uid),
    };
}
References enhanced_mr_image_storage_uid, and mr_image_storage_uid.
get_nm_sop_class_info()
const nm_sop_class_info * kcenon::pacs::services::sop_classes::get_nm_sop_class_info (std::string_view uid) noexcept
Get information about a specific NM SOP Class.
Parameters
uid The SOP Class UID to look up
Returns
Pointer to SOP class info, or nullptr if not a NM storage class
Definition at line 129 of file nm_storage.cpp.
{
    auto it = std::find_if(
        nm_sop_classes.begin(),
        nm_sop_classes.end(),
        [uid](const auto& info) { return info.uid == uid; }
    );
    if (it != nm_sop_classes.end()) {
        return &(*it);
    }
    return nullptr;
}
References uid.
Referenced by is_nm_multiframe_sop_class(), and is_nm_storage_sop_class().
get_nm_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_nm_storage_sop_classes (bool include_retired = true)
Get all NM Storage SOP Class UIDs.
Returns both current and retired SOP Class UIDs for comprehensive nuclear medicine storage support.
Parameters
include_retired Include retired SOP classes (default: true)
Returns
Vector of NM Storage SOP Class UIDs
Definition at line 115 of file nm_storage.cpp.
{
    std::vector<std::string> result;
    result.reserve(nm_sop_classes.size());
    for (const auto& info : nm_sop_classes) {
        if (!info.is_retired || include_retired) {
            result.emplace_back(info.uid);
        }
    }
    return result;
}
get_nm_transfer_syntaxes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_nm_transfer_syntaxes ()
Get recommended transfer syntaxes for NM images.
Returns a prioritized list of transfer syntaxes suitable for nuclear medicine image storage, considering multi-frame support and quantitative accuracy requirements.
Returns
Vector of transfer syntax UIDs in priority order
Definition at line 46 of file nm_storage.cpp.
{
    return {
        // Explicit VR Little Endian (preferred for interoperability)
        "1.2.840.10008.1.2.1",
        // Implicit VR Little Endian (universal baseline)
        "1.2.840.10008.1.2",
        // HTJ2K Lossless (high-throughput lossless, preserves count values)
        "1.2.840.10008.1.2.4.201",
        // JPEG Lossless (for diagnostic quality - important for quantitative data)
        "1.2.840.10008.1.2.4.70",
        // JPEG 2000 Lossless (better compression, preserves count values)
        "1.2.840.10008.1.2.4.90",
        // RLE Lossless
        "1.2.840.10008.1.2.5"
    };
}
get_ophthalmic_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_ophthalmic_storage_sop_classes ()
Get all Ophthalmic Storage SOP Class UIDs.
Returns
Vector of Ophthalmic Storage SOP Class UIDs
Definition at line 41 of file ophthalmic_storage.cpp.
{
    return {
        std::string(ophthalmic_photo_8bit_storage_uid),
        std::string(ophthalmic_photo_16bit_storage_uid),
        std::string(ophthalmic_tomography_storage_uid),
        std::string(wide_field_ophthalmic_photo_storage_uid),
        std::string(ophthalmic_oct_bscan_analysis_storage_uid),
    };
}
References ophthalmic_oct_bscan_analysis_storage_uid, ophthalmic_photo_16bit_storage_uid, ophthalmic_photo_8bit_storage_uid, ophthalmic_tomography_storage_uid, and wide_field_ophthalmic_photo_storage_uid.
get_parametric_map_sop_class_info()
const parametric_map_sop_class_info * kcenon::pacs::services::sop_classes::get_parametric_map_sop_class_info (std::string_view uid) noexcept
Get information about the Parametric Map SOP Class.
Parameters
uid The SOP Class UID to look up
Returns
Pointer to SOP class info, or nullptr if not a Parametric Map class
Definition at line 112 of file parametric_map_storage.cpp.
{
    if (uid == parametric_map_storage_uid) {
        return &pmap_sop_classes[0];
    }
    return nullptr;
}
References parametric_map_storage_uid, and uid.
get_parametric_map_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_parametric_map_storage_sop_classes ()
Get all Parametric Map Storage SOP Class UIDs.
Returns
Vector of Parametric Map Storage SOP Class UIDs
Definition at line 105 of file parametric_map_storage.cpp.
{
    return {
        std::string(parametric_map_storage_uid)
    };
}
References parametric_map_storage_uid.
get_parametric_map_transfer_syntaxes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_parametric_map_transfer_syntaxes ()
Get recommended transfer syntaxes for Parametric Map objects.
Returns a prioritized list of transfer syntaxes suitable for parametric map storage. Float pixel data requires uncompressed or lossless transfer syntaxes to preserve quantitative accuracy.
Returns
Vector of transfer syntax UIDs in priority order
Definition at line 47 of file parametric_map_storage.cpp.
{
    return {
        // Explicit VR Little Endian (preferred for interoperability)
        "1.2.840.10008.1.2.1",
        // Implicit VR Little Endian (universal baseline)
        "1.2.840.10008.1.2",
        // JPEG 2000 Lossless (preserves float data integrity)
        "1.2.840.10008.1.2.4.90",
        // HTJ2K Lossless (high-throughput lossless)
        "1.2.840.10008.1.2.4.201",
        // RLE Lossless
        "1.2.840.10008.1.2.5"
    };
}
get_pet_sop_class_info()
const pet_sop_class_info * kcenon::pacs::services::sop_classes::get_pet_sop_class_info (std::string_view uid) noexcept
Get information about a specific PET SOP Class.
Parameters
uid The SOP Class UID to look up
Returns
Pointer to SOP class info, or nullptr if not a PET storage class
Definition at line 135 of file pet_storage.cpp.
{
    auto it = std::find_if(
        pet_sop_classes.begin(),
        pet_sop_classes.end(),
        [uid](const auto& info) { return info.uid == uid; }
    );
    if (it != pet_sop_classes.end()) {
        return &(*it);
    }
    return nullptr;
}
References uid.
Referenced by is_enhanced_pet_sop_class(), and is_pet_storage_sop_class().
get_pet_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_pet_storage_sop_classes (bool include_retired = true)
Get all PET Storage SOP Class UIDs.
Returns both current and legacy SOP Class UIDs for comprehensive PET storage support.
Parameters
include_retired Include retired SOP classes (default: true)
Returns
Vector of PET Storage SOP Class UIDs
Definition at line 121 of file pet_storage.cpp.
{
    std::vector<std::string> result;
    result.reserve(pet_sop_classes.size());
    for (const auto& info : pet_sop_classes) {
        if (!info.is_retired || include_retired) {
            result.emplace_back(info.uid);
        }
    }
    return result;
}
get_pet_transfer_syntaxes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_pet_transfer_syntaxes ()
Get recommended transfer syntaxes for PET images.
Returns a prioritized list of transfer syntaxes suitable for PET image storage, considering compression requirements and quantitative accuracy.
Returns
Vector of transfer syntax UIDs in priority order
Definition at line 46 of file pet_storage.cpp.
{
    return {
        // Explicit VR Little Endian (preferred for interoperability)
        "1.2.840.10008.1.2.1",
        // Implicit VR Little Endian (universal baseline)
        "1.2.840.10008.1.2",
        // HTJ2K Lossless (high-throughput lossless, preserves quantitative data)
        "1.2.840.10008.1.2.4.201",
        // JPEG Lossless (for diagnostic quality - recommended for quantitative data)
        "1.2.840.10008.1.2.4.70",
        // JPEG 2000 Lossless (better compression, preserves quantitative values)
        "1.2.840.10008.1.2.4.90",
        // RLE Lossless
        "1.2.840.10008.1.2.5"
    };
}
get_primary_energy_kev()
double kcenon::pacs::services::sop_classes::get_primary_energy_kev (nm_radioisotope isotope) noexcept
Get primary photopeak energy for radioisotope.
Parameters
isotope The radioisotope type
Returns
Primary photopeak energy in keV
Definition at line 280 of file nm_storage.cpp.
{
    switch (isotope) {
        case nm_radioisotope::tc99m:
            return 140.0;
        case nm_radioisotope::i131:
            return 364.0;
        case nm_radioisotope::i123:
            return 159.0;
        case nm_radioisotope::tl201:
            return 71.0;  // Primary peak (also 167 keV)
        case nm_radioisotope::ga67:
            return 93.0;  // Primary peak (also 185, 300 keV)
        case nm_radioisotope::in111:
            return 171.0; // Primary peak (also 245 keV)
        case nm_radioisotope::f18:
            return 511.0; // Annihilation photons
        case nm_radioisotope::other:
            return 0.0;
    }
    return 0.0;
}
References f18, ga67, i123, i131, in111, other, tc99m, and tl201.
get_recommended_segment_color()
segment_color kcenon::pacs::services::sop_classes::get_recommended_segment_color (std::string_view segment_label) noexcept
Get recommended color for common segment types.
Parameters
segment_label The segment label (e.g., "Liver", "Tumor")
Returns
Recommended CIELab color, or default gray if unknown
Definition at line 185 of file seg_storage.cpp.
{
    auto it = standard_colors.find(segment_label);
    if (it != standard_colors.end()) {
        return it->second;
    }
    // Return default gray for unknown structures
    return standard_colors.at("Default");
}
get_recommended_sr_template()
std::string_view kcenon::pacs::services::sop_classes::get_recommended_sr_template (std::string_view uid) noexcept
Get recommended template ID for an SR SOP Class.
Parameters
uid The SR SOP Class UID
Returns
Template ID string, or empty if no specific template recommended
Definition at line 487 of file sr_storage.cpp.
{
    if (uid == mammography_cad_sr_storage_uid) {
        return sr_template::mammography_cad_report;
    }
    if (uid == chest_cad_sr_storage_uid) {
        return sr_template::chest_cad_report;
    }
    if (uid == colon_cad_sr_storage_uid) {
        return sr_template::colon_cad_report;
    }
    if (uid == xray_radiation_dose_sr_storage_uid ||
        uid == enhanced_xray_radiation_dose_sr_storage_uid) {
        return sr_template::xray_radiation_dose_report;
    }
    if (uid == key_object_selection_document_storage_uid) {
        return sr_template::key_object_selection;
    }
    if (uid == basic_text_sr_storage_uid ||
        uid == enhanced_sr_storage_uid ||
        uid == comprehensive_sr_storage_uid) {
        return sr_template::basic_diagnostic_imaging_report;
    }
    return "";
}
References kcenon::pacs::services::sop_classes::sr_template::basic_diagnostic_imaging_report, basic_text_sr_storage_uid, kcenon::pacs::services::sop_classes::sr_template::chest_cad_report, chest_cad_sr_storage_uid, kcenon::pacs::services::sop_classes::sr_template::colon_cad_report, colon_cad_sr_storage_uid, comprehensive_sr_storage_uid, enhanced_sr_storage_uid, enhanced_xray_radiation_dose_sr_storage_uid, kcenon::pacs::services::sop_classes::sr_template::key_object_selection, key_object_selection_document_storage_uid, kcenon::pacs::services::sop_classes::sr_template::mammography_cad_report, mammography_cad_sr_storage_uid, uid, kcenon::pacs::services::sop_classes::sr_template::xray_radiation_dose_report, and xray_radiation_dose_sr_storage_uid.
get_rt_sop_class_info()
const rt_sop_class_info * kcenon::pacs::services::sop_classes::get_rt_sop_class_info (std::string_view uid) noexcept
Get information about a specific RT SOP Class.
Parameters
uid The SOP Class UID to look up
Returns
Pointer to SOP class info, or nullptr if not an RT storage class
Definition at line 164 of file rt_storage.cpp.
{
    for (size_t i = 0; i < rt_sop_class_count; ++i) {
        if (rt_sop_classes[i].uid == uid) {
            return &rt_sop_classes[i];
        }
    }
    return nullptr;
}
References uid.
Referenced by is_rt_storage_sop_class(), and rt_sop_class_has_pixel_data().
get_rt_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_rt_storage_sop_classes (bool include_retired = true)
Get all RT Storage SOP Class UIDs.
Returns all RT Storage SOP Class UIDs for comprehensive radiation therapy support.
Parameters
include_retired Include retired SOP classes (default: true)
Returns
Vector of RT Storage SOP Class UIDs
Definition at line 149 of file rt_storage.cpp.
{
    std::vector<std::string> result;
    result.reserve(rt_sop_class_count);
    for (size_t i = 0; i < rt_sop_class_count; ++i) {
        const auto& info = rt_sop_classes[i];
        if (!info.is_retired || include_retired) {
            result.emplace_back(info.uid);
        }
    }
    return result;
}
get_rt_transfer_syntaxes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_rt_transfer_syntaxes ()
Get recommended transfer syntaxes for RT objects.
Returns a prioritized list of transfer syntaxes suitable for radiation therapy object storage. RT objects typically don't contain pixel data (except RT Image and RT Dose), so compression is less critical.
Returns
Vector of transfer syntax UIDs in priority order
Definition at line 46 of file rt_storage.cpp.
{
    return {
        // Explicit VR Little Endian (preferred for interoperability)
        "1.2.840.10008.1.2.1",
        // Implicit VR Little Endian (universal baseline)
        "1.2.840.10008.1.2",
        // HTJ2K Lossless (high-throughput lossless for dose grids)
        "1.2.840.10008.1.2.4.201",
        // JPEG Lossless (for RT Image and RT Dose with pixel data)
        "1.2.840.10008.1.2.4.70",
        // JPEG 2000 Lossless (better compression for dose grids)
        "1.2.840.10008.1.2.4.90",
        // RLE Lossless
        "1.2.840.10008.1.2.5"
    };
}
get_seg_sop_class_info()
const seg_sop_class_info * kcenon::pacs::services::sop_classes::get_seg_sop_class_info (std::string_view uid) noexcept
Get information about a specific SEG SOP Class.
Parameters
uid The SOP Class UID to look up
Returns
Pointer to SOP class info, or nullptr if not a SEG storage class
Definition at line 247 of file seg_storage.cpp.
{
    auto it = std::find_if(
        seg_sop_classes.begin(),
        seg_sop_classes.end(),
        [uid](const auto& info) { return info.uid == uid; }
    );
    if (it != seg_sop_classes.end()) {
        return &(*it);
    }
    return nullptr;
}
References uid.
Referenced by is_seg_storage_sop_class().
get_seg_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_seg_storage_sop_classes (bool include_surface = true)
Get all SEG Storage SOP Class UIDs.
Parameters
include_surface Include surface segmentation (default: true)
Returns
Vector of SEG Storage SOP Class UIDs
Definition at line 233 of file seg_storage.cpp.
{
    std::vector<std::string> result;
    result.reserve(include_surface ? 4 : 3);
    for (const auto& info : seg_sop_classes) {
        if (!info.is_surface || include_surface) {
            result.emplace_back(info.uid);
        }
    }
    return result;
}
get_seg_transfer_syntaxes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_seg_transfer_syntaxes ()
Get recommended transfer syntaxes for SEG objects.
Returns a prioritized list of transfer syntaxes suitable for segmentation object storage. Binary segmentations benefit from lossless compression.
Returns
Vector of transfer syntax UIDs in priority order
Definition at line 47 of file seg_storage.cpp.
{
    return {
        // Explicit VR Little Endian (preferred for interoperability)
        "1.2.840.10008.1.2.1",
        // Implicit VR Little Endian (universal baseline)
        "1.2.840.10008.1.2",
        // HTJ2K Lossless (high-throughput lossless for segmentation data)
        "1.2.840.10008.1.2.4.201",
        // JPEG 2000 Lossless (good for binary data)
        "1.2.840.10008.1.2.4.90",
        // RLE Lossless (excellent for binary segmentations)
        "1.2.840.10008.1.2.5",
        // JPEG Lossless
        "1.2.840.10008.1.2.4.70"
    };
}
get_segment_category_code()
std::string_view kcenon::pacs::services::sop_classes::get_segment_category_code (segment_category category) noexcept
Get SNOMED CT code for segment category.
Parameters
category The segment category
Returns
SNOMED CT code string
Definition at line 291 of file seg_storage.cpp.
{
    auto index = static_cast<size_t>(category);
    if (index < category_codes.size()) {
        return category_codes[index].code;
    }
    return category_codes[0].code;  // Default to tissue
}
get_segment_category_meaning()
std::string_view kcenon::pacs::services::sop_classes::get_segment_category_meaning (segment_category category) noexcept
Get code meaning for segment category.
Parameters
category The segment category
Returns
Human-readable category name
Definition at line 299 of file seg_storage.cpp.
{
    auto index = static_cast<size_t>(category);
    if (index < category_codes.size()) {
        return category_codes[index].meaning;
    }
    return category_codes[0].meaning;
}
get_sr_document_type()
sr_document_type kcenon::pacs::services::sop_classes::get_sr_document_type (std::string_view uid) noexcept
Get SR document type for a SOP Class UID.
Parameters
uid The SOP Class UID
Returns
The SR document type
Definition at line 61 of file sr_storage.cpp.
{
    if (uid == basic_text_sr_storage_uid) {
        return sr_document_type::basic_text;
    }
    if (uid == enhanced_sr_storage_uid) {
        return sr_document_type::enhanced;
    }
    if (uid == comprehensive_sr_storage_uid) {
        return sr_document_type::comprehensive;
    }
    if (uid == comprehensive_3d_sr_storage_uid) {
        return sr_document_type::comprehensive_3d;
    }
    if (uid == extensible_sr_storage_uid) {
        return sr_document_type::extensible;
    }
    if (uid == key_object_selection_document_storage_uid) {
        return sr_document_type::key_object_selection;
    }
    if (uid == mammography_cad_sr_storage_uid ||
        uid == chest_cad_sr_storage_uid ||
        uid == colon_cad_sr_storage_uid) {
        return sr_document_type::cad;
    }
    if (uid == xray_radiation_dose_sr_storage_uid ||
        uid == radiopharmaceutical_radiation_dose_sr_storage_uid ||
        uid == patient_radiation_dose_sr_storage_uid ||
        uid == enhanced_xray_radiation_dose_sr_storage_uid) {
        return sr_document_type::dose_report;
    }
    return sr_document_type::other;
}
References basic_text, basic_text_sr_storage_uid, cad, chest_cad_sr_storage_uid, colon_cad_sr_storage_uid, comprehensive, comprehensive_3d, comprehensive_3d_sr_storage_uid, comprehensive_sr_storage_uid, dose_report, enhanced, enhanced_sr_storage_uid, enhanced_xray_radiation_dose_sr_storage_uid, extensible, extensible_sr_storage_uid, key_object_selection, key_object_selection_document_storage_uid, mammography_cad_sr_storage_uid, other, patient_radiation_dose_sr_storage_uid, radiopharmaceutical_radiation_dose_sr_storage_uid, uid, and xray_radiation_dose_sr_storage_uid.
Referenced by kcenon::pacs::services::validation::sr_iod_validator::validate().
get_sr_sop_class_info()
const sr_sop_class_info * kcenon::pacs::services::sop_classes::get_sr_sop_class_info (std::string_view uid) noexcept
Get information about a specific SR SOP Class.
Parameters
uid The SOP Class UID to look up
Returns
Pointer to SOP class info, or nullptr if not an SR storage class
Definition at line 451 of file sr_storage.cpp.
{
    auto it = std::find_if(
        sr_sop_classes.begin(),
        sr_sop_classes.end(),
        [uid](const auto& info) { return info.uid == uid; }
    );
    if (it != sr_sop_classes.end()) {
        return &(*it);
    }
    return nullptr;
}
References uid.
Referenced by is_cad_sr_storage_sop_class(), is_dose_sr_storage_sop_class(), is_sr_storage_sop_class(), and sr_supports_spatial_coords().
get_sr_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_sr_storage_sop_classes (bool include_cad = true, bool include_dose = true)
Get all SR Storage SOP Class UIDs.
Parameters
include_cad Include CAD-specific SR classes (default: true)
include_dose Include dose report SR classes (default: true)
Returns
Vector of SR Storage SOP Class UIDs
Definition at line 428 of file sr_storage.cpp.
{
    std::vector<std::string> result;
    result.reserve(sr_sop_classes.size());
    for (const auto& info : sr_sop_classes) {
        bool include = true;
        if (!include_cad && info.document_type == sr_document_type::cad) {
            include = false;
        }
        if (!include_dose && info.document_type == sr_document_type::dose_report) {
            include = false;
        }
        if (include) {
            result.emplace_back(info.uid);
        }
    }
    return result;
}
References cad, and dose_report.
get_sr_transfer_syntaxes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_sr_transfer_syntaxes ()
Get recommended transfer syntaxes for SR objects.
Returns a prioritized list of transfer syntaxes suitable for structured report storage. SR objects are typically small and don't benefit from compression.
Returns
Vector of transfer syntax UIDs in priority order
Definition at line 46 of file sr_storage.cpp.
{
    return {
        // Explicit VR Little Endian (preferred for interoperability)
        "1.2.840.10008.1.2.1",
        // Implicit VR Little Endian (universal baseline)
        "1.2.840.10008.1.2",
        // Deflated Explicit VR Little Endian (good for large SRs)
        "1.2.840.10008.1.2.1.99"
    };
}
get_standard_screening_views()
std::vector< std::pair< breast_laterality, mg_view_position > > kcenon::pacs::services::sop_classes::get_standard_screening_views () noexcept
Get standard four-view screening exam views.
Returns the standard four views for screening mammography:
Right CC, Left CC, Right MLO, Left MLO
Returns
Vector of (laterality, view) pairs
Definition at line 399 of file mg_storage.cpp.
{
    return {
        {breast_laterality::right, mg_view_position::cc},
        {breast_laterality::left, mg_view_position::cc},
        {breast_laterality::right, mg_view_position::mlo},
        {breast_laterality::left, mg_view_position::mlo}
    };
}
References cc, left, mlo, and right.
get_typical_compression_force_range()
std::pair< double, double > kcenon::pacs::services::sop_classes::get_typical_compression_force_range () noexcept
Get typical compression force range.
Returns
Pair of (minimum, maximum) typical compression force in Newtons
Definition at line 209 of file mg_storage.cpp.
{
    return {50.0, 200.0};  // Newtons
}
Referenced by kcenon::pacs::services::validation::mg_iod_validator::check_compression_force_range().
get_us_sop_class_info()
const us_sop_class_info * kcenon::pacs::services::sop_classes::get_us_sop_class_info (std::string_view uid) noexcept
Get information about a specific US SOP Class.
Parameters
uid The SOP Class UID to look up
Returns
Pointer to sop class info, or nullptr if not a US storage class
Definition at line 179 of file us_storage.cpp.
{
    auto it = std::find_if(
        us_sop_classes.begin(),
        us_sop_classes.end(),
        [uid](const auto& info) { return info.uid == uid; }
    );
    if (it != us_sop_classes.end()) {
        return &(*it);
    }
    return nullptr;
}
References uid.
Referenced by is_us_multiframe_sop_class(), and is_us_storage_sop_class().
get_us_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_us_storage_sop_classes (bool include_retired = true)
Get all US Storage SOP Class UIDs.
Returns both current and retired SOP Class UIDs for comprehensive ultrasound storage support.
Parameters
include_retired Include retired SOP classes (default: true)
Returns
Vector of US Storage SOP Class UIDs
Definition at line 165 of file us_storage.cpp.
{
    std::vector<std::string> result;
    result.reserve(include_retired ? 4 : 2);
    for (const auto& info : us_sop_classes) {
        if (!info.is_retired || include_retired) {
            result.emplace_back(info.uid);
        }
    }
    return result;
}
get_us_transfer_syntaxes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_us_transfer_syntaxes ()
Get recommended transfer syntaxes for US images.
Returns a prioritized list of transfer syntaxes suitable for ultrasound image storage, considering color support and compression requirements.
Returns
Vector of transfer syntax UIDs in priority order
Definition at line 46 of file us_storage.cpp.
{
    return {
        // Explicit VR Little Endian (preferred for interoperability)
        "1.2.840.10008.1.2.1",
        // Implicit VR Little Endian (universal baseline)
        "1.2.840.10008.1.2",
        // JPEG Baseline (lossy, good for color US)
        "1.2.840.10008.1.2.4.50",
        // HTJ2K Lossless (high-throughput lossless)
        "1.2.840.10008.1.2.4.201",
        // JPEG Lossless (for diagnostic quality)
        "1.2.840.10008.1.2.4.70",
        // JPEG 2000 Lossless (better compression)
        "1.2.840.10008.1.2.4.90",
        // JPEG 2000 Lossy (for archival)
        "1.2.840.10008.1.2.4.91",
        // RLE Lossless
        "1.2.840.10008.1.2.5"
    };
}
get_valid_mg_view_positions()
std::vector< std::string_view > kcenon::pacs::services::sop_classes::get_valid_mg_view_positions () noexcept
Get all valid mammography view position strings.
Returns
Vector of valid DICOM view position codes
Definition at line 191 of file mg_storage.cpp.
{
    return {
        "CC", "MLO", "ML", "LM", "XCCL", "XCCM", "FB", "SIO", "ISO",
        "CV", "AT", "SPOT", "MAG", "SPOT MAG", "RL", "RM", "RS", "RI",
        "TAN", "ID"
    };
}
Referenced by kcenon::pacs::services::validation::mg_iod_validator::check_view_position_validity().
get_waveform_sop_class_info()
const waveform_sop_class_info * kcenon::pacs::services::sop_classes::get_waveform_sop_class_info (std::string_view uid) noexcept
Get information about a specific Waveform SOP Class.
Parameters
uid The SOP Class UID to look up
Returns
Pointer to SOP class info, or nullptr if not a waveform storage class
Definition at line 169 of file waveform_storage.cpp.
{
    auto it = std::find_if(kWaveformRegistry.begin(), kWaveformRegistry.end(),
                           [&uid](const waveform_sop_class_info& info) {
                               return info.uid == uid;
                           });
    return (it != kWaveformRegistry.end()) ? &(*it) : nullptr;
}
References uid.
Referenced by is_waveform_storage_sop_class(), and kcenon::pacs::services::sop_class_registry::register_waveform_sop_classes().
get_waveform_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_waveform_storage_sop_classes (bool include_presentation_state = true, bool include_annotation = true)
Get all Waveform Storage SOP Class UIDs.
Parameters
include_presentation_state Include presentation state class (default: true)
include_annotation Include annotation class (default: true)
Returns
Vector of Waveform Storage SOP Class UIDs
Definition at line 150 of file waveform_storage.cpp.
{
    std::vector<std::string> result;
    result.reserve(kWaveformRegistry.size());
    for (const auto& entry : kWaveformRegistry) {
        if (entry.type == waveform_type::presentation_state &&
            !include_presentation_state) {
            continue;
        }
        if (entry.type == waveform_type::annotation && !include_annotation) {
            continue;
        }
        result.emplace_back(entry.uid);
    }
    return result;
}
References annotation, and presentation_state.
Referenced by kcenon::pacs::services::sop_class_registry::register_waveform_sop_classes().
get_waveform_transfer_syntaxes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_waveform_transfer_syntaxes ()
Get recommended transfer syntaxes for waveform objects.
Returns
Vector of transfer syntax UIDs in priority order
Definition at line 46 of file waveform_storage.cpp.
{
    return {
        // Explicit VR Little Endian (preferred for interoperability)
        "1.2.840.10008.1.2.1",
        // Implicit VR Little Endian (universal baseline)
        "1.2.840.10008.1.2",
    };
}
get_waveform_type()
waveform_type kcenon::pacs::services::sop_classes::get_waveform_type (std::string_view uid) noexcept
Get waveform type from SOP Class UID.
Parameters
uid The SOP Class UID
Returns
The waveform type
Definition at line 59 of file waveform_storage.cpp.
{
    if (uid == twelve_lead_ecg_storage_uid) return waveform_type::ecg_12lead;
    if (uid == general_ecg_storage_uid) return waveform_type::ecg_general;
    if (uid == ambulatory_ecg_storage_uid) return waveform_type::ecg_ambulatory;
    if (uid == hemodynamic_waveform_storage_uid) return waveform_type::hemodynamic;
    if (uid == cardiac_ep_waveform_storage_uid) return waveform_type::cardiac_ep;
    if (uid == basic_voice_audio_storage_uid) return waveform_type::audio_basic;
    if (uid == general_audio_waveform_storage_uid) return waveform_type::audio_general;
    if (uid == arterial_pulse_waveform_storage_uid) return waveform_type::arterial_pulse;
    if (uid == respiratory_waveform_storage_uid) return waveform_type::respiratory;
    if (uid == multichannel_respiratory_waveform_storage_uid) return waveform_type::respiratory_multi;
    if (uid == routine_scalp_eeg_storage_uid) return waveform_type::eeg_routine;
    if (uid == emg_waveform_storage_uid) return waveform_type::emg;
    if (uid == eog_waveform_storage_uid) return waveform_type::eog;
    if (uid == sleep_eeg_storage_uid) return waveform_type::eeg_sleep;
    if (uid == body_position_waveform_storage_uid) return waveform_type::body_position;
    if (uid == waveform_presentation_state_storage_uid) return waveform_type::presentation_state;
    if (uid == waveform_annotation_storage_uid) return waveform_type::annotation;
    return waveform_type::unknown;
}
References ambulatory_ecg_storage_uid, annotation, arterial_pulse, arterial_pulse_waveform_storage_uid, audio_basic, audio_general, basic_voice_audio_storage_uid, body_position, body_position_waveform_storage_uid, cardiac_ep, cardiac_ep_waveform_storage_uid, ecg_12lead, ecg_ambulatory, ecg_general, eeg_routine, eeg_sleep, emg, emg_waveform_storage_uid, eog, eog_waveform_storage_uid, general_audio_waveform_storage_uid, general_ecg_storage_uid, hemodynamic, hemodynamic_waveform_storage_uid, multichannel_respiratory_waveform_storage_uid, presentation_state, respiratory, respiratory_multi, respiratory_waveform_storage_uid, routine_scalp_eeg_storage_uid, sleep_eeg_storage_uid, twelve_lead_ecg_storage_uid, uid, unknown, waveform_annotation_storage_uid, and waveform_presentation_state_storage_uid.
get_wsi_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_wsi_storage_sop_classes ()
Get all WSI Storage SOP Class UIDs.
Returns
Vector of WSI Storage SOP Class UIDs
Definition at line 41 of file wsi_storage.cpp.
{
    return {
        std::string(wsi_image_storage_uid),
    };
}
References wsi_image_storage_uid.
get_xa_sop_class_info()
const xa_sop_class_info * kcenon::pacs::services::sop_classes::get_xa_sop_class_info (std::string_view uid) noexcept
Get information about a specific XA SOP Class.
Parameters
uid The SOP Class UID to look up
Returns
Pointer to sop class info, or nullptr if not an XA storage class
Definition at line 155 of file xa_storage.cpp.
{
    auto it = std::find_if(
        xa_sop_classes.begin(),
        xa_sop_classes.end(),
        [uid](const auto& info) { return info.uid == uid; }
    );
    if (it != xa_sop_classes.end()) {
        return &(*it);
    }
    return nullptr;
}
References uid.
Referenced by is_enhanced_xa_sop_class(), is_xa_3d_sop_class(), is_xa_multiframe_sop_class(), and is_xa_storage_sop_class().
get_xa_storage_sop_classes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_xa_storage_sop_classes (bool include_3d = true)
Get all XA/XRF Storage SOP Class UIDs.
Returns all supported X-Ray angiographic SOP Class UIDs including standard, enhanced, and 3D variants.
Parameters
include_3d Include 3D angiographic SOP classes (default: true)
Returns
Vector of XA Storage SOP Class UIDs
Definition at line 141 of file xa_storage.cpp.
{
    std::vector<std::string> result;
    result.reserve(include_3d ? 5 : 3);
    for (const auto& info : xa_sop_classes) {
        if (!info.is_3d || include_3d) {
            result.emplace_back(info.uid);
        }
    }
    return result;
}
get_xa_transfer_syntaxes()
std::vector< std::string > kcenon::pacs::services::sop_classes::get_xa_transfer_syntaxes ()
Get recommended transfer syntaxes for XA images.
Returns a prioritized list of transfer syntaxes suitable for X-Ray angiographic image storage. XA images are typically grayscale with high bit depth (8-16 bits).
Returns
Vector of transfer syntax UIDs in priority order
Definition at line 47 of file xa_storage.cpp.
{
    return {
        // Explicit VR Little Endian (preferred for interoperability)
        "1.2.840.10008.1.2.1",
        // Implicit VR Little Endian (universal baseline)
        "1.2.840.10008.1.2",
        // HTJ2K Lossless (high-throughput lossless for multi-frame)
        "1.2.840.10008.1.2.4.201",
        // JPEG Lossless (for diagnostic quality)
        "1.2.840.10008.1.2.4.70",
        // RLE Lossless (for multi-frame)
        "1.2.840.10008.1.2.5"
    };
}
is_breast_tomosynthesis_sop_class()
bool kcenon::pacs::services::sop_classes::is_breast_tomosynthesis_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a breast tomosynthesis SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is a breast tomosynthesis storage SOP class
Definition at line 333 of file mg_storage.cpp.
{
    auto info = get_mg_sop_class_info(uid);
    return info && info->is_tomosynthesis;
}
References get_mg_sop_class_info(), and uid.
is_cad_sr_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_cad_sr_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a CAD SR Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is a CAD SR storage SOP class
Definition at line 468 of file sr_storage.cpp.
{
    const auto* info = get_sr_sop_class_info(uid);
    return info != nullptr && info->document_type == sr_document_type::cad;
}
References cad, get_sr_sop_class_info(), and uid.
is_ct_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_ct_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a CT Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is a CT storage SOP class
Definition at line 50 of file ct_storage.cpp.
{
    return uid == ct_image_storage_uid ||
           uid == enhanced_ct_image_storage_uid ||
           uid == ct_for_processing_image_storage_uid;
}
References ct_for_processing_image_storage_uid, ct_image_storage_uid, enhanced_ct_image_storage_uid, and uid.
Referenced by kcenon::pacs::services::validation::ct_iod_validator::validate_sop_common_module().
is_dose_sr_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_dose_sr_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a Dose Report SR Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is a dose report SR storage SOP class
Definition at line 473 of file sr_storage.cpp.
{
    const auto* info = get_sr_sop_class_info(uid);
    return info != nullptr && info->document_type == sr_document_type::dose_report;
}
References dose_report, get_sr_sop_class_info(), and uid.
is_dx_for_presentation_sop_class()
bool kcenon::pacs::services::sop_classes::is_dx_for_presentation_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a For Presentation SOP Class.
For Presentation images are ready for display and clinical review.
Parameters
uid The SOP Class UID to check
Returns
true if this is a For Presentation DX storage SOP class
Definition at line 324 of file dx_storage.cpp.
{
    const auto* info = get_dx_sop_class_info(uid);
    return info != nullptr && info->image_type == dx_image_type::for_presentation;
}
References for_presentation, get_dx_sop_class_info(), and uid.
Referenced by kcenon::pacs::services::validation::is_for_presentation_dx().
is_dx_for_processing_sop_class()
bool kcenon::pacs::services::sop_classes::is_dx_for_processing_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a For Processing SOP Class.
For Processing images contain raw detector data and typically require additional image processing before display.
Parameters
uid The SOP Class UID to check
Returns
true if this is a For Processing DX storage SOP class
Definition at line 319 of file dx_storage.cpp.
{
    const auto* info = get_dx_sop_class_info(uid);
    return info != nullptr && info->image_type == dx_image_type::for_processing;
}
References for_processing, get_dx_sop_class_info(), and uid.
Referenced by kcenon::pacs::services::validation::is_for_processing_dx().
is_dx_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_dx_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a DX Storage SOP Class.
Includes general DX, mammography, and intra-oral X-ray classes.
Parameters
uid The SOP Class UID to check
Returns
true if this is any DX-related storage SOP class
Definition at line 315 of file dx_storage.cpp.
{
    return get_dx_sop_class_info(uid) != nullptr;
}
References get_dx_sop_class_info(), and uid.
Referenced by kcenon::pacs::services::validation::dx_iod_validator::validate_sop_common_module().
is_enhanced_pet_sop_class()
bool kcenon::pacs::services::sop_classes::is_enhanced_pet_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an Enhanced PET Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is an enhanced PET storage SOP class
Definition at line 152 of file pet_storage.cpp.
{
    const auto* info = get_pet_sop_class_info(uid);
    return info != nullptr && info->is_enhanced;
}
References get_pet_sop_class_info(), and uid.
is_enhanced_xa_sop_class()
bool kcenon::pacs::services::sop_classes::is_enhanced_xa_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an enhanced XA SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is an enhanced XA SOP class
Definition at line 177 of file xa_storage.cpp.
{
    const auto* info = get_xa_sop_class_info(uid);
    return info != nullptr && info->is_enhanced;
}
References get_xa_sop_class_info(), and uid.
is_magnification_view()
bool kcenon::pacs::services::sop_classes::is_magnification_view (mg_view_position position) noexcept
Check if a view position requires magnification.
Parameters
position The view position to check
Returns
true if this view typically involves magnification
Definition at line 181 of file mg_storage.cpp.
{
    return position == mg_view_position::mag ||
           position == mg_view_position::spot_mag;
}
References mag, and spot_mag.
is_mammography_sop_class()
bool kcenon::pacs::services::sop_classes::is_mammography_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a mammography SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is a mammography storage SOP class
Definition at line 329 of file dx_storage.cpp.
{
    const auto* info = get_dx_sop_class_info(uid);
    return info != nullptr && info->is_mammography;
}
References get_dx_sop_class_info(), and uid.
is_mg_for_presentation_sop_class()
bool kcenon::pacs::services::sop_classes::is_mg_for_presentation_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a For Presentation mammography SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is a For Presentation mammography storage SOP class
Definition at line 343 of file mg_storage.cpp.
{
    auto info = get_mg_sop_class_info(uid);
    return info && info->image_type == mg_image_type::for_presentation;
}
References for_presentation, get_mg_sop_class_info(), and uid.
Referenced by kcenon::pacs::services::validation::is_for_presentation_mg().
is_mg_for_processing_sop_class()
bool kcenon::pacs::services::sop_classes::is_mg_for_processing_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a For Processing mammography SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is a For Processing mammography storage SOP class
Definition at line 338 of file mg_storage.cpp.
{
    auto info = get_mg_sop_class_info(uid);
    return info && info->image_type == mg_image_type::for_processing;
}
References for_processing, get_mg_sop_class_info(), and uid.
Referenced by kcenon::pacs::services::validation::is_for_processing_mg().
is_mg_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_mg_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a Mammography Storage SOP Class.
Includes standard mammography and breast tomosynthesis classes.
Parameters
uid The SOP Class UID to check
Returns
true if this is any mammography-related storage SOP class
Definition at line 329 of file mg_storage.cpp.
{
    return get_mg_sop_class_info(uid) != nullptr;
}
References get_mg_sop_class_info(), and uid.
Referenced by kcenon::pacs::services::validation::mg_iod_validator::validate_sop_common_module().
is_mr_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_mr_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an MR Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is an MR storage SOP class
Definition at line 48 of file mr_storage.cpp.
{
    return uid == mr_image_storage_uid ||
           uid == enhanced_mr_image_storage_uid;
}
References enhanced_mr_image_storage_uid, mr_image_storage_uid, and uid.
Referenced by kcenon::pacs::services::validation::mr_iod_validator::validate_sop_common_module().
is_nm_multiframe_sop_class()
bool kcenon::pacs::services::sop_classes::is_nm_multiframe_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID supports multi-frame.
Parameters
uid The SOP Class UID to check
Returns
true if this SOP class supports multi-frame images
Definition at line 146 of file nm_storage.cpp.
{
    const auto* info = get_nm_sop_class_info(uid);
    return info != nullptr && info->supports_multiframe;
}
References get_nm_sop_class_info(), and uid.
is_nm_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_nm_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a NM Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is any NM storage SOP class (current or retired)
Definition at line 142 of file nm_storage.cpp.
{
    return get_nm_sop_class_info(uid) != nullptr;
}
References get_nm_sop_class_info(), and uid.
Referenced by kcenon::pacs::services::validation::nm_iod_validator::validate_sop_common_module().
is_ophthalmic_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_ophthalmic_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an Ophthalmic Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is an ophthalmic storage SOP class
Definition at line 51 of file ophthalmic_storage.cpp.
{
    return uid == ophthalmic_photo_8bit_storage_uid ||
           uid == ophthalmic_photo_16bit_storage_uid ||
           uid == ophthalmic_tomography_storage_uid ||
           uid == wide_field_ophthalmic_photo_storage_uid ||
           uid == ophthalmic_oct_bscan_analysis_storage_uid;
}
References ophthalmic_oct_bscan_analysis_storage_uid, ophthalmic_photo_16bit_storage_uid, ophthalmic_photo_8bit_storage_uid, ophthalmic_tomography_storage_uid, uid, and wide_field_ophthalmic_photo_storage_uid.
Referenced by kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_sop_common_module().
is_parametric_map_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_parametric_map_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is Parametric Map Storage.
Parameters
uid The SOP Class UID to check
Returns
true if this is the Parametric Map Storage SOP class
Definition at line 119 of file parametric_map_storage.cpp.
{
    return uid == parametric_map_storage_uid;
}
References parametric_map_storage_uid, and uid.
Referenced by kcenon::pacs::services::validation::parametric_map_iod_validator::quick_check(), and kcenon::pacs::services::validation::parametric_map_iod_validator::validate_sop_common_module().
is_pet_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_pet_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a PET Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is any PET storage SOP class
Definition at line 148 of file pet_storage.cpp.
{
    return get_pet_sop_class_info(uid) != nullptr;
}
References get_pet_sop_class_info(), and uid.
Referenced by kcenon::pacs::services::validation::pet_iod_validator::validate_sop_common_module().
is_rt_plan_sop_class()
bool kcenon::pacs::services::sop_classes::is_rt_plan_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an RT Plan type.
Parameters
uid The SOP Class UID to check
Returns
true if this is RT Plan or RT Ion Plan
Definition at line 177 of file rt_storage.cpp.
{
    return uid == rt_plan_storage_uid || uid == rt_ion_plan_storage_uid;
}
References rt_ion_plan_storage_uid, rt_plan_storage_uid, and uid.
Referenced by kcenon::pacs::services::validation::rt_plan_iod_validator::validate_sop_common_module().
is_rt_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_rt_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an RT Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is any RT storage SOP class
Definition at line 173 of file rt_storage.cpp.
{
    return get_rt_sop_class_info(uid) != nullptr;
}
References get_rt_sop_class_info(), and uid.
is_screening_view()
bool kcenon::pacs::services::sop_classes::is_screening_view (mg_view_position position) noexcept
Check if a view position is a standard screening view.
Standard screening mammography typically includes CC and MLO views of each breast.
Parameters
position The view position to check
Returns
true if this is a standard screening view
Definition at line 177 of file mg_storage.cpp.
{
    return position == mg_view_position::cc || position == mg_view_position::mlo;
}
References cc, and mlo.
Referenced by kcenon::pacs::services::validation::is_screening_mammogram().
is_seg_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_seg_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a SEG Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is any SEG storage SOP class
Definition at line 260 of file seg_storage.cpp.
{
    return get_seg_sop_class_info(uid) != nullptr;
}
References get_seg_sop_class_info(), and uid.
Referenced by kcenon::pacs::services::validation::seg_iod_validator::quick_check(), and kcenon::pacs::services::validation::seg_iod_validator::validate_sop_common_module().
is_spot_compression_view()
bool kcenon::pacs::services::sop_classes::is_spot_compression_view (mg_view_position position) noexcept
Check if a view position involves spot compression.
Parameters
position The view position to check
Returns
true if this view involves spot compression
Definition at line 186 of file mg_storage.cpp.
{
    return position == mg_view_position::spot ||
           position == mg_view_position::spot_mag;
}
References spot, and spot_mag.
is_sr_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_sr_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an SR Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is any SR storage SOP class
Definition at line 464 of file sr_storage.cpp.
{
    return get_sr_sop_class_info(uid) != nullptr;
}
References get_sr_sop_class_info(), and uid.
Referenced by kcenon::pacs::services::validation::sr_iod_validator::quick_check(), and kcenon::pacs::services::validation::sr_iod_validator::validate_sop_common_module().
is_surface_segmentation_sop_class()
bool kcenon::pacs::services::sop_classes::is_surface_segmentation_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is Surface Segmentation.
Parameters
uid The SOP Class UID to check
Returns
true if this is Surface Segmentation SOP class
Definition at line 264 of file seg_storage.cpp.
{
    return uid == surface_segmentation_storage_uid;
}
References surface_segmentation_storage_uid, and uid.
is_us_multiframe_sop_class()
bool kcenon::pacs::services::sop_classes::is_us_multiframe_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a multi-frame US Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is a multi-frame US storage SOP class
Definition at line 196 of file us_storage.cpp.
{
    const auto* info = get_us_sop_class_info(uid);
    return info != nullptr && info->supports_multiframe;
}
References get_us_sop_class_info(), and uid.
is_us_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_us_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a US Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is any US storage SOP class (current or retired)
Definition at line 192 of file us_storage.cpp.
{
    return get_us_sop_class_info(uid) != nullptr;
}
References get_us_sop_class_info(), and uid.
Referenced by kcenon::pacs::services::validation::us_iod_validator::validate_sop_common_module().
is_valid_breast_laterality()
bool kcenon::pacs::services::sop_classes::is_valid_breast_laterality (std::string_view value) noexcept
Check if a laterality value is valid for mammography.
Parameters
value The DICOM string value
Returns
true if this is a valid mammography laterality value
Definition at line 87 of file mg_storage.cpp.
{
    return value == "L" || value == "R" || value == "B";
}
Referenced by kcenon::pacs::services::validation::mg_iod_validator::check_laterality_consistency().
is_valid_compressed_breast_thickness()
bool kcenon::pacs::services::sop_classes::is_valid_compressed_breast_thickness (double thickness_mm) noexcept
Validate compressed breast thickness.
Parameters
thickness_mm Compressed breast thickness in mm
Returns
true if the thickness is within reasonable range
Definition at line 213 of file mg_storage.cpp.
{
    // Typical compressed breast thickness: 20-100 mm
    // Extended range: 10-150 mm
    return thickness_mm >= 10.0 && thickness_mm <= 150.0;
}
Referenced by kcenon::pacs::services::validation::mg_iod_validator::validate_acquisition_dose_module().
is_valid_compression_force()
bool kcenon::pacs::services::sop_classes::is_valid_compression_force (double force_n) noexcept
Validate compression force value.
Typical compression force for mammography is between 50-200 Newtons. Values outside this range may indicate measurement errors or non-standard technique.
Parameters
force_n Compression force in Newtons
Returns
true if the force is within typical mammography range
Definition at line 203 of file mg_storage.cpp.
{
    // Typical mammography compression force: 50-200 N
    // Extended range to account for variations: 20-300 N
    return force_n >= 20.0 && force_n <= 300.0;
}
Referenced by kcenon::pacs::services::validation::mg_iod_validator::check_compression_force_range().
is_valid_ct_photometric()
bool kcenon::pacs::services::sop_classes::is_valid_ct_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for CT.
CT images are always grayscale (MONOCHROME1 or MONOCHROME2).
Parameters
value The photometric interpretation string
Returns
true if valid for CT images
Definition at line 56 of file ct_storage.cpp.
{
    return value == "MONOCHROME1" || value == "MONOCHROME2";
}
Referenced by kcenon::pacs::services::validation::ct_iod_validator::check_pixel_data_consistency(), and kcenon::pacs::services::validation::ct_processing_iod_validator::check_pixel_data_consistency().
is_valid_dx_photometric()
bool kcenon::pacs::services::sop_classes::is_valid_dx_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for DX.
Parameters
value The DICOM string value
Returns
true if this is a valid DX photometric interpretation
Definition at line 88 of file dx_storage.cpp.
{
    return value == "MONOCHROME1" || value == "MONOCHROME2";
}
Referenced by kcenon::pacs::services::validation::dx_iod_validator::check_photometric_interpretation().
is_valid_laterality_view_combination()
bool kcenon::pacs::services::sop_classes::is_valid_laterality_view_combination (breast_laterality laterality, mg_view_position view) noexcept
Check if laterality and view position are consistent.
Validates that the laterality and view position make clinical sense (e.g., bilateral laterality shouldn't be used with single-breast views).
Parameters
laterality The breast laterality
view The view position
Returns
true if the combination is clinically valid
Definition at line 373 of file mg_storage.cpp.
{
    // Bilateral laterality should only be used for comparison views
    // or special study types, not for standard single-breast views
    if (laterality == breast_laterality::bilateral) {
        // CV (cleavage view) can legitimately be bilateral
        if (view == mg_view_position::cv) {
            return true;
        }
        // Most standard views should specify L or R
        return false;
    }
    // Unknown laterality with a specific view is problematic
    if (laterality == breast_laterality::unknown) {
        // Allow if view is also unspecified
        return view == mg_view_position::other;
    }
    // Left or Right with any view is valid
    return true;
}
References bilateral, cv, other, and unknown.
Referenced by kcenon::pacs::services::validation::mg_iod_validator::check_view_position_validity().
is_valid_mr_photometric()
bool kcenon::pacs::services::sop_classes::is_valid_mr_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for MR.
MR images are always grayscale (MONOCHROME1 or MONOCHROME2).
Parameters
value The photometric interpretation string
Returns
true if valid for MR images
Definition at line 53 of file mr_storage.cpp.
{
    return value == "MONOCHROME1" || value == "MONOCHROME2";
}
Referenced by kcenon::pacs::services::validation::mr_iod_validator::check_pixel_data_consistency().
is_valid_nm_photometric()
bool kcenon::pacs::services::sop_classes::is_valid_nm_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for NM.
Parameters
value The DICOM string value
Returns
true if this is a valid NM photometric interpretation
Definition at line 85 of file nm_storage.cpp.
{
    return value == "MONOCHROME2" || value == "PALETTE COLOR";
}
Referenced by kcenon::pacs::services::validation::nm_iod_validator::check_pixel_data_consistency().
is_valid_ophthalmic_photometric()
bool kcenon::pacs::services::sop_classes::is_valid_ophthalmic_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for ophthalmic imaging.
Ophthalmic Photography supports RGB (color fundus) and MONOCHROME2 (fluorescein angiography, ICG). OCT supports MONOCHROME2. MONOCHROME1 is also valid for certain ophthalmic applications.
Parameters
value The photometric interpretation string
Returns
true if valid for ophthalmic images
Definition at line 59 of file ophthalmic_storage.cpp.
{
    return value == "MONOCHROME1" || value == "MONOCHROME2" ||
           value == "RGB" || value == "YBR_FULL_422" ||
           value == "PALETTE COLOR";
}
Referenced by kcenon::pacs::services::validation::ophthalmic_iod_validator::check_pixel_data_consistency().
is_valid_parametric_map_bits_allocated()
bool kcenon::pacs::services::sop_classes::is_valid_parametric_map_bits_allocated (uint16_t bits_allocated) noexcept
Check if a BitsAllocated value is valid for parametric maps.
Parameters
bits_allocated The BitsAllocated value to check
Returns
true if 32 or 64
Definition at line 84 of file parametric_map_storage.cpp.
{
    return bits_allocated == 32 || bits_allocated == 64;
}
Referenced by kcenon::pacs::services::validation::parametric_map_iod_validator::check_pixel_data_consistency().
is_valid_parametric_map_photometric()
bool kcenon::pacs::services::sop_classes::is_valid_parametric_map_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for parametric maps.
Parametric Maps use MONOCHROME2 for single-component float/double data.
Parameters
value The photometric interpretation string
Returns
true if valid for parametric maps
Definition at line 127 of file parametric_map_storage.cpp.
{
    return value == "MONOCHROME2";
}
Referenced by kcenon::pacs::services::validation::parametric_map_iod_validator::check_pixel_data_consistency().
is_valid_pet_photometric()
bool kcenon::pacs::services::sop_classes::is_valid_pet_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for PET.
Parameters
value The DICOM string value
Returns
true if this is a valid PET photometric interpretation
Definition at line 81 of file pet_storage.cpp.
{
    return value == "MONOCHROME2";
}
Referenced by kcenon::pacs::services::validation::pet_iod_validator::check_pixel_data_consistency().
is_valid_segment_algorithm_type()
bool kcenon::pacs::services::sop_classes::is_valid_segment_algorithm_type (std::string_view value) noexcept
Check if segment algorithm type string is valid.
Parameters
value The DICOM string value
Returns
true if this is a valid segment algorithm type
Definition at line 138 of file seg_storage.cpp.
{
    return value == "AUTOMATIC" ||
           value == "SEMIAUTOMATIC" ||
           value == "MANUAL";
}
Referenced by kcenon::pacs::services::validation::seg_iod_validator::validate_single_segment().
is_valid_segmentation_type()
bool kcenon::pacs::services::sop_classes::is_valid_segmentation_type (std::string_view value) noexcept
Check if segmentation type string is valid.
Parameters
value The DICOM string value
Returns
true if this is a valid segmentation type
Definition at line 85 of file seg_storage.cpp.
{
    return value == "BINARY" || value == "FRACTIONAL";
}
Referenced by kcenon::pacs::services::validation::seg_iod_validator::check_segmentation_type().
is_valid_sr_value_type()
bool kcenon::pacs::services::sop_classes::is_valid_sr_value_type (std::string_view value) noexcept
Check if SR value type string is valid.
Parameters
value The DICOM string value
Returns
true if this is a valid SR value type
Definition at line 175 of file sr_storage.cpp.
{
    return parse_sr_value_type(value) != sr_value_type::unknown;
}
References parse_sr_value_type(), and unknown.
is_valid_us_photometric()
bool kcenon::pacs::services::sop_classes::is_valid_us_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for US.
Parameters
value The DICOM string value
Returns
true if this is a valid US photometric interpretation
Definition at line 116 of file us_storage.cpp.
{
    return value == "MONOCHROME1" ||
           value == "MONOCHROME2" ||
           value == "PALETTE COLOR" ||
           value == "RGB" ||
           value == "YBR_FULL" ||
           value == "YBR_FULL_422";
}
Referenced by kcenon::pacs::services::validation::us_iod_validator::check_pixel_data_consistency().
is_valid_wsi_photometric()
bool kcenon::pacs::services::sop_classes::is_valid_wsi_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for WSI.
WSI images support RGB (brightfield), YBR variants (compressed), and MONOCHROME2 (fluorescence single-channel).
Parameters
value The photometric interpretation string
Returns
true if valid for WSI images
Definition at line 51 of file wsi_storage.cpp.
{
    return value == "RGB" || value == "YBR_FULL_422" ||
           value == "YBR_ICT" || value == "YBR_RCT" ||
           value == "MONOCHROME2";
}
Referenced by kcenon::pacs::services::validation::wsi_iod_validator::check_pixel_data_consistency().
is_valid_xa_photometric()
bool kcenon::pacs::services::sop_classes::is_valid_xa_photometric (std::string_view value) noexcept
Check if photometric interpretation is valid for XA.
Parameters
value The DICOM string value
Returns
true if this is a valid XA photometric interpretation
Definition at line 85 of file xa_storage.cpp.
{
    return value == "MONOCHROME1" || value == "MONOCHROME2";
}
Referenced by kcenon::pacs::services::validation::xa_iod_validator::check_xa_photometric().
is_waveform_annotation_sop_class()
bool kcenon::pacs::services::sop_classes::is_waveform_annotation_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a Waveform Annotation SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is the waveform annotation SOP class
Definition at line 185 of file waveform_storage.cpp.
{
    return uid == waveform_annotation_storage_uid;
}
References uid, and waveform_annotation_storage_uid.
Referenced by kcenon::pacs::services::validation::waveform_ps_iod_validator::quick_check(), kcenon::pacs::services::validation::waveform_ps_iod_validator::validate(), and kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_sop_common_module().
is_waveform_presentation_state_sop_class()
bool kcenon::pacs::services::sop_classes::is_waveform_presentation_state_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a Waveform Presentation State SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is the waveform presentation state SOP class
Definition at line 181 of file waveform_storage.cpp.
{
    return uid == waveform_presentation_state_storage_uid;
}
References uid, and waveform_presentation_state_storage_uid.
Referenced by kcenon::pacs::services::validation::waveform_ps_iod_validator::quick_check(), kcenon::pacs::services::validation::waveform_ps_iod_validator::validate(), and kcenon::pacs::services::validation::waveform_ps_iod_validator::validate_sop_common_module().
is_waveform_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_waveform_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a Waveform Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is any waveform storage SOP class
Definition at line 177 of file waveform_storage.cpp.
{
    return get_waveform_sop_class_info(uid) != nullptr;
}
References get_waveform_sop_class_info(), and uid.
is_wsi_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_wsi_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a WSI Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is a WSI storage SOP class
Definition at line 47 of file wsi_storage.cpp.
{
    return uid == wsi_image_storage_uid;
}
References uid, and wsi_image_storage_uid.
Referenced by kcenon::pacs::services::validation::wsi_iod_validator::validate_sop_common_module().
is_xa_3d_sop_class()
bool kcenon::pacs::services::sop_classes::is_xa_3d_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a 3D XA SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is a 3D XA storage SOP class
Definition at line 182 of file xa_storage.cpp.
{
    const auto* info = get_xa_sop_class_info(uid);
    return info != nullptr && info->is_3d;
}
References get_xa_sop_class_info(), and uid.
is_xa_multiframe_sop_class()
bool kcenon::pacs::services::sop_classes::is_xa_multiframe_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is a multi-frame XA Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is a multi-frame XA storage SOP class
Definition at line 172 of file xa_storage.cpp.
{
    const auto* info = get_xa_sop_class_info(uid);
    return info != nullptr && info->supports_multiframe;
}
References get_xa_sop_class_info(), and uid.
is_xa_storage_sop_class()
bool kcenon::pacs::services::sop_classes::is_xa_storage_sop_class (std::string_view uid) noexcept
Check if a SOP Class UID is an XA/XRF Storage SOP Class.
Parameters
uid The SOP Class UID to check
Returns
true if this is any XA/XRF storage SOP class
Definition at line 168 of file xa_storage.cpp.
{
    return get_xa_sop_class_info(uid) != nullptr;
}
References get_xa_sop_class_info(), and uid.
Referenced by kcenon::pacs::services::validation::xa_iod_validator::validate_sop_common_module().
parse_body_part()
dx_body_part kcenon::pacs::services::sop_classes::parse_body_part (std::string_view value) noexcept
Parse DICOM body part examined string.
Parameters
value The DICOM string value
Returns
The corresponding enum value, or other if unknown
Definition at line 194 of file dx_storage.cpp.
{
    if (value == "CHEST") return dx_body_part::chest;
    if (value == "ABDOMEN") return dx_body_part::abdomen;
    if (value == "PELVIS") return dx_body_part::pelvis;
    if (value == "SPINE" || value == "CSPINE" || value == "TSPINE" ||
        value == "LSPINE" || value == "SSPINE") {
        return dx_body_part::spine;
    }
    if (value == "SKULL" || value == "HEAD") return dx_body_part::skull;
    if (value == "HAND" || value == "FINGER") return dx_body_part::hand;
    if (value == "FOOT" || value == "TOE") return dx_body_part::foot;
    if (value == "KNEE") return dx_body_part::knee;
    if (value == "ELBOW") return dx_body_part::elbow;
    if (value == "SHOULDER") return dx_body_part::shoulder;
    if (value == "HIP") return dx_body_part::hip;
    if (value == "WRIST") return dx_body_part::wrist;
    if (value == "ANKLE") return dx_body_part::ankle;
    if (value == "EXTREMITY" || value == "ARM" || value == "LEG") {
        return dx_body_part::extremity;
    }
    if (value == "BREAST") return dx_body_part::breast;
    return dx_body_part::other;
}
References abdomen, ankle, breast, chest, elbow, extremity, foot, hand, hip, knee, other, pelvis, shoulder, skull, spine, and wrist.
parse_breast_laterality()
breast_laterality kcenon::pacs::services::sop_classes::parse_breast_laterality (std::string_view value) noexcept
Parse DICOM laterality string to enum.
Parameters
value The DICOM string value
Returns
The corresponding enum value, or unknown if not recognized
Definition at line 57 of file mg_storage.cpp.
{
    if (value.empty()) {
        return breast_laterality::unknown;
    }
    // Handle single character codes
    if (value.size() == 1) {
        switch (std::toupper(static_cast<unsigned char>(value[0]))) {
            case 'L': return breast_laterality::left;
            case 'R': return breast_laterality::right;
            case 'B': return breast_laterality::bilateral;
        }
    }
    // Handle full words (case-insensitive)
    std::string lower_value;
    lower_value.reserve(value.size());
    for (char c : value) {
        lower_value += static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    }
    if (lower_value == "left") return breast_laterality::left;
    if (lower_value == "right") return breast_laterality::right;
    if (lower_value == "bilateral" || lower_value == "both") {
        return breast_laterality::bilateral;
    }
    return breast_laterality::unknown;
}
References bilateral, left, right, and unknown.
Referenced by kcenon::pacs::services::validation::mg_iod_validator::check_view_position_validity().
parse_detector_type()
dx_detector_type kcenon::pacs::services::sop_classes::parse_detector_type (std::string_view value) noexcept
Parse DICOM detector type string.
Parameters
value The DICOM string value
Returns
The corresponding enum value
Definition at line 159 of file dx_storage.cpp.
{
    if (value == "DIRECT") return dx_detector_type::direct;
    if (value == "INDIRECT") return dx_detector_type::indirect;
    if (value == "STORAGE") return dx_detector_type::storage;
    if (value == "FILM") return dx_detector_type::film;
    // Default to direct for modern DR systems
    return dx_detector_type::direct;
}
References direct, film, indirect, and storage.
parse_dx_photometric_interpretation()
dx_photometric_interpretation kcenon::pacs::services::sop_classes::parse_dx_photometric_interpretation (std::string_view value) noexcept
Parse DICOM photometric interpretation string for DX.
Parameters
value The DICOM string value
Returns
The corresponding enum value, or monochrome2 if unknown
Definition at line 80 of file dx_storage.cpp.
{
    if (value == "MONOCHROME1") {
        return dx_photometric_interpretation::monochrome1;
    }
    // Default to MONOCHROME2 for DX
    return dx_photometric_interpretation::monochrome2;
}
References monochrome1, and monochrome2.
parse_mg_view_position()
mg_view_position kcenon::pacs::services::sop_classes::parse_mg_view_position (std::string_view value) noexcept
Parse DICOM view position string to mammography view enum.
Parameters
value The DICOM string value
Returns
The corresponding enum value, or other if not recognized
Definition at line 123 of file mg_storage.cpp.
{
    if (value.empty()) {
        return mg_view_position::other;
    }
    // Convert to uppercase for comparison
    std::string upper_value;
    upper_value.reserve(value.size());
    for (char c : value) {
        upper_value += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    }
    // Standard views
    if (upper_value == "CC") return mg_view_position::cc;
    if (upper_value == "MLO") return mg_view_position::mlo;
    if (upper_value == "ML") return mg_view_position::ml;
    if (upper_value == "LM") return mg_view_position::lm;
    // Extended CC views
    if (upper_value == "XCCL") return mg_view_position::xccl;
    if (upper_value == "XCCM") return mg_view_position::xccm;
    // Other standard views
    if (upper_value == "FB") return mg_view_position::fb;
    if (upper_value == "SIO") return mg_view_position::sio;
    if (upper_value == "ISO") return mg_view_position::iso;
    if (upper_value == "CV") return mg_view_position::cv;
    if (upper_value == "AT") return mg_view_position::at;
    // Spot/magnification views
    if (upper_value == "SPOT") return mg_view_position::spot;
    if (upper_value == "MAG") return mg_view_position::mag;
    if (upper_value == "SPOT MAG" || upper_value == "SPOTMAG") {
        return mg_view_position::spot_mag;
    }
    // Rolled views
    if (upper_value == "RL") return mg_view_position::rl;
    if (upper_value == "RM") return mg_view_position::rm;
    if (upper_value == "RS") return mg_view_position::rs;
    if (upper_value == "RI") return mg_view_position::ri;
    // Specialized views
    if (upper_value == "TAN" || upper_value == "TANGENTIAL") {
        return mg_view_position::tangen;
    }
    if (upper_value == "ID" || upper_value == "IMPLANT DISPLACED" ||
        upper_value == "IMPLANTDISPLACED") {
        return mg_view_position::implant;
    }
    return mg_view_position::other;
}
References at, cc, cv, fb, implant, iso, lm, mag, ml, mlo, other, ri, rl, rm, rs, sio, spot, spot_mag, tangen, xccl, and xccm.
Referenced by kcenon::pacs::services::validation::mg_iod_validator::check_view_position_validity(), kcenon::pacs::services::validation::is_screening_mammogram(), and kcenon::pacs::services::validation::mg_iod_validator::validate_breast_implant_module().
parse_nm_collimator_type()
nm_collimator_type kcenon::pacs::services::sop_classes::parse_nm_collimator_type (std::string_view value) noexcept
Parse collimator type from DICOM string.
Parameters
value The DICOM string value
Returns
The collimator type
Definition at line 229 of file nm_storage.cpp.
{
    if (value == "PARA" || value == "PARALLEL") {
        return nm_collimator_type::parallel;
    }
    if (value == "FANB" || value == "FAN BEAM") {
        return nm_collimator_type::fan_beam;
    }
    if (value == "CONE" || value == "CONE BEAM") {
        return nm_collimator_type::cone_beam;
    }
    if (value == "PINH" || value == "PINHOLE") {
        return nm_collimator_type::pinhole;
    }
    if (value == "DIVG" || value == "DIVERGING") {
        return nm_collimator_type::diverging;
    }
    if (value == "CVGB" || value == "CONVERGING") {
        return nm_collimator_type::converging;
    }
    if (value == "NONE") {
        return nm_collimator_type::none;
    }
    return nm_collimator_type::parallel;
}
References cone_beam, converging, diverging, fan_beam, none, parallel, and pinhole.
parse_nm_photometric_interpretation()
nm_photometric_interpretation kcenon::pacs::services::sop_classes::parse_nm_photometric_interpretation (std::string_view value) noexcept
Parse DICOM photometric interpretation string.
Parameters
value The DICOM string value
Returns
The corresponding enum value, or monochrome2 if unknown
Definition at line 78 of file nm_storage.cpp.
{
    if (value == "PALETTE COLOR") {
        return nm_photometric_interpretation::palette_color;
    }
    return nm_photometric_interpretation::monochrome2;
}
References monochrome2, and palette_color.
parse_nm_type_of_data()
nm_type_of_data kcenon::pacs::services::sop_classes::parse_nm_type_of_data (std::string_view value) noexcept
Parse NM type of data from DICOM string.
Parameters
value The DICOM string value
Returns
The type of data
Definition at line 177 of file nm_storage.cpp.
{
    if (value == "STATIC") {
        return nm_type_of_data::static_image;
    }
    if (value == "DYNAMIC") {
        return nm_type_of_data::dynamic;
    }
    if (value == "GATED") {
        return nm_type_of_data::gated;
    }
    if (value == "WHOLE BODY") {
        return nm_type_of_data::whole_body;
    }
    if (value == "RECON TOMO") {
        return nm_type_of_data::recon_tomo;
    }
    if (value == "RECON GATED TOMO") {
        return nm_type_of_data::recon_gated_tomo;
    }
    if (value == "TOMO") {
        return nm_type_of_data::tomo;
    }
    if (value == "GATED TOMO") {
        return nm_type_of_data::gated_tomo;
    }
    return nm_type_of_data::static_image;
}
References dynamic, gated, gated_tomo, recon_gated_tomo, recon_tomo, static_image, tomo, and whole_body.
parse_pet_photometric_interpretation()
pet_photometric_interpretation kcenon::pacs::services::sop_classes::parse_pet_photometric_interpretation (std::string_view value) noexcept
Parse DICOM photometric interpretation string.
Parameters
value The DICOM string value
Returns
The corresponding enum value, or monochrome2 if unknown
Definition at line 76 of file pet_storage.cpp.
{
    // PET images are always MONOCHROME2
    return pet_photometric_interpretation::monochrome2;
}
References monochrome2.
parse_pet_reconstruction_type()
pet_reconstruction_type kcenon::pacs::services::sop_classes::parse_pet_reconstruction_type (std::string_view value) noexcept
Parse PET reconstruction type from string.
Parameters
value The string value
Returns
The reconstruction type
Definition at line 180 of file pet_storage.cpp.
{
    if (value == "FBP" || value == "FILTERED BACK PROJECTION") {
        return pet_reconstruction_type::fbp;
    }
    if (value == "OSEM" || value == "3D-OSEM") {
        return pet_reconstruction_type::osem;
    }
    if (value == "MLEM") {
        return pet_reconstruction_type::mlem;
    }
    if (value.find("TOF") != std::string_view::npos) {
        return pet_reconstruction_type::tof_osem;
    }
    if (value.find("PSF") != std::string_view::npos) {
        return pet_reconstruction_type::psf_osem;
    }
    return pet_reconstruction_type::other;
}
References fbp, mlem, osem, other, psf_osem, and tof_osem.
parse_pet_units()
pet_units kcenon::pacs::services::sop_classes::parse_pet_units (std::string_view value) noexcept
Parse PET units from DICOM string.
Parameters
value The DICOM string value
Returns
The units type
Definition at line 225 of file pet_storage.cpp.
{
    if (value == "CNTS") {
        return pet_units::cnts;
    }
    if (value == "BQML" || value == "BQ/ML") {
        return pet_units::bqml;
    }
    if (value == "GML" || value == "G/ML") {
        return pet_units::gml;
    }
    if (value == "SUV" || value == "SUV_BW") {
        return pet_units::suv_bw;
    }
    if (value == "SUL" || value == "SUV_LBM") {
        return pet_units::suv_lbm;
    }
    if (value == "SUV_BSA") {
        return pet_units::suv_bsa;
    }
    if (value == "%ID/G" || value == "PERCENT_ID_GRAM") {
        return pet_units::percent_id_gram;
    }
    return pet_units::other;
}
References bqml, cnts, gml, other, percent_id_gram, suv_bsa, suv_bw, and suv_lbm.
parse_photometric_interpretation()
us_photometric_interpretation kcenon::pacs::services::sop_classes::parse_photometric_interpretation (std::string_view value) noexcept
Parse DICOM photometric interpretation string.
Parameters
value The DICOM string value
Returns
The corresponding enum value, or monochrome2 if unknown
Definition at line 93 of file us_storage.cpp.
{
    if (value == "MONOCHROME1") {
        return us_photometric_interpretation::monochrome1;
    }
    if (value == "MONOCHROME2") {
        return us_photometric_interpretation::monochrome2;
    }
    if (value == "PALETTE COLOR") {
        return us_photometric_interpretation::palette_color;
    }
    if (value == "RGB") {
        return us_photometric_interpretation::rgb;
    }
    if (value == "YBR_FULL") {
        return us_photometric_interpretation::ybr_full;
    }
    if (value == "YBR_FULL_422") {
        return us_photometric_interpretation::ybr_full_422;
    }
    // Default to MONOCHROME2 for unknown values
    return us_photometric_interpretation::monochrome2;
}
References monochrome1, monochrome2, palette_color, rgb, ybr_full, and ybr_full_422.
parse_pixel_value_representation()
pixel_value_representation kcenon::pacs::services::sop_classes::parse_pixel_value_representation (uint16_t bits_allocated) noexcept
Parse pixel value representation from BitsAllocated value.
Parameters
bits_allocated The BitsAllocated value
Returns
The pixel value representation, defaults to float32 for unknown values
Definition at line 77 of file parametric_map_storage.cpp.
{
    if (bits_allocated == 64) {
        return pixel_value_representation::float64;
    }
    return pixel_value_representation::float32;
}
References float32, and float64.
parse_rt_beam_type()
rt_beam_type kcenon::pacs::services::sop_classes::parse_rt_beam_type (std::string_view value) noexcept
Parse RT beam type from DICOM string.
Parameters
value The DICOM string value
Returns
The beam type
Definition at line 532 of file rt_storage.cpp.
{
    if (value == "DYNAMIC") {
        return rt_beam_type::dynamic;
    }
    return rt_beam_type::static_beam;
}
References dynamic, and static_beam.
parse_rt_dose_summation_type()
rt_dose_summation_type kcenon::pacs::services::sop_classes::parse_rt_dose_summation_type (std::string_view value) noexcept
Parse RT dose summation type from DICOM string.
Parameters
value The DICOM string value
Returns
The dose summation type
Definition at line 312 of file rt_storage.cpp.
{
    if (value == "PLAN") {
        return rt_dose_summation_type::plan;
    }
    if (value == "MULTI_PLAN") {
        return rt_dose_summation_type::multi_plan;
    }
    if (value == "FRACTION") {
        return rt_dose_summation_type::fraction;
    }
    if (value == "BEAM") {
        return rt_dose_summation_type::beam;
    }
    if (value == "BRACHY") {
        return rt_dose_summation_type::brachy;
    }
    if (value == "FRACTION_SESSION") {
        return rt_dose_summation_type::fraction_session;
    }
    if (value == "BEAM_SESSION") {
        return rt_dose_summation_type::beam_session;
    }
    if (value == "BRACHY_SESSION") {
        return rt_dose_summation_type::brachy_session;
    }
    if (value == "CONTROL_POINT") {
        return rt_dose_summation_type::control_point;
    }
    if (value == "RECORD") {
        return rt_dose_summation_type::record;
    }
    return rt_dose_summation_type::plan;
}
References beam, beam_session, brachy, brachy_session, control_point, fraction, fraction_session, multi_plan, plan, and record.
parse_rt_dose_type()
rt_dose_type kcenon::pacs::services::sop_classes::parse_rt_dose_type (std::string_view value) noexcept
Parse RT dose type from DICOM string.
Parameters
value The DICOM string value
Returns
The dose type
Definition at line 272 of file rt_storage.cpp.
{
    if (value == "EFFECTIVE") {
        return rt_dose_type::effective;
    }
    if (value == "ERROR") {
        return rt_dose_type::error;
    }
    return rt_dose_type::physical;
}
References effective, error, and physical.
parse_rt_dose_units()
rt_dose_units kcenon::pacs::services::sop_classes::parse_rt_dose_units (std::string_view value) noexcept
Parse RT dose units from DICOM string.
Parameters
value The DICOM string value
Returns
The dose units
Definition at line 360 of file rt_storage.cpp.
{
    if (value == "RELATIVE") {
        return rt_dose_units::relative;
    }
    return rt_dose_units::gy;
}
References gy, and relative.
parse_rt_image_plane()
rt_image_plane kcenon::pacs::services::sop_classes::parse_rt_image_plane (std::string_view value) noexcept
Parse RT image plane from DICOM string.
Parameters
value The DICOM string value
Returns
The image plane type
Definition at line 638 of file rt_storage.cpp.
{
    if (value == "AXIAL") {
        return rt_image_plane::axial;
    }
    if (value == "LOCALIZER") {
        return rt_image_plane::localizer;
    }
    if (value == "DRR") {
        return rt_image_plane::drr;
    }
    if (value == "PORTAL") {
        return rt_image_plane::portal;
    }
    if (value == "FLUENCE") {
        return rt_image_plane::fluence;
    }
    return rt_image_plane::portal;
}
References axial, drr, fluence, localizer, and portal.
parse_rt_plan_geometry()
rt_plan_geometry kcenon::pacs::services::sop_classes::parse_rt_plan_geometry (std::string_view value) noexcept
Parse RT plan geometry from DICOM string.
Parameters
value The DICOM string value
Returns
The plan geometry
Definition at line 249 of file rt_storage.cpp.
{
    if (value == "TREATMENT_DEVICE") {
        return rt_plan_geometry::treatment_device;
    }
    return rt_plan_geometry::patient;
}
References patient, and treatment_device.
parse_rt_plan_intent()
rt_plan_intent kcenon::pacs::services::sop_classes::parse_rt_plan_intent (std::string_view value) noexcept
Parse RT plan intent from DICOM string.
Parameters
value The DICOM string value
Returns
The plan intent
Definition at line 210 of file rt_storage.cpp.
{
    if (value == "CURATIVE") {
        return rt_plan_intent::curative;
    }
    if (value == "PALLIATIVE") {
        return rt_plan_intent::palliative;
    }
    if (value == "PROPHYLACTIC") {
        return rt_plan_intent::prophylactic;
    }
    if (value == "VERIFICATION") {
        return rt_plan_intent::verification;
    }
    if (value == "MACHINE_QA") {
        return rt_plan_intent::machine_qa;
    }
    if (value == "RESEARCH") {
        return rt_plan_intent::research;
    }
    if (value == "SERVICE") {
        return rt_plan_intent::service;
    }
    return rt_plan_intent::curative;
}
References curative, machine_qa, palliative, prophylactic, research, service, and verification.
parse_rt_radiation_type()
rt_radiation_type kcenon::pacs::services::sop_classes::parse_rt_radiation_type (std::string_view value) noexcept
Parse RT radiation type from DICOM string.
Parameters
value The DICOM string value
Returns
The radiation type
Definition at line 559 of file rt_storage.cpp.
{
    if (value == "PHOTON") {
        return rt_radiation_type::photon;
    }
    if (value == "ELECTRON") {
        return rt_radiation_type::electron;
    }
    if (value == "NEUTRON") {
        return rt_radiation_type::neutron;
    }
    if (value == "PROTON") {
        return rt_radiation_type::proton;
    }
    if (value == "ION") {
        return rt_radiation_type::ion;
    }
    return rt_radiation_type::photon;
}
References electron, ion, neutron, photon, and proton.
parse_rt_roi_generation_algorithm()
rt_roi_generation_algorithm kcenon::pacs::services::sop_classes::parse_rt_roi_generation_algorithm (std::string_view value) noexcept
Parse RT ROI generation algorithm from DICOM string.
Parameters
value The DICOM string value
Returns
The generation algorithm
Definition at line 508 of file rt_storage.cpp.
{
    if (value == "AUTOMATIC") {
        return rt_roi_generation_algorithm::automatic;
    }
    if (value == "SEMIAUTOMATIC") {
        return rt_roi_generation_algorithm::semiautomatic;
    }
    return rt_roi_generation_algorithm::manual;
}
References automatic, manual, and semiautomatic.
parse_rt_roi_interpreted_type()
rt_roi_interpreted_type kcenon::pacs::services::sop_classes::parse_rt_roi_interpreted_type (std::string_view value) noexcept
Parse RT ROI interpreted type from DICOM string.
Parameters
value The DICOM string value
Returns
The ROI interpreted type
Definition at line 421 of file rt_storage.cpp.
{
    if (value == "EXTERNAL") {
        return rt_roi_interpreted_type::external;
    }
    if (value == "PTV") {
        return rt_roi_interpreted_type::ptv;
    }
    if (value == "CTV") {
        return rt_roi_interpreted_type::ctv;
    }
    if (value == "GTV") {
        return rt_roi_interpreted_type::gtv;
    }
    if (value == "ORGAN") {
        return rt_roi_interpreted_type::organ;
    }
    if (value == "AVOIDANCE") {
        return rt_roi_interpreted_type::avoidance;
    }
    if (value == "TREATED_VOLUME") {
        return rt_roi_interpreted_type::treated_volume;
    }
    if (value == "IRRAD_VOLUME") {
        return rt_roi_interpreted_type::irrad_volume;
    }
    if (value == "BOLUS") {
        return rt_roi_interpreted_type::bolus;
    }
    if (value == "BRACHY_CHANNEL") {
        return rt_roi_interpreted_type::brachy_channel;
    }
    if (value == "BRACHY_ACCESSORY") {
        return rt_roi_interpreted_type::brachy_accessory;
    }
    if (value == "BRACHY_SRC_APPL") {
        return rt_roi_interpreted_type::brachy_src_appl;
    }
    if (value == "BRACHY_CHNL_SHLD") {
        return rt_roi_interpreted_type::brachy_chnl_shld;
    }
    if (value == "SUPPORT") {
        return rt_roi_interpreted_type::support;
    }
    if (value == "FIXATION") {
        return rt_roi_interpreted_type::fixation;
    }
    if (value == "DOSE_REGION") {
        return rt_roi_interpreted_type::dose_region;
    }
    if (value == "CONTRAST_AGENT") {
        return rt_roi_interpreted_type::contrast_agent;
    }
    if (value == "CAVITY") {
        return rt_roi_interpreted_type::cavity;
    }
    if (value == "MARKER") {
        return rt_roi_interpreted_type::marker;
    }
    if (value == "REGISTRATION") {
        return rt_roi_interpreted_type::registration;
    }
    if (value == "ISOCENTER") {
        return rt_roi_interpreted_type::isocenter;
    }
    if (value == "CONTROL") {
        return rt_roi_interpreted_type::control_point;
    }
    return rt_roi_interpreted_type::organ;
}
References avoidance, bolus, brachy_accessory, brachy_channel, brachy_chnl_shld, brachy_src_appl, cavity, contrast_agent, control_point, ctv, dose_region, external, fixation, gtv, irrad_volume, isocenter, marker, organ, ptv, registration, support, and treated_volume.
parse_rt_treatment_delivery_type()
rt_treatment_delivery_type kcenon::pacs::services::sop_classes::parse_rt_treatment_delivery_type (std::string_view value) noexcept
Parse RT treatment delivery type from DICOM string.
Parameters
value The DICOM string value
Returns
The treatment delivery type
Definition at line 599 of file rt_storage.cpp.
{
    if (value == "TREATMENT") {
        return rt_treatment_delivery_type::treatment;
    }
    if (value == "OPEN_PORTFILM") {
        return rt_treatment_delivery_type::open_portfilm;
    }
    if (value == "TRMT_PORTFILM") {
        return rt_treatment_delivery_type::trmt_portfilm;
    }
    if (value == "CONTINUATION") {
        return rt_treatment_delivery_type::continuation;
    }
    if (value == "SETUP") {
        return rt_treatment_delivery_type::setup;
    }
    return rt_treatment_delivery_type::treatment;
}
References continuation, open_portfilm, setup, treatment, and trmt_portfilm.
parse_segment_algorithm_type()
segment_algorithm_type kcenon::pacs::services::sop_classes::parse_segment_algorithm_type (std::string_view value) noexcept
Parse segment algorithm type from DICOM string.
Parameters
value The DICOM string value
Returns
The segment algorithm type
Definition at line 128 of file seg_storage.cpp.
{
    if (value == "AUTOMATIC") {
        return segment_algorithm_type::automatic;
    }
    if (value == "SEMIAUTOMATIC") {
        return segment_algorithm_type::semiautomatic;
    }
    return segment_algorithm_type::manual;
}
References automatic, manual, and semiautomatic.
parse_segmentation_fractional_type()
segmentation_fractional_type kcenon::pacs::services::sop_classes::parse_segmentation_fractional_type (std::string_view value) noexcept
Parse segmentation fractional type from DICOM string.
Parameters
value The DICOM string value
Returns
The segmentation fractional type
Definition at line 104 of file seg_storage.cpp.
{
    if (value == "OCCUPANCY") {
        return segmentation_fractional_type::occupancy;
    }
    return segmentation_fractional_type::probability;
}
References occupancy, and probability.
parse_segmentation_type()
segmentation_type kcenon::pacs::services::sop_classes::parse_segmentation_type (std::string_view value) noexcept
Parse segmentation type from DICOM string.
Parameters
value The DICOM string value
Returns
The segmentation type
Definition at line 78 of file seg_storage.cpp.
{
    if (value == "FRACTIONAL") {
        return segmentation_type::fractional;
    }
    return segmentation_type::binary;
}
References binary, and fractional.
parse_sr_completion_flag()
sr_completion_flag kcenon::pacs::services::sop_classes::parse_sr_completion_flag (std::string_view value) noexcept
Parse SR completion flag from DICOM string.
Parameters
value The DICOM string value
Returns
The completion flag
Definition at line 230 of file sr_storage.cpp.
{
    if (value == "COMPLETE") {
        return sr_completion_flag::complete;
    }
    return sr_completion_flag::partial;
}
References complete, and partial.
parse_sr_relationship_type()
sr_relationship_type kcenon::pacs::services::sop_classes::parse_sr_relationship_type (std::string_view value) noexcept
Parse SR relationship type from DICOM string.
Parameters
value The DICOM string value
Returns
The SR relationship type
Definition at line 205 of file sr_storage.cpp.
{
    if (value == "CONTAINS") return sr_relationship_type::contains;
    if (value == "HAS OBS CONTEXT") return sr_relationship_type::has_obs_context;
    if (value == "HAS ACQ CONTEXT") return sr_relationship_type::has_acq_context;
    if (value == "HAS CONCEPT MOD") return sr_relationship_type::has_concept_mod;
    if (value == "HAS PROPERTIES") return sr_relationship_type::has_properties;
    if (value == "INFERRED FROM") return sr_relationship_type::inferred_from;
    if (value == "SELECTED FROM") return sr_relationship_type::selected_from;
    return sr_relationship_type::unknown;
}
References contains, has_acq_context, has_concept_mod, has_obs_context, has_properties, inferred_from, selected_from, and unknown.
parse_sr_value_type()
sr_value_type kcenon::pacs::services::sop_classes::parse_sr_value_type (std::string_view value) noexcept
Parse SR value type from DICOM string.
Parameters
value The DICOM string value
Returns
The SR value type
Definition at line 155 of file sr_storage.cpp.
{
    if (value == "TEXT") return sr_value_type::text;
    if (value == "CODE") return sr_value_type::code;
    if (value == "NUM") return sr_value_type::num;
    if (value == "DATETIME") return sr_value_type::datetime;
    if (value == "DATE") return sr_value_type::date;
    if (value == "TIME") return sr_value_type::time;
    if (value == "UIDREF") return sr_value_type::uidref;
    if (value == "PNAME") return sr_value_type::pname;
    if (value == "COMPOSITE") return sr_value_type::composite;
    if (value == "IMAGE") return sr_value_type::image;
    if (value == "WAVEFORM") return sr_value_type::waveform;
    if (value == "SCOORD") return sr_value_type::scoord;
    if (value == "SCOORD3D") return sr_value_type::scoord3d;
    if (value == "TCOORD") return sr_value_type::tcoord;
    if (value == "CONTAINER") return sr_value_type::container;
    if (value == "TABLE") return sr_value_type::table;
    return sr_value_type::unknown;
}
References code, composite, container, date, datetime, image, num, pname, scoord, scoord3d, table, tcoord, text, time, uidref, unknown, and waveform.
Referenced by is_valid_sr_value_type(), and kcenon::pacs::services::validation::sr_iod_validator::validate_content_item().
parse_sr_verification_flag()
sr_verification_flag kcenon::pacs::services::sop_classes::parse_sr_verification_flag (std::string_view value) noexcept
Parse SR verification flag from DICOM string.
Parameters
value The DICOM string value
Returns
The verification flag
Definition at line 247 of file sr_storage.cpp.
{
    if (value == "VERIFIED") {
        return sr_verification_flag::verified;
    }
    return sr_verification_flag::unverified;
}
References unverified, and verified.
parse_view_position()
dx_view_position kcenon::pacs::services::sop_classes::parse_view_position (std::string_view value) noexcept
Parse DICOM view position string.
Parameters
value The DICOM string value
Returns
The corresponding enum value, or other if unknown
Definition at line 126 of file dx_storage.cpp.
{
    if (value == "AP") return dx_view_position::ap;
    if (value == "PA") return dx_view_position::pa;
    if (value == "LATERAL" || value == "LAT" ||
        value == "LL" || value == "RL") {
        return dx_view_position::lateral;
    }
    if (value == "OBLIQUE" || value == "OBL" ||
        value == "LAO" || value == "RAO" ||
        value == "LPO" || value == "RPO") {
        return dx_view_position::oblique;
    }
    return dx_view_position::other;
}
References ap, lateral, oblique, other, and pa.
parse_xa_photometric_interpretation()
xa_photometric_interpretation kcenon::pacs::services::sop_classes::parse_xa_photometric_interpretation (std::string_view value) noexcept
Parse DICOM photometric interpretation string for XA.
Parameters
value The DICOM string value
Returns
The corresponding enum value, or monochrome2 if unknown
Definition at line 77 of file xa_storage.cpp.
{
    if (value == "MONOCHROME1") {
        return xa_photometric_interpretation::monochrome1;
    }
    // Default to MONOCHROME2 for unknown or MONOCHROME2 values
    return xa_photometric_interpretation::monochrome2;
}
References monochrome1, and monochrome2.
rt_sop_class_has_pixel_data()
bool kcenon::pacs::services::sop_classes::rt_sop_class_has_pixel_data (std::string_view uid) noexcept
Check if a SOP Class UID contains pixel data.
Parameters
uid The SOP Class UID to check
Returns
true if this RT SOP class contains pixel data
Definition at line 181 of file rt_storage.cpp.
{
    const auto* info = get_rt_sop_class_info(uid);
    return info != nullptr && info->has_pixel_data;
}
References get_rt_sop_class_info(), and uid.
sr_supports_spatial_coords()
bool kcenon::pacs::services::sop_classes::sr_supports_spatial_coords (std::string_view uid) noexcept
Check if an SR SOP Class supports spatial coordinates.
Parameters
uid The SOP Class UID to check
Returns
true if the SR can contain SCOORD or SCOORD3D content items
Definition at line 478 of file sr_storage.cpp.
{
    const auto* info = get_sr_sop_class_info(uid);
    return info != nullptr && info->supports_spatial_coords;
}
References get_sr_sop_class_info(), and uid.
to_string() [1/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (breast_laterality laterality) noexcept
Convert breast laterality enum to DICOM string.
Parameters
laterality The breast laterality
Returns
DICOM-compliant string representation ("L", "R", "B", or empty)
Definition at line 47 of file mg_storage.cpp.
{
    switch (laterality) {
        case breast_laterality::left:       return "L";
        case breast_laterality::right:      return "R";
        case breast_laterality::bilateral:  return "B";
        case breast_laterality::unknown:    return "";
    }
    return "";
}
References bilateral, left, right, and unknown.
to_string() [2/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (cad_processing_status status) noexcept
Convert CAD processing status to display string.
Parameters
status The CAD status
Returns
Human-readable string representation
Definition at line 235 of file mg_storage.cpp.
{
    switch (status) {
        case cad_processing_status::not_processed:
            return "NOT PROCESSED";
        case cad_processing_status::processed_no_findings:
            return "PROCESSED - NO FINDINGS";
        case cad_processing_status::processed_findings:
            return "PROCESSED - FINDINGS";
        case cad_processing_status::processing_failed:
            return "PROCESSING FAILED";
        case cad_processing_status::pending:
            return "PENDING";
    }
    return "";
}
References not_processed, pending, processed_findings, processed_no_findings, and processing_failed.
to_string() [3/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (dx_body_part part) noexcept
Convert body part enum to DICOM string.
Parameters
part The body part
Returns
DICOM-compliant string representation
Definition at line 172 of file dx_storage.cpp.
{
    switch (part) {
        case dx_body_part::chest:       return "CHEST";
        case dx_body_part::abdomen:     return "ABDOMEN";
        case dx_body_part::pelvis:      return "PELVIS";
        case dx_body_part::spine:       return "SPINE";
        case dx_body_part::skull:       return "SKULL";
        case dx_body_part::hand:        return "HAND";
        case dx_body_part::foot:        return "FOOT";
        case dx_body_part::knee:        return "KNEE";
        case dx_body_part::elbow:       return "ELBOW";
        case dx_body_part::shoulder:    return "SHOULDER";
        case dx_body_part::hip:         return "HIP";
        case dx_body_part::wrist:       return "WRIST";
        case dx_body_part::ankle:       return "ANKLE";
        case dx_body_part::extremity:   return "EXTREMITY";
        case dx_body_part::breast:      return "BREAST";
        case dx_body_part::other:       return "";
    }
    return "";
}
References abdomen, ankle, breast, chest, elbow, extremity, foot, hand, hip, knee, other, pelvis, shoulder, skull, spine, and wrist.
to_string() [4/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (dx_detector_type type) noexcept
Convert detector type enum to DICOM string.
Parameters
type The detector type
Returns
DICOM-compliant string representation
Definition at line 145 of file dx_storage.cpp.
{
    switch (type) {
        case dx_detector_type::direct:
            return "DIRECT";
        case dx_detector_type::indirect:
            return "INDIRECT";
        case dx_detector_type::storage:
            return "STORAGE";
        case dx_detector_type::film:
            return "FILM";
    }
    return "DIRECT";
}
References direct, film, indirect, and storage.
to_string() [5/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (dx_image_type type) noexcept
Convert DX image type to string.
Parameters
type The image type
Returns
String representation
Definition at line 96 of file dx_storage.cpp.
{
    switch (type) {
        case dx_image_type::for_presentation:
            return "FOR PRESENTATION";
        case dx_image_type::for_processing:
            return "FOR PROCESSING";
    }
    return "FOR PRESENTATION";
}
References for_presentation, and for_processing.
to_string() [6/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (dx_photometric_interpretation interp) noexcept
Convert photometric interpretation enum to DICOM string.
Parameters
interp The photometric interpretation
Returns
DICOM-compliant string representation
Definition at line 69 of file dx_storage.cpp.
{
    switch (interp) {
        case dx_photometric_interpretation::monochrome1:
            return "MONOCHROME1";
        case dx_photometric_interpretation::monochrome2:
            return "MONOCHROME2";
    }
    return "MONOCHROME2";
}
References monochrome1, and monochrome2.
to_string() [7/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (dx_view_position position) noexcept
Convert view position enum to DICOM string.
Parameters
position The view position
Returns
DICOM-compliant string representation
Definition at line 110 of file dx_storage.cpp.
{
    switch (position) {
        case dx_view_position::ap:
            return "AP";
        case dx_view_position::pa:
            return "PA";
        case dx_view_position::lateral:
            return "LATERAL";
        case dx_view_position::oblique:
            return "OBLIQUE";
        case dx_view_position::other:
            return "";
    }
    return "";
}
References ap, lateral, oblique, other, and pa.
to_string() [8/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (mg_image_type type) noexcept
Convert mammography image type to string.
Parameters
type The image type
Returns
String representation
Definition at line 223 of file mg_storage.cpp.
{
    switch (type) {
        case mg_image_type::for_presentation: return "FOR PRESENTATION";
        case mg_image_type::for_processing:   return "FOR PROCESSING";
    }
    return "";
}
References for_presentation, and for_processing.
to_string() [9/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (mg_view_position position) noexcept
Convert mammography view position enum to DICOM string.
Parameters
position The view position
Returns
DICOM-compliant string representation
Definition at line 95 of file mg_storage.cpp.
{
    switch (position) {
        case mg_view_position::cc:       return "CC";
        case mg_view_position::mlo:      return "MLO";
        case mg_view_position::ml:       return "ML";
        case mg_view_position::lm:       return "LM";
        case mg_view_position::xccl:     return "XCCL";
        case mg_view_position::xccm:     return "XCCM";
        case mg_view_position::fb:       return "FB";
        case mg_view_position::sio:      return "SIO";
        case mg_view_position::iso:      return "ISO";
        case mg_view_position::cv:       return "CV";
        case mg_view_position::at:       return "AT";
        case mg_view_position::spot:     return "SPOT";
        case mg_view_position::mag:      return "MAG";
        case mg_view_position::spot_mag: return "SPOT MAG";
        case mg_view_position::rl:       return "RL";
        case mg_view_position::rm:       return "RM";
        case mg_view_position::rs:       return "RS";
        case mg_view_position::ri:       return "RI";
        case mg_view_position::tangen:   return "TAN";
        case mg_view_position::implant:  return "ID";
        case mg_view_position::id:       return "ID";
        case mg_view_position::other:    return "";
    }
    return "";
}
References at, cc, cv, fb, id, implant, iso, lm, mag, ml, mlo, other, ri, rl, rm, rs, sio, spot, spot_mag, tangen, xccl, and xccm.
to_string() [10/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (nm_collimator_type collimator) noexcept
Convert collimator type to DICOM string.
Parameters
collimator The collimator type
Returns
DICOM code string
Definition at line 209 of file nm_storage.cpp.
{
    switch (collimator) {
        case nm_collimator_type::parallel:
            return "PARA";
        case nm_collimator_type::fan_beam:
            return "FANB";
        case nm_collimator_type::cone_beam:
            return "CONE";
        case nm_collimator_type::pinhole:
            return "PINH";
        case nm_collimator_type::diverging:
            return "DIVG";
        case nm_collimator_type::converging:
            return "CVGB";
        case nm_collimator_type::none:
            return "NONE";
    }
    return "PARA";
}
References cone_beam, converging, diverging, fan_beam, none, parallel, and pinhole.
to_string() [11/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (nm_photometric_interpretation interp) noexcept
Convert photometric interpretation enum to DICOM string.
Parameters
interp The photometric interpretation
Returns
DICOM-compliant string representation
Definition at line 67 of file nm_storage.cpp.
{
    switch (interp) {
        case nm_photometric_interpretation::monochrome2:
            return "MONOCHROME2";
        case nm_photometric_interpretation::palette_color:
            return "PALETTE COLOR";
    }
    return "MONOCHROME2";
}
References monochrome2, and palette_color.
to_string() [12/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (nm_radioisotope isotope) noexcept
Get radioisotope name string.
Parameters
isotope The radioisotope type
Returns
Human-readable name
Definition at line 258 of file nm_storage.cpp.
{
    switch (isotope) {
        case nm_radioisotope::tc99m:
            return "Tc-99m";
        case nm_radioisotope::i131:
            return "I-131";
        case nm_radioisotope::i123:
            return "I-123";
        case nm_radioisotope::tl201:
            return "Tl-201";
        case nm_radioisotope::ga67:
            return "Ga-67";
        case nm_radioisotope::in111:
            return "In-111";
        case nm_radioisotope::f18:
            return "F-18";
        case nm_radioisotope::other:
            return "Other";
    }
    return "Other";
}
References f18, ga67, i123, i131, in111, other, tc99m, and tl201.
to_string() [13/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (nm_type_of_data type) noexcept
Convert NM type of data to DICOM string.
Parameters
type The type of data
Returns
DICOM-compliant string representation
Definition at line 155 of file nm_storage.cpp.
{
    switch (type) {
        case nm_type_of_data::static_image:
            return "STATIC";
        case nm_type_of_data::dynamic:
            return "DYNAMIC";
        case nm_type_of_data::gated:
            return "GATED";
        case nm_type_of_data::whole_body:
            return "WHOLE BODY";
        case nm_type_of_data::recon_tomo:
            return "RECON TOMO";
        case nm_type_of_data::recon_gated_tomo:
            return "RECON GATED TOMO";
        case nm_type_of_data::tomo:
            return "TOMO";
        case nm_type_of_data::gated_tomo:
            return "GATED TOMO";
    }
    return "STATIC";
}
References dynamic, gated, gated_tomo, recon_gated_tomo, recon_tomo, static_image, tomo, and whole_body.
to_string() [14/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (nm_whole_body_technique technique) noexcept
Convert whole body technique to string.
Parameters
technique The whole body technique
Returns
DICOM code string
Definition at line 306 of file nm_storage.cpp.
{
    switch (technique) {
        case nm_whole_body_technique::single_pass:
            return "1PASS";
        case nm_whole_body_technique::multi_pass:
            return "2PASS";
        case nm_whole_body_technique::stepping:
            return "STEP";
    }
    return "1PASS";
}
References multi_pass, single_pass, and stepping.
to_string() [15/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (pet_photometric_interpretation interp) noexcept
Convert photometric interpretation enum to DICOM string.
Parameters
interp The photometric interpretation
Returns
DICOM-compliant string representation
Definition at line 67 of file pet_storage.cpp.
{
    switch (interp) {
        case pet_photometric_interpretation::monochrome2:
            return "MONOCHROME2";
    }
    return "MONOCHROME2";
}
References monochrome2.
to_string() [16/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (pet_radiotracer tracer) noexcept
Get radiotracer name string.
Parameters
tracer The radiotracer type
Returns
Human-readable name
Definition at line 254 of file pet_storage.cpp.
{
    switch (tracer) {
        case pet_radiotracer::fdg:
            return "18F-FDG";
        case pet_radiotracer::naf:
            return "18F-NaF";
        case pet_radiotracer::flt:
            return "18F-FLT";
        case pet_radiotracer::fdopa:
            return "18F-FDOPA";
        case pet_radiotracer::ammonia:
            return "13N-Ammonia";
        case pet_radiotracer::rubidium:
            return "82Rb";
        case pet_radiotracer::gallium_dotatate:
            return "68Ga-DOTATATE";
        case pet_radiotracer::psma:
            return "PSMA";
        case pet_radiotracer::other:
            return "Other";
    }
    return "Other";
}
References ammonia, fdg, fdopa, flt, gallium_dotatate, naf, other, psma, and rubidium.
to_string() [17/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (pet_reconstruction_type recon) noexcept
Convert PET reconstruction type to string.
Parameters
recon The reconstruction type
Returns
String representation
Definition at line 161 of file pet_storage.cpp.
{
    switch (recon) {
        case pet_reconstruction_type::fbp:
            return "FBP";
        case pet_reconstruction_type::osem:
            return "OSEM";
        case pet_reconstruction_type::mlem:
            return "MLEM";
        case pet_reconstruction_type::tof_osem:
            return "TOF-OSEM";
        case pet_reconstruction_type::psf_osem:
            return "PSF-OSEM";
        case pet_reconstruction_type::other:
            return "OTHER";
    }
    return "OTHER";
}
References fbp, mlem, osem, other, psf_osem, and tof_osem.
to_string() [18/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (pet_units units) noexcept
Convert PET units to DICOM string.
Parameters
units The units type
Returns
DICOM-compliant string representation
Definition at line 203 of file pet_storage.cpp.
{
    switch (units) {
        case pet_units::cnts:
            return "CNTS";
        case pet_units::bqml:
            return "BQML";
        case pet_units::gml:
            return "GML";
        case pet_units::suv_bw:
            return "SUV";
        case pet_units::suv_lbm:
            return "SUL";
        case pet_units::suv_bsa:
            return "SUV_BSA";
        case pet_units::percent_id_gram:
            return "%ID/G";
        case pet_units::other:
            return "OTHER";
    }
    return "OTHER";
}
References bqml, cnts, gml, other, percent_id_gram, suv_bsa, suv_bw, and suv_lbm.
to_string() [19/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (rt_beam_type type) noexcept
Convert RT beam type to DICOM string.
Parameters
type The beam type
Returns
DICOM-compliant string representation
Definition at line 522 of file rt_storage.cpp.
{
    switch (type) {
        case rt_beam_type::static_beam:
            return "STATIC";
        case rt_beam_type::dynamic:
            return "DYNAMIC";
    }
    return "STATIC";
}
References dynamic, and static_beam.
to_string() [20/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (rt_dose_summation_type type) noexcept
Convert RT dose summation type to DICOM string.
Parameters
type The dose summation type
Returns
DICOM-compliant string representation
Definition at line 286 of file rt_storage.cpp.
{
    switch (type) {
        case rt_dose_summation_type::plan:
            return "PLAN";
        case rt_dose_summation_type::multi_plan:
            return "MULTI_PLAN";
        case rt_dose_summation_type::fraction:
            return "FRACTION";
        case rt_dose_summation_type::beam:
            return "BEAM";
        case rt_dose_summation_type::brachy:
            return "BRACHY";
        case rt_dose_summation_type::fraction_session:
            return "FRACTION_SESSION";
        case rt_dose_summation_type::beam_session:
            return "BEAM_SESSION";
        case rt_dose_summation_type::brachy_session:
            return "BRACHY_SESSION";
        case rt_dose_summation_type::control_point:
            return "CONTROL_POINT";
        case rt_dose_summation_type::record:
            return "RECORD";
    }
    return "PLAN";
}
References beam, beam_session, brachy, brachy_session, control_point, fraction, fraction_session, multi_plan, plan, and record.
to_string() [21/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (rt_dose_type type) noexcept
Convert RT dose type to DICOM string.
Parameters
type The dose type
Returns
DICOM-compliant string representation
Definition at line 260 of file rt_storage.cpp.
{
    switch (type) {
        case rt_dose_type::physical:
            return "PHYSICAL";
        case rt_dose_type::effective:
            return "EFFECTIVE";
        case rt_dose_type::error:
            return "ERROR";
    }
    return "PHYSICAL";
}
References effective, error, and physical.
to_string() [22/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (rt_dose_units units) noexcept
Convert RT dose units to DICOM string.
Parameters
units The dose units
Returns
DICOM-compliant string representation
Definition at line 350 of file rt_storage.cpp.
{
    switch (units) {
        case rt_dose_units::gy:
            return "GY";
        case rt_dose_units::relative:
            return "RELATIVE";
    }
    return "GY";
}
References gy, and relative.
to_string() [23/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (rt_image_plane plane) noexcept
Convert RT image plane to DICOM string.
Parameters
plane The image plane type
Returns
DICOM-compliant string representation
Definition at line 622 of file rt_storage.cpp.
{
    switch (plane) {
        case rt_image_plane::axial:
            return "AXIAL";
        case rt_image_plane::localizer:
            return "LOCALIZER";
        case rt_image_plane::drr:
            return "DRR";
        case rt_image_plane::portal:
            return "PORTAL";
        case rt_image_plane::fluence:
            return "FLUENCE";
    }
    return "PORTAL";
}
References axial, drr, fluence, localizer, and portal.
to_string() [24/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (rt_plan_geometry geometry) noexcept
Convert RT plan geometry to DICOM string.
Parameters
geometry The plan geometry
Returns
DICOM-compliant string representation
Definition at line 239 of file rt_storage.cpp.
{
    switch (geometry) {
        case rt_plan_geometry::patient:
            return "PATIENT";
        case rt_plan_geometry::treatment_device:
            return "TREATMENT_DEVICE";
    }
    return "PATIENT";
}
References patient, and treatment_device.
to_string() [25/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (rt_plan_intent intent) noexcept
Convert RT plan intent to DICOM string.
Parameters
intent The plan intent
Returns
DICOM-compliant string representation
Definition at line 190 of file rt_storage.cpp.
{
    switch (intent) {
        case rt_plan_intent::curative:
            return "CURATIVE";
        case rt_plan_intent::palliative:
            return "PALLIATIVE";
        case rt_plan_intent::prophylactic:
            return "PROPHYLACTIC";
        case rt_plan_intent::verification:
            return "VERIFICATION";
        case rt_plan_intent::machine_qa:
            return "MACHINE_QA";
        case rt_plan_intent::research:
            return "RESEARCH";
        case rt_plan_intent::service:
            return "SERVICE";
    }
    return "CURATIVE";
}
References curative, machine_qa, palliative, prophylactic, research, service, and verification.
to_string() [26/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (rt_radiation_type type) noexcept
Convert RT radiation type to DICOM string.
Parameters
type The radiation type
Returns
DICOM-compliant string representation
Definition at line 543 of file rt_storage.cpp.
{
    switch (type) {
        case rt_radiation_type::photon:
            return "PHOTON";
        case rt_radiation_type::electron:
            return "ELECTRON";
        case rt_radiation_type::neutron:
            return "NEUTRON";
        case rt_radiation_type::proton:
            return "PROTON";
        case rt_radiation_type::ion:
            return "ION";
    }
    return "PHOTON";
}
References electron, ion, neutron, photon, and proton.
to_string() [27/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (rt_roi_generation_algorithm algorithm) noexcept
Convert RT ROI generation algorithm to DICOM string.
Parameters
algorithm The generation algorithm
Returns
DICOM-compliant string representation
Definition at line 495 of file rt_storage.cpp.
{
    switch (algorithm) {
        case rt_roi_generation_algorithm::automatic:
            return "AUTOMATIC";
        case rt_roi_generation_algorithm::semiautomatic:
            return "SEMIAUTOMATIC";
        case rt_roi_generation_algorithm::manual:
            return "MANUAL";
    }
    return "MANUAL";
}
References automatic, manual, and semiautomatic.
to_string() [28/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (rt_roi_interpreted_type type) noexcept
Convert RT ROI interpreted type to DICOM string.
Parameters
type The ROI interpreted type
Returns
DICOM-compliant string representation
Definition at line 371 of file rt_storage.cpp.
{
    switch (type) {
        case rt_roi_interpreted_type::external:
            return "EXTERNAL";
        case rt_roi_interpreted_type::ptv:
            return "PTV";
        case rt_roi_interpreted_type::ctv:
            return "CTV";
        case rt_roi_interpreted_type::gtv:
            return "GTV";
        case rt_roi_interpreted_type::organ:
            return "ORGAN";
        case rt_roi_interpreted_type::avoidance:
            return "AVOIDANCE";
        case rt_roi_interpreted_type::treated_volume:
            return "TREATED_VOLUME";
        case rt_roi_interpreted_type::irrad_volume:
            return "IRRAD_VOLUME";
        case rt_roi_interpreted_type::bolus:
            return "BOLUS";
        case rt_roi_interpreted_type::brachy_channel:
            return "BRACHY_CHANNEL";
        case rt_roi_interpreted_type::brachy_accessory:
            return "BRACHY_ACCESSORY";
        case rt_roi_interpreted_type::brachy_src_appl:
            return "BRACHY_SRC_APPL";
        case rt_roi_interpreted_type::brachy_chnl_shld:
            return "BRACHY_CHNL_SHLD";
        case rt_roi_interpreted_type::support:
            return "SUPPORT";
        case rt_roi_interpreted_type::fixation:
            return "FIXATION";
        case rt_roi_interpreted_type::dose_region:
            return "DOSE_REGION";
        case rt_roi_interpreted_type::contrast_agent:
            return "CONTRAST_AGENT";
        case rt_roi_interpreted_type::cavity:
            return "CAVITY";
        case rt_roi_interpreted_type::marker:
            return "MARKER";
        case rt_roi_interpreted_type::registration:
            return "REGISTRATION";
        case rt_roi_interpreted_type::isocenter:
            return "ISOCENTER";
        case rt_roi_interpreted_type::control_point:
            return "CONTROL";
    }
    return "ORGAN";
}
References avoidance, bolus, brachy_accessory, brachy_channel, brachy_chnl_shld, brachy_src_appl, cavity, contrast_agent, control_point, ctv, dose_region, external, fixation, gtv, irrad_volume, isocenter, marker, organ, ptv, registration, support, and treated_volume.
to_string() [29/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (rt_treatment_delivery_type type) noexcept
Convert RT treatment delivery type to DICOM string.
Parameters
type The treatment delivery type
Returns
DICOM-compliant string representation
Definition at line 582 of file rt_storage.cpp.
{
    switch (type) {
        case rt_treatment_delivery_type::treatment:
            return "TREATMENT";
        case rt_treatment_delivery_type::open_portfilm:
            return "OPEN_PORTFILM";
        case rt_treatment_delivery_type::trmt_portfilm:
            return "TRMT_PORTFILM";
        case rt_treatment_delivery_type::continuation:
            return "CONTINUATION";
        case rt_treatment_delivery_type::setup:
            return "SETUP";
    }
    return "TREATMENT";
}
References continuation, open_portfilm, setup, treatment, and trmt_portfilm.
to_string() [30/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (segment_algorithm_type type) noexcept
Convert segment algorithm type to DICOM string.
Parameters
type The segment algorithm type
Returns
DICOM-compliant string representation
Definition at line 115 of file seg_storage.cpp.
{
    switch (type) {
        case segment_algorithm_type::automatic:
            return "AUTOMATIC";
        case segment_algorithm_type::semiautomatic:
            return "SEMIAUTOMATIC";
        case segment_algorithm_type::manual:
            return "MANUAL";
    }
    return "MANUAL";
}
References automatic, manual, and semiautomatic.
to_string() [31/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (segmentation_fractional_type type) noexcept
Convert segmentation fractional type to DICOM string.
Parameters
type The segmentation fractional type
Returns
DICOM-compliant string representation
Definition at line 93 of file seg_storage.cpp.
{
    switch (type) {
        case segmentation_fractional_type::probability:
            return "PROBABILITY";
        case segmentation_fractional_type::occupancy:
            return "OCCUPANCY";
    }
    return "PROBABILITY";
}
References occupancy, and probability.
to_string() [32/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (segmentation_type type) noexcept
Convert segmentation type to DICOM string.
Parameters
type The segmentation type
Returns
DICOM-compliant string representation
Definition at line 68 of file seg_storage.cpp.
{
    switch (type) {
        case segmentation_type::binary:
            return "BINARY";
        case segmentation_type::fractional:
            return "FRACTIONAL";
    }
    return "BINARY";
}
References binary, and fractional.
to_string() [33/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (sr_completion_flag flag) noexcept
Convert SR completion flag to DICOM string.
Parameters
flag The completion flag
Returns
DICOM-compliant string representation
Definition at line 220 of file sr_storage.cpp.
{
    switch (flag) {
        case sr_completion_flag::partial:
            return "PARTIAL";
        case sr_completion_flag::complete:
            return "COMPLETE";
    }
    return "PARTIAL";
}
References complete, and partial.
to_string() [34/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (sr_document_type type) noexcept
Get human-readable name for SR document type.
Parameters
type The SR document type
Returns
Human-readable type name
Definition at line 94 of file sr_storage.cpp.
{
    switch (type) {
        case sr_document_type::basic_text:
            return "Basic Text SR";
        case sr_document_type::enhanced:
            return "Enhanced SR";
        case sr_document_type::comprehensive:
            return "Comprehensive SR";
        case sr_document_type::comprehensive_3d:
            return "Comprehensive 3D SR";
        case sr_document_type::extensible:
            return "Extensible SR";
        case sr_document_type::key_object_selection:
            return "Key Object Selection";
        case sr_document_type::cad:
            return "CAD SR";
        case sr_document_type::dose_report:
            return "Dose Report SR";
        case sr_document_type::procedure_log:
            return "Procedure Log SR";
        case sr_document_type::other:
            return "Other SR";
    }
    return "Unknown SR";
}
References basic_text, cad, comprehensive, comprehensive_3d, dose_report, enhanced, extensible, key_object_selection, other, and procedure_log.
to_string() [35/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (sr_relationship_type type) noexcept
Convert SR relationship type to DICOM string.
Parameters
type The SR relationship type
Returns
DICOM-compliant string representation
Definition at line 183 of file sr_storage.cpp.
{
    switch (type) {
        case sr_relationship_type::contains:
            return "CONTAINS";
        case sr_relationship_type::has_obs_context:
            return "HAS OBS CONTEXT";
        case sr_relationship_type::has_acq_context:
            return "HAS ACQ CONTEXT";
        case sr_relationship_type::has_concept_mod:
            return "HAS CONCEPT MOD";
        case sr_relationship_type::has_properties:
            return "HAS PROPERTIES";
        case sr_relationship_type::inferred_from:
            return "INFERRED FROM";
        case sr_relationship_type::selected_from:
            return "SELECTED FROM";
        case sr_relationship_type::unknown:
            return "UNKNOWN";
    }
    return "UNKNOWN";
}
References contains, has_acq_context, has_concept_mod, has_obs_context, has_properties, inferred_from, selected_from, and unknown.
to_string() [36/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (sr_value_type type) noexcept
Convert SR value type to DICOM string.
Parameters
type The SR value type
Returns
DICOM-compliant string representation
Definition at line 147 of file sr_storage.cpp.
{
    auto index = static_cast<size_t>(type);
    if (index < std::size(value_type_strings)) {
        return value_type_strings[index];
    }
    return "UNKNOWN";
}
to_string() [37/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (sr_verification_flag flag) noexcept
Convert SR verification flag to DICOM string.
Parameters
flag The verification flag
Returns
DICOM-compliant string representation
Definition at line 237 of file sr_storage.cpp.
{
    switch (flag) {
        case sr_verification_flag::unverified:
            return "UNVERIFIED";
        case sr_verification_flag::verified:
            return "VERIFIED";
    }
    return "UNVERIFIED";
}
References unverified, and verified.
to_string() [38/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (us_photometric_interpretation interp) noexcept
Convert photometric interpretation enum to DICOM string.
Parameters
interp The photometric interpretation
Returns
DICOM-compliant string representation
Definition at line 84 of file us_storage.cpp.
{
    auto index = static_cast<size_t>(interp);
    if (index < std::size(photometric_strings)) {
        return photometric_strings[index];
    }
    return "MONOCHROME2";
}
to_string() [39/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (waveform_type type) noexcept
Get human-readable name for waveform type.
Parameters
type The waveform type
Returns
Human-readable type name
Definition at line 80 of file waveform_storage.cpp.
{
    switch (type) {
        case waveform_type::ecg_12lead: return "12-Lead ECG";
        case waveform_type::ecg_general: return "General ECG";
        case waveform_type::ecg_ambulatory: return "Ambulatory ECG";
        case waveform_type::hemodynamic: return "Hemodynamic";
        case waveform_type::cardiac_ep: return "Cardiac Electrophysiology";
        case waveform_type::audio_basic: return "Basic Voice Audio";
        case waveform_type::audio_general: return "General Audio";
        case waveform_type::arterial_pulse: return "Arterial Pulse";
        case waveform_type::respiratory: return "Respiratory";
        case waveform_type::respiratory_multi: return "Multi-channel Respiratory";
        case waveform_type::eeg_routine: return "Routine Scalp EEG";
        case waveform_type::emg: return "Electromyogram";
        case waveform_type::eog: return "Electrooculogram";
        case waveform_type::eeg_sleep: return "Sleep EEG";
        case waveform_type::body_position: return "Body Position";
        case waveform_type::presentation_state: return "Waveform Presentation State";
        case waveform_type::annotation: return "Waveform Annotation";
        case waveform_type::unknown: return "Unknown";
    }
    return "Unknown";
}
References annotation, arterial_pulse, audio_basic, audio_general, body_position, cardiac_ep, ecg_12lead, ecg_ambulatory, ecg_general, eeg_routine, eeg_sleep, emg, eog, hemodynamic, presentation_state, respiratory, respiratory_multi, and unknown.
to_string() [40/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (xa_photometric_interpretation interp) noexcept
Convert photometric interpretation enum to DICOM string.
Parameters
interp The photometric interpretation
Returns
DICOM-compliant string representation
Definition at line 66 of file xa_storage.cpp.
{
    switch (interp) {
        case xa_photometric_interpretation::monochrome1:
            return "MONOCHROME1";
        case xa_photometric_interpretation::monochrome2:
            return "MONOCHROME2";
    }
    return "MONOCHROME2";
}
References monochrome1, and monochrome2.
to_string() [41/41]
std::string_view kcenon::pacs::services::sop_classes::to_string (xa_positioner_motion motion) noexcept
Convert positioner motion enum to DICOM string.
Parameters
motion The positioner motion type
Returns
DICOM-compliant string representation
Definition at line 191 of file xa_storage.cpp.
{
    switch (motion) {
        case xa_positioner_motion::stationary:
            return "STATIONARY";
        case xa_positioner_motion::dynamic:
            return "DYNAMIC";
    }
    return "STATIONARY";
}
References dynamic, and stationary.
Variable Documentation
acquisition_context_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::acquisition_context_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.71"
Acquisition Context SR Storage SOP Class UID.
Definition at line 108 of file sr_storage.hpp.
ambulatory_ecg_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::ambulatory_ecg_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.1.3"
Ambulatory ECG Waveform Storage SOP Class UID.
Definition at line 70 of file waveform_storage.hpp.
Referenced by get_waveform_type().
arterial_pulse_waveform_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::arterial_pulse_waveform_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.5.1"
Arterial Pulse Waveform Storage SOP Class UID.
Definition at line 90 of file waveform_storage.hpp.
Referenced by get_waveform_type().
basic_text_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::basic_text_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.11"
Basic Text SR Storage SOP Class UID.
Definition at line 63 of file sr_storage.hpp.
Referenced by get_recommended_sr_template(), get_sr_document_type(), and kcenon::pacs::services::sop_class_registry::register_sr_sop_classes().
basic_voice_audio_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::basic_voice_audio_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.4.1"
Basic Voice Audio Waveform Storage SOP Class UID.
Definition at line 82 of file waveform_storage.hpp.
Referenced by get_waveform_type().
body_position_waveform_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::body_position_waveform_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.8.1"
Body Position Waveform Storage SOP Class UID.
Definition at line 118 of file waveform_storage.hpp.
Referenced by get_waveform_type().
breast_projection_image_storage_for_presentation_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::breast_projection_image_storage_for_presentation_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.13.1.4"
Breast Projection X-Ray Image Storage - For Presentation SOP Class UID.
Definition at line 83 of file mg_storage.hpp.
breast_projection_image_storage_for_processing_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::breast_projection_image_storage_for_processing_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.13.1.5"
Breast Projection X-Ray Image Storage - For Processing SOP Class UID.
Definition at line 87 of file mg_storage.hpp.
breast_tomosynthesis_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::breast_tomosynthesis_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.13.1.3"
Breast Tomosynthesis Image Storage SOP Class UID.
Definition at line 79 of file mg_storage.hpp.
cardiac_ep_waveform_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::cardiac_ep_waveform_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.3.1"
Basic Cardiac Electrophysiology Waveform Storage SOP Class UID.
Definition at line 78 of file waveform_storage.hpp.
Referenced by get_waveform_type().
chest_cad_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::chest_cad_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.65"
Chest CAD SR Storage SOP Class UID.
Definition at line 92 of file sr_storage.hpp.
Referenced by get_recommended_sr_template(), get_sr_document_type(), and kcenon::pacs::services::sop_class_registry::register_sr_sop_classes().
colon_cad_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::colon_cad_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.69"
Colon CAD SR Storage SOP Class UID.
Definition at line 96 of file sr_storage.hpp.
Referenced by get_recommended_sr_template(), get_sr_document_type(), and kcenon::pacs::services::sop_class_registry::register_sr_sop_classes().
comprehensive_3d_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::comprehensive_3d_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.34"
Comprehensive 3D SR Storage SOP Class UID.
Definition at line 75 of file sr_storage.hpp.
Referenced by get_sr_document_type(), and kcenon::pacs::services::sop_class_registry::register_sr_sop_classes().
comprehensive_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::comprehensive_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.33"
Comprehensive SR Storage SOP Class UID.
Definition at line 71 of file sr_storage.hpp.
Referenced by get_recommended_sr_template(), get_sr_document_type(), and kcenon::pacs::services::sop_class_registry::register_sr_sop_classes().
ct_for_processing_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::ct_for_processing_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.2.2"
CT For Processing Image Storage SOP Class UID Multi-energy/spectral CT basis material decomposition images.
Definition at line 69 of file ct_storage.hpp.
Referenced by get_ct_storage_sop_classes(), is_ct_storage_sop_class(), kcenon::pacs::services::validation::ct_processing_iod_validator::quick_check(), and kcenon::pacs::services::validation::ct_processing_iod_validator::validate_sop_common_module().
ct_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::ct_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.2"
CT Image Storage SOP Class UID.
Definition at line 60 of file ct_storage.hpp.
Referenced by get_ct_storage_sop_classes(), and is_ct_storage_sop_class().
dx_image_storage_for_presentation_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::dx_image_storage_for_presentation_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.1.1"
Digital X-Ray Image Storage - For Presentation SOP Class UID Used for images ready for display and clinical review.
Definition at line 69 of file dx_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_dx_sop_classes().
dx_image_storage_for_processing_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::dx_image_storage_for_processing_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.1.1.1"
Digital X-Ray Image Storage - For Processing SOP Class UID Used for raw detector data requiring additional processing.
Definition at line 74 of file dx_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_dx_sop_classes().
emg_waveform_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::emg_waveform_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.7.2"
Electromyogram Waveform Storage SOP Class UID.
Definition at line 106 of file waveform_storage.hpp.
Referenced by get_waveform_type().
enhanced_ct_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::enhanced_ct_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.2.1"
Enhanced CT Image Storage SOP Class UID.
Definition at line 64 of file ct_storage.hpp.
Referenced by get_ct_storage_sop_classes(), and is_ct_storage_sop_class().
enhanced_mr_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::enhanced_mr_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.4.1"
Enhanced MR Image Storage SOP Class UID.
Definition at line 63 of file mr_storage.hpp.
Referenced by get_mr_storage_sop_classes(), and is_mr_storage_sop_class().
enhanced_pet_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::enhanced_pet_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.130"
Enhanced PET Image Storage SOP Class UID.
Definition at line 66 of file pet_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_pet_sop_classes().
enhanced_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::enhanced_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.22"
Enhanced SR Storage SOP Class UID.
Definition at line 67 of file sr_storage.hpp.
Referenced by get_recommended_sr_template(), get_sr_document_type(), and kcenon::pacs::services::sop_class_registry::register_sr_sop_classes().
enhanced_xa_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::enhanced_xa_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.12.1.1"
Enhanced XA Image Storage SOP Class UID (enhanced IOD)
Definition at line 76 of file xa_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_xa_sop_classes().
enhanced_xray_radiation_dose_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::enhanced_xray_radiation_dose_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.76"
Enhanced X-Ray Radiation Dose SR Storage SOP Class UID.
Definition at line 128 of file sr_storage.hpp.
Referenced by get_recommended_sr_template(), and get_sr_document_type().
eog_waveform_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::eog_waveform_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.7.3"
Electrooculogram Waveform Storage SOP Class UID.
Definition at line 110 of file waveform_storage.hpp.
Referenced by get_waveform_type().
extensible_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::extensible_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.35"
Extensible SR Storage SOP Class UID.
Definition at line 79 of file sr_storage.hpp.
Referenced by get_sr_document_type(), and kcenon::pacs::services::sop_class_registry::register_sr_sop_classes().
general_audio_waveform_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::general_audio_waveform_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.4.2"
General Audio Waveform Storage SOP Class UID.
Definition at line 86 of file waveform_storage.hpp.
Referenced by get_waveform_type().
general_ecg_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::general_ecg_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.1.2"
General ECG Waveform Storage SOP Class UID.
Definition at line 66 of file waveform_storage.hpp.
Referenced by get_waveform_type().
heightmap_segmentation_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::heightmap_segmentation_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.66.7"
Heightmap Segmentation Storage SOP Class UID (Supplement 240)
Definition at line 71 of file seg_storage.hpp.
Referenced by kcenon::pacs::services::validation::heightmap_seg_iod_validator::quick_check(), kcenon::pacs::services::sop_class_registry::register_seg_sop_classes(), and kcenon::pacs::services::validation::heightmap_seg_iod_validator::validate_sop_common_module().
hemodynamic_waveform_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::hemodynamic_waveform_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.2.1"
Hemodynamic Waveform Storage SOP Class UID.
Definition at line 74 of file waveform_storage.hpp.
Referenced by get_waveform_type().
intraoral_image_storage_for_presentation_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::intraoral_image_storage_for_presentation_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.1.3"
Digital Intra-Oral X-Ray Image Storage - For Presentation.
Definition at line 96 of file dx_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_dx_sop_classes().
intraoral_image_storage_for_processing_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::intraoral_image_storage_for_processing_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.1.3.1"
Digital Intra-Oral X-Ray Image Storage - For Processing.
Definition at line 100 of file dx_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_dx_sop_classes().
key_object_selection_document_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::key_object_selection_document_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.59"
Key Object Selection Document Storage SOP Class UID.
Definition at line 137 of file sr_storage.hpp.
Referenced by kcenon::pacs::services::xds::imaging_document_source::build_document_entry(), kcenon::pacs::services::xds::imaging_document_source::create_kos_document(), get_recommended_sr_template(), get_sr_document_type(), and kcenon::pacs::services::sop_class_registry::register_sr_sop_classes().
label_map_segmentation_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::label_map_segmentation_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.66.8"
Label Map Segmentation Storage SOP Class UID (Supplement 243)
Definition at line 75 of file seg_storage.hpp.
Referenced by kcenon::pacs::services::validation::label_map_seg_iod_validator::quick_check(), kcenon::pacs::services::sop_class_registry::register_seg_sop_classes(), and kcenon::pacs::services::validation::label_map_seg_iod_validator::validate_sop_common_module().
legacy_converted_enhanced_pet_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::legacy_converted_enhanced_pet_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.128.1"
Legacy Converted Enhanced PET Image Storage SOP Class UID.
Definition at line 70 of file pet_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_pet_sop_classes().
mammography_cad_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::mammography_cad_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.50"
Mammography CAD SR Storage SOP Class UID.
Definition at line 88 of file sr_storage.hpp.
Referenced by get_recommended_sr_template(), get_sr_document_type(), and kcenon::pacs::services::sop_class_registry::register_sr_sop_classes().
mammography_image_storage_for_presentation_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::mammography_image_storage_for_presentation_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.1.2"
Digital Mammography X-Ray Image Storage - For Presentation.
Definition at line 83 of file dx_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_dx_sop_classes().
mammography_image_storage_for_processing_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::mammography_image_storage_for_processing_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.1.2.1"
Digital Mammography X-Ray Image Storage - For Processing.
Definition at line 87 of file dx_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_dx_sop_classes().
mg_image_storage_for_presentation_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::mg_image_storage_for_presentation_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.1.2"
Digital Mammography X-Ray Image Storage - For Presentation SOP Class UID.
Definition at line 71 of file mg_storage.hpp.
mg_image_storage_for_processing_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::mg_image_storage_for_processing_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.1.2.1"
Digital Mammography X-Ray Image Storage - For Processing SOP Class UID.
Definition at line 75 of file mg_storage.hpp.
mr_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::mr_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.4"
MR Image Storage SOP Class UID.
Definition at line 59 of file mr_storage.hpp.
Referenced by get_mr_storage_sop_classes(), and is_mr_storage_sop_class().
multichannel_respiratory_waveform_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::multichannel_respiratory_waveform_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.6.2"
Multi-channel Respiratory Waveform Storage SOP Class UID.
Definition at line 98 of file waveform_storage.hpp.
Referenced by get_waveform_type().
nm_image_storage_retired_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::nm_image_storage_retired_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.5"
Nuclear Medicine Image Storage (Retired) - for legacy systems.
Definition at line 71 of file nm_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_nm_sop_classes().
nm_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::nm_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.20"
Nuclear Medicine Image Storage SOP Class UID.
Definition at line 62 of file nm_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_nm_sop_classes().
ophthalmic_oct_bscan_analysis_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::ophthalmic_oct_bscan_analysis_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.77.1.5.8"
Ophthalmic Optical Coherence Tomography B-scan Volume Analysis Storage.
Definition at line 75 of file ophthalmic_storage.hpp.
Referenced by get_ophthalmic_storage_sop_classes(), is_ophthalmic_storage_sop_class(), kcenon::pacs::services::sop_class_registry::register_ophthalmic_sop_classes(), and kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_multiframe_module().
ophthalmic_photo_16bit_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::ophthalmic_photo_16bit_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.77.1.5.2"
Ophthalmic Photography 16 Bit Image Storage.
Definition at line 63 of file ophthalmic_storage.hpp.
Referenced by get_ophthalmic_storage_sop_classes(), is_ophthalmic_storage_sop_class(), and kcenon::pacs::services::sop_class_registry::register_ophthalmic_sop_classes().
ophthalmic_photo_8bit_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::ophthalmic_photo_8bit_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.77.1.5.1"
Ophthalmic Photography 8 Bit Image Storage.
Definition at line 59 of file ophthalmic_storage.hpp.
Referenced by get_ophthalmic_storage_sop_classes(), is_ophthalmic_storage_sop_class(), and kcenon::pacs::services::sop_class_registry::register_ophthalmic_sop_classes().
ophthalmic_tomography_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::ophthalmic_tomography_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.77.1.5.4"
Ophthalmic Tomography Image Storage (OCT)
Definition at line 67 of file ophthalmic_storage.hpp.
Referenced by get_ophthalmic_storage_sop_classes(), is_ophthalmic_storage_sop_class(), kcenon::pacs::services::sop_class_registry::register_ophthalmic_sop_classes(), and kcenon::pacs::services::validation::ophthalmic_iod_validator::validate_multiframe_module().
parametric_map_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::parametric_map_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.30"
Parametric Map Storage SOP Class UID.
Definition at line 60 of file parametric_map_storage.hpp.
Referenced by get_parametric_map_sop_class_info(), get_parametric_map_storage_sop_classes(), is_parametric_map_storage_sop_class(), and kcenon::pacs::services::sop_class_registry::register_parametric_map_sop_classes().
patient_radiation_dose_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::patient_radiation_dose_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.73"
Patient Radiation Dose SR Storage SOP Class UID.
Definition at line 116 of file sr_storage.hpp.
Referenced by get_sr_document_type().
performed_imaging_agent_admin_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::performed_imaging_agent_admin_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.75"
Performed Imaging Agent Administration SR Storage SOP Class UID.
Definition at line 124 of file sr_storage.hpp.
pet_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::pet_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.128"
PET Image Storage SOP Class UID.
Definition at line 62 of file pet_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_pet_sop_classes().
planned_imaging_agent_admin_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::planned_imaging_agent_admin_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.74"
Planned Imaging Agent Administration SR Storage SOP Class UID.
Definition at line 120 of file sr_storage.hpp.
radiopharmaceutical_radiation_dose_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::radiopharmaceutical_radiation_dose_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.68"
Radiopharmaceutical Radiation Dose SR Storage SOP Class UID.
Definition at line 104 of file sr_storage.hpp.
Referenced by get_sr_document_type().
respiratory_waveform_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::respiratory_waveform_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.6.1"
Respiratory Waveform Storage SOP Class UID.
Definition at line 94 of file waveform_storage.hpp.
Referenced by get_waveform_type().
routine_scalp_eeg_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::routine_scalp_eeg_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.7.1"
Routine Scalp Electroencephalogram Waveform Storage SOP Class UID.
Definition at line 102 of file waveform_storage.hpp.
Referenced by get_waveform_type().
rt_beams_treatment_record_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::rt_beams_treatment_record_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.481.4"
RT Beams Treatment Record Storage SOP Class UID.
Definition at line 79 of file rt_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_rt_sop_classes().
rt_brachy_treatment_record_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::rt_brachy_treatment_record_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.481.6"
RT Brachy Treatment Record Storage SOP Class UID.
Definition at line 83 of file rt_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_rt_sop_classes().
rt_dose_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::rt_dose_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.481.2"
RT Dose Storage SOP Class UID.
Definition at line 67 of file rt_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_rt_sop_classes(), kcenon::pacs::services::validation::rt_iod_validator::validate(), and kcenon::pacs::services::validation::rt_dose_iod_validator::validate_sop_common_module().
rt_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::rt_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.481.1"
RT Image Storage SOP Class UID.
Definition at line 75 of file rt_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_rt_sop_classes().
rt_ion_beams_treatment_record_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::rt_ion_beams_treatment_record_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.481.9"
RT Ion Beams Treatment Record Storage SOP Class UID.
Definition at line 95 of file rt_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_rt_sop_classes().
rt_ion_plan_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::rt_ion_plan_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.481.8"
RT Ion Plan Storage SOP Class UID.
Definition at line 91 of file rt_storage.hpp.
Referenced by is_rt_plan_sop_class(), kcenon::pacs::services::sop_class_registry::register_rt_sop_classes(), and kcenon::pacs::services::validation::rt_iod_validator::validate().
rt_plan_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::rt_plan_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.481.5"
RT Plan Storage SOP Class UID.
Definition at line 63 of file rt_storage.hpp.
Referenced by is_rt_plan_sop_class(), kcenon::pacs::services::sop_class_registry::register_rt_sop_classes(), and kcenon::pacs::services::validation::rt_iod_validator::validate().
rt_structure_set_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::rt_structure_set_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.481.3"
RT Structure Set Storage SOP Class UID.
Definition at line 71 of file rt_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_rt_sop_classes(), kcenon::pacs::services::validation::rt_iod_validator::validate(), and kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate_sop_common_module().
rt_treatment_summary_record_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::rt_treatment_summary_record_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.481.7"
RT Treatment Summary Record Storage SOP Class UID.
Definition at line 87 of file rt_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_rt_sop_classes().
segmentation_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::segmentation_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.66.4"
Segmentation Storage SOP Class UID.
Definition at line 63 of file seg_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_seg_sop_classes().
simplified_adult_echo_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::simplified_adult_echo_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.72"
Simplified Adult Echo SR Storage SOP Class UID.
Definition at line 112 of file sr_storage.hpp.
sleep_eeg_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::sleep_eeg_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.7.4"
Sleep Electroencephalogram Waveform Storage SOP Class UID.
Definition at line 114 of file waveform_storage.hpp.
Referenced by get_waveform_type().
surface_segmentation_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::surface_segmentation_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.66.5"
Surface Segmentation Storage SOP Class UID.
Definition at line 67 of file seg_storage.hpp.
Referenced by is_surface_segmentation_sop_class(), and kcenon::pacs::services::sop_class_registry::register_seg_sop_classes().
twelve_lead_ecg_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::twelve_lead_ecg_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.9.1.1"
12-lead ECG Waveform Storage SOP Class UID
Definition at line 62 of file waveform_storage.hpp.
Referenced by get_waveform_type().
us_image_storage_retired_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::us_image_storage_retired_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.6"
US Image Storage (Retired) - for legacy systems.
Definition at line 77 of file us_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_us_sop_classes().
us_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::us_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.6.1"
US Image Storage SOP Class UID (single-frame)
Definition at line 64 of file us_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_us_sop_classes().
us_multiframe_image_storage_retired_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::us_multiframe_image_storage_retired_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.3.1"
US Multi-frame Image Storage (Retired) - for legacy systems.
Definition at line 81 of file us_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_us_sop_classes().
us_multiframe_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::us_multiframe_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.6.2"
US Multi-frame Image Storage SOP Class UID (cine loops)
Definition at line 68 of file us_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_us_sop_classes().
waveform_annotation_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::waveform_annotation_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.11.12"
Waveform Annotation Storage SOP Class UID.
Definition at line 131 of file waveform_storage.hpp.
Referenced by get_waveform_type(), and is_waveform_annotation_sop_class().
waveform_presentation_state_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::waveform_presentation_state_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.11.11"
Waveform Presentation State Storage SOP Class UID.
Definition at line 127 of file waveform_storage.hpp.
Referenced by get_waveform_type(), and is_waveform_presentation_state_sop_class().
wide_field_ophthalmic_photo_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::wide_field_ophthalmic_photo_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.77.1.5.7"
Wide Field Ophthalmic Photography SOP Class Storage.
Definition at line 71 of file ophthalmic_storage.hpp.
Referenced by get_ophthalmic_storage_sop_classes(), is_ophthalmic_storage_sop_class(), and kcenon::pacs::services::sop_class_registry::register_ophthalmic_sop_classes().
wsi_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::wsi_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.77.1.6"
VL Whole Slide Microscopy Image Storage SOP Class UID.
Definition at line 60 of file wsi_storage.hpp.
Referenced by get_wsi_storage_sop_classes(), is_wsi_storage_sop_class(), and kcenon::pacs::services::sop_class_registry::register_wsi_sop_classes().
xa_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::xa_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.12.1"
XA Image Storage SOP Class UID (single/multi-frame)
Definition at line 72 of file xa_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_xa_sop_classes().
xray_3d_angiographic_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::xray_3d_angiographic_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.13.1.1"
X-Ray 3D Angiographic Image Storage SOP Class UID (3D rotational)
Definition at line 89 of file xa_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_xa_sop_classes().
xray_3d_craniofacial_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::xray_3d_craniofacial_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.13.1.2"
X-Ray 3D Craniofacial Image Storage SOP Class UID.
Definition at line 93 of file xa_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_xa_sop_classes().
xray_radiation_dose_sr_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::xray_radiation_dose_sr_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.88.67"
X-Ray Radiation Dose SR Storage SOP Class UID.
Definition at line 100 of file sr_storage.hpp.
Referenced by get_recommended_sr_template(), get_sr_document_type(), and kcenon::pacs::services::sop_class_registry::register_sr_sop_classes().
xrf_image_storage_uid
constexpr std::string_view kcenon::pacs::services::sop_classes::xrf_image_storage_uid inline constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.12.2"
XRF Image Storage SOP Class UID (X-Ray Radiofluoroscopic)
Definition at line 80 of file xa_storage.hpp.
Referenced by kcenon::pacs::services::sop_class_registry::register_xa_sop_classes().