PACS System: kcenon::pacs::storage Namespace Reference
kcenon::pacs::storage Namespace Reference
Classes
struct annotation_query
struct annotation_record
Annotation record from the database.
class annotation_repository
Repository for annotation persistence (legacy SQLite interface)
struct annotation_style
Style information for annotations.
struct audit_query
Query parameters for audit log search.
struct audit_record
Audit log record from the database.
class audit_repository
struct azure_blob_info
Information about an Azure Blob object.
class azure_blob_storage
struct azure_storage_config
Configuration for Azure Blob storage.
struct cloud_storage_config
Configuration for S3-compatible cloud storage.
class file_storage
struct file_storage_config
Configuration for file_storage.
class hsm_migration_service
struct hsm_statistics
Combined statistics for all HSM tiers.
class hsm_storage
struct hsm_storage_config
Configuration for HSM storage.
struct index_config
Configuration for index database.
class index_database
struct instance_query
struct instance_record
Instance record from the database.
class instance_repository
Repository for instance metadata persistence (legacy SQLite interface)
struct job_query_options
Query options for listing jobs.
class job_repository
Repository for job persistence (legacy SQLite interface)
struct key_image_query
struct key_image_record
Key image record from the database.
class key_image_repository
Repository for key image persistence (legacy SQLite interface)
struct measurement_query
struct measurement_record
Measurement record from the database.
class measurement_repository
Repository for measurement persistence (legacy SQLite interface)
struct migration_record
Represents a record of an applied database migration.
struct migration_result
Result of a migration operation.
class migration_runner
struct migration_service_config
Configuration for the migration service.
class mock_azure_client
Mock Azure Blob client for testing without Azure SDK dependency.
class mock_s3_client
Mock S3 client for testing without AWS SDK dependency.
struct mpps_query
struct mpps_record
MPPS record from the database.
class mpps_repository
class node_repository
Repository for remote node persistence (legacy SQLite interface)
struct patient_query
struct patient_record
Patient record from the database.
class patient_repository
Repository for patient metadata persistence (legacy SQLite interface)
struct performed_series_info
Information about a performed series.
struct prefetch_history_query_options
Query options for listing prefetch history.
class prefetch_repository
Repository for prefetch persistence (legacy SQLite interface)
struct prefetch_rule_query_options
Query options for listing prefetch rules.
struct recent_study_record
Recent study access record from the database.
class routing_repository
Repository for routing rule persistence (legacy SQLite interface)
struct routing_rule_query_options
Query options for listing routing rules.
struct s3_object_info
Information about an S3 object.
class s3_storage
struct series_query
struct series_record
Series record from the database.
class series_repository
Repository for series metadata persistence (legacy SQLite interface)
class storage_interface
struct storage_statistics
Storage statistics structure.
struct study_query
struct study_record
Study record from the database.
class study_repository
Repository for study metadata persistence (legacy SQLite interface)
class sync_repository
Repository for sync persistence (legacy SQLite interface)
struct tier_metadata
Metadata for tracking instance tier location.
struct tier_policy
struct tier_statistics
Statistics for a single storage tier.
class ups_repository
struct ups_subscription
UPS subscription record from the database.
struct ups_workitem
UPS workitem record from the database.
struct ups_workitem_query
struct viewer_state_query
struct viewer_state_record
Viewer state record from the database.
class viewer_state_repository
Repository for viewer state persistence (legacy SQLite interface)
struct worklist_item
Worklist item record from the database.
struct worklist_query
class worklist_repository
Typedefs
template<typename T >
using Result = kcenon::common::Result<T>
Result type alias for operations returning a value.
using azure_progress_callback
Callback type for upload/download progress tracking.
using migration_function = std::function<VoidResult(sqlite3* db)>
Function type for migration implementations (SQLite)
using progress_callback
Callback type for upload/download progress tracking.
Enumerations
enum class annotation_type {
arrow , line , rectangle , ellipse ,
polygon , freehand , text , angle ,
roi
}
Annotation types supported by the system.
enum class audit_event_type {
association_established , association_released , c_store , c_find ,
c_move , c_get , security_event , configuration_change ,
system_startup , system_shutdown , user_login , user_logout ,
data_access , data_export , error
}
Audit event type enumeration.
enum class audit_outcome { success , failure , warning }
Audit log outcome/status.
enum class naming_scheme { uid_hierarchical , date_hierarchical , flat }
Naming scheme for DICOM file organization.
enum class duplicate_policy { reject , replace , ignore }
Policy for handling duplicate SOP Instance UIDs.
enum class storage_tier { hot , warm , cold }
Storage tier classification.
enum class measurement_type {
length , area , angle , hounsfield ,
suv , ellipse_area , polygon_area
}
Measurement types supported by the system.
enum class mpps_status { in_progress , completed , discontinued }
MPPS status values.
enum class ups_state { scheduled , in_progress , completed , canceled }
UPS workitem state values.
enum class ups_priority { low , medium , high }
UPS workitem priority values.
enum class worklist_status { scheduled , started , completed }
Worklist step status values.
Functions
auto to_string (annotation_type type) -> std::string
Convert annotation_type to string.
auto annotation_type_from_string (std::string_view str) -> std::optional< annotation_type >
Parse string to annotation_type.
auto to_string (audit_event_type type) -> std::string
Convert audit_event_type enum to string representation.
auto parse_audit_event_type (std::string_view str) -> std::optional< audit_event_type >
Parse string to audit_event_type enum.
auto to_string (audit_outcome outcome) -> std::string
Convert audit_outcome enum to string.
constexpr auto to_string (storage_tier tier) noexcept -> std::string_view
Convert storage_tier to string representation.
constexpr auto storage_tier_from_string (std::string_view str) -> std::optional< storage_tier >
Parse storage_tier from string.
auto to_string (measurement_type type) -> std::string
Convert measurement_type to string.
auto measurement_type_from_string (std::string_view str) -> std::optional< measurement_type >
Parse string to measurement_type.
auto to_string (mpps_status status) -> std::string
Convert mpps_status enum to string representation.
auto parse_mpps_status (std::string_view str) -> std::optional< mpps_status >
Parse string to mpps_status enum.
auto to_string (ups_state state) -> std::string
Convert ups_state enum to string representation.
auto parse_ups_state (std::string_view str) -> std::optional< ups_state >
Parse string to ups_state enum.
auto to_string (ups_priority priority) -> std::string
Convert ups_priority enum to string representation.
auto parse_ups_priority (std::string_view str) -> std::optional< ups_priority >
Parse string to ups_priority enum.
auto to_string (worklist_status status) -> std::string
Convert worklist_status enum to string representation.
auto parse_worklist_status (std::string_view str) -> std::optional< worklist_status >
Parse string to worklist_status enum.
Typedef Documentation
azure_progress_callback
using kcenon::pacs::storage::azure_progress_callback
Initial value:
    std::function<bool(std::size_t bytes_transferred, std::size_t total_bytes)>
Callback type for upload/download progress tracking.
Parameters:
bytes_transferred: Number of bytes transferred so far
total_bytes: Total number of bytes to transfer
Returns: true to continue, false to abort
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/azure_blob_storage.h.
Definition at line 124 of file azure_blob_storage.h.
migration_function
using kcenon::pacs::storage::migration_function = std::function<VoidResult(sqlite3* db)>
Function type for migration implementations (SQLite)
Each migration function receives a database handle and should execute the necessary SQL to upgrade the schema to its target version.
Parameters
db The SQLite database handle
Returns
VoidResult Success or error information
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/migration_runner.h.
Definition at line 58 of file migration_runner.h.
progress_callback
using kcenon::pacs::storage::progress_callback
Initial value:
    std::function<bool(std::size_t bytes_transferred, std::size_t total_bytes)>
Callback type for upload/download progress tracking.
Parameters:
bytes_transferred: Number of bytes transferred so far
total_bytes: Total number of bytes to transfer
Returns: true to continue, false to abort
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/hsm_migration_service.h, and /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/s3_storage.h.
Definition at line 115 of file s3_storage.h.
Result
template<typename T > using kcenon::pacs::storage::Result = kcenon::common::Result<T>
Result type alias for operations returning a value.
Result type alias.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/azure_blob_storage.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/file_storage.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/hsm_storage.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/index_database.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/s3_storage.h, and /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/storage_interface.h.
Definition at line 176 of file annotation_repository.h.
Enumeration Type Documentation
annotation_type
enum class kcenon::pacs::storage::annotation_type strong
Annotation types supported by the system.
Enumerator
arrow
Arrow annotation.
line
Simple line.
rectangle
Rectangle shape.
ellipse
Ellipse/oval shape.
polygon
Multi-point polygon.
freehand
Freehand drawing.
text
Text annotation.
angle
Angle measurement annotation.
roi
Region of interest.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/annotation_record.h.
Definition at line 29 of file annotation_record.h.
{
    arrow,
    line,
    rectangle,
    ellipse,
    polygon,
    freehand,
    text,
    angle,
    roi
};
audit_event_type
enum class kcenon::pacs::storage::audit_event_type strong
Audit event type enumeration.
Enumerator
association_established
association_released
c_store
c_find
c_move
c_get
security_event
configuration_change
system_startup
system_shutdown
user_login
user_logout
data_access
data_export
error
Definition at line 28 of file audit_record.h.
{
    association_established,
    association_released,
    c_store,
    c_find,
    c_move,
    c_get,
    security_event,
    configuration_change,
    system_startup,
    system_shutdown,
    user_login,
    user_logout,
    data_access,
    data_export,
    error
};
audit_outcome
enum class kcenon::pacs::storage::audit_outcome strong
Audit log outcome/status.
Enumerator
success
failure
warning
Definition at line 142 of file audit_record.h.
{
    success,
    failure,
    warning
};
duplicate_policy
enum class kcenon::pacs::storage::duplicate_policy strong
Policy for handling duplicate SOP Instance UIDs.
Enumerator
reject
Return error if instance already exists.
replace
Overwrite existing instance.
ignore
Skip silently if instance exists.
Definition at line 52 of file file_storage.h.
{
    reject,
    replace,
    ignore
};
measurement_type
enum class kcenon::pacs::storage::measurement_type strong
Measurement types supported by the system.
Enumerator
length
Linear distance measurement.
area
Area measurement (generic)
angle
Angle measurement in degrees.
hounsfield
CT Hounsfield unit value.
suv
PET Standard Uptake Value.
ellipse_area
Ellipse area measurement.
polygon_area
Polygon area measurement.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/measurement_record.h.
Definition at line 29 of file measurement_record.h.
{
    length,
    area,
    angle,
    hounsfield,
    suv,
    ellipse_area,
    polygon_area
};
mpps_status
enum class kcenon::pacs::storage::mpps_status strong
MPPS status values.
Defines the valid states for a Modality Performed Procedure Step. COMPLETED and DISCONTINUED are final states.
Enumerator
in_progress
Procedure is currently being performed.
completed
Procedure completed successfully.
discontinued
Procedure was stopped/cancelled.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/mpps_record.h.
Definition at line 33 of file mpps_record.h.
                       {
    in_progress,
    completed,
    discontinued
};
naming_scheme
enum class kcenon::pacs::storage::naming_scheme strong
Naming scheme for DICOM file organization.
Determines how files are organized in the storage directory.
Enumerator
uid_hierarchical
{StudyUID}/{SeriesUID}/{SOPUID}.dcm
date_hierarchical
YYYY/MM/DD/{StudyUID}/{SOPUID}.dcm.
flat
{SOPUID}.dcm (flat structure)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/file_storage.h.
Definition at line 38 of file file_storage.h.
{
    uid_hierarchical,
    date_hierarchical,
    flat
};
storage_tier
enum class kcenon::pacs::storage::storage_tier strong
Storage tier classification.
Represents the different tiers in the hierarchical storage system. Each tier has different performance characteristics and cost implications:
Hot: Fast access, high cost (SSD/NVMe)
Warm: Medium access, medium cost (HDD)
Cold: Slow access, low cost (S3/Glacier/Archive)
Enumerator
hot
Hot tier - Recent, frequently accessed data (SSD/NVMe)
warm
Warm tier - Older, occasionally accessed data (HDD)
cold
Cold tier - Archive, rarely accessed data (S3/Glacier)
Definition at line 37 of file hsm_types.h.
{
    hot,
    warm,
    cold
};
ups_priority
enum class kcenon::pacs::storage::ups_priority strong
UPS workitem priority values.
Defines the priority levels for UPS workitems (PS3.4 CC.1.1).
Enumerator
low
Low priority.
medium
Medium priority (default)
high
High priority.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/ups_workitem.h.
Definition at line 90 of file ups_workitem.h.
{
    low,
    medium,
    high
};
ups_state
enum class kcenon::pacs::storage::ups_state strong
UPS workitem state values.
Defines the valid states for a Unified Procedure Step workitem. State transitions are unidirectional as defined in PS3.4 Table CC.1.1-2.
Enumerator
scheduled
Workitem is scheduled (initial state)
in_progress
Workitem is being performed.
completed
Workitem completed successfully (final)
canceled
Workitem was canceled (final)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/ups_workitem.h.
Definition at line 34 of file ups_workitem.h.
                     {
    scheduled,
    in_progress,
    completed,
    canceled
};
worklist_status
enum class kcenon::pacs::storage::worklist_status strong
Worklist step status values.
Defines the valid states for a Scheduled Procedure Step.
Enumerator
scheduled
Procedure is scheduled (default)
started
Procedure has been started (MPPS received)
completed
Procedure has been completed.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/worklist_record.h.
Definition at line 31 of file worklist_record.h.
{
    scheduled,
    started,
    completed
};
Function Documentation
annotation_type_from_string()
auto kcenon::pacs::storage::annotation_type_from_string (std::string_view str) -> std::optional<annotation_type> inline nodiscard
Parse string to annotation_type.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/annotation_record.h.
Definition at line 62 of file annotation_record.h.
{
    if (str == "arrow") return annotation_type::arrow;
    if (str == "line") return annotation_type::line;
    if (str == "rectangle") return annotation_type::rectangle;
    if (str == "ellipse") return annotation_type::ellipse;
    if (str == "polygon") return annotation_type::polygon;
    if (str == "freehand") return annotation_type::freehand;
    if (str == "text") return annotation_type::text;
    if (str == "angle") return annotation_type::angle;
    if (str == "roi") return annotation_type::roi;
    return std::nullopt;
}
References angle, arrow, ellipse, freehand, line, polygon, rectangle, roi, and text.
measurement_type_from_string()
auto kcenon::pacs::storage::measurement_type_from_string (std::string_view str) -> std::optional<measurement_type> inline nodiscard
Parse string to measurement_type.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/measurement_record.h.
Definition at line 58 of file measurement_record.h.
{
    if (str == "length") return measurement_type::length;
    if (str == "area") return measurement_type::area;
    if (str == "angle") return measurement_type::angle;
    if (str == "hounsfield") return measurement_type::hounsfield;
    if (str == "suv") return measurement_type::suv;
    if (str == "ellipse_area") return measurement_type::ellipse_area;
    if (str == "polygon_area") return measurement_type::polygon_area;
    return std::nullopt;
}
References angle, area, ellipse_area, hounsfield, length, polygon_area, and suv.
Referenced by kcenon::pacs::web::endpoints::register_measurement_endpoints_impl().
parse_audit_event_type()
auto kcenon::pacs::storage::parse_audit_event_type (std::string_view str) -> std::optional<audit_event_type> inline nodiscard
Parse string to audit_event_type enum.
Definition at line 89 of file audit_record.h.
{
    if (str == "ASSOCIATION_ESTABLISHED") {
        return audit_event_type::association_established;
    }
    if (str == "ASSOCIATION_RELEASED") {
        return audit_event_type::association_released;
    }
    if (str == "C_STORE") {
        return audit_event_type::c_store;
    }
    if (str == "C_FIND") {
        return audit_event_type::c_find;
    }
    if (str == "C_MOVE") {
        return audit_event_type::c_move;
    }
    if (str == "C_GET") {
        return audit_event_type::c_get;
    }
    if (str == "SECURITY_EVENT") {
        return audit_event_type::security_event;
    }
    if (str == "CONFIGURATION_CHANGE") {
        return audit_event_type::configuration_change;
    }
    if (str == "SYSTEM_STARTUP") {
        return audit_event_type::system_startup;
    }
    if (str == "SYSTEM_SHUTDOWN") {
        return audit_event_type::system_shutdown;
    }
    if (str == "USER_LOGIN") {
        return audit_event_type::user_login;
    }
    if (str == "USER_LOGOUT") {
        return audit_event_type::user_logout;
    }
    if (str == "DATA_ACCESS") {
        return audit_event_type::data_access;
    }
    if (str == "DATA_EXPORT") {
        return audit_event_type::data_export;
    }
    if (str == "ERROR") {
        return audit_event_type::error;
    }
    return std::nullopt;
}
References association_established, association_released, c_find, c_get, c_move, c_store, configuration_change, data_access, data_export, error, security_event, system_shutdown, system_startup, user_login, and user_logout.
parse_mpps_status()
auto kcenon::pacs::storage::parse_mpps_status (std::string_view str) -> std::optional<mpps_status> inline nodiscard
Parse string to mpps_status enum.
Parameters
str The string representation
Returns
Optional containing the status if valid, nullopt otherwise
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/mpps_record.h.
Definition at line 64 of file mpps_record.h.
{
    if (str == "IN PROGRESS") {
        return mpps_status::in_progress;
    }
    if (str == "COMPLETED") {
        return mpps_status::completed;
    }
    if (str == "DISCONTINUED") {
        return mpps_status::discontinued;
    }
    return std::nullopt;
}
References completed, discontinued, and in_progress.
Referenced by kcenon::pacs::storage::mpps_record::get_status().
parse_ups_priority()
auto kcenon::pacs::storage::parse_ups_priority (std::string_view str) -> std::optional<ups_priority> inline nodiscard
Parse string to ups_priority enum.
Parameters
str The string representation
Returns
Optional containing the priority if valid, nullopt otherwise
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/ups_workitem.h.
Definition at line 121 of file ups_workitem.h.
{
    if (str == "LOW") {
        return ups_priority::low;
    }
    if (str == "MEDIUM") {
        return ups_priority::medium;
    }
    if (str == "HIGH") {
        return ups_priority::high;
    }
    return std::nullopt;
}
References high, low, and medium.
Referenced by kcenon::pacs::storage::ups_workitem::get_priority().
parse_ups_state()
auto kcenon::pacs::storage::parse_ups_state (std::string_view str) -> std::optional<ups_state> inline nodiscard
Parse string to ups_state enum.
Parameters
str The string representation
Returns
Optional containing the state if valid, nullopt otherwise
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/ups_workitem.h.
Definition at line 68 of file ups_workitem.h.
{
    if (str == "SCHEDULED") {
        return ups_state::scheduled;
    }
    if (str == "IN PROGRESS") {
        return ups_state::in_progress;
    }
    if (str == "COMPLETED") {
        return ups_state::completed;
    }
    if (str == "CANCELED") {
        return ups_state::canceled;
    }
    return std::nullopt;
}
References canceled, completed, in_progress, and scheduled.
Referenced by kcenon::pacs::storage::ups_repository::change_ups_state(), kcenon::pacs::storage::ups_workitem::get_state(), kcenon::pacs::services::ups_push_scp::handle_n_action(), kcenon::pacs::services::ups_push_scp::handle_n_create(), and kcenon::pacs::services::ups_push_scp::handle_n_set().
parse_worklist_status()
auto kcenon::pacs::storage::parse_worklist_status (std::string_view str) -> std::optional<worklist_status> inline nodiscard
Parse string to worklist_status enum.
Parameters
str The string representation
Returns
Optional containing the status if valid, nullopt otherwise
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/worklist_record.h.
Definition at line 62 of file worklist_record.h.
{
    if (str == "SCHEDULED") {
        return worklist_status::scheduled;
    }
    if (str == "STARTED") {
        return worklist_status::started;
    }
    if (str == "COMPLETED") {
        return worklist_status::completed;
    }
    return std::nullopt;
}
References completed, scheduled, and started.
Referenced by kcenon::pacs::storage::worklist_item::get_status().
storage_tier_from_string()
auto kcenon::pacs::storage::storage_tier_from_string (std::string_view str) -> std::optional<storage_tier> nodiscard constexpr
Parse storage_tier from string.
Parameters
str String representation ("hot", "warm", "cold")
Returns
Parsed storage tier or std::nullopt if invalid
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/hsm_types.h.
Definition at line 71 of file hsm_types.h.
{
    if (str == "hot") {
        return storage_tier::hot;
    }
    if (str == "warm") {
        return storage_tier::warm;
    }
    if (str == "cold") {
        return storage_tier::cold;
    }
    return std::nullopt;
}
References cold, hot, and warm.
to_string() [1/9]
auto kcenon::pacs::storage::to_string (annotation_type type) -> std::string inline nodiscard
Convert annotation_type to string.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/annotation_record.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/hsm_types.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/measurement_record.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/mpps_record.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/ups_workitem.h, and /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/storage/worklist_record.h.
Definition at line 44 of file annotation_record.h.
{
    switch (type) {
        case annotation_type::arrow: return "arrow";
        case annotation_type::line: return "line";
        case annotation_type::rectangle: return "rectangle";
        case annotation_type::ellipse: return "ellipse";
        case annotation_type::polygon: return "polygon";
        case annotation_type::freehand: return "freehand";
        case annotation_type::text: return "text";
        case annotation_type::angle: return "angle";
        case annotation_type::roi: return "roi";
    }
    return "unknown";
}
References angle, arrow, ellipse, freehand, line, polygon, rectangle, roi, and text.
Referenced by kcenon::pacs::storage::hsm_storage::migrate_instance(), kcenon::pacs::storage::sync_repository::resolve_conflict(), kcenon::pacs::storage::annotation_repository::save(), kcenon::pacs::storage::measurement_repository::save(), kcenon::pacs::storage::sync_repository::save_config(), kcenon::pacs::storage::sync_repository::save_conflict(), kcenon::pacs::storage::annotation_repository::search(), kcenon::pacs::storage::measurement_repository::search(), and kcenon::pacs::storage::hsm_storage::verify_integrity().
to_string() [2/9]
auto kcenon::pacs::storage::to_string (audit_event_type type) -> std::string inline nodiscard
Convert audit_event_type enum to string representation.
Definition at line 49 of file audit_record.h.
{
    switch (type) {
        case audit_event_type::association_established:
            return "ASSOCIATION_ESTABLISHED";
        case audit_event_type::association_released:
            return "ASSOCIATION_RELEASED";
        case audit_event_type::c_store:
            return "C_STORE";
        case audit_event_type::c_find:
            return "C_FIND";
        case audit_event_type::c_move:
            return "C_MOVE";
        case audit_event_type::c_get:
            return "C_GET";
        case audit_event_type::security_event:
            return "SECURITY_EVENT";
        case audit_event_type::configuration_change:
            return "CONFIGURATION_CHANGE";
        case audit_event_type::system_startup:
            return "SYSTEM_STARTUP";
        case audit_event_type::system_shutdown:
            return "SYSTEM_SHUTDOWN";
        case audit_event_type::user_login:
            return "USER_LOGIN";
        case audit_event_type::user_logout:
            return "USER_LOGOUT";
        case audit_event_type::data_access:
            return "DATA_ACCESS";
        case audit_event_type::data_export:
            return "DATA_EXPORT";
        case audit_event_type::error:
            return "ERROR";
        default:
            return "UNKNOWN";
    }
}
References association_established, association_released, c_find, c_get, c_move, c_store, configuration_change, data_access, data_export, error, security_event, system_shutdown, system_startup, user_login, and user_logout.
to_string() [3/9]
auto kcenon::pacs::storage::to_string (audit_outcome outcome) -> std::string inline nodiscard
Convert audit_outcome enum to string.
Definition at line 151 of file audit_record.h.
{
    switch (outcome) {
        case audit_outcome::success:
            return "SUCCESS";
        case audit_outcome::failure:
            return "FAILURE";
        case audit_outcome::warning:
            return "WARNING";
        default:
            return "UNKNOWN";
    }
}
References failure, success, and warning.
to_string() [4/9]
auto kcenon::pacs::storage::to_string (measurement_type type) -> std::string inline nodiscard
Convert measurement_type to string.
Definition at line 42 of file measurement_record.h.
{
    switch (type) {
        case measurement_type::length: return "length";
        case measurement_type::area: return "area";
        case measurement_type::angle: return "angle";
        case measurement_type::hounsfield: return "hounsfield";
        case measurement_type::suv: return "suv";
        case measurement_type::ellipse_area: return "ellipse_area";
        case measurement_type::polygon_area: return "polygon_area";
    }
    return "unknown";
}
References angle, area, ellipse_area, hounsfield, length, polygon_area, and suv.
to_string() [5/9]
auto kcenon::pacs::storage::to_string (mpps_status status) -> std::string inline nodiscard
Convert mpps_status enum to string representation.
Parameters
status The status enum value
Returns
String representation matching DICOM standard
Definition at line 45 of file mpps_record.h.
{
    switch (status) {
        case mpps_status::in_progress:
            return "IN PROGRESS";
        case mpps_status::completed:
            return "COMPLETED";
        case mpps_status::discontinued:
            return "DISCONTINUED";
        default:
            return "IN PROGRESS";
    }
}
References completed, discontinued, and in_progress.
to_string() [6/9]
auto kcenon::pacs::storage::to_string (storage_tier tier) -> std::string_view nodiscard constexpr noexcept
Convert storage_tier to string representation.
Parameters
tier The storage tier
Returns
String representation ("hot", "warm", "cold")
Definition at line 53 of file hsm_types.h.
                      {
    switch (tier) {
        case storage_tier::hot:
            return "hot";
        case storage_tier::warm:
            return "warm";
        case storage_tier::cold:
            return "cold";
    }
    return "unknown";
}
References cold, hot, and warm.
to_string() [7/9]
auto kcenon::pacs::storage::to_string (ups_priority priority) -> std::string inline nodiscard
Convert ups_priority enum to string representation.
Parameters
priority The priority enum value
Returns
String representation matching DICOM standard
Definition at line 102 of file ups_workitem.h.
{
    switch (priority) {
        case ups_priority::low:
            return "LOW";
        case ups_priority::medium:
            return "MEDIUM";
        case ups_priority::high:
            return "HIGH";
        default:
            return "MEDIUM";
    }
}
References high, low, and medium.
to_string() [8/9]
auto kcenon::pacs::storage::to_string (ups_state state) -> std::string inline nodiscard
Convert ups_state enum to string representation.
Parameters
state The state enum value
Returns
String representation matching DICOM standard
Definition at line 47 of file ups_workitem.h.
{
    switch (state) {
        case ups_state::scheduled:
            return "SCHEDULED";
        case ups_state::in_progress:
            return "IN PROGRESS";
        case ups_state::completed:
            return "COMPLETED";
        case ups_state::canceled:
            return "CANCELED";
        default:
            return "SCHEDULED";
    }
}
References canceled, completed, in_progress, and scheduled.
to_string() [9/9]
auto kcenon::pacs::storage::to_string (worklist_status status) -> std::string inline nodiscard
Convert worklist_status enum to string representation.
Parameters
status The status enum value
Returns
String representation
Definition at line 43 of file worklist_record.h.
{
    switch (status) {
        case worklist_status::scheduled:
            return "SCHEDULED";
        case worklist_status::started:
            return "STARTED";
        case worklist_status::completed:
            return "COMPLETED";
        default:
            return "SCHEDULED";
    }
}
References completed, scheduled, and started.