PACS System: kcenon::pacs::ai Namespace Reference
kcenon::pacs::ai Namespace Reference
Namespaces
namespace aira_tags
namespace json_util
namespace manager_tags
namespace metrics
namespace sop_class
Classes
struct ai_assessment
Complete assessment of an AI result.
struct ai_handler_config
Configuration for AI result handler.
class ai_result_handler
struct ai_result_info
Information about an AI result stored in the system.
struct ai_service_config
Configuration for AI service connection.
class ai_service_connector
Connector for external AI inference services.
struct assessed_result_reference
Reference to the AI result being assessed.
struct assessment_creation_result
Result of creating an assessment SR document.
class assessment_creator
struct assessment_info
Information about a stored assessment.
class assessment_manager
struct assessment_modification
Modification details when assessment_type is modify.
struct assessment_rejection
Rejection reason when assessment_type is reject.
struct cad_finding
CAD finding extracted from Structured Report.
struct error_info
Simple error info for fallback when common_system is unavailable.
struct inference_request
Request structure for AI inference.
struct inference_status
Status information for an inference job.
struct model_info
Information about an available AI model.
class Result
Simple result type for error handling.
struct segment_info
Segment information from Segmentation object.
struct source_reference
Source reference linking AI result to original images.
struct validation_result
Validation result containing status and details.
Typedefs
template<typename T >
using Result = kcenon::common::Result< T >
Result type alias for operations returning a value.
using VoidResult = kcenon::common::VoidResult
Result type alias for void operations.
using ai_result_received_callback = std::function< void(const ai_result_info &info)>
Callback for notification when AI result is received.
using pre_store_validator = std::function< bool(const core::dicom_dataset &dataset, ai_result_type type)>
Callback for pre-storage validation.
Enumerations
enum class ai_result_type { structured_report , segmentation , presentation_state }
Types of AI-generated DICOM objects.
enum class validation_status {
valid , missing_required_tags , invalid_reference , invalid_template ,
invalid_segment_data , unknown_error
}
Validation status for AI results.
enum class inference_status_code {
pending , running , completed , failed ,
cancelled , timeout
}
Status codes for AI inference jobs.
enum class authentication_type { none , api_key , bearer_token , basic }
Types of authentication for AI services.
enum class assessment_type { accept , modify , reject }
Assessment decision made by a clinician on an AI result.
enum class assessment_status { draft , final_ , amended }
Assessment status tracking.
Functions
auto to_string (inference_status_code status) -> std::string
Convert inference status code to string.
auto to_string (authentication_type type) -> std::string
Convert authentication type to string.
std::string to_string (assessment_type type)
Convert assessment_type enum to string.
std::string to_string (assessment_status status)
Convert assessment_status enum to string.
if (!request.parameters.empty())
if (!request.metadata.empty())
Typedef Documentation
ai_result_received_callback
using kcenon::pacs::ai::ai_result_received_callback = typedef std::function<void(const ai_result_info& info)>
Callback for notification when AI result is received.
Parameters
info Information about the received AI result
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/ai/ai_result_handler.hpp.
Definition at line 231 of file ai_result_handler.hpp.
pre_store_validator
using kcenon::pacs::ai::pre_store_validator = typedef std::function<bool(const core::dicom_dataset& dataset, ai_result_type type)>
Callback for pre-storage validation.
Parameters
dataset The AI result dataset to validate
type The type of AI result
Returns
true to proceed with storage, false to reject
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/ai/ai_result_handler.hpp.
Definition at line 240 of file ai_result_handler.hpp.
Result
template<typename T > using kcenon::pacs::ai::Result = typedef kcenon::common::Result<T>
Result type alias for operations returning a value.
Definition at line 65 of file ai_result_handler.hpp.
VoidResult
using kcenon::pacs::ai::VoidResult = typedef kcenon::common::VoidResult
Result type alias for void operations.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/ai/ai_result_handler.hpp.
Definition at line 68 of file ai_result_handler.hpp.
Enumeration Type Documentation
ai_result_type
enum class kcenon::pacs::ai::ai_result_type strong
Types of AI-generated DICOM objects.
Enumerator
structured_report
DICOM SR (Structured Report)
segmentation
DICOM SEG (Segmentation)
presentation_state
DICOM PR (Presentation State)
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/ai/ai_result_handler.hpp.
Definition at line 77 of file ai_result_handler.hpp.
{
    structured_report,
    segmentation,
    presentation_state
};
assessment_status
enum class kcenon::pacs::ai::assessment_status strong
Assessment status tracking.
Enumerator
draft
Assessment in progress, not yet finalized.
final_
Assessment finalized and signed off.
amended
Previously finalized assessment has been amended.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/ai/aira_assessment.hpp.
Definition at line 73 of file aira_assessment.hpp.
{
    draft,
    final_,
    amended
};
assessment_type
enum class kcenon::pacs::ai::assessment_type strong
Assessment decision made by a clinician on an AI result.
Enumerator
accept
Clinician accepts AI result as-is.
modify
Clinician modifies AI result (e.g., edits segmentation)
reject
Clinician rejects AI result with reason.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/ai/aira_assessment.hpp, and /home/runner/work/pacs_system/pacs_system/include/pacs/ai/aira_assessment_manager.hpp.
Definition at line 64 of file aira_assessment.hpp.
{
    accept,
    modify,
    reject
};
authentication_type
enum class kcenon::pacs::ai::authentication_type strong
Types of authentication for AI services.
Enumerator
none
No authentication.
api_key
API key in header.
bearer_token
OAuth2 bearer token.
basic
HTTP basic authentication.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/ai/ai_service_connector.hpp.
Definition at line 135 of file ai_service_connector.hpp.
{
    none,
    api_key,
    bearer_token,
    basic
};
inference_status_code
enum class kcenon::pacs::ai::inference_status_code strong
Status codes for AI inference jobs.
Enumerator
pending
Job is queued but not started.
running
Job is currently processing.
completed
Job completed successfully.
failed
Job failed with error.
cancelled
Job was cancelled.
timeout
Job timed out.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/ai/ai_service_connector.hpp.
Definition at line 122 of file ai_service_connector.hpp.
{
    pending,
    running,
    completed,
    failed,
    cancelled,
    timeout
};
validation_status
enum class kcenon::pacs::ai::validation_status strong
Validation status for AI results.
Enumerator
valid
All validations passed.
missing_required_tags
Required DICOM tags are missing.
invalid_reference
Referenced source images not found.
invalid_template
SR template conformance failed.
invalid_segment_data
Segmentation data is malformed.
unknown_error
Unexpected validation error.
Examples
/home/runner/work/pacs_system/pacs_system/include/pacs/ai/ai_result_handler.hpp.
Definition at line 86 of file ai_result_handler.hpp.
{
    valid,
    missing_required_tags,
    invalid_reference,
    invalid_template,
    invalid_segment_data,
    unknown_error
};
Function Documentation
if() [1/2]
kcenon::pacs::ai::if (!request.metadata. empty())
Definition at line 268 of file ai_service_connector.cpp.
{
        oss << R"(,"metadata":{)";
        bool first = true;
        for (const auto& [key, value] : request.metadata) {
            if (!first) oss << ",";
            oss << "\"" << escape_string(key) << "\":\"" << escape_string(value) << "\"";
            first = false;
        }
        oss << "}";
    }
References kcenon::pacs::ai::json_util::escape_string(), and kcenon::pacs::ai::inference_request::metadata.
if() [2/2]
kcenon::pacs::ai::if (!request.parameters. empty())
Definition at line 257 of file ai_service_connector.cpp.
{
        oss << R"(,"parameters":{)";
        bool first = true;
        for (const auto& [key, value] : request.parameters) {
            if (!first) oss << ",";
            oss << "\"" << escape_string(key) << "\":\"" << escape_string(value) << "\"";
            first = false;
        }
        oss << "}";
    }
References kcenon::pacs::ai::json_util::escape_string(), and kcenon::pacs::ai::inference_request::parameters.
to_string() [1/4]
std::string kcenon::pacs::ai::to_string (assessment_status status)
Convert assessment_status enum to string.
Definition at line 396 of file aira_assessment.cpp.
{
    switch (status) {
    case assessment_status::draft:   return "draft";
    case assessment_status::final_:  return "final";
    case assessment_status::amended: return "amended";
    }
    return "draft";
}
References amended, draft, final_, and to_string().
to_string() [2/4]
std::string kcenon::pacs::ai::to_string (assessment_type type)
Convert assessment_type enum to string.
Definition at line 387 of file aira_assessment.cpp.
{
    switch (type) {
    case assessment_type::accept: return "accept";
    case assessment_type::modify: return "modify";
    case assessment_type::reject: return "reject";
    }
    return "accept";
}
References accept, modify, reject, and to_string().
to_string() [3/4]
auto kcenon::pacs::ai::to_string (authentication_type type) -> std::string inline
Convert authentication type to string.
Parameters
type The authentication type
Returns
Human-readable authentication type string
Definition at line 551 of file ai_service_connector.hpp.
{
    switch (type) {
        case authentication_type::none:
            return "none";
        case authentication_type::api_key:
            return "api_key";
        case authentication_type::bearer_token:
            return "bearer_token";
        case authentication_type::basic:
            return "basic";
        default:
            return "unknown";
    }
}
References api_key, basic, bearer_token, none, and to_string().
to_string() [4/4]
auto kcenon::pacs::ai::to_string (inference_status_code status) -> std::string inline
Convert inference status code to string.
Parameters
status The status code
Returns
Human-readable status string
Definition at line 527 of file ai_service_connector.hpp.
{
    switch (status) {
        case inference_status_code::pending:
            return "pending";
        case inference_status_code::running:
            return "running";
        case inference_status_code::completed:
            return "completed";
        case inference_status_code::failed:
            return "failed";
        case inference_status_code::cancelled:
            return "cancelled";
        case inference_status_code::timeout:
            return "timeout";
        default:
            return "unknown";
    }
}
References cancelled, completed, failed, pending, running, timeout, and to_string().
Referenced by to_string(), to_string(), to_string(), and to_string().