PACS System: kcenon::pacs::integration_test Namespace Reference
kcenon::pacs::integration_test Namespace Reference
Classes
class background_process_guard
RAII wrapper for a background process.
struct dcmtk_result
Result of a DCMTK tool execution.
class dcmtk_server_guard
RAII guard for DCMTK server processes.
class dcmtk_tool
Wrapper class for DCMTK command-line tools.
struct multi_modal_study
Represents a complete patient study with multiple modalities.
class process_launcher
Cross-platform process launcher for binary integration testing.
struct process_result
Result of a process execution.
class test_association
Helper for establishing test associations.
class test_counter
Thread-safe test result counter.
class test_data_generator
Comprehensive DICOM test data generator.
class test_directory
RAII wrapper for temporary test directory.
class test_server
RAII wrapper for a test DICOM server.
Enumerations
enum class invalid_dataset_type {
missing_sop_class_uid , missing_sop_instance_uid , missing_patient_id , missing_study_instance_uid ,
invalid_vr , corrupted_pixel_data , oversized_value
}
Types of invalid datasets for error testing.
Functions
TEST_CASE ("test_data_generator::ct generates valid CT dataset", "[data_generator][ct]")
TEST_CASE ("test_data_generator::mr generates valid MR dataset", "[data_generator][mr]")
TEST_CASE ("test_data_generator::xa generates valid XA dataset", "[data_generator][xa]")
TEST_CASE ("test_data_generator::us generates valid US dataset", "[data_generator][us]")
TEST_CASE ("test_data_generator::xa_cine generates valid multi-frame XA dataset", "[data_generator][xa][multiframe]")
TEST_CASE ("test_data_generator::us_cine generates valid multi-frame US dataset", "[data_generator][us][multiframe]")
TEST_CASE ("test_data_generator::enhanced_ct generates valid Enhanced CT dataset", "[data_generator][ct][enhanced]")
TEST_CASE ("test_data_generator::enhanced_mr generates valid Enhanced MR dataset", "[data_generator][mr][enhanced]")
TEST_CASE ("test_data_generator::patient_journey creates multi-modal study", "[data_generator][workflow]")
TEST_CASE ("test_data_generator::worklist generates valid worklist item", "[data_generator][worklist]")
TEST_CASE ("test_data_generator::large creates appropriately sized dataset", "[data_generator][edge_case]")
TEST_CASE ("test_data_generator::unicode creates dataset with Unicode characters", "[data_generator][edge_case][unicode]")
TEST_CASE ("test_data_generator::with_private_tags includes private tags", "[data_generator][edge_case][private]")
TEST_CASE ("test_data_generator::invalid creates datasets with specific errors", "[data_generator][edge_case][invalid]")
TEST_CASE ("test_data_generator::generate_uid creates unique UIDs", "[data_generator][utility]")
TEST_CASE ("test_data_generator::current_date returns valid DICOM date", "[data_generator][utility]")
TEST_CASE ("test_data_generator::current_time returns valid DICOM time", "[data_generator][utility]")
bool is_ci_environment ()
Check if running in a CI environment.
std::chrono::milliseconds default_timeout ()
Default timeout for test operations (5s normal, 30s CI)
std::chrono::milliseconds server_ready_timeout ()
Port listening timeout for pacs_system servers (5s normal, 30s CI)
std::chrono::milliseconds dcmtk_server_ready_timeout ()
Port listening timeout for DCMTK servers (10s normal, 60s CI)
bool supports_real_tcp_dicom ()
Check if pacs_system supports real TCP DICOM connections.
std::string generate_uid (const std::string &root="1.2.826.0.1.3680043.9.9999")
Generate a unique UID for testing.
bool is_port_available (uint16_t port)
Check if a port is actually available by attempting to bind.
uint16_t find_available_port (uint16_t start=default_test_port, int max_attempts=200)
Find an available port for testing.
template<typename Func >
bool wait_for (Func &&condition, std::chrono::milliseconds timeout, std::chrono::milliseconds interval=std::chrono::milliseconds{50})
Wait for a condition with timeout.
template<typename Func >
bool wait_for (Func &&condition)
Wait for a condition with default timeout.
core::dicom_dataset generate_ct_dataset (const std::string &study_uid="", const std::string &series_uid="", const std::string &instance_uid="")
Generate a minimal CT image dataset for testing.
core::dicom_dataset generate_mr_dataset (const std::string &study_uid="")
Generate a MR image dataset for testing.
core::dicom_dataset generate_xa_dataset (const std::string &study_uid="")
Generate a XA (X-Ray Angiographic) image dataset for testing.
core::dicom_dataset generate_worklist_item ()
Generate a worklist item dataset.
Variables
constexpr uint16_t default_test_port = 41104
Default test port range start (use high ports to avoid conflicts)
constexpr const char * test_scp_ae_title = "TEST_SCP"
Default AE titles.
constexpr const char * test_scu_ae_title = "TEST_SCU"
Enumeration Type Documentation
invalid_dataset_type
enum class kcenon::pacs::integration_test::invalid_dataset_type strong
Types of invalid datasets for error testing.
Enumerator
missing_sop_class_uid
Missing SOP Class UID.
missing_sop_instance_uid
Missing SOP Instance UID.
missing_patient_id
Missing Patient ID.
missing_study_instance_uid
Missing Study Instance UID.
invalid_vr
Invalid Value Representation.
corrupted_pixel_data
Corrupted pixel data.
oversized_value
Value exceeds VR length limit.
Definition at line 34 of file test_data_generator.h.
{
    missing_sop_class_uid,
    missing_sop_instance_uid,
    missing_patient_id,
    missing_study_instance_uid,
    invalid_vr,
    corrupted_pixel_data,
    oversized_value
};
Function Documentation
dcmtk_server_ready_timeout()
std::chrono::milliseconds kcenon::pacs::integration_test::dcmtk_server_ready_timeout () inline
Port listening timeout for DCMTK servers (10s normal, 60s CI)
Definition at line 119 of file test_fixtures.h.
{
    return is_ci_environment()
        ? std::chrono::milliseconds{60000}
        : std::chrono::milliseconds{10000};
}
References is_ci_environment().
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
default_timeout()
std::chrono::milliseconds kcenon::pacs::integration_test::default_timeout () inline
Default timeout for test operations (5s normal, 30s CI)
Definition at line 105 of file test_fixtures.h.
{
    return is_ci_environment()
        ? std::chrono::milliseconds{30000}
        : std::chrono::milliseconds{5000};
}
References is_ci_environment().
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and wait_for().
find_available_port()
uint16_t kcenon::pacs::integration_test::find_available_port (uint16_t start = default_test_port, int max_attempts = 200) inline
Find an available port for testing.
Parameters
start Starting port number (default: default_test_port)
max_attempts Maximum attempts to find an available port
Returns
Available port number
This function actually tests port availability by attempting to bind, which prevents port conflicts in CI environments where multiple tests may run concurrently.
Definition at line 239 of file test_fixtures.h.
{
    static std::atomic<uint16_t> port_offset{0};
    // Use a wider range and randomize starting point to reduce conflicts
    static std::random_device rd;
    static std::mt19937 gen(rd());
    std::uniform_int_distribution<uint16_t> dist(0, 500);
    uint16_t base_offset = port_offset.fetch_add(1) % 200;
    uint16_t random_offset = dist(gen);
    for (int attempt = 0; attempt < max_attempts; ++attempt) {
        uint16_t port = start + ((base_offset + random_offset + attempt) % 1000);
        // Avoid well-known ports and ensure we stay in a valid range
        if (port < 1024) {
            port += 40000;
        }
        if (port > 65000) {
            port = start + (attempt % 500);
        }
        if (is_port_available(port)) {
            return port;
        }
    }
    // Fallback: return incremental port (original behavior)
    return start + (port_offset++ % 100);
}
References is_port_available().
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
generate_ct_dataset()
core::dicom_dataset kcenon::pacs::integration_test::generate_ct_dataset (const std::string & study_uid = "", const std::string & series_uid = "", const std::string & instance_uid = "") inline
Generate a minimal CT image dataset for testing.
Parameters
study_uid Study Instance UID (generated if empty)
series_uid Series Instance UID (generated if empty)
instance_uid SOP Instance UID (generated if empty)
Returns
DICOM dataset
Definition at line 316 of file test_fixtures.h.
{
    core::dicom_dataset ds;
    // Patient module
    ds.set_string(core::tags::patient_name, encoding::vr_type::PN, "TEST^PATIENT");
    ds.set_string(core::tags::patient_id, encoding::vr_type::LO, "TEST001");
    ds.set_string(core::tags::patient_birth_date, encoding::vr_type::DA, "19800101");
    ds.set_string(core::tags::patient_sex, encoding::vr_type::CS, "M");
    // Study module
    ds.set_string(core::tags::study_instance_uid, encoding::vr_type::UI,
                  study_uid.empty() ? generate_uid() : study_uid);
    ds.set_string(core::tags::study_date, encoding::vr_type::DA, "20240101");
    ds.set_string(core::tags::study_time, encoding::vr_type::TM, "120000");
    ds.set_string(core::tags::accession_number, encoding::vr_type::SH, "ACC001");
    ds.set_string(core::tags::study_id, encoding::vr_type::SH, "STUDY001");
    ds.set_string(core::tags::study_description, encoding::vr_type::LO, "Integration Test Study");
    // Series module
    ds.set_string(core::tags::series_instance_uid, encoding::vr_type::UI,
                  series_uid.empty() ? generate_uid() : series_uid);
    ds.set_string(core::tags::modality, encoding::vr_type::CS, "CT");
    ds.set_string(core::tags::series_number, encoding::vr_type::IS, "1");
    ds.set_string(core::tags::series_description, encoding::vr_type::LO, "Test Series");
    // SOP Common module
    ds.set_string(core::tags::sop_class_uid, encoding::vr_type::UI, "1.2.840.10008.5.1.4.1.1.2");  // CT Image Storage
    ds.set_string(core::tags::sop_instance_uid, encoding::vr_type::UI,
                  instance_uid.empty() ? generate_uid() : instance_uid);
    // Image module (minimal)
    ds.set_numeric<uint16_t>(core::tags::rows, encoding::vr_type::US, 64);
    ds.set_numeric<uint16_t>(core::tags::columns, encoding::vr_type::US, 64);
    ds.set_numeric<uint16_t>(core::tags::bits_allocated, encoding::vr_type::US, 16);
    ds.set_numeric<uint16_t>(core::tags::bits_stored, encoding::vr_type::US, 12);
    ds.set_numeric<uint16_t>(core::tags::high_bit, encoding::vr_type::US, 11);
    ds.set_numeric<uint16_t>(core::tags::pixel_representation, encoding::vr_type::US, 0);
    ds.set_numeric<uint16_t>(core::tags::samples_per_pixel, encoding::vr_type::US, 1);
    ds.set_string(core::tags::photometric_interpretation, encoding::vr_type::CS, "MONOCHROME2");
    // Generate minimal pixel data (64x64 16-bit)
    std::vector<uint16_t> pixel_data(64 * 64, 512);
    core::dicom_element pixel_elem(core::tags::pixel_data, encoding::vr_type::OW);
    pixel_elem.set_value(std::span<const uint8_t>(
        reinterpret_cast<const uint8_t*>(pixel_data.data()),
        pixel_data.size() * sizeof(uint16_t)));
    ds.insert(std::move(pixel_elem));
    return ds;
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::tags::columns, kcenon::pacs::encoding::CS, kcenon::pacs::encoding::DA, generate_uid(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::core::dicom_dataset::insert(), kcenon::pacs::encoding::IS, kcenon::pacs::encoding::LO, kcenon::pacs::core::tags::modality, kcenon::pacs::encoding::OW, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, kcenon::pacs::core::tags::patient_sex, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::encoding::PN, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, kcenon::pacs::core::tags::series_description, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::series_number, kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::core::dicom_element::set_value(), kcenon::pacs::encoding::SH, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_description, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, kcenon::pacs::core::tags::study_time, kcenon::pacs::encoding::TM, kcenon::pacs::encoding::UI, and kcenon::pacs::encoding::US.
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
generate_mr_dataset()
core::dicom_dataset kcenon::pacs::integration_test::generate_mr_dataset (const std::string & study_uid = "") inline
Generate a MR image dataset for testing.
Parameters
study_uid Study Instance UID (generated if empty)
Returns
DICOM dataset
Definition at line 376 of file test_fixtures.h.
{
    core::dicom_dataset ds;
    // Patient module
    ds.set_string(core::tags::patient_name, encoding::vr_type::PN, "TEST^MR^PATIENT");
    ds.set_string(core::tags::patient_id, encoding::vr_type::LO, "TESTMR001");
    ds.set_string(core::tags::patient_birth_date, encoding::vr_type::DA, "19900215");
    ds.set_string(core::tags::patient_sex, encoding::vr_type::CS, "F");
    // Study module
    ds.set_string(core::tags::study_instance_uid, encoding::vr_type::UI,
                  study_uid.empty() ? generate_uid() : study_uid);
    ds.set_string(core::tags::study_date, encoding::vr_type::DA, "20240115");
    ds.set_string(core::tags::study_time, encoding::vr_type::TM, "140000");
    ds.set_string(core::tags::accession_number, encoding::vr_type::SH, "ACCMR001");
    ds.set_string(core::tags::study_id, encoding::vr_type::SH, "STUDYMR001");
    ds.set_string(core::tags::study_description, encoding::vr_type::LO, "MR Integration Test");
    // Series module
    ds.set_string(core::tags::series_instance_uid, encoding::vr_type::UI, generate_uid());
    ds.set_string(core::tags::modality, encoding::vr_type::CS, "MR");
    ds.set_string(core::tags::series_number, encoding::vr_type::IS, "1");
    ds.set_string(core::tags::series_description, encoding::vr_type::LO, "T1 FLAIR");
    // SOP Common module
    ds.set_string(core::tags::sop_class_uid, encoding::vr_type::UI, "1.2.840.10008.5.1.4.1.1.4");  // MR Image Storage
    ds.set_string(core::tags::sop_instance_uid, encoding::vr_type::UI, generate_uid());
    // Image module (minimal)
    ds.set_numeric<uint16_t>(core::tags::rows, encoding::vr_type::US, 64);
    ds.set_numeric<uint16_t>(core::tags::columns, encoding::vr_type::US, 64);
    ds.set_numeric<uint16_t>(core::tags::bits_allocated, encoding::vr_type::US, 16);
    ds.set_numeric<uint16_t>(core::tags::bits_stored, encoding::vr_type::US, 12);
    ds.set_numeric<uint16_t>(core::tags::high_bit, encoding::vr_type::US, 11);
    ds.set_numeric<uint16_t>(core::tags::pixel_representation, encoding::vr_type::US, 0);
    ds.set_numeric<uint16_t>(core::tags::samples_per_pixel, encoding::vr_type::US, 1);
    ds.set_string(core::tags::photometric_interpretation, encoding::vr_type::CS, "MONOCHROME2");
    // Generate minimal pixel data
    std::vector<uint16_t> pixel_data(64 * 64, 256);
    core::dicom_element pixel_elem(core::tags::pixel_data, encoding::vr_type::OW);
    pixel_elem.set_value(std::span<const uint8_t>(
        reinterpret_cast<const uint8_t*>(pixel_data.data()),
        pixel_data.size() * sizeof(uint16_t)));
    ds.insert(std::move(pixel_elem));
    return ds;
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::tags::columns, kcenon::pacs::encoding::CS, kcenon::pacs::encoding::DA, generate_uid(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::core::dicom_dataset::insert(), kcenon::pacs::encoding::IS, kcenon::pacs::encoding::LO, kcenon::pacs::core::tags::modality, kcenon::pacs::encoding::OW, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, kcenon::pacs::core::tags::patient_sex, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::encoding::PN, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, kcenon::pacs::core::tags::series_description, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::series_number, kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::core::dicom_element::set_value(), kcenon::pacs::encoding::SH, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_description, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, kcenon::pacs::core::tags::study_time, kcenon::pacs::encoding::TM, kcenon::pacs::encoding::UI, and kcenon::pacs::encoding::US.
Referenced by TEST_CASE(), and TEST_CASE().
generate_uid()
std::string kcenon::pacs::integration_test::generate_uid (const std::string & root = "1.2.826.0.1.3680043.9.9999") inline
Generate a unique UID for testing.
Parameters
root Root UID prefix
Returns
Unique UID string
Definition at line 174 of file test_fixtures.h.
{
    static std::atomic<uint64_t> counter{0};
    auto now = std::chrono::system_clock::now();
    auto timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(
        now.time_since_epoch()).count();
    return root + "." + std::to_string(timestamp) + "." + std::to_string(++counter);
}
Referenced by generate_ct_dataset(), generate_mr_dataset(), generate_worklist_item(), generate_xa_dataset(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
generate_worklist_item()
core::dicom_dataset kcenon::pacs::integration_test::generate_worklist_item () inline
Generate a worklist item dataset.
Returns
DICOM dataset for worklist
Definition at line 496 of file test_fixtures.h.
{
    core::dicom_dataset ds;
    // Patient module
    ds.set_string(core::tags::patient_name, encoding::vr_type::PN, "WORKLIST^PATIENT");
    ds.set_string(core::tags::patient_id, encoding::vr_type::LO, "WL001");
    ds.set_string(core::tags::patient_birth_date, encoding::vr_type::DA, "19850520");
    ds.set_string(core::tags::patient_sex, encoding::vr_type::CS, "M");
    // Scheduled Procedure Step
    ds.set_string(core::tags::scheduled_procedure_step_start_date, encoding::vr_type::DA, "20240201");
    ds.set_string(core::tags::scheduled_procedure_step_start_time, encoding::vr_type::TM, "090000");
    ds.set_string(core::tags::modality, encoding::vr_type::CS, "CT");
    ds.set_string(core::tags::scheduled_station_ae_title, encoding::vr_type::AE, "CT_SCANNER");
    ds.set_string(core::tags::scheduled_procedure_step_description, encoding::vr_type::LO, "CT Chest");
    // Requested Procedure
    ds.set_string(core::tags::requested_procedure_id, encoding::vr_type::SH, "RP001");
    ds.set_string(core::tags::accession_number, encoding::vr_type::SH, "WLACC001");
    ds.set_string(core::tags::study_instance_uid, encoding::vr_type::UI, generate_uid());
    return ds;
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::encoding::AE, kcenon::pacs::encoding::CS, kcenon::pacs::encoding::DA, generate_uid(), kcenon::pacs::encoding::LO, kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, kcenon::pacs::core::tags::patient_sex, kcenon::pacs::encoding::PN, kcenon::pacs::core::tags::requested_procedure_id, kcenon::pacs::core::tags::scheduled_procedure_step_description, kcenon::pacs::core::tags::scheduled_procedure_step_start_date, kcenon::pacs::core::tags::scheduled_procedure_step_start_time, kcenon::pacs::core::tags::scheduled_station_ae_title, kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::encoding::SH, kcenon::pacs::core::tags::study_instance_uid, kcenon::pacs::encoding::TM, and kcenon::pacs::encoding::UI.
generate_xa_dataset()
core::dicom_dataset kcenon::pacs::integration_test::generate_xa_dataset (const std::string & study_uid = "") inline
Generate a XA (X-Ray Angiographic) image dataset for testing.
Parameters
study_uid Study Instance UID (generated if empty)
Returns
DICOM dataset
Definition at line 430 of file test_fixtures.h.
{
    core::dicom_dataset ds;
    // Patient module
    ds.set_string(core::tags::patient_name, encoding::vr_type::PN, "TEST^XA^PATIENT");
    ds.set_string(core::tags::patient_id, encoding::vr_type::LO, "TESTXA001");
    ds.set_string(core::tags::patient_birth_date, encoding::vr_type::DA, "19750610");
    ds.set_string(core::tags::patient_sex, encoding::vr_type::CS, "F");
    // Study module
    ds.set_string(core::tags::study_instance_uid, encoding::vr_type::UI,
                  study_uid.empty() ? generate_uid() : study_uid);
    ds.set_string(core::tags::study_date, encoding::vr_type::DA, "20240220");
    ds.set_string(core::tags::study_time, encoding::vr_type::TM, "103000");
    ds.set_string(core::tags::accession_number, encoding::vr_type::SH, "ACCXA001");
    ds.set_string(core::tags::study_id, encoding::vr_type::SH, "STUDYXA001");
    ds.set_string(core::tags::study_description, encoding::vr_type::LO, "XA Integration Test");
    // Series module
    ds.set_string(core::tags::series_instance_uid, encoding::vr_type::UI, generate_uid());
    ds.set_string(core::tags::modality, encoding::vr_type::CS, "XA");
    ds.set_string(core::tags::series_number, encoding::vr_type::IS, "1");
    ds.set_string(core::tags::series_description, encoding::vr_type::LO, "Coronary Angio");
    // SOP Common module
    ds.set_string(core::tags::sop_class_uid, encoding::vr_type::UI, "1.2.840.10008.5.1.4.1.1.12.1");  // XA Image Storage
    ds.set_string(core::tags::sop_instance_uid, encoding::vr_type::UI, generate_uid());
    // Image module
    ds.set_numeric<uint16_t>(core::tags::rows, encoding::vr_type::US, 512);
    ds.set_numeric<uint16_t>(core::tags::columns, encoding::vr_type::US, 512);
    ds.set_numeric<uint16_t>(core::tags::bits_allocated, encoding::vr_type::US, 16);
    ds.set_numeric<uint16_t>(core::tags::bits_stored, encoding::vr_type::US, 12);
    ds.set_numeric<uint16_t>(core::tags::high_bit, encoding::vr_type::US, 11);
    ds.set_numeric<uint16_t>(core::tags::pixel_representation, encoding::vr_type::US, 0);
    ds.set_numeric<uint16_t>(core::tags::samples_per_pixel, encoding::vr_type::US, 1);
    ds.set_string(core::tags::photometric_interpretation, encoding::vr_type::CS, "MONOCHROME2");
    // XA Specific
    // Note: Using raw tag numbers if constants are not defined yet
    // Positioner Primary Angle
    ds.set_string({0x0018, 0x1510}, encoding::vr_type::DS, "0");
    // Positioner Secondary Angle
    ds.set_string({0x0018, 0x1511}, encoding::vr_type::DS, "0");
    // KVP
    ds.set_string({0x0018, 0x0060}, encoding::vr_type::DS, "80");
    // X-Ray Tube Current
    ds.set_numeric<uint16_t>({0x0018, 0x1151}, encoding::vr_type::IS, 500);
    // Exposure Time
    ds.set_numeric<uint16_t>({0x0018, 0x1150}, encoding::vr_type::IS, 100);
    // Generate minimal pixel data
    std::vector<uint16_t> pixel_data(512 * 512, 128);
    core::dicom_element pixel_elem(core::tags::pixel_data, encoding::vr_type::OW);
    pixel_elem.set_value(std::span<const uint8_t>(
        reinterpret_cast<const uint8_t*>(pixel_data.data()),
        pixel_data.size() * sizeof(uint16_t)));
    ds.insert(std::move(pixel_elem));
    return ds;
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::bits_stored, kcenon::pacs::core::tags::columns, kcenon::pacs::encoding::CS, kcenon::pacs::encoding::DA, kcenon::pacs::encoding::DS, generate_uid(), kcenon::pacs::core::tags::high_bit, kcenon::pacs::core::dicom_dataset::insert(), kcenon::pacs::encoding::IS, kcenon::pacs::encoding::LO, kcenon::pacs::core::tags::modality, kcenon::pacs::encoding::OW, kcenon::pacs::core::tags::patient_birth_date, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, kcenon::pacs::core::tags::patient_sex, kcenon::pacs::core::tags::photometric_interpretation, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::pixel_representation, kcenon::pacs::encoding::PN, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, kcenon::pacs::core::tags::series_description, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::series_number, kcenon::pacs::core::dicom_dataset::set_numeric(), kcenon::pacs::core::dicom_dataset::set_string(), kcenon::pacs::core::dicom_element::set_value(), kcenon::pacs::encoding::SH, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, kcenon::pacs::core::tags::study_date, kcenon::pacs::core::tags::study_description, kcenon::pacs::core::tags::study_id, kcenon::pacs::core::tags::study_instance_uid, kcenon::pacs::core::tags::study_time, kcenon::pacs::encoding::TM, kcenon::pacs::encoding::UI, and kcenon::pacs::encoding::US.
Referenced by TEST_CASE().
is_ci_environment()
bool kcenon::pacs::integration_test::is_ci_environment () inline
Check if running in a CI environment.
Detects CI environments by checking common CI environment variables:
CI: Generic CI variable (GitHub Actions, GitLab CI, Travis CI)
GITHUB_ACTIONS: GitHub Actions
GITLAB_CI: GitLab CI
JENKINS_URL: Jenkins
CIRCLECI: CircleCI
TRAVIS: Travis CI
Returns
true if running in CI environment
Definition at line 81 of file test_fixtures.h.
{
    static const bool ci_detected = []() {
        const char* ci_vars[] = {
            "CI", "GITHUB_ACTIONS", "GITLAB_CI",
            "JENKINS_URL", "CIRCLECI", "TRAVIS"
        };
        for (const auto* var : ci_vars) {
            if (std::getenv(var) != nullptr) {
                return true;
            }
        }
        return false;
    }();
    return ci_detected;
}
Referenced by kcenon::pacs::integration_test::test_server::check_port_listening(), dcmtk_server_ready_timeout(), kcenon::pacs::integration_test::dcmtk_tool::default_scp_startup_timeout(), default_timeout(), kcenon::pacs::integration_test::process_launcher::is_port_listening(), and server_ready_timeout().
is_port_available()
bool kcenon::pacs::integration_test::is_port_available (uint16_t port) inline
Check if a port is actually available by attempting to bind.
Parameters
port Port to check
Returns
true if port is available
Definition at line 188 of file test_fixtures.h.
{
#ifdef _WIN32
    SOCKET sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (sock == INVALID_SOCKET) {
        return false;
    }
    int reuse = 1;
    setsockopt(sock, SOL_SOCKET, SO_REUSEADDR,
               reinterpret_cast<const char*>(&reuse), sizeof(reuse));
    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    addr.sin_port = htons(port);
    bool available = (bind(sock, reinterpret_cast<sockaddr*>(&addr),
                           sizeof(addr)) == 0);
    closesocket(sock);
    return available;
#else
    int sock = socket(AF_INET, SOCK_STREAM, 0);
    if (sock < 0) {
        return false;
    }
    int reuse = 1;
    setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));
    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    addr.sin_port = htons(port);
    bool available = (bind(sock, reinterpret_cast<sockaddr*>(&addr),
                           sizeof(addr)) == 0);
    close(sock);
    return available;
#endif
}
Referenced by find_available_port().
server_ready_timeout()
std::chrono::milliseconds kcenon::pacs::integration_test::server_ready_timeout () inline
Port listening timeout for pacs_system servers (5s normal, 30s CI)
Definition at line 112 of file test_fixtures.h.
{
    return is_ci_environment()
        ? std::chrono::milliseconds{30000}
        : std::chrono::milliseconds{5000};
}
References is_ci_environment().
Referenced by kcenon::pacs::integration_test::test_server::start(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
supports_real_tcp_dicom()
bool kcenon::pacs::integration_test::supports_real_tcp_dicom () inline
Check if pacs_system supports real TCP DICOM connections.
Currently returns false because accept_worker immediately closes TCP connections after accepting them. This is a known limitation documented in accept_worker.cpp.
When real network I/O support is implemented in the association class, this function should be updated to return true.
Returns
true if real TCP DICOM connections are supported
Note
DCMTK interoperability tests require real TCP DICOM support. Until this is implemented, those tests will be skipped when this function returns false.
See also
accept_worker.cpp - "association doesn't support real network I/O yet"
Issue #XXX - Real TCP DICOM connection support (TODO: create issue)
Definition at line 148 of file test_fixtures.h.
{
    // Currently, pacs_system does not support real TCP connections
    // for DICOM protocol. The accept_worker accepts TCP connections
    // but immediately closes them without performing DICOM handshake.
    //
    // This causes DCMTK clients to receive "Peer aborted Association"
    // errors when attempting to connect.
    //
    // When real TCP support is implemented, update this to return true
    // or perform an actual connection test.
    return false;
}
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
TEST_CASE() [1/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::ct generates valid CT dataset" , "" [data_generator][ct])
Definition at line 23 of file test_data_generator_test.cpp.
{
    auto ds = test_data_generator::ct();
    SECTION("has required patient module attributes") {
        REQUIRE(ds.contains(core::tags::patient_name));
        REQUIRE(ds.contains(core::tags::patient_id));
        CHECK(ds.get_string(core::tags::patient_name) == "TEST^CT^PATIENT");
    }
    SECTION("has required study module attributes") {
        REQUIRE(ds.contains(core::tags::study_instance_uid));
        REQUIRE(ds.contains(core::tags::study_date));
    }
    SECTION("has required series module attributes") {
        REQUIRE(ds.contains(core::tags::series_instance_uid));
        REQUIRE(ds.contains(core::tags::modality));
        CHECK(ds.get_string(core::tags::modality) == "CT");
    }
    SECTION("has required SOP common attributes") {
        REQUIRE(ds.contains(core::tags::sop_class_uid));
        REQUIRE(ds.contains(core::tags::sop_instance_uid));
        CHECK(ds.get_string(core::tags::sop_class_uid) == "1.2.840.10008.5.1.4.1.1.2");
    }
    SECTION("has pixel data") {
        REQUIRE(ds.contains(core::tags::pixel_data));
    }
    SECTION("respects provided study UID") {
        std::string custom_study_uid = "1.2.3.4.5.6.7.8.9";
        auto ds2 = test_data_generator::ct(custom_study_uid);
        CHECK(ds2.get_string(core::tags::study_instance_uid) == custom_study_uid);
    }
}
References kcenon::pacs::integration_test::test_data_generator::ct(), kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, kcenon::pacs::core::tags::study_date, and kcenon::pacs::core::tags::study_instance_uid.
TEST_CASE() [2/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::current_date returns valid DICOM date" , "" [data_generator][utility])
Definition at line 365 of file test_data_generator_test.cpp.
{
    std::string date = test_data_generator::current_date();
    // DICOM DA format: YYYYMMDD (8 characters)
    CHECK(date.length() == 8);
    // Should be all digits
    CHECK(std::all_of(date.begin(), date.end(), ::isdigit));
}
References kcenon::pacs::integration_test::test_data_generator::current_date().
TEST_CASE() [3/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::current_time returns valid DICOM time" , "" [data_generator][utility])
Definition at line 375 of file test_data_generator_test.cpp.
{
    std::string time = test_data_generator::current_time();
    // DICOM TM format: HHMMSS (6 characters minimum)
    CHECK(time.length() >= 6);
    // Should be all digits
    CHECK(std::all_of(time.begin(), time.end(), ::isdigit));
}
References kcenon::pacs::integration_test::test_data_generator::current_time().
TEST_CASE() [4/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::enhanced_ct generates valid Enhanced CT dataset" , "" [data_generator][ct][enhanced])
Definition at line 177 of file test_data_generator_test.cpp.
{
    constexpr uint32_t num_frames = 50;
    auto ds = test_data_generator::enhanced_ct(num_frames);
    SECTION("has Enhanced CT SOP Class") {
        CHECK(ds.get_string(core::tags::sop_class_uid) == "1.2.840.10008.5.1.4.1.1.2.1");
    }
    SECTION("has Image Type attribute") {
        REQUIRE(ds.contains(core::tags::image_type));
    }
    SECTION("has Number of Frames") {
        constexpr core::dicom_tag number_of_frames{0x0028, 0x0008};
        CHECK(ds.get_string(number_of_frames) == std::to_string(num_frames));
    }
}
References kcenon::pacs::integration_test::test_data_generator::enhanced_ct(), kcenon::pacs::core::tags::image_type, number_of_frames, and kcenon::pacs::core::tags::sop_class_uid.
TEST_CASE() [5/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::enhanced_mr generates valid Enhanced MR dataset" , "" [data_generator][mr][enhanced])
Definition at line 195 of file test_data_generator_test.cpp.
{
    constexpr uint32_t num_frames = 25;
    auto ds = test_data_generator::enhanced_mr(num_frames);
    SECTION("has Enhanced MR SOP Class") {
        CHECK(ds.get_string(core::tags::sop_class_uid) == "1.2.840.10008.5.1.4.1.1.4.1");
    }
    SECTION("has Number of Frames") {
        constexpr core::dicom_tag number_of_frames{0x0028, 0x0008};
        CHECK(ds.get_string(number_of_frames) == std::to_string(num_frames));
    }
}
References kcenon::pacs::integration_test::test_data_generator::enhanced_mr(), number_of_frames, and kcenon::pacs::core::tags::sop_class_uid.
TEST_CASE() [6/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::generate_uid creates unique UIDs" , "" [data_generator][utility])
Definition at line 352 of file test_data_generator_test.cpp.
{
    std::string uid1 = test_data_generator::generate_uid();
    std::string uid2 = test_data_generator::generate_uid();
    std::string uid3 = test_data_generator::generate_uid();
    CHECK(uid1 != uid2);
    CHECK(uid2 != uid3);
    CHECK(uid1 != uid3);
    // All should start with the default root
    CHECK(uid1.find("1.2.826.0.1.3680043.9.9999") == 0);
}
References kcenon::pacs::integration_test::test_data_generator::generate_uid().
TEST_CASE() [7/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::invalid creates datasets with specific errors" , "" [data_generator][edge_case][invalid])
Definition at line 318 of file test_data_generator_test.cpp.
{
    SECTION("missing_sop_class_uid") {
        auto ds = test_data_generator::invalid(invalid_dataset_type::missing_sop_class_uid);
        CHECK_FALSE(ds.contains(core::tags::sop_class_uid));
    }
    SECTION("missing_sop_instance_uid") {
        auto ds = test_data_generator::invalid(invalid_dataset_type::missing_sop_instance_uid);
        CHECK_FALSE(ds.contains(core::tags::sop_instance_uid));
    }
    SECTION("missing_patient_id") {
        auto ds = test_data_generator::invalid(invalid_dataset_type::missing_patient_id);
        CHECK_FALSE(ds.contains(core::tags::patient_id));
    }
    SECTION("missing_study_instance_uid") {
        auto ds = test_data_generator::invalid(invalid_dataset_type::missing_study_instance_uid);
        CHECK_FALSE(ds.contains(core::tags::study_instance_uid));
    }
    SECTION("corrupted_pixel_data") {
        auto ds = test_data_generator::invalid(invalid_dataset_type::corrupted_pixel_data);
        auto* pixel_elem = ds.get(core::tags::pixel_data);
        REQUIRE(pixel_elem != nullptr);
        // Pixel data should be much smaller than expected
        CHECK(pixel_elem->length() < 1000);
    }
}
References corrupted_pixel_data, kcenon::pacs::integration_test::test_data_generator::invalid(), missing_patient_id, missing_sop_class_uid, missing_sop_instance_uid, missing_study_instance_uid, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, and kcenon::pacs::core::tags::study_instance_uid.
TEST_CASE() [8/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::large creates appropriately sized dataset" , "" [data_generator][edge_case])
Definition at line 268 of file test_data_generator_test.cpp.
{
    constexpr size_t target_mb = 2;
    auto ds = test_data_generator::large(target_mb);
    auto* pixel_elem = ds.get(core::tags::pixel_data);
    REQUIRE(pixel_elem != nullptr);
    // Check that pixel data size is approximately correct
    // (may not be exact due to square dimension rounding)
    size_t target_bytes = target_mb * 1024 * 1024;
    size_t actual_size = pixel_elem->length();
    // Allow for some variance due to dimension rounding
    CHECK(actual_size >= target_bytes / 2);
    CHECK(actual_size <= target_bytes * 2);
}
References kcenon::pacs::integration_test::test_data_generator::large(), and kcenon::pacs::core::tags::pixel_data.
TEST_CASE() [9/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::mr generates valid MR dataset" , "" [data_generator][mr])
Definition at line 60 of file test_data_generator_test.cpp.
{
    auto ds = test_data_generator::mr();
    REQUIRE(ds.contains(core::tags::modality));
    CHECK(ds.get_string(core::tags::modality) == "MR");
    CHECK(ds.get_string(core::tags::sop_class_uid) == "1.2.840.10008.5.1.4.1.1.4");
    REQUIRE(ds.contains(core::tags::pixel_data));
}
References kcenon::pacs::core::tags::modality, kcenon::pacs::integration_test::test_data_generator::mr(), kcenon::pacs::core::tags::pixel_data, and kcenon::pacs::core::tags::sop_class_uid.
TEST_CASE() [10/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::patient_journey creates multi-modal study" , "" [data_generator][workflow])
Definition at line 213 of file test_data_generator_test.cpp.
{
    auto study = test_data_generator::patient_journey("PATIENT001", {"CT", "MR", "XA"});
    SECTION("has consistent patient information") {
        CHECK(study.patient_id == "PATIENT001");
        CHECK_FALSE(study.study_uid.empty());
        for (const auto& ds : study.datasets) {
            CHECK(ds.get_string(core::tags::patient_id) == "PATIENT001");
            CHECK(ds.get_string(core::tags::study_instance_uid) == study.study_uid);
        }
    }
    SECTION("contains all requested modalities") {
        CHECK(study.datasets.size() == 3);
        auto ct_datasets = study.get_by_modality("CT");
        auto mr_datasets = study.get_by_modality("MR");
        auto xa_datasets = study.get_by_modality("XA");
        CHECK(ct_datasets.size() == 1);
        CHECK(mr_datasets.size() == 1);
        CHECK(xa_datasets.size() == 1);
    }
    SECTION("each modality has unique series UID") {
        CHECK(study.series_count() == 3);
    }
}
References kcenon::pacs::core::tags::patient_id, kcenon::pacs::integration_test::test_data_generator::patient_journey(), and kcenon::pacs::core::tags::study_instance_uid.
TEST_CASE() [11/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::unicode creates dataset with Unicode characters" , "" [data_generator][edge_case][unicode])
Definition at line 285 of file test_data_generator_test.cpp.
{
    auto ds = test_data_generator::unicode();
    SECTION("has specific character set") {
        REQUIRE(ds.contains(core::tags::specific_character_set));
    }
    SECTION("has patient name with Korean characters") {
        REQUIRE(ds.contains(core::tags::patient_name));
        // The patient name contains Korean characters
        auto patient_name = ds.get_string(core::tags::patient_name);
        CHECK_FALSE(patient_name.empty());
    }
}
References kcenon::pacs::core::tags::patient_name, kcenon::pacs::core::tags::specific_character_set, and kcenon::pacs::integration_test::test_data_generator::unicode().
TEST_CASE() [12/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::us generates valid US dataset" , "" [data_generator][us])
Definition at line 102 of file test_data_generator_test.cpp.
{
    auto ds = test_data_generator::us();
    REQUIRE(ds.contains(core::tags::modality));
    CHECK(ds.get_string(core::tags::modality) == "US");
    SECTION("has US SOP Class UID") {
        CHECK(ds.get_string(core::tags::sop_class_uid) ==
              std::string(services::sop_classes::us_image_storage_uid));
    }
    SECTION("has 8-bit pixel data") {
        auto bits_allocated = ds.get_numeric<uint16_t>(core::tags::bits_allocated);
        REQUIRE(bits_allocated.has_value());
        CHECK(bits_allocated.value() == 8);
    }
}
References kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::integration_test::test_data_generator::us(), and kcenon::pacs::services::sop_classes::us_image_storage_uid.
TEST_CASE() [13/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::us_cine generates valid multi-frame US dataset" , "" [data_generator][us][multiframe])
Definition at line 152 of file test_data_generator_test.cpp.
{
    constexpr uint32_t num_frames = 30;
    auto ds = test_data_generator::us_cine(num_frames);
    SECTION("has US Multi-frame SOP Class") {
        CHECK(ds.get_string(core::tags::sop_class_uid) ==
              std::string(services::sop_classes::us_multiframe_image_storage_uid));
    }
    SECTION("has Number of Frames attribute") {
        constexpr core::dicom_tag number_of_frames{0x0028, 0x0008};
        REQUIRE(ds.contains(number_of_frames));
        CHECK(ds.get_string(number_of_frames) == std::to_string(num_frames));
    }
    SECTION("has 8-bit pixel data with multiple frames") {
        auto* pixel_elem = ds.get(core::tags::pixel_data);
        REQUIRE(pixel_elem != nullptr);
        // 640x480 * 1 byte * 30 frames = 9,216,000 bytes
        size_t expected_size = 640 * 480 * 1 * num_frames;
        CHECK(pixel_elem->length() == expected_size);
    }
}
References number_of_frames, kcenon::pacs::core::tags::pixel_data, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::integration_test::test_data_generator::us_cine(), and kcenon::pacs::services::sop_classes::us_multiframe_image_storage_uid.
TEST_CASE() [14/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::with_private_tags includes private tags" , "" [data_generator][edge_case][private])
Definition at line 300 of file test_data_generator_test.cpp.
{
    auto ds = test_data_generator::with_private_tags("MY_PRIVATE_CREATOR");
    SECTION("has private creator tag") {
        constexpr core::dicom_tag private_creator_tag{0x0011, 0x0010};
        REQUIRE(ds.contains(private_creator_tag));
        CHECK(ds.get_string(private_creator_tag) == "MY_PRIVATE_CREATOR");
    }
    SECTION("has private data tags") {
        constexpr core::dicom_tag private_data_1{0x0011, 0x1001};
        constexpr core::dicom_tag private_data_2{0x0011, 0x1002};
        REQUIRE(ds.contains(private_data_1));
        REQUIRE(ds.contains(private_data_2));
    }
}
References kcenon::pacs::integration_test::test_data_generator::with_private_tags().
TEST_CASE() [15/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::worklist generates valid worklist item" , "" [data_generator][worklist])
Definition at line 243 of file test_data_generator_test.cpp.
{
    auto ds = test_data_generator::worklist("WL001", "MR");
    SECTION("has patient attributes") {
        REQUIRE(ds.contains(core::tags::patient_name));
        CHECK(ds.get_string(core::tags::patient_id) == "WL001");
    }
    SECTION("has scheduled procedure step attributes") {
        REQUIRE(ds.contains(core::tags::scheduled_procedure_step_start_date));
        REQUIRE(ds.contains(core::tags::scheduled_station_ae_title));
        CHECK(ds.get_string(core::tags::modality) == "MR");
    }
    SECTION("has requested procedure attributes") {
        REQUIRE(ds.contains(core::tags::requested_procedure_id));
        REQUIRE(ds.contains(core::tags::accession_number));
        REQUIRE(ds.contains(core::tags::study_instance_uid));
    }
}
References kcenon::pacs::core::tags::accession_number, kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::patient_id, kcenon::pacs::core::tags::patient_name, kcenon::pacs::core::tags::requested_procedure_id, kcenon::pacs::core::tags::scheduled_procedure_step_start_date, kcenon::pacs::core::tags::scheduled_station_ae_title, kcenon::pacs::core::tags::study_instance_uid, and kcenon::pacs::integration_test::test_data_generator::worklist().
TEST_CASE() [16/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::xa generates valid XA dataset" , "" [data_generator][xa])
Definition at line 69 of file test_data_generator_test.cpp.
{
    auto ds = test_data_generator::xa();
    REQUIRE(ds.contains(core::tags::modality));
    CHECK(ds.get_string(core::tags::modality) == "XA");
    SECTION("has XA SOP Class UID") {
        CHECK(ds.get_string(core::tags::sop_class_uid) ==
              std::string(services::sop_classes::xa_image_storage_uid));
    }
    SECTION("has XA-specific attributes") {
        constexpr core::dicom_tag positioner_primary_angle{0x0018, 0x1510};
        constexpr core::dicom_tag kvp{0x0018, 0x0060};
        REQUIRE(ds.contains(positioner_primary_angle));
        REQUIRE(ds.contains(kvp));
    }
    SECTION("has larger image dimensions than CT/MR") {
        REQUIRE(ds.contains(core::tags::rows));
        REQUIRE(ds.contains(core::tags::columns));
        auto rows = ds.get_numeric<uint16_t>(core::tags::rows);
        auto cols = ds.get_numeric<uint16_t>(core::tags::columns);
        REQUIRE(rows.has_value());
        REQUIRE(cols.has_value());
        CHECK(rows.value() == 512);
        CHECK(cols.value() == 512);
    }
}
References kcenon::pacs::core::tags::columns, kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::integration_test::test_data_generator::xa(), and kcenon::pacs::services::sop_classes::xa_image_storage_uid.
TEST_CASE() [17/17]
kcenon::pacs::integration_test::TEST_CASE ("test_data_generator::xa_cine generates valid multi-frame XA dataset" , "" [data_generator][xa][multiframe])
Definition at line 124 of file test_data_generator_test.cpp.
{
    constexpr uint32_t num_frames = 15;
    auto ds = test_data_generator::xa_cine(num_frames);
    SECTION("has Number of Frames attribute") {
        constexpr core::dicom_tag number_of_frames{0x0028, 0x0008};
        REQUIRE(ds.contains(number_of_frames));
        CHECK(ds.get_string(number_of_frames) == std::to_string(num_frames));
    }
    SECTION("has XA-specific cine attributes") {
        constexpr core::dicom_tag cine_rate{0x0018, 0x0040};
        constexpr core::dicom_tag frame_time{0x0018, 0x1063};
        REQUIRE(ds.contains(cine_rate));
        REQUIRE(ds.contains(frame_time));
    }
    SECTION("has appropriately sized pixel data") {
        auto* pixel_elem = ds.get(core::tags::pixel_data);
        REQUIRE(pixel_elem != nullptr);
        // 512x512 * 2 bytes * 15 frames = 7,864,320 bytes
        size_t expected_size = 512 * 512 * 2 * num_frames;
        CHECK(pixel_elem->length() == expected_size);
    }
}
References number_of_frames, kcenon::pacs::core::tags::pixel_data, and kcenon::pacs::integration_test::test_data_generator::xa_cine().
wait_for() [1/2]
template<typename Func > bool kcenon::pacs::integration_test::wait_for (Func && condition)
Wait for a condition with default timeout.
Parameters
condition Condition function
Returns
true if condition became true before timeout
Definition at line 301 of file test_fixtures.h.
{
    return wait_for(std::forward<Func>(condition), default_timeout());
}
References default_timeout(), and wait_for().
wait_for() [2/2]
template<typename Func > bool kcenon::pacs::integration_test::wait_for (Func && condition, std::chrono::milliseconds timeout, std::chrono::milliseconds interval = std::chrono::milliseconds{50})
Wait for a condition with timeout.
Parameters
condition Condition function
timeout Maximum wait time (uses default_timeout() if not specified)
interval Check interval
Returns
true if condition became true before timeout
Definition at line 279 of file test_fixtures.h.
                                                          {50}) {
    auto start = std::chrono::steady_clock::now();
    while (!condition()) {
        auto elapsed = std::chrono::steady_clock::now() - start;
        if (elapsed >= timeout) {
            return false;
        }
        std::this_thread::sleep_for(interval);
    }
    return true;
}
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and wait_for().
Variable Documentation
default_test_port
uint16_t kcenon::pacs::integration_test::default_test_port = 41104 constexpr
Default test port range start (use high ports to avoid conflicts)
Definition at line 102 of file test_fixtures.h.
test_scp_ae_title
const char* kcenon::pacs::integration_test::test_scp_ae_title = "TEST_SCP" constexpr
Default AE titles.
Definition at line 162 of file test_fixtures.h.
test_scu_ae_title
const char* kcenon::pacs::integration_test::test_scu_ae_title = "TEST_SCU" constexpr
Definition at line 163 of file test_fixtures.h.