PACS System: kcenon::pacs::di::test Namespace Reference
kcenon::pacs::di::test Namespace Reference
Classes
class MockNetwork
Mock network service for testing.
class MockStorage
class TestContainerBuilder
Functions
std::shared_ptr< kcenon::common::di::service_container > create_test_container ()
Create a test container with all mock services.
void register_mock_storage (kcenon::common::di::IServiceContainer &container, std::shared_ptr< MockStorage > mock)
Register mock storage with a container.
void register_mock_network (kcenon::common::di::IServiceContainer &container, std::shared_ptr< MockNetwork > mock)
Register mock network with a container.
Function Documentation
create_test_container()
std::shared_ptr< kcenon::common::di::service_container > kcenon::pacs::di::test::create_test_container () inline nodiscard
Create a test container with all mock services.
Returns
Shared pointer to container with mock services
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h.
Definition at line 365 of file test_support.h.
{
    return TestContainerBuilder()
        .with_mock_storage()
        .with_mock_network()
        .build();
}
References kcenon::pacs::di::test::TestContainerBuilder::build(), kcenon::pacs::di::test::TestContainerBuilder::with_mock_network(), and kcenon::pacs::di::test::TestContainerBuilder::with_mock_storage().
register_mock_network()
void kcenon::pacs::di::test::register_mock_network (kcenon::common::di::IServiceContainer & container, std::shared_ptr< MockNetwork > mock) inline
Register mock network with a container.
Parameters
container The container to register with
mock The mock network instance
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h.
Definition at line 390 of file test_support.h.
{
    container.register_instance<IDicomNetwork>(std::move(mock));
}
register_mock_storage()
void kcenon::pacs::di::test::register_mock_storage (kcenon::common::di::IServiceContainer & container, std::shared_ptr< MockStorage > mock) inline
Register mock storage with a container.
Parameters
container The container to register with
mock The mock storage instance
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/di/test_support.h.
Definition at line 378 of file test_support.h.
{
    container.register_instance<IDicomStorage>(std::move(mock));
}