PACS System: kcenon::pacs::services::validation Namespace Reference
kcenon::pacs::services::validation Namespace Reference
Namespaces
namespace ct_processing_tags
namespace ct_tags
namespace dx_tags
namespace heightmap_seg_tags
namespace label_map_seg_tags
namespace mg_tags
namespace mr_tags
namespace nm_tags
namespace ophthalmic_iod_tags
namespace pet_tags
namespace pmap_iod_tags
namespace rt_tags
namespace seg_tags
namespace sr_tags
namespace waveform_tags
namespace wsi_iod_tags
namespace xa_tags
Classes
class ct_iod_validator
class ct_processing_iod_validator
struct ct_processing_validation_options
Options for CT For Processing IOD validation.
struct ct_validation_options
Options for CT IOD validation.
class dx_iod_validator
struct dx_validation_options
Options for DX IOD validation.
class heightmap_seg_iod_validator
struct heightmap_seg_validation_options
Options for Heightmap Segmentation IOD validation.
class label_map_seg_iod_validator
struct label_map_seg_validation_options
Options for Label Map Segmentation IOD validation.
class mg_iod_validator
struct mg_validation_options
Options for Mammography IOD validation.
class mr_iod_validator
struct mr_validation_options
Options for MR IOD validation.
class nm_iod_validator
struct nm_validation_options
Options for NM IOD validation.
class ophthalmic_iod_validator
struct ophthalmic_validation_options
Options for Ophthalmic IOD validation.
class parametric_map_iod_validator
class pet_iod_validator
struct pet_validation_options
Options for PET IOD validation.
struct pmap_validation_options
Options for Parametric Map IOD validation.
class rt_dose_iod_validator
Validator for RT Dose IODs.
class rt_iod_validator
Unified validator for all RT IODs.
class rt_plan_iod_validator
Validator for RT Plan IODs.
class rt_structure_set_iod_validator
Validator for RT Structure Set IODs.
struct rt_validation_options
Options for RT IOD validation.
class seg_iod_validator
struct seg_validation_options
Options for SEG IOD validation.
class sr_iod_validator
struct sr_validation_options
Options for SR IOD validation.
class us_iod_validator
struct us_validation_options
Options for US IOD validation.
struct validation_finding
Single validation finding.
struct validation_result
Result of IOD validation.
class waveform_ps_iod_validator
Validates Waveform Presentation State and Annotation IODs.
struct waveform_ps_validation_options
Options for Waveform Presentation State / Annotation IOD validation.
class wsi_iod_validator
struct wsi_validation_options
Options for WSI IOD validation.
class xa_iod_validator
struct xa_validation_options
Options for XA IOD validation.
Enumerations
enum class validation_severity { error , warning , info }
Severity level of validation findings.
Functions
validation_result validate_ct_iod (const core::dicom_dataset &dataset)
Validate a CT dataset with default options.
bool is_valid_ct_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid CT image.
validation_result validate_ct_processing_iod (const core::dicom_dataset &dataset)
Validate a CT For Processing dataset with default options.
bool is_valid_ct_processing_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid CT For Processing image.
validation_result validate_dx_iod (const core::dicom_dataset &dataset)
Validate a DX dataset with default options.
bool is_valid_dx_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid DX image.
bool is_for_presentation_dx (const core::dicom_dataset &dataset)
Check if dataset is a For Presentation DX image.
bool is_for_processing_dx (const core::dicom_dataset &dataset)
Check if dataset is a For Processing DX image.
validation_result validate_heightmap_seg_iod (const core::dicom_dataset &dataset)
Validate a Heightmap Segmentation dataset with default options.
bool is_valid_heightmap_seg_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid Heightmap Segmentation object.
bool is_heightmap_segmentation (const core::dicom_dataset &dataset)
Check if dataset is a heightmap segmentation.
validation_result validate_label_map_seg_iod (const core::dicom_dataset &dataset)
Validate a Label Map Segmentation dataset with default options.
bool is_valid_label_map_seg_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid Label Map Segmentation object.
bool is_label_map_segmentation (const core::dicom_dataset &dataset)
Check if dataset is a label map segmentation.
validation_result validate_mg_iod (const core::dicom_dataset &dataset)
Validate a mammography dataset with default options.
bool is_valid_mg_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid mammography image.
bool is_for_presentation_mg (const core::dicom_dataset &dataset)
Check if dataset is a For Presentation mammography image.
bool is_for_processing_mg (const core::dicom_dataset &dataset)
Check if dataset is a For Processing mammography image.
bool has_breast_implant (const core::dicom_dataset &dataset)
Check if dataset indicates breast implant presence.
bool is_screening_mammogram (const core::dicom_dataset &dataset)
Check if dataset is a screening mammogram.
validation_result validate_mr_iod (const core::dicom_dataset &dataset)
Validate an MR dataset with default options.
bool is_valid_mr_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid MR image.
validation_result validate_nm_iod (const core::dicom_dataset &dataset)
Validate a NM dataset with default options.
bool is_valid_nm_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid NM image.
validation_result validate_ophthalmic_iod (const core::dicom_dataset &dataset)
Validate an ophthalmic dataset with default options.
bool is_valid_ophthalmic_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid ophthalmic image.
validation_result validate_parametric_map_iod (const core::dicom_dataset &dataset)
Validate a Parametric Map dataset with default options.
bool is_valid_parametric_map_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid Parametric Map object.
validation_result validate_pet_iod (const core::dicom_dataset &dataset)
Validate a PET dataset with default options.
bool is_valid_pet_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid PET image.
validation_result validate_rt_plan_iod (const core::dicom_dataset &dataset)
Validate an RT Plan dataset with default options.
validation_result validate_rt_dose_iod (const core::dicom_dataset &dataset)
Validate an RT Dose dataset with default options.
validation_result validate_rt_structure_set_iod (const core::dicom_dataset &dataset)
Validate an RT Structure Set dataset with default options.
validation_result validate_rt_iod (const core::dicom_dataset &dataset)
Validate any RT dataset (auto-detects type) with default options.
bool is_valid_rt_plan_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid RT Plan.
bool is_valid_rt_dose_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid RT Dose.
bool is_valid_rt_structure_set_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid RT Structure Set.
bool is_valid_rt_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid RT object (any type)
validation_result validate_seg_iod (const core::dicom_dataset &dataset)
Validate a SEG dataset with default options.
bool is_valid_seg_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid SEG object.
bool is_binary_segmentation (const core::dicom_dataset &dataset)
Check if dataset is binary segmentation.
bool is_fractional_segmentation (const core::dicom_dataset &dataset)
Check if dataset is fractional segmentation.
size_t get_segment_count (const core::dicom_dataset &dataset)
Get segment count from dataset.
validation_result validate_sr_iod (const core::dicom_dataset &dataset)
Validate an SR dataset with default options.
bool is_valid_sr_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid SR document.
bool is_sr_complete (const core::dicom_dataset &dataset)
Check if SR document is complete.
bool is_sr_verified (const core::dicom_dataset &dataset)
Check if SR document is verified.
size_t get_content_item_count (const core::dicom_dataset &dataset)
Get content item count from dataset.
std::string get_sr_document_title (const core::dicom_dataset &dataset)
Get SR document title from Concept Name Code Sequence.
validation_result validate_us_iod (const core::dicom_dataset &dataset)
Validate a US dataset with default options.
bool is_valid_us_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid US image.
validation_result validate_wsi_iod (const core::dicom_dataset &dataset)
Validate a WSI dataset with default options.
bool is_valid_wsi_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid WSI image.
validation_result validate_xa_iod (const core::dicom_dataset &dataset)
Validate an XA dataset with default options.
bool is_valid_xa_dataset (const core::dicom_dataset &dataset)
Quick check if a dataset is a valid XA image.
bool has_qca_calibration (const core::dicom_dataset &dataset)
Check if dataset has valid QCA calibration data.
Variables
static constexpr std::string_view heightmap_segmentation_storage_uid
static constexpr std::string_view label_map_segmentation_storage_uid
Enumeration Type Documentation
validation_severity
enum class kcenon::pacs::services::validation::validation_severity strong
Severity level of validation findings.
Enumerator
error
Critical - IOD is non-compliant.
warning
Non-critical - IOD may have issues.
info
Informational - suggestion for improvement.
Definition at line 39 of file us_iod_validator.h.
{
    error,
    warning,
    info
};
Function Documentation
get_content_item_count()
size_t kcenon::pacs::services::validation::get_content_item_count (const core::dicom_dataset & dataset) nodiscard
Get content item count from dataset.
Parameters
dataset The dataset to check
Returns
Number of content items at root level, or 0 if cannot be determined
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/sr_iod_validator.h.
Definition at line 986 of file sr_iod_validator.cpp.
{
    constexpr dicom_tag content_sequence{0x0040, 0xA730};
    const auto* element = dataset.get(content_sequence);
    if (element && element->is_sequence()) {
        return element->sequence_items().size();
    }
    return 0;
}
References kcenon::pacs::core::dicom_dataset::get().
get_segment_count()
size_t kcenon::pacs::services::validation::get_segment_count (const core::dicom_dataset & dataset) nodiscard
Get segment count from dataset.
Parameters
dataset The dataset to check
Returns
Number of segments, or 0 if cannot be determined
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/seg_iod_validator.h.
Definition at line 714 of file seg_iod_validator.cpp.
{
    constexpr dicom_tag segment_sequence{0x0062, 0x0002};
    const auto* element = dataset.get(segment_sequence);
    if (element && element->is_sequence()) {
        return element->sequence_items().size();
    }
    return 0;
}
References kcenon::pacs::core::dicom_dataset::get().
get_sr_document_title()
std::string kcenon::pacs::services::validation::get_sr_document_title (const core::dicom_dataset & dataset) nodiscard
Get SR document title from Concept Name Code Sequence.
Parameters
dataset The dataset to check
Returns
Document title code meaning, or empty string if not found
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/sr_iod_validator.h.
Definition at line 995 of file sr_iod_validator.cpp.
{
    constexpr dicom_tag concept_name_code_sequence{0x0040, 0xA043};
    constexpr dicom_tag code_meaning{0x0008, 0x0104};
    const auto* element = dataset.get(concept_name_code_sequence);
    if (element && element->is_sequence() && !element->sequence_items().empty()) {
        const auto& item = element->sequence_items()[0];
        if (item.contains(code_meaning)) {
            return item.get_string(code_meaning);
        }
    }
    return "";
}
References kcenon::pacs::core::dicom_dataset::get().
has_breast_implant()
bool kcenon::pacs::services::validation::has_breast_implant (const core::dicom_dataset & dataset) nodiscard
Check if dataset indicates breast implant presence.
Parameters
dataset The dataset to check
Returns
true if breast implant is present according to the dataset
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/mg_iod_validator.h.
Definition at line 1024 of file mg_iod_validator.cpp.
{
    constexpr dicom_tag breast_implant_present{0x0028, 0x1300};
    if (!dataset.contains(breast_implant_present)) {
        return false;
    }
    auto value = dataset.get_string(breast_implant_present);
    return value == "YES";
}
References kcenon::pacs::core::dicom_dataset::contains(), and kcenon::pacs::core::dicom_dataset::get_string().
has_qca_calibration()
bool kcenon::pacs::services::validation::has_qca_calibration (const core::dicom_dataset & dataset) nodiscard
Check if dataset has valid QCA calibration data.
Parameters
dataset The dataset to check
Returns
true if the dataset has complete calibration for QCA
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/xa_iod_validator.h.
Definition at line 611 of file xa_iod_validator.cpp.
{
    // QCA requires ImagerPixelSpacing, SID, and SOD
    if (!dataset.contains(xa_tags::imager_pixel_spacing)) return false;
    if (!dataset.contains(xa_tags::distance_source_to_detector)) return false;
    if (!dataset.contains(xa_tags::distance_source_to_patient)) return false;
    // Validate SID > SOD
    auto sid = dataset.get_numeric<double>(xa_tags::distance_source_to_detector);
    auto sod = dataset.get_numeric<double>(xa_tags::distance_source_to_patient);
    if (!sid || !sod || *sid <= *sod) return false;
    return true;
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::services::validation::xa_tags::distance_source_to_detector, kcenon::pacs::services::validation::xa_tags::distance_source_to_patient, kcenon::pacs::core::dicom_dataset::get_numeric(), and kcenon::pacs::services::validation::xa_tags::imager_pixel_spacing.
is_binary_segmentation()
bool kcenon::pacs::services::validation::is_binary_segmentation (const core::dicom_dataset & dataset) nodiscard
Check if dataset is binary segmentation.
Parameters
dataset The dataset to check
Returns
true if Segmentation Type is BINARY
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/seg_iod_validator.h.
Definition at line 698 of file seg_iod_validator.cpp.
{
    constexpr dicom_tag segmentation_type{0x0062, 0x0001};
    if (!dataset.contains(segmentation_type)) {
        return false;
    }
    return dataset.get_string(segmentation_type) == "BINARY";
}
References kcenon::pacs::core::dicom_dataset::contains(), and kcenon::pacs::core::dicom_dataset::get_string().
is_for_presentation_dx()
bool kcenon::pacs::services::validation::is_for_presentation_dx (const core::dicom_dataset & dataset) nodiscard
Check if dataset is a For Presentation DX image.
Examines the SOP Class UID to determine the image type.
Parameters
dataset The dataset to check
Returns
true if this is a For Presentation DX image
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/dx_iod_validator.h.
Definition at line 684 of file dx_iod_validator.cpp.
{
    if (!dataset.contains(tags::sop_class_uid)) {
        return false;
    }
    auto sop_class = dataset.get_string(tags::sop_class_uid);
    return sop_classes::is_dx_for_presentation_sop_class(sop_class);
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_dx_for_presentation_sop_class(), and kcenon::pacs::core::tags::sop_class_uid.
is_for_presentation_mg()
bool kcenon::pacs::services::validation::is_for_presentation_mg (const core::dicom_dataset & dataset) nodiscard
Check if dataset is a For Presentation mammography image.
Examines the SOP Class UID to determine the image type.
Parameters
dataset The dataset to check
Returns
true if this is a For Presentation mammography image
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/mg_iod_validator.h.
Definition at line 1008 of file mg_iod_validator.cpp.
{
    if (!dataset.contains(tags::sop_class_uid)) {
        return false;
    }
    auto sop_class = dataset.get_string(tags::sop_class_uid);
    return is_mg_for_presentation_sop_class(sop_class);
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_mg_for_presentation_sop_class(), and kcenon::pacs::core::tags::sop_class_uid.
is_for_processing_dx()
bool kcenon::pacs::services::validation::is_for_processing_dx (const core::dicom_dataset & dataset) nodiscard
Check if dataset is a For Processing DX image.
Examines the SOP Class UID to determine the image type.
Parameters
dataset The dataset to check
Returns
true if this is a For Processing DX image
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/dx_iod_validator.h.
Definition at line 692 of file dx_iod_validator.cpp.
{
    if (!dataset.contains(tags::sop_class_uid)) {
        return false;
    }
    auto sop_class = dataset.get_string(tags::sop_class_uid);
    return sop_classes::is_dx_for_processing_sop_class(sop_class);
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_dx_for_processing_sop_class(), and kcenon::pacs::core::tags::sop_class_uid.
is_for_processing_mg()
bool kcenon::pacs::services::validation::is_for_processing_mg (const core::dicom_dataset & dataset) nodiscard
Check if dataset is a For Processing mammography image.
Examines the SOP Class UID to determine the image type.
Parameters
dataset The dataset to check
Returns
true if this is a For Processing mammography image
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/mg_iod_validator.h.
Definition at line 1016 of file mg_iod_validator.cpp.
{
    if (!dataset.contains(tags::sop_class_uid)) {
        return false;
    }
    auto sop_class = dataset.get_string(tags::sop_class_uid);
    return is_mg_for_processing_sop_class(sop_class);
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_mg_for_processing_sop_class(), and kcenon::pacs::core::tags::sop_class_uid.
is_fractional_segmentation()
bool kcenon::pacs::services::validation::is_fractional_segmentation (const core::dicom_dataset & dataset) nodiscard
Check if dataset is fractional segmentation.
Parameters
dataset The dataset to check
Returns
true if Segmentation Type is FRACTIONAL
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/seg_iod_validator.h.
Definition at line 706 of file seg_iod_validator.cpp.
{
    constexpr dicom_tag segmentation_type{0x0062, 0x0001};
    if (!dataset.contains(segmentation_type)) {
        return false;
    }
    return dataset.get_string(segmentation_type) == "FRACTIONAL";
}
References kcenon::pacs::core::dicom_dataset::contains(), and kcenon::pacs::core::dicom_dataset::get_string().
is_heightmap_segmentation()
bool kcenon::pacs::services::validation::is_heightmap_segmentation (const core::dicom_dataset & dataset) nodiscard
Check if dataset is a heightmap segmentation.
Parameters
dataset The dataset to check
Returns
true if Segmentation Type is HEIGHTMAP
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/heightmap_seg_iod_validator.h.
Definition at line 660 of file heightmap_seg_iod_validator.cpp.
{
    constexpr dicom_tag segmentation_type{0x0062, 0x0001};
    if (!dataset.contains(segmentation_type)) {
        return false;
    }
    return dataset.get_string(segmentation_type) == "HEIGHTMAP";
}
References kcenon::pacs::core::dicom_dataset::contains(), and kcenon::pacs::core::dicom_dataset::get_string().
is_label_map_segmentation()
bool kcenon::pacs::services::validation::is_label_map_segmentation (const core::dicom_dataset & dataset) nodiscard
Check if dataset is a label map segmentation.
Parameters
dataset The dataset to check
Returns
true if Segmentation Type is LABELMAP
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/label_map_seg_iod_validator.h.
Definition at line 695 of file label_map_seg_iod_validator.cpp.
{
    constexpr dicom_tag segmentation_type{0x0062, 0x0001};
    if (!dataset.contains(segmentation_type)) {
        return false;
    }
    return dataset.get_string(segmentation_type) == "LABELMAP";
}
References kcenon::pacs::core::dicom_dataset::contains(), and kcenon::pacs::core::dicom_dataset::get_string().
is_screening_mammogram()
bool kcenon::pacs::services::validation::is_screening_mammogram (const core::dicom_dataset & dataset) nodiscard
Check if dataset is a screening mammogram.
Determines if the image is part of a standard screening exam based on view position (CC or MLO).
Parameters
dataset The dataset to check
Returns
true if this appears to be a screening mammogram
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/mg_iod_validator.h.
Definition at line 1033 of file mg_iod_validator.cpp.
{
    constexpr dicom_tag view_position{0x0018, 0x5101};
    if (!dataset.contains(view_position)) {
        return false;
    }
    auto view_str = dataset.get_string(view_position);
    auto view = parse_mg_view_position(view_str);
    return is_screening_view(view);
}
References kcenon::pacs::core::dicom_dataset::contains(), kcenon::pacs::core::dicom_dataset::get_string(), kcenon::pacs::services::sop_classes::is_screening_view(), and kcenon::pacs::services::sop_classes::parse_mg_view_position().
is_sr_complete()
bool kcenon::pacs::services::validation::is_sr_complete (const core::dicom_dataset & dataset) nodiscard
Check if SR document is complete.
Parameters
dataset The dataset to check
Returns
true if Completion Flag is COMPLETE
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/sr_iod_validator.h.
Definition at line 970 of file sr_iod_validator.cpp.
{
    constexpr dicom_tag completion_flag{0x0040, 0xA491};
    if (!dataset.contains(completion_flag)) {
        return false;
    }
    return dataset.get_string(completion_flag) == "COMPLETE";
}
References kcenon::pacs::core::dicom_dataset::contains(), and kcenon::pacs::core::dicom_dataset::get_string().
is_sr_verified()
bool kcenon::pacs::services::validation::is_sr_verified (const core::dicom_dataset & dataset) nodiscard
Check if SR document is verified.
Parameters
dataset The dataset to check
Returns
true if Verification Flag is VERIFIED
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/sr_iod_validator.h.
Definition at line 978 of file sr_iod_validator.cpp.
{
    constexpr dicom_tag verification_flag{0x0040, 0xA493};
    if (!dataset.contains(verification_flag)) {
        return false;
    }
    return dataset.get_string(verification_flag) == "VERIFIED";
}
References kcenon::pacs::core::dicom_dataset::contains(), and kcenon::pacs::core::dicom_dataset::get_string().
is_valid_ct_dataset()
bool kcenon::pacs::services::validation::is_valid_ct_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid CT image.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic CT IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ct_iod_validator.h.
Definition at line 459 of file ct_iod_validator.cpp.
{
    ct_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::ct_iod_validator::quick_check().
is_valid_ct_processing_dataset()
bool kcenon::pacs::services::validation::is_valid_ct_processing_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid CT For Processing image.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ct_processing_iod_validator.h.
Definition at line 480 of file ct_processing_iod_validator.cpp.
{
    ct_processing_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::ct_processing_iod_validator::quick_check().
is_valid_dx_dataset()
bool kcenon::pacs::services::validation::is_valid_dx_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid DX image.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic DX IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/dx_iod_validator.h.
Definition at line 679 of file dx_iod_validator.cpp.
{
    dx_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::dx_iod_validator::quick_check().
is_valid_heightmap_seg_dataset()
bool kcenon::pacs::services::validation::is_valid_heightmap_seg_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid Heightmap Segmentation object.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic Heightmap Segmentation IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/heightmap_seg_iod_validator.h.
Definition at line 655 of file heightmap_seg_iod_validator.cpp.
{
    heightmap_seg_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::heightmap_seg_iod_validator::quick_check().
is_valid_label_map_seg_dataset()
bool kcenon::pacs::services::validation::is_valid_label_map_seg_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid Label Map Segmentation object.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic Label Map Segmentation validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/label_map_seg_iod_validator.h.
Definition at line 690 of file label_map_seg_iod_validator.cpp.
{
    label_map_seg_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::label_map_seg_iod_validator::quick_check().
is_valid_mg_dataset()
bool kcenon::pacs::services::validation::is_valid_mg_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid mammography image.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic mammography IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/mg_iod_validator.h.
Definition at line 1003 of file mg_iod_validator.cpp.
{
    mg_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::mg_iod_validator::quick_check().
is_valid_mr_dataset()
bool kcenon::pacs::services::validation::is_valid_mr_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid MR image.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic MR IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/mr_iod_validator.h.
Definition at line 479 of file mr_iod_validator.cpp.
{
    mr_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::mr_iod_validator::quick_check().
is_valid_nm_dataset()
bool kcenon::pacs::services::validation::is_valid_nm_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid NM image.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic NM IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/nm_iod_validator.h.
Definition at line 685 of file nm_iod_validator.cpp.
{
    nm_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::nm_iod_validator::quick_check().
is_valid_ophthalmic_dataset()
bool kcenon::pacs::services::validation::is_valid_ophthalmic_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid ophthalmic image.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic ophthalmic IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 495 of file ophthalmic_iod_validator.cpp.
{
    ophthalmic_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::ophthalmic_iod_validator::quick_check().
is_valid_parametric_map_dataset()
bool kcenon::pacs::services::validation::is_valid_parametric_map_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid Parametric Map object.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic Parametric Map IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 542 of file parametric_map_iod_validator.cpp.
{
    parametric_map_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::parametric_map_iod_validator::quick_check().
is_valid_pet_dataset()
bool kcenon::pacs::services::validation::is_valid_pet_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid PET image.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic PET IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 640 of file pet_iod_validator.cpp.
{
    pet_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::pet_iod_validator::quick_check().
is_valid_rt_dataset()
bool kcenon::pacs::services::validation::is_valid_rt_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid RT object (any type)
Definition at line 1172 of file rt_iod_validator.cpp.
{
    rt_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::rt_iod_validator::quick_check().
is_valid_rt_dose_dataset()
bool kcenon::pacs::services::validation::is_valid_rt_dose_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid RT Dose.
Definition at line 1162 of file rt_iod_validator.cpp.
{
    rt_dose_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::rt_dose_iod_validator::quick_check().
is_valid_rt_plan_dataset()
bool kcenon::pacs::services::validation::is_valid_rt_plan_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid RT Plan.
Definition at line 1157 of file rt_iod_validator.cpp.
{
    rt_plan_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::rt_plan_iod_validator::quick_check().
is_valid_rt_structure_set_dataset()
bool kcenon::pacs::services::validation::is_valid_rt_structure_set_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid RT Structure Set.
Definition at line 1167 of file rt_iod_validator.cpp.
{
    rt_structure_set_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::rt_structure_set_iod_validator::quick_check().
is_valid_seg_dataset()
bool kcenon::pacs::services::validation::is_valid_seg_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid SEG object.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic SEG IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/seg_iod_validator.h.
Definition at line 693 of file seg_iod_validator.cpp.
{
    seg_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::seg_iod_validator::quick_check().
is_valid_sr_dataset()
bool kcenon::pacs::services::validation::is_valid_sr_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid SR document.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic SR IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/sr_iod_validator.h.
Definition at line 965 of file sr_iod_validator.cpp.
{
    sr_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::sr_iod_validator::quick_check().
is_valid_us_dataset()
bool kcenon::pacs::services::validation::is_valid_us_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid US image.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic US IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 478 of file us_iod_validator.cpp.
{
    us_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::us_iod_validator::quick_check().
is_valid_wsi_dataset()
bool kcenon::pacs::services::validation::is_valid_wsi_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid WSI image.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic WSI IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/wsi_iod_validator.h.
Definition at line 498 of file wsi_iod_validator.cpp.
{
    wsi_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::wsi_iod_validator::quick_check().
is_valid_xa_dataset()
bool kcenon::pacs::services::validation::is_valid_xa_dataset (const core::dicom_dataset & dataset) nodiscard
Quick check if a dataset is a valid XA image.
Parameters
dataset The dataset to check
Returns
true if the dataset passes basic XA IOD validation
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/xa_iod_validator.h.
Definition at line 606 of file xa_iod_validator.cpp.
{
    xa_iod_validator validator;
    return validator.quick_check(dataset);
}
References kcenon::pacs::services::validation::xa_iod_validator::quick_check().
validate_ct_iod()
validation_result kcenon::pacs::services::validation::validate_ct_iod (const core::dicom_dataset & dataset) nodiscard
Validate a CT dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ct_iod_validator.h.
Definition at line 454 of file ct_iod_validator.cpp.
{
    ct_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::ct_iod_validator::validate().
validate_ct_processing_iod()
validation_result kcenon::pacs::services::validation::validate_ct_processing_iod (const core::dicom_dataset & dataset) nodiscard
Validate a CT For Processing dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ct_processing_iod_validator.h.
Definition at line 475 of file ct_processing_iod_validator.cpp.
{
    ct_processing_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::ct_processing_iod_validator::validate().
validate_dx_iod()
validation_result kcenon::pacs::services::validation::validate_dx_iod (const core::dicom_dataset & dataset) nodiscard
Validate a DX dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/dx_iod_validator.h.
Definition at line 674 of file dx_iod_validator.cpp.
{
    dx_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::dx_iod_validator::validate().
validate_heightmap_seg_iod()
validation_result kcenon::pacs::services::validation::validate_heightmap_seg_iod (const core::dicom_dataset & dataset) nodiscard
Validate a Heightmap Segmentation dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/heightmap_seg_iod_validator.h.
Definition at line 650 of file heightmap_seg_iod_validator.cpp.
{
    heightmap_seg_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::heightmap_seg_iod_validator::validate().
validate_label_map_seg_iod()
validation_result kcenon::pacs::services::validation::validate_label_map_seg_iod (const core::dicom_dataset & dataset) nodiscard
Validate a Label Map Segmentation dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/label_map_seg_iod_validator.h.
Definition at line 685 of file label_map_seg_iod_validator.cpp.
{
    label_map_seg_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::label_map_seg_iod_validator::validate().
validate_mg_iod()
validation_result kcenon::pacs::services::validation::validate_mg_iod (const core::dicom_dataset & dataset) nodiscard
Validate a mammography dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/mg_iod_validator.h.
Definition at line 998 of file mg_iod_validator.cpp.
{
    mg_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::mg_iod_validator::validate().
validate_mr_iod()
validation_result kcenon::pacs::services::validation::validate_mr_iod (const core::dicom_dataset & dataset) nodiscard
Validate an MR dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/mr_iod_validator.h.
Definition at line 474 of file mr_iod_validator.cpp.
{
    mr_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::mr_iod_validator::validate().
validate_nm_iod()
validation_result kcenon::pacs::services::validation::validate_nm_iod (const core::dicom_dataset & dataset) nodiscard
Validate a NM dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/nm_iod_validator.h.
Definition at line 680 of file nm_iod_validator.cpp.
{
    nm_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::nm_iod_validator::validate().
validate_ophthalmic_iod()
validation_result kcenon::pacs::services::validation::validate_ophthalmic_iod (const core::dicom_dataset & dataset) nodiscard
Validate an ophthalmic dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/ophthalmic_iod_validator.h.
Definition at line 490 of file ophthalmic_iod_validator.cpp.
{
    ophthalmic_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::ophthalmic_iod_validator::validate().
validate_parametric_map_iod()
validation_result kcenon::pacs::services::validation::validate_parametric_map_iod (const core::dicom_dataset & dataset) nodiscard
Validate a Parametric Map dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/parametric_map_iod_validator.h.
Definition at line 537 of file parametric_map_iod_validator.cpp.
{
    parametric_map_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::parametric_map_iod_validator::validate().
validate_pet_iod()
validation_result kcenon::pacs::services::validation::validate_pet_iod (const core::dicom_dataset & dataset) nodiscard
Validate a PET dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/pet_iod_validator.h.
Definition at line 635 of file pet_iod_validator.cpp.
{
    pet_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::pet_iod_validator::validate().
validate_rt_dose_iod()
validation_result kcenon::pacs::services::validation::validate_rt_dose_iod (const core::dicom_dataset & dataset) nodiscard
Validate an RT Dose dataset with default options.
Definition at line 1142 of file rt_iod_validator.cpp.
{
    rt_dose_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::rt_dose_iod_validator::validate().
validate_rt_iod()
validation_result kcenon::pacs::services::validation::validate_rt_iod (const core::dicom_dataset & dataset) nodiscard
Validate any RT dataset (auto-detects type) with default options.
Definition at line 1152 of file rt_iod_validator.cpp.
{
    rt_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::rt_iod_validator::validate().
validate_rt_plan_iod()
validation_result kcenon::pacs::services::validation::validate_rt_plan_iod (const core::dicom_dataset & dataset) nodiscard
Validate an RT Plan dataset with default options.
Definition at line 1137 of file rt_iod_validator.cpp.
{
    rt_plan_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::rt_plan_iod_validator::validate().
validate_rt_structure_set_iod()
validation_result kcenon::pacs::services::validation::validate_rt_structure_set_iod (const core::dicom_dataset & dataset) nodiscard
Validate an RT Structure Set dataset with default options.
Definition at line 1147 of file rt_iod_validator.cpp.
{
    rt_structure_set_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::rt_structure_set_iod_validator::validate().
validate_seg_iod()
validation_result kcenon::pacs::services::validation::validate_seg_iod (const core::dicom_dataset & dataset) nodiscard
Validate a SEG dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/seg_iod_validator.h.
Definition at line 688 of file seg_iod_validator.cpp.
{
    seg_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::seg_iod_validator::validate().
validate_sr_iod()
validation_result kcenon::pacs::services::validation::validate_sr_iod (const core::dicom_dataset & dataset) nodiscard
Validate an SR dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/sr_iod_validator.h.
Definition at line 960 of file sr_iod_validator.cpp.
{
    sr_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::sr_iod_validator::validate().
validate_us_iod()
validation_result kcenon::pacs::services::validation::validate_us_iod (const core::dicom_dataset & dataset) nodiscard
Validate a US dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/us_iod_validator.h.
Definition at line 473 of file us_iod_validator.cpp.
{
    us_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::us_iod_validator::validate().
validate_wsi_iod()
validation_result kcenon::pacs::services::validation::validate_wsi_iod (const core::dicom_dataset & dataset) nodiscard
Validate a WSI dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/wsi_iod_validator.h.
Definition at line 493 of file wsi_iod_validator.cpp.
{
    wsi_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::wsi_iod_validator::validate().
validate_xa_iod()
validation_result kcenon::pacs::services::validation::validate_xa_iod (const core::dicom_dataset & dataset) nodiscard
Validate an XA dataset with default options.
Parameters
dataset The dataset to validate
Returns
Validation result
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/services/validation/xa_iod_validator.h.
Definition at line 601 of file xa_iod_validator.cpp.
{
    xa_iod_validator validator;
    return validator.validate(dataset);
}
References kcenon::pacs::services::validation::xa_iod_validator::validate().
Variable Documentation
heightmap_segmentation_storage_uid
std::string_view kcenon::pacs::services::validation::heightmap_segmentation_storage_uid static constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.66.7"
Definition at line 20 of file heightmap_seg_iod_validator.cpp.
label_map_segmentation_storage_uid
std::string_view kcenon::pacs::services::validation::label_map_segmentation_storage_uid static constexpr
Initial value:
=
    "1.2.840.10008.5.1.4.1.1.66.8"
Definition at line 20 of file label_map_seg_iod_validator.cpp.