PACS System: kcenon::pacs Namespace Reference
kcenon::pacs Namespace Reference
Namespaces
namespace ai
namespace client
namespace compat
namespace core
namespace dcm_modify
namespace di
namespace encoding
namespace error_codes
namespace events
namespace example
namespace integration
namespace integration_test
namespace monitoring
namespace network
namespace security
namespace services
namespace storage
namespace web
namespace workflow
Typedefs
template<typename T >
using Result = kcenon::common::Result<T>
Result type alias for PACS operations.
using error_info = kcenon::common::error_info
Error information type.
Functions
template<typename T >
Result< T > pacs_error (int code, const std::string &message, const std::string &details="")
Create a PACS error result with module context.
VoidResult pacs_void_error (int code, const std::string &message, const std::string &details="")
Create a PACS void error result.
Typedef Documentation
error_info
using kcenon::pacs::error_info = kcenon::common::error_info
Error information type.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/ai/ai_service_connector.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/dicom_session.h, and /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/network_adapter.h.
Definition at line 40 of file result.h.
Result
template<typename T > using kcenon::pacs::Result = kcenon::common::Result<T>
Result type alias for PACS operations.
Template Parameters
T The success value type
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/client/remote_node_manager.h, /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/dicom_session.h, and /home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/integration/network_adapter.h.
Definition at line 30 of file result.h.
Function Documentation
pacs_error()
template<typename T > Result< T > kcenon::pacs::pacs_error (int code, const std::string & message, const std::string & details = "") inline
Create a PACS error result with module context.
Template Parameters
T The result value type
Parameters
code Error code from kcenon::pacs::error_codes
message Error message
details Optional additional details
Returns
Result<T> containing the error
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/core/dicom_element.h, and mpps_scp/main.cpp.
Definition at line 234 of file result.h.
{
    if (details.empty()) {
        return kcenon::common::make_error<T>(code, message, "pacs");
    }
    return kcenon::common::make_error<T>(code, message, "pacs", details);
}
References code.
Referenced by kcenon::pacs::core::dicom_element::as_numeric(), kcenon::pacs::services::query_scu::cancel(), kcenon::pacs::services::retrieve_scu::cancel(), kcenon::pacs::services::worklist_scu::cancel(), kcenon::pacs::services::ups_push_scu::change_state(), kcenon::pacs::services::mpps_scu::create(), kcenon::pacs::services::ups_push_scu::create(), kcenon::pacs::services::print_scu::create_film_box(), kcenon::pacs::services::print_scu::create_film_session(), kcenon::pacs::encoding::compression::frame_deflate_codec::decode(), kcenon::pacs::encoding::compression::hevc_codec::decode(), kcenon::pacs::encoding::compression::htj2k_codec::decode(), kcenon::pacs::encoding::compression::jpeg2000_codec::impl::decode(), kcenon::pacs::encoding::compression::jpeg_baseline_codec::impl::decode(), kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::decode(), kcenon::pacs::encoding::compression::jpeg_ls_codec::impl::decode(), kcenon::pacs::encoding::compression::jpegxl_codec::decode(), kcenon::pacs::encoding::compression::rle_codec::impl::decode(), kcenon::pacs::encoding::explicit_vr_big_endian_codec::decode(), kcenon::pacs::encoding::explicit_vr_codec::decode(), kcenon::pacs::encoding::implicit_vr_codec::decode(), kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::decode_frame(), kcenon::pacs::encoding::compression::rle_codec::impl::decode_frame(), kcenon::pacs::network::pipeline::pdu_decode_job::decode_pdu(), kcenon::pacs::services::print_scu::delete_film_box(), kcenon::pacs::services::print_scu::delete_film_session(), kcenon::pacs::encoding::compression::frame_deflate_codec::encode(), kcenon::pacs::encoding::compression::hevc_codec::encode(), kcenon::pacs::encoding::compression::htj2k_codec::encode(), kcenon::pacs::encoding::compression::jpeg2000_codec::impl::encode(), kcenon::pacs::encoding::compression::jpeg_baseline_codec::impl::encode(), kcenon::pacs::encoding::compression::jpeg_lossless_codec::impl::encode(), kcenon::pacs::encoding::compression::jpeg_ls_codec::impl::encode(), kcenon::pacs::encoding::compression::jpegxl_codec::encode(), kcenon::pacs::encoding::compression::rle_codec::impl::encode(), kcenon::pacs::services::query_scu::find_impl(), kcenon::pacs::services::query_scu::find_streaming(), kcenon::pacs::core::dicom_file::from_bytes(), kcenon::pacs::services::n_get_scu::get(), kcenon::pacs::services::ups_push_scu::get(), kcenon::pacs::storage::index_database::get_storage_stats(), kcenon::pacs::services::storage_commitment_scu::handle_event_report(), kcenon::pacs::services::ups_watch_scu::handle_event_report(), kcenon::pacs::core::memory_mapped_file::open(), kcenon::pacs::core::dicom_file::parse_meta_information(), kcenon::pacs::services::retrieve_scu::perform_get(), kcenon::pacs::services::retrieve_scu::perform_move(), kcenon::pacs::services::print_scu::print_film_box(), kcenon::pacs::network::pipeline::dimse_process_job::process_p_data(), kcenon::pacs::services::worklist_scu::query_impl(), kcenon::pacs::services::print_scu::query_printer_status(), kcenon::pacs::services::worklist_scu::query_streaming(), kcenon::pacs::services::ups_push_scu::request_cancel(), kcenon::pacs::services::retrieve_scu::retrieve_instance(), kcenon::pacs::services::retrieve_scu::retrieve_series(), kcenon::pacs::services::retrieve_scu::retrieve_study(), kcenon::pacs::services::ups_watch_scu::send_watch_action(), kcenon::pacs::services::mpps_scu::set(), kcenon::pacs::services::ups_push_scu::set(), kcenon::pacs::services::print_scu::set_image_box(), kcenon::pacs::services::storage_scu::store_file(), and kcenon::pacs::services::storage_scu::store_impl().
pacs_void_error()
VoidResult kcenon::pacs::pacs_void_error (int code, const std::string & message, const std::string & details = "") inline
Create a PACS void error result.
Parameters
code Error code from kcenon::pacs::error_codes
message Error message
details Optional additional details
Returns
VoidResult containing the error
Definition at line 249 of file result.h.
{
    if (details.empty()) {
        return VoidResult(error_info{code, message, "pacs"});
    }
    return VoidResult(error_info{code, message, "pacs", details});
}
References code.
Referenced by kcenon::pacs::client::sync_manager::add_config(), kcenon::pacs::client::remote_node_manager::add_node(), kcenon::pacs::client::routing_manager::add_rule(), kcenon::pacs::client::job_manager::cancel_job(), kcenon::pacs::client::job_manager::delete_job(), kcenon::pacs::security::atna_syslog_transport::ensure_tls_connected(), kcenon::pacs::network::pipeline::pdu_decode_job::execute(), kcenon::pacs::network::pipeline::receive_network_io_job::execute(), kcenon::pacs::network::pipeline::send_network_io_job::execute(), kcenon::pacs::services::retrieve_scp::handle_c_get(), kcenon::pacs::services::retrieve_scp::handle_c_move(), kcenon::pacs::services::mpps_scp::handle_message(), kcenon::pacs::services::n_get_scp::handle_message(), kcenon::pacs::services::print_scp::handle_message(), kcenon::pacs::services::query_scp::handle_message(), kcenon::pacs::services::retrieve_scp::handle_message(), kcenon::pacs::services::storage_commitment_scp::handle_message(), kcenon::pacs::services::storage_scp::handle_message(), kcenon::pacs::services::ups_push_scp::handle_message(), kcenon::pacs::services::ups_query_scp::handle_message(), kcenon::pacs::services::ups_watch_scp::handle_message(), kcenon::pacs::services::verification_scp::handle_message(), kcenon::pacs::services::worklist_scp::handle_message(), kcenon::pacs::services::ups_push_scp::handle_n_action(), kcenon::pacs::services::ups_watch_scp::handle_n_action(), kcenon::pacs::services::mpps_scp::handle_n_create(), kcenon::pacs::services::ups_push_scp::handle_n_create(), kcenon::pacs::services::ups_push_scp::handle_n_get(), kcenon::pacs::services::mpps_scp::handle_n_set(), kcenon::pacs::services::ups_push_scp::handle_n_set(), kcenon::pacs::services::ups_watch_scp::handle_subscribe(), kcenon::pacs::services::ups_watch_scp::handle_suspend_global(), kcenon::pacs::services::ups_watch_scp::handle_unsubscribe(), kcenon::pacs::network::pipeline::pipeline_adapter::on_data_received(), kcenon::pacs::client::job_manager::pause_job(), kcenon::pacs::client::remote_node_manager::impl::perform_echo(), kcenon::pacs::client::sync_manager::remove_config(), kcenon::pacs::client::remote_node_manager::remove_node(), kcenon::pacs::services::storage_commitment_scu::request_commitment(), kcenon::pacs::client::sync_manager::resolve_conflict(), kcenon::pacs::client::job_manager::resume_job(), kcenon::pacs::client::job_manager::retry_job(), kcenon::pacs::core::dicom_file::save(), kcenon::pacs::security::atna_syslog_transport::send_tls(), kcenon::pacs::security::atna_syslog_transport::send_udp(), kcenon::pacs::network::pipeline::pipeline_coordinator::start(), kcenon::pacs::client::job_manager::start_job(), kcenon::pacs::network::pipeline::pipeline_coordinator::stop(), kcenon::pacs::network::pipeline::pipeline_coordinator::submit_task(), kcenon::pacs::network::pipeline::pipeline_coordinator::submit_to_stage(), kcenon::pacs::network::pipeline::pipeline_coordinator::submit_to_stage(), kcenon::pacs::client::sync_manager::update_config(), kcenon::pacs::client::remote_node_manager::update_node(), kcenon::pacs::client::prefetch_manager::update_rule(), kcenon::pacs::client::routing_manager::update_rule(), and kcenon::pacs::client::remote_node_manager::verify_node().