PACS System: kcenon::pacs::encoding::simd::detail Namespace Reference
kcenon::pacs::encoding::simd::detail Namespace Reference
Functions
void invert_monochrome_8bit_scalar (const uint8_t *src, uint8_t *dst, size_t pixel_count) noexcept
Scalar 8-bit monochrome inversion (MONOCHROME1 <-> MONOCHROME2)
void invert_monochrome_16bit_scalar (const uint16_t *src, uint16_t *dst, size_t pixel_count, uint16_t max_value) noexcept
Scalar 16-bit monochrome inversion.
void rgb_to_ycbcr_8bit_scalar (const uint8_t *src, uint8_t *dst, size_t pixel_count) noexcept
Scalar RGB to YCbCr conversion (ITU-R BT.601)
void ycbcr_to_rgb_8bit_scalar (const uint8_t *src, uint8_t *dst, size_t pixel_count) noexcept
Scalar YCbCr to RGB conversion (ITU-R BT.601)
void interleaved_to_planar_rgb8_scalar (const uint8_t *src, uint8_t *r, uint8_t *g, uint8_t *b, size_t pixel_count) noexcept
void planar_to_interleaved_rgb8_scalar (const uint8_t *r, const uint8_t *g, const uint8_t *b, uint8_t *dst, size_t pixel_count) noexcept
void split_16bit_to_planes_scalar (const uint8_t *src, uint8_t *high, uint8_t *low, size_t pixel_count) noexcept
void merge_planes_to_16bit_scalar (const uint8_t *high, const uint8_t *low, uint8_t *dst, size_t pixel_count) noexcept
void swap_bytes_16_scalar (const uint8_t *src, uint8_t *dst, size_t byte_count) noexcept
void swap_bytes_32_scalar (const uint8_t *src, uint8_t *dst, size_t byte_count) noexcept
void swap_bytes_64_scalar (const uint8_t *src, uint8_t *dst, size_t byte_count) noexcept
void apply_window_level_8bit_scalar (const uint8_t *src, uint8_t *dst, size_t pixel_count, const window_level_params &params) noexcept
Scalar 8-bit window/level application.
void apply_window_level_16bit_scalar (const uint16_t *src, uint8_t *dst, size_t pixel_count, const window_level_params &params) noexcept
Scalar 16-bit window/level application.
void apply_window_level_16bit_signed_scalar (const int16_t *src, uint8_t *dst, size_t pixel_count, const window_level_params &params) noexcept
Scalar signed 16-bit window/level application.
Function Documentation
apply_window_level_16bit_scalar()
void kcenon::pacs::encoding::simd::detail::apply_window_level_16bit_scalar (const uint16_t * src, uint8_t * dst, size_t pixel_count, const window_level_params & params) inline noexcept
Scalar 16-bit window/level application.
Definition at line 197 of file simd_windowing.h.
{
    const double min_val = params.center - params.width / 2.0;
    const double scale = 255.0 / params.width;
    for (size_t i = 0; i < pixel_count; ++i) {
        double val = (src[i] - min_val) * scale;
        val = std::clamp(val, 0.0, 255.0);
        if (params.invert) {
            val = 255.0 - val;
        }
        dst[i] = static_cast<uint8_t>(val);
    }
}
Referenced by kcenon::pacs::encoding::simd::apply_window_level_16bit().
apply_window_level_16bit_signed_scalar()
void kcenon::pacs::encoding::simd::detail::apply_window_level_16bit_signed_scalar (const int16_t * src, uint8_t * dst, size_t pixel_count, const window_level_params & params) inline noexcept
Scalar signed 16-bit window/level application.
Definition at line 216 of file simd_windowing.h.
{
    const double min_val = params.center - params.width / 2.0;
    const double scale = 255.0 / params.width;
    for (size_t i = 0; i < pixel_count; ++i) {
        double val = (src[i] - min_val) * scale;
        val = std::clamp(val, 0.0, 255.0);
        if (params.invert) {
            val = 255.0 - val;
        }
        dst[i] = static_cast<uint8_t>(val);
    }
}
Referenced by kcenon::pacs::encoding::simd::apply_window_level_16bit_signed().
apply_window_level_8bit_scalar()
void kcenon::pacs::encoding::simd::detail::apply_window_level_8bit_scalar (const uint8_t * src, uint8_t * dst, size_t pixel_count, const window_level_params & params) inline noexcept
Scalar 8-bit window/level application.
Definition at line 178 of file simd_windowing.h.
{
    const double min_val = params.center - params.width / 2.0;
    const double scale = 255.0 / params.width;
    for (size_t i = 0; i < pixel_count; ++i) {
        double val = (src[i] - min_val) * scale;
        val = std::clamp(val, 0.0, 255.0);
        if (params.invert) {
            val = 255.0 - val;
        }
        dst[i] = static_cast<uint8_t>(val);
    }
}
Referenced by kcenon::pacs::encoding::simd::apply_window_level_8bit().
interleaved_to_planar_rgb8_scalar()
void kcenon::pacs::encoding::simd::detail::interleaved_to_planar_rgb8_scalar (const uint8_t * src, uint8_t * r, uint8_t * g, uint8_t * b, size_t pixel_count) inline noexcept
Definition at line 50 of file simd_rle.h.
{
    for (size_t i = 0; i < pixel_count; ++i) {
        r[i] = src[i * 3];
        g[i] = src[i * 3 + 1];
        b[i] = src[i * 3 + 2];
    }
}
Referenced by kcenon::pacs::encoding::simd::interleaved_to_planar_rgb8().
invert_monochrome_16bit_scalar()
void kcenon::pacs::encoding::simd::detail::invert_monochrome_16bit_scalar (const uint16_t * src, uint16_t * dst, size_t pixel_count, uint16_t max_value) inline noexcept
Scalar 16-bit monochrome inversion.
Parameters
max_value Maximum pixel value (e.g., 4095 for 12-bit, 65535 for 16-bit)
Definition at line 61 of file simd_photometric.h.
{
    for (size_t i = 0; i < pixel_count; ++i) {
        dst[i] = max_value - src[i];
    }
}
Referenced by kcenon::pacs::encoding::simd::invert_monochrome_16bit().
invert_monochrome_8bit_scalar()
void kcenon::pacs::encoding::simd::detail::invert_monochrome_8bit_scalar (const uint8_t * src, uint8_t * dst, size_t pixel_count) inline noexcept
Scalar 8-bit monochrome inversion (MONOCHROME1 <-> MONOCHROME2)
Definition at line 50 of file simd_photometric.h.
{
    for (size_t i = 0; i < pixel_count; ++i) {
        dst[i] = 255 - src[i];
    }
}
Referenced by kcenon::pacs::encoding::simd::invert_monochrome_8bit().
merge_planes_to_16bit_scalar()
void kcenon::pacs::encoding::simd::detail::merge_planes_to_16bit_scalar (const uint8_t * high, const uint8_t * low, uint8_t * dst, size_t pixel_count) inline noexcept
Definition at line 79 of file simd_rle.h.
{
    for (size_t i = 0; i < pixel_count; ++i) {
        dst[i * 2] = low[i];
        dst[i * 2 + 1] = high[i];
    }
}
Referenced by kcenon::pacs::encoding::simd::merge_planes_to_16bit().
planar_to_interleaved_rgb8_scalar()
void kcenon::pacs::encoding::simd::detail::planar_to_interleaved_rgb8_scalar (const uint8_t * r, const uint8_t * g, const uint8_t * b, uint8_t * dst, size_t pixel_count) inline noexcept
Definition at line 60 of file simd_rle.h.
{
    for (size_t i = 0; i < pixel_count; ++i) {
        dst[i * 3] = r[i];
        dst[i * 3 + 1] = g[i];
        dst[i * 3 + 2] = b[i];
    }
}
Referenced by kcenon::pacs::encoding::simd::planar_to_interleaved_rgb8().
rgb_to_ycbcr_8bit_scalar()
void kcenon::pacs::encoding::simd::detail::rgb_to_ycbcr_8bit_scalar (const uint8_t * src, uint8_t * dst, size_t pixel_count) inline noexcept
Scalar RGB to YCbCr conversion (ITU-R BT.601)
Y = 0.299*R + 0.587*G + 0.114*B Cb = -0.169*R - 0.331*G + 0.500*B + 128 Cr = 0.500*R - 0.419*G - 0.081*B + 128
Definition at line 76 of file simd_photometric.h.
{
    for (size_t i = 0; i < pixel_count; ++i) {
        const int r = src[i * 3];
        const int g = src[i * 3 + 1];
        const int b = src[i * 3 + 2];
        // Fixed-point arithmetic (16.16 format for precision)
        // Coefficients scaled by 65536
        const int y = (19595 * r + 38470 * g + 7471 * b + 32768) >> 16;
        const int cb = (-11056 * r - 21712 * g + 32768 * b + 32768) >> 16;
        const int cr = (32768 * r - 27440 * g - 5328 * b + 32768) >> 16;
        dst[i * 3] = static_cast<uint8_t>(y < 0 ? 0 : (y > 255 ? 255 : y));
        dst[i * 3 + 1] = static_cast<uint8_t>(cb + 128);
        dst[i * 3 + 2] = static_cast<uint8_t>(cr + 128);
    }
}
Referenced by kcenon::pacs::encoding::simd::rgb_to_ycbcr_8bit().
split_16bit_to_planes_scalar()
void kcenon::pacs::encoding::simd::detail::split_16bit_to_planes_scalar (const uint8_t * src, uint8_t * high, uint8_t * low, size_t pixel_count) inline noexcept
Definition at line 70 of file simd_rle.h.
{
    for (size_t i = 0; i < pixel_count; ++i) {
        low[i] = src[i * 2];
        high[i] = src[i * 2 + 1];
    }
}
Referenced by kcenon::pacs::encoding::simd::split_16bit_to_planes().
swap_bytes_16_scalar()
void kcenon::pacs::encoding::simd::detail::swap_bytes_16_scalar (const uint8_t * src, uint8_t * dst, size_t byte_count) inline noexcept
Definition at line 38 of file simd_utils.h.
{
    for (size_t i = 0; i + 1 < byte_count; i += 2) {
        dst[i] = src[i + 1];
        dst[i + 1] = src[i];
    }
}
Referenced by kcenon::pacs::encoding::simd::swap_bytes_16_simd().
swap_bytes_32_scalar()
void kcenon::pacs::encoding::simd::detail::swap_bytes_32_scalar (const uint8_t * src, uint8_t * dst, size_t byte_count) inline noexcept
Definition at line 46 of file simd_utils.h.
{
    for (size_t i = 0; i + 3 < byte_count; i += 4) {
        dst[i] = src[i + 3];
        dst[i + 1] = src[i + 2];
        dst[i + 2] = src[i + 1];
        dst[i + 3] = src[i];
    }
}
Referenced by kcenon::pacs::encoding::simd::swap_bytes_32_simd().
swap_bytes_64_scalar()
void kcenon::pacs::encoding::simd::detail::swap_bytes_64_scalar (const uint8_t * src, uint8_t * dst, size_t byte_count) inline noexcept
Definition at line 56 of file simd_utils.h.
{
    for (size_t i = 0; i + 7 < byte_count; i += 8) {
        dst[i] = src[i + 7];
        dst[i + 1] = src[i + 6];
        dst[i + 2] = src[i + 5];
        dst[i + 3] = src[i + 4];
        dst[i + 4] = src[i + 3];
        dst[i + 5] = src[i + 2];
        dst[i + 6] = src[i + 1];
        dst[i + 7] = src[i];
    }
}
Referenced by kcenon::pacs::encoding::simd::swap_bytes_64_simd().
ycbcr_to_rgb_8bit_scalar()
void kcenon::pacs::encoding::simd::detail::ycbcr_to_rgb_8bit_scalar (const uint8_t * src, uint8_t * dst, size_t pixel_count) inline noexcept
Scalar YCbCr to RGB conversion (ITU-R BT.601)
R = Y + 1.402*(Cr-128) G = Y - 0.344*(Cb-128) - 0.714*(Cr-128) B = Y + 1.772*(Cb-128)
Definition at line 102 of file simd_photometric.h.
{
    for (size_t i = 0; i < pixel_count; ++i) {
        const int y = src[i * 3];
        const int cb = src[i * 3 + 1] - 128;
        const int cr = src[i * 3 + 2] - 128;
        // Fixed-point arithmetic (coefficients scaled by 65536)
        const int r = y + ((91881 * cr + 32768) >> 16);
        const int g = y - ((22554 * cb + 46802 * cr + 32768) >> 16);
        const int b = y + ((116130 * cb + 32768) >> 16);
        dst[i * 3] = static_cast<uint8_t>(r < 0 ? 0 : (r > 255 ? 255 : r));
        dst[i * 3 + 1] = static_cast<uint8_t>(g < 0 ? 0 : (g > 255 ? 255 : g));
        dst[i * 3 + 2] = static_cast<uint8_t>(b < 0 ? 0 : (b > 255 ? 255 : b));
    }
}
Referenced by kcenon::pacs::encoding::simd::ycbcr_to_rgb_8bit().