PACS System: kcenon::pacs::ai::json_util Namespace Reference
kcenon::pacs::ai::json_util Namespace Reference
Functions
std::string escape_string (std::string_view str)
Escape special characters in JSON string.
std::string to_iso8601 (std::chrono::system_clock::time_point tp)
Convert time_point to ISO 8601 string.
std::optional< std::chrono::system_clock::time_point > from_iso8601 (const std::string &str)
Parse ISO 8601 string to time_point.
std::optional< std::string > extract_string (const std::string &json, const std::string &key)
Simple JSON value extractor (for basic parsing)
std::optional< int > extract_int (const std::string &json, const std::string &key)
Simple JSON integer extractor.
std::string build_request_json (const inference_request &request)
Build inference request JSON.
Function Documentation
build_request_json()
std::string kcenon::pacs::ai::json_util::build_request_json (const inference_request & request) inline
Build inference request JSON.
Definition at line 240 of file ai_service_connector.cpp.
References kcenon::pacs::ai::inference_request::callback_url, escape_string(), kcenon::pacs::ai::inference_request::model_id, kcenon::pacs::ai::inference_request::priority, kcenon::pacs::ai::inference_request::series_instance_uid, and kcenon::pacs::ai::inference_request::study_instance_uid.
escape_string()
std::string kcenon::pacs::ai::json_util::escape_string (std::string_view str) inline
Escape special characters in JSON string.
Definition at line 86 of file ai_service_connector.cpp.
{
    std::string result;
    result.reserve(str.size() + 10);
    for (char c : str) {
        switch (c) {
            case '"':
                result += "\\\"";
                break;
            case '\\':
                result += "\\\\";
                break;
            case '\b':
                result += "\\b";
                break;
            case '\f':
                result += "\\f";
                break;
            case '\n':
                result += "\\n";
                break;
            case '\r':
                result += "\\r";
                break;
            case '\t':
                result += "\\t";
                break;
            default:
                if (static_cast<unsigned char>(c) < 0x20) {
                    char buf[8];
                    std::snprintf(buf, sizeof(buf), "\\u%04x",
                                  static_cast<unsigned char>(c));
                    result += buf;
                } else {
                    result += c;
                }
                break;
        }
    }
    return result;
}
Referenced by build_request_json(), kcenon::pacs::ai::if(), and kcenon::pacs::ai::if().
extract_int()
std::optional< int > kcenon::pacs::ai::json_util::extract_int (const std::string & json, const std::string & key) inline
Simple JSON integer extractor.
Definition at line 204 of file ai_service_connector.cpp.
{
    std::string search_key = "\"" + key + "\"";
    auto pos = json.find(search_key);
    if (pos == std::string::npos) {
        return std::nullopt;
    }
    pos = json.find(':', pos);
    if (pos == std::string::npos) {
        return std::nullopt;
    }
    // Skip whitespace
    pos++;
    while (pos < json.size() && std::isspace(json[pos])) {
        pos++;
    }
    if (pos >= json.size()) {
        return std::nullopt;
    }
    try {
        std::size_t end_pos;
        int value = std::stoi(json.substr(pos), &end_pos);
        return value;
    } catch (...) {
        return std::nullopt;
    }
}
Referenced by parse_status_json().
extract_string()
std::optional< std::string > kcenon::pacs::ai::json_util::extract_string (const std::string & json, const std::string & key) inline
Simple JSON value extractor (for basic parsing)
Definition at line 173 of file ai_service_connector.cpp.
{
    std::string search_key = "\"" + key + "\"";
    auto pos = json.find(search_key);
    if (pos == std::string::npos) {
        return std::nullopt;
    }
    pos = json.find(':', pos);
    if (pos == std::string::npos) {
        return std::nullopt;
    }
    pos = json.find('"', pos);
    if (pos == std::string::npos) {
        return std::nullopt;
    }
    auto start = pos + 1;
    auto end = json.find('"', start);
    if (end == std::string::npos) {
        return std::nullopt;
    }
    return json.substr(start, end - start);
}
Referenced by parse_model_json(), and parse_status_json().
from_iso8601()
std::optional< std::chrono::system_clock::time_point > kcenon::pacs::ai::json_util::from_iso8601 (const std::string & str) inline
Parse ISO 8601 string to time_point.
Definition at line 152 of file ai_service_connector.cpp.
{
    std::tm tm_val{};
    std::istringstream iss(str);
    iss >> std::get_time(&tm_val, "%Y-%m-%dT%H:%M:%SZ");
    if (iss.fail()) {
        return std::nullopt;
    }
#if defined(_MSC_VER)
    auto time_t_val = _mkgmtime(&tm_val);
#else
    auto time_t_val = timegm(&tm_val);
#endif
    return std::chrono::system_clock::from_time_t(time_t_val);
}
Referenced by parse_status_json().
to_iso8601()
std::string kcenon::pacs::ai::json_util::to_iso8601 (std::chrono::system_clock::time_point tp) inline
Convert time_point to ISO 8601 string.
Definition at line 132 of file ai_service_connector.cpp.
{
    const auto time_t_val = std::chrono::system_clock::to_time_t(tp);
    std::tm tm_val{};
#if defined(_MSC_VER)
    gmtime_s(&tm_val, &time_t_val);
#else
    gmtime_r(&time_t_val, &tm_val);
#endif
    std::ostringstream oss;
    oss << std::put_time(&tm_val, "%Y-%m-%dT%H:%M:%SZ");
    return oss.str();
}