PACS System: kcenon::pacs::web::endpoints Namespace Reference
kcenon::pacs::web::endpoints Namespace Reference
Functions
void register_security_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
Register security endpoints with the Crow app.
void register_annotation_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_association_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_audit_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_dicomweb_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_jobs_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_key_image_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_measurement_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_metadata_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_patient_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_remote_nodes_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_routing_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_series_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_storage_commitment_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_study_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_system_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_thumbnail_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_viewer_state_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_wado_uri_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
void register_worklist_endpoints_impl (crow::SimpleApp &app, std::shared_ptr< rest_server_context > ctx)
Function Documentation
register_annotation_endpoints_impl()
void kcenon::pacs::web::endpoints::register_annotation_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 428 of file annotation_endpoints.cpp.
{
  // POST /api/v1/annotations - Create annotation
  CROW_ROUTE(app, "/api/v1/annotations")
      .methods(crow::HTTPMethod::POST)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        if (!ctx->database) {
          res.code = 503;
          res.body =
              make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
          return res;
        }
        std::string body = req.body;
        if (body.empty()) {
          res.code = 400;
          res.body = make_error_json("INVALID_REQUEST", "Request body is empty");
          return res;
        }
        storage::annotation_record ann;
        ann.annotation_id = generate_uuid();
        ann.study_uid = parse_json_string(body, "study_uid");
        ann.series_uid = parse_json_string(body, "series_uid");
        ann.sop_instance_uid = parse_json_string(body, "sop_instance_uid");
        ann.frame_number = parse_json_int(body, "frame_number");
        ann.user_id = parse_json_string(body, "user_id");
        auto type_str = parse_json_string(body, "annotation_type");
        auto type_opt = storage::annotation_type_from_string(type_str);
        if (!type_opt.has_value()) {
          res.code = 400;
          res.body = make_error_json("INVALID_TYPE", "Invalid annotation type");
          return res;
        }
        ann.type = type_opt.value();
        ann.geometry_json = parse_json_object(body, "geometry");
        ann.text = parse_json_string(body, "text");
        ann.style = parse_style(parse_json_object(body, "style"));
        ann.created_at = std::chrono::system_clock::now();
        ann.updated_at = ann.created_at;
        if (ann.study_uid.empty()) {
          res.code = 400;
          res.body = make_error_json("MISSING_FIELD", "study_uid is required");
          return res;
        }
        auto repo = make_annotation_repo(ctx->database.get());
        auto save_result = repo.save(ann);
        if (!save_result.is_ok()) {
          res.code = 500;
          res.body =
              make_error_json("SAVE_ERROR", save_result.error().message);
          return res;
        }
        res.code = 201;
        std::ostringstream oss;
        oss << R"({"annotation_id":")" << json_escape(ann.annotation_id)
            << R"(","created_at":")" << format_timestamp(ann.created_at)
            << R"("})";
        res.body = oss.str();
        return res;
      });
  // GET /api/v1/annotations - List annotations
  CROW_ROUTE(app, "/api/v1/annotations")
      .methods(crow::HTTPMethod::GET)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        if (!ctx->database) {
          res.code = 503;
          res.body =
              make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
          return res;
        }
        auto [limit, offset] = parse_pagination(req);
        storage::annotation_query query;
        query.limit = limit;
        query.offset = offset;
        auto study_uid = req.url_params.get("study_uid");
        if (study_uid) {
          query.study_uid = study_uid;
        }
        auto series_uid = req.url_params.get("series_uid");
        if (series_uid) {
          query.series_uid = series_uid;
        }
        auto sop_instance_uid = req.url_params.get("sop_instance_uid");
        if (sop_instance_uid) {
          query.sop_instance_uid = sop_instance_uid;
        }
        auto user_id = req.url_params.get("user_id");
        if (user_id) {
          query.user_id = user_id;
        }
        auto repo = make_annotation_repo(ctx->database.get());
        storage::annotation_query count_query = query;
        count_query.limit = 0;
        count_query.offset = 0;
        size_t total_count = count_annotations(repo, count_query);
        auto annotations = search_annotations(repo, query);
        res.code = 200;
        res.body = annotations_to_json(annotations, total_count);
        return res;
      });
  // GET /api/v1/annotations/<annotationId> - Get annotation by ID
  CROW_ROUTE(app, "/api/v1/annotations/<string>")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/, const std::string &annotation_id) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            auto repo = make_annotation_repo(ctx->database.get());
            auto ann = find_annotation(repo, annotation_id);
            if (!ann.has_value()) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Annotation not found");
              return res;
            }
            res.code = 200;
            res.body = annotation_to_json(ann.value());
            return res;
          });
  // PUT /api/v1/annotations/<annotationId> - Update annotation
  CROW_ROUTE(app, "/api/v1/annotations/<string>")
      .methods(crow::HTTPMethod::PUT)(
          [ctx](const crow::request &req, const std::string &annotation_id) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            auto repo = make_annotation_repo(ctx->database.get());
            auto existing = find_annotation(repo, annotation_id);
            if (!existing.has_value()) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Annotation not found");
              return res;
            }
            std::string body = req.body;
            if (body.empty()) {
              res.code = 400;
              res.body =
                  make_error_json("INVALID_REQUEST", "Request body is empty");
              return res;
            }
            storage::annotation_record ann = existing.value();
            auto geometry = parse_json_object(body, "geometry");
            if (geometry != "{}") {
              ann.geometry_json = geometry;
            }
            auto text = parse_json_string(body, "text");
            if (!text.empty() || body.find("\"text\":\"\"") != std::string::npos) {
              ann.text = text;
            }
            auto style_json = parse_json_object(body, "style");
            if (style_json != "{}") {
              ann.style = parse_style(style_json);
            }
            ann.updated_at = std::chrono::system_clock::now();
            auto update_result = repo.update(ann);
            if (!update_result.is_ok()) {
              res.code = 500;
              res.body =
                  make_error_json("UPDATE_ERROR", update_result.error().message);
              return res;
            }
            res.code = 200;
            std::ostringstream oss;
            oss << R"({"annotation_id":")" << json_escape(ann.annotation_id)
                << R"(","updated_at":")" << format_timestamp(ann.updated_at)
                << R"("})";
            res.body = oss.str();
            return res;
          });
  // DELETE /api/v1/annotations/<annotationId> - Delete annotation
  CROW_ROUTE(app, "/api/v1/annotations/<string>")
      .methods(crow::HTTPMethod::DELETE)(
          [ctx](const crow::request & /*req*/, const std::string &annotation_id) {
            crow::response res;
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            auto repo = make_annotation_repo(ctx->database.get());
            if (!annotation_exists(repo, annotation_id)) {
              res.code = 404;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("NOT_FOUND", "Annotation not found");
              return res;
            }
            auto remove_result = repo.remove(annotation_id);
            if (!remove_result.is_ok()) {
              res.code = 500;
              res.add_header("Content-Type", "application/json");
              res.body =
                  make_error_json("DELETE_ERROR", remove_result.error().message);
              return res;
            }
            res.code = 204;
            return res;
          });
  // GET /api/v1/instances/<sopInstanceUid>/annotations - Get annotations for instance
  CROW_ROUTE(app, "/api/v1/instances/<string>/annotations")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/,
                const std::string &sop_instance_uid) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            auto repo = make_annotation_repo(ctx->database.get());
            auto annotations = find_by_instance(repo, sop_instance_uid);
            std::ostringstream oss;
            oss << R"({"data":[)";
            for (size_t i = 0; i < annotations.size(); ++i) {
              if (i > 0) {
                oss << ",";
              }
              oss << annotation_to_json(annotations[i]);
            }
            oss << "]}";
            res.code = 200;
            res.body = oss.str();
            return res;
          });
}
References kcenon::pacs::storage::annotation_record::annotation_id, kcenon::pacs::storage::annotation_record::created_at, kcenon::pacs::storage::annotation_record::frame_number, kcenon::pacs::storage::annotation_record::geometry_json, kcenon::pacs::web::json_escape(), kcenon::pacs::storage::annotation_query::limit, kcenon::pacs::web::make_error_json(), kcenon::pacs::storage::annotation_query::offset, register_annotation_endpoints_impl(), kcenon::pacs::storage::annotation_record::series_uid, kcenon::pacs::storage::annotation_record::sop_instance_uid, kcenon::pacs::storage::annotation_record::study_uid, kcenon::pacs::storage::annotation_record::style, kcenon::pacs::storage::annotation_record::text, kcenon::pacs::storage::annotation_record::type, kcenon::pacs::storage::annotation_record::updated_at, and kcenon::pacs::storage::annotation_record::user_id.
Referenced by register_annotation_endpoints_impl(), and kcenon::pacs::web::rest_server::start_async().
register_association_endpoints_impl()
void kcenon::pacs::web::endpoints::register_association_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 74 of file association_endpoints.cpp.
{
  // GET /api/v1/associations/active - List active DICOM associations
  CROW_ROUTE(app, "/api/v1/associations/active")
      .methods(crow::HTTPMethod::GET)([ctx](const crow::request & /*req*/) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        if (!ctx->dicom_server) {
            res.code = 503;
            res.body = make_error_json("SERVICE_UNAVAILABLE",
                                       "DICOM server not configured");
            return res;
        }
        auto stats = ctx->dicom_server->get_statistics();
        auto active_count = ctx->dicom_server->active_associations();
        auto uptime_sec = stats.uptime().count();
        std::ostringstream oss;
        oss << R"({"active_count":)" << active_count
            << R"(,"total_associations":)" << stats.total_associations
            << R"(,"rejected_associations":)" << stats.rejected_associations
            << R"(,"messages_processed":)" << stats.messages_processed
            << R"(,"bytes_received":)" << stats.bytes_received
            << R"(,"bytes_sent":)" << stats.bytes_sent
            << R"(,"uptime_seconds":)" << uptime_sec
            << R"(,"server_running":)"
            << (ctx->dicom_server->is_running() ? "true" : "false")
            << '}';
        res.code = 200;
        res.body = oss.str();
        return res;
      });
  // DELETE /api/v1/associations/:id - Terminate a DICOM association
  CROW_ROUTE(app, "/api/v1/associations/<string>")
      .methods(crow::HTTPMethod::DELETE)(
          [ctx](const crow::request & /*req*/,
                const std::string &association_id) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (association_id.empty()) {
              res.code = 400;
              res.body = make_error_json("INVALID_REQUEST",
                                         "Association ID is required");
              return res;
            }
            if (!ctx->dicom_server) {
              res.code = 503;
              res.body = make_error_json("SERVICE_UNAVAILABLE",
                                         "DICOM server not configured");
              return res;
            }
            // Individual association termination is not supported via the
            // dicom_server public API. The server manages association
            // lifecycles internally through idle timeouts and graceful
            // shutdown.
            res.code = 501;
            res.body = make_error_json(
                "NOT_IMPLEMENTED",
                "Individual association termination is not supported. "
                "Associations are managed by the DICOM server via idle "
                "timeouts and graceful shutdown.");
            return res;
          });
  // GET /api/v1/associations/:id - Get specific association details
  CROW_ROUTE(app, "/api/v1/associations/<string>")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/,
                const std::string &association_id) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (association_id.empty()) {
              res.code = 400;
              res.body = make_error_json("INVALID_REQUEST",
                                         "Association ID is required");
              return res;
            }
            if (!ctx->dicom_server) {
              res.code = 503;
              res.body = make_error_json("SERVICE_UNAVAILABLE",
                                         "DICOM server not configured");
              return res;
            }
            // Individual association lookup is not supported via the
            // dicom_server public API. Use GET /associations/active for
            // aggregate statistics.
            res.code = 501;
            res.body = make_error_json(
                "NOT_IMPLEMENTED",
                "Individual association lookup is not supported. "
                "Use GET /api/v1/associations/active for aggregate "
                "statistics.");
            return res;
          });
}
References kcenon::pacs::web::make_error_json().
Referenced by kcenon::pacs::web::rest_server::start_async().
register_audit_endpoints_impl()
void kcenon::pacs::web::endpoints::register_audit_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 184 of file audit_endpoints.cpp.
{
  // GET /api/v1/audit/logs - List audit log entries (paginated)
  CROW_ROUTE(app, "/api/v1/audit/logs")
      .methods(crow::HTTPMethod::GET)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        if (!ctx->database) {
          res.code = 503;
          res.body =
              make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
          return res;
        }
        // Parse pagination
        auto [limit, offset] = parse_pagination(req);
        // Build query from URL parameters
        storage::audit_query query;
        query.limit = limit;
        query.offset = offset;
        auto event_type = req.url_params.get("event_type");
        if (event_type) {
          query.event_type = event_type;
        }
        auto outcome = req.url_params.get("outcome");
        if (outcome) {
          query.outcome = outcome;
        }
        auto user_id = req.url_params.get("user_id");
        if (user_id) {
          query.user_id = user_id;
        }
        auto source_ae = req.url_params.get("source_ae");
        if (source_ae) {
          query.source_ae = source_ae;
        }
        auto patient_id = req.url_params.get("patient_id");
        if (patient_id) {
          query.patient_id = patient_id;
        }
        auto study_uid = req.url_params.get("study_uid");
        if (study_uid) {
          query.study_uid = study_uid;
        }
        auto date_from = req.url_params.get("date_from");
        if (date_from) {
          query.date_from = date_from;
        }
        auto date_to = req.url_params.get("date_to");
        if (date_to) {
          query.date_to = date_to;
        }
        // Check export format
        auto format_param = req.url_params.get("format");
        bool export_csv = format_param && std::string(format_param) == "csv";
        // Get total count (without pagination)
        storage::audit_query count_query = query;
        count_query.limit = 0;
        count_query.offset = 0;
        auto all_records_result = ctx->database->query_audit_log(count_query);
        if (!all_records_result.is_ok()) {
          res.code = 500;
          res.body = make_error_json("QUERY_ERROR",
                                     all_records_result.error().message);
          return res;
        }
        size_t total_count = all_records_result.value().size();
        // Get paginated results
        auto records_result = ctx->database->query_audit_log(query);
        if (!records_result.is_ok()) {
          res.code = 500;
          res.body = make_error_json("QUERY_ERROR",
                                     records_result.error().message);
          return res;
        }
        auto records = std::move(records_result.value());
        if (export_csv) {
          res.add_header("Content-Type", "text/csv");
          res.add_header("Content-Disposition",
                         "attachment; filename=\"audit_logs.csv\"");
          res.code = 200;
          res.body = audit_records_to_csv(records);
        } else {
          res.code = 200;
          res.body = audit_records_to_json(records, total_count);
        }
        return res;
      });
  // GET /api/v1/audit/logs/:id - Get specific audit log entry
  CROW_ROUTE(app, "/api/v1/audit/logs/<int>")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/, int pk) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            auto record = ctx->database->find_audit_by_pk(pk);
            if (!record) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Audit log entry not found");
              return res;
            }
            res.code = 200;
            res.body = audit_record_to_json(*record);
            return res;
          });
  // GET /api/v1/audit/export - Export audit logs (CSV or JSON)
  CROW_ROUTE(app, "/api/v1/audit/export")
      .methods(crow::HTTPMethod::GET)([ctx](const crow::request &req) {
        crow::response res;
        add_cors_headers(res, *ctx);
        if (!ctx->database) {
          res.add_header("Content-Type", "application/json");
          res.code = 503;
          res.body =
              make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
          return res;
        }
        // Build query from URL parameters (no pagination for export)
        storage::audit_query query;
        auto event_type = req.url_params.get("event_type");
        if (event_type) {
          query.event_type = event_type;
        }
        auto outcome = req.url_params.get("outcome");
        if (outcome) {
          query.outcome = outcome;
        }
        auto user_id = req.url_params.get("user_id");
        if (user_id) {
          query.user_id = user_id;
        }
        auto date_from = req.url_params.get("date_from");
        if (date_from) {
          query.date_from = date_from;
        }
        auto date_to = req.url_params.get("date_to");
        if (date_to) {
          query.date_to = date_to;
        }
        auto records_result = ctx->database->query_audit_log(query);
        if (!records_result.is_ok()) {
          res.add_header("Content-Type", "application/json");
          res.code = 500;
          res.body = make_error_json("QUERY_ERROR",
                                     records_result.error().message);
          return res;
        }
        auto records = std::move(records_result.value());
        // Check export format
        auto format_param = req.url_params.get("format");
        std::string format = format_param ? format_param : "json";
        if (format == "csv") {
          res.add_header("Content-Type", "text/csv");
          res.add_header("Content-Disposition",
                         "attachment; filename=\"audit_logs.csv\"");
          res.code = 200;
          res.body = audit_records_to_csv(records);
        } else {
          res.add_header("Content-Type", "application/json");
          res.add_header("Content-Disposition",
                         "attachment; filename=\"audit_logs.json\"");
          res.code = 200;
          res.body = audit_records_to_json(records, records.size());
        }
        return res;
      });
}
References kcenon::pacs::security::atna_coded_value::code, kcenon::pacs::storage::audit_query::limit, kcenon::pacs::web::make_error_json(), and kcenon::pacs::storage::audit_query::offset.
Referenced by kcenon::pacs::web::rest_server::start_async().
register_dicomweb_endpoints_impl()
void kcenon::pacs::web::endpoints::register_dicomweb_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 1817 of file dicomweb_endpoints.cpp.
{
    // ========================================================================
    // Study Retrieval
    // ========================================================================
    // GET /dicomweb/studies/{studyUID} - Retrieve entire study
    CROW_ROUTE(app, "/dicomweb/studies/<string>")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req, const std::string& study_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                // OAuth 2.0 / legacy auth check
                if (!check_dicomweb_auth(ctx, req, res,
                        {"dicomweb.read"})) {
                    return res;
                }
                if (!ctx->database) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                // Check Accept header
                auto accept = req.get_header_value("Accept");
                auto accept_infos = dicomweb::parse_accept_header(accept);
                // Check if metadata is requested
                if (dicomweb::is_acceptable(accept_infos,
                                            dicomweb::media_type::dicom_json)) {
                    auto files_result = ctx->database->get_study_files(study_uid);
                    if (!files_result.is_ok()) {
                        res.code = 500;
                        res.add_header("Content-Type", "application/json");
                        res.body = make_error_json("QUERY_ERROR",
                                                   files_result.error().message);
                        return res;
                    }
                    std::string bulk_uri = "/dicomweb/studies/" + study_uid +
                                           "/bulkdata/";
                    return build_metadata_response(files_result.value(), *ctx, bulk_uri);
                }
                // Return DICOM instances
                auto files_result = ctx->database->get_study_files(study_uid);
                if (!files_result.is_ok()) {
                    res.code = 500;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("QUERY_ERROR",
                                               files_result.error().message);
                    return res;
                }
                std::string base_uri = "/dicomweb/studies/" + study_uid;
                return build_multipart_dicom_response(files_result.value(), *ctx, base_uri);
            });
    // GET /dicomweb/studies/{studyUID}/metadata - Study metadata
    CROW_ROUTE(app, "/dicomweb/studies/<string>/metadata")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req, const std::string& study_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                // OAuth 2.0 / legacy auth check
                if (!check_dicomweb_auth(ctx, req, res,
                        {"dicomweb.read"})) {
                    return res;
                }
                if (!ctx->database) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                auto files_result = ctx->database->get_study_files(study_uid);
                if (!files_result.is_ok()) {
                    res.code = 500;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("QUERY_ERROR",
                                               files_result.error().message);
                    return res;
                }
                std::string bulk_uri = "/dicomweb/studies/" + study_uid +
                                       "/bulkdata/";
                return build_metadata_response(files_result.value(), *ctx, bulk_uri);
            });
    // ========================================================================
    // Series Retrieval
    // ========================================================================
    // GET /dicomweb/studies/{studyUID}/series/{seriesUID} - Retrieve series
    CROW_ROUTE(app, "/dicomweb/studies/<string>/series/<string>")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req,
                  const std::string& study_uid,
                  const std::string& series_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                if (!ctx->database) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                // Verify study exists
                auto study = ctx->database->find_study(study_uid);
                if (!study) {
                    res.code = 404;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("NOT_FOUND", "Study not found");
                    return res;
                }
                // Check Accept header
                auto accept = req.get_header_value("Accept");
                auto accept_infos = dicomweb::parse_accept_header(accept);
                // Check if metadata is requested
                if (dicomweb::is_acceptable(accept_infos,
                                            dicomweb::media_type::dicom_json)) {
                    auto files_result = ctx->database->get_series_files(series_uid);
                    if (!files_result.is_ok()) {
                        res.code = 500;
                        res.add_header("Content-Type", "application/json");
                        res.body = make_error_json("QUERY_ERROR",
                                                   files_result.error().message);
                        return res;
                    }
                    std::string bulk_uri = "/dicomweb/studies/" + study_uid +
                                           "/series/" + series_uid + "/bulkdata/";
                    return build_metadata_response(files_result.value(), *ctx, bulk_uri);
                }
                auto files_result = ctx->database->get_series_files(series_uid);
                if (!files_result.is_ok()) {
                    res.code = 500;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("QUERY_ERROR",
                                               files_result.error().message);
                    return res;
                }
                std::string base_uri = "/dicomweb/studies/" + study_uid +
                                       "/series/" + series_uid;
                return build_multipart_dicom_response(files_result.value(), *ctx, base_uri);
            });
    // GET /dicomweb/studies/{studyUID}/series/{seriesUID}/metadata
    CROW_ROUTE(app, "/dicomweb/studies/<string>/series/<string>/metadata")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& /*req*/,
                  const std::string& study_uid,
                  const std::string& series_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                if (!ctx->database) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                auto files_result = ctx->database->get_series_files(series_uid);
                if (!files_result.is_ok()) {
                    res.code = 500;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("QUERY_ERROR",
                                               files_result.error().message);
                    return res;
                }
                std::string bulk_uri = "/dicomweb/studies/" + study_uid +
                                       "/series/" + series_uid + "/bulkdata/";
                return build_metadata_response(files_result.value(), *ctx, bulk_uri);
            });
    // ========================================================================
    // Instance Retrieval
    // ========================================================================
    // GET /dicomweb/studies/{studyUID}/series/{seriesUID}/instances/{sopUID}
    CROW_ROUTE(app,
               "/dicomweb/studies/<string>/series/<string>/instances/<string>")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req,
                  const std::string& study_uid,
                  const std::string& series_uid,
                  const std::string& sop_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                if (!ctx->database) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                auto file_path_result = ctx->database->get_file_path(sop_uid);
                if (!file_path_result.is_ok()) {
                    res.code = 500;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("QUERY_ERROR",
                                               file_path_result.error().message);
                    return res;
                }
                const auto& file_path = file_path_result.value();
                if (!file_path) {
                    res.code = 404;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("NOT_FOUND", "Instance not found");
                    return res;
                }
                // Check Accept header
                auto accept = req.get_header_value("Accept");
                auto accept_infos = dicomweb::parse_accept_header(accept);
                // Check if metadata is requested
                if (dicomweb::is_acceptable(accept_infos,
                                            dicomweb::media_type::dicom_json)) {
                    std::vector<std::string> files = {*file_path};
                    std::string bulk_uri = "/dicomweb/studies/" + study_uid +
                                           "/series/" + series_uid +
                                           "/instances/" + sop_uid + "/bulkdata/";
                    return build_metadata_response(files, *ctx, bulk_uri);
                }
                // Return DICOM instance
                auto data = read_file_bytes(*file_path);
                if (data.empty()) {
                    res.code = 500;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("READ_ERROR",
                                               "Failed to read DICOM file");
                    return res;
                }
                res.code = 200;
                res.add_header("Content-Type",
                               std::string(dicomweb::media_type::dicom));
                res.body = std::string(reinterpret_cast<char*>(data.data()),
                                       data.size());
                return res;
            });
    // GET /dicomweb/studies/{studyUID}/series/{seriesUID}/instances/{sopUID}/metadata
    CROW_ROUTE(app,
               "/dicomweb/studies/<string>/series/<string>/instances/<string>/metadata")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& /*req*/,
                  const std::string& study_uid,
                  const std::string& series_uid,
                  const std::string& sop_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                if (!ctx->database) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                auto file_path_result = ctx->database->get_file_path(sop_uid);
                if (!file_path_result.is_ok()) {
                    res.code = 500;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("QUERY_ERROR",
                                               file_path_result.error().message);
                    return res;
                }
                const auto& file_path = file_path_result.value();
                if (!file_path) {
                    res.code = 404;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("NOT_FOUND", "Instance not found");
                    return res;
                }
                std::vector<std::string> files = {*file_path};
                std::string bulk_uri = "/dicomweb/studies/" + study_uid +
                                       "/series/" + series_uid +
                                       "/instances/" + sop_uid + "/bulkdata/";
                return build_metadata_response(files, *ctx, bulk_uri);
            });
    // ========================================================================
    // Frame Retrieval (WADO-RS)
    // ========================================================================
    // GET /dicomweb/studies/{studyUID}/series/{seriesUID}/instances/{sopUID}/frames/{frameNumbers}
    CROW_ROUTE(app,
               "/dicomweb/studies/<string>/series/<string>/instances/<string>/frames/<string>")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req,
                  const std::string& study_uid,
                  const std::string& series_uid,
                  const std::string& sop_uid,
                  const std::string& frame_list) {
                crow::response res;
                add_cors_headers(res, *ctx);
                if (!ctx->database) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                auto file_path_result = ctx->database->get_file_path(sop_uid);
                if (!file_path_result.is_ok()) {
                    res.code = 500;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("QUERY_ERROR",
                                               file_path_result.error().message);
                    return res;
                }
                const auto& file_path = file_path_result.value();
                if (!file_path) {
                    res.code = 404;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("NOT_FOUND", "Instance not found");
                    return res;
                }
                // Parse frame numbers
                auto frames = dicomweb::parse_frame_numbers(frame_list);
                if (frames.empty()) {
                    res.code = 400;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("INVALID_FRAME_LIST",
                                               "No valid frame numbers specified");
                    return res;
                }
                // Load DICOM file
                auto data = read_file_bytes(*file_path);
                if (data.empty()) {
                    res.code = 500;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("READ_ERROR",
                                               "Failed to read DICOM file");
                    return res;
                }
                auto dicom_result = core::dicom_file::from_bytes(
                    std::span<const uint8_t>(data.data(), data.size()));
                if (dicom_result.is_err()) {
                    res.code = 500;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("PARSE_ERROR",
                                               "Failed to parse DICOM file");
                    return res;
                }
                const auto& dataset = dicom_result.value().dataset();
                // Get image parameters
                auto rows_elem = dataset.get(core::tags::rows);
                auto cols_elem = dataset.get(core::tags::columns);
                auto bits_alloc_elem = dataset.get(core::tags::bits_allocated);
                auto samples_elem = dataset.get(core::tags::samples_per_pixel);
                // Number of Frames (0028,0008)
                constexpr core::dicom_tag number_of_frames_tag{0x0028, 0x0008};
                auto num_frames_elem = dataset.get(number_of_frames_tag);
                auto pixel_data_elem = dataset.get(core::tags::pixel_data);
                if (!rows_elem || !cols_elem || !pixel_data_elem) {
                    res.code = 400;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("NOT_IMAGE",
                                               "Instance does not contain image data");
                    return res;
                }
                uint16_t rows = rows_elem->as_numeric<uint16_t>().unwrap_or(0);
                uint16_t cols = cols_elem->as_numeric<uint16_t>().unwrap_or(0);
                uint16_t bits_allocated = bits_alloc_elem ?
                    bits_alloc_elem->as_numeric<uint16_t>().unwrap_or(16) : 16;
                uint16_t samples_per_pixel = samples_elem ?
                    samples_elem->as_numeric<uint16_t>().unwrap_or(1) : 1;
                uint32_t num_frames = 1;
                if (num_frames_elem) {
                    try {
                        num_frames = std::stoul(num_frames_elem->as_string().unwrap_or("1"));
                    } catch (...) {}
                }
                // Calculate frame size
                size_t frame_size = static_cast<size_t>(rows) * cols *
                                    samples_per_pixel * ((bits_allocated + 7) / 8);
                auto pixel_data = pixel_data_elem->raw_data();
                // Check Accept header
                auto accept = req.get_header_value("Accept");
                // Build multipart response for multiple frames
                dicomweb::multipart_builder builder(
                    dicomweb::media_type::octet_stream);
                for (uint32_t frame_num : frames) {
                    if (frame_num > num_frames) {
                        // Skip invalid frame numbers
                        continue;
                    }
                    auto frame_data = dicomweb::extract_frame(
                        pixel_data, frame_num, frame_size);
                    if (!frame_data.empty()) {
                        std::string location = "/dicomweb/studies/" + study_uid +
                                               "/series/" + series_uid +
                                               "/instances/" + sop_uid +
                                               "/frames/" + std::to_string(frame_num);
                        builder.add_part_with_location(std::move(frame_data), location);
                    }
                }
                if (builder.empty()) {
                    res.code = 404;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("NOT_FOUND",
                                               "No valid frames found");
                    return res;
                }
                // Return single part or multipart
                if (builder.size() == 1) {
                    // Single frame - return directly
                    auto body = builder.build();
                    res.code = 200;
                    res.add_header("Content-Type",
                                   std::string(dicomweb::media_type::octet_stream));
                    // Extract just the data part from multipart
                    auto frame_data = dicomweb::extract_frame(
                        pixel_data, frames[0], frame_size);
                    res.body = std::string(
                        reinterpret_cast<char*>(frame_data.data()),
                        frame_data.size());
                } else {
                    // Multiple frames - return multipart
                    res.code = 200;
                    res.add_header("Content-Type", builder.content_type_header());
                    res.body = builder.build();
                }
                return res;
            });
    // ========================================================================
    // Rendered Images (WADO-RS)
    // ========================================================================
    // GET /dicomweb/studies/{studyUID}/series/{seriesUID}/instances/{sopUID}/rendered
    CROW_ROUTE(app,
               "/dicomweb/studies/<string>/series/<string>/instances/<string>/rendered")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req,
                  const std::string& study_uid,
                  const std::string& series_uid,
                  const std::string& sop_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                if (!ctx->database) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                auto file_path_result = ctx->database->get_file_path(sop_uid);
                if (!file_path_result.is_ok()) {
                    res.code = 500;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("QUERY_ERROR",
                                               file_path_result.error().message);
                    return res;
                }
                const auto& file_path = file_path_result.value();
                if (!file_path) {
                    res.code = 404;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("NOT_FOUND", "Instance not found");
                    return res;
                }
                // Parse rendering parameters
                auto accept = req.get_header_value("Accept");
                auto params = dicomweb::parse_rendered_params(req.raw_url, accept);
                // Render image
                auto result = dicomweb::render_dicom_image(*file_path, params);
                if (!result.success) {
                    res.code = 400;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("RENDER_ERROR", result.error_message);
                    return res;
                }
                res.code = 200;
                res.add_header("Content-Type", result.content_type);
                res.body = std::string(
                    reinterpret_cast<char*>(result.data.data()),
                    result.data.size());
                return res;
            });
    // GET /dicomweb/studies/{studyUID}/series/{seriesUID}/instances/{sopUID}/frames/{frameNumber}/rendered
    CROW_ROUTE(app,
               "/dicomweb/studies/<string>/series/<string>/instances/<string>/frames/<string>/rendered")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req,
                  const std::string& study_uid,
                  const std::string& series_uid,
                  const std::string& sop_uid,
                  const std::string& frame_str) {
                crow::response res;
                add_cors_headers(res, *ctx);
                if (!ctx->database) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                auto file_path_result = ctx->database->get_file_path(sop_uid);
                if (!file_path_result.is_ok()) {
                    res.code = 500;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("QUERY_ERROR",
                                               file_path_result.error().message);
                    return res;
                }
                const auto& file_path = file_path_result.value();
                if (!file_path) {
                    res.code = 404;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("NOT_FOUND", "Instance not found");
                    return res;
                }
                // Parse frame number
                uint32_t frame_num = 1;
                try {
                    frame_num = std::stoul(frame_str);
                    if (frame_num == 0) frame_num = 1;
                } catch (...) {
                    res.code = 400;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("INVALID_FRAME",
                                               "Invalid frame number");
                    return res;
                }
                // Parse rendering parameters and set frame
                auto accept = req.get_header_value("Accept");
                auto params = dicomweb::parse_rendered_params(req.raw_url, accept);
                params.frame = frame_num;
                // Render image
                auto result = dicomweb::render_dicom_image(*file_path, params);
                if (!result.success) {
                    res.code = 400;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("RENDER_ERROR", result.error_message);
                    return res;
                }
                res.code = 200;
                res.add_header("Content-Type", result.content_type);
                res.body = std::string(
                    reinterpret_cast<char*>(result.data.data()),
                    result.data.size());
                return res;
            });
    // ========================================================================
    // STOW-RS (Store Over the Web)
    // ========================================================================
    // POST /dicomweb/studies - Store instances (new study)
    CROW_ROUTE(app, "/dicomweb/studies")
        .methods(crow::HTTPMethod::POST)(
            [ctx](const crow::request& req) {
                crow::response res;
                add_cors_headers(res, *ctx);
                // OAuth 2.0 / legacy auth check (write scope)
                if (!check_dicomweb_auth(ctx, req, res,
                        {"dicomweb.write"})) {
                    return res;
                }
                if (!ctx->database || !ctx->file_storage) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               !ctx->database
                                                   ? "Database not configured"
                                                   : "File storage not configured");
                    return res;
                }
                // Parse Content-Type header
                auto content_type = req.get_header_value("Content-Type");
                if (content_type.empty() ||
                    content_type.find("multipart/related") == std::string::npos) {
                    res.code = 415; // Unsupported Media Type
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json(
                        "UNSUPPORTED_MEDIA_TYPE",
                        "Content-Type must be multipart/related");
                    return res;
                }
                // Parse multipart body
                auto parse_result = dicomweb::multipart_parser::parse(
                    content_type, req.body);
                if (!parse_result) {
                    res.code = 400;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json(
                        parse_result.error->code,
                        parse_result.error->message);
                    return res;
                }
                if (parse_result.parts.empty()) {
                    res.code = 400;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json(
                        "NO_INSTANCES",
                        "No DICOM instances in request body");
                    return res;
                }
                // Process each part
                dicomweb::store_response store_response;
                for (const auto& part : parse_result.parts) {
                    dicomweb::store_instance_result result;
                    // Only process application/dicom parts
                    if (part.content_type.find("application/dicom") ==
                        std::string::npos) {
                        continue;
                    }
                    // Parse DICOM from memory
                    auto dicom_result = core::dicom_file::from_bytes(
                        std::span<const uint8_t>(part.data.data(), part.data.size()));
                    if (dicom_result.is_err()) {
                        result.success = false;
                        result.error_code = "INVALID_DATA";
                        result.error_message = "Failed to parse DICOM data";
                        store_response.failed_instances.push_back(
                            std::move(result));
                        continue;
                    }
                    const auto& dataset = dicom_result.value().dataset();
                    // Validate instance
                    auto validation = dicomweb::validate_instance(dataset);
                    if (!validation) {
                        result.success = false;
                        result.error_code = validation.error_code;
                        result.error_message = validation.error_message;
                        // Try to extract UIDs for error reporting
                        if (auto elem = dataset.get(core::tags::sop_class_uid)) {
                            result.sop_class_uid = elem->as_string().unwrap_or("");
                        }
                        if (auto elem = dataset.get(core::tags::sop_instance_uid)) {
                            result.sop_instance_uid = elem->as_string().unwrap_or("");
                        }
                        store_response.failed_instances.push_back(
                            std::move(result));
                        continue;
                    }
                    // Extract UIDs
                    auto sop_class_elem = dataset.get(core::tags::sop_class_uid);
                    auto sop_instance_elem = dataset.get(core::tags::sop_instance_uid);
                    auto study_uid_elem = dataset.get(core::tags::study_instance_uid);
                    auto series_uid_elem = dataset.get(core::tags::series_instance_uid);
                    result.sop_class_uid = sop_class_elem->as_string().unwrap_or("");
                    result.sop_instance_uid = sop_instance_elem->as_string().unwrap_or("");
                    std::string study_uid = study_uid_elem->as_string().unwrap_or("");
                    std::string series_uid = series_uid_elem->as_string().unwrap_or("");
                    // Check for duplicate
                    auto existing_result = ctx->database->get_file_path(
                        result.sop_instance_uid);
                    if (existing_result.is_ok() && existing_result.value()) {
                        result.success = false;
                        result.error_code = "DUPLICATE";
                        result.error_message = "Instance already exists";
                        store_response.failed_instances.push_back(
                            std::move(result));
                        continue;
                    }
                    // Store instance via file_storage and index in database
                    if (!store_instance_to_storage(ctx, dataset, result)) {
                        store_response.failed_instances.push_back(
                            std::move(result));
                        continue;
                    }
                    result.success = true;
                    result.retrieve_url = "/dicomweb/studies/" + study_uid +
                                          "/series/" + series_uid +
                                          "/instances/" + result.sop_instance_uid;
                    store_response.referenced_instances.push_back(
                        std::move(result));
                }
                // Build response
                std::string base_url;  // Empty base URL, client should use relative URLs
                res.add_header("Content-Type",
                               std::string(dicomweb::media_type::dicom_json));
                if (store_response.all_failed()) {
                    res.code = 409; // Conflict
                } else if (store_response.partial_success()) {
                    res.code = 202; // Accepted with warnings
                } else {
                    res.code = 200; // OK
                }
                res.body = dicomweb::build_store_response_json(
                    store_response, base_url);
                return res;
            });
    // POST /dicomweb/studies/{studyUID} - Store instances to existing study
    CROW_ROUTE(app, "/dicomweb/studies/<string>")
        .methods(crow::HTTPMethod::POST)(
            [ctx](const crow::request& req, const std::string& target_study_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                // OAuth 2.0 / legacy auth check (write scope)
                if (!check_dicomweb_auth(ctx, req, res,
                        {"dicomweb.write"})) {
                    return res;
                }
                if (!ctx->database || !ctx->file_storage) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               !ctx->database
                                                   ? "Database not configured"
                                                   : "File storage not configured");
                    return res;
                }
                // Parse Content-Type header
                auto content_type = req.get_header_value("Content-Type");
                if (content_type.empty() ||
                    content_type.find("multipart/related") == std::string::npos) {
                    res.code = 415;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json(
                        "UNSUPPORTED_MEDIA_TYPE",
                        "Content-Type must be multipart/related");
                    return res;
                }
                // Parse multipart body
                auto parse_result = dicomweb::multipart_parser::parse(
                    content_type, req.body);
                if (!parse_result) {
                    res.code = 400;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json(
                        parse_result.error->code,
                        parse_result.error->message);
                    return res;
                }
                if (parse_result.parts.empty()) {
                    res.code = 400;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json(
                        "NO_INSTANCES",
                        "No DICOM instances in request body");
                    return res;
                }
                // Process each part
                dicomweb::store_response store_response;
                for (const auto& part : parse_result.parts) {
                    dicomweb::store_instance_result result;
                    // Only process application/dicom parts
                    if (part.content_type.find("application/dicom") ==
                        std::string::npos) {
                        continue;
                    }
                    // Parse DICOM from memory
                    auto dicom_result = core::dicom_file::from_bytes(
                        std::span<const uint8_t>(part.data.data(), part.data.size()));
                    if (dicom_result.is_err()) {
                        result.success = false;
                        result.error_code = "INVALID_DATA";
                        result.error_message = "Failed to parse DICOM data";
                        store_response.failed_instances.push_back(
                            std::move(result));
                        continue;
                    }
                    const auto& dataset = dicom_result.value().dataset();
                    // Validate instance with target study UID check
                    auto validation = dicomweb::validate_instance(
                        dataset, target_study_uid);
                    if (!validation) {
                        result.success = false;
                        result.error_code = validation.error_code;
                        result.error_message = validation.error_message;
                        if (auto elem = dataset.get(core::tags::sop_class_uid)) {
                            result.sop_class_uid = elem->as_string().unwrap_or("");
                        }
                        if (auto elem = dataset.get(core::tags::sop_instance_uid)) {
                            result.sop_instance_uid = elem->as_string().unwrap_or("");
                        }
                        store_response.failed_instances.push_back(
                            std::move(result));
                        continue;
                    }
                    // Extract UIDs
                    auto sop_class_elem = dataset.get(core::tags::sop_class_uid);
                    auto sop_instance_elem = dataset.get(core::tags::sop_instance_uid);
                    auto series_uid_elem = dataset.get(core::tags::series_instance_uid);
                    result.sop_class_uid = sop_class_elem->as_string().unwrap_or("");
                    result.sop_instance_uid = sop_instance_elem->as_string().unwrap_or("");
                    std::string series_uid = series_uid_elem->as_string().unwrap_or("");
                    // Check for duplicate
                    auto existing_result = ctx->database->get_file_path(
                        result.sop_instance_uid);
                    if (existing_result.is_ok() && existing_result.value()) {
                        result.success = false;
                        result.error_code = "DUPLICATE";
                        result.error_message = "Instance already exists";
                        store_response.failed_instances.push_back(
                            std::move(result));
                        continue;
                    }
                    // Store instance via file_storage and index in database
                    if (!store_instance_to_storage(ctx, dataset, result)) {
                        store_response.failed_instances.push_back(
                            std::move(result));
                        continue;
                    }
                    result.success = true;
                    result.retrieve_url = "/dicomweb/studies/" + target_study_uid +
                                          "/series/" + series_uid +
                                          "/instances/" + result.sop_instance_uid;
                    store_response.referenced_instances.push_back(
                        std::move(result));
                }
                // Build response
                std::string base_url;  // Empty base URL, client should use relative URLs
                res.add_header("Content-Type",
                               std::string(dicomweb::media_type::dicom_json));
                if (store_response.all_failed()) {
                    res.code = 409; // Conflict
                } else if (store_response.partial_success()) {
                    res.code = 202; // Accepted with warnings
                } else {
                    res.code = 200; // OK
                }
                res.body = dicomweb::build_store_response_json(
                    store_response, base_url);
                return res;
            });
    // ========================================================================
    // QIDO-RS (Query based on ID for DICOM Objects)
    // ========================================================================
    // GET /dicomweb/studies - Search for studies
    CROW_ROUTE(app, "/dicomweb/studies")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req) {
                crow::response res;
                add_cors_headers(res, *ctx);
                res.add_header("Content-Type",
                               std::string(dicomweb::media_type::dicom_json));
                // OAuth 2.0 / legacy auth check (read or search scope)
                if (!check_dicomweb_auth(ctx, req, res,
                        {"dicomweb.read", "dicomweb.search"})) {
                    return res;
                }
                if (!ctx->database) {
                    res.code = 503;
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                // Parse query parameters
                auto query = dicomweb::parse_study_query_params(req.raw_url);
                // Set default limit if not specified (prevent unlimited queries)
                if (query.limit == 0) {
                    query.limit = 100;
                }
                // Execute search
                auto studies_result = ctx->database->search_studies(query);
                if (!studies_result.is_ok()) {
                    res.code = 500;
                    res.body = make_error_json("QUERY_ERROR",
                                               studies_result.error().message);
                    return res;
                }
                // Build response
                std::ostringstream oss;
                oss << "[";
                bool first = true;
                for (const auto& study : studies_result.value()) {
                    if (!first) oss << ",";
                    first = false;
                    // Get patient info for this study
                    std::string patient_id;
                    std::string patient_name;
                    if (auto patient = ctx->database->find_patient_by_pk(study.patient_pk)) {
                        patient_id = patient->patient_id;
                        patient_name = patient->patient_name;
                    }
                    oss << dicomweb::study_record_to_dicom_json(
                        study, patient_id, patient_name);
                }
                oss << "]";
                res.code = 200;
                res.body = oss.str();
                return res;
            });
    // GET /dicomweb/series - Search for all series
    CROW_ROUTE(app, "/dicomweb/series")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req) {
                crow::response res;
                add_cors_headers(res, *ctx);
                res.add_header("Content-Type",
                               std::string(dicomweb::media_type::dicom_json));
                if (!ctx->database) {
                    res.code = 503;
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                // Parse query parameters
                auto query = dicomweb::parse_series_query_params(req.raw_url);
                // Set default limit if not specified
                if (query.limit == 0) {
                    query.limit = 100;
                }
                // Execute search
                auto series_list_result = ctx->database->search_series(query);
                if (!series_list_result.is_ok()) {
                    res.code = 500;
                    res.body = make_error_json("QUERY_ERROR",
                                               series_list_result.error().message);
                    return res;
                }
                // Build response
                std::ostringstream oss;
                oss << "[";
                bool first = true;
                for (const auto& series : series_list_result.value()) {
                    if (!first) oss << ",";
                    first = false;
                    // Get study UID for this series
                    std::string study_uid;
                    if (auto study = ctx->database->find_study_by_pk(series.study_pk)) {
                        study_uid = study->study_uid;
                    }
                    oss << dicomweb::series_record_to_dicom_json(series, study_uid);
                }
                oss << "]";
                res.code = 200;
                res.body = oss.str();
                return res;
            });
    // GET /dicomweb/instances - Search for all instances
    CROW_ROUTE(app, "/dicomweb/instances")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req) {
                crow::response res;
                add_cors_headers(res, *ctx);
                res.add_header("Content-Type",
                               std::string(dicomweb::media_type::dicom_json));
                if (!ctx->database) {
                    res.code = 503;
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                // Parse query parameters
                auto query = dicomweb::parse_instance_query_params(req.raw_url);
                // Set default limit if not specified
                if (query.limit == 0) {
                    query.limit = 100;
                }
                // Execute search
                auto instances_result = ctx->database->search_instances(query);
                if (!instances_result.is_ok()) {
                    res.code = 500;
                    res.body = make_error_json("QUERY_ERROR",
                                               instances_result.error().message);
                    return res;
                }
                // Build response
                std::ostringstream oss;
                oss << "[";
                bool first = true;
                for (const auto& instance : instances_result.value()) {
                    if (!first) oss << ",";
                    first = false;
                    // Get series and study UIDs
                    std::string series_uid;
                    std::string study_uid;
                    if (auto series = ctx->database->find_series_by_pk(instance.series_pk)) {
                        series_uid = series->series_uid;
                        if (auto study = ctx->database->find_study_by_pk(series->study_pk)) {
                            study_uid = study->study_uid;
                        }
                    }
                    oss << dicomweb::instance_record_to_dicom_json(
                        instance, series_uid, study_uid);
                }
                oss << "]";
                res.code = 200;
                res.body = oss.str();
                return res;
            });
    // GET /dicomweb/studies/{studyUID}/series - Search series in a study (QIDO-RS)
    CROW_ROUTE(app, "/dicomweb/studies/<string>/series")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req, const std::string& study_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                res.add_header("Content-Type",
                               std::string(dicomweb::media_type::dicom_json));
                // OAuth 2.0 / legacy auth check
                if (!check_dicomweb_auth(ctx, req, res,
                        {"dicomweb.read", "dicomweb.search"})) {
                    return res;
                }
                if (!ctx->database) {
                    res.code = 503;
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                // Verify study exists
                auto study = ctx->database->find_study(study_uid);
                if (!study) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Study not found");
                    return res;
                }
                // Parse query parameters and add study filter
                auto query = dicomweb::parse_series_query_params(req.raw_url);
                query.study_uid = study_uid;
                // Set default limit if not specified
                if (query.limit == 0) {
                    query.limit = 100;
                }
                // Execute search
                auto series_list_result = ctx->database->search_series(query);
                if (!series_list_result.is_ok()) {
                    res.code = 500;
                    res.body = make_error_json("QUERY_ERROR",
                                               series_list_result.error().message);
                    return res;
                }
                // Build response
                std::ostringstream oss;
                oss << "[";
                bool first = true;
                for (const auto& series : series_list_result.value()) {
                    if (!first) oss << ",";
                    first = false;
                    oss << dicomweb::series_record_to_dicom_json(series, study_uid);
                }
                oss << "]";
                res.code = 200;
                res.body = oss.str();
                return res;
            });
    // GET /dicomweb/studies/{studyUID}/instances - Search instances in a study (QIDO-RS)
    CROW_ROUTE(app, "/dicomweb/studies/<string>/instances")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req, const std::string& study_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                res.add_header("Content-Type",
                               std::string(dicomweb::media_type::dicom_json));
                // OAuth 2.0 / legacy auth check
                if (!check_dicomweb_auth(ctx, req, res,
                        {"dicomweb.read", "dicomweb.search"})) {
                    return res;
                }
                if (!ctx->database) {
                    res.code = 503;
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                // Verify study exists
                auto study = ctx->database->find_study(study_uid);
                if (!study) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Study not found");
                    return res;
                }
                // Get all series in this study and then instances
                storage::series_query series_query;
                series_query.study_uid = study_uid;
                auto series_list_result = ctx->database->search_series(series_query);
                if (!series_list_result.is_ok()) {
                    res.code = 500;
                    res.body = make_error_json("QUERY_ERROR",
                                               series_list_result.error().message);
                    return res;
                }
                // Parse query parameters for additional filters
                auto inst_query = dicomweb::parse_instance_query_params(req.raw_url);
                if (inst_query.limit == 0) {
                    inst_query.limit = 100;
                }
                // Collect instances from all series
                std::ostringstream oss;
                oss << "[";
                bool first = true;
                size_t count = 0;
                size_t skipped = 0;
                for (const auto& series : series_list_result.value()) {
                    if (count >= inst_query.limit) break;
                    // Search instances in this series
                    storage::instance_query query;
                    query.series_uid = series.series_uid;
                    if (inst_query.sop_uid.has_value()) {
                        query.sop_uid = inst_query.sop_uid;
                    }
                    if (inst_query.sop_class_uid.has_value()) {
                        query.sop_class_uid = inst_query.sop_class_uid;
                    }
                    if (inst_query.instance_number.has_value()) {
                        query.instance_number = inst_query.instance_number;
                    }
                    query.limit = inst_query.limit - count;
                    auto instances_result = ctx->database->search_instances(query);
                    if (!instances_result.is_ok()) {
                        continue;
                    }
                    for (const auto& instance : instances_result.value()) {
                        // Handle offset
                        if (skipped < inst_query.offset) {
                            ++skipped;
                            continue;
                        }
                        if (count >= inst_query.limit) break;
                        if (!first) oss << ",";
                        first = false;
                        oss << dicomweb::instance_record_to_dicom_json(
                            instance, series.series_uid, study_uid);
                        ++count;
                    }
                }
                oss << "]";
                res.code = 200;
                res.body = oss.str();
                return res;
            });
    // GET /dicomweb/studies/{studyUID}/series/{seriesUID}/instances - Search instances in a series (QIDO-RS)
    CROW_ROUTE(app, "/dicomweb/studies/<string>/series/<string>/instances")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req,
                  const std::string& study_uid,
                  const std::string& series_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                res.add_header("Content-Type",
                               std::string(dicomweb::media_type::dicom_json));
                // OAuth 2.0 / legacy auth check
                if (!check_dicomweb_auth(ctx, req, res,
                        {"dicomweb.read", "dicomweb.search"})) {
                    return res;
                }
                if (!ctx->database) {
                    res.code = 503;
                    res.body = make_error_json("DATABASE_UNAVAILABLE",
                                               "Database not configured");
                    return res;
                }
                // Verify study exists
                auto study = ctx->database->find_study(study_uid);
                if (!study) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Study not found");
                    return res;
                }
                // Verify series exists
                auto series = ctx->database->find_series(series_uid);
                if (!series) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Series not found");
                    return res;
                }
                // Parse query parameters and add series filter
                auto query = dicomweb::parse_instance_query_params(req.raw_url);
                query.series_uid = series_uid;
                // Set default limit if not specified
                if (query.limit == 0) {
                    query.limit = 100;
                }
                // Execute search
                auto instances_result = ctx->database->search_instances(query);
                if (!instances_result.is_ok()) {
                    res.code = 500;
                    res.body = make_error_json("QUERY_ERROR",
                                               instances_result.error().message);
                    return res;
                }
                // Build response
                std::ostringstream oss;
                oss << "[";
                bool first = true;
                for (const auto& instance : instances_result.value()) {
                    if (!first) oss << ",";
                    first = false;
                    oss << dicomweb::instance_record_to_dicom_json(
                        instance, series_uid, study_uid);
                }
                oss << "]";
                res.code = 200;
                res.body = oss.str();
                return res;
            });
    // ========================================================================
    // CORS Preflight Handler for DICOMweb
    // ========================================================================
    CROW_ROUTE(app, "/dicomweb/<path>")
        .methods(crow::HTTPMethod::OPTIONS)(
            [ctx](const crow::request& /*req*/, const std::string& /*path*/) {
                crow::response res(204);
                if (ctx->config) {
                    res.add_header("Access-Control-Allow-Origin",
                                   ctx->config->cors_allowed_origins);
                }
                res.add_header("Access-Control-Allow-Methods",
                               "GET, POST, OPTIONS");
                res.add_header("Access-Control-Allow-Headers",
                               "Content-Type, Accept, Authorization");
                res.add_header("Access-Control-Max-Age", "86400");
                return res;
            });
}
References kcenon::pacs::web::dicomweb::multipart_builder::add_part_with_location(), kcenon::pacs::web::dicomweb::store_response::all_failed(), kcenon::pacs::core::tags::bits_allocated, kcenon::pacs::web::dicomweb::multipart_builder::build(), kcenon::pacs::web::dicomweb::build_store_response_json(), kcenon::pacs::security::atna_coded_value::code, kcenon::pacs::core::tags::columns, kcenon::pacs::web::dicomweb::multipart_builder::content_type_header(), kcenon::pacs::web::dicomweb::media_type::dicom, kcenon::pacs::web::dicomweb::media_type::dicom_json, kcenon::pacs::web::dicomweb::multipart_builder::empty(), kcenon::pacs::web::dicomweb::store_instance_result::error_code, kcenon::pacs::web::dicomweb::store_instance_result::error_message, kcenon::pacs::web::dicomweb::extract_frame(), kcenon::pacs::web::dicomweb::store_response::failed_instances, kcenon::pacs::core::dicom_file::from_bytes(), kcenon::pacs::web::dicomweb::instance_record_to_dicom_json(), kcenon::pacs::web::dicomweb::is_acceptable(), kcenon::pacs::web::make_error_json(), kcenon::pacs::web::dicomweb::media_type::octet_stream, kcenon::pacs::web::dicomweb::multipart_parser::parse(), kcenon::pacs::web::dicomweb::parse_accept_header(), kcenon::pacs::web::dicomweb::parse_frame_numbers(), kcenon::pacs::web::dicomweb::parse_instance_query_params(), kcenon::pacs::web::dicomweb::parse_rendered_params(), kcenon::pacs::web::dicomweb::parse_series_query_params(), kcenon::pacs::web::dicomweb::parse_study_query_params(), kcenon::pacs::web::dicomweb::store_response::partial_success(), kcenon::pacs::core::tags::pixel_data, kcenon::pacs::web::dicomweb::store_response::referenced_instances, kcenon::pacs::web::dicomweb::render_dicom_image(), kcenon::pacs::web::dicomweb::store_instance_result::retrieve_url, kcenon::pacs::core::tags::rows, kcenon::pacs::core::tags::samples_per_pixel, kcenon::pacs::core::tags::series_instance_uid, kcenon::pacs::web::dicomweb::series_record_to_dicom_json(), kcenon::pacs::web::dicomweb::multipart_builder::size(), kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::web::dicomweb::store_instance_result::sop_class_uid, kcenon::pacs::core::tags::sop_instance_uid, kcenon::pacs::web::dicomweb::store_instance_result::sop_instance_uid, kcenon::pacs::core::tags::study_instance_uid, kcenon::pacs::web::dicomweb::study_record_to_dicom_json(), kcenon::pacs::storage::series_query::study_uid, kcenon::pacs::web::dicomweb::store_instance_result::success, and kcenon::pacs::web::dicomweb::validate_instance().
Referenced by kcenon::pacs::web::rest_server::start_async().
register_jobs_endpoints_impl()
void kcenon::pacs::web::endpoints::register_jobs_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 469 of file jobs_endpoints.cpp.
{
    // GET /api/v1/jobs - List jobs (paginated with filters)
    CROW_ROUTE(app, "/api/v1/jobs")
        .methods(crow::HTTPMethod::GET)([ctx](const crow::request& req) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->job_manager) {
                res.code = 503;
                res.body = make_error_json("SERVICE_UNAVAILABLE",
                                           "Job manager not configured");
                return res;
            }
            // Parse pagination
            auto [limit, offset] = parse_pagination(req);
            // Parse filters
            std::optional<client::job_status> status_filter;
            std::optional<client::job_type> type_filter;
            auto status_param = req.url_params.get("status");
            if (status_param) {
                status_filter = client::job_status_from_string(status_param);
            }
            auto type_param = req.url_params.get("type");
            if (type_param) {
                type_filter = client::job_type_from_string(type_param);
            }
            // Get jobs with filters
            auto jobs = ctx->job_manager->list_jobs(status_filter, type_filter,
                                                     limit, offset);
            // Get total count (without pagination for now, we use jobs.size())
            // TODO: Add count method to job_manager for accurate total
            size_t total_count = jobs.size();
            res.code = 200;
            res.body = jobs_to_json(jobs, total_count);
            return res;
        });
    // POST /api/v1/jobs - Create a new job
    CROW_ROUTE(app, "/api/v1/jobs")
        .methods(crow::HTTPMethod::POST)([ctx](const crow::request& req) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->job_manager) {
                res.code = 503;
                res.body = make_error_json("SERVICE_UNAVAILABLE",
                                           "Job manager not configured");
                return res;
            }
            // Parse job type
            auto type_str = get_json_string_value(req.body, "type");
            if (type_str.empty()) {
                res.code = 400;
                res.body = make_error_json("INVALID_REQUEST", "type is required");
                return res;
            }
            auto type = client::job_type_from_string(type_str);
            // Parse priority (optional, defaults to normal)
            auto priority_str = get_json_string_value(req.body, "priority");
            auto priority = priority_str.empty()
                ? client::job_priority::normal
                : client::job_priority_from_string(priority_str);
            std::string job_id;
            // Create job based on type
            switch (type) {
                case client::job_type::retrieve: {
                    auto source_node_id = get_json_string_value(req.body, "source_node_id");
                    auto study_uid = get_json_string_value(req.body, "study_uid");
                    if (source_node_id.empty()) {
                        res.code = 400;
                        res.body = make_error_json("INVALID_REQUEST",
                                                   "source_node_id is required for retrieve job");
                        return res;
                    }
                    if (study_uid.empty()) {
                        res.code = 400;
                        res.body = make_error_json("INVALID_REQUEST",
                                                   "study_uid is required for retrieve job");
                        return res;
                    }
                    auto series_uid = get_json_string_value(req.body, "series_uid");
                    std::optional<std::string_view> series_opt;
                    if (!series_uid.empty()) {
                        series_opt = series_uid;
                    }
                    job_id = ctx->job_manager->create_retrieve_job(
                        source_node_id, study_uid, series_opt, priority);
                    break;
                }
                case client::job_type::store: {
                    auto destination_node_id = get_json_string_value(req.body, "destination_node_id");
                    auto instance_uids = get_json_string_array(req.body, "instance_uids");
                    if (destination_node_id.empty()) {
                        res.code = 400;
                        res.body = make_error_json("INVALID_REQUEST",
                                                   "destination_node_id is required for store job");
                        return res;
                    }
                    if (instance_uids.empty()) {
                        res.code = 400;
                        res.body = make_error_json("INVALID_REQUEST",
                                                   "instance_uids is required for store job");
                        return res;
                    }
                    job_id = ctx->job_manager->create_store_job(
                        destination_node_id, instance_uids, priority);
                    break;
                }
                case client::job_type::query: {
                    auto node_id = get_json_string_value(req.body, "node_id");
                    auto query_level = get_json_string_value(req.body, "query_level");
                    if (node_id.empty()) {
                        res.code = 400;
                        res.body = make_error_json("INVALID_REQUEST",
                                                   "node_id is required for query job");
                        return res;
                    }
                    if (query_level.empty()) {
                        query_level = "STUDY";  // Default to study level
                    }
                    // Parse query keys (simplified - in production use proper JSON parser)
                    std::unordered_map<std::string, std::string> query_keys;
                    auto patient_id = get_json_string_value(req.body, "patient_id");
                    if (!patient_id.empty()) {
                        query_keys["PatientID"] = patient_id;
                    }
                    auto patient_name = get_json_string_value(req.body, "patient_name");
                    if (!patient_name.empty()) {
                        query_keys["PatientName"] = patient_name;
                    }
                    job_id = ctx->job_manager->create_query_job(
                        node_id, query_level, query_keys, priority);
                    break;
                }
                case client::job_type::sync: {
                    auto source_node_id = get_json_string_value(req.body, "source_node_id");
                    if (source_node_id.empty()) {
                        res.code = 400;
                        res.body = make_error_json("INVALID_REQUEST",
                                                   "source_node_id is required for sync job");
                        return res;
                    }
                    auto patient_id = get_json_string_value(req.body, "patient_id");
                    std::optional<std::string_view> patient_opt;
                    if (!patient_id.empty()) {
                        patient_opt = patient_id;
                    }
                    job_id = ctx->job_manager->create_sync_job(
                        source_node_id, patient_opt, priority);
                    break;
                }
                case client::job_type::prefetch: {
                    auto source_node_id = get_json_string_value(req.body, "source_node_id");
                    auto patient_id = get_json_string_value(req.body, "patient_id");
                    if (source_node_id.empty()) {
                        res.code = 400;
                        res.body = make_error_json("INVALID_REQUEST",
                                                   "source_node_id is required for prefetch job");
                        return res;
                    }
                    if (patient_id.empty()) {
                        res.code = 400;
                        res.body = make_error_json("INVALID_REQUEST",
                                                   "patient_id is required for prefetch job");
                        return res;
                    }
                    job_id = ctx->job_manager->create_prefetch_job(
                        source_node_id, patient_id, priority);
                    break;
                }
                default: {
                    res.code = 400;
                    res.body = make_error_json("INVALID_REQUEST",
                                               "Unsupported job type: " + type_str);
                    return res;
                }
            }
            // Retrieve and return the created job
            auto created_job = ctx->job_manager->get_job(job_id);
            if (!created_job) {
                res.code = 201;
                res.body = R"({"job_id":")" + json_escape(job_id) + R"(","status":"pending"})";
                return res;
            }
            res.code = 201;
            res.body = job_to_json(*created_job);
            return res;
        });
    // GET /api/v1/jobs/<jobId> - Get a specific job
    CROW_ROUTE(app, "/api/v1/jobs/<string>")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& /*req*/, const std::string& job_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->job_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Job manager not configured");
                    return res;
                }
                auto job = ctx->job_manager->get_job(job_id);
                if (!job) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Job not found");
                    return res;
                }
                res.code = 200;
                res.body = job_to_json(*job);
                return res;
            });
    // DELETE /api/v1/jobs/<jobId> - Delete a job
    CROW_ROUTE(app, "/api/v1/jobs/<string>")
        .methods(crow::HTTPMethod::DELETE)(
            [ctx](const crow::request& /*req*/, const std::string& job_id) {
                crow::response res;
                add_cors_headers(res, *ctx);
                if (!ctx->job_manager) {
                    res.add_header("Content-Type", "application/json");
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Job manager not configured");
                    return res;
                }
                // Check if job exists
                auto job = ctx->job_manager->get_job(job_id);
                if (!job) {
                    res.add_header("Content-Type", "application/json");
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Job not found");
                    return res;
                }
                auto result = ctx->job_manager->delete_job(job_id);
                if (!result.is_ok()) {
                    res.add_header("Content-Type", "application/json");
                    res.code = 500;
                    res.body = make_error_json("DELETE_FAILED", result.error().message);
                    return res;
                }
                res.code = 204;
                return res;
            });
    // GET /api/v1/jobs/<jobId>/progress - Get job progress
    CROW_ROUTE(app, "/api/v1/jobs/<string>/progress")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& /*req*/, const std::string& job_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->job_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Job manager not configured");
                    return res;
                }
                // Check if job exists
                auto job = ctx->job_manager->get_job(job_id);
                if (!job) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Job not found");
                    return res;
                }
                auto progress = ctx->job_manager->get_progress(job_id);
                res.code = 200;
                res.body = progress_to_json(progress);
                return res;
            });
    // =========================================================================
    // Job Control Endpoints (Issue #559)
    // =========================================================================
    // POST /api/v1/jobs/<jobId>/start - Start a pending job
    CROW_ROUTE(app, "/api/v1/jobs/<string>/start")
        .methods(crow::HTTPMethod::POST)(
            [ctx](const crow::request& /*req*/, const std::string& job_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->job_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Job manager not configured");
                    return res;
                }
                // Check if job exists
                auto job = ctx->job_manager->get_job(job_id);
                if (!job) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Job not found");
                    return res;
                }
                auto result = ctx->job_manager->start_job(job_id);
                if (!result.is_ok()) {
                    res.code = 409;
                    res.body = make_error_json("INVALID_STATE_TRANSITION",
                                               result.error().message);
                    return res;
                }
                // Return updated job
                auto updated_job = ctx->job_manager->get_job(job_id);
                if (updated_job) {
                    res.code = 200;
                    res.body = job_to_json(*updated_job);
                } else {
                    res.code = 200;
                    res.body = R"({"job_id":")" + json_escape(job_id) +
                               R"(","message":"Job started"})";
                }
                return res;
            });
    // POST /api/v1/jobs/<jobId>/pause - Pause a running job
    CROW_ROUTE(app, "/api/v1/jobs/<string>/pause")
        .methods(crow::HTTPMethod::POST)(
            [ctx](const crow::request& /*req*/, const std::string& job_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->job_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Job manager not configured");
                    return res;
                }
                // Check if job exists
                auto job = ctx->job_manager->get_job(job_id);
                if (!job) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Job not found");
                    return res;
                }
                auto result = ctx->job_manager->pause_job(job_id);
                if (!result.is_ok()) {
                    res.code = 409;
                    res.body = make_error_json("INVALID_STATE_TRANSITION",
                                               result.error().message);
                    return res;
                }
                // Return updated job
                auto updated_job = ctx->job_manager->get_job(job_id);
                if (updated_job) {
                    res.code = 200;
                    res.body = job_to_json(*updated_job);
                } else {
                    res.code = 200;
                    res.body = R"({"job_id":")" + json_escape(job_id) +
                               R"(","message":"Job paused"})";
                }
                return res;
            });
    // POST /api/v1/jobs/<jobId>/resume - Resume a paused job
    CROW_ROUTE(app, "/api/v1/jobs/<string>/resume")
        .methods(crow::HTTPMethod::POST)(
            [ctx](const crow::request& /*req*/, const std::string& job_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->job_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Job manager not configured");
                    return res;
                }
                // Check if job exists
                auto job = ctx->job_manager->get_job(job_id);
                if (!job) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Job not found");
                    return res;
                }
                auto result = ctx->job_manager->resume_job(job_id);
                if (!result.is_ok()) {
                    res.code = 409;
                    res.body = make_error_json("INVALID_STATE_TRANSITION",
                                               result.error().message);
                    return res;
                }
                // Return updated job
                auto updated_job = ctx->job_manager->get_job(job_id);
                if (updated_job) {
                    res.code = 200;
                    res.body = job_to_json(*updated_job);
                } else {
                    res.code = 200;
                    res.body = R"({"job_id":")" + json_escape(job_id) +
                               R"(","message":"Job resumed"})";
                }
                return res;
            });
    // POST /api/v1/jobs/<jobId>/cancel - Cancel a job
    CROW_ROUTE(app, "/api/v1/jobs/<string>/cancel")
        .methods(crow::HTTPMethod::POST)(
            [ctx](const crow::request& /*req*/, const std::string& job_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->job_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Job manager not configured");
                    return res;
                }
                // Check if job exists
                auto job = ctx->job_manager->get_job(job_id);
                if (!job) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Job not found");
                    return res;
                }
                auto result = ctx->job_manager->cancel_job(job_id);
                if (!result.is_ok()) {
                    res.code = 409;
                    res.body = make_error_json("INVALID_STATE_TRANSITION",
                                               result.error().message);
                    return res;
                }
                // Return updated job
                auto updated_job = ctx->job_manager->get_job(job_id);
                if (updated_job) {
                    res.code = 200;
                    res.body = job_to_json(*updated_job);
                } else {
                    res.code = 200;
                    res.body = R"({"job_id":")" + json_escape(job_id) +
                               R"(","message":"Job cancelled"})";
                }
                return res;
            });
    // POST /api/v1/jobs/<jobId>/retry - Retry a failed job
    CROW_ROUTE(app, "/api/v1/jobs/<string>/retry")
        .methods(crow::HTTPMethod::POST)(
            [ctx](const crow::request& /*req*/, const std::string& job_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->job_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Job manager not configured");
                    return res;
                }
                // Check if job exists
                auto job = ctx->job_manager->get_job(job_id);
                if (!job) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Job not found");
                    return res;
                }
                auto result = ctx->job_manager->retry_job(job_id);
                if (!result.is_ok()) {
                    res.code = 409;
                    res.body = make_error_json("INVALID_STATE_TRANSITION",
                                               result.error().message);
                    return res;
                }
                // Return updated job
                auto updated_job = ctx->job_manager->get_job(job_id);
                if (updated_job) {
                    res.code = 200;
                    res.body = job_to_json(*updated_job);
                } else {
                    res.code = 200;
                    res.body = R"({"job_id":")" + json_escape(job_id) +
                               R"(","message":"Job retry queued"})";
                }
                return res;
            });
    // =========================================================================
    // WebSocket Endpoints (Issue #560)
    // =========================================================================
    // Register job_manager callbacks for broadcasting (only once)
    if (ctx->job_manager && !g_callbacks_registered.exchange(true)) {
        // Progress callback - broadcasts to all subscribers
        ctx->job_manager->set_progress_callback(
            [](const std::string& job_id, const client::job_progress& progress) {
                auto message = make_progress_message(job_id, progress);
                ws_subscriber_state::instance().broadcast_progress(job_id, message);
            });
        // Completion callback - broadcasts final status
        ctx->job_manager->set_completion_callback(
            [](const std::string& job_id, const client::job_record& record) {
                auto message = make_completion_message(job_id, record);
                ws_subscriber_state::instance().broadcast_progress(job_id, message);
            });
    }
    // WS /api/v1/jobs/<jobId>/progress/stream - Stream progress for specific job
    // Note: URL parameters in WebSocket routes require using onaccept to extract
    // the job_id from the request URL and store it in userdata
    CROW_WEBSOCKET_ROUTE(app, "/api/v1/jobs/<string>/progress/stream")
        .onaccept([ctx](const crow::request& req, void** userdata) -> bool {
            // Extract job_id from URL: /api/v1/jobs/{job_id}/progress/stream
            std::string url = req.url;
            // Find the job_id between /jobs/ and /progress
            const std::string prefix = "/api/v1/jobs/";
            const std::string suffix = "/progress/stream";
            if (url.find(prefix) != 0) {
                return false;
            }
            auto suffix_pos = url.rfind(suffix);
            if (suffix_pos == std::string::npos) {
                return false;
            }
            std::string job_id = url.substr(prefix.length(),
                                            suffix_pos - prefix.length());
            if (job_id.empty()) {
                return false;
            }
            // Verify job manager is available
            if (!ctx->job_manager) {
                return false;
            }
            // Verify job exists
            auto job = ctx->job_manager->get_job(job_id);
            if (!job) {
                return false;
            }
            // Store job_id in userdata (allocate on heap)
            *userdata = new std::string(job_id);
            return true;
        })
        .onopen([ctx](crow::websocket::connection& conn) {
            auto* job_id_ptr = static_cast<std::string*>(conn.userdata());
            if (!job_id_ptr || !ctx->job_manager) {
                conn.send_text(R"({"error":"Invalid connection state"})");
                conn.close("Invalid state");
                return;
            }
            const std::string& job_id = *job_id_ptr;
            // Subscribe to job updates
            ws_subscriber_state::instance().add_job_subscriber(job_id, &conn);
            // Send initial progress
            auto progress = ctx->job_manager->get_progress(job_id);
            conn.send_text(make_progress_message(job_id, progress));
        })
        .onclose([](crow::websocket::connection& conn,
                    const std::string& /*reason*/, uint16_t /*code*/) {
            auto* job_id_ptr = static_cast<std::string*>(conn.userdata());
            if (job_id_ptr) {
                ws_subscriber_state::instance().remove_job_subscriber(*job_id_ptr, &conn);
                delete job_id_ptr;
                conn.userdata(nullptr);
            }
        })
        .onmessage([](crow::websocket::connection& /*conn*/,
                      const std::string& /*data*/, bool /*is_binary*/) {
            // Client messages not expected, but handle gracefully
        });
    // WS /api/v1/jobs/stream - Stream all job updates
    CROW_WEBSOCKET_ROUTE(app, "/api/v1/jobs/stream")
        .onaccept([ctx](const crow::request& /*req*/, void** /*userdata*/) -> bool {
            // Only accept if job_manager is available
            return ctx->job_manager != nullptr;
        })
        .onopen([](crow::websocket::connection& conn) {
            // Subscribe to all job updates
            ws_subscriber_state::instance().add_all_jobs_subscriber(&conn);
            // Send initial connected message
            conn.send_text(R"({"type":"connected","message":"Subscribed to all job updates"})");
        })
        .onclose([](crow::websocket::connection& conn,
                    const std::string& /*reason*/, uint16_t /*code*/) {
            ws_subscriber_state::instance().remove_all_jobs_subscriber(&conn);
        })
        .onmessage([](crow::websocket::connection& /*conn*/,
                      const std::string& /*data*/, bool /*is_binary*/) {
            // Client messages not expected, but handle gracefully
        });
}
References kcenon::pacs::client::job_priority_from_string(), kcenon::pacs::client::job_status_from_string(), kcenon::pacs::client::job_type_from_string(), kcenon::pacs::web::json_escape(), kcenon::pacs::web::make_error_json(), kcenon::pacs::client::normal, kcenon::pacs::client::prefetch, kcenon::pacs::client::query, kcenon::pacs::client::retrieve, kcenon::pacs::client::store, and kcenon::pacs::client::sync.
Referenced by kcenon::pacs::web::rest_server::start_async().
register_key_image_endpoints_impl()
void kcenon::pacs::web::endpoints::register_key_image_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 194 of file key_image_endpoints.cpp.
{
  // POST /api/v1/studies/<studyUid>/key-images - Create key image
  CROW_ROUTE(app, "/api/v1/studies/<string>/key-images")
      .methods(crow::HTTPMethod::POST)(
          [ctx](const crow::request &req, const std::string &study_uid) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body =
                  make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
              return res;
            }
            std::string body = req.body;
            if (body.empty()) {
              res.code = 400;
              res.body = make_error_json("INVALID_REQUEST", "Request body is empty");
              return res;
            }
            storage::key_image_record ki;
            ki.key_image_id = generate_uuid();
            ki.study_uid = study_uid;
            ki.sop_instance_uid = parse_json_string(body, "sop_instance_uid");
            ki.frame_number = parse_json_int(body, "frame_number");
            ki.user_id = parse_json_string(body, "user_id");
            ki.reason = parse_json_string(body, "reason");
            ki.document_title = parse_json_string(body, "document_title");
            ki.created_at = std::chrono::system_clock::now();
            if (ki.sop_instance_uid.empty()) {
              res.code = 400;
              res.body = make_error_json("MISSING_FIELD", "sop_instance_uid is required");
              return res;
            }
#ifdef PACS_WITH_DATABASE_SYSTEM
            storage::key_image_repository repo(ctx->database->db_adapter());
#else
            storage::key_image_repository repo(ctx->database->native_handle());
#endif
            auto save_result = repo.save(ki);
            if (!save_result.is_ok()) {
              res.code = 500;
              res.body =
                  make_error_json("SAVE_ERROR", save_result.error().message);
              return res;
            }
            res.code = 201;
            std::ostringstream oss;
            oss << R"({"key_image_id":")" << json_escape(ki.key_image_id)
                << R"(","created_at":")" << format_timestamp(ki.created_at)
                << R"("})";
            res.body = oss.str();
            return res;
          });
  // GET /api/v1/studies/<studyUid>/key-images - List key images for study
  CROW_ROUTE(app, "/api/v1/studies/<string>/key-images")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/, const std::string &study_uid) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body =
                  make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
              return res;
            }
#ifdef PACS_WITH_DATABASE_SYSTEM
            storage::key_image_repository repo(ctx->database->db_adapter());
            auto key_images_result = repo.find_by_study(study_uid);
            if (!key_images_result.is_ok()) {
              res.code = 500;
              res.body = make_error_json("QUERY_ERROR", key_images_result.error().message);
              return res;
            }
            res.code = 200;
            res.body = key_images_to_json(key_images_result.value());
#else
            storage::key_image_repository repo(ctx->database->native_handle());
            auto key_images = repo.find_by_study(study_uid);
            res.code = 200;
            res.body = key_images_to_json(key_images);
#endif
            return res;
          });
  // DELETE /api/v1/key-images/<keyImageId> - Delete key image
  CROW_ROUTE(app, "/api/v1/key-images/<string>")
      .methods(crow::HTTPMethod::DELETE)(
          [ctx](const crow::request & /*req*/, const std::string &key_image_id) {
            crow::response res;
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
#ifdef PACS_WITH_DATABASE_SYSTEM
            storage::key_image_repository repo(ctx->database->db_adapter());
            auto exists_result = repo.exists(key_image_id);
            if (!exists_result.is_ok()) {
              res.code = 500;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("QUERY_ERROR", exists_result.error().message);
              return res;
            }
            if (!exists_result.value()) {
              res.code = 404;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("NOT_FOUND", "Key image not found");
              return res;
            }
#else
            storage::key_image_repository repo(ctx->database->native_handle());
            if (!repo.exists(key_image_id)) {
              res.code = 404;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("NOT_FOUND", "Key image not found");
              return res;
            }
#endif
            auto remove_result = repo.remove(key_image_id);
            if (!remove_result.is_ok()) {
              res.code = 500;
              res.add_header("Content-Type", "application/json");
              res.body =
                  make_error_json("DELETE_ERROR", remove_result.error().message);
              return res;
            }
            res.code = 204;
            return res;
          });
  // POST /api/v1/studies/<studyUid>/key-images/export-sr - Export as Key Object Selection SR
  CROW_ROUTE(app, "/api/v1/studies/<string>/key-images/export-sr")
      .methods(crow::HTTPMethod::POST)(
          [ctx](const crow::request & /*req*/, const std::string &study_uid) {
            crow::response res;
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
#ifdef PACS_WITH_DATABASE_SYSTEM
            storage::key_image_repository repo(ctx->database->db_adapter());
            auto key_images_result = repo.find_by_study(study_uid);
            if (!key_images_result.is_ok()) {
              res.code = 500;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("QUERY_ERROR", key_images_result.error().message);
              return res;
            }
            const auto& key_images = key_images_result.value();
#else
            storage::key_image_repository repo(ctx->database->native_handle());
            auto key_images = repo.find_by_study(study_uid);
#endif
            if (key_images.empty()) {
              res.code = 404;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("NO_KEY_IMAGES",
                                         "No key images found for study");
              return res;
            }
            // Build Key Object Selection Document as JSON
            // Note: Full DICOM SR encoding requires dcmtk/dicom_dataset integration
            // This endpoint returns a structured JSON that can be converted to DICOM SR
            std::ostringstream oss;
            oss << R"({"document_type":"Key Object Selection",)";
            oss << R"("study_uid":")" << json_escape(study_uid) << R"(",)";
            oss << R"("document_title":"Key Images",)";
            oss << R"("referenced_instances":[)";
            for (size_t i = 0; i < key_images.size(); ++i) {
              if (i > 0) {
                oss << ",";
              }
              const auto &ki = key_images[i];
              oss << R"({"sop_instance_uid":")" << json_escape(ki.sop_instance_uid) << R"(",)";
              oss << R"("frame_number":)";
              if (ki.frame_number.has_value()) {
                oss << ki.frame_number.value();
              } else {
                oss << "null";
              }
              oss << R"(,"reason":")" << json_escape(ki.reason) << R"("})";
            }
            oss << R"(],"created_at":")" << format_timestamp(std::chrono::system_clock::now()) << R"("})";
            res.code = 200;
            res.add_header("Content-Type", "application/json");
            res.body = oss.str();
            return res;
          });
}
References kcenon::pacs::storage::key_image_record::created_at, kcenon::pacs::storage::key_image_record::document_title, kcenon::pacs::storage::key_image_repository::exists(), kcenon::pacs::storage::key_image_repository::find_by_study(), kcenon::pacs::storage::key_image_record::frame_number, kcenon::pacs::web::json_escape(), kcenon::pacs::storage::key_image_record::key_image_id, kcenon::pacs::web::make_error_json(), kcenon::pacs::storage::key_image_record::reason, kcenon::pacs::storage::key_image_repository::remove(), kcenon::pacs::storage::key_image_repository::save(), kcenon::pacs::storage::key_image_record::sop_instance_uid, kcenon::pacs::storage::key_image_record::study_uid, and kcenon::pacs::storage::key_image_record::user_id.
Referenced by kcenon::pacs::web::rest_server::start_async().
register_measurement_endpoints_impl()
void kcenon::pacs::web::endpoints::register_measurement_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 284 of file measurement_endpoints.cpp.
{
  // POST /api/v1/measurements - Create measurement
  CROW_ROUTE(app, "/api/v1/measurements")
      .methods(crow::HTTPMethod::POST)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        if (!ctx->database) {
          res.code = 503;
          res.body =
              make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
          return res;
        }
        std::string body = req.body;
        if (body.empty()) {
          res.code = 400;
          res.body = make_error_json("INVALID_REQUEST", "Request body is empty");
          return res;
        }
        storage::measurement_record meas;
        meas.measurement_id = generate_uuid();
        meas.sop_instance_uid = parse_json_string(body, "sop_instance_uid");
        meas.frame_number = parse_json_int(body, "frame_number");
        meas.user_id = parse_json_string(body, "user_id");
        auto type_str = parse_json_string(body, "measurement_type");
        auto type_opt = storage::measurement_type_from_string(type_str);
        if (!type_opt.has_value()) {
          res.code = 400;
          res.body = make_error_json("INVALID_TYPE", "Invalid measurement type");
          return res;
        }
        meas.type = type_opt.value();
        meas.geometry_json = parse_json_object(body, "geometry");
        meas.value = parse_json_double(body, "value");
        meas.unit = parse_json_string(body, "unit");
        meas.label = parse_json_string(body, "label");
        meas.created_at = std::chrono::system_clock::now();
        if (meas.sop_instance_uid.empty()) {
          res.code = 400;
          res.body =
              make_error_json("MISSING_FIELD", "sop_instance_uid is required");
          return res;
        }
#ifdef PACS_WITH_DATABASE_SYSTEM
        storage::measurement_repository repo(ctx->database->db_adapter());
#else
        storage::measurement_repository repo(ctx->database->native_handle());
#endif
        auto save_result = repo.save(meas);
        if (!save_result.is_ok()) {
          res.code = 500;
          res.body =
              make_error_json("SAVE_ERROR", save_result.error().message);
          return res;
        }
        res.code = 201;
        std::ostringstream oss;
        oss << R"({"measurement_id":")" << json_escape(meas.measurement_id)
            << R"(","value":)" << meas.value << R"(,"unit":")"
            << json_escape(meas.unit) << R"("})";
        res.body = oss.str();
        return res;
      });
  // GET /api/v1/measurements - List measurements
  CROW_ROUTE(app, "/api/v1/measurements")
      .methods(crow::HTTPMethod::GET)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        if (!ctx->database) {
          res.code = 503;
          res.body =
              make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
          return res;
        }
        auto [limit, offset] = parse_pagination(req);
        storage::measurement_query query;
        query.limit = limit;
        query.offset = offset;
        auto sop_instance_uid = req.url_params.get("sop_instance_uid");
        if (sop_instance_uid) {
          query.sop_instance_uid = sop_instance_uid;
        }
        auto study_uid = req.url_params.get("study_uid");
        if (study_uid) {
          query.study_uid = study_uid;
        }
        auto user_id = req.url_params.get("user_id");
        if (user_id) {
          query.user_id = user_id;
        }
        auto measurement_type = req.url_params.get("measurement_type");
        if (measurement_type) {
          auto type_opt = storage::measurement_type_from_string(measurement_type);
          if (type_opt.has_value()) {
            query.type = type_opt.value();
          }
        }
#ifdef PACS_WITH_DATABASE_SYSTEM
        storage::measurement_repository repo(ctx->database->db_adapter());
        storage::measurement_query count_query = query;
        count_query.limit = 0;
        count_query.offset = 0;
        auto count_result = repo.count(count_query);
        if (!count_result.is_ok()) {
          res.code = 500;
          res.body = make_error_json("COUNT_ERROR", count_result.error().message);
          return res;
        }
        size_t total_count = count_result.value();
        auto measurements_result = repo.search(query);
        if (!measurements_result.is_ok()) {
          res.code = 500;
          res.body = make_error_json("QUERY_ERROR", measurements_result.error().message);
          return res;
        }
        res.code = 200;
        res.body = measurements_to_json(measurements_result.value(), total_count);
#else
        storage::measurement_repository repo(ctx->database->native_handle());
        storage::measurement_query count_query = query;
        count_query.limit = 0;
        count_query.offset = 0;
        size_t total_count = repo.count(count_query);
        auto measurements = repo.search(query);
        res.code = 200;
        res.body = measurements_to_json(measurements, total_count);
#endif
        return res;
      });
  // GET /api/v1/measurements/<measurementId> - Get measurement by ID
  CROW_ROUTE(app, "/api/v1/measurements/<string>")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/, const std::string &measurement_id) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
#ifdef PACS_WITH_DATABASE_SYSTEM
            storage::measurement_repository repo(ctx->database->db_adapter());
            auto meas_result = repo.find_by_id(measurement_id);
            if (!meas_result.is_ok()) {
              // Check if it's a NOT_FOUND error
              if (meas_result.error().message.find("not found") != std::string::npos ||
                  meas_result.error().message.find("NOT_FOUND") != std::string::npos) {
                res.code = 404;
                res.body = make_error_json("NOT_FOUND", "Measurement not found");
              } else {
                res.code = 500;
                res.body = make_error_json("QUERY_ERROR", meas_result.error().message);
              }
              return res;
            }
            res.code = 200;
            res.body = measurement_to_json(meas_result.value());
#else
            storage::measurement_repository repo(ctx->database->native_handle());
            auto meas_result = repo.find_by_id(measurement_id);
            if (!meas_result.has_value()) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Measurement not found");
              return res;
            }
            res.code = 200;
            res.body = measurement_to_json(meas_result.value());
#endif
            return res;
          });
  // DELETE /api/v1/measurements/<measurementId> - Delete measurement
  CROW_ROUTE(app, "/api/v1/measurements/<string>")
      .methods(crow::HTTPMethod::DELETE)(
          [ctx](const crow::request & /*req*/, const std::string &measurement_id) {
            crow::response res;
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
#ifdef PACS_WITH_DATABASE_SYSTEM
            storage::measurement_repository repo(ctx->database->db_adapter());
            auto exists_result = repo.exists(measurement_id);
            if (!exists_result.is_ok()) {
              res.code = 500;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("QUERY_ERROR", exists_result.error().message);
              return res;
            }
            if (!exists_result.value()) {
              res.code = 404;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("NOT_FOUND", "Measurement not found");
              return res;
            }
#else
            storage::measurement_repository repo(ctx->database->native_handle());
            if (!repo.exists(measurement_id)) {
              res.code = 404;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("NOT_FOUND", "Measurement not found");
              return res;
            }
#endif
            auto remove_result = repo.remove(measurement_id);
            if (!remove_result.is_ok()) {
              res.code = 500;
              res.add_header("Content-Type", "application/json");
              res.body =
                  make_error_json("DELETE_ERROR", remove_result.error().message);
              return res;
            }
            res.code = 204;
            return res;
          });
  // GET /api/v1/instances/<sopInstanceUid>/measurements - Get measurements for instance
  CROW_ROUTE(app, "/api/v1/instances/<string>/measurements")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/,
                const std::string &sop_instance_uid) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
#ifdef PACS_WITH_DATABASE_SYSTEM
            storage::measurement_repository repo(ctx->database->db_adapter());
            auto measurements_result = repo.find_by_instance(sop_instance_uid);
            if (!measurements_result.is_ok()) {
              res.code = 500;
              res.body = make_error_json("QUERY_ERROR", measurements_result.error().message);
              return res;
            }
            const auto& measurements = measurements_result.value();
#else
            storage::measurement_repository repo(ctx->database->native_handle());
            auto measurements = repo.find_by_instance(sop_instance_uid);
#endif
            std::ostringstream oss;
            oss << R"({"data":[)";
            for (size_t i = 0; i < measurements.size(); ++i) {
              if (i > 0) {
                oss << ",";
              }
              oss << measurement_to_json(measurements[i]);
            }
            oss << "]}";
            res.code = 200;
            res.body = oss.str();
            return res;
          });
}
References kcenon::pacs::storage::measurement_repository::count(), kcenon::pacs::storage::measurement_record::created_at, kcenon::pacs::storage::measurement_repository::exists(), kcenon::pacs::storage::measurement_repository::find_by_id(), kcenon::pacs::storage::measurement_repository::find_by_instance(), kcenon::pacs::storage::measurement_record::frame_number, kcenon::pacs::storage::measurement_record::geometry_json, kcenon::pacs::web::json_escape(), kcenon::pacs::storage::measurement_record::label, kcenon::pacs::storage::measurement_query::limit, kcenon::pacs::web::make_error_json(), kcenon::pacs::storage::measurement_record::measurement_id, kcenon::pacs::storage::measurement_type_from_string(), kcenon::pacs::storage::measurement_query::offset, kcenon::pacs::storage::measurement_repository::remove(), kcenon::pacs::storage::measurement_repository::save(), kcenon::pacs::storage::measurement_repository::search(), kcenon::pacs::storage::measurement_record::sop_instance_uid, kcenon::pacs::storage::measurement_record::type, kcenon::pacs::storage::measurement_record::unit, kcenon::pacs::storage::measurement_record::user_id, and kcenon::pacs::storage::measurement_record::value.
Referenced by kcenon::pacs::web::rest_server::start_async().
register_metadata_endpoints_impl()
void kcenon::pacs::web::endpoints::register_metadata_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 333 of file metadata_endpoints.cpp.
{
    // Initialize metadata service if database is available
    if (ctx->database != nullptr && g_metadata_service == nullptr) {
        g_metadata_service = std::make_shared<metadata_service>(ctx->database);
    }
    // =========================================================================
    // Selective Metadata
    // =========================================================================
    // GET /api/v1/instances/{sopInstanceUid}/metadata
    CROW_ROUTE(app, "/api/v1/instances/<string>/metadata")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req, const std::string& sop_uid) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (g_metadata_service == nullptr) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Metadata service not configured");
                    return res;
                }
                auto request = parse_metadata_request(req);
                auto result = g_metadata_service->get_metadata(sop_uid, request);
                if (!result.success) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", result.error_message);
                    return res;
                }
                res.code = 200;
                res.body = metadata_response_to_json(result);
                return res;
            });
    // =========================================================================
    // Series Navigation
    // =========================================================================
    // GET /api/v1/series/{seriesUid}/instances/sorted
    CROW_ROUTE(app, "/api/v1/series/<string>/instances/sorted")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req, const std::string& series_uid) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (g_metadata_service == nullptr) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Metadata service not configured");
                    return res;
                }
                // Parse sort parameters
                sort_order order = sort_order::position;
                auto sort_param = req.url_params.get("sort_by");
                if (sort_param != nullptr) {
                    auto parsed = sort_order_from_string(sort_param);
                    if (parsed.has_value()) {
                        order = parsed.value();
                    }
                }
                bool ascending = true;
                auto dir_param = req.url_params.get("direction");
                if (dir_param != nullptr) {
                    std::string dir = dir_param;
                    ascending = (dir != "desc");
                }
                auto result = g_metadata_service->get_sorted_instances(
                    series_uid, order, ascending);
                if (!result.success) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", result.error_message);
                    return res;
                }
                res.code = 200;
                res.body = sorted_instances_to_json(result);
                return res;
            });
    // GET /api/v1/instances/{sopInstanceUid}/navigation
    CROW_ROUTE(app, "/api/v1/instances/<string>/navigation")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& /*req*/, const std::string& sop_uid) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (g_metadata_service == nullptr) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Metadata service not configured");
                    return res;
                }
                auto result = g_metadata_service->get_navigation(sop_uid);
                if (!result.success) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", result.error_message);
                    return res;
                }
                res.code = 200;
                res.body = navigation_info_to_json(result);
                return res;
            });
    // =========================================================================
    // Window/Level Presets
    // =========================================================================
    // GET /api/v1/presets/window-level
    CROW_ROUTE(app, "/api/v1/presets/window-level")
        .methods(crow::HTTPMethod::GET)([ctx](const crow::request& req) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            std::string modality = "CT";  // Default modality
            auto modality_param = req.url_params.get("modality");
            if (modality_param != nullptr) {
                modality = modality_param;
            }
            auto presets = metadata_service::get_window_level_presets(modality);
            res.code = 200;
            res.body = presets_to_json(presets);
            return res;
        });
    // GET /api/v1/instances/{sopInstanceUid}/voi-lut
    CROW_ROUTE(app, "/api/v1/instances/<string>/voi-lut")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& /*req*/, const std::string& sop_uid) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (g_metadata_service == nullptr) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Metadata service not configured");
                    return res;
                }
                auto result = g_metadata_service->get_voi_lut(sop_uid);
                if (!result.success) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", result.error_message);
                    return res;
                }
                res.code = 200;
                res.body = voi_lut_to_json(result);
                return res;
            });
    // =========================================================================
    // Multi-frame Support
    // =========================================================================
    // GET /api/v1/instances/{sopInstanceUid}/frame-info
    CROW_ROUTE(app, "/api/v1/instances/<string>/frame-info")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& /*req*/, const std::string& sop_uid) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (g_metadata_service == nullptr) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Metadata service not configured");
                    return res;
                }
                auto result = g_metadata_service->get_frame_info(sop_uid);
                if (!result.success) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", result.error_message);
                    return res;
                }
                res.code = 200;
                res.body = frame_info_to_json(result);
                return res;
            });
}
References kcenon::pacs::web::metadata_service::get_window_level_presets(), kcenon::pacs::web::make_error_json(), kcenon::pacs::web::position, and kcenon::pacs::web::sort_order_from_string().
Referenced by kcenon::pacs::web::rest_server::start_async().
register_patient_endpoints_impl()
void kcenon::pacs::web::endpoints::register_patient_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 169 of file patient_endpoints.cpp.
{
  // GET /api/v1/patients - List patients (paginated)
  CROW_ROUTE(app, "/api/v1/patients")
      .methods(crow::HTTPMethod::GET)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        if (!ctx->database) {
          res.code = 503;
          res.body =
              make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
          return res;
        }
        // Parse pagination
        auto [limit, offset] = parse_pagination(req);
        // Build query from URL parameters
        storage::patient_query query;
        query.limit = limit;
        query.offset = offset;
        auto patient_id = req.url_params.get("patient_id");
        if (patient_id) {
          query.patient_id = patient_id;
        }
        auto patient_name = req.url_params.get("patient_name");
        if (patient_name) {
          query.patient_name = patient_name;
        }
        auto birth_date = req.url_params.get("birth_date");
        if (birth_date) {
          query.birth_date = birth_date;
        }
        auto birth_date_from = req.url_params.get("birth_date_from");
        if (birth_date_from) {
          query.birth_date_from = birth_date_from;
        }
        auto birth_date_to = req.url_params.get("birth_date_to");
        if (birth_date_to) {
          query.birth_date_to = birth_date_to;
        }
        auto sex = req.url_params.get("sex");
        if (sex) {
          query.sex = sex;
        }
        // Get total count (without pagination for accurate count)
        storage::patient_query count_query = query;
        count_query.limit = 0;
        count_query.offset = 0;
        auto all_patients_result = ctx->database->search_patients(count_query);
        if (!all_patients_result.is_ok()) {
          res.code = 500;
          res.body = make_error_json("QUERY_ERROR",
                                     all_patients_result.error().message);
          return res;
        }
        size_t total_count = all_patients_result.value().size();
        // Get paginated results
        auto patients_result = ctx->database->search_patients(query);
        if (!patients_result.is_ok()) {
          res.code = 500;
          res.body = make_error_json("QUERY_ERROR",
                                     patients_result.error().message);
          return res;
        }
        res.code = 200;
        res.body = patients_to_json(patients_result.value(), total_count);
        return res;
      });
  // GET /api/v1/patients/:id - Get patient details
  CROW_ROUTE(app, "/api/v1/patients/<string>")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/, const std::string &patient_id) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            auto patient = ctx->database->find_patient(patient_id);
            if (!patient) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Patient not found");
              return res;
            }
            res.code = 200;
            res.body = patient_to_json(*patient);
            return res;
          });
  // GET /api/v1/patients/:id/studies - Get patient's studies
  CROW_ROUTE(app, "/api/v1/patients/<string>/studies")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/, const std::string &patient_id) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            // Verify patient exists
            auto patient = ctx->database->find_patient(patient_id);
            if (!patient) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Patient not found");
              return res;
            }
            auto studies_result = ctx->database->list_studies(patient_id);
            if (!studies_result.is_ok()) {
              res.code = 500;
              res.body = make_error_json("QUERY_ERROR",
                                         studies_result.error().message);
              return res;
            }
            res.code = 200;
            res.body = studies_to_json(studies_result.value());
            return res;
          });
}
References kcenon::pacs::storage::patient_query::limit, kcenon::pacs::web::make_error_json(), and kcenon::pacs::storage::patient_query::offset.
Referenced by kcenon::pacs::web::rest_server::start_async().
register_remote_nodes_endpoints_impl()
void kcenon::pacs::web::endpoints::register_remote_nodes_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 308 of file remote_nodes_endpoints.cpp.
{
    // GET /api/v1/remote-nodes - List remote nodes (paginated)
    CROW_ROUTE(app, "/api/v1/remote-nodes")
        .methods(crow::HTTPMethod::GET)([ctx](const crow::request& req) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->node_manager) {
                res.code = 503;
                res.body = make_error_json("SERVICE_UNAVAILABLE",
                                           "Remote node manager not configured");
                return res;
            }
            // Parse pagination
            auto [limit, offset] = parse_pagination(req);
            // Filter by status if provided
            auto status_param = req.url_params.get("status");
            std::vector<client::remote_node> nodes;
            if (status_param) {
                auto status = client::node_status_from_string(status_param);
                nodes = ctx->node_manager->list_nodes_by_status(status);
            } else {
                nodes = ctx->node_manager->list_nodes();
            }
            size_t total_count = nodes.size();
            // Apply pagination
            std::vector<client::remote_node> paginated;
            for (size_t i = offset; i < nodes.size() && paginated.size() < limit; ++i) {
                paginated.push_back(nodes[i]);
            }
            res.code = 200;
            res.body = nodes_to_json(paginated, total_count);
            return res;
        });
    // POST /api/v1/remote-nodes - Create a new remote node
    CROW_ROUTE(app, "/api/v1/remote-nodes")
        .methods(crow::HTTPMethod::POST)([ctx](const crow::request& req) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->node_manager) {
                res.code = 503;
                res.body = make_error_json("SERVICE_UNAVAILABLE",
                                           "Remote node manager not configured");
                return res;
            }
            std::string error_message;
            auto node_opt = parse_node_from_json(req.body, error_message);
            if (!node_opt) {
                res.code = 400;
                res.body = make_error_json("INVALID_REQUEST", error_message);
                return res;
            }
            auto& node = *node_opt;
            // Generate node_id if not provided
            if (node.node_id.empty()) {
                // Use ae_title + timestamp as default node_id
                auto now = std::chrono::system_clock::now();
                auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
                    now.time_since_epoch()).count();
                node.node_id = node.ae_title + "_" + std::to_string(ms);
            }
            auto result = ctx->node_manager->add_node(node);
            if (!result.is_ok()) {
                res.code = 409;
                res.body = make_error_json("CONFLICT", result.error().message);
                return res;
            }
            // Retrieve the created node to get full details
            auto created_node = ctx->node_manager->get_node(node.node_id);
            if (!created_node) {
                res.code = 201;
                res.body = node_to_json(node);
                return res;
            }
            res.code = 201;
            res.body = node_to_json(*created_node);
            return res;
        });
    // GET /api/v1/remote-nodes/<nodeId> - Get a specific remote node
    CROW_ROUTE(app, "/api/v1/remote-nodes/<string>")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& /*req*/, const std::string& node_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->node_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Remote node manager not configured");
                    return res;
                }
                auto node = ctx->node_manager->get_node(node_id);
                if (!node) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Remote node not found");
                    return res;
                }
                res.code = 200;
                res.body = node_to_json(*node);
                return res;
            });
    // PUT /api/v1/remote-nodes/<nodeId> - Update a remote node
    CROW_ROUTE(app, "/api/v1/remote-nodes/<string>")
        .methods(crow::HTTPMethod::PUT)(
            [ctx](const crow::request& req, const std::string& node_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->node_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Remote node manager not configured");
                    return res;
                }
                // Check if node exists
                auto existing = ctx->node_manager->get_node(node_id);
                if (!existing) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Remote node not found");
                    return res;
                }
                std::string error_message;
                auto node_opt = parse_node_from_json(req.body, error_message);
                if (!node_opt) {
                    res.code = 400;
                    res.body = make_error_json("INVALID_REQUEST", error_message);
                    return res;
                }
                auto& node = *node_opt;
                node.node_id = node_id; // Preserve the node_id from URL
                auto result = ctx->node_manager->update_node(node);
                if (!result.is_ok()) {
                    res.code = 500;
                    res.body = make_error_json("UPDATE_FAILED", result.error().message);
                    return res;
                }
                // Retrieve the updated node
                auto updated_node = ctx->node_manager->get_node(node_id);
                if (!updated_node) {
                    res.code = 200;
                    res.body = node_to_json(node);
                    return res;
                }
                res.code = 200;
                res.body = node_to_json(*updated_node);
                return res;
            });
    // DELETE /api/v1/remote-nodes/<nodeId> - Delete a remote node
    CROW_ROUTE(app, "/api/v1/remote-nodes/<string>")
        .methods(crow::HTTPMethod::DELETE)(
            [ctx](const crow::request& /*req*/, const std::string& node_id) {
                crow::response res;
                add_cors_headers(res, *ctx);
                if (!ctx->node_manager) {
                    res.add_header("Content-Type", "application/json");
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Remote node manager not configured");
                    return res;
                }
                // Check if node exists
                auto existing = ctx->node_manager->get_node(node_id);
                if (!existing) {
                    res.add_header("Content-Type", "application/json");
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Remote node not found");
                    return res;
                }
                auto result = ctx->node_manager->remove_node(node_id);
                if (!result.is_ok()) {
                    res.add_header("Content-Type", "application/json");
                    res.code = 500;
                    res.body = make_error_json("DELETE_FAILED", result.error().message);
                    return res;
                }
                res.code = 204;
                return res;
            });
    // POST /api/v1/remote-nodes/<nodeId>/verify - Verify node connectivity
    CROW_ROUTE(app, "/api/v1/remote-nodes/<string>/verify")
        .methods(crow::HTTPMethod::POST)(
            [ctx](const crow::request& /*req*/, const std::string& node_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->node_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Remote node manager not configured");
                    return res;
                }
                // Check if node exists
                auto existing = ctx->node_manager->get_node(node_id);
                if (!existing) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Remote node not found");
                    return res;
                }
                auto start = std::chrono::steady_clock::now();
                auto result = ctx->node_manager->verify_node(node_id);
                auto end = std::chrono::steady_clock::now();
                auto elapsed_ms = std::chrono::duration_cast<std::chrono::milliseconds>(
                    end - start).count();
                if (result.is_ok()) {
                    std::ostringstream oss;
                    oss << R"({"success":true,"response_time_ms":)" << elapsed_ms << '}';
                    res.code = 200;
                    res.body = oss.str();
                } else {
                    std::ostringstream oss;
                    oss << R"({"success":false,"error":")"
                        << json_escape(result.error().message)
                        << R"(","response_time_ms":)" << elapsed_ms << '}';
                    res.code = 200;
                    res.body = oss.str();
                }
                return res;
            });
    // GET /api/v1/remote-nodes/<nodeId>/status - Get node status
    CROW_ROUTE(app, "/api/v1/remote-nodes/<string>/status")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& /*req*/, const std::string& node_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->node_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Remote node manager not configured");
                    return res;
                }
                auto node = ctx->node_manager->get_node(node_id);
                if (!node) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Remote node not found");
                    return res;
                }
                auto stats = ctx->node_manager->get_statistics(node_id);
                std::ostringstream oss;
                oss << R"({"status":")" << client::to_string(node->status) << '"';
                auto last_verified = format_timestamp(node->last_verified);
                if (!last_verified.empty()) {
                    oss << R"(,"last_verified":")" << last_verified << '"';
                }
                if (!node->last_error_message.empty()) {
                    oss << R"(,"last_error_message":")"
                        << json_escape(node->last_error_message) << '"';
                }
                oss << R"(,"total_connections":)" << stats.total_connections
                    << R"(,"active_connections":)" << stats.active_connections
                    << R"(,"successful_operations":)" << stats.successful_operations
                    << R"(,"failed_operations":)" << stats.failed_operations;
                if (stats.avg_response_time.count() > 0) {
                    oss << R"(,"avg_response_time_ms":)" << stats.avg_response_time.count();
                }
                oss << '}';
                res.code = 200;
                res.body = oss.str();
                return res;
            });
    // POST /api/v1/remote-nodes/<nodeId>/query - Query remote PACS
    CROW_ROUTE(app, "/api/v1/remote-nodes/<string>/query")
        .methods(crow::HTTPMethod::POST)(
            [ctx](const crow::request& req, const std::string& node_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->node_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Remote node manager not configured");
                    return res;
                }
                auto node = ctx->node_manager->get_node(node_id);
                if (!node) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Remote node not found");
                    return res;
                }
                if (!node->supports_find) {
                    res.code = 400;
                    res.body = make_error_json("UNSUPPORTED",
                        "Remote node does not support C-FIND queries");
                    return res;
                }
                // Parse query parameters from request body
                auto get_str = [&req](const std::string& key) -> std::string {
                    std::string search = "\"" + key + "\":\"";
                    auto pos = req.body.find(search);
                    if (pos == std::string::npos) return "";
                    pos += search.length();
                    auto end_pos = req.body.find('"', pos);
                    if (end_pos == std::string::npos) return "";
                    return req.body.substr(pos, end_pos - pos);
                };
                auto level = get_str("level");
                if (level.empty()) level = "STUDY";
                // Determine calling AE title from dicom_server config
                std::string calling_ae = "PACS_SCU";
                if (ctx->dicom_server) {
                    calling_ae = ctx->dicom_server->config().ae_title;
                }
                // Build association config for C-FIND
                network::association_config assoc_config;
                assoc_config.calling_ae_title = calling_ae;
                assoc_config.called_ae_title = node->ae_title;
                assoc_config.proposed_contexts.push_back({
                    1,
                    std::string(services::study_root_find_sop_class_uid),
                    {"1.2.840.10008.1.2.1"}  // Explicit VR Little Endian
                });
                auto timeout = std::chrono::milliseconds(
                    node->connection_timeout.count() * 1000);
                auto assoc_result = network::association::connect(
                    node->host,
                    static_cast<uint16_t>(node->port),
                    assoc_config,
                    timeout);
                if (assoc_result.is_err()) {
                    res.code = 502;
                    res.body = make_error_json("CONNECTION_FAILED",
                        "Failed to connect to remote PACS: " +
                        assoc_result.error().message);
                    return res;
                }
                auto& assoc = assoc_result.value();
                services::query_scu scu;
                // Helper to format query results as JSON
                auto format_query_response = [](
                    const services::query_result& qr) -> std::string {
                    std::ostringstream oss;
                    oss << R"({"matches":[)";
                    for (size_t i = 0; i < qr.matches.size(); ++i) {
                        if (i > 0) oss << ',';
                        oss << '{';
                        bool first_field = true;
                        for (const auto& [tag, element] : qr.matches[i]) {
                            auto val = element.as_string();
                            if (val.is_err()) continue;
                            if (!first_field) oss << ',';
                            first_field = false;
                            oss << '"' << json_escape(tag.to_string())
                                << R"(":")" << json_escape(val.value()) << '"';
                        }
                        oss << '}';
                    }
                    oss << R"(],"total_matches":)" << qr.matches.size()
                        << R"(,"elapsed_ms":)" << qr.elapsed.count()
                        << R"(,"status":")"
                        << (qr.is_success() ? "success" : "error")
                        << R"("})";
                    return oss.str();
                };
                // Helper to handle query result and build response
                auto handle_result = [&](
                    network::Result<services::query_result>& result) {
                    (void)assoc.release();
                    if (result.is_err()) {
                        res.code = 502;
                        res.body = make_error_json("QUERY_FAILED",
                            "C-FIND query failed: " + result.error().message);
                    } else {
                        res.code = 200;
                        res.body = format_query_response(result.value());
                    }
                };
                // Execute query based on level
                if (level == "PATIENT") {
                    services::patient_query_keys keys;
                    keys.patient_name = get_str("patient_name");
                    keys.patient_id = get_str("patient_id");
                    keys.birth_date = get_str("birth_date");
                    keys.sex = get_str("sex");
                    auto result = scu.find_patients(assoc, keys);
                    handle_result(result);
                } else if (level == "STUDY") {
                    services::study_query_keys keys;
                    keys.patient_id = get_str("patient_id");
                    keys.study_uid = get_str("study_uid");
                    keys.study_date = get_str("study_date");
                    keys.accession_number = get_str("accession_number");
                    keys.modality = get_str("modality");
                    keys.study_description = get_str("study_description");
                    auto result = scu.find_studies(assoc, keys);
                    handle_result(result);
                } else if (level == "SERIES") {
                    services::series_query_keys keys;
                    keys.study_uid = get_str("study_uid");
                    keys.series_uid = get_str("series_uid");
                    keys.modality = get_str("modality");
                    keys.series_number = get_str("series_number");
                    if (keys.study_uid.empty()) {
                        (void)assoc.release();
                        res.code = 400;
                        res.body = make_error_json("INVALID_REQUEST",
                            "study_uid is required for SERIES level queries");
                        return res;
                    }
                    auto result = scu.find_series(assoc, keys);
                    handle_result(result);
                } else if (level == "IMAGE") {
                    services::instance_query_keys keys;
                    keys.series_uid = get_str("series_uid");
                    keys.sop_instance_uid = get_str("sop_instance_uid");
                    keys.instance_number = get_str("instance_number");
                    if (keys.series_uid.empty()) {
                        (void)assoc.release();
                        res.code = 400;
                        res.body = make_error_json("INVALID_REQUEST",
                            "series_uid is required for IMAGE level queries");
                        return res;
                    }
                    auto result = scu.find_instances(assoc, keys);
                    handle_result(result);
                } else {
                    (void)assoc.release();
                    res.code = 400;
                    res.body = make_error_json("INVALID_REQUEST",
                        "Invalid query level. Use PATIENT, STUDY, SERIES, "
                        "or IMAGE.");
                    return res;
                }
                return res;
            });
    // POST /api/v1/remote-nodes/<nodeId>/retrieve - Retrieve from remote PACS
    CROW_ROUTE(app, "/api/v1/remote-nodes/<string>/retrieve")
        .methods(crow::HTTPMethod::POST)(
            [ctx](const crow::request& req, const std::string& node_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->node_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Remote node manager not configured");
                    return res;
                }
                if (!ctx->job_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Job manager not configured");
                    return res;
                }
                auto node = ctx->node_manager->get_node(node_id);
                if (!node) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Remote node not found");
                    return res;
                }
                if (!node->supports_move && !node->supports_get) {
                    res.code = 400;
                    res.body = make_error_json("UNSUPPORTED",
                        "Remote node does not support C-MOVE or C-GET");
                    return res;
                }
                // Parse retrieve parameters from request body
                auto get_str = [&req](const std::string& key) -> std::string {
                    std::string search = "\"" + key + "\":\"";
                    auto pos = req.body.find(search);
                    if (pos == std::string::npos) return "";
                    pos += search.length();
                    auto end_pos = req.body.find('"', pos);
                    if (end_pos == std::string::npos) return "";
                    return req.body.substr(pos, end_pos - pos);
                };
                auto study_uid = get_str("study_uid");
                if (study_uid.empty()) {
                    res.code = 400;
                    res.body = make_error_json("INVALID_REQUEST",
                        "study_uid is required");
                    return res;
                }
                auto series_uid = get_str("series_uid");
                auto priority_str = get_str("priority");
                // Map priority string to enum
                auto priority = client::job_priority::normal;
                if (priority_str == "low") {
                    priority = client::job_priority::low;
                } else if (priority_str == "high") {
                    priority = client::job_priority::high;
                } else if (priority_str == "urgent") {
                    priority = client::job_priority::urgent;
                }
                // Create retrieve job
                std::optional<std::string_view> series_opt;
                if (!series_uid.empty()) {
                    series_opt = series_uid;
                }
                auto job_id = ctx->job_manager->create_retrieve_job(
                    node_id, study_uid, series_opt, priority);
                // Start the job
                auto start_result = ctx->job_manager->start_job(job_id);
                if (start_result.is_err()) {
                    res.code = 500;
                    res.body = make_error_json("JOB_START_FAILED",
                        "Failed to start retrieve job: " +
                        start_result.error().message);
                    return res;
                }
                std::ostringstream oss;
                oss << R"({"job_id":")" << json_escape(job_id)
                    << R"(","status":"pending"})";
                res.code = 202;
                res.body = oss.str();
                return res;
            });
}
References kcenon::pacs::services::study_query_keys::accession_number, kcenon::pacs::services::patient_query_keys::birth_date, kcenon::pacs::network::association_config::called_ae_title, kcenon::pacs::network::association_config::calling_ae_title, kcenon::pacs::security::atna_coded_value::code, kcenon::pacs::network::association::connect(), error_message, kcenon::pacs::services::query_scu::find_instances(), kcenon::pacs::services::query_scu::find_patients(), kcenon::pacs::services::query_scu::find_series(), kcenon::pacs::services::query_scu::find_studies(), kcenon::pacs::client::high, kcenon::pacs::services::instance_query_keys::instance_number, kcenon::pacs::web::json_escape(), kcenon::pacs::client::low, kcenon::pacs::web::make_error_json(), kcenon::pacs::services::study_query_keys::modality, kcenon::pacs::services::series_query_keys::modality, kcenon::pacs::client::node_status_from_string(), kcenon::pacs::client::normal, kcenon::pacs::services::patient_query_keys::patient_id, kcenon::pacs::services::study_query_keys::patient_id, kcenon::pacs::services::patient_query_keys::patient_name, kcenon::pacs::network::association_config::proposed_contexts, kcenon::pacs::services::series_query_keys::series_number, kcenon::pacs::services::series_query_keys::series_uid, kcenon::pacs::services::instance_query_keys::series_uid, kcenon::pacs::services::patient_query_keys::sex, kcenon::pacs::services::instance_query_keys::sop_instance_uid, kcenon::pacs::services::study_query_keys::study_date, kcenon::pacs::services::study_query_keys::study_description, kcenon::pacs::services::study_root_find_sop_class_uid, kcenon::pacs::services::study_query_keys::study_uid, kcenon::pacs::services::series_query_keys::study_uid, kcenon::pacs::client::to_string(), and kcenon::pacs::client::urgent.
Referenced by kcenon::pacs::web::rest_server::start_async().
register_routing_endpoints_impl()
void kcenon::pacs::web::endpoints::register_routing_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 637 of file routing_endpoints.cpp.
{
    // GET /api/v1/routing/rules - List routing rules (paginated)
    CROW_ROUTE(app, "/api/v1/routing/rules")
        .methods(crow::HTTPMethod::GET)([ctx](const crow::request& req) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->routing_manager) {
                res.code = 503;
                res.body = make_error_json("SERVICE_UNAVAILABLE",
                                           "Routing manager not configured");
                return res;
            }
            // Parse pagination
            auto [limit, offset] = parse_pagination(req);
            // Filter by enabled if provided
            auto enabled_param = req.url_params.get("enabled");
            std::vector<client::routing_rule> rules;
            if (enabled_param) {
                std::string enabled_str(enabled_param);
                if (enabled_str == "true") {
                    rules = ctx->routing_manager->list_enabled_rules();
                } else {
                    rules = ctx->routing_manager->list_rules();
                }
            } else {
                rules = ctx->routing_manager->list_rules();
            }
            size_t total_count = rules.size();
            // Apply pagination
            std::vector<client::routing_rule> paginated;
            for (size_t i = offset; i < rules.size() && paginated.size() < limit; ++i) {
                paginated.push_back(rules[i]);
            }
            res.code = 200;
            res.body = rules_to_json(paginated, total_count);
            return res;
        });
    // POST /api/v1/routing/rules - Create a new routing rule
    CROW_ROUTE(app, "/api/v1/routing/rules")
        .methods(crow::HTTPMethod::POST)([ctx](const crow::request& req) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->routing_manager) {
                res.code = 503;
                res.body = make_error_json("SERVICE_UNAVAILABLE",
                                           "Routing manager not configured");
                return res;
            }
            std::string error_message;
            auto rule_opt = parse_rule_from_json(req.body, error_message);
            if (!rule_opt) {
                res.code = 400;
                res.body = make_error_json("INVALID_REQUEST", error_message);
                return res;
            }
            auto& rule = *rule_opt;
            // Generate rule_id if not provided
            if (rule.rule_id.empty()) {
                auto now = std::chrono::system_clock::now();
                auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
                    now.time_since_epoch()).count();
                rule.rule_id = "rule_" + std::to_string(ms);
            }
            auto result = ctx->routing_manager->add_rule(rule);
            if (!result.is_ok()) {
                res.code = 409;
                res.body = make_error_json("CONFLICT", result.error().message);
                return res;
            }
            // Retrieve the created rule to get full details
            auto created_rule = ctx->routing_manager->get_rule(rule.rule_id);
            if (!created_rule) {
                res.code = 201;
                res.body = rule_to_json(rule);
                return res;
            }
            res.code = 201;
            res.body = rule_to_json(*created_rule);
            return res;
        });
    // GET /api/v1/routing/rules/<ruleId> - Get a specific routing rule
    CROW_ROUTE(app, "/api/v1/routing/rules/<string>")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& /*req*/, const std::string& rule_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->routing_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Routing manager not configured");
                    return res;
                }
                auto rule = ctx->routing_manager->get_rule(rule_id);
                if (!rule) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Routing rule not found");
                    return res;
                }
                res.code = 200;
                res.body = rule_to_json(*rule);
                return res;
            });
    // PUT /api/v1/routing/rules/<ruleId> - Update a routing rule
    CROW_ROUTE(app, "/api/v1/routing/rules/<string>")
        .methods(crow::HTTPMethod::PUT)(
            [ctx](const crow::request& req, const std::string& rule_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->routing_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Routing manager not configured");
                    return res;
                }
                // Check if rule exists
                auto existing = ctx->routing_manager->get_rule(rule_id);
                if (!existing) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Routing rule not found");
                    return res;
                }
                std::string error_message;
                auto rule_opt = parse_rule_from_json(req.body, error_message);
                if (!rule_opt) {
                    res.code = 400;
                    res.body = make_error_json("INVALID_REQUEST", error_message);
                    return res;
                }
                auto& rule = *rule_opt;
                rule.rule_id = rule_id; // Preserve the rule_id from URL
                auto result = ctx->routing_manager->update_rule(rule);
                if (!result.is_ok()) {
                    res.code = 500;
                    res.body = make_error_json("UPDATE_FAILED", result.error().message);
                    return res;
                }
                // Retrieve the updated rule
                auto updated_rule = ctx->routing_manager->get_rule(rule_id);
                if (!updated_rule) {
                    res.code = 200;
                    res.body = rule_to_json(rule);
                    return res;
                }
                res.code = 200;
                res.body = rule_to_json(*updated_rule);
                return res;
            });
    // DELETE /api/v1/routing/rules/<ruleId> - Delete a routing rule
    CROW_ROUTE(app, "/api/v1/routing/rules/<string>")
        .methods(crow::HTTPMethod::DELETE)(
            [ctx](const crow::request& /*req*/, const std::string& rule_id) {
                crow::response res;
                add_cors_headers(res, *ctx);
                if (!ctx->routing_manager) {
                    res.add_header("Content-Type", "application/json");
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Routing manager not configured");
                    return res;
                }
                // Check if rule exists
                auto existing = ctx->routing_manager->get_rule(rule_id);
                if (!existing) {
                    res.add_header("Content-Type", "application/json");
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Routing rule not found");
                    return res;
                }
                auto result = ctx->routing_manager->remove_rule(rule_id);
                if (!result.is_ok()) {
                    res.add_header("Content-Type", "application/json");
                    res.code = 500;
                    res.body = make_error_json("DELETE_FAILED", result.error().message);
                    return res;
                }
                res.code = 204;
                return res;
            });
    // POST /api/v1/routing/rules/reorder - Reorder routing rules
    CROW_ROUTE(app, "/api/v1/routing/rules/reorder")
        .methods(crow::HTTPMethod::POST)([ctx](const crow::request& req) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->routing_manager) {
                res.code = 503;
                res.body = make_error_json("SERVICE_UNAVAILABLE",
                                           "Routing manager not configured");
                return res;
            }
            auto rule_ids = parse_rule_ids(req.body);
            if (rule_ids.empty()) {
                res.code = 400;
                res.body = make_error_json("INVALID_REQUEST",
                                           "rule_ids array is required");
                return res;
            }
            auto result = ctx->routing_manager->reorder_rules(rule_ids);
            if (!result.is_ok()) {
                res.code = 400;
                res.body = make_error_json("REORDER_FAILED", result.error().message);
                return res;
            }
            res.code = 200;
            res.body = R"({"status":"success"})";
            return res;
        });
    // POST /api/v1/routing/enable - Enable routing globally
    CROW_ROUTE(app, "/api/v1/routing/enable")
        .methods(crow::HTTPMethod::POST)([ctx](const crow::request& /*req*/) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->routing_manager) {
                res.code = 503;
                res.body = make_error_json("SERVICE_UNAVAILABLE",
                                           "Routing manager not configured");
                return res;
            }
            ctx->routing_manager->enable();
            res.code = 200;
            res.body = R"({"enabled":true})";
            return res;
        });
    // POST /api/v1/routing/disable - Disable routing globally
    CROW_ROUTE(app, "/api/v1/routing/disable")
        .methods(crow::HTTPMethod::POST)([ctx](const crow::request& /*req*/) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->routing_manager) {
                res.code = 503;
                res.body = make_error_json("SERVICE_UNAVAILABLE",
                                           "Routing manager not configured");
                return res;
            }
            ctx->routing_manager->disable();
            res.code = 200;
            res.body = R"({"enabled":false})";
            return res;
        });
    // GET /api/v1/routing/status - Get routing status and statistics
    CROW_ROUTE(app, "/api/v1/routing/status")
        .methods(crow::HTTPMethod::GET)([ctx](const crow::request& /*req*/) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->routing_manager) {
                res.code = 503;
                res.body = make_error_json("SERVICE_UNAVAILABLE",
                                           "Routing manager not configured");
                return res;
            }
            bool enabled = ctx->routing_manager->is_enabled();
            auto all_rules = ctx->routing_manager->list_rules();
            auto enabled_rules = ctx->routing_manager->list_enabled_rules();
            auto stats = ctx->routing_manager->get_statistics();
            std::ostringstream oss;
            oss << R"({"enabled":)" << (enabled ? "true" : "false")
                << R"(,"rules_count":)" << all_rules.size()
                << R"(,"enabled_rules_count":)" << enabled_rules.size()
                << R"(,"statistics":{)"
                << R"("total_evaluated":)" << stats.total_evaluated
                << R"(,"total_matched":)" << stats.total_matched
                << R"(,"total_forwarded":)" << stats.total_forwarded
                << R"(,"total_failed":)" << stats.total_failed
                << R"(}})";
            res.code = 200;
            res.body = oss.str();
            return res;
        });
    // POST /api/v1/routing/test - Test all rules against a dataset (dry run)
    CROW_ROUTE(app, "/api/v1/routing/test")
        .methods(crow::HTTPMethod::POST)([ctx](const crow::request& req) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->routing_manager) {
                res.code = 503;
                res.body = make_error_json("SERVICE_UNAVAILABLE",
                                           "Routing manager not configured");
                return res;
            }
            // Parse dataset from request body
            auto dataset = parse_test_dataset(req.body);
            if (dataset.empty()) {
                res.code = 400;
                res.body = make_error_json("INVALID_REQUEST",
                                           "dataset object is required");
                return res;
            }
            // Evaluate rules against the dataset
            // Note: evaluate_with_rule_ids requires routing to be enabled,
            // so we use a direct evaluation approach for testing
            auto matches = ctx->routing_manager->evaluate_with_rule_ids(dataset);
            bool matched = !matches.empty();
            res.code = 200;
            res.body = test_result_to_json(matched, matches, ctx->routing_manager);
            return res;
        });
    // POST /api/v1/routing/rules/<ruleId>/test - Test specific rule against a dataset
    CROW_ROUTE(app, "/api/v1/routing/rules/<string>/test")
        .methods(crow::HTTPMethod::POST)(
            [ctx](const crow::request& req, const std::string& rule_id) {
                crow::response res;
                res.add_header("Content-Type", "application/json");
                add_cors_headers(res, *ctx);
                if (!ctx->routing_manager) {
                    res.code = 503;
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Routing manager not configured");
                    return res;
                }
                // Check if rule exists
                auto rule = ctx->routing_manager->get_rule(rule_id);
                if (!rule) {
                    res.code = 404;
                    res.body = make_error_json("NOT_FOUND", "Routing rule not found");
                    return res;
                }
                // Parse dataset from request body
                auto dataset = parse_test_dataset(req.body);
                if (dataset.empty()) {
                    res.code = 400;
                    res.body = make_error_json("INVALID_REQUEST",
                                               "dataset object is required");
                    return res;
                }
                // Test only this specific rule
                // We need to manually check if all conditions match
                bool all_match = !rule->conditions.empty();
                for (const auto& condition : rule->conditions) {
                    // Get the field value from dataset
                    std::string value;
                    switch (condition.match_field) {
                        case client::routing_field::modality:
                            value = dataset.get_string(core::tags::modality);
                            break;
                        case client::routing_field::station_ae:
                            value = dataset.get_string(core::tags::station_name);
                            break;
                        case client::routing_field::institution:
                            value = dataset.get_string(core::tags::institution_name);
                            break;
                        case client::routing_field::department:
                            value = dataset.get_string(core::dicom_tag{0x0008, 0x1040});
                            break;
                        case client::routing_field::referring_physician:
                            value = dataset.get_string(core::tags::referring_physician_name);
                            break;
                        case client::routing_field::study_description:
                            value = dataset.get_string(core::tags::study_description);
                            break;
                        case client::routing_field::series_description:
                            value = dataset.get_string(core::tags::series_description);
                            break;
                        case client::routing_field::body_part:
                            value = dataset.get_string(core::dicom_tag{0x0018, 0x0015});
                            break;
                        case client::routing_field::patient_id_pattern:
                            value = dataset.get_string(core::tags::patient_id);
                            break;
                        case client::routing_field::sop_class_uid:
                            value = dataset.get_string(core::tags::sop_class_uid);
                            break;
                        default:
                            break;
                    }
                    // Simple wildcard matching
                    auto match_wildcard = [](std::string_view pattern,
                                            std::string_view val,
                                            bool case_sensitive) -> bool {
                        auto to_lower = [](std::string_view s) {
                            std::string result;
                            result.reserve(s.size());
                            for (char c : s) {
                                result += static_cast<char>(std::tolower(
                                    static_cast<unsigned char>(c)));
                            }
                            return result;
                        };
                        std::string pat_str = case_sensitive ?
                            std::string(pattern) : to_lower(pattern);
                        std::string val_str = case_sensitive ?
                            std::string(val) : to_lower(val);
                        const char* p = pat_str.c_str();
                        const char* v = val_str.c_str();
                        const char* star_p = nullptr;
                        const char* star_v = nullptr;
                        while (*v) {
                            if (*p == '*') {
                                star_p = p++;
                                star_v = v;
                            } else if (*p == '?' || *p == *v) {
                                ++p;
                                ++v;
                            } else if (star_p) {
                                p = star_p + 1;
                                v = ++star_v;
                            } else {
                                return false;
                            }
                        }
                        while (*p == '*') {
                            ++p;
                        }
                        return *p == '\0';
                    };
                    bool matched = match_wildcard(condition.pattern, value,
                                                  condition.case_sensitive);
                    if (condition.negate) {
                        matched = !matched;
                    }
                    if (!matched) {
                        all_match = false;
                        break;
                    }
                }
                res.code = 200;
                if (all_match) {
                    res.body = single_rule_test_to_json(true, rule->actions);
                } else {
                    res.body = single_rule_test_to_json(false, {});
                }
                return res;
            });
}
References kcenon::pacs::client::body_part, kcenon::pacs::client::department, error_message, kcenon::pacs::client::institution, kcenon::pacs::core::tags::institution_name, kcenon::pacs::web::make_error_json(), kcenon::pacs::client::modality, kcenon::pacs::core::tags::modality, kcenon::pacs::core::tags::patient_id, kcenon::pacs::client::patient_id_pattern, kcenon::pacs::client::referring_physician, kcenon::pacs::core::tags::referring_physician_name, kcenon::pacs::client::series_description, kcenon::pacs::core::tags::series_description, kcenon::pacs::client::sop_class_uid, kcenon::pacs::core::tags::sop_class_uid, kcenon::pacs::client::station_ae, kcenon::pacs::core::tags::station_name, kcenon::pacs::client::study_description, and kcenon::pacs::core::tags::study_description.
Referenced by kcenon::pacs::web::rest_server::start_async().
register_security_endpoints_impl()
void kcenon::pacs::web::endpoints::register_security_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Register security endpoints with the Crow app.
Parameters
app Crow application instance
ctx Shared server context
Definition at line 46 of file security_endpoints.cpp.
{
  // POST /api/v1/security/users - Create a new user
  CROW_ROUTE(app, "/api/v1/security/users")
      .methods(crow::HTTPMethod::POST)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        if (!ctx->security_manager) {
          res.body = make_error_json("SECURITY_UNAVAILABLE",
                                     "Security manager not configured");
          res.code = 503;
          return res;
        }
        auto x = crow::json::load(req.body);
        if (!x) {
          res.body = make_error_json("INVALID_JSON", "Invalid JSON body");
          res.code = 400;
          return res;
        }
        if (!x.has("username") || !x.has("id")) {
          res.body =
              make_error_json("MISSING_FIELDS", "Username and ID are required");
          res.code = 400;
          return res;
        }
        kcenon::pacs::security::User user;
        user.id = x["id"].s();
        user.username = x["username"].s();
        user.active = true; // Default to active
        auto result = ctx->security_manager->create_user(user);
        if (result.is_err()) {
          res.body = make_error_json(
              "CREATE_FAILED", "Failed to create user"); // In real app, expose
                                                         // inner error safely
          res.code = 500;
        } else {
          res.body = make_success_json("User created");
          res.code = 201;
        }
        return res;
      });
  // POST /api/v1/security/users/<id>/roles - Assign role to user
  CROW_ROUTE(app, "/api/v1/security/users/<string>/roles")
      .methods(crow::HTTPMethod::POST)([ctx](const crow::request &req,
                                             std::string user_id) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        if (!ctx->security_manager) {
          res.body = make_error_json("SECURITY_UNAVAILABLE",
                                     "Security manager not configured");
          res.code = 503;
          return res;
        }
        auto x = crow::json::load(req.body);
        if (!x || !x.has("role")) {
          res.body = make_error_json("INVALID_REQUEST", "Role is required");
          res.code = 400;
          return res;
        }
        std::string role_str = x["role"].s();
        auto role_opt = kcenon::pacs::security::parse_role(role_str);
        if (!role_opt) {
          res.body = make_error_json("INVALID_ROLE", "Invalid role specified");
          res.code = 400;
          return res;
        }
        auto result = ctx->security_manager->assign_role(user_id, *role_opt);
        if (result.is_err()) {
          // Could distinguish user not found vs other errors
          res.body = make_error_json("ASSIGN_FAILED", "Failed to assign role");
          res.code = 500;
        } else {
          res.body = make_success_json("Role assigned");
          res.code = 200;
        }
        return res;
      });
}
References kcenon::pacs::web::make_error_json(), kcenon::pacs::web::make_success_json(), and kcenon::pacs::security::parse_role().
Referenced by kcenon::pacs::web::rest_server::start_async().
register_series_endpoints_impl()
void kcenon::pacs::web::endpoints::register_series_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 125 of file series_endpoints.cpp.
{
  // GET /api/v1/series/:uid - Get series details
  CROW_ROUTE(app, "/api/v1/series/<string>")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/, const std::string &series_uid) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            auto series = ctx->database->find_series(series_uid);
            if (!series) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Series not found");
              return res;
            }
            res.code = 200;
            res.body = series_to_json(*series);
            return res;
          });
  // GET /api/v1/series/:uid/instances - Get series instances
  CROW_ROUTE(app, "/api/v1/series/<string>/instances")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/, const std::string &series_uid) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            // Verify series exists
            auto series = ctx->database->find_series(series_uid);
            if (!series) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Series not found");
              return res;
            }
            auto instances_result = ctx->database->list_instances(series_uid);
            if (!instances_result.is_ok()) {
              res.code = 500;
              res.body = make_error_json("QUERY_ERROR",
                                         instances_result.error().message);
              return res;
            }
            res.code = 200;
            res.body = instances_to_json(instances_result.value());
            return res;
          });
}
References kcenon::pacs::web::make_error_json().
Referenced by kcenon::pacs::web::rest_server::start_async().
register_storage_commitment_endpoints_impl()
void kcenon::pacs::web::endpoints::register_storage_commitment_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 431 of file storage_commitment_endpoints.cpp.
{
    // Shared transaction store for all requests
    auto store = std::make_shared<storage_commitment::transaction_store>();
    // POST /dicomweb/storage-commitments
    // Request storage commitment for a list of SOP Instances
    CROW_ROUTE(app, "/dicomweb/storage-commitments")
        .methods(crow::HTTPMethod::POST)(
            [ctx, store](const crow::request& req) {
                crow::response res;
                res.add_header("Content-Type", "application/dicom+json");
                add_cors_headers(res, *ctx);
                if (!check_storage_commitment_auth(
                        ctx, req, res, {"dicomweb.write"})) {
                    return res;
                }
                if (!ctx->database) {
                    res.code = 503;
                    res.body = make_error_json(
                        "DATABASE_UNAVAILABLE",
                        "Storage service is not available");
                    return res;
                }
                auto parsed = storage_commitment::parse_commitment_request(
                    req.body);
                if (!parsed.valid) {
                    res.code = 400;
                    res.body = make_error_json(
                        "INVALID_REQUEST", parsed.error_message);
                    return res;
                }
                // Create transaction
                storage_commitment::commitment_transaction txn;
                txn.transaction_uid = generate_transaction_uid();
                txn.state = storage_commitment::transaction_state::pending;
                txn.requested_references = std::move(parsed.references);
                txn.created_at = std::chrono::system_clock::now();
                store->add(txn);
                // Verify instances synchronously for simplicity
                // (async with thread pool in production)
                verify_instances_async(ctx, store, txn.transaction_uid);
                auto result = store->find(txn.transaction_uid);
                res.code = 202;  // Accepted
                res.add_header("Content-Location",
                               "/dicomweb/storage-commitments/" +
                                   txn.transaction_uid);
                res.body = storage_commitment::transaction_to_json(*result);
                return res;
            });
    // POST /dicomweb/studies/{studyUID}/commitment
    // Request storage commitment for a study
    CROW_ROUTE(app, "/dicomweb/studies/<string>/commitment")
        .methods(crow::HTTPMethod::POST)(
            [ctx, store](const crow::request& req,
                         const std::string& study_uid) {
                crow::response res;
                res.add_header("Content-Type", "application/dicom+json");
                add_cors_headers(res, *ctx);
                if (!check_storage_commitment_auth(
                        ctx, req, res, {"dicomweb.write"})) {
                    return res;
                }
                if (!ctx->database) {
                    res.code = 503;
                    res.body = make_error_json(
                        "DATABASE_UNAVAILABLE",
                        "Storage service is not available");
                    return res;
                }
                auto parsed = storage_commitment::parse_commitment_request(
                    req.body, study_uid);
                if (!parsed.valid) {
                    res.code = 400;
                    res.body = make_error_json(
                        "INVALID_REQUEST", parsed.error_message);
                    return res;
                }
                storage_commitment::commitment_transaction txn;
                txn.transaction_uid = generate_transaction_uid();
                txn.state = storage_commitment::transaction_state::pending;
                txn.requested_references = std::move(parsed.references);
                txn.study_instance_uid = study_uid;
                txn.created_at = std::chrono::system_clock::now();
                store->add(txn);
                verify_instances_async(ctx, store, txn.transaction_uid);
                auto result = store->find(txn.transaction_uid);
                res.code = 202;
                res.add_header("Content-Location",
                               "/dicomweb/storage-commitments/" +
                                   txn.transaction_uid);
                res.body = storage_commitment::transaction_to_json(*result);
                return res;
            });
    // GET /dicomweb/storage-commitments/{transactionUID}
    // Check commitment status
    CROW_ROUTE(app, "/dicomweb/storage-commitments/<string>")
        .methods(crow::HTTPMethod::GET)(
            [ctx, store](const crow::request& req,
                         const std::string& transaction_uid) {
                crow::response res;
                res.add_header("Content-Type", "application/dicom+json");
                add_cors_headers(res, *ctx);
                if (!check_storage_commitment_auth(
                        ctx, req, res, {"dicomweb.read"})) {
                    return res;
                }
                auto txn = store->find(transaction_uid);
                if (!txn) {
                    res.code = 404;
                    res.body = make_error_json(
                        "NOT_FOUND",
                        "Transaction not found: " + transaction_uid);
                    return res;
                }
                res.code = 200;
                res.body = storage_commitment::transaction_to_json(*txn);
                return res;
            });
    // GET /dicomweb/storage-commitments
    // List all commitment transactions
    CROW_ROUTE(app, "/dicomweb/storage-commitments")
        .methods(crow::HTTPMethod::GET)(
            [ctx, store](const crow::request& req) {
                crow::response res;
                res.add_header("Content-Type", "application/dicom+json");
                add_cors_headers(res, *ctx);
                if (!check_storage_commitment_auth(
                        ctx, req, res, {"dicomweb.read"})) {
                    return res;
                }
                size_t limit = 100;
                auto limit_param = req.url_params.get("limit");
                if (limit_param != nullptr) {
                    try {
                        int val = std::stoi(limit_param);
                        if (val > 0) {
                            limit = static_cast<size_t>(val);
                        }
                    } catch (...) {
                        // Use default
                    }
                }
                auto transactions = store->list(limit);
                res.code = 200;
                res.body = storage_commitment::transactions_to_json(transactions);
                return res;
            });
}
References kcenon::pacs::web::storage_commitment::commitment_transaction::created_at, kcenon::pacs::web::make_error_json(), kcenon::pacs::web::storage_commitment::parse_commitment_request(), kcenon::pacs::web::storage_commitment::pending, kcenon::pacs::web::storage_commitment::commitment_transaction::requested_references, kcenon::pacs::web::storage_commitment::commitment_transaction::state, kcenon::pacs::web::storage_commitment::commitment_transaction::study_instance_uid, kcenon::pacs::web::storage_commitment::transaction_to_json(), kcenon::pacs::web::storage_commitment::commitment_transaction::transaction_uid, and kcenon::pacs::web::storage_commitment::transactions_to_json().
Referenced by kcenon::pacs::web::rest_server::start_async().
register_study_endpoints_impl()
void kcenon::pacs::web::endpoints::register_study_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 217 of file study_endpoints.cpp.
{
  // GET /api/v1/studies - List studies (paginated)
  CROW_ROUTE(app, "/api/v1/studies")
      .methods(crow::HTTPMethod::GET)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        if (!ctx->database) {
          res.code = 503;
          res.body =
              make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
          return res;
        }
        // Parse pagination
        auto [limit, offset] = parse_pagination(req);
        // Build query from URL parameters
        storage::study_query query;
        query.limit = limit;
        query.offset = offset;
        auto patient_id = req.url_params.get("patient_id");
        if (patient_id) {
          query.patient_id = patient_id;
        }
        auto patient_name = req.url_params.get("patient_name");
        if (patient_name) {
          query.patient_name = patient_name;
        }
        auto study_uid = req.url_params.get("study_uid");
        if (study_uid) {
          query.study_uid = study_uid;
        }
        auto study_id = req.url_params.get("study_id");
        if (study_id) {
          query.study_id = study_id;
        }
        auto study_date = req.url_params.get("study_date");
        if (study_date) {
          query.study_date = study_date;
        }
        auto study_date_from = req.url_params.get("study_date_from");
        if (study_date_from) {
          query.study_date_from = study_date_from;
        }
        auto study_date_to = req.url_params.get("study_date_to");
        if (study_date_to) {
          query.study_date_to = study_date_to;
        }
        auto accession_number = req.url_params.get("accession_number");
        if (accession_number) {
          query.accession_number = accession_number;
        }
        auto modality = req.url_params.get("modality");
        if (modality) {
          query.modality = modality;
        }
        auto referring_physician = req.url_params.get("referring_physician");
        if (referring_physician) {
          query.referring_physician = referring_physician;
        }
        auto study_description = req.url_params.get("study_description");
        if (study_description) {
          query.study_description = study_description;
        }
        // Get total count (without pagination)
        storage::study_query count_query = query;
        count_query.limit = 0;
        count_query.offset = 0;
        auto all_studies_result = ctx->database->search_studies(count_query);
        if (!all_studies_result.is_ok()) {
          res.code = 500;
          res.body = make_error_json("QUERY_ERROR",
                                     all_studies_result.error().message);
          return res;
        }
        size_t total_count = all_studies_result.value().size();
        // Get paginated results
        auto studies_result = ctx->database->search_studies(query);
        if (!studies_result.is_ok()) {
          res.code = 500;
          res.body = make_error_json("QUERY_ERROR",
                                     studies_result.error().message);
          return res;
        }
        res.code = 200;
        res.body = studies_to_json(studies_result.value(), total_count);
        return res;
      });
  // GET /api/v1/studies/:uid - Get study details
  CROW_ROUTE(app, "/api/v1/studies/<string>")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/, const std::string &study_uid) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            auto study = ctx->database->find_study(study_uid);
            if (!study) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Study not found");
              return res;
            }
            res.code = 200;
            res.body = study_to_json(*study);
            return res;
          });
  // GET /api/v1/studies/:uid/series - Get study's series
  CROW_ROUTE(app, "/api/v1/studies/<string>/series")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/, const std::string &study_uid) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            // Verify study exists
            auto study = ctx->database->find_study(study_uid);
            if (!study) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Study not found");
              return res;
            }
            auto series_list_result = ctx->database->list_series(study_uid);
            if (!series_list_result.is_ok()) {
              res.code = 500;
              res.body = make_error_json("QUERY_ERROR",
                                         series_list_result.error().message);
              return res;
            }
            res.code = 200;
            res.body = series_list_to_json(series_list_result.value());
            return res;
          });
  // GET /api/v1/studies/:uid/instances - Get study's instances (all series)
  CROW_ROUTE(app, "/api/v1/studies/<string>/instances")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/, const std::string &study_uid) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            // Verify study exists
            auto study = ctx->database->find_study(study_uid);
            if (!study) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Study not found");
              return res;
            }
            // Get all series and their instances
            std::vector<storage::instance_record> all_instances;
            auto series_list_result = ctx->database->list_series(study_uid);
            if (!series_list_result.is_ok()) {
              res.code = 500;
              res.body = make_error_json("QUERY_ERROR",
                                         series_list_result.error().message);
              return res;
            }
            for (const auto &series : series_list_result.value()) {
              auto instances_result = ctx->database->list_instances(series.series_uid);
              if (!instances_result.is_ok()) {
                res.code = 500;
                res.body = make_error_json("QUERY_ERROR",
                                           instances_result.error().message);
                return res;
              }
              const auto& instances = instances_result.value();
              all_instances.insert(all_instances.end(), instances.begin(),
                                   instances.end());
            }
            res.code = 200;
            res.body = instances_to_json(all_instances);
            return res;
          });
  // DELETE /api/v1/studies/:uid - Delete study
  CROW_ROUTE(app, "/api/v1/studies/<string>")
      .methods(crow::HTTPMethod::DELETE)(
          [ctx](const crow::request & /*req*/, const std::string &study_uid) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            // Verify study exists
            auto study = ctx->database->find_study(study_uid);
            if (!study) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Study not found");
              return res;
            }
            auto result = ctx->database->delete_study(study_uid);
            if (result.is_err()) {
              res.code = 500;
              res.body = make_error_json("DELETE_FAILED",
                                         result.error().message);
              return res;
            }
            res.code = 200;
            res.body = make_success_json("Study deleted successfully");
            return res;
          });
}
References kcenon::pacs::storage::study_query::limit, kcenon::pacs::web::make_error_json(), kcenon::pacs::web::make_success_json(), and kcenon::pacs::storage::study_query::offset.
Referenced by kcenon::pacs::web::rest_server::start_async().
register_system_endpoints_impl()
void kcenon::pacs::web::endpoints::register_system_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 131 of file system_endpoints.cpp.
{
  // GET /api/v1/system/status - System health status
  CROW_ROUTE(app, "/api/v1/system/status")
      .methods(crow::HTTPMethod::GET)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        // Permission Check: System Read
        if (!check_permission(ctx, req, res, security::ResourceType::System,
                              security::Action::Read)) {
          return res;
        }
        crow::json::wvalue status_json;
        status_json["status"] = "unknown";                        // Default
        status_json["message"] = "Health checker not configured"; // Default
        status_json["version"] = "1.0.0";                         // Default
#ifdef PACS_WITH_MONITORING
        if (ctx->health_checker) {
          auto status = ctx->health_checker->get_status();
          // to_json is a free function in kcenon::pacs::monitoring namespace
          status_json = crow::json::load(
              monitoring::to_json(status)); // Parse existing JSON into wvalue
          status_json["version"] = "1.0.0"; // Add version
        } else {
          status_json["status"] = "unknown";
          status_json["message"] = "Health checker not configured";
        }
#else
        // Basic status without monitoring module
        res.code = 200;
#endif
        return res;
      });
  // GET /api/v1/system/metrics - Performance metrics
  CROW_ROUTE(app, "/api/v1/system/metrics").methods(crow::HTTPMethod::GET)([ctx]() {
    crow::response res;
    res.add_header("Content-Type", "application/json");
    add_cors_headers(res, *ctx);
#ifdef PACS_WITH_MONITORING
    if (ctx->metrics) {
      // pacs_metrics provides individual counters, build simple JSON
      std::ostringstream oss;
      oss << R"({"message":"Metrics available via pacs_metrics API"})";
      res.body = oss.str();
      res.code = 200;
    } else {
      res.body =
          R"({"error":{"code":"METRICS_UNAVAILABLE","message":"Metrics provider not configured"}})";
      res.code = 503;
    }
#else
    // Basic metrics without monitoring module
    res.body =
        R"({"uptime_seconds":0,"requests_total":0,"message":"Metrics module not available"})";
    res.code = 200;
#endif
    return res;
  });
  // GET /api/v1/system/config - Current configuration
  CROW_ROUTE(app, "/api/v1/system/config")
      .methods(crow::HTTPMethod::GET)([ctx]() {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        if (ctx->config) {
          res.body = config_to_json(*ctx->config);
          res.code = 200;
        } else {
          res.body = make_error_json("CONFIG_UNAVAILABLE",
                                     "Configuration not available");
          res.code = 500;
        }
        return res;
      });
  // PUT /api/v1/system/config - Update configuration
  CROW_ROUTE(app, "/api/v1/system/config")
      .methods(crow::HTTPMethod::PUT)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        // Validate content type
        auto content_type = req.get_header_value("Content-Type");
        if (content_type.find("application/json") == std::string::npos) {
          res.body = make_error_json("INVALID_CONTENT_TYPE",
                                     "Content-Type must be application/json");
          res.code = 415;
          return res;
        }
        // Validate body is not empty
        if (req.body.empty()) {
          res.body = make_error_json("EMPTY_BODY", "Request body is required");
          res.code = 400;
          return res;
        }
        // Note: Full configuration update would require parsing JSON and
        // updating the config. For now, we return a placeholder success
        // response. Actual implementation would need a callback or direct
        // config reference.
        res.body = make_success_json("Configuration update acknowledged");
        res.code = 200;
        return res;
      });
  // GET /api/v1/system/version - API version info
  CROW_ROUTE(app, "/api/v1/system/version").methods(crow::HTTPMethod::GET)([ctx]() {
    crow::response res;
    res.add_header("Content-Type", "application/json");
    add_cors_headers(res, *ctx);
    res.body =
        R"({"api_version":"v1","pacs_version":"1.2.0","crow_version":"1.2.0"})";
    res.code = 200;
    return res;
  });
}
References kcenon::pacs::web::make_error_json(), kcenon::pacs::web::make_success_json(), kcenon::pacs::security::Action::Read, and kcenon::pacs::security::System.
Referenced by kcenon::pacs::web::rest_server::start(), and kcenon::pacs::web::rest_server::start_async().
register_thumbnail_endpoints_impl()
void kcenon::pacs::web::endpoints::register_thumbnail_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 138 of file thumbnail_endpoints.cpp.
{
    // Initialize thumbnail service if database is available
    if (ctx->database != nullptr && g_thumbnail_service == nullptr) {
        g_thumbnail_service =
            std::make_shared<thumbnail_service>(ctx->database);
    }
    // GET /api/v1/thumbnails/instances/{sopInstanceUid}
    CROW_ROUTE(app, "/api/v1/thumbnails/instances/<string>")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req, const std::string& sop_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                if (g_thumbnail_service == nullptr) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Thumbnail service not configured");
                    return res;
                }
                auto params = parse_thumbnail_params(req);
                auto result = g_thumbnail_service->get_thumbnail(sop_uid, params);
                if (!result.success) {
                    res.code = 404;
                    res.add_header("Content-Type", "application/json");
                    res.body =
                        make_error_json("NOT_FOUND", result.error_message);
                    return res;
                }
                res.code = 200;
                res.add_header("Content-Type", result.entry.content_type);
                res.add_header("Cache-Control", "max-age=3600");
                res.body = std::string(
                    reinterpret_cast<const char*>(result.entry.data.data()),
                    result.entry.data.size());
                return res;
            });
    // GET /api/v1/thumbnails/series/{seriesUid}
    CROW_ROUTE(app, "/api/v1/thumbnails/series/<string>")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req, const std::string& series_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                if (g_thumbnail_service == nullptr) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Thumbnail service not configured");
                    return res;
                }
                auto params = parse_thumbnail_params(req);
                auto result =
                    g_thumbnail_service->get_series_thumbnail(series_uid, params);
                if (!result.success) {
                    res.code = 404;
                    res.add_header("Content-Type", "application/json");
                    res.body =
                        make_error_json("NOT_FOUND", result.error_message);
                    return res;
                }
                res.code = 200;
                res.add_header("Content-Type", result.entry.content_type);
                res.add_header("Cache-Control", "max-age=3600");
                res.body = std::string(
                    reinterpret_cast<const char*>(result.entry.data.data()),
                    result.entry.data.size());
                return res;
            });
    // GET /api/v1/thumbnails/studies/{studyUid}
    CROW_ROUTE(app, "/api/v1/thumbnails/studies/<string>")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req, const std::string& study_uid) {
                crow::response res;
                add_cors_headers(res, *ctx);
                if (g_thumbnail_service == nullptr) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json("SERVICE_UNAVAILABLE",
                                               "Thumbnail service not configured");
                    return res;
                }
                auto params = parse_thumbnail_params(req);
                auto result =
                    g_thumbnail_service->get_study_thumbnail(study_uid, params);
                if (!result.success) {
                    res.code = 404;
                    res.add_header("Content-Type", "application/json");
                    res.body =
                        make_error_json("NOT_FOUND", result.error_message);
                    return res;
                }
                res.code = 200;
                res.add_header("Content-Type", result.entry.content_type);
                res.add_header("Cache-Control", "max-age=3600");
                res.body = std::string(
                    reinterpret_cast<const char*>(result.entry.data.data()),
                    result.entry.data.size());
                return res;
            });
    // DELETE /api/v1/thumbnails/cache - Clear all cached thumbnails
    CROW_ROUTE(app, "/api/v1/thumbnails/cache")
        .methods(crow::HTTPMethod::DELETE)([ctx](const crow::request& /*req*/) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (g_thumbnail_service == nullptr) {
                res.code = 503;
                res.body = make_error_json("SERVICE_UNAVAILABLE",
                                           "Thumbnail service not configured");
                return res;
            }
            g_thumbnail_service->clear_cache();
            res.code = 200;
            res.body = make_success_json("Cache cleared successfully");
            return res;
        });
    // GET /api/v1/thumbnails/cache/stats - Get cache statistics
    CROW_ROUTE(app, "/api/v1/thumbnails/cache/stats")
        .methods(crow::HTTPMethod::GET)([ctx](const crow::request& /*req*/) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (g_thumbnail_service == nullptr) {
                res.code = 503;
                res.body = make_error_json("SERVICE_UNAVAILABLE",
                                           "Thumbnail service not configured");
                return res;
            }
            std::ostringstream oss;
            oss << R"({"cache_size":)" << g_thumbnail_service->cache_size()
                << R"(,"entry_count":)" << g_thumbnail_service->cache_entry_count()
                << R"(,"max_size":)" << g_thumbnail_service->max_cache_size()
                << "}";
            res.code = 200;
            res.body = oss.str();
            return res;
        });
}
References kcenon::pacs::web::make_error_json(), and kcenon::pacs::web::make_success_json().
Referenced by kcenon::pacs::web::rest_server::start_async().
register_viewer_state_endpoints_impl()
void kcenon::pacs::web::endpoints::register_viewer_state_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 269 of file viewer_state_endpoints.cpp.
{
  // POST /api/v1/viewer-states - Create viewer state
  CROW_ROUTE(app, "/api/v1/viewer-states")
      .methods(crow::HTTPMethod::POST)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        if (!ctx->database) {
          res.code = 503;
          res.body =
              make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
          return res;
        }
        std::string body = req.body;
        if (body.empty()) {
          res.code = 400;
          res.body = make_error_json("INVALID_REQUEST", "Request body is empty");
          return res;
        }
        storage::viewer_state_record state;
        state.state_id = generate_uuid();
        state.study_uid = parse_json_string(body, "study_uid");
        state.user_id = parse_json_string(body, "user_id");
        state.state_json = build_state_json(body);
        state.created_at = std::chrono::system_clock::now();
        state.updated_at = state.created_at;
        if (state.study_uid.empty()) {
          res.code = 400;
          res.body = make_error_json("MISSING_FIELD", "study_uid is required");
          return res;
        }
 #ifdef PACS_WITH_DATABASE_SYSTEM
        storage::viewer_state_record_repository repo(ctx->database->db_adapter());
        storage::recent_study_repository recent_repo(ctx->database->db_adapter());
#else
        storage::viewer_state_repository repo(ctx->database->native_handle());
#endif
        auto save_result =
#ifdef PACS_WITH_DATABASE_SYSTEM
            repo.save(state);
#else
            repo.save_state(state);
#endif
        if (!save_result.is_ok()) {
          res.code = 500;
          res.body =
              make_error_json("SAVE_ERROR", save_result.error().message);
          return res;
        }
        // Also record study access if user_id is provided
        if (!state.user_id.empty()) {
 #ifdef PACS_WITH_DATABASE_SYSTEM
          (void)recent_repo.record_access(state.user_id, state.study_uid);
 #else
          (void)repo.record_study_access(state.user_id, state.study_uid);
 #endif
        }
        res.code = 201;
        std::ostringstream oss;
        oss << R"({"state_id":")" << json_escape(state.state_id)
            << R"(","created_at":")" << format_timestamp(state.created_at)
            << R"("})";
        res.body = oss.str();
        return res;
      });
  // GET /api/v1/viewer-states - List viewer states
  CROW_ROUTE(app, "/api/v1/viewer-states")
      .methods(crow::HTTPMethod::GET)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        if (!ctx->database) {
          res.code = 503;
          res.body =
              make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
          return res;
        }
        storage::viewer_state_query query;
        auto study_uid = req.url_params.get("study_uid");
        if (study_uid) {
          query.study_uid = study_uid;
        }
        auto user_id = req.url_params.get("user_id");
        if (user_id) {
          query.user_id = user_id;
        }
        auto limit_param = req.url_params.get("limit");
        if (limit_param) {
          try {
            query.limit = std::stoul(limit_param);
            if (query.limit > 100) {
              query.limit = 100;
            }
          } catch (...) {
            // Use default
          }
        }
 #ifdef PACS_WITH_DATABASE_SYSTEM
        storage::viewer_state_record_repository repo(ctx->database->db_adapter());
 #else
        storage::viewer_state_repository repo(ctx->database->native_handle());
#endif
 #ifdef PACS_WITH_DATABASE_SYSTEM
        auto states_result = repo.search(query);
        if (states_result.is_err()) {
          res.code = 500;
          res.body =
              make_error_json("SEARCH_ERROR", states_result.error().message);
          return res;
        }
        auto states = std::move(states_result.value());
 #else
        auto states = repo.search_states(query);
 #endif
        res.code = 200;
        res.body = viewer_states_to_json(states);
        return res;
      });
  // GET /api/v1/viewer-states/<stateId> - Get viewer state by ID
  CROW_ROUTE(app, "/api/v1/viewer-states/<string>")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/, const std::string &state_id) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
 #ifdef PACS_WITH_DATABASE_SYSTEM
            storage::viewer_state_record_repository repo(ctx->database->db_adapter());
 #else
            storage::viewer_state_repository repo(ctx->database->native_handle());
#endif
 #ifdef PACS_WITH_DATABASE_SYSTEM
            auto state_result = repo.find_by_id(state_id);
            if (state_result.is_err()) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Viewer state not found");
              return res;
            }
            auto state = state_result.value();
 #else
            auto state = repo.find_state_by_id(state_id);
            if (!state.has_value()) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Viewer state not found");
              return res;
            }
 #endif
            res.code = 200;
 #ifdef PACS_WITH_DATABASE_SYSTEM
            res.body = viewer_state_to_json(state);
 #else
            res.body = viewer_state_to_json(state.value());
 #endif
            return res;
          });
  // DELETE /api/v1/viewer-states/<stateId> - Delete viewer state
  CROW_ROUTE(app, "/api/v1/viewer-states/<string>")
      .methods(crow::HTTPMethod::DELETE)(
          [ctx](const crow::request & /*req*/, const std::string &state_id) {
            crow::response res;
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
 #ifdef PACS_WITH_DATABASE_SYSTEM
            storage::viewer_state_record_repository repo(ctx->database->db_adapter());
 #else
            storage::viewer_state_repository repo(ctx->database->native_handle());
#endif
 #ifdef PACS_WITH_DATABASE_SYSTEM
            auto existing = repo.find_by_id(state_id);
            if (existing.is_err()) {
              res.code = 404;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("NOT_FOUND", "Viewer state not found");
              return res;
            }
 #else
            auto existing = repo.find_state_by_id(state_id);
            if (!existing.has_value()) {
              res.code = 404;
              res.add_header("Content-Type", "application/json");
              res.body = make_error_json("NOT_FOUND", "Viewer state not found");
              return res;
            }
 #endif
            auto remove_result =
 #ifdef PACS_WITH_DATABASE_SYSTEM
                repo.remove(state_id);
 #else
                repo.remove_state(state_id);
 #endif
            if (!remove_result.is_ok()) {
              res.code = 500;
              res.add_header("Content-Type", "application/json");
              res.body =
                  make_error_json("DELETE_ERROR", remove_result.error().message);
              return res;
            }
            res.code = 204;
            return res;
          });
  // GET /api/v1/users/<userId>/recent-studies - Get recent studies for user
  CROW_ROUTE(app, "/api/v1/users/<string>/recent-studies")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request &req, const std::string &user_id) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            size_t limit = 20;
            auto limit_param = req.url_params.get("limit");
            if (limit_param) {
              try {
                limit = std::stoul(limit_param);
                if (limit > 100) {
                  limit = 100;
                }
              } catch (...) {
                // Use default
              }
            }
 #ifdef PACS_WITH_DATABASE_SYSTEM
            storage::recent_study_repository repo(ctx->database->db_adapter());
 #else
            storage::viewer_state_repository repo(ctx->database->native_handle());
#endif
 #ifdef PACS_WITH_DATABASE_SYSTEM
            auto records_result = repo.find_by_user(user_id, limit);
            if (records_result.is_err()) {
              res.code = 500;
              res.body = make_error_json("SEARCH_ERROR",
                                         records_result.error().message);
              return res;
            }
            auto total_result = repo.count_for_user(user_id);
            if (total_result.is_err()) {
              res.code = 500;
              res.body =
                  make_error_json("COUNT_ERROR", total_result.error().message);
              return res;
            }
            auto records = std::move(records_result.value());
            size_t total = total_result.value();
 #else
            auto records = repo.get_recent_studies(user_id, limit);
            size_t total = repo.count_recent_studies(user_id);
 #endif
            res.code = 200;
            res.body = recent_studies_to_json(records, total);
            return res;
          });
}
References kcenon::pacs::storage::viewer_state_record::created_at, kcenon::pacs::web::json_escape(), kcenon::pacs::web::make_error_json(), kcenon::pacs::storage::viewer_state_record::state_id, kcenon::pacs::storage::viewer_state_record::state_json, kcenon::pacs::storage::viewer_state_record::study_uid, kcenon::pacs::storage::viewer_state_record::updated_at, and kcenon::pacs::storage::viewer_state_record::user_id.
Referenced by kcenon::pacs::web::rest_server::start_async().
register_wado_uri_endpoints_impl()
void kcenon::pacs::web::endpoints::register_wado_uri_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 325 of file wado_uri_endpoints.cpp.
{
    // GET /wado?requestType=WADO&studyUID=...&seriesUID=...&objectUID=...
    CROW_ROUTE(app, "/wado")
        .methods(crow::HTTPMethod::GET)(
            [ctx](const crow::request& req) {
                crow::response res;
                add_cors_headers(res, *ctx);
                // OAuth 2.0 / legacy auth check (read scope for WADO-URI)
                if (ctx->oauth2 && ctx->oauth2->enabled()) {
                    auto auth = ctx->oauth2->authenticate(req, res);
                    if (!auth) return res;
                    if (!ctx->oauth2->require_any_scope(
                            auth->claims, res,
                            {"dicomweb.read"})) {
                        return res;
                    }
                }
                // Validate requestType parameter
                auto request_type = req.url_params.get("requestType");
                if (request_type == nullptr
                    || std::string(request_type) != "WADO") {
                    res.code = 400;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json(
                        "INVALID_REQUEST_TYPE",
                        "requestType must be 'WADO'");
                    return res;
                }
                // Check database availability
                if (!ctx->database) {
                    res.code = 503;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json(
                        "DATABASE_UNAVAILABLE", "Database not configured");
                    return res;
                }
                // Parse and validate parameters
                auto wado_request = wado_uri::parse_wado_uri_params(
                    req.url_params.get("studyUID"),
                    req.url_params.get("seriesUID"),
                    req.url_params.get("objectUID"),
                    req.url_params.get("contentType"),
                    req.url_params.get("transferSyntax"),
                    req.url_params.get("anonymize"),
                    req.url_params.get("rows"),
                    req.url_params.get("columns"),
                    req.url_params.get("windowCenter"),
                    req.url_params.get("windowWidth"),
                    req.url_params.get("frameNumber"));
                auto validation = wado_uri::validate_wado_uri_request(
                    wado_request);
                if (!validation.valid) {
                    res.code = validation.http_status;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json(
                        validation.error_code, validation.error_message);
                    return res;
                }
                // Look up the DICOM instance
                auto file_path_result = ctx->database->get_file_path(
                    wado_request.object_uid);
                if (!file_path_result.is_ok()) {
                    res.code = 500;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json(
                        "QUERY_ERROR", file_path_result.error().message);
                    return res;
                }
                const auto& file_path = file_path_result.value();
                if (!file_path) {
                    res.code = 404;
                    res.add_header("Content-Type", "application/json");
                    res.body = make_error_json(
                        "NOT_FOUND", "DICOM instance not found");
                    return res;
                }
                // Route to appropriate handler based on content type
                if (wado_request.content_type == "application/dicom") {
                    return handle_dicom_response(*file_path, *ctx);
                }
                if (wado_request.content_type == "image/jpeg"
                    || wado_request.content_type == "image/png") {
                    return handle_rendered_response(
                        *file_path, wado_request, *ctx);
                }
                if (wado_request.content_type == "application/dicom+json") {
                    return handle_dicom_json_response(*file_path, *ctx);
                }
                // Should not reach here due to validation, but handle defensively
                res.code = 406;
                res.add_header("Content-Type", "application/json");
                res.body = make_error_json(
                    "UNSUPPORTED_MEDIA_TYPE",
                    "Unsupported contentType: " + wado_request.content_type);
                return res;
            });
}
References kcenon::pacs::web::make_error_json(), kcenon::pacs::web::wado_uri::parse_wado_uri_params(), and kcenon::pacs::web::wado_uri::validate_wado_uri_request().
Referenced by kcenon::pacs::web::rest_server::start_async().
register_worklist_endpoints_impl()
void kcenon::pacs::web::endpoints::register_worklist_endpoints_impl (crow::SimpleApp & app, std::shared_ptr< rest_server_context > ctx)
Definition at line 219 of file worklist_endpoints.cpp.
{
  // GET /api/v1/worklist - List scheduled procedures (paginated)
  CROW_ROUTE(app, "/api/v1/worklist")
      .methods(crow::HTTPMethod::GET)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        if (!ctx->database) {
          res.code = 503;
          res.body =
              make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
          return res;
        }
        // Parse pagination
        auto [limit, offset] = parse_pagination(req);
        // Build query from URL parameters
        storage::worklist_query query;
        query.limit = limit;
        query.offset = offset;
        auto station_ae = req.url_params.get("station_ae");
        if (station_ae) {
          query.station_ae = station_ae;
        }
        auto modality = req.url_params.get("modality");
        if (modality) {
          query.modality = modality;
        }
        auto scheduled_date_from = req.url_params.get("scheduled_date_from");
        if (scheduled_date_from) {
          query.scheduled_date_from = scheduled_date_from;
        }
        auto scheduled_date_to = req.url_params.get("scheduled_date_to");
        if (scheduled_date_to) {
          query.scheduled_date_to = scheduled_date_to;
        }
        auto patient_id = req.url_params.get("patient_id");
        if (patient_id) {
          query.patient_id = patient_id;
        }
        auto patient_name = req.url_params.get("patient_name");
        if (patient_name) {
          query.patient_name = patient_name;
        }
        auto accession_no = req.url_params.get("accession_no");
        if (accession_no) {
          query.accession_no = accession_no;
        }
        auto step_id = req.url_params.get("step_id");
        if (step_id) {
          query.step_id = step_id;
        }
        // Check if we should include all statuses
        auto include_all = req.url_params.get("include_all_status");
        if (include_all && std::string(include_all) == "true") {
          query.include_all_status = true;
        }
        // Get total count (without pagination)
        storage::worklist_query count_query = query;
        count_query.limit = 0;
        count_query.offset = 0;
        auto all_items_result = ctx->database->query_worklist(count_query);
        if (!all_items_result.is_ok()) {
          res.code = 500;
          res.body = make_error_json("QUERY_ERROR",
                                     all_items_result.error().message);
          return res;
        }
        size_t total_count = all_items_result.value().size();
        // Get paginated results
        auto items_result = ctx->database->query_worklist(query);
        if (!items_result.is_ok()) {
          res.code = 500;
          res.body = make_error_json("QUERY_ERROR",
                                     items_result.error().message);
          return res;
        }
        res.code = 200;
        res.body = worklist_items_to_json(items_result.value(), total_count);
        return res;
      });
  // POST /api/v1/worklist - Create worklist item
  CROW_ROUTE(app, "/api/v1/worklist")
      .methods(crow::HTTPMethod::POST)([ctx](const crow::request &req) {
        crow::response res;
        res.add_header("Content-Type", "application/json");
        add_cors_headers(res, *ctx);
        if (!ctx->database) {
          res.code = 503;
          res.body =
              make_error_json("DATABASE_UNAVAILABLE", "Database not configured");
          return res;
        }
        // Parse request body
        auto item = parse_worklist_item_json(req.body);
        if (!item) {
          res.code = 400;
          res.body = make_error_json(
              "INVALID_REQUEST",
              "Missing required fields: step_id, patient_id, modality, "
              "scheduled_datetime");
          return res;
        }
        // Add worklist item
        auto result = ctx->database->add_worklist_item(*item);
        if (result.is_err()) {
          res.code = 500;
          res.body = make_error_json("CREATE_FAILED", result.error().message);
          return res;
        }
        // Fetch the created item to return
        auto created_item = ctx->database->find_worklist_by_pk(result.value());
        if (created_item) {
          res.code = 201;
          res.body = worklist_item_to_json(*created_item);
        } else {
          res.code = 201;
          res.body = make_success_json("Worklist item created");
        }
        return res;
      });
  // GET /api/v1/worklist/:id - Get worklist item by pk
  CROW_ROUTE(app, "/api/v1/worklist/<int>")
      .methods(crow::HTTPMethod::GET)(
          [ctx](const crow::request & /*req*/, int pk) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            auto item = ctx->database->find_worklist_by_pk(pk);
            if (!item) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Worklist item not found");
              return res;
            }
            res.code = 200;
            res.body = worklist_item_to_json(*item);
            return res;
          });
  // PUT /api/v1/worklist/:id - Update worklist item
  CROW_ROUTE(app, "/api/v1/worklist/<int>")
      .methods(crow::HTTPMethod::PUT)(
          [ctx](const crow::request &req, int pk) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            // Verify item exists
            auto existing_item = ctx->database->find_worklist_by_pk(pk);
            if (!existing_item) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Worklist item not found");
              return res;
            }
            // Parse new status from request body
            auto get_json_string = [&req](const std::string &key) -> std::string {
              std::string search_key = "\"" + key + "\":\"";
              auto pos = req.body.find(search_key);
              if (pos == std::string::npos) {
                return "";
              }
              pos += search_key.length();
              auto end_pos = req.body.find("\"", pos);
              if (end_pos == std::string::npos) {
                return "";
              }
              return req.body.substr(pos, end_pos - pos);
            };
            std::string new_status = get_json_string("step_status");
            if (new_status.empty()) {
              res.code = 400;
              res.body = make_error_json("INVALID_REQUEST",
                                         "step_status is required for update");
              return res;
            }
            // Update status
            auto result = ctx->database->update_worklist_status(
                existing_item->step_id,
                existing_item->accession_no,
                new_status);
            if (result.is_err()) {
              res.code = 500;
              res.body = make_error_json("UPDATE_FAILED", result.error().message);
              return res;
            }
            // Fetch updated item
            auto updated_item = ctx->database->find_worklist_by_pk(pk);
            if (updated_item) {
              res.code = 200;
              res.body = worklist_item_to_json(*updated_item);
            } else {
              res.code = 200;
              res.body = make_success_json("Worklist item updated");
            }
            return res;
          });
  // DELETE /api/v1/worklist/:id - Delete worklist item
  CROW_ROUTE(app, "/api/v1/worklist/<int>")
      .methods(crow::HTTPMethod::DELETE)(
          [ctx](const crow::request & /*req*/, int pk) {
            crow::response res;
            res.add_header("Content-Type", "application/json");
            add_cors_headers(res, *ctx);
            if (!ctx->database) {
              res.code = 503;
              res.body = make_error_json("DATABASE_UNAVAILABLE",
                                         "Database not configured");
              return res;
            }
            // Verify item exists
            auto item = ctx->database->find_worklist_by_pk(pk);
            if (!item) {
              res.code = 404;
              res.body = make_error_json("NOT_FOUND", "Worklist item not found");
              return res;
            }
            auto result = ctx->database->delete_worklist_item(
                item->step_id, item->accession_no);
            if (result.is_err()) {
              res.code = 500;
              res.body = make_error_json("DELETE_FAILED", result.error().message);
              return res;
            }
            res.code = 200;
            res.body = make_success_json("Worklist item deleted successfully");
            return res;
          });
}
References kcenon::pacs::storage::worklist_query::limit, kcenon::pacs::web::make_error_json(), kcenon::pacs::web::make_success_json(), and kcenon::pacs::storage::worklist_query::offset.
Referenced by kcenon::pacs::web::rest_server::start_async().