PACS System: kcenon::pacs::web Namespace Reference
kcenon::pacs::web Namespace Reference
Namespaces
namespace auth
namespace dicomweb
namespace endpoints
namespace storage_commitment
namespace wado_uri
Classes
struct api_error
Standard API error structure.
struct frame_info
Multi-frame information.
struct metadata_request
Parameters for selective metadata retrieval.
struct metadata_response
Response for selective metadata retrieval.
class metadata_service
Service for selective metadata retrieval and series navigation.
struct navigation_info
Navigation info for an instance.
class rest_server
REST API server for PACS administration and monitoring.
struct rest_server_config
Configuration options for the REST server.
struct rest_server_context
Shared context for REST endpoints.
struct sorted_instance
Instance info for series navigation.
struct sorted_instances_response
Response for sorted instances query.
struct tag_value
DICOM tag value in metadata response.
struct thumbnail_cache_entry
Cached thumbnail entry.
struct thumbnail_params
Parameters for thumbnail generation.
struct thumbnail_result
Result type for thumbnail operations.
class thumbnail_service
Thumbnail generation and caching service.
struct voi_lut_info
VOI LUT information from DICOM.
struct window_level_preset
Window/Level preset.
Enumerations
enum class metadata_preset {
image_display , window_level , patient_info , acquisition ,
positioning , multiframe
}
Metadata preset types for common use cases.
enum class sort_order { position , instance_number , acquisition_time }
Sort order for series instances.
enum class http_status : std::uint16_t {
ok = 200 , created = 201 , accepted = 202 , no_content = 204 ,
bad_request = 400 , unauthorized = 401 , forbidden = 403 , not_found = 404 ,
method_not_allowed = 405 , conflict = 409 , unprocessable_entity = 422 , internal_server_error = 500 ,
not_implemented = 501 , service_unavailable = 503
}
Common HTTP status codes.
Functions
std::string_view preset_to_string (metadata_preset preset)
Convert preset enum to string.
std::optional< metadata_preset > preset_from_string (std::string_view str)
Parse preset from string.
std::string_view sort_order_to_string (sort_order order)
Convert sort order enum to string.
std::optional< sort_order > sort_order_from_string (std::string_view str)
Parse sort order from string.
std::string to_json (const api_error &error)
Create JSON error response body.
std::string make_error_json (std::string_view code, std::string_view message)
Create JSON error response body with details.
std::string make_success_json (std::string_view message="OK")
Create success response with optional message.
std::string json_escape (std::string_view s)
Escape a string for JSON.
Enumeration Type Documentation
http_status
enum class kcenon::pacs::web::http_status : std::uint16_t strong
Common HTTP status codes.
Enumerator
ok
created
accepted
no_content
bad_request
unauthorized
forbidden
not_found
method_not_allowed
conflict
unprocessable_entity
internal_server_error
not_implemented
service_unavailable
Definition at line 55 of file rest_types.hpp.
                       : std::uint16_t {
  // Success
  ok = 200,
  created = 201,
  accepted = 202,
  no_content = 204,
  // Client errors
  bad_request = 400,
  unauthorized = 401,
  forbidden = 403,
  not_found = 404,
  method_not_allowed = 405,
  conflict = 409,
  unprocessable_entity = 422,
  // Server errors
  internal_server_error = 500,
  not_implemented = 501,
  service_unavailable = 503
};
metadata_preset
enum class kcenon::pacs::web::metadata_preset strong
Metadata preset types for common use cases.
Enumerator
image_display
Rows, Columns, Bits, PhotometricInterpretation.
window_level
WindowCenter, WindowWidth, Rescale values.
patient_info
Patient demographics.
acquisition
KVP, ExposureTime, SliceThickness.
positioning
ImagePosition, ImageOrientation, PixelSpacing.
multiframe
NumberOfFrames, FrameTime.
Definition at line 65 of file metadata_service.hpp.
{
    image_display,
    window_level,
    patient_info,
    acquisition,
    positioning,
    multiframe
};
sort_order
enum class kcenon::pacs::web::sort_order strong
Sort order for series instances.
Enumerator
position
Sort by ImagePositionPatient/SliceLocation.
instance_number
Sort by InstanceNumber.
acquisition_time
Sort by AcquisitionTime.
Definition at line 167 of file metadata_service.hpp.
                      {
    position,
    instance_number,
    acquisition_time
};
Function Documentation
json_escape()
std::string kcenon::pacs::web::json_escape (std::string_view s) inline
Escape a string for JSON.
Parameters
s Input string
Returns
JSON-escaped string
Definition at line 126 of file rest_types.hpp.
{
  std::string result;
  result.reserve(s.size() + 10);
  for (char c : s) {
    switch (c) {
    case '"':
      result += "\\\"";
      break;
    case '\\':
      result += "\\\\";
      break;
    case '\b':
      result += "\\b";
      break;
    case '\f':
      result += "\\f";
      break;
    case '\n':
      result += "\\n";
      break;
    case '\r':
      result += "\\r";
      break;
    case '\t':
      result += "\\t";
      break;
    default:
      result += c;
      break;
    }
  }
  return result;
}
References json_escape().
Referenced by kcenon::pacs::web::dicomweb::dataset_to_dicom_json(), kcenon::pacs::web::dicomweb::instance_record_to_dicom_json(), json_escape(), kcenon::pacs::web::endpoints::register_annotation_endpoints_impl(), kcenon::pacs::web::endpoints::register_jobs_endpoints_impl(), kcenon::pacs::web::endpoints::register_key_image_endpoints_impl(), kcenon::pacs::web::endpoints::register_measurement_endpoints_impl(), kcenon::pacs::web::endpoints::register_remote_nodes_endpoints_impl(), kcenon::pacs::web::endpoints::register_viewer_state_endpoints_impl(), kcenon::pacs::web::dicomweb::series_record_to_dicom_json(), kcenon::pacs::web::dicomweb::study_record_to_dicom_json(), and kcenon::pacs::web::storage_commitment::transaction_to_json().
make_error_json()
std::string kcenon::pacs::web::make_error_json (std::string_view code, std::string_view message) inline
Create JSON error response body with details.
Parameters
code Error code
message Error message
Returns
JSON string
Definition at line 104 of file rest_types.hpp.
{
  return std::string(R"({"error":{"code":")") + std::string(code) +
         R"(","message":")" + std::string(message) + R"("}})";
}
References code, and make_error_json().
Referenced by make_error_json(), kcenon::pacs::web::endpoints::register_annotation_endpoints_impl(), kcenon::pacs::web::endpoints::register_association_endpoints_impl(), kcenon::pacs::web::endpoints::register_audit_endpoints_impl(), kcenon::pacs::web::endpoints::register_dicomweb_endpoints_impl(), kcenon::pacs::web::endpoints::register_jobs_endpoints_impl(), kcenon::pacs::web::endpoints::register_key_image_endpoints_impl(), kcenon::pacs::web::endpoints::register_measurement_endpoints_impl(), kcenon::pacs::web::endpoints::register_metadata_endpoints_impl(), kcenon::pacs::web::endpoints::register_patient_endpoints_impl(), kcenon::pacs::web::endpoints::register_remote_nodes_endpoints_impl(), kcenon::pacs::web::endpoints::register_routing_endpoints_impl(), kcenon::pacs::web::endpoints::register_security_endpoints_impl(), kcenon::pacs::web::endpoints::register_series_endpoints_impl(), kcenon::pacs::web::endpoints::register_storage_commitment_endpoints_impl(), kcenon::pacs::web::endpoints::register_study_endpoints_impl(), kcenon::pacs::web::endpoints::register_system_endpoints_impl(), kcenon::pacs::web::endpoints::register_thumbnail_endpoints_impl(), kcenon::pacs::web::endpoints::register_viewer_state_endpoints_impl(), kcenon::pacs::web::endpoints::register_wado_uri_endpoints_impl(), kcenon::pacs::web::endpoints::register_worklist_endpoints_impl(), kcenon::pacs::web::auth::oauth2_middleware::set_forbidden(), and kcenon::pacs::web::auth::oauth2_middleware::set_unauthorized().
make_success_json()
std::string kcenon::pacs::web::make_success_json (std::string_view message = "OK") inline
Create success response with optional message.
Parameters
message Optional message
Returns
JSON string
Definition at line 116 of file rest_types.hpp.
{
  return std::string(R"({"status":"success","message":")") +
         std::string(message) + R"("})";
}
References make_success_json().
Referenced by make_success_json(), kcenon::pacs::web::endpoints::register_security_endpoints_impl(), kcenon::pacs::web::endpoints::register_study_endpoints_impl(), kcenon::pacs::web::endpoints::register_system_endpoints_impl(), kcenon::pacs::web::endpoints::register_thumbnail_endpoints_impl(), and kcenon::pacs::web::endpoints::register_worklist_endpoints_impl().
preset_from_string()
std::optional< metadata_preset > kcenon::pacs::web::preset_from_string (std::string_view str)
Parse preset from string.
Definition at line 77 of file metadata_service.cpp.
{
    if (str == "image_display") {
        return metadata_preset::image_display;
    }
    if (str == "window_level") {
        return metadata_preset::window_level;
    }
    if (str == "patient_info") {
        return metadata_preset::patient_info;
    }
    if (str == "acquisition") {
        return metadata_preset::acquisition;
    }
    if (str == "positioning") {
        return metadata_preset::positioning;
    }
    if (str == "multiframe") {
        return metadata_preset::multiframe;
    }
    return std::nullopt;
}
References acquisition, image_display, multiframe, patient_info, positioning, and window_level.
preset_to_string()
std::string_view kcenon::pacs::web::preset_to_string (metadata_preset preset)
Convert preset enum to string.
Definition at line 59 of file metadata_service.cpp.
{
    switch (preset) {
        case metadata_preset::image_display:
            return "image_display";
        case metadata_preset::window_level:
            return "window_level";
        case metadata_preset::patient_info:
            return "patient_info";
        case metadata_preset::acquisition:
            return "acquisition";
        case metadata_preset::positioning:
            return "positioning";
        case metadata_preset::multiframe:
            return "multiframe";
    }
    return "unknown";
}
References acquisition, image_display, multiframe, patient_info, positioning, and window_level.
sort_order_from_string()
std::optional< sort_order > kcenon::pacs::web::sort_order_from_string (std::string_view str)
Parse sort order from string.
Definition at line 111 of file metadata_service.cpp.
{
    if (str == "position") {
        return sort_order::position;
    }
    if (str == "instance_number") {
        return sort_order::instance_number;
    }
    if (str == "acquisition_time") {
        return sort_order::acquisition_time;
    }
    return std::nullopt;
}
References acquisition_time, instance_number, and position.
Referenced by kcenon::pacs::web::endpoints::register_metadata_endpoints_impl().
sort_order_to_string()
std::string_view kcenon::pacs::web::sort_order_to_string (sort_order order)
Convert sort order enum to string.
Definition at line 99 of file metadata_service.cpp.
{
    switch (order) {
        case sort_order::position:
            return "position";
        case sort_order::instance_number:
            return "instance_number";
        case sort_order::acquisition_time:
            return "acquisition_time";
    }
    return "unknown";
}
References acquisition_time, instance_number, and position.
to_json()
std::string kcenon::pacs::web::to_json (const api_error & error) inline
Create JSON error response body.
Parameters
error The API error
Returns
JSON string
Definition at line 92 of file rest_types.hpp.
{
  std::string json = R"({"error":{"code":")" + error.code + R"(","message":")" +
                     error.message + R"("})";
  return json;
}