PACS System: examples/pacs_server/main.cpp File Reference
main.cpp File Reference
Entry point for PACS Server sample application.
#include "config.h"
#include "server_app.h"
#include <atomic>
#include <csignal>
#include <iostream>
Functions
int main (int argc, char *argv[])
Detailed Description
Entry point for PACS Server sample application.
Definition in file main.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 57 of file main.cpp.
{
    std::cout << R"(
  ____   _    ____ ____    ____
 |  _ \ / \  / ___/ ___|  / ___|  ___ _ ____   _____ _ __
 | |_) / _ \| |   \___ \  \___ \ / _ \ '__\ \ / / _ \ '__|
 |  __/ ___ \ |___ ___) |  ___) |  __/ |   \ V /  __/ |
 |_| /_/   \_\____|____/  |____/ \___|_|    \_/ \___|_|
                Complete DICOM Archive Server
)" << "\n";
    // Parse command line arguments
    auto config = kcenon::pacs::example::pacs_server_config::parse_args(argc, argv);
    if (!config) {
        return 1;
    }
    // Install signal handlers
    install_signal_handlers();
    // Create and initialize server
    kcenon::pacs::example::pacs_server_app server(config.value());
    g_server = &server;
    if (!server.initialize()) {
        std::cerr << "Failed to initialize PACS server\n";
        return 1;
    }
    // Start server
    if (!server.start()) {
        std::cerr << "Failed to start PACS server\n";
        return 1;
    }
    // Wait for shutdown
    server.wait_for_shutdown();
References kcenon::pacs::example::pacs_server_app::initialize(), kcenon::pacs::example::pacs_server_config::parse_args(), kcenon::pacs::example::pacs_server_app::print_statistics(), kcenon::pacs::example::pacs_server_app::start(), and kcenon::pacs::example::pacs_server_app::wait_for_shutdown().