PACS System: kcenon::pacs::services::mpps_result Struct Reference
kcenon::pacs::services::mpps_result Struct Reference
Result of an MPPS operation.
#include <mpps_scu.h>
Public Member Functions
bool is_success () const noexcept
Check if the operation was successful.
bool is_warning () const noexcept
Check if this was a warning status.
bool is_error () const noexcept
Check if this was an error status.
Public Attributes
std::string mpps_sop_instance_uid
MPPS SOP Instance UID.
uint16_t status {0}
DIMSE status code (0x0000 = success)
std::string error_comment
Error comment from the SCP (if any)
std::chrono::milliseconds elapsed {0}
Time taken for the operation.
Detailed Description
Result of an MPPS operation.
Contains information about the outcome of N-CREATE or N-SET operations.
Definition at line 132 of file mpps_scu.h.
Member Function Documentation
is_error()
bool kcenon::pacs::services::mpps_result::is_error () const inline nodiscard noexcept
Check if this was an error status.
Definition at line 156 of file mpps_scu.h.
{
        return !is_success() && !is_warning();
    }
References is_success(), and is_warning().
is_success()
bool kcenon::pacs::services::mpps_result::is_success () const inline nodiscard noexcept
Check if the operation was successful.
Definition at line 146 of file mpps_scu.h.
{
        return status == 0x0000;
    }
References status.
Referenced by kcenon::pacs::services::mpps_scu::create(), is_error(), and kcenon::pacs::services::mpps_scu::set().
is_warning()
bool kcenon::pacs::services::mpps_result::is_warning () const inline nodiscard noexcept
Check if this was a warning status.
Definition at line 151 of file mpps_scu.h.
{
        return (status & 0xF000) == 0xB000;
    }
References status.
Referenced by is_error().
Member Data Documentation
elapsed
std::chrono::milliseconds kcenon::pacs::services::mpps_result::elapsed {0}
Time taken for the operation.
Definition at line 143 of file mpps_scu.h.
{0};
Referenced by kcenon::pacs::services::mpps_scu::create(), and kcenon::pacs::services::mpps_scu::set().
error_comment
std::string kcenon::pacs::services::mpps_result::error_comment
Error comment from the SCP (if any)
Definition at line 140 of file mpps_scu.h.
Referenced by kcenon::pacs::services::mpps_scu::create(), and kcenon::pacs::services::mpps_scu::set().
mpps_sop_instance_uid
std::string kcenon::pacs::services::mpps_result::mpps_sop_instance_uid
MPPS SOP Instance UID.
Definition at line 134 of file mpps_scu.h.
Referenced by kcenon::pacs::services::mpps_scu::create(), and kcenon::pacs::services::mpps_scu::set().
status
uint16_t kcenon::pacs::services::mpps_result::status {0}
DIMSE status code (0x0000 = success)
Definition at line 137 of file mpps_scu.h.
{0};
Referenced by kcenon::pacs::services::mpps_scu::create(), is_success(), is_warning(), and kcenon::pacs::services::mpps_scu::set().
The documentation for this struct was generated from the following file:
include/kcenon/pacs/services/mpps_scu.h