PACS System: kcenon::pacs::services::n_get_result Struct Reference
kcenon::pacs::services::n_get_result Struct Reference
Result of an N-GET operation.
#include <n_get_scu.hpp>
Public Member Functions
bool is_success () const noexcept
Check if the operation was successful.
bool is_warning () const noexcept
Check if this was a warning status.
bool is_error () const noexcept
Check if this was an error status.
Public Attributes
uint16_t status {0}
DIMSE status code (0x0000 = success)
core::dicom_dataset attributes
Retrieved attributes from the SOP Instance.
std::string error_comment
Error comment from the SCP (if any)
std::chrono::milliseconds elapsed {0}
Time taken for the operation.
Detailed Description
Result of an N-GET operation.
Contains the retrieved attributes and status information.
Definition at line 70 of file n_get_scu.hpp.
Member Function Documentation
is_error()
bool kcenon::pacs::services::n_get_result::is_error () const inline noexcept
Check if this was an error status.
Definition at line 94 of file n_get_scu.hpp.
{
        return !is_success() && !is_warning();
    }
References is_success(), and is_warning().
is_success()
bool kcenon::pacs::services::n_get_result::is_success () const inline noexcept
Check if the operation was successful.
Definition at line 84 of file n_get_scu.hpp.
{
        return status == 0x0000;
    }
References status.
Referenced by kcenon::pacs::services::n_get_scu::get(), and is_error().
is_warning()
bool kcenon::pacs::services::n_get_result::is_warning () const inline noexcept
Check if this was a warning status.
Definition at line 89 of file n_get_scu.hpp.
{
        return (status & 0xF000) == 0xB000;
    }
References status.
Referenced by is_error().
Member Data Documentation
attributes
core::dicom_dataset kcenon::pacs::services::n_get_result::attributes
Retrieved attributes from the SOP Instance.
Definition at line 75 of file n_get_scu.hpp.
Referenced by kcenon::pacs::services::n_get_scu::get().
elapsed
std::chrono::milliseconds kcenon::pacs::services::n_get_result::elapsed {0}
Time taken for the operation.
Definition at line 81 of file n_get_scu.hpp.
{0};
Referenced by kcenon::pacs::services::n_get_scu::get().
error_comment
std::string kcenon::pacs::services::n_get_result::error_comment
Error comment from the SCP (if any)
Definition at line 78 of file n_get_scu.hpp.
Referenced by kcenon::pacs::services::n_get_scu::get().
status
uint16_t kcenon::pacs::services::n_get_result::status {0}
DIMSE status code (0x0000 = success)
Definition at line 72 of file n_get_scu.hpp.
{0};
Referenced by kcenon::pacs::services::n_get_scu::get(), is_success(), and is_warning().
The documentation for this struct was generated from the following file:
include/pacs/services/n_get_scu.hpp