PACS System: kcenon::pacs::encoding::specific_character_set Struct Reference
kcenon::pacs::encoding::specific_character_set Struct Reference
Parsed representation of a multi-valued Specific Character Set.
#include <character_set.hpp>
Public Member Functions
bool uses_extensions () const noexcept
Whether this uses ISO 2022 code extensions.
bool is_single_byte_only () const noexcept
Whether this is a single-byte-only configuration.
bool is_utf8 () const noexcept
Check if UTF-8 is the active character set.
Public Attributes
const character_set_info * default_set
Character set for default (G0) repertoire.
std::vector< const character_set_info * > extension_sets
Additional character sets activated by escape sequences.
Detailed Description
Parsed representation of a multi-valued Specific Character Set.
DICOM Specific Character Set (0008,0005) can be multi-valued with backslash separators. The first value is the default character set for G0, and subsequent values define character sets used via ISO 2022 escape sequences.
Example: "\\ISO 2022 IR 149" means:
Component 0: empty → ASCII (ISO-IR 6) default
Component 1: ISO 2022 IR 149 → Korean
Definition at line 138 of file character_set.hpp.
Member Function Documentation
is_single_byte_only()
bool kcenon::pacs::encoding::specific_character_set::is_single_byte_only () const noexcept
Whether this is a single-byte-only configuration.
Definition at line 480 of file character_set.cpp.
{
    if (default_set && default_set->is_multi_byte) {
        return false;
    }
    for (const auto* cs : extension_sets) {
        if (cs && cs->is_multi_byte) {
            return false;
        }
    }
    return true;
}
References default_set, extension_sets, and kcenon::pacs::encoding::character_set_info::is_multi_byte.
is_utf8()
bool kcenon::pacs::encoding::specific_character_set::is_utf8 () const noexcept
Check if UTF-8 is the active character set.
Definition at line 492 of file character_set.cpp.
{
    return default_set && default_set->defined_term == "ISO_IR 192";
}
References default_set, and kcenon::pacs::encoding::character_set_info::defined_term.
Referenced by kcenon::pacs::encoding::decode_to_utf8(), and kcenon::pacs::encoding::encode_from_utf8().
uses_extensions()
bool kcenon::pacs::encoding::specific_character_set::uses_extensions () const noexcept
Whether this uses ISO 2022 code extensions.
Definition at line 476 of file character_set.cpp.
{
    return !extension_sets.empty();
}
References extension_sets.
Referenced by kcenon::pacs::encoding::decode_to_utf8(), kcenon::pacs::encoding::encode_from_utf8(), and kcenon::pacs::encoding::split_by_escape_sequences().
Member Data Documentation
default_set
const character_set_info* kcenon::pacs::encoding::specific_character_set::default_set
Character set for default (G0) repertoire.
Definition at line 140 of file character_set.hpp.
Referenced by kcenon::pacs::encoding::decode_to_utf8(), kcenon::pacs::encoding::encode_from_utf8(), is_single_byte_only(), is_utf8(), kcenon::pacs::encoding::parse_specific_character_set(), and kcenon::pacs::encoding::split_by_escape_sequences().
extension_sets
std::vector<const character_set_info*> kcenon::pacs::encoding::specific_character_set::extension_sets
Additional character sets activated by escape sequences.
Definition at line 143 of file character_set.hpp.
Referenced by kcenon::pacs::encoding::encode_from_utf8(), is_single_byte_only(), kcenon::pacs::encoding::parse_specific_character_set(), and uses_extensions().
The documentation for this struct was generated from the following files:
include/pacs/encoding/character_set.hpp
src/encoding/character_set.cpp