PACS System: kcenon::pacs::security::tag_action_config Struct Reference
kcenon::pacs::security::tag_action_config Struct Reference
Configuration for a custom tag action.
#include <tag_action.hpp>
Static Public Member Functions
static auto make_remove () -> tag_action_config
Create a remove action config.
static auto make_empty () -> tag_action_config
Create an empty action config.
static auto make_keep () -> tag_action_config
Create a keep action config.
static auto make_replace (std::string value) -> tag_action_config
Create a replace action config with a custom value.
static auto make_hash (std::string algorithm="SHA256", bool salt=true) -> tag_action_config
Create a hash action config.
Public Attributes
tag_action action {tag_action::remove}
The action to perform.
std::string replacement_value
Replacement value (for replace action)
std::string hash_algorithm {"SHA256"}
Hash algorithm (for hash action): "SHA256", "SHA512".
bool use_salt {true}
Whether to include salt in hash.
Detailed Description
Configuration for a custom tag action.
Allows specifying action-specific parameters such as replacement values or hash algorithms.
Definition at line 173 of file tag_action.hpp.
Member Function Documentation
make_empty()
static auto kcenon::pacs::security::tag_action_config::make_empty () -> tag_action_config inline static
Create an empty action config.
Definition at line 196 of file tag_action.hpp.
{
        return {.action = tag_action::empty};
    }
References action, and kcenon::pacs::security::empty.
Referenced by kcenon::pacs::security::anonymizer::get_profile_actions().
make_hash()
static auto kcenon::pacs::security::tag_action_config::make_hash (std::string algorithm = "SHA256", bool salt = true) -> tag_action_config inline static
Create a hash action config.
Parameters
algorithm Hash algorithm to use
salt Whether to use salt
Definition at line 220 of file tag_action.hpp.
{
        return {
            .action = tag_action::hash,
            .hash_algorithm = std::move(algorithm),
            .use_salt = salt
        };
    }
References action, and kcenon::pacs::security::hash.
Referenced by kcenon::pacs::security::anonymizer::get_profile_actions().
make_keep()
static auto kcenon::pacs::security::tag_action_config::make_keep () -> tag_action_config inline static
Create a keep action config.
Definition at line 203 of file tag_action.hpp.
{
        return {.action = tag_action::keep};
    }
References action, and kcenon::pacs::security::keep.
Referenced by kcenon::pacs::security::anonymizer::get_profile_actions(), and kcenon::pacs::security::anonymizer::get_tag_action().
make_remove()
static auto kcenon::pacs::security::tag_action_config::make_remove () -> tag_action_config inline static
Create a remove action config.
Definition at line 189 of file tag_action.hpp.
{
        return {.action = tag_action::remove};
    }
References action, and kcenon::pacs::security::remove.
Referenced by kcenon::pacs::security::anonymizer::get_profile_actions().
make_replace()
static auto kcenon::pacs::security::tag_action_config::make_replace (std::string value) -> tag_action_config inline static
Create a replace action config with a custom value.
Parameters
value The replacement value
Definition at line 211 of file tag_action.hpp.
{
        return {.action = tag_action::replace, .replacement_value = std::move(value)};
    }
References action, and kcenon::pacs::security::replace.
Referenced by kcenon::pacs::security::anonymizer::get_profile_actions().
Member Data Documentation
action
tag_action kcenon::pacs::security::tag_action_config::action {tag_action::remove}
The action to perform.
Definition at line 175 of file tag_action.hpp.
{tag_action::remove};
Referenced by make_empty(), make_hash(), make_keep(), make_remove(), and make_replace().
hash_algorithm
std::string kcenon::pacs::security::tag_action_config::hash_algorithm {"SHA256"}
Hash algorithm (for hash action): "SHA256", "SHA512".
Definition at line 181 of file tag_action.hpp.
{"SHA256"};
replacement_value
std::string kcenon::pacs::security::tag_action_config::replacement_value
Replacement value (for replace action)
Definition at line 178 of file tag_action.hpp.
use_salt
bool kcenon::pacs::security::tag_action_config::use_salt {true}
Whether to include salt in hash.
Definition at line 184 of file tag_action.hpp.
{true};
The documentation for this struct was generated from the following file:
include/pacs/security/tag_action.hpp