PACS System: kcenon::pacs::monitoring::operation_counter Struct Reference
kcenon::pacs::monitoring::operation_counter Struct Reference
Atomic counter for tracking operation success/failure counts.
#include <pacs_metrics.h>
Public Member Functions
std::uint64_t total_count () const noexcept
Get total operation count (success + failure)
std::uint64_t average_duration_us () const noexcept
Get average duration in microseconds (0 if no operations)
void record_success (std::chrono::microseconds duration) noexcept
Record a successful operation with duration.
void record_failure (std::chrono::microseconds duration) noexcept
Record a failed operation with duration.
void reset () noexcept
Reset all counters to zero.
Public Attributes
std::atomic< std::uint64_t > success_count {0}
std::atomic< std::uint64_t > failure_count {0}
std::atomic< std::uint64_t > total_duration_us {0}
Total duration in microseconds.
std::atomic< std::uint64_t > min_duration_us {UINT64_MAX}
std::atomic< std::uint64_t > max_duration_us {0}
Detailed Description
Atomic counter for tracking operation success/failure counts.
Thread-safe counters for tracking the number of successful and failed operations, along with timing statistics.
Definition at line 95 of file pacs_metrics.h.
Member Function Documentation
average_duration_us()
std::uint64_t kcenon::pacs::monitoring::operation_counter::average_duration_us () const inline nodiscard noexcept
Get average duration in microseconds (0 if no operations)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 109 of file pacs_metrics.h.
{
        const auto total = total_count();
        if (total == 0) {
            return 0;
        }
        return total_duration_us.load(std::memory_order_relaxed) / total;
    }
References total_count(), and total_duration_us.
record_failure()
void kcenon::pacs::monitoring::operation_counter::record_failure (std::chrono::microseconds duration) inline noexcept
Record a failed operation with duration.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 140 of file pacs_metrics.h.
{
        failure_count.fetch_add(1, std::memory_order_relaxed);
        const auto duration_us = static_cast<std::uint64_t>(duration.count());
        total_duration_us.fetch_add(duration_us, std::memory_order_relaxed);
        // Update min/max with CAS loops
        auto current_min = min_duration_us.load(std::memory_order_relaxed);
        while (duration_us < current_min &&
               !min_duration_us.compare_exchange_weak(current_min, duration_us,
                                                       std::memory_order_relaxed)) {
        }
        auto current_max = max_duration_us.load(std::memory_order_relaxed);
        while (duration_us > current_max &&
               !max_duration_us.compare_exchange_weak(current_max, duration_us,
                                                       std::memory_order_relaxed)) {
        }
    }
References failure_count, max_duration_us, min_duration_us, and total_duration_us.
Referenced by kcenon::pacs::monitoring::pacs_metrics::record_echo(), kcenon::pacs::monitoring::pacs_metrics::record_get(), kcenon::pacs::monitoring::pacs_metrics::record_move(), kcenon::pacs::monitoring::pacs_metrics::record_query(), and kcenon::pacs::monitoring::pacs_metrics::record_store().
record_success()
void kcenon::pacs::monitoring::operation_counter::record_success (std::chrono::microseconds duration) inline noexcept
Record a successful operation with duration.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 118 of file pacs_metrics.h.
{
        success_count.fetch_add(1, std::memory_order_relaxed);
        const auto duration_us = static_cast<std::uint64_t>(duration.count());
        total_duration_us.fetch_add(duration_us, std::memory_order_relaxed);
        // Update min/max with CAS loops
        auto current_min = min_duration_us.load(std::memory_order_relaxed);
        while (duration_us < current_min &&
               !min_duration_us.compare_exchange_weak(current_min, duration_us,
                                                       std::memory_order_relaxed)) {
            // Loop until successful
        }
        auto current_max = max_duration_us.load(std::memory_order_relaxed);
        while (duration_us > current_max &&
               !max_duration_us.compare_exchange_weak(current_max, duration_us,
                                                       std::memory_order_relaxed)) {
            // Loop until successful
        }
    }
References max_duration_us, min_duration_us, success_count, and total_duration_us.
Referenced by kcenon::pacs::monitoring::pacs_metrics::record_echo(), kcenon::pacs::monitoring::pacs_metrics::record_get(), kcenon::pacs::monitoring::pacs_metrics::record_move(), kcenon::pacs::monitoring::pacs_metrics::record_query(), and kcenon::pacs::monitoring::pacs_metrics::record_store().
reset()
void kcenon::pacs::monitoring::operation_counter::reset () inline noexcept
Reset all counters to zero.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 160 of file pacs_metrics.h.
{
        success_count.store(0, std::memory_order_relaxed);
        failure_count.store(0, std::memory_order_relaxed);
        total_duration_us.store(0, std::memory_order_relaxed);
        min_duration_us.store(UINT64_MAX, std::memory_order_relaxed);
        max_duration_us.store(0, std::memory_order_relaxed);
    }
References failure_count, max_duration_us, min_duration_us, success_count, and total_duration_us.
Referenced by kcenon::pacs::monitoring::pacs_metrics::reset().
total_count()
std::uint64_t kcenon::pacs::monitoring::operation_counter::total_count () const inline nodiscard noexcept
Get total operation count (success + failure)
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 103 of file pacs_metrics.h.
{
        return success_count.load(std::memory_order_relaxed) +
               failure_count.load(std::memory_order_relaxed);
    }
References failure_count, and success_count.
Referenced by average_duration_us().
Member Data Documentation
failure_count
std::atomic<std::uint64_t> kcenon::pacs::monitoring::operation_counter::failure_count {0}
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 97 of file pacs_metrics.h.
{0};
Referenced by record_failure(), reset(), and total_count().
max_duration_us
std::atomic<std::uint64_t> kcenon::pacs::monitoring::operation_counter::max_duration_us {0}
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 100 of file pacs_metrics.h.
{0};
Referenced by record_failure(), record_success(), and reset().
min_duration_us
std::atomic<std::uint64_t> kcenon::pacs::monitoring::operation_counter::min_duration_us {UINT64_MAX}
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 99 of file pacs_metrics.h.
{UINT64_MAX};
Referenced by record_failure(), record_success(), and reset().
success_count
std::atomic<std::uint64_t> kcenon::pacs::monitoring::operation_counter::success_count {0}
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 96 of file pacs_metrics.h.
{0};
Referenced by record_success(), reset(), and total_count().
total_duration_us
std::atomic<std::uint64_t> kcenon::pacs::monitoring::operation_counter::total_duration_us {0}
Total duration in microseconds.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 98 of file pacs_metrics.h.
{0};
Referenced by average_duration_us(), record_failure(), record_success(), and reset().
The documentation for this struct was generated from the following file:
include/kcenon/pacs/monitoring/pacs_metrics.h