PACS System: kcenon::pacs::monitoring::data_transfer_metrics Struct Reference
kcenon::pacs::monitoring::data_transfer_metrics Struct Reference
Metrics for tracking data transfer volumes.
#include <pacs_metrics.h>
Public Member Functions
void add_bytes_sent (std::uint64_t bytes) noexcept
Record bytes sent.
void add_bytes_received (std::uint64_t bytes) noexcept
Record bytes received.
void increment_images_stored () noexcept
Record an image stored.
void increment_images_retrieved () noexcept
Record an image retrieved.
void reset () noexcept
Reset all counters to zero.
Public Attributes
std::atomic< std::uint64_t > bytes_sent {0}
std::atomic< std::uint64_t > bytes_received {0}
std::atomic< std::uint64_t > images_stored {0}
std::atomic< std::uint64_t > images_retrieved {0}
Detailed Description
Metrics for tracking data transfer volumes.
Thread-safe counters for tracking bytes sent/received and image counts.
Definition at line 175 of file pacs_metrics.h.
Member Function Documentation
add_bytes_received()
void kcenon::pacs::monitoring::data_transfer_metrics::add_bytes_received (std::uint64_t bytes) inline noexcept
Record bytes received.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 187 of file pacs_metrics.h.
{
        bytes_received.fetch_add(bytes, std::memory_order_relaxed);
    }
References bytes_received.
Referenced by kcenon::pacs::monitoring::pacs_metrics::record_bytes_received(), and kcenon::pacs::monitoring::pacs_metrics::record_store().
add_bytes_sent()
void kcenon::pacs::monitoring::data_transfer_metrics::add_bytes_sent (std::uint64_t bytes) inline noexcept
Record bytes sent.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 182 of file pacs_metrics.h.
{
        bytes_sent.fetch_add(bytes, std::memory_order_relaxed);
    }
References bytes_sent.
Referenced by kcenon::pacs::monitoring::pacs_metrics::record_bytes_sent(), and kcenon::pacs::monitoring::pacs_metrics::record_get().
increment_images_retrieved()
void kcenon::pacs::monitoring::data_transfer_metrics::increment_images_retrieved () inline noexcept
Record an image retrieved.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 197 of file pacs_metrics.h.
{
        images_retrieved.fetch_add(1, std::memory_order_relaxed);
    }
References images_retrieved.
Referenced by kcenon::pacs::monitoring::pacs_metrics::record_get(), and kcenon::pacs::monitoring::pacs_metrics::record_move().
increment_images_stored()
void kcenon::pacs::monitoring::data_transfer_metrics::increment_images_stored () inline noexcept
Record an image stored.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 192 of file pacs_metrics.h.
{
        images_stored.fetch_add(1, std::memory_order_relaxed);
    }
References images_stored.
Referenced by kcenon::pacs::monitoring::pacs_metrics::record_store().
reset()
void kcenon::pacs::monitoring::data_transfer_metrics::reset () inline noexcept
Reset all counters to zero.
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 202 of file pacs_metrics.h.
{
        bytes_sent.store(0, std::memory_order_relaxed);
        bytes_received.store(0, std::memory_order_relaxed);
        images_stored.store(0, std::memory_order_relaxed);
        images_retrieved.store(0, std::memory_order_relaxed);
    }
References bytes_received, bytes_sent, images_retrieved, and images_stored.
Referenced by kcenon::pacs::monitoring::pacs_metrics::reset().
Member Data Documentation
bytes_received
std::atomic<std::uint64_t> kcenon::pacs::monitoring::data_transfer_metrics::bytes_received {0}
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 177 of file pacs_metrics.h.
{0};
Referenced by add_bytes_received(), reset(), kcenon::pacs::monitoring::pacs_metrics::to_json(), and kcenon::pacs::monitoring::pacs_metrics::to_prometheus().
bytes_sent
std::atomic<std::uint64_t> kcenon::pacs::monitoring::data_transfer_metrics::bytes_sent {0}
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 176 of file pacs_metrics.h.
{0};
Referenced by add_bytes_sent(), reset(), kcenon::pacs::monitoring::pacs_metrics::to_json(), and kcenon::pacs::monitoring::pacs_metrics::to_prometheus().
images_retrieved
std::atomic<std::uint64_t> kcenon::pacs::monitoring::data_transfer_metrics::images_retrieved {0}
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 179 of file pacs_metrics.h.
{0};
Referenced by increment_images_retrieved(), reset(), kcenon::pacs::monitoring::pacs_metrics::to_json(), and kcenon::pacs::monitoring::pacs_metrics::to_prometheus().
images_stored
std::atomic<std::uint64_t> kcenon::pacs::monitoring::data_transfer_metrics::images_stored {0}
Examples
/home/runner/work/pacs_system/pacs_system/include/kcenon/pacs/monitoring/pacs_metrics.h.
Definition at line 178 of file pacs_metrics.h.
{0};
Referenced by increment_images_stored(), reset(), kcenon::pacs::monitoring::pacs_metrics::to_json(), and kcenon::pacs::monitoring::pacs_metrics::to_prometheus().
The documentation for this struct was generated from the following file:
include/kcenon/pacs/monitoring/pacs_metrics.h