PACS System: kcenon::pacs::services::store_result Struct Reference
kcenon::pacs::services::store_result Struct Reference
Result of a C-STORE operation.
#include <storage_scu.h>
Public Member Functions
bool is_success () const noexcept
Check if the store operation was successful.
bool is_warning () const noexcept
Check if this was a warning status.
bool is_error () const noexcept
Check if this was an error status.
Public Attributes
std::string sop_instance_uid
SOP Instance UID of the stored instance.
uint16_t status {0}
DIMSE status code (0x0000 = success)
std::string error_comment
Error comment from the SCP (if any)
Detailed Description
Result of a C-STORE operation.
Contains information about the outcome of storing a single DICOM instance.
Examples
store_scu/main.cpp.
Definition at line 43 of file storage_scu.h.
Member Function Documentation
is_error()
bool kcenon::pacs::services::store_result::is_error () const inline nodiscard noexcept
Check if this was an error status.
Definition at line 64 of file storage_scu.h.
{
        return !is_success() && !is_warning();
    }
References is_success(), and is_warning().
is_success()
bool kcenon::pacs::services::store_result::is_success () const inline nodiscard noexcept
Check if the store operation was successful.
Examples
store_scu/main.cpp.
Definition at line 54 of file storage_scu.h.
{
        return status == 0x0000;
    }
References status.
Referenced by is_error(), kcenon::pacs::services::storage_scu::store_impl(), TEST_CASE(), and TEST_CASE().
is_warning()
bool kcenon::pacs::services::store_result::is_warning () const inline nodiscard noexcept
Check if this was a warning status.
Examples
store_scu/main.cpp.
Definition at line 59 of file storage_scu.h.
{
        return (status & 0xF000) == 0xB000;
    }
References status.
Referenced by is_error(), and kcenon::pacs::services::storage_scu::store_impl().
Member Data Documentation
error_comment
std::string kcenon::pacs::services::store_result::error_comment
Error comment from the SCP (if any)
Examples
store_scu/main.cpp.
Definition at line 51 of file storage_scu.h.
Referenced by kcenon::pacs::services::storage_scu::store_batch(), kcenon::pacs::services::storage_scu::store_files(), and kcenon::pacs::services::storage_scu::store_impl().
sop_instance_uid
std::string kcenon::pacs::services::store_result::sop_instance_uid
SOP Instance UID of the stored instance.
Examples
store_scu/main.cpp.
Definition at line 45 of file storage_scu.h.
Referenced by kcenon::pacs::services::storage_scu::store_batch(), kcenon::pacs::services::storage_scu::store_files(), and kcenon::pacs::services::storage_scu::store_impl().
status
uint16_t kcenon::pacs::services::store_result::status {0}
DIMSE status code (0x0000 = success)
Examples
store_scu/main.cpp.
Definition at line 48 of file storage_scu.h.
{0};
Referenced by is_success(), is_warning(), kcenon::pacs::services::storage_scu::store_batch(), kcenon::pacs::services::storage_scu::store_files(), and kcenon::pacs::services::storage_scu::store_impl().
The documentation for this struct was generated from the following file:
include/kcenon/pacs/services/storage_scu.h