PACS System: kcenon::pacs::web::thumbnail_result Struct Reference
kcenon::pacs::web::thumbnail_result Struct Reference
Result type for thumbnail operations.
#include <thumbnail_service.hpp>
Static Public Member Functions
static thumbnail_result ok (thumbnail_cache_entry entry)
Create a success result.
static thumbnail_result error (std::string message)
Create an error result.
Public Attributes
bool success {false}
Whether the operation succeeded.
std::string error_message
Error message if failed.
thumbnail_cache_entry entry
Thumbnail data if succeeded.
Detailed Description
Result type for thumbnail operations.
Definition at line 101 of file thumbnail_service.hpp.
Member Function Documentation
error()
static thumbnail_result kcenon::pacs::web::thumbnail_result::error (std::string message) inline static
Create an error result.
Definition at line 120 of file thumbnail_service.hpp.
{
        thumbnail_result r;
        r.success = false;
        r.error_message = std::move(message);
        return r;
    }
References error_message, and success.
Referenced by kcenon::pacs::web::thumbnail_service::get_series_thumbnail(), kcenon::pacs::web::thumbnail_service::get_study_thumbnail(), and kcenon::pacs::web::thumbnail_service::get_thumbnail().
ok()
static thumbnail_result kcenon::pacs::web::thumbnail_result::ok (thumbnail_cache_entry entry) inline static
Create a success result.
Definition at line 112 of file thumbnail_service.hpp.
{
        thumbnail_result r;
        r.success = true;
        r.entry = std::move(entry);
        return r;
    }
References entry, and success.
Referenced by kcenon::pacs::web::thumbnail_service::get_thumbnail().
Member Data Documentation
entry
thumbnail_cache_entry kcenon::pacs::web::thumbnail_result::entry
Thumbnail data if succeeded.
Definition at line 109 of file thumbnail_service.hpp.
Referenced by ok().
error_message
std::string kcenon::pacs::web::thumbnail_result::error_message
Error message if failed.
Definition at line 106 of file thumbnail_service.hpp.
Referenced by error().
success
bool kcenon::pacs::web::thumbnail_result::success {false}
Whether the operation succeeded.
Definition at line 103 of file thumbnail_service.hpp.
{false};
Referenced by error(), and ok().
The documentation for this struct was generated from the following file:
include/pacs/web/thumbnail_service.hpp