PACS System: examples/integration_tests/test_xa_storage.cpp File Reference
test_xa_storage.cpp File Reference
Integration tests for XA Storage SOP Classes.
#include "test_fixtures.h"
#include "kcenon/pacs/storage/file_storage.h"
#include <catch2/catch_test_macros.hpp>
#include <iostream>
Functions
TEST_CASE ("XA Storage Integration", "[integration][xa][storage]")
Variables
constexpr dicom_tag number_of_frames {0x0028, 0x0008}
Detailed Description
Integration tests for XA Storage SOP Classes.
Verifies XA Image Storage, Enhanced XA, and related workflows. Covers Issue #135 scenarios.
Definition in file test_xa_storage.cpp.
Function Documentation
TEST_CASE()
TEST_CASE ("XA Storage Integration" , "" [integration][xa][storage])
Definition at line 102 of file test_xa_storage.cpp.
{
    // Setup test environment
    auto port = find_available_port();
    xa_pacs_server server(port, "XA_SCP");
    REQUIRE(server.initialize());
    REQUIRE(server.start());
    SECTION("Scenario 1: Basic XA Storage") {
        // Create XA dataset
        auto ds = generate_xa_dataset();
        auto instance_uid = ds.get_string(tags::sop_instance_uid);
        // Connect and store
        auto assoc_result = test_association::connect(
            "127.0.0.1", port, "XA_SCP", "TEST_SCU",
            {"1.2.840.10008.5.1.4.1.1.12.1", "1.2.840.10008.1.1"});
        REQUIRE(assoc_result.is_ok());
        auto association = std::move(assoc_result.value());
        // Verify connection with C-ECHO
        auto context_id_opt = association.accepted_context_id(verification_sop_class_uid);
        if (!context_id_opt) {
            // Known issue: Global negotiation failure
            WARN("Verification SOP Class not accepted (Global Issue)");
        } else {
            auto echo_rq = make_c_echo_rq(1, verification_sop_class_uid);
            auto send_result = association.send_dimse(*context_id_opt, echo_rq);
            CHECK(send_result.is_ok());
            auto recv_result = association.receive_dimse(std::chrono::seconds{5});
            CHECK(recv_result.is_ok());
        }
        storage_scu scu;
        auto store_result = scu.store(association, ds);
        if (store_result.is_err()) {
            FAIL("Store failed: " << store_result.error().message);
        }
        CHECK(store_result.value().is_success()); // Success
        // Verify file exists
        auto stored_path = server.storage_path() / (instance_uid + ".dcm");
        CHECK(std::filesystem::exists(stored_path));
        // Release association
        [[maybe_unused]] auto release_result = association.release();
    }
    SECTION("Scenario 2: XA IOD Validation") {
        // Valid dataset
        auto valid_ds = generate_xa_dataset();
        // Connect
        auto assoc_result = test_association::connect(
            "127.0.0.1", port, "XA_SCP", "TEST_SCU",
            {"1.2.840.10008.5.1.4.1.1.12.1"});
        REQUIRE(assoc_result.is_ok());
        auto association = std::move(assoc_result.value());
        // Store valid
        storage_scu scu;
        auto result_valid = scu.store(association, valid_ds);
        if (result_valid.is_err()) {
            FAIL("Store valid failed: " << result_valid.error().message);
        }
        CHECK(result_valid.value().is_success());
        // Release association
        [[maybe_unused]] auto release_result = association.release();
        // TODO: Implement invalid dataset test once dataset API is confirmed.
    }
    SECTION("Scenario 3: Multi-frame XA Storage") {
        auto ds = generate_xa_dataset();
        ds.set_string(number_of_frames, vr_type::IS, "10");
        // Update pixel data for 10 frames
        std::vector<uint16_t> pixel_data(512 * 512 * 10, 128);
        ds.insert(dicom_element(tags::pixel_data, vr_type::OW,
            std::span<const uint8_t>(reinterpret_cast<const uint8_t*>(pixel_data.data()), pixel_data.size() * sizeof(uint16_t))));
        auto assoc_result = test_association::connect(
            "127.0.0.1", port, "XA_SCP", "TEST_SCU",
            {"1.2.840.10008.5.1.4.1.1.12.1"});
        REQUIRE(assoc_result.is_ok());
        auto association = std::move(assoc_result.value());
        storage_scu scu;
        auto result = scu.store(association, ds);
        if (result.is_err()) {
            FAIL("Multi-frame store failed: " << result.error().message);
        }
        CHECK(result.value().is_success());
        // Release association
        [[maybe_unused]] auto release_result = association.release();
    }
    SECTION("Scenario 4: XA Specific Attributes") {
        auto ds = generate_xa_dataset();
        // Verify we can set/get XA specific tags
        auto assoc_result = test_association::connect(
            "127.0.0.1", port, "XA_SCP", "TEST_SCU",
            {"1.2.840.10008.5.1.4.1.1.12.1"});
        REQUIRE(assoc_result.is_ok());
        auto association = std::move(assoc_result.value());
        storage_scu scu;
        auto result = scu.store(association, ds);
        if (result.is_err()) {
            FAIL("XA attributes store failed: " << result.error().message);
        }
        CHECK(result.value().is_success());
        // Release association
        [[maybe_unused]] auto release_result = association.release();
    }
    // Stop server explicitly
    server.stop();
}
References kcenon::pacs::network::association::accepted_context_id(), kcenon::pacs::integration_test::test_association::connect(), kcenon::pacs::integration_test::find_available_port(), kcenon::pacs::integration_test::generate_xa_dataset(), kcenon::pacs::services::store_result::is_success(), kcenon::pacs::network::dimse::make_c_echo_rq(), number_of_frames, kcenon::pacs::network::association::receive_dimse(), kcenon::pacs::network::association::release(), kcenon::pacs::network::association::send_dimse(), kcenon::pacs::services::storage_scu::store(), and kcenon::pacs::services::verification_sop_class_uid.
Variable Documentation
number_of_frames
dicom_tag number_of_frames {0x0028, 0x0008} constexpr
Definition at line 23 of file test_xa_storage.cpp.
{0x0028, 0x0008};
Referenced by kcenon::pacs::integration_test::test_data_generator::add_multiframe_pixel_data(), kcenon::pacs::integration_test::TEST_CASE(), kcenon::pacs::integration_test::TEST_CASE(), kcenon::pacs::integration_test::TEST_CASE(), kcenon::pacs::integration_test::TEST_CASE(), TEST_CASE(), and kcenon::pacs::services::validation::us_iod_validator::validate_multiframe_module().