##################################################
# Build Summary
##################################################

message(STATUS "")
message(STATUS "========================================")
message(STATUS "PACS System v${PROJECT_VERSION}")
message(STATUS "========================================")
message(STATUS "")
message(STATUS "Dependency Chain (Tier 5):")
message(STATUS "  pacs_system")
if(COMMON_SYSTEM_FOUND)
    message(STATUS "    ├── common_system (Tier 0): ON")
else()
    message(STATUS "    ├── common_system (Tier 0): OFF")
endif()
if(TARGET container_system)
    message(STATUS "    ├── container_system (Tier 1): ON")
else()
    message(STATUS "    ├── container_system (Tier 1): OFF")
endif()
if(TARGET network_system)
    message(STATUS "    └── network_system (Tier 4): ON")
    message(STATUS "          ├── logger_system (Tier 2): [AUTO]")
    message(STATUS "          │     └── thread_system (Tier 1): [AUTO]")
    message(STATUS "          └── monitoring_system (Tier 3): [OPTIONAL]")
else()
    message(STATUS "    └── network_system (Tier 4): OFF")
endif()
message(STATUS "")
message(STATUS "Build Options:")
message(STATUS "  Tests: ${PACS_BUILD_TESTS}")
if(PACS_BUILD_EXAMPLES AND TARGET pacs_server)
    message(STATUS "  Examples: ON (pacs_server)")
else()
    message(STATUS "  Examples: ${PACS_BUILD_EXAMPLES}")
endif()
message(STATUS "  Benchmarks: ${PACS_BUILD_BENCHMARKS}")
message(STATUS "  Samples: ${PACS_BUILD_SAMPLES}")
message(STATUS "  Services: ON")
if(TARGET pacs_storage)
    message(STATUS "  Storage: ON (SQLite3)")
else()
    message(STATUS "  Storage: OFF")
endif()
if(TARGET pacs_integration)
    message(STATUS "  Integration: ON (container_system)")
else()
    message(STATUS "  Integration: OFF")
endif()
message(STATUS "========================================")
